### PR TITLE
[No squash] Corrections to entity and node light calculation

### LINKED ISSUE #12686: 5.6 changed object glow drastically
##### Minetest version
```
5.6
```

##### Summary
image

##### Steps to reproduce
Look at a glowing dropped item (like a MTG meselamp) with both 5.5.1 and 5.6, see the difference.

### PR DESCRIPTION
**Pull request by x2048**
This PR fixes two things:
1. When smooth light is disabled, makes visible brightness of nodebox and other draw types the same as NDT_SOLID at the same light level:
image
2. Corrects computation of brightness for entity `glow` property to work on the light levels (0..LIGHT_MAX):
  a. Glow is added to the map light level at the node position, before converting to the color space
  b. Additional brightness is added at the final stage in the same was as for light sources

The reason for a single PR is that light calculation for both scenarios is based on [getInteriorLight](https://github.com/minetest/minetest/blob/a8711158896d993e23d823f41ab086c3915c7d4e/src/client/mapblock_mesh.cpp#L102) function

Fixes #12686 in a formally correct way.

## To do

This PR is Ready for Review.

## How to test

In devtest:
Test 1:
1. Throw various light sources on the ground in a dark place.
2. Brightness of the item entities must reflect the light source level

Note, depending on your hardware, dim light sources (1-3) may not be visible in full darkness.

Test 2:

1. Place arrays of sandstone, sandstone slab and sandstone stairs in sunlight and check that the brightness level is the same
2. Place arrays of sandstone, sandstone slab and sandstone stairs near an array of light sources as show below:
image
3. Brightness of stairs and slabs must be exactly one level higher than on solid nodes. This is because solid nodes use light levels of the air nodes above them, which are 1 manhattan unit further away from the light source (as displayed above).

### CODE REVIEW

File: src/client/content_cao.cpp [hunk 1]
```diff
@@ -881,7 +881,7 @@ void GenericCAO::updateLight(u32 day_night_ratio)
 	if (!pos_ok)
 		light_at_pos = LIGHT_SUN;
 
-	video::SColor light = encode_light(light_at_pos, decode_light(m_prop.glow));
+	video::SColor light = encode_light(light_at_pos, m_prop.glow);
```
Comment (SmallJoker) [inline src/client/content_cao.cpp:884]: `glow` is a value between [0, LIGHT_SUN] but `encode_light` treats the increment parameter as a value between [0, 255] for the effective brightness, hence the `decode_light` call here was more correct than the current code.

**Comment by Zughy** [comment]
@x2048 rebase needed

File: src/client/content_cao.cpp (hunk 1 above)
Comment (x2048) [reply src/client/content_cao.cpp:884]: I have added comments explaining how glow is used now:
* Glow now impacts light level of the entity in the getInteriorLight call
* A small boost is added to the final color to make entities brighter at the same light level

**Review by SmallJoker — APPROVED** [review]
LGTM
