### PR TITLE
Use "Aux" key name consistently

### LINKED ISSUE #7600: Inconsistent name of “Use” / “Aux1” / “AUX” / “special1” key
##### Issue type
 - Bug report
 
##### Minetest version
0.5.0-dev

PC version and Android version.

##### Summary
The naming of the control referered to by the control setting `keymap_special1` is inconsistent in player-facing interfaces. The following names are used all for the same control:

* Special (PC version 5.0.0-dev, controls settings menu)
* AUX (Android version, GUI)
* aux1 (`minetest.conf` → `aux1_descends`)
* special1 (`minetest.conf` → `keymap_special1`)
* “Key for moving fast in fast mode” (`README.md`, `minetest.conf.example`)

Note I include `minetest.conf` and `minetest.conf.example` as “player-facing” since this is a configuration file, not a programmer's file.

Yes, we had this debate about the name of this key before, but can we AT LEAST agree to stick to ONE name and use it consistently everywhere? ;-)

Also note the description “Key for moving fast in fast mode” is only half-true. This key could also be used to descend if `aux1_descends` is true. Plus this key is sometimes used in mods (especially for sprinting it's popular), but I don't think this needs mentioning.

#### Solution

1. Pick ONE name for the control and stick to it (ideally case-sensitively).
2. Make sure the change is reflected in Minetest everywhere. Places which need to be touched:
    * `README.md`
    * `minetest.conf`
    * `minetest.conf.example`
    * `src/guiKeyChangeMenu.cpp`
    * The Android image for the button of this control (why is this not a real icon, anyway?)
    * Minetest Wiki
    * \<insert other places here\>

### PR DESCRIPTION
**Pull request by Wuzzy2**
Fixes #7600.

This changes the inconsistent naming of the key “Aux1”/“aux”/“Aux”/“Special”/“special1”/“Use”.

In player-facing, this key is now called “Aux” everywhere.

Internal names are also changed. Internally, this is now referered to as “aux”, “AUX”, “aux1” or “AUX1”. The “1” is preserved for historical reasons only.
This also changes the setting `keymap_special` to `keymap_aux1`. So players might need to reconfigure this key after updating. It's a minor inconvenience, but not a bug.

Name “Aux” (with capital “A”) picked per core dev consensus in #7600 and elsewhere.

## To do

This PR is Ready for Review.

## How to test

Compile and run.
Look in controls.
Check out updated settings.
Read source code to spot weirdnesses.

### CODE REVIEW

**Comment by Wuzzy2** [comment]
> Internal names are also changed. Internally, this is now referered to as “aux”, “AUX”, “aux1” or “AUX1”. The “1” is preserved for historical reasons only.

Correction: Internally, only the names “aux1” or “AUX1” are used.

File: src/defaultsettings.cpp [hunk 1]
```diff
@@ -76,7 +76,7 @@ void set_default_settings(Settings *settings)
 	settings->setDefault("keymap_drop", "KEY_KEY_Q");
 	settings->setDefault("keymap_zoom", "KEY_KEY_Z");
 	settings->setDefault("keymap_inventory", "KEY_KEY_I");
-	settings->setDefault("keymap_special1", "KEY_KEY_E");
+	settings->setDefault("keymap_aux1", "KEY_KEY_E");
```
Comment (paramat) [inline src/defaultsettings.cpp]: "keymap_aux1" is a user-facing setting so should be 'aux'.

File: builtin/settingtypes.txt [hunk 2]
```diff
@@ -188,7 +188,7 @@ keymap_inventory (Inventory key) key KEY_KEY_I
 
 #    Key for moving fast in fast mode.
 #    See http://irrlicht.sourceforge.net/docu/namespaceirr.html#a54da2a0e231901735e3da1b0edf72eb3
-keymap_special1 (Special key) key KEY_KEY_E
+keymap_aux1 (Aux key) key KEY_KEY_E
```
Comment (paramat) [inline builtin/settingtypes.txt]: "keymap_aux1" is a user-facing setting so should be "keymap_aux".

File: src/client/inputhandler.cpp [hunk 3]
```diff
@@ -35,7 +35,7 @@ void KeyCache::populate()
 	key[KeyType::LEFT] = getKeySetting("keymap_left");
 	key[KeyType::RIGHT] = getKeySetting("keymap_right");
 	key[KeyType::JUMP] = getKeySetting("keymap_jump");
-	key[KeyType::SPECIAL1] = getKeySetting("keymap_special1");
+	key[KeyType::AUX1] = getKeySetting("keymap_aux1");
```
Comment (paramat) [inline src/client/inputhandler.cpp]: "keymap_aux1" is a user-facing setting so should be "keymap_aux".

File: src/client/inputhandler.cpp [hunk 4]
```diff
@@ -203,7 +203,7 @@ void RandomInputHandler::step(float dtime)
 		counter1 -= dtime;
 		if (counter1 < 0.0) {
 			counter1 = 0.1 * Rand(1, 40);
-			keydown.toggle(getKeySetting("keymap_special1"));
+			keydown.toggle(getKeySetting("keymap_aux1"));
```
Comment (paramat) [inline src/client/inputhandler.cpp]: "keymap_aux1" is a user-facing setting so should be "keymap_aux".

File: src/gui/guiKeyChangeMenu.cpp [hunk 5]
```diff
@@ -414,7 +414,7 @@ void GUIKeyChangeMenu::init_keys()
 	this->add_key(GUI_ID_KEY_BACKWARD_BUTTON,  wgettext("Backward"),         "keymap_backward");
 	this->add_key(GUI_ID_KEY_LEFT_BUTTON,      wgettext("Left"),             "keymap_left");
 	this->add_key(GUI_ID_KEY_RIGHT_BUTTON,     wgettext("Right"),            "keymap_right");
-	this->add_key(GUI_ID_KEY_USE_BUTTON,       wgettext("Special"),          "keymap_special1");
+	this->add_key(GUI_ID_KEY_USE_BUTTON,       wgettext("Aux"),              "keymap_aux1");
```
Comment (paramat) [inline src/gui/guiKeyChangeMenu.cpp]: "keymap_aux1" is a user-facing setting so should be "keymap_aux".

**Comment by paramat** [comment]
Nice, at last =)
Keeping the '1' internally makes sense as we might add 'aux2' etc.

**Comment by Wuzzy2** [comment]
I'm not sure if I want to use `keymap_aux1` or `keymap_aux`, tbh …
There's also a setting called “aux1_descends” which I didn't touch in this PR.

I'm waiting for other core dev opinions before I proceed because it's not clear what the consensus will be.

I'm neutral.

**Comment by paramat** [comment]
Ahh ... i think 'aux1_descends' needs to be changed in this PR, as it is user-facing too, and will now be inconsistent.
Users may need to alter some settings but i think it is worth the disruption to get everything sorted out in one go.
I am thinking perhaps internally 'aux' and 'AUX' should be used, dropping the '1'. It will be consistent with settings and clearer for development work. If we later add more auxilary keys those could then be aux2 etc.

**Comment by SmallJoker** [comment]
I'd say let's keep it `aux1` in case there will be more special/auxiliary keys for modders.

File: src/client/inputhandler.cpp (hunk 3 above)
Comment (SmallJoker) [inline src/client/inputhandler.cpp]: Needs backwards compatibility in case `keymap_special1` is found inside `minetest.conf`, but `keymap_aux1` isn't.

**Comment by Wuzzy2** [comment]
Now we have a problem ... Two core devs are disagreeing.

> Users may need to alter some settings but i think it is worth the disruption to get everything sorted out in one go.

> Needs backwards compatibility in case keymap_special1 is found inside minetest.conf, but keymap_aux1 isn't.

**Comment by paramat** [comment]
@SmallJoker , 'aux1' everywhere or just internally? I prefer internal is identical to user-facing, whichever of 'aux' or 'aux1' we use.

File: src/client/inputhandler.cpp (hunk 3 above)
Comment (paramat) [reply src/client/inputhandler.cpp]: If we are too afraid of tiny settings compatibility changes we will never clean up this code. Please, lets sort this out forever in one go, a tiny bit of temporary inconvenience to players is well worth it.
Keeping compatibility here will also confuse players because there will be differing terminology for 'aux' in user-facing settings. The whole point of this PR is to fix that.

**Comment by paramat** [comment]
To be clear, i will disapprove this PR if it does not make all user-facing settings use the same word ('aux' or 'aux1'), the whole point of this PR is to clean up this mess, backwards compatibility for all settings is impossible and a very minor issue.

File: src/client/inputhandler.cpp (hunk 3 above)
Comment (paramat) [reply src/client/inputhandler.cpp]: Wuzzy2, there probably is not conflict because i think SmallJoker means add code to accept either terminology.

**Comment by SmallJoker** [comment]
> @SmallJoker , 'aux1' everywhere or just internally?

Everywhere. Inconsistency is what this PR wants to resolve, so latter would be missing the point.
"Aux" describes an audio port, thus I think "Aux1" would also be a more unique name to not confuse those two.

**Comment by Wuzzy2** [comment]
I want a clear core dev consensus on:

* Whether to use “Aux” or “Aux1”
* Whether old `keymap_*` names require any backwards-compability

**Comment by paramat** [comment]
I am ok with 'aux1' everywhere.
I have no problem with using code to keep backwards settings compatibility, as long as all settings use the same word, including `_descends` and `keymap_`.

**Comment by Wuzzy2** [comment]
> I am ok with 'aux1' everywhere.

This implies changing now the user-facing “Aux” to “Aux1” as well. Android has the word “AUX” currently baked-in into an image.

**Comment by paramat** [comment]
> This implies changing now the user-facing “Aux” to “Aux1” as well

Yes, i will support that if other core devs prefer that. I would like to see more core dev input though @sfan5 @rubenwardy

**Comment by Wuzzy2** [comment]
PR updated!

File: builtin/settingtypes.txt (hunk 2 above)
Comment (paramat) [reply builtin/settingtypes.txt:191]: Ignore that, see discussion for updated requests.

File: src/client/inputhandler.cpp (hunk 3 above)
Comment (paramat) [reply src/client/inputhandler.cpp:38]: Ignore that, see discussion for updated requests.

File: src/client/inputhandler.cpp (hunk 4 above)
Comment (paramat) [reply src/client/inputhandler.cpp:206]: Ignore that, see discussion for updated requests.

File: src/defaultsettings.cpp (hunk 1 above)
Comment (paramat) [reply src/defaultsettings.cpp:79]: Ignore that, see discussion for updated requests.

File: src/gui/guiKeyChangeMenu.cpp (hunk 5 above)
Comment (paramat) [reply src/gui/guiKeyChangeMenu.cpp:419]: Ignore that, see discussion for updated requests.

File: builtin/settingtypes.txt (hunk 2 above)
Comment (paramat) [reply builtin/settingtypes.txt:191]: Ignore that, see discussion for updated requests.

File: src/client/inputhandler.cpp (hunk 4 above)
Comment (paramat) [reply src/client/inputhandler.cpp:206]: Ignore that, see discussion for updated requests.

**Comment by paramat** [comment]
No input from other core devs so i guess we go with what SmallJoker and i want.

See the last few comments, it seems we prefer that 'Aux1' is used everywhere, internally and user-facing. The PR still uses 'Aux' is some places.
> This implies changing now the user-facing “Aux” to “Aux1” as well. Android has the word “AUX” currently baked-in into an image.

Yes please (we can update the android image later).

As for backwards compatibility, i think a little breakage is worth it for clearing up this mess in the simplest way, so i would personally prefer no added code for backwards compatibility, however i will not disapprove the PR if other core devs insist on such code being added.

**Comment by Wuzzy2** [comment]
I hate to be using “Aux1” over “Aux”, to be honest, as it's the only “Aux” key. Are there any plans to add an Aux2 in future? Otherwise the 1 doesn't make sense to me.

**Comment by paramat** [comment]
^ @SmallJoker 
There are no plans for additional aux keys, it is just a possibility mentioned.
I am ok with either 'aux' or 'aux1' (i can see good arguments both ways) as long as whatever we choose is used everywhere: internally, user-facing, and in any other setting or place that mentions 'aux' or 'special'.
So other core devs will have to decide this.

**Comment by SmallJoker** [comment]
Whatever. If you dislike `aux1`, use `aux`. If it's consistent and backwards-compatible it'll be fine.

**Comment by paramat** [comment]
I have a slight preference for 'aux', so go ahead with that =)

**Comment by Wuzzy2** [comment]
Oh no! I just realized that the name `aux1` is already used in the Lua API ...

`player:get_player_control()` and `player:get_player_control_bits()`.

I can't change that w/o breaking backwards-compat. :-(

**Comment by Wuzzy2** [comment]
How about:

`aux1` internally, `Aux` player-facing.

**Comment by Wuzzy2** [comment]
Sadly, I was forced to switch to the ugly name “Aux1” everywhere, as this is the only solution that can be done consistently. But at least it's a consistent name now. Hopefully.

WARNING: This PR needs serious testing to make sure I didn't overlook anything.

**Comment by paramat** [comment]
> I was forced to switch to the ugly name “Aux1” everywhere, as this is the only solution that can be done consistently

That is fine.

File: src/client/inputhandler.cpp (hunk 3 above)
Comment (SmallJoker) [reply src/client/inputhandler.cpp:38]:
```C++
// Migrate old key settings
std::string value;
if (g_settings->getNoEx("keymap_special1", value) {
	g_settings->set("keymap_special1", value); // Don't know whether the callback execution here might be recursive (stack overflow)
	g_settings->remove("keymap_special1");
}
```

**Comment by Wuzzy2** [comment]
Rebase done.

**Comment by SmallJoker** [comment]
Just to make sure: Would you like to have this PR merged without migrating the setting name (replacing old with new name)? The PR looks good in overall, but I'd like to clarify this prior testing/approving.

**Comment by Wuzzy2** [comment]
I don't intend to add any compability stuff. It's just a control name. The worst that will happen is that a single key will revert to the default setting for players that changed it. I think this minor level of “breakage”, if we can even call it like this, is acceptable. And any compability layer for this is more work than it's worth.

IMO the only responsibility we have is to write it in the changelog, and that's it.

**Review by SmallJoker — APPROVED** [review]
Works on desktop Linux.

**Comment by paramat** [comment]
> The worst that will happen is that a single key will revert to the default setting for players that changed it. I think this minor level of “breakage”, if we can even call it like this, is acceptable. And any compability layer for this is more work than it's worth.

I agree.

**Review by m42uko — APPROVED** [review]
Code looks good to me. I also agree that we probably don't need the compatibility layer here as the possible negative impact on the user experience is pretty low.

Tested with Joystick on Linux.
