### PR TITLE
Formspec: fix dropping held items by clicking outside

### LINKED ISSUE #16952: can't drop half the stack
### Luanti version

```true
Luanti 5.15.1 (Linux)
Using LuaJIT 2.1.1767980792
Built by GCC 15.2
Running on Linux/6.18.8 x86_64
BUILD_TYPE=Release
RUN_IN_PLACE=1
USE_CURL=1
USE_GETTEXT=1
USE_SOUND=1
STATIC_SHAREDIR="."
STATIC_LOCALEDIR="locale"
```

### Operating system and version

Manjaro Linux 26.0.2

### CPU model

Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz

### GPU model

Kaby Lake-U GT2 [HD Graphics 620] (i915)

### Active renderer

4.6 / opengl3 / SDL 2.32.62 (COMPAT)

### Summary

hi,

I can't drop half the stack when right clicking from inventory. Used to be working in eariler versions of minetest/luanti

### Steps to reproduce

steps to reproduce:
1. log in to a minetest game based server
2. have exactly two default:cobble in your inventory, in a single stack
3. open inventory
4. right click the default:cobble
5. click outside the inventory dialog
6. expected behaviour: the client drops one of your default:cobbles
7. actual behaviour: the inventory dialog closes, none of your cobbles get dropped

https://github.com/user-attachments/assets/ec56f411-95fc-4384-b43f-e07b82887486

### PR DESCRIPTION
**Pull request by sofar**
When items are picked up via right-click, middle-click, or mouse wheel (none of which change GUI focus), clicking outside the formspec closes it instead of dropping the held item. This happens because remapClickOutside() only delegates to GUIInventoryList when it has focus, but focus is only set on left mouse down.

Add a virtual hasModalInteraction() hook so GUIFormSpecMenu can signal that it has an ongoing interaction (held item). When true, remapClickOutside() backs off and lets the normal event dispatch route the click to the formspec's inventory drop handling code.

Fixes #16952

### CODE REVIEW

**Comment by cx384** [comment]
Can confirm fixes the bug, but I'm not sure about the solution. The name `hasModalInteraction` may also be misleading.

The existing `m_remap_click_outside` could be turned into a function, but that's what `remapClickOutside` does. So I suggest to just make it virtual. https://github.com/sofar/luanti/pull/1/changes/b6b87c70b0ff3d84837e414559d150c4fb720c15

**Comment by sofar** [comment]
@cx384 please re-test.

File: src/gui/guiFormSpecMenu.cpp [hunk 1]
```diff
@@ -4054,6 +4054,15 @@ void GUIFormSpecMenu::acceptInput(FormspecQuitMode quitmode)
 	}
 }
 
+bool GUIFormSpecMenu::remapClickOutside(const SEvent &event)
+{
+	// Don't close the form when the player is holding an item;
+	// let normal event dispatch handle the drop instead.
```
Comment (cx384) [inline src/gui/guiFormSpecMenu.cpp]:
```suggestion
	// Don't remap a click outside the formspec to ESC when holding an item.
```

**Comment by SmallJoker** [comment]
~~So why does the bug not occur when waiting long enough to drop the stack outside?~~ `PointerAction::isRelated` has a 400 ms delay.

**Comment by grorp** [comment]
Is this code still needed with the new approach?

https://github.com/luanti-org/luanti/blob/d5fc9a1658d04dd266eb7c6b7ba221653a180bde/src/gui/modalMenu.cpp#L126-L133

**Comment by sofar** [comment]
> Is this code still needed with the new approach?
> 
> https://github.com/luanti-org/luanti/blob/d5fc9a1658d04dd266eb7c6b7ba221653a180bde/src/gui/modalMenu.cpp#L126-L133

Thanks, this is indeed now dead code. So we can remove it (pushed).

File: src/gui/guiFormSpecMenu.cpp (hunk 1 above)
Comment (grorp) [reply src/gui/guiFormSpecMenu.cpp]: you reverted this change with the force push

Comment (sofar) [reply src/gui/guiFormSpecMenu.cpp]: Ok, sorry, didn't see that. I'll put it back in today.

Comment (sofar) [reply src/gui/guiFormSpecMenu.cpp]: fixed
