### PR TITLE
Move malloc_trim invocations to background thread

### LINKED ISSUE #14737: After #14707 I observe increased visual jitter, in singleplayer mode
### Minetest version

```true
Latest from main - after #14707
```

### Irrlicht device

_No response_

### Operating system and version

Linux, Fedora 39

### CPU model

_No response_

### GPU model

NVidia GeForce GTX 1650 Mobile / Max-Q

### Active renderer

_No response_

### Summary

I noticed visual jitter. My viewing_range is 1000, and client_mesh_chunk is 8, so this is expected to produce quite a lot of garbage as new blocks are loaded and meshes are rebuild.

When I add logging before malloc_trim I see that it is called about 8-10x per second, corresponding with the jitter.
When MEMORY_TRIM_THRESHOLD to 1GB, this is reduced to about once per second and the jitter goes away (i.e. just once per second).

128MB is probably too way small, or we should rate limit this to only once every few second.
The point of #14707 was not to return freed memory in realtime, but to prevent infinite accumulation, so returning memory to OS once per minute should absolutely be sufficient. And the accumulation only becomes a problem when it is so fragmented that it cannot be reused again.

This feels a little like an optimization in search of a problem. We could just as well call malloc_trim every 1-5 minutes or so (or once an hour).

### Steps to reproduce

Set viewing_range is 1000 and client_mesh_chunk is 8, move around. Notice the jitter.

### PR DESCRIPTION
**Pull request by sfan5**
fixes #14737

### CODE REVIEW

File: src/porting.cpp [hunk 1]
```diff
@@ -920,22 +920,34 @@ double perf_freq = get_perf_freq();
...
+ * jitter (in particular on the client), so we additionally restrict this to only
+ * happen once a minute.
  */
 
 static std::atomic<size_t> memory_freed;
 
-constexpr size_t MEMORY_TRIM_THRESHOLD = 128 * 1024 * 1024;
+static u64 next_trim_time;
+
+constexpr size_t MEMORY_TRIM_THRESHOLD = 256 * 1024 * 1024;
```
Comment (lhofhansl) [inline src/porting.cpp:933]: The size_t could overflow in a minute, right?

Comment (appgurueu) [reply src/porting.cpp:933]: `size_t` is unsigned, so goes up to 2^32 - 1 or 2^64 - 1 respectively, depending on how large a result of `sizeof` can be (32- or 64-bit machine), which is an upper bound on the amount of memory that can be allocated, so I don't see how this could possibly overflow.

**Review by nerzhul — APPROVED** [review]

**Review by Desour — COMMENTED** [review]
Tested with `/emergeblocks (-1000,-1000,-500) (0,0,0)`, by adding a TimeTaker. Does what it says.

In master it does several trims that cost about 4 to 30 ms. With PR, it's only one, but it takes about 400 ms.
Even in not so extreme examples, one would get lag spikes of > 1 frame every `MEMORY_TRIM_INTERVAL` seconds (if I just stand around in devtest, I easily get 13 ms). Needless to say, this is not good for a game.

Something else that I saw is that the drawtime doesn't seem to be affected by the lag spike. So other threads don't seem to be heavily affected by the trim call.

File: src/porting.cpp [hunk 2]
```diff
@@ -920,22 +920,34 @@ double perf_freq = get_perf_freq();
...
 {
 	constexpr auto MO = std::memory_order_relaxed;
 	memory_freed.fetch_add(amount, MO);
 	if (memory_freed.load(MO) >= MEMORY_TRIM_THRESHOLD) {
+		const u64 now = porting::getTimeS();
+		if (now < next_trim_time)
+			return;
 		// Synchronize call
-		if (memory_freed.exchange(0, MO) < MEMORY_TRIM_THRESHOLD)
+		if (memory_freed.exchange(0) < MEMORY_TRIM_THRESHOLD)
```
[the remark this answers is not in the document]
Comment (sfan5) [reply src/porting.cpp:946]: I read through https://stackoverflow.com/a/14091836 and thought there could be problems since we're working with multiple variables.

**Comment by sfan5** [comment]
> With PR, it's only one, but it takes about 400 ms.
> Even in not so extreme examples, one would get lag spikes of > 1 frame every `MEMORY_TRIM_INTERVAL` seconds

Hmm, that's sort of the same as the initial problem.
Where the lag spike happens might depend on which threads ends up calling `malloc_trim`. I guess we would have to move it to some background thread.

**Comment by lhofhansl** [comment]
> Hmm, that's sort of the same as the initial problem.

Until we have a satisfactory solution, can we please revert the original change and not call malloc_trim at all.
The issue that started all this was about a server that ran for many days, that kind of server one should have a beefy machine anyway.

I'm happy if we call malloc_trim once an hour - that would still satisfy the base issue, and a 400ms blip per hour is OK.
Another alternative is to limit this to the server, i.e. do not track the mesh-updates at all. (Won't make a difference in Singleplayer, though).

In the end we're creating new problems for something that has not been a problem for many years, is only a problem for long running servers, and is at best a nuisance anyway.

Create an admin command to call malloc_trim if admins want this.

**Comment by sfan5** [comment]
Like I argued in #14737 this can't be reduced to "some unimportant problem that happens if you run servers for days".

Anyway, I switched this to a new approach. @lhofhansl @Desour can you two re-test?

**Comment by lhofhansl** [comment]
I guess we just have to agree to disagree on whether this is useful or not.

With that said, I retested this and it works fine. No new jitter observed. So +1.

**Review by Desour — APPROVED** [review]
It would make more sense to do the trimming in a separate background thread, so to not cause unnecessary latency in meshgen or mapgen sometimes.

But this is better than in master, so :+1: .

(Also, maybe a purely time-based solution would be simpler and good enough. After all, I just have to walk 10 nodes or so in one direction to trigger a trim call.)
