### PR TITLE
[no squash] Fix network window size logic

### LINKED ISSUE #14765: New 5.9.0-dev networking is not allowing legitimate players to connect under some rare circumstances
### Minetest version

```true
Minetest-5.9.0-dev-93f4844c
```

### Irrlicht device

_No response_

### Operating system and version

Ubuntu 20.04

### CPU model

_No response_

### GPU model

_No response_

### Active renderer

_No response_

### Summary

Since upgrading our server to Minetest 5.9.0-dev, we have had two cases now about users not being able to log in, but having no difficulty logging into other servers that are on 5.8.0 or a later version. 

The first case involves one of our users (we'll call her Jane Doe) that had no problems logging in before, and started having difficulty joining (whenever she joined, she would get a Connection timed out message). After investigating a bit, we applied this patch: https://gitlab.com/tunnelers-abyss/minetest/-/commit/f9ece9553a970dd550bf2f97b7999580ae60f502
This allowed Jane Doe to get past the initial connecting phase, but her client would then stall on Item Definitions. After waiting for 10 or 15 minutes there, her client finally logged in. Once she is in-game, it's mostly smooth sailing. Sometimes it is much faster to login, sometimes it is slower, and when the server was on 5.8.0 she apparently did not have this problem. Her internet is also pretty good, so it's not that, and she doesn't have any firewalls / something similar that might be happening here.

The second case involves a user that has trouble logging in (stuck at Item Definitions again), but when they finally log in, everything moves at a snail's pace around them - almost no packets are being sent/received for some reason - when this user was fine before the upgrade. Additionally, this user has like 80mb up/down internet, which is more than enough...

I don't really have the time to do deep debugging with Wireshark or something similar, which is why tweaking the new checks in the networking code was my first thought. The vast majority of our users have had absolutely no problems, which makes this a bit more difficult to debug.

### Steps to reproduce

I really have no idea. If you give me things to try I can test them with Jane Doe, who wants very much to get this issue fixed!

### PR DESCRIPTION
**Pull request by sfan5**
this is supposed to fix #14765

## How to test

1. join a busy server with 5.9.0 or older.
2. update a busy server to this PR.
3. try to reproduce the issue by joining from a poor connection.

### CODE REVIEW

File: src/network/mtp/threads.cpp [hunk 1]
```diff
@@ -317,6 +317,7 @@ void ConnectionSendThread::sendAsPacketReliable(BufferedPacketPtr &p, Channel *c
 		channel->outgoing_reliables_sent.insert(p,
 			(channel->readOutgoingSequenceNumber() - MAX_RELIABLE_WINDOW_SIZE)
 				% (MAX_RELIABLE_WINDOW_SIZE + 1));
+		// wtf is this calculation?? ^
```
Comment (red-001) [inline src/network/mtp/threads.cpp:320]: start of the reliable window for that packet?

Comment (sfan5) [reply src/network/mtp/threads.cpp:320]: can you explain how we arrive at this number?
because this calculation falls apart with max=2048

Comment (red-001) [reply src/network/mtp/threads.cpp:320]: The whole calculation I think is pointless, since this only exists cause someone had the idea that incoming and outgoing packets should be tracked using the same queue type despite clearly having different requirements.

I *think* the idea was to get the actual current sequence number, subtract from it the window size, and then take that mod the size of the sequence number type. Someone messed up and used `MAX_RELIABLE_WINDOW_SIZE + 1` instead of  `MAX_SEQ_NUM` or whatever the (stupid-ish) `#define` for that is.
Didn't matter before your changes since it was basically pointless code (I think) that was just meant to pass a window check and it passed.

I made changes to stop using that common queue type on the receiving end when implementing encryption because it involved pointless constructing a wire formatted packet, maybe I should pull those changes out and also refactor the sender side to use a more sane queue.

Comment (sfan5) [reply src/network/mtp/threads.cpp:320]: > The whole calculation I think is pointless, since this only exists cause someone had the idea that incoming and outgoing packets should be tracked using the same queue type despite clearly having different requirements.

> Didn't matter before your changes since it was basically pointless code (I think) that was just meant to pass a window check and it passed.

that's what I thought too, however that can't be entirely true as depending on the current connection state - out of of two outgoing reliables you want to track with seqnums 1234, 65500 - either 65500 is the first or 1234 is the first and you need some information to disambiguate.

anyway it doesn't really matter. personally I wouldn't invest more work into the protocol code beyond fixing the necessary.

**Comment by sfan5** [comment]
> it might need more adjustments to allow the window to grow faster to not regress media transfer speed too much.
> (testing needed to determine if this is the case)

I tested a bit with a latency of 126ms over the internet.
the results:
|           | 6MB  | 16MB |
|-----------|------|------|
| before PR | 10s  | 13s  |
| with PR   | 11s  | 15s  |
| wget      | 1,5s | 2,2s |

Obviously a smaller window means more transfer time, but the difference is less than I expected. So that doesn't need adjustment.
wget is shown for comparison (our protocol implementation is really terrible).
