### PR TITLE
Give subgames the ability to disallow specific mapgens

### LINKED ISSUE #4768: Hide or discourage mapgens in main menu on subgame request
There are some subgames which are mostly designed to work with only a subset of the available map generators. Subgames might either perform poorly with the “wrong” mapgen or simply don't work at all.
One example is Pixture. The recommended mapgen is v7, and v6 is strongly discouraged for Pixture.
Other subgames completely overwrite the mapgen choice. But in the main menu, the user still has the illusion of choice. Restricting the mapgen choice often has legit reasons. Either other mapgens would simply never make sense with this subgame, they don't work well together or the subgame is entirely singlenode-based.

I think Minetest should allow subgames to specify a list of mapgens for the user to be selectable. Additionally, it should be possible to list mapgens which technically work more or less, but do not provide the best gameplay experience as “discouraged”. For example, if the subgame's mapgen gives poor balancing results in v6 but v6 still works good enough to not outright disable it, v6 can be called “discouraged” which means a small warning is displayed in the world creation dialog.

The scope of my suggestion is basically ONLY the main menu, specifically the world creation dialog. Configuration and world data files are still taken seriously. The goal is to not clutter the world creation dialog with mapgens which in reality are never used in the subgame.

This new feature will also mean a comeback of singlenode in the main menu, but only for those subgames which allow it.

Examples:

* SkyTest: This subgame currently overwrites all mapgen settings of the user and forces singlenode. Which is of course a direct contradiction to user request (e.g. v6 selected). With this suggestion implemented, SkyTest can list `singlenode` as the only available mapgen.
* Minetest Game: No changes neccessary.
* Pixture: Only specifically designed for v7. It also is apparently completely broken for v6. So this subgame would remove v6 and discourage all mapgens except v7.

Specification. Subgames specify their mapgen preferences in `game.conf` with two new variables:

* available_mapgens: Comma-separated list of mapgens which are available. Default is `v5, v6, v7, flat, fractal, valleys`, i.e. the current mapgen list in Minetest 0.4.14
* `discouraged_mapgens`: Comma-seperated list of mapgens which are discouraged. Adding unavailable mapgens into this list will be ignored. Default is empty.

### PR DESCRIPTION
**Pull request by Ezhh**
This allows a subgame to control which mapgens show in the Mapgen dropdown when making a new game/world. 

Mapgens which are not supported or otherwise suitable for a given subgame can be disallowed by adding a setting in game.conf. For example, if you wish to disable v6, flat and fractal mapgens, add: 
disallowed_mapgens = v6,flat,fractal

This results in:
mapgensleft

Fixes  #4768

### CODE REVIEW

**Comment by paramat** [comment]
Will test.

**Comment by Ezhh** [comment]
Thank you. Also please let me know if there is anywhere suitable to document this (other than wiki). It feels like it needs documentation, but none of the docs I see are suitable.

File: builtin/common/misc_helpers.lua [hunk 1]
```diff
@@ -551,7 +551,7 @@ end
 --------------------------------------------------------------------------------
 if INIT == "mainmenu" then
 	function core.get_game(index)
-		local games = game.get_games()
+		local games = core.get_games()
```
Comment (paramat) [inline builtin/common/misc_helpers.lua]: Interesting, was this a bug?

**Comment by paramat** [comment]
Documentation could be here https://github.com/minetest/minetest/blob/master/doc/lua_api.txt#L56

File: builtin/common/misc_helpers.lua (hunk 1 above)
Comment (Ezhh) [reply builtin/common/misc_helpers.lua]: Yup.

**Comment by Ezhh** [comment]
Added documentation.

**Comment by paramat** [comment]
Works well :+1:

File: builtin/mainmenu/dlg_create_world.lua [hunk 2]
```diff
@@ -20,6 +20,29 @@ local function create_world_formspec(dialogdata)
...
+		
+		if gameidx == nil then
+			gameidx = 0
+		end
+	end
+
+	local gamepath = minetest.get_game(gameidx).path
+	local gameconfig = Settings(gamepath.."/game.conf")
+
+	local disallowed_mapgens = gameconfig:get("disallowed_mapgens")
```
Comment (rubenwardy) [inline builtin/mainmenu/dlg_create_world.lua]:
```lua
local disallowed_mapgens = gameconfig:get("disallowed_mapgens"):lower():split()
for key, value in pairs(disallowed_mapgens) do
     disallowed_mapgens[key] = value:trim()
end
```

File: builtin/mainmenu/dlg_create_world.lua [hunk 3]
```diff
@@ -20,6 +20,29 @@ local function create_world_formspec(dialogdata)
...
+
+	if disallowed_mapgens then
+		for i = #mapgens, 1, -1 do
+			if string.find(disallowed_mapgens, mapgens[i]) then
```
Comment (rubenwardy) [inline builtin/mainmenu/dlg_create_world.lua]:
```lua
if table.indexof(disallowed, mapgens[i]:lower()) then
```

**Comment by rubenwardy** [comment]
Changing the subgame resets the text fields

**Comment by Ezhh** [comment]
Worldname fixed and no longer resets incorrcetly, thank you. Seed already saves correctly so shouldn't need any adjustment.

**Comment by rubenwardy** [comment]
@paramat: still ok with this?

**Comment by ThomasMonroe314** [comment]
This is a nice feature to have for modders to use.

File: builtin/mainmenu/dlg_create_world.lua [hunk 4]
```diff
@@ -15,11 +15,39 @@
...
+
+	local gamepath = minetest.get_game(gameidx).path
+	local gameconfig = Settings(gamepath.."/game.conf")
+
+	local disallowed_mapgens = (gameconfig:get("disallowed_mapgens") or ""):split()
+	for key, value in pairs(disallowed_mapgens) do
+		disallowed_mapgens[key] = value:trim()
+	end
+
+	if disallowed_mapgens then
```
Comment (SmallJoker) [inline builtin/mainmenu/dlg_create_world.lua]: Superfluous check. `string.split` never returns `nil`.

File: builtin/mainmenu/dlg_create_world.lua [hunk 5]
```diff
@@ -15,11 +15,39 @@
...
+	local game, gameidx = nil , 0
+	if gameid ~= nil then
+		game, gameidx = gamemgr.find_by_gameid(gameid)
+		
+		if gameidx == nil then
+			gameidx = 0
+		end
+	end
+
+	local gamepath = minetest.get_game(gameidx).path
```
Comment (SmallJoker) [inline builtin/mainmenu/dlg_create_world.lua]: `core.get_game`

File: builtin/mainmenu/dlg_create_world.lua (hunk 4 above)
Comment (Ezhh) [reply builtin/mainmenu/dlg_create_world.lua]: rubenwardy requested it be this way. I know his commented version is a little different, but he asked me to adjust to this, so will see what he says.

**Comment by Ezhh** [comment]
Just to note: When you've had three approvals... and are still getting asked to change things on something that works and isn't controversial, there is something a bit unappealing with the development process.

**Comment by SmallJoker** [comment]
@Ezhh Whereas the labels suggest the PR is not reviewed entirely yet - it apparently is. As you can see, the changes I requested are quite trivial and not required to make this PR work properly, they were requested for consistent and simple code.
Please note that reviews sometimes have to be refreshed when changes were done, hence, rubenwardy's question whether the approval is still standing. Nevertheless, it hasn't got any disapprovals which makes it ready to merge already now.

**Comment by Ezhh** [comment]
@SmallJoker I will be changing the other point you've raised, so hold on for that please. I simply don't want to change things that are already changes specifically asked for by developers without them weighing in again. I do understand how this works, but I also feel justified in being frustrated by it.

**Comment by NewbProgrammer101** [comment]
649eef9

File: builtin/mainmenu/dlg_create_world.lua (hunk 4 above)
Comment (rubenwardy) [reply builtin/mainmenu/dlg_create_world.lua]: I didn't notice this aha, krock is right unfortunately. But doesn't matter too much

**Comment by Wuzzy2** [comment]
Wow, so this was coded, tested and merged and I only noticed it now? xD

Thanks, man! :heart:

**Comment by Ezhh** [comment]
@Wuzzy2 Very welcome. Hope it will be useful :)

**Comment by Megaf** [comment]
:tada:

**Comment by paramat** [comment]
Yes i'm still fine with it.
