### PR TITLE
[no squash] Port shadow shaders to work with OpenGL3 

### LINKED ISSUE #15635: OpenGL3 break shadows on leave-like nodes
### Luanti version

```true
Luanti 5.11.0-dev-5bcb7983e (Linux)
Using LuaJIT 2.1.1720049189
Built by GCC 14.2
Running on Linux/6.12.7 x86_64
BUILD_TYPE=Release
RUN_IN_PLACE=0
USE_CURL=1
USE_GETTEXT=1
USE_SOUND=1
STATIC_SHAREDIR="/opt/luanti/share/luanti"
STATIC_LOCALEDIR="/opt/luanti/share/locale"
```

### Operating system and version

Fedora 41

### CPU model

Core i9-13980HX

### GPU model

NVidia RTX 4000 ada

### Active renderer

4.6.0 / opengl3 / SDL

### Summary

OpenGL3:
screenshot_20250104_104721

OpenGL:
screenshot_20250104_104746

### Steps to reproduce

Enabled shadows, look at any scene with some grass.
Set driver to opengl3, notice that grass (and some leaves) are not producing a shadow.
Now set driver to opengl (restart) and notice that now the shadows are rendered correctly.

### PR DESCRIPTION
**Pull request by sfan5**
fixes #15635
adopts #16329

## To do

This PR is  Ready for Review.

## How to test

1. use dynamic shadows with opengl 3
2. make sure everything works
3. same for the legacy opengl driver

### CODE REVIEW

File: src/client/shadows/shadowsshadercallbacks.h [hunk 1]
```diff
@@ -42,20 +42,19 @@ class ShadowUniformSetter : public IShaderUniformSetter
 class ShadowUniformSetterFactory : public IShaderUniformSetterFactory
 {
 public:
-	virtual IShaderUniformSetter *create() {
+	virtual IShaderUniformSetter *create(const std::string &name) {
+		if (str_starts_with(name, "shadow/"))
```
Comment (lhofhansl) [inline src/client/shadows/shadowsshadercallbacks.h:46]: I realize that is what we had all the discussions about in the original PR... That said, isn't it a bit clumsy to compare the shader path here?

**Comment by lhofhansl** [comment]
I can confirm that it works fine on my machine.

File: src/client/shadows/shadowsshadercallbacks.h (hunk 1 above)
Comment (sfan5) [reply src/client/shadows/shadowsshadercallbacks.h:46]: Yes :shrug:

File: src/client/shadows/dynamicshadowsrender.cpp [hunk 2]
```diff
@@ -508,185 +499,36 @@ void ShadowRenderer::mixShadowsQuad()
...
-
-		// HACK, TODO: investigate this better
-		// Grab the material renderer once more so minetest doesn't crash
-		// on exit
-		m_driver->getMaterialRenderer(depth_shader_trans)->grab();
+	{
+		auto *shadow_mix_cb = new ShadowScreenQuadUniformSetter();
+		u32 shader_id = shdsrc->getShader("shadow/pass2", {},
+			video::EMT_SOLID, shadow_mix_cb);
+		shadow_mix_cb->drop();
```
Comment (SmallJoker) [inline src/client/shadows/dynamicshadowsrender.cpp:526]: Note: GCC 14.2.0 is probably drunk. Regardless, it compiles.
```C++
irr/include/IReferenceCounted.h:50:9: warning: ‘void operator delete(void*, std::size_t)’ called on pointer ‘<unknown>’ with nonzero offset 8 [-Wfree-nonheap-object]
   50 |         }
      |         ^
src/client/shadows/dynamicshadowsrender.cpp: In member function ‘void ShadowRenderer::createShaders()’:
src/client/shadows/dynamicshadowsrender.cpp:523:73: note: returned from ‘void* operator new(std::size_t)’
  523 |                 auto *shadow_mix_cb = new ShadowScreenQuadUniformSetter();
      |  
```

**Comment by sfan5** [comment]
> ❓ `shadow/pass1_trans` is apparently not used or there's no error handling? I cannot provoke an error there by modifying the glsl files. Why's that?

it's only used if colored shadows are enabled.

**Review by SmallJoker — APPROVED** [review]

**Comment by lhofhansl** [comment]
Unfortunately I have to report that this broke something:

Without PR:
screenshot_20251019_213811

With PR:
screenshot_20251019_213946

The holes also move in the wrong direction (can post a video if folks want).

This has nothing to with whether blocks are loaded or not, it happens only with new code, in OpenGL, and OpenGL3, GLX, SDL, etc.
Other setting: No colored shadows, fairly far viewing_range, and it seems this is only visible with zoom.

@sfan5

File: src/client/shadows/dynamicshadowsrender.cpp [hunk 3]
```diff
@@ -431,11 +430,9 @@ void ShadowRenderer::renderShadowMap(video::ITexture *target,
 	material.FrontfaceCulling = true;
 
 	if (m_shadow_map_colored && pass != scene::ESNRP_SOLID) {
-		material.MaterialType = (video::E_MATERIAL_TYPE) depth_shader_trans;
-	}
-	else {
-		material.MaterialType = (video::E_MATERIAL_TYPE) depth_shader;
-		material.BlendOperation = video::EBO_MIN;
```
Comment (lhofhansl) [inline src/client/shadows/dynamicshadowsrender.cpp:438]: Looks like BlendOperation has to be restored...

Comment (sfan5) [reply src/client/shadows/dynamicshadowsrender.cpp:438]: did you try it?

Comment (lhofhansl) [reply src/client/shadows/dynamicshadowsrender.cpp:438]: Yes. I wouldn't have suggested it otherwise :)
It removes the problem I saw.
