### PR TITLE
Fix missing airlike buffer info

### LINKED ISSUE #16636: Crash when adding airlike wield item mesh
### Luanti version

```true
Luanti 5.15.0-dev-debug-1ead48c5 (Linux)
Using LuaJIT 2.1.1716656478
Built by GCC 14.2
Running on Linux/6.6.74 x86_64
BUILD_TYPE=Debug
RUN_IN_PLACE=1
USE_CURL=1
USE_GETTEXT=1
USE_SOUND=1
STATIC_SHAREDIR="."
STATIC_LOCALEDIR="locale"
```

### Operating system and version

Gentoo

### CPU model

_No response_

### GPU model

_No response_

### Active renderer

4.6 / opengl / SDL 2.32.2

### Summary

Always crashes in particular area, presumably because of the item frame with specific item in it?

```
/usr/lib/gcc/x86_64-pc-linux-gnu/14/include/g++-v14/bits/stl_vector.h:1130: std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::operator[](size_type) [with _Tp = ItemMeshBufferInfo; _Alloc = std::allocator<ItemMeshBufferInfo>; reference = ItemMeshBufferInfo&; size_type = long unsigned int]: Assertion '__n < this->size()' failed.

Thread 1 "luanti" received signal SIGABRT, Aborted.
```

Backtrace:
```
#0  __pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0)
    at pthread_kill.c:44
#1  0x00007ffff68aa1e3 in __pthread_kill_internal (signo=6, threadid=<optimized out>) at pthread_kill.c:78
#2  0x00007ffff685a356 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#3  0x00007ffff68428f7 in __GI_abort () at abort.c:79
#4  0x00007ffff6ad96af in std::__glibcxx_assert_fail(char const*, int, char const*, char const*) ()
   from /usr/lib/gcc/x86_64-pc-linux-gnu/14/libstdc++.so.6
#5  0x000055555592d060 in std::vector<ItemMeshBufferInfo, std::allocator<ItemMeshBufferInfo> >::operator[] (
    this=0x55557552bdc0, __n=0) at /usr/lib/gcc/x86_64-pc-linux-gnu/14/include/g++-v14/bits/stl_vector.h:1130
#6  0x000055555592b203 in WieldMeshSceneNode::setItem (this=0x55557552bcd0, item=..., client=0x5555584488b0, 
    check_wield_image=true) at ./minetest-git/src/client/wieldmesh.cpp:563
#7  0x00005555557e03cc in GenericCAO::addToScene (this=0x5555755beae0, tsrc=0x555557284e90, smgr=0x5555577d3440)
    at ./minetest-git/src/client/content_cao.cpp:743
#8  0x000055555578e83c in ClientEnvironment::addActiveObject (this=0x555558448930, 
    object=std::unique_ptr<ClientActiveObject> = {...})
    at ./minetest-git/src/client/clientenvironment.cpp:304
#9  0x000055555578ea5b in ClientEnvironment::addActiveObject (this=0x555558448930, id=5235, type=101 'e', 
    init_data="\001\000\017itemframes:item\000\024s\306\030\370\000C\252fg\306\356 ", '\000' <repeats 14 times>, "\001\005\000\000\000\274\000\004\000\001", '\000' <repeats 53 times>, "\001\000\twielditem>\250\365\303>\250\365\303>\250\365\303\000\001\000\031mobs_banshee:glowing_node\000\001\000\001\000\000\000\000\001\000?\200\000\000\000\000\000\000\001\000\000\000\000\000\000\000\000\000\001\000\000\377\377\377\377\277\200\000"...)
    at ./minetest-git/src/client/clientenvironment.cpp:336
#10 0x0000555555a38e77 in Client::handleCommand_ActiveObjectRemoveAdd (this=0x5555584488b0, pkt=0x7fffffffbb70)
    at ./minetest-git/src/network/clientpackethandler.cpp:442
#11 0x0000555555768b8c in Client::handleCommand (this=0x5555584488b0, pkt=0x7fffffffbb70)
    at ./minetest-git/src/client/client.cpp:979
#12 0x0000555555768dc5 in Client::ProcessData (this=0x5555584488b0, pkt=0x7fffffffbb70)
    at ./minetest-git/src/client/client.cpp:1027
#13 0x0000555555768a21 in Client::ReceiveAll (this=0x5555584488b0)
    at ./minetest-git/src/client/client.cpp:967
#14 0x0000555555765317 in Client::step (this=0x5555584488b0, dtime=0.042183999)
    at ./minetest-git/src/client/client.cpp:404
#15 0x00005555558176b1 in Game::step (this=0x7fffffffc200, dtime=0.042183999)
    at ./minetest-git/src/client/game.cpp:2219
#16 0x000055555580d48f in Game::run (this=0x7fffffffc200)
    at ./minetest-git/src/client/game.cpp:691
#17 0x000055555582281e in the_game (kill=0x5555565bd3e0 <porting::g_killed>, input=0x5555577ca4e0, 
    rendering_engine=0x555556f13350, start_data=..., error_message="", chat_backend=..., 
    reconnect_requested=0x7fffffffc560) at ./minetest-git/src/client/game.cpp:3858
#18 0x000055555579730f in ClientLauncher::run (this=0x7fffffffc920, start_data=..., cmd_args=...)
    at ./minetest-git/src/client/clientlauncher.cpp:199
#19 0x0000555555d03938 in main (argc=1, argv=0x7fffffffcdd8)
    at ./minetest-git/src/main.cpp:269
```

### Steps to reproduce

~~Join Your Land server, visit Aventiure city with long view range~~
Item data says it's `mobs_banshee:glowing_node` inside an item frame.
Happened to 2 other people too, running `-dev` versions.

### PR DESCRIPTION
**Pull request by cx384**
Fixes #16636

## To do

Ready for review.

## How to test

Wield `testnodes:airlike` in the devtest game

### CODE REVIEW

File: src/client/wieldmesh.cpp [hunk 1]
```diff
@@ -520,7 +521,9 @@ void WieldMeshSceneNode::setItem(const ItemStack &item, Client *client, bool che
 		switch (f.drawtype) {
 		case NDT_AIRLIKE:
 			setExtruded(tsrc->getTexture("no_texture_airlike.png"), nullptr, v3f(1));
-			break;
+			m_buffer_info.emplace_back(0);
+			setColor(video::SColor(0xFFFFFFFF));
+			return;
```
Comment (sfan5) [inline src/client/wieldmesh.cpp:526]: wouldn't this work?
```suggestion
```

Comment (cx384) [reply src/client/wieldmesh.cpp:526]: No, because of bilinear/trilinear filters: https://github.com/luanti-org/luanti/blob/1ead48c58b316b376e02d135a9a043201a72b41a/src/client/wieldmesh.cpp#L564-L566

But it would not crash at least.

Comment (sfan5) [reply src/client/wieldmesh.cpp:526]: what would break if the filter code runs?

Comment (cx384) [reply src/client/wieldmesh.cpp:526]: It would look like this:
grafik

Comment (sfan5) [reply src/client/wieldmesh.cpp:526]: I see, nvm.

File: src/client/wieldmesh.cpp [hunk 2]
```diff
@@ -305,6 +305,7 @@ void WieldMeshSceneNode::setExtruded(const TileDef &d0, const TileLayer &l0,
 	m_buffer_info.emplace_back(1, l1);
 }
 
+// This does not set m_buffer_info
```
Comment (SmallJoker) [inline src/client/wieldmesh.cpp:308]: Then why does e.g. `NDT_PLANTLIKE_ROOTED` work correctly?

Comment (cx384) [reply src/client/wieldmesh.cpp:308]: https://github.com/luanti-org/luanti/blob/1ead48c58b316b376e02d135a9a043201a72b41a/src/client/wieldmesh.cpp#L536-L539

It uses https://github.com/luanti-org/luanti/blob/1ead48c58b316b376e02d135a9a043201a72b41a/src/client/wieldmesh.cpp#L296
which does set m_buffer_info unlike
https://github.com/luanti-org/luanti/blob/1ead48c58b316b376e02d135a9a043201a72b41a/src/client/wieldmesh.cpp#L308
