### PR TITLE
CSM: Bugfixes to camera:get_pos() and camera:get_fov()

### LINKED ISSUE #9857: Minetest.camera:get_pos() returns pos with wrong decimal place
For example: if player position is:
x= -1285.9
y=3.5
z=1576.5

then minetest.camera reports the camera adjusted position as:
x = -12858.57421875
y = 49.700000762939
z = 15765.104492188

### PR DESCRIPTION
**Pull request by sfan5**
closes #9857

## To do

This PR is a Ready for Review.

### CODE REVIEW

File: clientmods/preview/init.lua [hunk 1]
```diff
@@ -79,7 +79,7 @@ core.register_on_item_use(function(itemstack, pointed_thing)
 		return false
 	end
 
-	local pos = vector.add(core.localplayer:get_pos(), core.camera:get_offset())
+	local pos = core.camera:get_pos()
```
Comment (SmallJoker) [inline clientmods/preview/init.lua:82]: These are not equal in the two 3rd perspective modes. This code is not so important, so it might suffice to note that this shootline starts from the camera, rather than the head position.

File: src/script/lua_api/l_camera.cpp [hunk 2]
```diff
@@ -115,38 +120,40 @@ int LuaCamera::l_get_offset(lua_State *L)
 	return 1;
 }
 
+// get_look_dir(self)
```
Comment (SmallJoker) [inline src/script/lua_api/l_camera.cpp:123]: `// FIXME: wouldn't localplayer be a better place for this?`

for the sake of completeness

File: src/script/lua_api/l_camera.cpp [hunk 3]
```diff
@@ -115,38 +120,40 @@ int LuaCamera::l_get_offset(lua_State *L)
...
+	if (!camera)
+		return 0;
 
-	push_v3f(L, v);
+	push_v3f(L, camera->getDirection());
 	return 1;
 }
 
+// get_look_horizontal(self)
+// FIXME: wouldn't localplayer be a better place for this?
```
Comment (SmallJoker) [inline src/script/lua_api/l_camera.cpp:135]: Would be consistent with the server-side `ObjectRef`, but since these values are calculated locally I think they should be kept in the camera object.

File: clientmods/preview/init.lua (hunk 1 above)
Comment (sfan5) [reply clientmods/preview/init.lua:82]: This is just debug and testing code.
