### PR TITLE
Meshgen: Refactor and fix blend nodebox splitting

### LINKED ISSUE #16934: Complicated node boxes with `use_texture_alpha = "blend"` look weird
### Luanti version

```true
Luanti 5.15.0-dev-5f468eae2 (Linux)
Using LuaJIT 2.1.0-beta3
Built by GCC 12.2
Running on Linux/6.1.0 x86_64
BUILD_TYPE=Release
RUN_IN_PLACE=1
USE_CURL=1
USE_GETTEXT=1
USE_SOUND=1
STATIC_SHAREDIR="."
STATIC_LOCALEDIR="locale"
```

### Operating system and version

Debian

### CPU model

Ryzen 5600

### GPU model

AMD RX 6600

### Active renderer

4.6 / opengl  / SDL 2.26.5

### Summary

If a node box node has `use_texture_alpha = "blend"` and consists of an inner and outer box, then the resulting node renders in a weird way. It looks like there are faces within the node that spans the whole node. See screenshots

Image

Image

Image

### Steps to reproduce

Register a node using the following:

```
core.register_node("modname:nodename", {
	drawtype = "nodebox",
	paramtype = "light",
	node_box = {
		type = "fixed",
		fixed = {
			{-0.25, -0.25, -0.25, 0.25, 0.25, 0.25},
			{-0.5, -0.5, -0.5, 0.5, 0.5, 0.5},
		}
	},
	tiles = {"semi_transparent_texture.png"},
	use_texture_alpha = "blend",
})
```

Or start Mineclonia and check how slime block looks.

### PR DESCRIPTION
**Pull request by Desour**
Fixes #16934.

## To do

This PR is a Ready for Review.

## How to test

* Use the added devtest nodes.
* Also use wireframe mode, to confirm that the faces are split correctly.

### CODE REVIEW

File: src/client/content_mapblock.cpp [hunk 1]
```diff
@@ -1628,60 +1628,75 @@ void MapblockMeshGenerator::drawNodeboxNode()
 	std::vector<aabb3f> boxes;
 	cur_node.n.getNodeBoxes(nodedef, &boxes, neighbors_set);
 
-	bool isTransparent = false;
+	std::vector<u8> masks;
+	masks.reserve(boxes.size());
+	for (const auto &box : boxes)
+		masks.push_back(getNodeBoxMask(box, solid_neighbors, sametype_neighbors));
+	assert(masks.size() == boxes.size());
```
Comment (sfan5) [inline src/client/content_mapblock.cpp]: there's the same assert further down, this one feels pointless

**Comment by CandyFiend** [comment]
I have checked the items, it is displayed as expected.
Is it possible to do something with the face rendering mode at the junction of the nodboxes? For example, you can see a darkened plane in the stairs. I have a metal fence made of nodboxes in my game, it has a face drawn at the joints, which spoils the appearance. I would like to prevent the inner face from being drawn so that it looks like xpanes from mtg, but I didn't have to invent a whole module for this purpose. 
image
image

**Comment by Desour** [comment]
>For example, you can see a darkened plane in the stairs.

The greener face in the stairs is where two faces are drawn. The mod specified it like this, so the engine should render it like this.

>I have a metal fence made of nodboxes in my game, it has a face drawn at the joints, which spoils the appearance. I would like to prevent the inner face from being drawn so that it looks like xpanes from mtg, but I didn't have to invent a whole module for this purpose.

I'm not sure if I understand you correctly. Your fence doesn't need alpha blending. So you're not reporting a bug here, right?
If you're using connected nodeboxes, the disconnected boxes might be useful for you.

I thought about making nodebox masks available to the modding api, which would allow to do advanced stuff with nodeboxes. But not in this bugfix PR.

**Comment by CandyFiend** [comment]
This is not a bug, but rather a question related to the topic of PR. I understand that intermediate faces are drawn on the stairs, and I was asking if there was any way to disable the drawing of these faces. For example, should they be drawn in clip mode or not? I can't say for sure if this applies to PR or not, but it certainly doesn't apply to the issue originally identified.

**Comment by Desour** [comment]
Offtopic.
I've created an issue now for disabling sides of boxes: #16949

File: src/client/content_mapblock.cpp [hunk 2]
```diff
@@ -1628,60 +1628,74 @@ void MapblockMeshGenerator::drawNodeboxNode()
...
 
+		// Default split at node bounds, up to 3 nodes in each direction
+		for (int half_node = -7; half_node < 8; half_node += 2)
+			sections.push_back(half_node * 0.5f * BS);
+		assert(sections.size() == 8);
+
 		for (int axis = 0; axis < 3; axis++) {
+			int mask_axis = std::array<int, 3>{1, 0, 2}[axis];
+			u8 mask_neg = 1 << (mask_axis * 2);
+			u8 mask_pos = 1 << (mask_axis * 2 + 1);
```
Comment (sfan5) [inline src/client/content_mapblock.cpp]: I would like a short comment on what these two represent

Comment (sfan5) [reply src/client/content_mapblock.cpp]: I mean what specifically does `mask_neg` refer to and what about `mask_pos`?

Comment (Desour) [reply src/client/content_mapblock.cpp]: Ok, done.
