### PR TITLE
Vein ore: Fix bug caused by changing perlinmap Y size

### LINKED ISSUE #7364: "Vein" ore type causes a crash when generating map chunks near y_max
##### Issue type
 - Bug report
 
##### Minetest version

```
minetest-0.5.0-cf0bceb-win64
```

##### OS / Hardware

Operating system: Windows 10
CPU: Intel Core i7-3770K

##### Summary

While working on a mod that uses a "vein" ore type to add magma conduits to mapgen, I've discovered that if you try to generate map chunks around the elevation of the ore definition's y_max parameter Minetest will immediately crash with no logged information about the cause of the crash.

##### Steps to reproduce

The issue can be reproduced by starting a Minetest Game with mapgen v7 and the following test mod enabled:

[init.txt](https://github.com/minetest/minetest/files/2025100/init.txt) (rename to init.lua)
[depends.txt](https://github.com/minetest/minetest/files/2025077/depends.txt)

The game should crash immediately upon startup.

If you change the y_max ore parameter to something larger than 0 (for example, 500) the game won't crash.

I've also tried setting the height to 1300 and enabling the floatlands, and I still get a crash when I'm up in the sky around the 1300 altitude so it's not just a sea-level issue.

### PR DESCRIPTION
**Pull request by paramat**
Because vein ore uses 3D noise (all the other ores use 2D noise) the
perlinmap Y size can be different in different mapchunks when close
to the ore Y limits.
Previously this caused bugs in the vein structure because changes in
perlinmap Y size did not recreate the noise objects.

Recreate the noise objects with the new Y size if Y size has changed.
//////////////////////

Fixes #7364 
Tested, used printf() to check when noise objects were recreated.

### CODE REVIEW

File: src/mapgen/mg_ore.cpp [hunk 1]
```diff
@@ -371,17 +371,19 @@ void OreVein::generate(MMVManip *vm, int mapseed, u32 blockseed,
...
-		noise2 = new Noise(&np, mapseed + 436, sx, sy, sz);
+	int sizex = nmax.X - nmin.X + 1;
+	int sizey = nmax.Y - nmin.Y + 1;
+	// Because this ore uses 3D noise the perlinmap Y size can be different in
+	// different mapchunks due to ore Y limits. So recreate the noise objects
+	// if Y size has changed.
+	if (!noise || sizey != sizey_prev) {
+		int sizez = nmax.Z - nmin.Z + 1;
+		noise  = new Noise(&np, mapseed, sizex, sizey, sizez);
+		noise2 = new Noise(&np, mapseed + 436, sizex, sizey, sizez);
```
Comment (SmallJoker) [inline src/mapgen/mg_ore.cpp]: Both noises need deletion when they were defined previously (non-nullptr).

Comment (SmallJoker) [reply src/mapgen/mg_ore.cpp]: That's the OreVein destructor, which is only called when this class here is deleted. What we need is to destruct and delete/free the `Noise` class.

Comment (paramat) [reply src/mapgen/mg_ore.cpp]: I have no idea what is right to do. Also, such changes are needed for all ore types so should be a separate PR, will merge this bugfix first.

Comment (paramat) [reply src/mapgen/mg_ore.cpp]: Done. well spotted, deletion is needed for this ore type only because the noises are created multiple times.

**Comment by paramat** [comment]
Updated with deletions, will retest.

File: src/mapgen/mg_ore.cpp [hunk 2]
```diff
@@ -371,17 +371,25 @@ void OreVein::generate(MMVManip *vm, int mapseed, u32 blockseed,
...
-		noise2 = new Noise(&np, mapseed + 436, sx, sy, sz);
+	int sizex = nmax.X - nmin.X + 1;
+	int sizey = nmax.Y - nmin.Y + 1;
+	// Because this ore uses 3D noise the perlinmap Y size can be different in
+	// different mapchunks due to ore Y limits. So recreate the noise objects
+	// if Y size has changed.
+	// Because these noise objects are created multiple times for this ore type
+	// it is necessary to 'delete' them here.
+	if (!noise || sizey != sizey_prev) {
+		if (noise)
```
Comment (nerzhul) [inline src/mapgen/mg_ore.cpp]: useless if

File: src/mapgen/mg_ore.cpp [hunk 3]
```diff
@@ -371,17 +371,25 @@ void OreVein::generate(MMVManip *vm, int mapseed, u32 blockseed,
...
+			delete noise;
+		if (noise2)
```
Comment (nerzhul) [inline src/mapgen/mg_ore.cpp]: same here

File: src/mapgen/mg_ore.cpp (hunk 2 above)
Comment (paramat) [reply src/mapgen/mg_ore.cpp]: ?

Comment (paramat) [reply src/mapgen/mg_ore.cpp]: Oh you mean just 'delete'? The noise has to exist if we delete (i think).

Comment (paramat) [reply src/mapgen/mg_ore.cpp]: Maybe not, they are initialised as nullptr, will try.

Comment (paramat) [reply src/mapgen/mg_ore.cpp]: Done.

File: src/mapgen/mg_ore.cpp (hunk 3 above)
Comment (paramat) [reply src/mapgen/mg_ore.cpp]: Done.

**Comment by paramat** [comment]
Removed unnecesary 'if ()' lines, retested.
