### PR TITLE
ContentCAO: Fix threshold of alpha channel textures

### LINKED ISSUE #14204: Alpha-blending entities disappear completely when enable_shaders=false and alpha <= 127
### Minetest version

```true
Minetest 5.8.0 (Linux)
Using Irrlicht 1.9.0mt13
Using LuaJIT 2.1.0-beta3
BUILD_TYPE=Release
RUN_IN_PLACE=1
USE_CURL=1
USE_GETTEXT=1
USE_SOUND=1
STATIC_SHAREDIR="."
STATIC_LOCALEDIR="locale"
```

### Active renderer

OpenGL 4.2

### Irrlicht device

X11

### Operating system and version

Debian GNU/Linux 12 (bookworm) x86_64

### CPU model

Intel i5-3320M (4) @ 3.300GHz

### GPU model

Intel 3rd Gen Core processor Graphics Controller

### OpenGL version

4.2 (Compatibility Profile) Mesa 22.3.6

### Summary

Entities with alpha blending (semi-transparent texture and use_texture_alpha = true) are completely transparent when enable_shaders = false in MT config

### Steps to reproduce

- Set enable_shaders = false in MT
- Install the **Citadel** game, version https://github.com/Irevol/minetest-citadel/commit/a926d4cf3d5f482656bc8edceb2995f949ca014b or earlier (before a workaround was added for this issue)
- Teleport/travel to (5, 2, 12)
- Look south and upwards, and see (or don't) the ghost

**With shaders disabled** the ghost is invisible.

screenshot_20240101_155727

**With shaders enabled** the ghost appears correctly.

screenshot_20240101_155832

### PR DESCRIPTION
**Pull request by SmallJoker**
With disabled shaders, the material EMT_TRANSPARENT_ALPHA_CHANNEL uses the parameter as an alpha threshold to decide whether to draw the texture. Thus lowering this limit fixes the issue of vanishing textures below alpha 128.

Fixes #14204

## To do

This PR is Ready for Review.

## How to test

1.- Set enable_shaders = false in MT
2. Install the Citadel game (ContentDB)
3. Teleport/travel to (5, 2, 12)
4. Look south and upwards, and see (or don't) the ghost
5. edit `games/citadel/mods/citadel_core/ghost.lua`. Modify the opacity in the line `self.object:set_texture_mod` to 10, 127, 128 and make sure the texture is still rendered.

### CODE REVIEW

File: src/client/content_cao.cpp [hunk 1]
```diff
@@ -325,7 +325,9 @@ void TestCAO::processMessage(const std::string &data)
 #include "clientobject.h"
 
 GenericCAO::GenericCAO(Client *client, ClientEnvironment *env):
-		ClientActiveObject(0, client, env)
+		ClientActiveObject(0, client, env),
+		m_material_type(video::EMT_TRANSPARENT_ALPHA_CHANNEL_REF),
+		m_material_type_param(0.5f)
```
Comment (sfan5) [inline src/client/content_cao.cpp:330]: are these values actually used? otherwise a bit confusing to init them here IMO

Comment (SmallJoker) [reply src/client/content_cao.cpp:330]: `m_material_type` happens to be assigned in every case. I felt like initializing the variables to a sane default that would then be changed later was a more reliable solution compared to potentially end up with uninitialized values.

Comment (sfan5) [reply src/client/content_cao.cpp:330]: If they're always meant to be overwritten I suggest putting clearly invalid values in there so this mistake is noticed.

File: src/client/content_cao.cpp [hunk 2]
```diff
@@ -634,8 +636,12 @@ void GenericCAO::addToScene(ITextureSource *tsrc, scene::ISceneManager *smgr)
 		u32 shader_id = shader_source->getShader("object_shader", material_type, NDT_NORMAL);
 		m_material_type = shader_source->getShaderInfo(shader_id).material;
 	} else {
-		m_material_type = (m_prop.use_texture_alpha) ?
-			video::EMT_TRANSPARENT_ALPHA_CHANNEL : video::EMT_TRANSPARENT_ALPHA_CHANNEL_REF;
+		if (m_prop.use_texture_alpha) {
+			m_material_type = video::EMT_TRANSPARENT_ALPHA_CHANNEL;
+			m_material_type_param = 1.0f / 256.f; // minimal alpha for texture rendering
```
Comment (grorp) [inline src/client/content_cao.cpp:641]: Wouldn't 0.0f have the same effect?

Comment (SmallJoker) [reply src/client/content_cao.cpp:641]: :shrug:

Comment (appgurueu) [reply src/client/content_cao.cpp:641]: Well, is it a `<` or `<=`? :sweat_smile:

**Review by sfan5 — APPROVED** [review]
LGTM

File: src/client/content_cao.cpp (hunk 2 above)
Comment (SmallJoker) [reply src/client/content_cao.cpp:641]: @appgurueu In L623 I put a note regarding this value. `0.5f` cuts off values below 128, hence this code will cut off at alpha = 0 which is already transparent.
