### PR TITLE
Make string to v3f parsing consistent, replace `core.setting_get_pos()` by `core.settings:get_pos()`

### LINKED ISSUE #14033: `Settings::getV3F()` and `minetest.setting_get_pos()` have inconsistant parsing
### Minetest version

```true
Minetest 5.8.0-dev-debug-79cc71851-dirty (Linux)
Using Irrlicht 1.9.0mt12
Using LuaJIT 2.1.1692716794
BUILD_TYPE=Debug
RUN_IN_PLACE=0
USE_CURL=1
USE_GETTEXT=1
USE_SOUND=1
STATIC_SHAREDIR="/usr/local/share/minetest"
STATIC_LOCALEDIR="/usr/local/share/locale"
```

### Operating system and version

Fedora 39

### Summary

`Settings::getV3F()`:

https://github.com/minetest/minetest/blob/6783734612832bd6a25adc3ddcd32f6a12c89249/src/settings.cpp#L563-L566

https://github.com/minetest/minetest/blob/6783734612832bd6a25adc3ddcd32f6a12c89249/src/util/string.cpp#L902-L911

`minetest.setting_get_pos()`:

https://github.com/minetest/minetest/blob/6783734612832bd6a25adc3ddcd32f6a12c89249/builtin/game/misc_s.lua#L42-L48

https://github.com/minetest/minetest/blob/6783734612832bd6a25adc3ddcd32f6a12c89249/builtin/common/misc_helpers.lua#L430-L446

---

Basically the C++ function only handle values like this: `(1, 2, 3)` while the Lua function handle also values like `1, 2, 3`.

C++ function should support both notations IMO.

### Steps to reproduce

Run some C++ code like this in the server context with `static_spawnpoint = (1, 2, 3)`:

```cpp
auto v = Settings::getV3F("static_spawnpoint");
warningstream << v.X << ", " << v.Y, ", " << v.Z << std::endl;
```

See that the values are printed to warning stream correctly. Check with `/kill` in devtest that the static spawn point works.

Set `static_spawnpoint = 1, 2, 3`. Try running the C++ code again and see `0, 0, 0` as output. Check again that static spawn point works in devtest. 

---

By the way, why is the spawnpoint handeled by C++ AND Lua? The Lua callback will always handle it I think.

https://github.com/minetest/minetest/blob/03ba9370b951f1c0904b53dfac3f5daf0bb354d6/src/server.cpp#L2846-L2865

https://github.com/minetest/minetest/blob/03ba9370b951f1c0904b53dfac3f5daf0bb354d6/src/server.cpp#L3791-L3796

https://github.com/minetest/minetest/blob/ade7a1cbcf7156ebddb12bd2ec2ea60818d72b19/builtin/game/static_spawn.lua#L3-L23

### PR DESCRIPTION
**Pull request by AFCMS**
Fix #14033 and #6062

## To do

This PR is Ready for Review.

- [x] Reimplement `str_to_v3f` ~~using regex~~
- [x] How to handle invalid parsing? The Lua version returns nil.
- [x] Implement the `Settings` class method `get_pos`
- [x] Implement the `Settings` class method `set_pos`
- [x] Deprecate the old Lua function `core.setting_get_pos`
- [x] Documentation
- [x] Tests

## How to test

Put that in the main function, see the results in console.

```cpp
    auto t = str_to_v3f("(1,2,3)").value();
    printf("(1,2,3) => v3f: %f, %f, %f\n", t.X, t.Y, t.Z);
    auto t2 = str_to_v3f("(-1.467247,2.23,323.23)").value();
    printf("(-1.467247,2.23,323.23) => v3f: %f, %f, %f\n", t2.X, t2.Y, t2.Z);
    auto t3 = str_to_v3f("-1,2.23, 323.23").value();
    printf("-1,2.23, 323.23 => v3f: %f, %f, %f\n", t3.X, t3.Y, t3.Z);
    auto t4 = str_to_v3f("(-1,2.23,323.23");
    if (!t4.has_value()) {
        printf("(-1,2.23,323.23 => v3f: null\n");
    }

    auto t5 = str_to_v3f("");
    if (!t5.has_value()) {
        printf("\"\" => v3f: null\n");
    }

    exit(0);
```

t1 and t2 should pass with both the new and the old implementation
t3 should pass ONLY with the new implementation (space)
t4 returns a zero vector with the new implementation at the moment (the Lua version returns nil instead)

Later in the function (if placed at the start it segfault):
```cpp
    std::optional<v3f> ttt;
    ttt = g_settings->getV3F("static_spawnpoint");

    v3f tttt = ttt.value_or(v3f());

    printf("static_spawnpoint: %f, %f, %f\n", tttt.X, tttt.Y, tttt.Z); // should be equal to your static spawn point or 0,0,0
```

Try the Lua methods in builtin or a mod:

```lua
core.register_on_joinplayer(function(player)
	core.settings:set_pos("static_spawnpoint", vector.new(0, 25, 0))
        core.log("error", dump(core.settings:get_pos("static_spawnpoint")))
end)
```

Run unittests also.

### CODE REVIEW

**Comment by AFCMS** [comment]
Would refactoring the function to return `std::optional<v3f>` be acceptable?

**Comment by HybridDog** [comment]
I remember that an `#include <regex>` has significantly slowed down the compilation speed when I used it a long time ago. Does this still happen?

**Comment by AFCMS** [comment]
Didn't notice any significant difference, but that's perhaps because I have a quite powerful CPU.

Maybe I should check more accurately.

**Comment by appgurueu** [comment]
> Would refactoring the function to return `std::optional<v3f>` be acceptable?

I would say so, yes.

**Comment by sfan5** [comment]
personal opinion: regex is too big for this, it's simpler to not use it.

**Comment by AFCMS** [comment]
I have started to build a regex free version, but refactoring the function to `std::optional<v3f>` will be painful.

**Comment by appgurueu** [comment]
> I have started to build a regex free version

:+1: I would suggest you use an istringstream in that case

> but refactoring the function to `std::optional<v3f>` will be painful

Why? There seem to be only two usages. If propagating the error properly is too painful / it is unclear what to do, just do the same thing as was previously done (`.value_or(v3f())` in optional terms) and add a `// FIXME` comment.

**Comment by AFCMS** [comment]
> > I have started to build a regex free version
> 
> 👍 I would suggest you use an istringstream in that case

I came with this:

```cpp
std::optional<v3f> str_to_v3f(std::string_view str) {
    v3f value = {0.0f, 0.0f, 0.0f};

    // Strip parentheses if they exist
    if (str.front() == '(' && str.back() == ')') {
        str.remove_prefix(1);
        str.remove_suffix(1);
    }

    // Replace commas with spaces
    std::string str_copy(str);
    for (char& ch : str_copy) {
        if (ch == ',') {
            ch = ' ';
        }
    }

    // Parse coordinates
    std::istringstream iss(str_copy);
    if (iss >> value.X >> value.Y >> value.Z) {
        return value;
    }

    return std::nullopt;
}
```

> > but refactoring the function to `std::optional<v3f>` will be painful
> 
> Why? There seem to be only two usages. If propagating the error properly is too painful / it is unclear what to do, just do the same thing as was previously done (`.value_or(v3f())` in optional terms) and add a `// FIXME` comment.

I started propagating the error like this but there are areas where it's a bit harder/lead to more verbose code.

File: src/server.cpp [hunk 1]
```diff
@@ -3870,7 +3870,10 @@ v3f Server::findSpawnPos()
 {
 	ServerMap &map = m_env->getServerMap();
 	v3f nodeposf;
-	if (g_settings->getV3FNoEx("static_spawnpoint", nodeposf))
+
+    std::optional<v3f> staticSpawnPoint;
+	if (g_settings->getV3FNoEx("static_spawnpoint", staticSpawnPoint) && staticSpawnPoint.has_value())
+        nodeposf = staticSpawnPoint.value();
```
Comment (sfan5) [inline src/server.cpp:3876]: bug!

File: src/util/string.cpp [hunk 2]
```diff
@@ -1069,25 +1069,28 @@ void safe_print_string(std::ostream &os, std::string_view str)
 	os.setf(flags);
 }
 
-const std::regex patternParenthesis(R"(^\((.*?)\)$)");
-const std::regex patternCoordinates(R"(^([\d.-]+)[,\s]\s*([\d.-]+)[,\s]\s*([\d.-]+)$)");
-
-v3f str_to_v3f(std::string_view str)
-{
+std::optional<v3f> str_to_v3f(std::string_view str) {
```
Comment (sfan5) [inline src/util/string.cpp:1072]:
```suggestion
std::optional<v3f> str_to_v3f(std::string_view str)
{
```

File: src/util/string.cpp [hunk 3]
```diff
@@ -1069,25 +1069,28 @@ void safe_print_string(std::ostream &os, std::string_view str)
...
     v3f value;
-    std::cmatch matches;
 
-    // Strip parentheses
-    if (std::regex_search(str.data(), str.data() + str.size(), matches, patternParenthesis)) {
-        str = std::string_view(matches[1].first, matches[1].length());
+    // Strip parentheses if they exist
+    if (str.front() == '(' && str.back() == ')') {
```
Comment (sfan5) [inline src/util/string.cpp:1076]: UB if str is empty

File: src/util/string.cpp [hunk 4]
```diff
@@ -1069,25 +1069,28 @@ void safe_print_string(std::ostream &os, std::string_view str)
...
-        value.Y = stof(matches[2].str());
-        value.Z = stof(matches[3].str());
+    // Parse coordinates
+    std::istringstream iss(str_copy);
+    if (iss >> value.X >> value.Y >> value.Z) {
+        return value;
     }
 
-    return value;
+    return std::nullopt;
```
Comment (sfan5) [inline src/util/string.cpp:1095]: can we add a handful of unit tests for the success and error case?

Comment (AFCMS) [reply src/util/string.cpp:1095]: Will add

**Comment by AFCMS** [comment]
Code isn't 100% functional right now, still working on it

File: src/util/string.cpp (hunk 3 above)
Comment (AFCMS) [reply src/util/string.cpp:1081]: Added a check :+1:

File: doc/lua_api.md [hunk 5]
```diff
@@ -9048,6 +9048,9 @@ means that no defaults will be returned for mod settings.
     * Is currently limited to mapgen flags `mg_flags` and mapgen-specific
       flags like `mgv5_spflags`.
     * Returns `nil` if `key` is not found.
+* `get_pos(key)`:
+    * Returns a `vector`
+    * Returns `nil` if no value is found of parsing failed.
```
Comment (sfan5) [inline doc/lua_api.md:9053]:
```suggestion
    * Returns `nil` if no value is found or parsing failed.
```

File: src/script/lua_api/l_settings.cpp [hunk 6]
```diff
@@ -176,6 +177,21 @@ int LuaSettings::l_get_flags(lua_State *L)
...
+    std::string key = std::string(luaL_checkstring(L, 2));
+
+    std::optional<v3f> pos;
+    if (o->m_settings->getV3FNoEx(key, pos) && pos.has_value()) {
+        push_v3f(L, pos.value());
+    } else {
+        lua_pushnil(L);
+    }
+    return 1;
+}
```
Comment (sfan5) [inline src/script/lua_api/l_settings.cpp:193]:
```suggestion
int LuaSettings::l_get_pos(lua_State *L)
{
    NO_MAP_LOCK_REQUIRED;
    LuaSettings *o = checkObject<LuaSettings>(L, 1);
    std::string key = luaL_checkstring(L, 2);

    std::optional<v3f> pos;
    if (o->m_settings->getV3FNoEx(key, pos) && pos.has_value())
        push_v3f(L, pos.value());
    else
        lua_pushnil(L);
    return 1;
}
```

Comment (AFCMS) [reply src/script/lua_api/l_settings.cpp:193]: I am really too used to Javascript lol

File: builtin/game/misc_s.lua [hunk 7]
```diff
@@ -36,11 +36,8 @@ end
 
 
 function core.setting_get_pos(name)
-	local value = core.settings:get(name)
-	if not value then
-		return nil
-	end
-	return core.string_to_pos(value)
+	core.log("deprecated", "Deprecated usage of setting_get_pos, use core.settings:get_pos() instead")
```
Comment (appgurueu) [inline builtin/game/misc_s.lua:39]: Question: What's the value of this deprecation warning? Given that this is just an alias, it should be pretty harmless to keep around for basically forever.

Modders will be annoyed by the deprecation warnings, and would have to do something like `core.settings.get_pos and core.settings:get_pos(name) or core.setting_get_pos(name)`, or patch out the deprecation warning at a game / mod level.

File: src/util/string.cpp [hunk 8]
```diff
@@ -1068,14 +1069,33 @@ void safe_print_string(std::ostream &os, std::string_view str)
...
+        return std::nullopt;
+    }
+
+    // Strip parentheses if they exist
+    if (str.front() == '(' && str.back() == ')') {
+        str.remove_prefix(1);
+        str.remove_suffix(1);
+    }
+
+    // Replace commas with spaces
```
Comment (appgurueu) [inline src/util/string.cpp:1086]: Technically overly permissive: This will accept e.g. `,,1,2 , ,, 3<arbitrary suffix>`

Here's how I would go about this (without regex): Suppose you had a lambda `skip_delimiter` like this

```c++
const auto expect_delimiter = [&]() {
    const auto c = iss.get();
    return c == ' ' || c == ',';
};
```

(This could also be a function taking `iss` as a mutable reference, but you do really want it to be namespaced to just `str_to_v3f`.)

Then you could do

```c++
v3f value;
if (!(iss >> value.X)) return std::nullopt;
if (!expect_delimiter()) return std::nullopt;
if (!(iss >> value.Y)) return std::nullopt;
if (!expect_delimiter()) return std::nullopt;
if (!(iss >> value.Z)) return std::nullopt;
```

p.s. Writing parsers is something where you should be able to turn your brain off, because how grammars translate to recursive descent parsing is usually quite straightforward.

File: src/script/lua_api/l_settings.cpp [hunk 9]
```diff
@@ -226,6 +242,22 @@ int LuaSettings::l_set_np_group(lua_State *L)
...
 }
 
+// set_pos(self, key, value)
+int LuaSettings::l_set_pos(lua_State *L)
+{
+    NO_MAP_LOCK_REQUIRED;
+    LuaSettings *o = checkObject<LuaSettings>(L, 1);
+
+    std::string key = std::string(luaL_checkstring(L, 2));
+    v3f value = read_v3f(L, 3);
```
Comment (appgurueu) [inline src/script/lua_api/l_settings.cpp:252]: Shouldn't this use `check_v3f` to be strict about what we accept?

File: src/script/lua_api/l_settings.cpp [hunk 10]
```diff
@@ -226,6 +242,22 @@ int LuaSettings::l_set_np_group(lua_State *L)
 	return 0;
 }
 
+// set_pos(self, key, value)
+int LuaSettings::l_set_pos(lua_State *L)
+{
+    NO_MAP_LOCK_REQUIRED;
+    LuaSettings *o = checkObject<LuaSettings>(L, 1);
+
+    std::string key = std::string(luaL_checkstring(L, 2));
```
Comment (appgurueu) [inline src/script/lua_api/l_settings.cpp:251]:
```suggestion
    std::string key = luaL_checkstring(L, 2);
```

the copy assignment constructor should already do the job.

File: src/mapgen/mapgen_fractal.cpp [hunk 11]
```diff
@@ -103,8 +103,17 @@ void MapgenFractalParams::readParams(const Settings *settings)
 	settings->getS16NoEx("mgfractal_dungeon_ymax",         dungeon_ymax);
 	settings->getU16NoEx("mgfractal_fractal",              fractal);
 	settings->getU16NoEx("mgfractal_iterations",           iterations);
-	settings->getV3FNoEx("mgfractal_scale",                scale);
-	settings->getV3FNoEx("mgfractal_offset",               offset);
+
+    std::optional<v3f> mgfractalScale;
+    if (settings->getV3FNoEx("mgfractal_scale", mgfractalScale) && mgfractalScale.has_value()) {
+        scale = mgfractalScale.value();
```
Comment (appgurueu) [inline src/mapgen/mapgen_fractal.cpp:109]: Nitpick:

```suggestion
        scale = *mgfractalScale;
```

whenever you have already ensured that a value is present, use `*optional` instead of `optional.value()`, which includes a (then unnecessary) check for whether a value is present.

Also applies to a couple `.value()` calls below.

File: src/util/string.h [hunk 12]
```diff
@@ -794,4 +795,4 @@ void safe_print_string(std::ostream &os, std::string_view str);
  * @param str string
  * @return float vector
  */
-v3f str_to_v3f(std::string_view str);
+std::optional<v3f> str_to_v3f(std::string_view str);
```
Comment (appgurueu) [inline src/util/string.h:798]: The doc comment here should probably be updated to say that the parenthesis are optional.

File: builtin/game/misc_s.lua (hunk 7 above)
Comment (AFCMS) [reply builtin/game/misc_s.lua:39]: I will remove it, it will annoy projects like VoxeLibre which support the last two versions of Luanti.

File: src/util/string.cpp [hunk 13]
```diff
@@ -1068,14 +1068,33 @@ void safe_print_string(std::ostream &os, std::string_view str)
...
+        return std::nullopt;
+    }
+
+    // Strip parentheses if they exist
+    if (str.front() == '(' && str.back() == ')') {
+        str.remove_prefix(1);
+        str.remove_suffix(1);
+    }
+
+    std::istringstream iss((std::string(str)));
```
Comment (appgurueu) [inline src/util/string.cpp:1085]:
```suggestion
    std::istringstream iss(std::string(str));
```

File: src/script/lua_api/l_settings.cpp [hunk 14]
```diff
@@ -176,6 +177,21 @@ int LuaSettings::l_get_flags(lua_State *L)
...
+// get_pos(self, key) -> vector or nil
+int LuaSettings::l_get_pos(lua_State *L)
+{
+    NO_MAP_LOCK_REQUIRED;
+    LuaSettings *o = checkObject<LuaSettings>(L, 1);
+    std::string key = luaL_checkstring(L, 2);
+
+    std::optional<v3f> pos;
+    if (o->m_settings->getV3FNoEx(key, pos) && pos.has_value())
+        push_v3f(L, pos.value());
```
Comment (appgurueu) [inline src/script/lua_api/l_settings.cpp:189]:
```suggestion
        push_v3f(L, *pos);
```

File: src/server.cpp [hunk 15]
```diff
@@ -3870,8 +3870,13 @@ v3f Server::findSpawnPos()
 {
 	ServerMap &map = m_env->getServerMap();
 	v3f nodeposf;
-	if (g_settings->getV3FNoEx("static_spawnpoint", nodeposf))
-		return nodeposf * BS;
+
+    std::optional<v3f> staticSpawnPoint;
+	if (g_settings->getV3FNoEx("static_spawnpoint", staticSpawnPoint) && staticSpawnPoint.has_value())
+    {
+        nodeposf = staticSpawnPoint.value();
```
Comment (appgurueu) [inline src/server.cpp:3877]:
```suggestion
       return *staticSpawnPoint * BS;
```

then get rid of the `v3f nodeposf;` above (you will have to introduce a `v3f` a bit below, basically you're making the scope more limited)

File: src/settings.cpp [hunk 16]
```diff
@@ -626,7 +626,11 @@ bool Settings::getNoiseParamsFromGroup(const std::string &name,
 
 	group->getFloatNoEx("offset",      np.offset);
 	group->getFloatNoEx("scale",       np.scale);
-	group->getV3FNoEx("spread",        np.spread);
+
+    std::optional<v3f> spread;
+	if (group->getV3FNoEx("spread", spread) && spread.has_value())
+        np.spread = spread.value();
```
Comment (appgurueu) [inline src/settings.cpp:632]:
```suggestion
        np.spread = *spread;
```

File: src/util/string.cpp [hunk 17]
```diff
@@ -1068,14 +1068,33 @@ void safe_print_string(std::ostream &os, std::string_view str)
...
+        return c == ' ' || c == ',';
+    };
+
+    v3f value;
+    if (!(iss >> value.X)) return std::nullopt;
+    if (!expect_delimiter()) return std::nullopt;
+    if (!(iss >> value.Y)) return std::nullopt;
+    if (!expect_delimiter()) return std::nullopt;
+    if (!(iss >> value.Z)) return std::nullopt;
+
```
Comment (appgurueu) [inline src/util/string.cpp:1098]: It's possible I forgot about this in my initial comment but we still need to check that there isn't a non-whitespace suffix here. So something like

```c++
while (!iss.eof()) if (!std::isspace(iss.get())) return std::nullopt;
```

please also consider adding a unit test like `1, 2, 3 test` which should result in `std::nullopt`

File: src/client/hud.cpp [hunk 18]
```diff
@@ -54,14 +54,14 @@ Hud::Hud(Client *client, LocalPlayer *player,
...
-	v3f crosshair_color = g_settings->getV3F("crosshair_color");
+	v3f crosshair_color = g_settings->getV3F("crosshair_color").value_or(v3f());
 	u32 cross_r = rangelim(myround(crosshair_color.X), 0, 255);
 	u32 cross_g = rangelim(myround(crosshair_color.Y), 0, 255);
 	u32 cross_b = rangelim(myround(crosshair_color.Z), 0, 255);
 	u32 cross_a = rangelim(g_settings->getS32("crosshair_alpha"), 0, 255);
 	crosshair_argb = video::SColor(cross_a, cross_r, cross_g, cross_b);
 
-	v3f selectionbox_color = g_settings->getV3F("selectionbox_color");
+	v3f selectionbox_color = g_settings->getV3F("selectionbox_color").value_or(v3f());
```
Comment (nerzhul) [inline src/client/hud.cpp:64]: sounds like you are a rust programmer

Comment (nerzhul) [reply src/client/hud.cpp:64]: i'd prefer we add a default setting in getV3F with a default= v3f()

File: src/unittest/test_settings.cpp [hunk 19]
```diff
@@ -94,7 +96,9 @@ const char *TestSettings::config_text_after =
 	"	spread = (250,250,250)\n"
 	"}\n"
 	"zoop = true\n"
-	"coord2 = (1,2,3.3)\n"
+	"coord2 = (1,2,3.25)\n"
+    "coord_invalid = (1,2,3\n"
```
Comment (nerzhul) [inline src/unittest/test_settings.cpp:100]: please add tests like this to ensure how wrong things (and very stupid) works:
*  (wtf, is, this)
* (1, wtf, 3)
* ()
* (1, 2)
* (1)

File: src/client/hud.cpp (hunk 18 above)
Comment (appgurueu) [reply src/client/hud.cpp:64]: Optionals are perfectly fine for this

File: src/unittest/test_settings.cpp (hunk 19 above)
Comment (appgurueu) [reply src/unittest/test_settings.cpp:100]: yeah, more error cases are probably good

File: src/client/hud.cpp (hunk 18 above)
Comment (AFCMS) [reply src/client/hud.cpp:64]: > sounds like you are a rust programmer

I want to be one but not yet :sweat_smile:

**Review by appgurueu — APPROVED** [review]
Looks good to me now, the unit tests are sensible and pass.

File: src/util/string.cpp [hunk 20]
```diff
@@ -1068,14 +1068,35 @@ void safe_print_string(std::ostream &os, std::string_view str)
...
+    while (!iss.eof()) if (!std::isspace(iss.get())) return std::nullopt;
```
Comment (sfan5) [inline src/util/string.cpp:1099]: 1. blatant code style violation
2. it makes more sense to trim again after removing braces

File: src/util/string.cpp [hunk 21]
```diff
@@ -1072,16 +1072,17 @@ std::optional<v3f> str_to_v3f(std::string_view str)
...
         return std::nullopt;
-    }
 
     // Strip parentheses if they exist
     if (str.front() == '(' && str.back() == ')') {
         str.remove_prefix(1);
         str.remove_suffix(1);
     }
 
+    str = trim(str);
```
Comment (appgurueu) [inline src/util/string.cpp:1084]: Nitpick: I'd move this inside the "strip parenthesis" if body, makes the logic more obvious IMO.

**Review by sfan5 — APPROVED** [review]
looks ok

File: src/client/hud.cpp (hunk 18 above)
Comment (nerzhul) [reply src/client/hud.cpp:64]: @appgurueu it's not a common C++ mode, generally we use defaults as it's permitted in this language :)

Comment (nerzhul) [reply src/client/hud.cpp:64]: we are here introducing a new pattern not present in our codebase, i'm not sure it's a good idea

**Review by nerzhul — APPROVED** [review]
