### PR TITLE
Resize hotbar immediately before drawing

### LINKED ISSUE #12852: Held items jumpscare on world startup
##### Minetest version
```
1317cd1 (post preprocessing)
```

##### OS / Hardware
Operating system: Arch Linux
CPU: AMD Phenom II X4 955

GPU model: AMD Radeon RX 560
OpenGL version: 4.6

##### Summary
Ever since the postprocessing pipeline was merged, usually when starting up a world your held items will fill the entire screen for a split second, similar to how it acts when an item in the hotbar goes off-screen if the window size is too small.

##### Steps to reproduce
Launch into a world, preferrably one where you have some items in your hotbar, and your hotbar items will fill the entire screen for a split second. Boo!

image

### PR DESCRIPTION
**Pull request by x2048**
Avoids incorrect rendering when hotbar uses outdated screen dimensions

Fixes #12852.

## To do

This PR is Ready for Review.

## How to test

1. Set fps = 2
2. Start the game (assuming you have at least one node item in the inventory)
      - NO fullscreen inventory item should be rendered in the first frame.
3. Press ESC
4. Resize the window quickly (maximize/restore)
      - no fullscreen inventory item should be rendered in any frame.

### CODE REVIEW

**Review by sfan5 — APPROVED** [review]

File: src/client/render/plain.cpp [hunk 1]
```diff
@@ -52,6 +52,7 @@ void DrawHUD::run(PipelineContext &context)
 		if (context.draw_crosshair)
 			context.hud->drawCrosshair();
 
+		context.hud->resizeHotbar();
 		context.hud->drawHotbar(context.client->getEnv().getLocalPlayer()->getWieldIndex());
```
Comment (nerzhul) [inline src/client/render/plain.cpp:56]: it's not possible to enforce resize on drawHotbar function
 directly if it's mandatory ?

Comment (x2048) [reply src/client/render/plain.cpp]: I've moved it before drawCrosshair() call because otherwise crosshair is jumping around on screen when using hotkeys to resize the window (e.g. maximize/minimize).
