### PR TITLE
RTT fixes

### LINKED ISSUE #4214: Update RTT in F5 debug info
Strangely enough I've noticed that RTT (round trip time) is updated only on connect in F5 info text, it is useful to check network with it, can you make it update once a second or so as before?

### PR DESCRIPTION
**Pull request by HybridDog**
Small code changes: remove duplicate code and use assert where rtt should not be negative
When the server probably crashed, after 2 seconds show the time since crash instead of average RTT because the average RTT doesn't longer pertain in this case
 The RTT usually is less than 2 seconds I hope 
Fix #4214 (please test)

### CODE REVIEW

**Comment by SmallJoker** [comment]
I've noticed that the average RTT value is very solid. It does only seems to change a little over a big time period, which is why it might be better to reduce the sample rate a bit.

**Comment by HybridDog** [comment]
I don't know why it's set to MAX_RELIABLE_WINDOW_SIZE * 10 = 327680.

File: src/network/connection.cpp [hunk 1]
```diff
@@ -825,8 +825,9 @@ void Peer::DecUseCount()
 	delete this;
 }
 
-void Peer::RTTStatistics(float rtt, const std::string &profiler_id,
-		unsigned int num_samples) {
+void Peer::RTTStatistics(float rtt, const std::string &profiler_id)
+{
+	static const float avg_factor = 0.1 / MAX_RELIABLE_WINDOW_SIZE;
```
[the remark this answers is not in the document]
Comment (HybridDog) [reply src/network/connection.cpp]: I didn't use a float constant because l think the number is calculated during compile time, so a double division followed by a float conversion would be more precise.

File: src/network/connection.cpp [hunk 2]
```diff
@@ -825,8 +825,9 @@ void Peer::DecUseCount()
 	delete this;
 }
 
-void Peer::RTTStatistics(float rtt, const std::string &profiler_id,
-		unsigned int num_samples) {
+void Peer::RTTStatistics(float rtt, const std::string &profiler_id)
+{
+	static const float avg_factor = 0.1f / MAX_RELIABLE_WINDOW_SIZE;
```
Comment (nerzhul) [inline src/network/connection.cpp]: seems to be constexpr const instead of just const

Comment (sfan5) [reply src/network/connection.cpp]: `MAX_RELIABLE_WINDOW_SIZE` is a define, so const should be okay

**Comment by SmallJoker** [comment]
@nerzhul Would it be any issue if we changed the sample rate to `MAX_RELIABLE_WINDOW_SIZE` or `MAX_RELIABLE_WINDOW_SIZE / 10.f`? The current 300k samples seem to be quite high, which causes the average value to change very slowly.

File: src/network/connection.cpp [hunk 3]
```diff
@@ -837,32 +838,26 @@ void Peer::RTTStatistics(float rtt, const std::string &profiler_id,
 
 		/* do average calculation */
 		if (m_rtt.avg_rtt < 0.0)
-			m_rtt.avg_rtt  = rtt;
+			m_rtt.avg_rtt = rtt;
 		else
-			m_rtt.avg_rtt  = m_rtt.avg_rtt * (num_samples/(num_samples-1)) +
-								rtt * (1/num_samples);
+			m_rtt.avg_rtt = m_rtt.avg_rtt +
```
Comment (HybridDog) [inline src/network/connection.cpp]: `m__rtt.avg_rtt += […]`

**Comment by HybridDog** [comment]
This looks like the commit where RTT calculation changed: @sapier https://github.com/minetest/minetest/commit/9edb91da5754cf194637d1d7faa513719b61f9b4#diff-a2a82fe964a7b85f20cd5239d386184aL500
Before, avg_factor was 0.1.

**Comment by SmallJoker** [comment]
@sfan5, @nerzhul: Could you please update (refresh or discard) your reviews when you've got some time?
