### PR TITLE
Fix server steps shorter than dedicated_server_step since #13370

### LINKED ISSUE #15193: Different globalstep compared to <5.9?
### Minetest version

```true
5.9.1 (both server and client)
```

### Irrlicht device

_No response_

### Operating system and version

Pop!_OS 22.04 LTS

### CPU model

i7

### GPU model

_No response_

### Active renderer

OpenGL

### Summary

Things relying on small afters go slower than they used to, at least online. I had a report from an AES user and I can reproduce that as well. ~~There is no declared `dedicated_server_step` in our `minetest.conf`~~ silly me, it's 0.1

### Steps to reproduce

1. download Block League from CDB
2. put it in a local world of yours
3. take from creative the submachine gun and shoot by holding down left click: everything works flawlessly
4. now join the AES server
5. play a Block League game or play the tutorial
6. try shooting with the submachine gun: see that it goes slower than in local. Stamina bar also stutters when reloading, something that didn't happen earlier

Submachine gun should shoot every `0.1` (see [here](https://gitlab.com/zughy-friends-minetest/block_league/-/blob/master/block_league/src/weapons/smg.lua?ref_type=heads#L50)). This is also noticeable with the peacifier, which shoots slightly slower than in local (it should shoot every `0.2`, see [here](https://gitlab.com/zughy-friends-minetest/block_league/-/blob/master/block_league/src/weapons/peacifier.lua?ref_type=heads#L50))

### PR DESCRIPTION
**Pull request by grorp**
Fixes #15193
Closes #15325

This is an alternative to #15325 (which does not fix #15193)

This PR makes `dedicated_server_step` a lower bound for step dtime on dedicated servers again. For explanation, see https://github.com/minetest/minetest/pull/15325#issuecomment-2436136992 and https://github.com/minetest/minetest/pull/15325#issuecomment-2436216151.

## To do

This PR is a Ready for Review.

## How to test

Confirm that this PR fixes #15193: Set `dedicated_server_step = 0.1`, download [the mod in question](https://content.minetest.net/packages/Zughy/block_league/) and see that the SMG shoots fast again on a dedicated server.

------

Or confirm that this PR does what it promises:

```lua
-- for dedicated_server_step = 0.1
core.register_globalstep(function(dtime)
  assert(dtime == 0 or dtime >= 0.1)
end)
```

The assertion succeeds on 5.8.0, fails on the master branch and succeeds again with this PR.

-----

Or use test code from https://codeberg.org/Desour/test_tmp/src/branch/different_globalstep_15193/init.lua to measure how the server step and `core.after` behave on a dedicated server. You'll see that `core.after` with the target server step as wait time works properly again.

### CODE REVIEW

**Comment by grorp** [comment]
The alternative approach avoiding the busy-waiting would be this: 44d344c2c856c6cde2193fac9b5caee7ffc5d7e4

The results are not as nice, but probably still acceptable (`dedicated_server_step = 0.1`):

```
realtime   : N=50 μ=102.020040 σ=9.055835 MIN=94.968000 MAX=163.541000
ingame time: N=50 μ=101.932500 σ=9.068429 MIN=100.198999 MAX=165.392995
dtime      : N=50 μ=101.932500 σ=9.068429 MIN=100.198999 MAX=165.392995
actualdtime: N=50 μ=102.016940 σ=9.089439 MIN=95.285000 MAX=163.853000

realtime   : N=50 μ=101.828380 σ=9.224372 MIN=95.689000 MAX=164.793000
ingame time: N=50 μ=101.895380 σ=8.955755 MIN=100.050002 MAX=164.566994
dtime      : N=50 μ=101.895380 σ=8.955755 MIN=100.050002 MAX=164.566994
actualdtime: N=50 μ=101.831720 σ=9.244566 MIN=95.691000 MAX=164.948000

realtime   : N=50 μ=100.556120 σ=1.389382 MIN=96.379000 MAX=103.453000
ingame time: N=50 μ=100.545860 σ=0.292561 MIN=100.004002 MAX=101.106003
dtime      : N=50 μ=100.545860 σ=0.292561 MIN=100.004002 MAX=101.106003
actualdtime: N=50 μ=100.555840 σ=1.389041 MIN=96.392000 MAX=103.454000

realtime   : N=50 μ=100.613000 σ=1.715025 MIN=94.688000 MAX=104.776000
ingame time: N=50 μ=100.646800 σ=0.454447 MIN=100.032002 MAX=103.147998
dtime      : N=50 μ=100.646800 σ=0.454447 MIN=100.032002 MAX=103.147998
actualdtime: N=50 μ=100.613220 σ=1.600994 MIN=94.686000 MAX=104.776000
```

**Comment by Desour** [comment]
>Open question: The other PR needed to adjust the yieldToOtherThreads workaround logic. Do I need to do this too?

Yes, I think so. Just add 1 ms (like before https://github.com/minetest/minetest/pull/15325/commits/5e078b5c4d8f9278b1fcdf91b1c7eb320c606dbc in my PR).

>Now it actually busy-waits.

Not ok.

>The alternative approach avoiding the busy-waiting would be this: https://github.com/minetest/minetest/commit/44d344c2c856c6cde2193fac9b5caee7ffc5d7e4

Just round up by adding 999 us before dividing (for the likely special case of 0).

---

Doc added by #15316 needs adjustment.

**Comment by grorp** [comment]
> Doc added by https://github.com/minetest/minetest/pull/15316 needs adjustment.

I had already adjusted that (simply removed the problem note again), do you have more suggestions?

**Comment by grorp** [comment]
Made some logging code for the new version of this PR: acb005bc14c875f3e54bc2ebb6a5c1f76cb3b25c. Here's what it looks like on a "normal" server:
```
Server::Receive with timeout = 97943 us
	ReceiveTimeoutMs with remaining time = 97916 us; timeout = 98 ms  -> got packet
	ReceiveTimeoutMs with remaining time = 66571 us; timeout = 67 ms  -> got packet
	ReceiveTimeoutMs with remaining time = 16692 us; timeout = 17 ms  -> no packet

Server::Receive with timeout = 99401 us
	ReceiveTimeoutMs with remaining time = 99378 us; timeout = 100 ms  -> no packet

Server::Receive with timeout = 8499 us
	ReceiveTimeoutMs with remaining time = 8468 us; timeout = 9 ms  -> got packet
	ReceiveTimeoutMs with remaining time = 8438 us; timeout = 9 ms  -> no packet
```


Or on a lagging server:
```
Server::Receive with timeout = -47132 us
	ReceiveTimeoutMs with remaining time = 0 us; timeout = 0 ms  -> got packet
	ReceiveTimeoutMs with remaining time = 0 us; timeout = 0 ms  -> no packet

Server::Receive with timeout = -71382 us
	ReceiveTimeoutMs with remaining time = 0 us; timeout = 0 ms  -> got packet
	ReceiveTimeoutMs with remaining time = 0 us; timeout = 0 ms  -> got packet
	ReceiveTimeoutMs with remaining time = 0 us; timeout = 0 ms  -> got packet
	ReceiveTimeoutMs with remaining time = 0 us; timeout = 0 ms  -> no packet

Server::Receive with timeout = -46106 us
	ReceiveTimeoutMs with remaining time = 0 us; timeout = 0 ms  -> no packet
```

File: src/server.cpp [hunk 1]
```diff
@@ -1101,15 +1102,17 @@ void Server::Receive(float timeout)
 		pkt.clear();
 		peer_id = 0;
 		try {
+			// Round up since the target step length is the minimum step length,
+			// we only have millisecond precision and we don't want to busy-wait by calling
+			// ReceiveTimeoutMs(.., 0) repeatedly.
+			// Also be sure we don't wait if the remaining time is zero/negative.
```
Comment (Desour) [inline src/server.cpp:1109]: I don't think this last line makes sense if the reader hasn't seen the std::max alternative.
(`remaining_time_us()` is always non-negative and receive with timeout 0 is fine.)
```suggestion
```

File: src/server.cpp [hunk 2]
```diff
@@ -1084,6 +1085,7 @@ void Server::AsyncRunStep(float dtime, bool initial_step)
 	m_shutdown_state.tick(dtime, this);
 }
 
+//! Receive all incoming packets and wait for at least `timeout` seconds.
 void Server::Receive(float timeout)
```
Comment (Desour) [inline src/server.cpp:1089]: We usually only use doxygen in headers. https://dev.minetest.net/Code_style_guidelines#Comments

**Review by Desour — APPROVED** [review]
Tested. Works as expected. :+1: 

(With the default 0.09 dedicat step, and after 0.1, one step never seems to reach 0.1, so this is also fine.)

File: src/server.cpp [hunk 3]
```diff
@@ -1101,15 +1102,16 @@ void Server::Receive(float timeout)
...
-					(u32)remaining_time_us() / 1000)) {
+					((u32)remaining_time_us() + 999) / 1000)) {
 				// No incoming data.
-				// Already break if there's 1ms left, as ReceiveTimeoutMs is too coarse
-				// and a faster server-step is better than busy waiting.
-				if (remaining_time_us() < 1000.0f)
-					break;
-				else
+				if (remaining_time_us() > 0.0f)
 					continue;
```
Comment (grorp) [inline src/server.cpp:1112]: I guess this condition will never trigger except if `ReceiveTimeoutMs` doesn't wait as long as it should, since we're already waiting >= `remaining_time_us()` with `ReceiveTimeoutMs` above.

Comment (Desour) [reply src/server.cpp:1112]: `Semaphore::wait()` doesn't try again on EINTR, so it can trigger.

(Sidemark: `ReceiveTimeoutMs` can also wait infinity long, looks like a problem to me, but not for this PR.)

**Comment by grorp** [comment]
For reference: Also tested by Zughy. https://irc.minetest.net/minetest-dev/2024-10-27#i_6211614

File: src/server.cpp [hunk 4]
```diff
@@ -1101,15 +1102,16 @@ void Server::Receive(float timeout)
 		pkt.clear();
 		peer_id = 0;
 		try {
+			// Round up since the target step length is the minimum step length,
+			// we only have millisecond precision and we don't want to busy-wait by calling
+			// ReceiveTimeoutMs(.., 0) repeatedly.
```
Comment (sfan5) [inline src/server.cpp:1107]: since we have a float anyway this would be more straightforward:
`const u32 cur_timeout = std::ceil(remaining_time_us() / 1000.0f);`

File: src/server.h [hunk 5]
```diff
@@ -205,6 +205,7 @@ class Server : public con::PeerHandler, public MapEventReceiver,
 
 	// This is run by ServerThread and does the actual processing
 	void AsyncRunStep(float dtime, bool initial_step = false);
+	// Receive all incoming packets and wait for at least `timeout` seconds.
```
Comment (sfan5) [inline src/server.h:208]:
```suggestion
	/// Receive and process all incoming packets. Sleep if the time goal isn't met.
	/// @param timeout minimum time to take [s]
```

Comment (grorp) [reply src/server.h]: Hah, "timeout" is pretty much the opposite of "minimum time", the name is really misleading now. Renamed to "min_time".
