### PR TITLE
Fix inconsistent craft replacements (#9250)

### LINKED ISSUE #9250: Inconsistency with crafting replacements with multiple inputs
##### Minetest version
```
5.2.0-dev-e20f2539, 5.1.0, and probably earlier
```

##### OS / Hardware
N/A

##### Summary

There is some inconsistency with crafting w/ the results of crafting recipes w/ replacements, and I don't know what the correct behaviour is. If a recipe lists a replacement, and there are multiple instances of the "source" item in the recipe, you will get a varying number of replacements, depending on various things. 

##### Steps to reproduce

I noticed this behaviour while using unified_inventory (and sometimes unified_inventory_plus), but it works the same w/ the default inventory screen. Because there are no recipes w/ replacements in minetest_game, we'll have to add a mod w/ a few recipes for tests:

```
-- 1
minetest.register_craft({
    output = "default:stone",
    recipe = {{"default:cactus", "default:cactus", "default:stick"}},
    replacements = {{"default:cactus", "default:cactus"}}
})

-- 2
minetest.register_craft({
    output = "default:stone",
    recipe = {{"default:dirt", "default:dirt", "default:stick"}},
    replacements = {{"default:dirt", "default:dirt 2"}}
})

-- 3
minetest.register_craft({
    output = "default:stone",
    recipe = {{"default:cactus", "default:stick"}},
    replacements = {{"default:cactus", "default:cactus"}}
})

-- 4
minetest.register_craft({
    output = "default:stone",
    recipe = {{"default:dirt", "default:stick"}},
    replacements = {{"default:dirt", "default:dirt 2"}}
})
```
Note that recipes (1) and (2) demonstrate the issue; recipes (3) and (4) are just provided for reference. Also note that recipes that replace multiple different kinds of items behave like (3) and (4), as long as there is only a single instance of each "source" item in the recipe. 

number of replacement items received after | recipe 1 | recipe 2 | recipe 3 | recipe 4
-- | -- | -- | -- | --
crafting a single item, crafting grid empty afterwards | 1 | 2 | 1 | 2
crafting a single item, crafting grid retains more ingredients | 2 | 4 | 1 | 2
crafting 10 items, crafting grid empty afterwards | 19 | 38 | 10 | 20
crafting 10 items, crafting grid retains more ingredients | 20 | 40 | 10 | 20

The real result of this behaviour, is that different mods seem to assume that the replacements in crafting recipes work differently; some have recipes like recipe (1), and some have recipes like (2). With recipes like (1), however, you don't always get the replacements you expected, and with (2), you can easily end up w/ many more replacements than you should get, which is technically an exploit. 

My intuition, looking at this data, is that the code that is used to add replacements in the crafting grid after a craft only replaces a single instance of an item in a recipe, whereas the code that adds replacements to the player's inventory replaces all of them, and that the former should be made to behave like the latter. I'd like some input from people more familiar w/ the code and the intentions, though.

### PR DESCRIPTION
**Pull request by Wuzzy2**
Fixes #9250.

How to test:

Use this recipe in MTG:
```
minetest.register_craft({
	type = "shaped",
	recipe = {
		{"group:leaves", "default:apple"},
		{"default:apple", "group:leaves"},
	},
	output = "default:dirt",
	replacements = {
		{"group:leaves", "default:sapling"},
	},
})
```

Craft this recipe.
One time craft it with exactly 1 of each of the 4 recipe input slots in the grid.
The other time, craft it with exactly 2 of each recipe input slots in the grid.

Both times, you should get 1 dirt as regular output plus 1 sapling.
In the first time, the sapling appears in the crafting grid.
In the second time, the sapling appears in your inventory instead.

(The bug was that in the second time, you might end up with 2 instead of 1 sapling, depending on the stack sizes of your input items.)

Shoutout to @p-ouellette!

### CODE REVIEW

**Review by TurkeyMcMac — APPROVED** [review]
Works.

File: src/craftdef.cpp [hunk 1]
```diff
@@ -229,6 +229,7 @@ static void craftDecrementOrReplaceInput(CraftInput &input,
 				rep.deSerialize(j->second, gamedef->idef());
 				item.remove(1);
 				found_replacement = true;
+				pairs.erase(j);
```
Comment (sfan5) [inline src/craftdef.cpp:232]: the way it is right now is not safe while iterating the list
bad:
```cpp
for (auto j = pairs.begin(); j != pairs.end(); j++) {
  if (any condition)
    pairs.erase(j);
}
```
good:
```cpp
for (auto j = pairs.begin(); j != pairs.end(); ) {
  if (any condition)
    j = pairs.erase(j);
  else
    j++;
}
```

Comment (TurkeyMcMac) [reply src/craftdef.cpp:232]: I think it's fine, since the loop breaks right after erasing.

Comment (savilli) [reply src/craftdef.cpp:232]: @sfan5 your good example is also incorrect. `std::vector` invalidates any iterator after `erase` call, because `vector::iterator` points to the `vector::data`, and vector resizing can result in reallocation.

This `erase` is fine, because of `break` later.

**Comment by Wuzzy2** [comment]
So I'm not going to change this PR because of the `break` statements, until a maintainer says otherwise (and it's still functional).

**Comment by fluxionary** [comment]
There's still a bug somewhere.

use this recipe:
```lua
minetest.register_craft({
    type = "shapeless",
    output = "default:tree",
    recipe = {"default:wood", "default:wood", "default:stick", "default:stick"},
    replacements = {
        {"default:wood", "default:coal_lump"},
        {"default:wood", "default:coal_lump"},
        {"default:stick", "default:stick"},
    },
})
```
expected results after crafting w/ stacks of count 2 in the crafting grid, crafting a single item: 
* get 1 `default:tree`
* get 2 `default:coal_lump` in main inventory
* get 1 `default:stick` in main inventory
* crafting grid still contains 2 stacks of 1 `default:wood` and 2 stacks of 1 `default:stick`.

however, you will end up w/ *2* `default:stick` in main inventory instead of 1 (everything else as expected).

**Comment by TurkeyMcMac** [comment]
I can't reproduce your issue.

**Comment by fluxionary** [comment]
> I can't reproduce your issue.

you're right, i was running the test in the wrong window. everything works fine now.
