### PR TITLE
Don't display page-nav buttons when #store.packages == 0

### LINKED ISSUE #7436: Browse online content: Lua error on arrow click when list is empty
##### Issue type

 - Bug report
 
##### Minetest version

```
0.5.0-git
```

##### OS / Hardware

Operating system: Windows 7
CPU: Intel Core i3-2120

GPU model: ATI X800GTO
OpenGL version: 2.1

##### Summary

If you don't receive list of packages in "Browse online content" you are presented with empty list, if you click on "<" or ">>" - it gives lua error:
default

```
ERROR[Main]: https://content.minetest.net/packages/ not found (Timeout was reached) (response code 200)
ERROR[Main]: Invalid JSON download 
ERROR[Main]: Main menu error: Runtime error from mod '' in callback handleMainMenuButtons(): ...Games\11111\bin\..\builtin\mainmenu\dlg_contentstore.lua:148: attempt to index local 'package' (a nil value)
ERROR[Main]: stack traceback:
ERROR[Main]: 	...Games\11111\bin\..\builtin\mainmenu\dlg_contentstore.lua:148: in function 'get_screenshot'
ERROR[Main]: 	...Games\11111\bin\..\builtin\mainmenu\dlg_contentstore.lua:377: in function 'get_formspec'
ERROR[Main]: 	...Games\11111\bin\..\builtin\mainmenu\dlg_contentstore.lua:484: in function 'handle_buttons'
ERROR[Main]: 	C:\Programs\_Games\11111\bin\..\builtin\fstk\ui.lua:148: in function 'handle_buttons'
ERROR[Main]: 	C:\Programs\_Games\11111\bin\..\builtin\fstk\ui.lua:192: in function <C:\Programs\_Games\11111\bin\..\builtin\fstk\ui.lua:178>
```

### PR DESCRIPTION
**Pull request by ClobberXD**
Trivial PR. Fixes #7436. Tested.

- Moves the whole page-nav container into the `if #store.packages > 0` block, and displays a stand-alone `Back to main menu` button otherwise.

screenshot

### CODE REVIEW

File: builtin/mainmenu/dlg_contentstore.lua [hunk 1]
```diff
@@ -355,9 +355,9 @@ function store.get_formspec()
 	if cur_page > pages then
 		cur_page = 1
 	end
-
+	print(#store.packages)
```
Comment (srifqi) [inline builtin/mainmenu/dlg_contentstore.lua]: Is it needed?

Comment (ClobberXD) [reply builtin/mainmenu/dlg_contentstore.lua]: Oh no...

My bad, sorry. Removed :)

**Comment by ClobberXD** [comment]
Would someone be able to review this PR? This PR essentially just moves a block of code from one place to another. It has also been tested and I've provided a screenshot in the first post.
