### PR TITLE
Fix no_texture.png being shown (instead of unknown_node.png) for unknown nodes w/ content ID < 125

### LINKED ISSUE #12248: Unknown nodes (sometimes) show with no_texture.png instead of unknown_node.png
##### Minetest version

5.6.0-devs
**only happens in multiplayer**, not singleplayer

##### Summary

Unknown nodes in the world no longer show with the texture they're supposed to have but instead have the "no texture" fallback texture

### PR DESCRIPTION
**Pull request by Wuzzy2**
Fixes #12248.
The issue description is wrong, the bug can also happen in singleplayer under the right conditions (see the issue discussion).

If the content ID of an unknown node happens to be below 125, it incorrectly showed the `no_texture.png` texture instead of `unknown_node.png`. Moreover, the F5 debug showed "pointed: , param2: 0" (i.e. the empty string). The reason was `ContentFeatures& get(content_t c)` only returning the ContentFeatures from the Unknown Node if the content ID iff the content ID was < 125, due to the positioning of the Air, Ignore and Unknown Node's Content Features. Otherwise, it reads from ID/nodename map, from an entry in which everything, including `name` is unassigned. `no_texture.png` is the fallback for empty texture field, and the empty string is also the default of `name` which explains the F5 oddity.

Since the content ID can change after every load, this also explains why this bug happens sporadically. Singleplayer vs multiplayer does NOT cause the bug.

The check in array bounds in this function was correct, but incomplete. Therefore, my fix is to also check if `.name` in the ContentFeatures is empty. Because if it is empty, that means it was not assigned before and must therefore be an unknown node.

Thanks to @sfan5's important analysis on this.

## How to test

Create a dummy game with a mod `minimod` with this code in the `init.lua`:

```
local NODES_COUNT = 256

for i=0,NODES_COUNT-1 do
	minetest.register_node("minimod:badnode"..string.format("%03d", i), {
		tiles = { "logo.png" },
		groups = { dig_immediate = 3 },
	})
end

minetest.register_on_mods_loaded(function()
	-- Print list of content IDs
	local nodelist = {}
	for node, _ in pairs(minetest.registered_nodes) do
		table.insert(nodelist, node)
	end
	table.sort(nodelist)
	for i=1, #nodelist do
		local node = nodelist[i]
		local id = minetest.get_content_id(node)
		minetest.log("error", id..": "..node)
	end
end)


minetest.register_chatcommand("place_nodes", {
	privs = {server=true},
	func = function(name, param)
		local pos = vector.zero()
		local row = 0
		for i=0,NODES_COUNT-1 do
			minetest.set_node(pos, {name="minimod:badnode"..string.format("%03d", i)})
			pos.x = pos.x + 2
			row = row + 1
			if row >= 16 then
				row = 0
				pos.x = 0
				pos.z = pos.z + 2
			end
		end
		return true
	end,
})
```

* Start the world, enable fly, teleport to 0,0,0
* `/place_nodes`. This creates a 16×16 node grid with 256 nodes total. The Minetest logo (`logo.png`) should be visible.
* Leave the world
* In the code, set `NODES_COUNT = 0`.
* Start the world again

EXPECTED BUG-FREE BEHAVIOR: Every node of the 256 nodes shows the `unknown_node.png` texture
CURRENT BUGGY BEHAVIOR: 125 nodes of the 256 nodes show the `no_texture.png` texture, the rest shows `unknown_node.png`. The affected nodes can differ per-launch.

Feel free to repeat this test with other values for `NODES_COUNT`.

### CODE REVIEW

File: src/nodedef.h [hunk 1]
```diff
@@ -538,9 +538,15 @@ class NodeDefManager {
...
-				m_content_features[c] : m_content_features[CONTENT_UNKNOWN];
+		if (c < m_content_features.size()) {
+			if (m_content_features[c].name == "") {
+				return m_content_features[CONTENT_UNKNOWN];
+			} else {
+				return m_content_features[c];
+			}
+		} else {
+			return m_content_features[CONTENT_UNKNOWN];
+		}
```
Comment (sfan5) [inline src/nodedef.h:549]: doing these checks on lookup could be a relevant performance regression

**Comment by Wuzzy2** [comment]
@sfan5: Because of the string comparison? Would a boolean flag be better?
Or are you saying that even `c < m_content_features.size()` (which existed before) is bad?

**Comment by SmallJoker** [comment]
Generally, lookup functions should have as less and as efficient code as possible. The alternative would be to initialize the first few tiles (until `initial_length`) within "unknown_node.png" in `NodeDefManager::clear()`.

However, it is a fake unknown node and I'd expect exactly `CONTENT_UNKNOWN` and not a lookalike.
Suggested code change:
```C++
	inline const ContentFeatures& get(content_t c) const {
		return
			(c < m_content_features.size() && !m_content_features[c].name.empty()) ?
				m_content_features[c] : m_content_features[CONTENT_UNKNOWN];
	}
```

**Comment by Wuzzy2** [comment]
That code looks similar. You're still performing two checks (`size()` and `empty()`). My code does 1-2 checks.

I feel like this should *actually* be tested for performance, but I don't know how.

**Comment by SmallJoker** [comment]
@Wuzzy2 The only difference is the constant `empty()` (respectively (`size()`) call rather than literal string comparison. Regardless on that, it's the same code but more compact.
FYI: The first condition acts as a short-circuit. If the first condition of the AND operator evaluates to 0, the second is skipped. Same happens for OR, when the first condition evaluates to 1.

Either way, the performance impact is in the magnitude of a few instructions hence unlikely a big deal. Question is whether to pre-fill `m_content_features` with "unknown node"-lookalikes or to extend the `NodeDefManager:get()` checks. Waiting for further opinions...

**Comment by Wuzzy2** [comment]
My opinion on "real" vs "fake" unknown node: I think it's better to return the real unknown node and not a fake one. Returning a fake unknown node by populating the unassigned content IDs sounds really ugly to me because this introduces redundancy and thus a potential bug factory.

This code change seems simple enough, let's not over-complicate things.

**Comment by Wuzzy2** [comment]
I tested and pushed the suggested code. It works fine to me.

**Review by SmallJoker — APPROVED** [review]
`m_content_features` is an `std::vector`, hence access complexity O(1) and the same for `std::string::empty()`. This is acceptable IMO.
