### PR TITLE
Fixup parsing for `Plural-Forms`

### LINKED ISSUE #15518: Error message "Invalid Plural-Forms line" in Russian PO file
### Luanti version

```true
5.10.0
```

### Irrlicht device

X11

### Operating system and version

GNU/Linux

### CPU model

_No response_

### GPU model

_No response_

### Active renderer

_No response_

### Summary

If you start the game in Russian and play a game that includes a Russian PO file in any mod, Luanti reports the following error message:

> Invalid Plural-Forms line: [...]

(abridged, the "[...]" represents the Plural-Forms line it complains about)

This error message is from `translation.cpp`.

The Plural-Forms line in question is:

```
"Plural-Forms: nplurals=3; plural=n%10==1 && n%100!=11 ? 0 : n%10>=2 && "
"n%10<=4 && (n%100<10 || n%100>=20) ? 1 : 2;\n"
```

Yes, these are 2 lines but changing it to:

```
"Plural-Forms: nplurals=3; plural=n%10==1 && n%100!=11 ? 0 : n%10>=2 && n%10<=4 && (n%100<10 || n%100>=20) ? 1 : 2;\n"
```

does not fix it either. I am pretty certain this is valid syntax because basically the same line is used for the Luanti engine PO file for Russian, the only difference is that the `plurals` expression is enclosed in 2 additional brackets. Adding those to my game did not make the error go away either but really it shouldn't make a difference.
This expression looks valid to me, it's also literally in the gettext manual. According to the gettext manual (<https://www.gnu.org/software/gettext/manual/html_node/Plural-forms.html>), the `plurals` expression is C code with some restrictions. And to be extra sure, I wrote a tiny C program with this expression to see if it compiles. It compiles.

I therefore suspect there is an error in Luanti's expression parser.

### Steps to reproduce

1. Create a game or mod with a Russian PO file. Use the aforementioned Plural-Forms line. Alternatively, use Repixture 3.17.2
2. Set language to Russian
3. Restart Luanti
4. Start the game or mod

* Expected: No error message
* Actual result: Error messages

### PR DESCRIPTION
**Pull request by y5nw**
Followup for #14726.

- Goal of the PR
  Fix issues from the PR that were overlooked.
- Does it resolve any reported issue?
  Fixes #15518.
- Does this relate to a goal in [the roadmap](https://github.com/minetest/minetest/blob/master/doc/direction.md)?
  No.

## To do

- [x] #15518
- [x] Look for other sensible testcases from the examples in [the Gettext documentation](https://www.gnu.org/software/gettext/manual/html_node/Plural-forms.html)
- [x] `const std::wstring_view&` -> `std::wstring_view`

## How to test

The fixes should be covered by the relevant testcases.

### CODE REVIEW

File: src/gettext_plural_form.cpp [hunk 1]
```diff
@@ -99,7 +99,7 @@ static ParserResult reduce_ltr(const size_t nplurals, const ParserResult &res, c
 {
```
Comment (sfan5) [inline src/gettext_plural_form.cpp:99]: unrelated but it appears whoever reviewed the code in this file did not notice the `const wstring_view&` anti-pattern

File: src/unittest/test_translations.cpp [hunk 2]
```diff
@@ -25,12 +25,41 @@ TEST_CASE("test translations")
 {
 	SECTION("Plural-Forms function for translations")
 	{
-		auto form = GettextPluralForm::parseHeaderLine(L"Plural-Forms: nplurals=3; plural= (n-1+1)<=1 ? n||1?0:1 : 1?(!!2):2;");
-		REQUIRE(form);
-		REQUIRE(form->size() == 3);
+#define REQUIRE_FORM_SIZE(x) {REQUIRE(form); REQUIRE(form->size() == (x));}
```
Comment (sfan5) [inline src/unittest/test_translations.cpp:28]: use `REQUIRE(form && form->size() == N)`?

Comment (y5nw) [reply src/unittest/test_translations.cpp:28]: I get this error when I apply this change:
```
/home/y5nw/Documents/minetest/lib/catch2/catch_amalgamated.hpp:5547:27: error: static assertion failed due to requirement 'always_false<bool>::value': operator&& is not supported inside assertions, wrap the expression inside parentheses, or decompose it
 5547 |             static_assert(always_false<RhsT>::value,
      |                           ^~~~~~~~~~~~~~~~~~~~~~~~~
/home/y5nw/Documents/minetest/src/unittest/test_translations.cpp:31:3: note: in instantiation of function template specialization 'Catch::operator&&<bool>' requested here
   31 |                 REQUIRE_FORM_SIZE(2);
      |                 ^
/home/y5nw/Documents/minetest/src/unittest/test_translations.cpp:28:46: note: expanded from macro 'REQUIRE_FORM_SIZE'
   28 | #define REQUIRE_FORM_SIZE(x) {REQUIRE((form) && (form->size() == (x)));}
      |                                              ^
1 error generated.
```

Aside from that, I prefer the current one because it allows telling the exact problem if the `REQUIRE` fails: you can tell whether it parsed the `nplurals` part incorrectly or the `plural` expression.

File: src/gettext_plural_form.cpp (hunk 1 above)
Comment (y5nw) [reply src/gettext_plural_form.cpp:99]: I might as well fix it in this PR.

**Review by sfan5 — APPROVED** [review]
LGTM
