### PR TITLE
Fix formula used for acceleration

### LINKED ISSUE #12340: Physics: Acceleration is severely broken
See https://github.com/minetest/minetest/pull/11855, which partially fixes this in relation to players.

**Physics are currently fundamentally and severely broken:** Acceleration does not work the way it should as outlined in the PR; objects accelerate faster than they should. This has consequences for all kinds of use cases where modders (and the engine) may use acceleration:

* Friction/drag of entities;
* Increase in speed of entities (i.e. towards a target);
* Most fundamentally: Gravity

First of all, the physical units can't be applied; an acceleration of `{x=0, y=-9.81, z=0}` does not have the same effect as the gravitational constant of an acceleration of `9.81m/s²`; acceleration is not the second derivative of location/position.

For the sake of simplicity, let's assume the object only has an acceleration `a` and initial position `s` and initial velocity `v` are both zero. Then the position of the object after the first step of duration `t` would be given as `s' = at²/2`; due to the currently used incorrect formula it's actually calculated as `s' = v't = at²`. The error (difference between these two values) can trivially be seen to be `s' = at²/2`: In the first server step, the position is off by 100%! In subsequent server steps however, as the velocity rises linearly, the percentual error shrinks; it can be calculated as `d/t` where `d` is the stepsize and `t` is the total time (hence 100%). 

Consequences:

* The percentual error with constant stepsizes `d` after a time `t` has passed is `d/t`
* The **larger the stepsize (i.e. "lag"), the larger the error** but also **the shorter the time, the larger the error** (which is why jump heights are off)
* This means that the absolute error after a time is `d/t * at²/2` = dat/2` - a constant velocity of `da/2` is constantly added
* It is impossible for modders to fix this as the size of the steps run client- & serverside is a factor in the equation; constantly setting position or acceleration manually would just yield larger errors.
* This leads to a client-server desync due to different stepsizes (different stepsizes, different errors, different final object positions)

In conclusion, most ballistics are severely broken: Objects travelling a long distance with the same initial velocity & acceleration hit at vastly different positions because **serversteps** become a factor in the calculation and these may vary based on factors like lag. Jump height is very broken too.

Now, what works properly in the current movement code and may not be broken?

* Linear movement (velocity) and the resulting change of position works just fine;
* Increase in velocity through acceleration works just fine

I thus demand this issue be assigned high priority and put on the roadmap immediately, even though fixing it either requires (1) a flag / object property for all entities (which may obviously only be respected by newer clients, causing all kinds of horrible issues on older clients) or (2) a major release of Minetest (6.0).

Below is a small Lua script that calculates both correct & incorrect position as well as the error, simulating entity movement for 10 secs:
```lua
local dt, a = ...
dt, a = tonumber(dt) or 0.5, tonumber(a) or 9.81
local v = 0
local s_correct = 0
local s_incorrect = 0
for t = 0, 10, dt do
	print("t", t, "s_c", s_correct,  "s_i", s_incorrect, "err", (s_incorrect - s_correct) / s_correct)
	local prev_v = v
	v = v + a*dt
	s_incorrect = s_incorrect + v*dt
	s_correct = s_correct + (prev_v + v) / 2 * dt
end
```
and the output for the first second:
```lua
t	0	s_c	0	s_f	0	err	-nan
t	0.1	s_c	0.04905	s_f	0.0981	err	1
t	0.2	s_c	0.1962	s_f	0.2943	err	0.5
t	0.3	s_c	0.44145	s_f	0.5886	err	0.33333333333333
t	0.4	s_c	0.7848	s_f	0.981	err	0.25
t	0.5	s_c	1.22625	s_f	1.4715	err	0.2
t	0.6	s_c	1.7658	s_f	2.0601	err	0.16666666666667
t	0.7	s_c	2.40345	s_f	2.7468	err	0.14285714285714
t	0.8	s_c	3.1392	s_f	3.5316	err	0.125
t	0.9	s_c	3.97305	s_f	4.4145	err	0.11111111111111
t	1	s_c	4.905	s_f	5.3955	err	0.1
```

### PR DESCRIPTION
**Pull request by appgurueu**
"Breaking" change. Fixes #12340.

Note: Jumping etc. necessarily feels slightly different with this the lower the FPS (hence why this is a breaking change); ~~some defaults such as gravity should be considered to be tweaked.~~

### CODE REVIEW

File: src/collision.cpp [hunk 1]
```diff
@@ -249,10 +249,12 @@ collisionMoveResult collisionMoveSimple(Environment *env, IGameDef *gamedef,
...
 		time_notification_done = false;
 	}
+
+	v3f newpos_f = *pos_f + (*speed_f + accel_f * 0.5f * dtime) * dtime;
 	*speed_f += accel_f * dtime;
 
-	// If there is no speed, there are no collisions
-	if (speed_f->getLength() == 0)
+	// If there is no speed or acceleration, there are no collisions
+	if (speed_f->getLength() == 0 && accel_f.getLength() == 0)
```
Comment (appgurueu) [inline src/collision.cpp:257]: Could be optimized to `if (newpos_f == *pos_f)`

File: src/client/particles.cpp [hunk 2]
```diff
@@ -149,8 +149,8 @@ void Particle::step(float dtime)
 			m_velocity = p_velocity / BS;
 		}
 	} else {
+		m_pos += (m_velocity + m_acceleration * 0.5f * dtime) * dtime;
```
Comment (lhofhansl) [inline src/client/particles.cpp:152]: So it's just replacing Euler with Runge-Kutta...?
It's definitely going to be more accurate. We should make this change!

**Comment by lhofhansl** [comment]
It's definitely going to be more accurate then before and less prone to rounding error.
So I'm a fan.

Need to test it, though.

**Comment by Wuzzy2** [comment]
>  Perhaps some platform or parkour games might be broken now.

This alone should be reason for immediate rejection, especially for a minor release.

Breakage is likely because sometimes, jumps are very close. This is a very major change for a minor release that claims to preserve compatibility. Such major movement changes should NOT be taken lightly. @sofar will probably not like this either because he can then basically kiss good-bye to all the parcours boxes in Inside The Box as well as related stats which need to be invalidated. And it's not just parkour maps, it will also break any other game in which the jumping height has been fine-tuned, so it's possible that jumps that were easy before are now impossible.
This amount of breakage is definitely unacceptable for a minor release, and it's questionable even for a major release.

As long this change does not come with any form of compatibility, this is a BIG thumbs down from me.

**Comment by Wuzzy2** [comment]
Addendum: It's unfortunate acceleration is so broken right now, but breaking existing games is also not good. So I understand why this PR was made. So IMHO if this is merged, the next release MUST be 6.0.0 because the implications of this are massive. It WILL be painful for servers, games and mods to clean up, but at least they were warned.

**Comment by appgurueu** [comment]
Would you be happy with an (by default unset) object property for a smoother transition? Things to note:

* This should increase jump height as the previous calculation resulted in stronger acceleration;
* On clients the error may be negligible as they often use very small step sizes (FPS) - the higher the stepsize, the smaller the error

**Comment by Wuzzy2** [comment]
Object property sounds reasonable but then this also has to be supported till eternity.

I'm not a physics expert, but I recommend to make a full review of the object physics then, to see if there is anything else that is very broken. If you're going to change physics at all, do it right the first time. Multiple incremental breaking changes are worse than one big breaking change that does everything right from the start.

**Comment by lhofhansl** [comment]
Maybe tag this for 6.0.0 then.

**Comment by appgurueu** [comment]
This might be added to the [breakages list](https://github.com/minetest/minetest/blob/master/doc/breakages.md) by a core dev. I'm not opening a second PR for that though as to not clutter up the PR list.

**Comment by SmallJoker** [comment]
Hot take: This is not a breaking change.

Why? While testing #11367 I noticed that Minetest 5.2.0 is the last version where 1 full node + a 0.5m slab could be jumped on. The breakage already happened, just nobody noticed. Also while testing this PR for a bit, it does not seem to be much different (running at 60 FPS).

**Comment by appgurueu** [comment]
> Hot take: This is not a breaking change.
> 
> Why? While testing #11367 I noticed that Minetest 5.2.0 is the last version where 1 full node + a 0.5m slab could be jumped on. The breakage already happened, just nobody noticed. Also while testing this PR for a bit, it does not seem to be much different (running at 60 FPS).

As I state in my analysis on the issue:

> The percentual error with constant stepsizes d after a time t has passed is d/t
> 
> The larger the stepsize (i.e. "lag"), the larger the error but also the shorter the time, the larger the error (which is why jump heights are off)

On clients with high FPS (30 - 60 FPS) the error will thus already have been acceptably small for this to qualify as non-breaking. **In fact this increases fairness among clients, since all clients fall at the same speed now (without this PR clients with higher FPS would fall slower due to the error being smaller)**. What concerns me more are servers which operate at a stepsize of 10 steps per second. During the first couple steps the error is rather significant there.

Note also that this should allow you to jump (a very tiny bit) higher than before since before gravity was over-accounted for. Parkours etc. *should* still work just fine.

**Comment by SmallJoker** [comment]
comparison chart

Spreadsheet for comparison: [server_acceleration_calc.ods](https://github.com/minetest/minetest/files/8886107/server_acceleration_calc.ods) << formulas might not show up properly on MS Excel.

**Comment by pecksin** [comment]
Another peculiarity of jumping in versions < 5.3 that seems to not be well-known is, due to a larger ground collision tolerance, a sufficiently fast client stepsize can result in immediately (repeatedly?) jumping again while still inside that tolerance, resulting in inconsistently higher jumps.

More noticable with trampolines (< v5.3) since bounce accumulation is applied with each jump.

**Comment by appgurueu** [comment]
> Did I miss something? The player should jump 2.15 nodes high, but does not do that.

Here's my calculation:

For the gravity: $v = gt$

For the jump speed: $v = v_0$

At the highest point of the parabola, the vertical component is zero - e.g. the downwards velocity added through gravity equals the initial velocity: $v_0 = gt$ thus $t = \frac{v_0}{g} = 6.5/9.81 = 0.663 [s]$. That's the point in time. Now we may obtain the height as $s = v_0t - \frac{1}[2}at^2 = (6.5 - 9.81*0.663/2)*0.663 = 2.15$. I can confirm your calculations. **In conclusion: The model is wrong.** It does not accurately represent what the code actually does. This is due to localplayer shenanigans; if you spawn an entity with an initial velocity of $(0, 6.5, 0)$ and an acceleration of $(0, -9.81, 0)$ it should indeed rise to $2.15 [m]$ before falling.

`float jump_height = 1.1f; // TODO: better than a magic number` in autojump code BTW...

**Comment by appgurueu** [comment]
Alright @SmallJoker, I have identified the shenanigans:

in `client/clientenvironment.cpp`:
```cpp
		// Apply physics
		if (!free_move) {
			// Gravity
			v3f speed = lplayer->getSpeed();
			if (!is_climbing && !lplayer->in_liquid)
				speed.Y -= lplayer->movement_gravity *
					lplayer->physics_override_gravity * dtime_part * 2.0f;

			// Liquid floating / sinking
			if (!is_climbing && lplayer->in_liquid &&
					!lplayer->swimming_vertical &&
					!lplayer->swimming_pitch)
				speed.Y -= lplayer->movement_liquid_sink * dtime_part * 2.0f;

		}
```

some dingus apparently thought it would be fun to just *double* the gravity (presumably because )

Experiments show this is indeed the case: The time we calculated must be halved!

**Comment by appgurueu** [comment]
Substituting twice the gravity yields an ideal jump height of `1.0767074413863` - just above one block.

**Comment by appgurueu** [comment]
Bump. Opinions are needed on this. I now believe that this should actually be considered a crucial bugfix; the "breakage" (minor deviations in jump height) seems acceptable to me.

File: src/client/localplayer.cpp [hunk 3]
```diff
@@ -879,7 +879,7 @@ void LocalPlayer::old_move(f32 dtime, Environment *env, f32 pos_max_d,
 	// TODO: This shouldn't be hardcoded but decided by the server
 	float player_stepheight = touching_ground ? (BS * 0.6f) : (BS * 0.2f);
 
-	v3f accel_f;
+	v3f accel_f(0, -gravity, 0);
```
Comment (appgurueu) [inline src/client/localplayer.cpp:882]: Should I perhaps not apply the fix to the `old_move` code?

**Comment by benrob0329** [comment]
So with some playtesting, I don't see this breaking anything. It feels ever so slightly more "floaty", but nothing drastic and nothing I'd consider bad. I played both Inside The Box's "Hopscotch" (one of the oldest parkour levels on there), along with A.E.S.'s Tower Of The Gods, and both seem fine.

The only thing I will note is that there seems to be a bug with the old movement code that's used on AES, where you'll sink down about half a block when standing off an edge, see below:
screenshot_20220702_141602

**Comment by appgurueu** [comment]
> The only thing I will note is that there seems to be a bug with the old movement code that's used on AES, where you'll sink down about half a block when standing off an edge

Simplest & perhaps cleanest solution would be to just leave the old move code be. It's called "old" for a reason, updating it feels odd. Will revert those changes.

**Comment by pecksin** [comment]
@appgurueu 
I have not playtested, but I have been poking at movement/collision code a lot lately.  Quick look at your changes looks like you are no longer directly applying gravity inside `ClientEnvironment::step` and instead doing it in `LocalPlayer::move`

If I'm right, I think one thing you "could" do is effect the gravity manually inside the `if (!physics_override_new_move)` block in localplayer, before invoking an unchanged old_move?

Whether that's a good idea or not, well... ¯\\_(ツ)_/¯

File: src/client/localplayer.cpp (hunk 3 above)
Comment (sfan5) [reply src/client/localplayer.cpp:882]: it's called old for a reason and supposed to be unchanging

**Comment by appgurueu** [comment]
> The only thing I will note is that there seems to be a bug with the old movement code that's used on AES, where you'll sink down about half a block when standing off an edge

Fixed by reverting the changes to old move code. Those who want fixed acceleration will have to use the new move code.

**Comment by appgurueu** [comment]
I just found [this marvelous rant](http://lolengine.net/blog/2011/12/14/understanding-motion-in-games) on the issue:

Bildschirmfoto von 2022-07-04 13-03-31

**Comment by appgurueu** [comment]
Bump. This can use testing & reviews.

**Comment by lhofhansl** [comment]
OK... Putting a stake in the ground... One approval. Instead of a breaking change I am considering this a bug fix.

If people feel strongly we can consider for 6.0.0, personally I am in favor of 5.7.0.

File: src/client/localplayer.cpp [hunk 4]
```diff
@@ -1117,8 +1120,11 @@ void LocalPlayer::handleAutojump(f32 dtime, Environment *env,
 		}
 	}
 
-	float jump_height = 1.1f; // TODO: better than a magic number
-	v3f jump_pos = initial_position + v3f(0.0f, jump_height * BS, 0.0f);
+
+	float jumpspeed = movement_speed_jump * physics_override_jump;
+	float peak_dtime = jumpspeed / gravity; // at the peak of the jump v = gt <=> t = v / g
+	float jump_height = (jumpspeed - 0.5 * gravity * peak_dtime) * peak_dtime; // s = vt - 1/2 gt^2
```
Comment (sfan5) [inline src/client/localplayer.cpp:1126]:
```suggestion
	float jump_height = (jumpspeed - 0.5f * gravity * peak_dtime) * peak_dtime; // s = vt - 1/2 gt^2
```

File: src/collision.cpp [hunk 5]
```diff
@@ -249,10 +249,12 @@ collisionMoveResult collisionMoveSimple(Environment *env, IGameDef *gamedef,
...
 		time_notification_done = false;
 	}
+
+	v3f newpos_f = *pos_f + (*speed_f + accel_f * 0.5f * dtime) * dtime;
 	*speed_f += accel_f * dtime;
 
-	// If there is no speed, there are no collisions
-	if (speed_f->getLength() == 0)
+	// If the object is static, there are no collisions
+	if (newpos_f == *pos_f)
```
Comment (sfan5) [inline src/collision.cpp:257]: general question (not for this PR): shouldn't this use a comparison with some margin of tolerance?
or would that introduce a bug where it might miss collisions?

**Comment by sfan5** [comment]
Testing this in singleplayer I can barely feel a difference, if anything I could agree with the "more floaty" @benrob0329 mentioned.
So I guess this is fine for the usual Minecraft-y games usecase.

What I'm worried about is the following:
* There is no way to get consistent movement between players of different versions (okay there's `old_move` but you don't want  to import all the disadvantages)
* What about games that use more extreme acceleration values? They will be more affected, and this also applies to entities.

File: src/collision.cpp (hunk 5 above)
Comment (appgurueu) [reply src/collision.cpp:257]: All movement happening at a speed below the margin would be completely ignored and would cause entities to miss collisions, yes.

**Comment by sfan5** [comment]
So what about my concern? Anyone want to chime in?
I am not opposed to merging this but would like to avoid a situation where this change blows up at us once 5.7 is out and the first servers have it.

**Comment by appgurueu** [comment]
> There is no way to get consistent movement between players of different versions (okay there's `old_move` but you don't want  to import all the disadvantages)

There never was consistent movement to begin with; players with higher FPS fall slower currently. This PR makes all players equal (the same would happen if FPS approached infinity).

> What about games that use more extreme acceleration values? They will be more affected, and this also applies to entities.

I don't think games can successfully use extreme acceleration with the current buggy behavior. If they did, they must have relied on certain fixed stepsizes for consistent behavior.

**Review by SmallJoker — APPROVED** [review]
Works. No differences found in the old movement code, new movement code and the autojump feature.

**Comment by Wuzzy2** [comment]
Wait, how did you find "no differences" if the author admits it's a breaking change and there were even graphs that show differences?

I'd be surprised if really no parcours map will be broken by this. There are many such maps, the probability that ALL of them still work perfectly seems low. This could seriously blow up. You're basically gambling here, and praying that nobody will notice; it does not seem it was even remotely tested enough yet.

What's worse, when there IS a parcours map that breaks, I'm afraid there will be NO workaround for this, other than releasing two different versions for this map.

This could probably one of biggest breaking changes since 5.0.0, and you brush it all off. I'm honestly shocked that such a risky change is seriously considered for a minor version, rather than a major version. Especially with the lack of testing, lack of input from players or server operators.

I strongly suggest to move this to the 6.0.0 milestone instead; better safe than sorry.

**Comment by Wuzzy2** [comment]
Compromise solution: Put this change in anyways and do the next release like you would usually do, except you call it 6.0.0. This would at least communicate the risk clearly.

**Comment by appgurueu** [comment]
> Compromise solution: Put this change in anyways and do the next release like you would usually do, except you call it 6.0.0. This would at least communicate the risk clearly.

I apologize for initially misassessing the potential breakage. Further analysis has led to the conclusion that this is not a breaking change but rather a bugfix; this could even go into 5.6.1 IMO.

If the next version was to be a major one, many other breaking changes would be introduced as well to properly use the version bump.

**Comment by SmallJoker** [comment]
@Wuzzy2 I would like to highlight that the focus should be put on server-side entity movement. As mentioned above, little to no difference on client-side is totally expected due to the small time increments and thus more accurate calculation. The server however uses a 90 ms tick, which results in increased jump heights (see https://github.com/minetest/minetest/pull/12353#issuecomment-1153762962 ) for mobs.
