### PR TITLE
Wieldhand: Specify which ItemStack to use

### LINKED ISSUE #8953: Item in inventory list 'hand' can appear in list 'main'
##### Minetest version

```
Minetest 5.1.0-dev-c413eeb-dirty (Linux)
Using Irrlicht 1.8.4
BUILD_TYPE=Release
RUN_IN_PLACE=1
USE_GETTEXT=1
USE_SOUND=1
USE_CURL=1
USE_FREETYPE=1
USE_LUAJIT=0
STATIC_SHAREDIR="."
```

##### OS / Hardware

Operating system: Linux Mint 19.1
CPU: Intel© Core™ i5-7300HQ CPU @ 2.50GHz × 4

GPU model:
OpenGL version:

##### Summary

The item in the inventory list 'hand' can end up in the main list when breaking a node.

##### Steps to reproduce

1. Install the attached hand_test mod in a world with minimal game.
2. Break a node bare handed.
3. The hand item should appear in the inventory.
[hand_test.zip](https://github.com/minetest/minetest/files/3630165/hand_test.zip)

### PR DESCRIPTION
**Pull request by SmallJoker**
Fixes #8953

## To do

This PR is Ready for Review.

## How to test
(Shamelessly copied from #8953)

1. Install the attached hand_test mod in a world with minimal game.
2. Break a node bare handed.
3. The hand item should appear in the inventory.
[hand_test.zip](https://github.com/minetest/minetest/files/3630165/hand_test.zip)

### CODE REVIEW

File: src/network/serverpackethandler.cpp [hunk 1]
```diff
@@ -1150,9 +1150,10 @@ void Server::handleCommand_Interact(NetworkPacket *pkt)
 			if (pointed_object->isGone())
 				return;
 
-			ItemStack punchitem = playersao->getWieldedItem();
+			ItemStack selected_item, hand_item;
+			ItemStack tool_item = playersao->getWieldedItem(&selected_item, &hand_item);
```
Comment (sfan5) [inline src/network/serverpackethandler.cpp]: `hand_item` isn't needed here, is it?

Comment (SmallJoker) [reply src/network/serverpackethandler.cpp]: It's needed as a parameter for the function so that it knows from which set it should take the non-empty stack. If "hand_item" is provided, it will fall back to the hand as soon the selected item is an empty ItemStack.

**Comment by DS-Minetest** [comment]
Maybe the documentation of the "hand" list could be improved:
https://github.com/minetest/minetest/blob/47da640d7763ee1e00badb7476ac5afc4f864367/doc/lua_api.txt#L2557-L2558
Eg. state that the tool capabilities are only applied if the selected item is empty.
