### PR TITLE
TouchScreenGUI: Fix only 9 hotbar slots being usable

### LINKED ISSUE #13691: Only hotbar slots 1-9 are selectable on Android.
##### Minetest version

```
5.7.0 (Android)
```
##### Summary
On Android, when using a mod that allows increasing the hotbar size, only slots 1-9 can be selected, despite other slots being visible.

Originally reported in https://github.com/mt-mods/dreambuilder_hotbar/issues/3, confirmed using current version.

##### Steps to reproduce
1. Install a mod that changes the hotbar size (e.g. [`dreambuilder_hotbar`](https://github.com/mt-mods/dreambuilder_hotbar))
2. Start a world, and set the hotbar size to greater than 9 slots.
3. Try to select any hotbar slot above slot 9.

### PR DESCRIPTION
**Pull request by grorp**
This PR fixes #13691.

Before this PR, TouchScreenGUI simply emitted a keypress event for one of the number keys when a hotbar item was pressed. After the 9th hotbar item (the last one for which there is a number key), it started pressing "random" keys.

After this PR, all hotbar items are selectable (except if they are hidden behind other controls, but that's a different issue). 

## To do

This PR is a Ready for Review.

## How to test

Install the CI-built APK on your Android device. Start a Devtest world and execute `/hotbar 20`. Verify that you can select all hotbar slots. Verify that you *cannot* use the 19th hotbar slot to change your camera mode.

Because I rebased this PR, you'll experience #13743 while testing.

### CODE REVIEW

File: src/client/hud.cpp [hunk 1]
```diff
@@ -226,13 +226,9 @@ void Hud::drawItem(const ItemStack &item, const core::rect<s32>& rect,
 //NOTE: selectitem = 0 -> no selected; selectitem 1-based
```
Comment (srifqi) [inline src/client/hud.cpp:226]: While we are touching this function, please also tidy up this line:
```suggestion
// NOTE: selectitem = 0 -> no selected; selectitem is 1-based
```

File: src/gui/touchscreengui.cpp [hunk 2]
```diff
@@ -581,25 +581,27 @@ touch_gui_button_id TouchScreenGUI::getButtonID(size_t eventID)
...
-			translated.EventType            = irr::EET_KEY_INPUT_EVENT;
-			translated.KeyInput.Key         = (irr::EKEY_CODE) (KEY_KEY_1 + hud_rect.first);
-			translated.KeyInput.Control     = false;
-			translated.KeyInput.Shift       = false;
-			translated.KeyInput.PressedDown = true;
-			m_receiver->OnEvent(translated);
-			m_hud_ids[event.TouchInput.ID]  = translated.KeyInput.Key;
+	// check if hotbar item is pressed
+	for (auto &[index, rect] : m_hotbar_rects) {
+		if (rect.isPointInside(v2s32(event.TouchInput.X, event.TouchInput.Y))) {
```
Comment (srifqi) [inline src/gui/touchscreengui.cpp:588]:
```suggestion
	const v2s32 touch_pos = v2s32(event.TouchInput.X, event.TouchInput.Y);
	// check if hotbar item is pressed
	for (auto &[index, rect] : m_hotbar_rects) {
		if (rect.isPointInside(touch_pos)) {
```

**Comment by srifqi** [comment]
Thank you for this fix. I was not sure about the hotbar when refactoring `TouchScreenGUI`, so I just left it as it is. I also just compiled it using Android Studio, so I have not checked it with other compilers.

**Review by srifqi — CHANGES_REQUESTED** [review]
I tested the fix. It does work and its implementation looks good, except for a few lines.

**Review by srifqi — APPROVED** [review]
This PR looks good to me.
