### PR TITLE
[no sq] Don't recalculate meshnode normals unnecessarily

### LINKED ISSUE #15503: Incorrect normals on mesh nodes
### Luanti version

```true
Luanti 5.10.0 (Windows)
Using LuaJIT 2.1.1725453128
Built by Clang 18.1
Running on Windows/10.0.19041 x86_64
BUILD_TYPE=Release
RUN_IN_PLACE=1
USE_CURL=1
USE_GETTEXT=1
USE_SOUND=1
STATIC_SHAREDIR="."
STATIC_LOCALEDIR="locale"
```

### Irrlicht device

_No response_

### Operating system and version

Windows 10, 64 bit

### CPU model

Intel Core i9-10900F

### GPU model

NVIDIA GeForce RTX 3060

### Active renderer

_No response_

### Summary

Normals on nodes that uses mesh draw type are not the same as in .obj file and are highly influenced by face direction. On the entities all imported normals works fine (right is node, left is entity):

screenshot_20241201_163725

### Steps to reproduce

Simple mod (for any game) that can reproduce this issue (adds node `debug_normals:sphere` and entity `debug_normals:sphere`)
[debug_normals.zip](https://github.com/user-attachments/files/17969081/debug_normals.zip)

### PR DESCRIPTION
**Pull request by sfan5**
fixes #15503 (thanks to @appgurueu)

## To do

This PR is Ready for Review.

## How to test

1. use test mod from #15503
2. the problem should appear fixed
3. add `paramtype2 = "facedir"` to test node and rotate it
4. problem should still be fixed

### CODE REVIEW

File: src/client/content_mapblock.cpp [hunk 1]
```diff
@@ -1664,48 +1663,51 @@ void MapblockMeshGenerator::drawMeshNode()
...
 			rotateMeshBy6dFacedir(mesh, facedir);
 		else if (degrotate)
 			rotateMeshXZby(mesh, 1.5f * degrotate);
-		recalculateBoundingBox(mesh);
-		meshmanip->recalculateNormals(mesh, true, false);
+		else
+			modified = false;
+		if (modified) {
+			recalculateBoundingBox(mesh);
+			// FIXME: we should rotate the normals too, instead of recalculating
```
Comment (appgurueu) [inline src/client/content_mapblock.cpp:1676]: Why leave this as a `FIXME`? Isn't this pretty easy to fix or am I missing something:

```diff
diff --git a/src/client/mesh.cpp b/src/client/mesh.cpp
index 3f947ae50..06b9f1d67 100644
--- a/src/client/mesh.cpp
+++ b/src/client/mesh.cpp
@@ -249,10 +249,14 @@ static void rotateMesh(scene::IMesh *mesh, float degrees)
        float c = std::cos(degrees);
        float s = std::sin(degrees);
        auto rotator = [c, s] (video::S3DVertex *vertex) {
-               float u = vertex->Pos.*U;
-               float v = vertex->Pos.*V;
-               vertex->Pos.*U = c * u - s * v;
-               vertex->Pos.*V = s * u + c * v;
+               auto rotate_vec = [c, s] (v3f &vec) {
+                       float u = vec.*U;
+                       float v = vec.*V;
+                       vec.*U = c * u - s * v;
+                       vec.*V = s * u + c * v;
+               };
+               rotate_vec(vertex->Pos);
+               rotate_vec(vertex->Normal);
        };
        applyToMesh(mesh, rotator);
 }
```

Comment (sfan5) [reply src/client/content_mapblock.cpp:1676]: looks fine but I didn't want it to be me who figures it out

Comment (appgurueu) [reply src/client/content_mapblock.cpp]: https://github.com/minetest/minetest/pull/15523/commits/d0b886bd2750ac23ca7887db210acb74a0f45d12
