### PR TITLE
Rework object attachment handling to fix bugs

### LINKED ISSUE #14694: Segmentation fault under specific conditions (apparently unloading the entity the player is attached to)
### Minetest version

```true
Minetest 5.9.0-dev-debug-c4703a7f1 (Linux)
Using LuaJIT 2.1.1713773202
Built by GCC 11.4
Running on Linux/6.5.0-35-generic x86_64
BUILD_TYPE=Debug
RUN_IN_PLACE=1
USE_CURL=1
USE_GETTEXT=1
USE_SOUND=1
STATIC_SHAREDIR="."
STATIC_LOCALEDIR="locale"
```

### Irrlicht device

_No response_

### Operating system and version

Linux Mint 21.3 Cinnamon

### CPU model

Intel© Core™ i3-7100U CPU @ 2.40GHz × 2

### GPU model

Intel Corporation HD Graphics 620

### Active renderer

_No response_

### Summary

The server can crash with Segmentation Fault error when riding an Advtrains train for some time. The bug can be easily reproduced when using a modified version of Advtrains from https://gitlab.com/tunnelers-abyss/advtrains which allows larger speed of trains (I had also once managed to reproduce it with the standard version of Advtrains but it was much more difficult). It's not because of bugs in the mod, because even if it is, potential bugs in mods shouldn't cause Segmentation Fault in the whole engine. Coredump pointed that the source of the crash is l_object.cpp:728:
```
Core was generated by `./bin/minetest'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00006087f0369155 in ObjectRef::l_set_attach (L=0x79a46e65b380)
    at /home/andrii/git/minetest/src/script/lua_api/l_object.cpp:728
728			old_parent->removeAttachmentChild(sao->getId());
[Current thread is 1 (Thread 0x79a46cad6640 (LWP 5562))]
(gdb) p sao
$1 = (ServerActiveObject *) 0x79a4401a6960
(gdb) p old_parent
$2 = (ServerActiveObject *) 0x0
```
Also, before the crash, there was the following line in the log:
`WARNING[Server]: PlayerSAO::step() id=1 is attached to nonexistent parent. This is a bug.`

### Steps to reproduce

1. Install Advtrains mod from https://gitlab.com/tunnelers-abyss/advtrains
2. Build a long straight railroad (1000m was enough for me), in each end of which the train automatically changes direction (using "Station/Stop Rail") so that it could run infinitely
3. Run the train with the max speed, and wait until the Seg.fault happens. To speed up the process, you can try to teleport to a distant location when riding a train (under normal conditions you can be automatically teleported back to the train but sometimes it might cause the area with the train to unload that is apparently the reason of the bug. Also decreasing the viewing range to minimum may help.

Restricting max memory for the app via
`systemd-run --scope -p MemoryMax=500M --user ./bin/minetest`
didn't help to reproduce the bug.

### PR DESCRIPTION
**Pull request by sfan5**
fixes #14694
(root cause unfixed, but this fixes the crash)

to make all this work a behavior change was necessary:
* entity detach callbacks are called with detachment already done
  * before: objects were still linked
* if you do something like re-attach in `on_detach` it will now work properly and cause an infinite loop

## To do

This PR is Ready for Review.

Note: not tested much beyond MTG carts and the unit tests

### CODE REVIEW

File: src/server/clientiface.cpp [hunk 1]
```diff
@@ -85,23 +85,13 @@ void RemoteClient::ResendBlockIfOnWire(v3s16 p)
...
-	bool force_visible;
-	sao->getAttachment(&id, &bone, &dummy, &dummy, &force_visible);
-	ServerActiveObject *ao = env->getActiveObject(id);
-	while (id && ao) {
-		ao->getAttachment(&id, &bone, &dummy, &dummy, &force_visible);
-		if (id)
-			ao = env->getActiveObject(id);
-	}
-	return dynamic_cast<LuaEntitySAO *>(ao);
+static LuaEntitySAO *getAttachedObject(PlayerSAO *sao, ServerEnvironment *env)
```
Comment (lhofhansl) [inline src/server/clientiface.cpp:88]: So much nicer!

File: src/server/unit_sao.cpp [hunk 2]
```diff
@@ -183,79 +220,67 @@ void UnitSAO::getAttachment(int *parent_id, std::string *bone, v3f *position,
...
-void UnitSAO::clearParentAttachment()
-{
-	ServerActiveObject *parent = nullptr;
-	if (m_attachment_parent_id) {
-		parent = m_env->getActiveObject(m_attachment_parent_id);
-		setAttachment(0, "", m_attachment_position, m_attachment_rotation, false);
-	} else {
-		setAttachment(0, "", v3f(0, 0, 0), v3f(0, 0, 0), false);
+		if (auto *child = m_env->getActiveObject(child_id))
+			child->clearParentAttachment();
```
Comment (SmallJoker) [inline src/server/unit_sao.cpp:242]: When `child == nullptr`, `m_attachment_child_ids` will never shrink. Endless loop.

File: src/server/unit_sao.cpp [hunk 3]
```diff
@@ -130,50 +130,87 @@ void UnitSAO::sendOutdatedData()
...
-	auto *obj = parent_id ? m_env->getActiveObject(parent_id) : nullptr;
-	if (obj) {
-		// Do checks to avoid circular references
-		// The chain of wanted parent must not refer or contain "this"
-		for (obj = obj->getParent(); obj; obj = obj->getParent()) {
-			if (obj == this) {
-				warningstream << "Mod bug: Attempted to attach object " << m_id << " to parent "
-					<< parent_id << " but former is an (in)direct parent of latter." << std::endl;
-				return;
+	const auto call_count = ++m_attachment_call_counter;
```
Comment (SmallJoker) [inline src/server/unit_sao.cpp:136]: Maybe we should throw an error when `call_count == 255`, e.g. endless recursion that does not trigger a stack overflow immediately because the functions take too much time to execute. Even worse; the variable does overflow too.

File: src/server/unit_sao.cpp (hunk 2 above)
Comment (sfan5) [reply src/server/unit_sao.cpp:242]: If we get into that situation that's generally a problem but I'll handle it here at least

File: src/server/unit_sao.cpp (hunk 3 above)
Comment (sfan5) [reply src/server/unit_sao.cpp:136]: That's easy to do. Will add.

File: src/server/unit_sao.cpp (hunk 2 above)
Comment (SmallJoker) [reply src/server/unit_sao.cpp:242]: Granted, I did provoke this and the other comment at the same time with the following recursive snippet:
```Lua
	on_punch = function(self, puncher, _, _, _, _)
		self.object:set_detach()
		error("oops")
	end,
	on_detach = function(self, parent)
		self.object:set_attach(parent, "", {x=30,y=0,z=30}, {x=45,y=45,z=0})
		print("on_detach")
	end,
```
where `self.object` is attached to another object, and you hit it. Used this testing code: https://github.com/SmallJoker/minetest_lab/blob/master/init_18_attachment_chain.lua

File: src/server/unit_sao.cpp [hunk 4]
```diff
@@ -130,50 +130,97 @@ void UnitSAO::sendOutdatedData()
...
+
+	const auto check_nesting = [&] (const char *descr) -> bool {
+		if (m_attachment_call_counter == call_count)
+			return false;
+		auto d = wrappedDifference(m_attachment_call_counter, call_count, (u8)U8_MAX);
+		if (d > 30) {
```
Comment (SmallJoker) [inline src/server/unit_sao.cpp:142]: Does not trigger when punching the lowest node in the given test script with the following callback code:
```Lua
	on_punch = function(self, puncher, _, _, _, _)
		self.object:set_detach()
		--error("lockout")
	end,
	on_detach = function(self, parent)
		self.object:set_attach(parent, "", {x=30,y=0,z=30}, {x=45,y=45,z=0})
		print("on_detach")
	end,
```

because `check_nesting` is only run on the most recent (or 2nd most recent when no detach is necessary) function call, thus resulting in distances of 0 and 1:

```
CALL 152
     ^ call_count
152 DETACH
^ call_count
CALL 153
153 ATTACH
	check 153 152
          ^ m_attachment_call_counter | call_count
CALL 154
154 DETACH
CALL 155
155 ATTACH
	check 155 154
CALL 156
156 DETACH
CALL 157
157 ATTACH
	check 157 156
CALL 158
158 DETACH
CALL 159
159 ATTACH
```

Suggestion: use `m_attachment_call_counter--;`  on function exit, similar to `Inventory::ResizeUnlocker`. Error when `call_counter == 255).

**Comment by SmallJoker** [comment]
About the "Breaking Change" label: Was an issue found in combination with some mods, or does it represent the unknown extent of this PR's changes?

**Comment by sfan5** [comment]
Just semantics. I doubt that this causes problems in practice.

File: src/server/unit_sao.cpp (hunk 4 above)
Comment (sfan5) [reply src/server/unit_sao.cpp:142]: I need to be able to abort an existing attach operation if a nested call to `setAttachment` has completed. this doesn't work if the value is decremented again.

you're correct that the loop detection doesn't work like this, I'll have to remove it.

**Review by SmallJoker — APPROVED** [review]
The infinite loop `on_detach` -> `obj:set_attach` in the case of entity death is not caught but I suppose modders are to blame for such logic faults.

LGTM. Works with advtrains (3 waggons) and MTG carts.
