### PR TITLE
Fix font memory leak

### LINKED ISSUE #13832: Small memory leak detected by ASan
### Minetest version

```
Minetest 5.8.0-dev-debug-95056f978-dirty (Linux)
Using Irrlicht 1.9.0mt12
Using Lua 5.1.5
BUILD_TYPE=Debug
RUN_IN_PLACE=0
USE_CURL=1
USE_GETTEXT=0
USE_SOUND=1
STATIC_SHAREDIR="/usr/local/share/minetest"
```

### Active renderer

_No response_

### Irrlicht device

_No response_

### Operating system and version

I hate issue forms. I would have to admit that I'm an Ubuntu user here even though it adds absolutely *nothing* to the issue.

### CPU model

_No response_

### GPU model

_No response_

### OpenGL version

_No response_

### Summary

ASan report:

```
==94522==ERROR: LeakSanitizer: detected memory leaks
 
Direct leak of 56 byte(s) in 1 object(s) allocated from:
    #0 0x7fa5b1dd91e7 in operator new(unsigned long) ../../../../src/libsanitizer/asan/asan_new_delete.cpp:99
    #1 0x56411d786326 in irr::gui::CGUITTFont::load(irr::core::string<char> const&, unsigned int, bool, bool) /home/lars/minetest/src/irrlicht_changes/CGUITTFont.cpp:323
    #2 0x56411d78469f in irr::gui::CGUITTFont::createTTFont(irr::gui::IGUIEnvironment*, irr::core::string<char> const&, unsigned int, bool, bool, unsigned int, unsigned int) /home/lars/minetest/src/irrlicht_changes/CGUITTFont.cpp:229
    #3 0x56411d2a839a in FontEngine::initFont(FontSpec const&) /home/lars/minetest/src/client/fontengine.cpp:252
    #4 0x56411d2a5985 in FontEngine::getFont(FontSpec, bool) /home/lars/minetest/src/client/fontengine.cpp:120
    #5 0x56411d2a5531 in FontEngine::getFont(FontSpec) /home/lars/minetest/src/client/fontengine.cpp:95
    #6 0x56411d11100c in FontEngine::getFont(unsigned int, FontMode) /home/lars/minetest/src/client/fontengine.h:74
    #7 0x56411d31f1fe in GameUI::init() /home/lars/minetest/src/client/gameui.cpp:94
    #8 0x56411d2b758c in Game::initGui() /home/lars/minetest/src/client/game.cpp:1533
    #9 0x56411d2b68f0 in Game::createClient(GameStartData const&) /home/lars/minetest/src/client/game.cpp:1499
    #10 0x56411d2b1792 in Game::startup(bool*, InputHandler*, RenderingEngine*, GameStartData const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, bool*, ChatBackend*) /home/lars/minetest/src/client/game.cpp:1155
    #11 0x56411d2e9b02 in the_game(bool*, InputHandler*, RenderingEngine*, GameStartData const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, ChatBackend&, bool*) /home/lars/minetest/src/client/game.cpp:4523
    #12 0x56411d1b1918 in ClientLauncher::run(GameStartData&, Settings const&) /home/lars/minetest/src/client/clientlauncher.cpp:263
    #13 0x56411de703df in main /home/lars/minetest/src/main.cpp:266
    #14 0x7fa5b0df0d8f in __libc_start_call_main ../sysdeps/nptl/libc_start_call_main.h:58
 
Direct leak of 56 byte(s) in 1 object(s) allocated from:
    #0 0x7fa5b1dd91e7 in operator new(unsigned long) ../../../../src/libsanitizer/asan/asan_new_delete.cpp:99
    #1 0x56411d786326 in irr::gui::CGUITTFont::load(irr::core::string<char> const&, unsigned int, bool, bool) /home/lars/minetest/src/irrlicht_changes/CGUITTFont.cpp:323
    #2 0x56411d78469f in irr::gui::CGUITTFont::createTTFont(irr::gui::IGUIEnvironment*, irr::core::string<char> const&, unsigned int, bool, bool, unsigned int, unsigned int) /home/lars/minetest/src/irrlicht_changes/CGUITTFont.cpp:229
    #3 0x56411d2a839a in FontEngine::initFont(FontSpec const&) /home/lars/minetest/src/client/fontengine.cpp:252
    #4 0x56411d2a5985 in FontEngine::getFont(FontSpec, bool) /home/lars/minetest/src/client/fontengine.cpp:120
    #5 0x56411d2a5531 in FontEngine::getFont(FontSpec) /home/lars/minetest/src/client/fontengine.cpp:95
    #6 0x56411d11100c in FontEngine::getFont(unsigned int, FontMode) /home/lars/minetest/src/client/fontengine.h:74
    #7 0x56411d2a7033 in FontEngine::updateFontCache() /home/lars/minetest/src/client/fontengine.cpp:202
    #8 0x56411d2a6a7c in FontEngine::readSettings() /home/lars/minetest/src/client/fontengine.cpp:184
    #9 0x56411d2a495f in FontEngine::FontEngine(irr::gui::IGUIEnvironment*) /home/lars/minetest/src/client/fontengine.cpp:54
    #10 0x56411d1b0336 in ClientLauncher::run(GameStartData&, Settings const&) /home/lars/minetest/src/client/clientlauncher.cpp:172
    #11 0x56411de703df in main /home/lars/minetest/src/main.cpp:266
    #12 0x7fa5b0df0d8f in __libc_start_call_main ../sysdeps/nptl/libc_start_call_main.h:58
 
SUMMARY: AddressSanitizer: 112 byte(s) leaked in 2 allocation(s).
```

### Steps to reproduce

Compile Minetest with ASan (`cmake -D CMAKE_CXX_FLAGS="-fsanitize=address" .`), join game, leave, quit Minetest.

### PR DESCRIPTION
**Pull request by cx384**
Fixes #13832

## To do

Ready for Review.

## How to test

Compile with `CMAKE_CXX_FLAGS=-fsanitize=address`
Start Luanti and exit.

### CODE REVIEW

**Comment by appgurueu** [comment]
Sounds to me like the caller should drop it after the call then (rather than the callee not grabbing it). The caller should probably use irr_ptr so that automatically happens on scope exit.

**Comment by cx384** [comment]
Oh right `tt_face` is not a copy. I suppose the font should store it then.

(font->load does not take ownership of the face, and the returned font does reference (not copy) it, so I don't think createTTFont should drop the face.)

Edit:
For clarification our `FontEngine` stores the faces, and fonts also grab them (which I had removed), and now they at least drop them again to not leak memory.

File: src/irrlicht_changes/CGUITTFont.h [hunk 1]
```diff
@@ -256,6 +256,7 @@ namespace gui
 			core::vector2di getKerning(const char32_t thisLetter, const char32_t previousLetter) const;
 
 			video::IVideoDriver* Driver = nullptr;
+			irr_ptr<SGUITTFace> m_face = nullptr;
```
Comment (appgurueu) [inline src/irrlicht_changes/CGUITTFont.h]:
```suggestion
			irr_ptr<SGUITTFace> m_face;
```

`irr_ptr` default initializes to `nullptr` like smart pointers in the STL

**Review by appgurueu — APPROVED** [review]
I see, makes sense
