### PR TITLE
[no sq] Some fixes

### LINKED ISSUE #10027: CAOs vanish for one frame when shifting camera offset
_5.3.0-dev_
This happens when the camera offset changes, every 200 nodes traveled. Every CAO including the player vanishes for a frame.
blink
framestep
I tried looking for a quick and dirty fix but it's not as easy as shifting some function calls around. Any help?

### PR DESCRIPTION
**Pull request by sfan5**
- fixes #10027
- addresses one point in #14989 and #15682

## To do

This PR is  Ready for Review.

## How to test

1. make sure camera related things still work as expected

### CODE REVIEW

**Review by SmallJoker — APPROVED** [review]
:ballot_box_with_check: Camera offset each 200 m shows no glitches
:ballot_box_with_check: `--server --worldname "test123"` (new world) prompts for a `--gameid` parameter (there are > 1 games installed) and lists the available worlds.
:question: `--server --worldname "test123" --gameid minetest_game` (new world) picks the first best world and not `test123`. However, I don't think that it's related to this PR.
:ballot_box_with_check: `--server --gameid minetest_game` does pick the first best world.
:ballot_box_with_check: `--server --gameid minetest_game --world "./test123"` creates a new world (using relative path to world)
:ballot_box_with_check: `--server --world "./test123"` prompts for a `--gameid` parameter

The code changes look good and clean. Thank you.

**Comment by lhofhansl** [comment]
@sfan5 This causes the shadow flashing you noticed.

File: src/client/camera.cpp [hunk 1]
```diff
@@ -281,6 +282,20 @@ void Camera::addArmInertia(f32 player_yaw)
 	}
 }
 
+void Camera::updateOffset()
+{
+	v3f cp = m_camera_position / BS;
+
+	// Update offset if too far away from the center of the map
+	m_camera_offset = v3s16(
+		floorf(cp.X / CAMERA_OFFSET_STEP) * CAMERA_OFFSET_STEP,
```
Comment (lhofhansl) [inline src/client/camera.cpp:291]: @sfan5 This will also switch the offset at a fixed position.
Before the change it would not change the offset again, unless you actually move 200 nodes.

Comment (sfan5) [reply src/client/camera.cpp:291]: I see. I missed that on the old code because it wasn't obvious.

No urgent need to change it back however IMO. We should be handling offset changes correctly in the first place, then the timing doesn't matter.
