### PR TITLE
Two ContentDB GUI fixes

### LINKED ISSUE #11155: Contentdb in the launcher should show what content it would like to update, if updates are available
At the moment users can only find out what was updated, when they start the launcher from a terminal, then they get an output like: 
`ACTION[Main]: Installed package to /home/USERNAME/minetest/5.4.0/mods/MODNAME` 
but only **after** the update. 

Mostly I check out first what comes with a new version of a mod, texture or game and then I decide to update it or not. 
At the moment it is intransparent.

### LINKED ISSUE #12670: Can't uninstall a package whilst updates are available
##### Summary
Because the update button replaces the remove button, it's not possible to uninstall a package in the ContentDB menu whilst it has updates. This is especially a problem when updates fail

It is possible to remove the package from the Content tab

### PR DESCRIPTION
**Pull request by grorp**
This PR fixes two minor issues with the ContentDB GUI. I know that a new CDB GUI is in the works, but these issues are such low hanging fruits that I think they should be fixed anyway.

- The dialog now sorts packages that have an update available before all other packages. This allows you to immediately see which packages will be updated when you click "Update All". Fixes #11155.

- You can now uninstall packages that have updates available. Fixes #12670.

## To do

This PR is a Ready for Review.

## How to test

In the CDB GUI:

 - Verify that updatable packages are shown before all other packages.

 - Verify that the "Uninstall" button is also shown for packages that have an update available.

### CODE REVIEW

**Review by rubenwardy — APPROVED** [review]

**Comment by grorp** [comment]
This PR now also includes a commit that reduces the padding of the CDB formspec on ENABLE_TOUCH builds.

File: builtin/mainmenu/dlg_contentstore.lua [hunk 1]
```diff
@@ -908,7 +916,10 @@ function store.get_formspec(dlgdata)
 		formspec[#formspec + 1] = "]"
 
 		-- buttons
-		local left_base = "image_button[-1.55,0;0.7,0.7;" .. core.formspec_escape(defaulttexturedir)
+		local description_width = W - 2.625 - 2*0.7 - 2*0.15
```
Comment (srifqi) [inline builtin/mainmenu/dlg_contentstore.lua:919]:
```suggestion
		local description_width = W - 2.625 - 2 * 0.7 - 2 * 0.15
```

**Review by srifqi — APPROVED** [review]
Screenshot of the browse content page
