### PR TITLE
[no sq] Use polygon offset to fix z-fighting for overlay tiles

### LINKED ISSUE #15632: Overlay tiles Z-fight
### Luanti version

```true
Luanti 5.11.0-dev-c4d624083 (Linux)
Using LuaJIT 2.1.1734355927
Built by GCC 13.3
Running on Linux/6.8.0 x86_64
BUILD_TYPE=Release
RUN_IN_PLACE=0
USE_CURL=1
USE_GETTEXT=1
USE_SOUND=1
STATIC_SHAREDIR="/usr/local/share/luanti"
STATIC_LOCALEDIR="/usr/local/share/locale"
```

### Operating system and version

Linux Mint 22

### CPU model

AMD Athlon(tm) II X4 640 Processor × 4

### GPU model

NVIDIA Corporation GK208B [GeForce GT 730]

### Active renderer

X11

### Summary

When there's a node with hardware coloring and overlay tiles ~~and it's near a mapchunk edge/cross-section (<=2 nodes away)~~, the overlay tiles Z-fight with the tiles underneath. It might be worth mentioning that in both cases shown here, the normal tiles (except for the top one) use `color="white"` to avoid being recolored.

<details>
<summary>VoxeLibre 0.88.0-SNAPSHOT <a href="https://git.minetest.land/VoxeLibre/VoxeLibre/commit/cc82293c7464838d2a1d37e2ab65c43115a1112b"><code>cc82293c74</code></a></summary>

```lua
minetest.register_node("mcl_core:dirt_with_grass", {
	-- ...
	paramtype2 = "color",
	tiles = {"mcl_core_grass_block_top.png", { name="default_dirt.png", color="white" }, { name="default_dirt.png^mcl_dirt_grass_shadow.png", color="white" }},
	overlay_tiles = {"mcl_core_grass_block_top.png", "blank.png", {name="mcl_core_grass_block_side_overlay.png", tileable_vertical=false}},
	palette = "mcl_core_palette_grass.png",
	palette_index = 0,
	color = "#7CBD6B",
	-- ...
})
```
</details>

<details>
<summary>Mineclonia <a href="https://codeberg.org/mineclonia/mineclonia/commit/fed8513572892f83950d96c0c2581eda9d4907fd"><code>fed8513572</code></a></summary>

```lua
minetest.register_node("mcl_core:dirt_with_grass", {
	-- ...
	paramtype2 = "color",
	tiles = {"mcl_core_grass_block_top.png", { name="default_dirt.png", color="white" }, { name="default_dirt.png^mcl_dirt_grass_shadow.png", color="white" }},
	overlay_tiles = {"mcl_core_grass_block_top.png", "blank.png", {name="mcl_core_grass_block_side_overlay.png", tileable_vertical=false}},
	palette = "mcl_core_palette_grass.png",
	palette_index = 0,
	color = "#8EB971",
	-- ...
})
```
</details>

This bug doesn't appear in 5.10.0 or older versions.

### Steps to reproduce

1. Load into a VoxeLibre/Mineclonia world on latest Luanti
2. ~~Enable Block bounds (can be bound to a key in Controls menu)~~
3. Locate a biome that generates `mcl_core:dirt_with_grass` (e.g. `/findbiome Forest`)
4. Fly around and check for Z-fighting on the nodes ~~near the mapblock edges~~

### PR DESCRIPTION
**Pull request by sfan5**
fixes #15632

(third commit unrelated)

## To do

This PR is Ready for Review.

## How to test

1. join MTG world with the following code:
```lua
core.override_item("default:dirt_with_grass", {
	tiles = {"default_grass.png", "default_dirt.png"},
	overlay_tiles = {"", "", {name = "default_grass_side.png", tileable_vertical = false}},
})
```
2. look at grass at various distances (ideally you have a scene that showed z-fighting before)

### CODE REVIEW

File: src/client/wieldmesh.cpp [hunk 1]
```diff
@@ -688,7 +710,9 @@ scene::SMesh *getExtrudedMesh(ITextureSource *tsrc,
 	return mesh;
 }
 
-void postProcessNodeMesh(scene::SMesh *mesh, const ContentFeatures &f,
+// FIXME: this is weirdly inconsistent with what MapBlockMesh does.
+// also set_material is never true.
```
Comment (SmallJoker) [inline src/client/wieldmesh.cpp:714]: Would you please be so nice to keep the previous description/comment from the header file? I think it's a good summary.

File: src/client/mapblock_mesh.cpp [hunk 2]
```diff
@@ -702,6 +702,16 @@ MapBlockMesh::MapBlockMesh(Client *client, MeshMakeData *data, v3s16 camera_offs
 				tex.MinFilter = video::ETMINF_NEAREST_MIPMAP_NEAREST;
 				tex.MagFilter = video::ETMAGF_NEAREST;
 			});
+			/*
+			 * The second layer is for overlays, but uses the same vertex positions
+			 * as the first, which quickly leads to z-fighting.
+			 * To fix this we can offset the polygons in the direction of the camera.
+			 * This only affects the depth buffer and leads to no visual gaps in geometry.
+			 */
+			if (layer == 1) {
```
Comment (SmallJoker) [inline src/client/mapblock_mesh.cpp:711]: Suggestion for `tile.h`:
```C++
enum {
	TILE_LAYER_NORMAL = 0,
	TILE_LAYER_OVERLAY = 1,
	MAX_TILE_LAYERS = 2
};
```
And here (and in `createSpecialNodeMesh`): `if (layer == TILE_LAYER_OVERLAY)`

1. Easier code searching by keywords
2. Mostly self-explaining code branches

**Review by SmallJoker — COMMENTED** [review]
Tested with a more distinct overlay, however I cannot reproduce the issue in master. Neither with the opengl nor opengl3 driver on my AMD Polaris card. The overlay is always above.
```Lua
core.override_item("default:dirt_with_grass", {
	tiles = {"default_dirt.png", "default_dirt.png"},
	overlay_tiles = {"", "", {name = "default_cobble.png", tileable_vertical = false}},
})
```
This PR does not break anything on my side and the code looks good (aside minor comments). Will above after the comments were handled.

File: src/client/wieldmesh.cpp (hunk 1 above)
Comment (sfan5) [reply src/client/wieldmesh.cpp:714]: it's still there are the very top

File: src/client/mapblock_mesh.cpp (hunk 2 above)
Comment (sfan5) [reply src/client/mapblock_mesh.cpp:711]: I don't disagree, but `0` and `1` are already used as constants all over the code and having an enum value used only once may be confusing than not having it.
I'll add an explanation next to `MAX_TILE_LAYERS` however.

Comment (SmallJoker) [reply src/client/mapblock_mesh.cpp:711]: Alright. Thank you.

**Review by SmallJoker — APPROVED** [review]
