### PR TITLE
Avoid crash caused by, and improve, 'findSpawnPos()' 

### LINKED ISSUE #8722: Avoid crash caused on spawn when using some extreme mapgen parameters
For example, in mgv7, if terrain surface is set to be at y = 32000:
Even though terrain will not appear there due to being outside MAX_MAP_GENERATION_LIMIT, the spawning code of mgv7 (and maybe some other mapgens) will attempt to place the player there, causing an 'object out of bounds' crash.

### PR DESCRIPTION
**Pull request by paramat**
Avoid crash caused by, and improve, 'findSpawnPos()'

Avoid an unsuitable spawn position (which if outside mapgen limits can
cause a crash) if the main 0-3999 loop reaches its end. Fallback to a
spawn at 0,0,0.
Check the mapgen-returned 'spawn_level' value for being outside limits.
When 'air_count' reaches 2, move back down 1 to spawn in the lower
empty node.
If the spawn position is disallowed by 'objectpos_over_limit()', 'break'
from loop instead of 'continue' because positions above are probably
also over limit.
Reset 'air_count' to 0 if an obstruction is found, to make 'air_count'
consecutive empty nodes.
Add clarifying comments and improve codestyle.
////////////////////////////////////////
Commit 2:
Allow spawn in 'airlike' drawtype nodes
////////////////////////////////////////

Closes #8722 

How to test

The following mapgen parameters added to .conf, when using mgv7, will cause a crash in master branch. With this PR spawn falls back to 0,0,0.
'engine_spawn = true' is required to disable MTG spawn mod which may interfere.
```
engine_spawn = true
mgv7_np_terrain_base = {
    offset      = 32000,
    scale       = 0,
    spread      = (600, 600, 600),
    seed        = 82341,
    octaves     = 5,
    persistence = 0.6,
    lacunarity  = 2.0,
    flags       = eased
}
mgv7_np_terrain_alt = {
    offset      = 32000,
    scale       = 0,
    spread      = (600, 600, 600),
    seed        = 5934,
    octaves     = 5,
    persistence = 0.6,
    lacunarity  = 2.0,
    flags       = eased
}
```
These set the terrain surface to y = 32000.
The actual surface level is of course is limited to y = 30900 or so by 'mapgen limit'. However, the 'get spawn level at point' function of mgv7 actually returns y = 32000 in this situation (which i will fix in a separate PR), causing the player to be spawned at y = 32001. This then causes a crash as described above.

### CODE REVIEW

**Comment by paramat** [comment]
Just to document some useful results:

Using a mgflat world consisting of entirely jungletrees (maximum spawn obstruction):
With all these debugging messages added, here are the messages for a spawn in a new world.
The emerged mapblocks are all ungenerated so consist of ignore, this cannot avoid spawning inside a decoration as those haven't been generated yet:
```
0-4000 main loop 0
mapgen-returned spawn level at point 8
0-10 upwards search loop 0
air or ignore
0-10 upwards search loop 1
air or ignore
consecutive air count > 2
is good, final return
```
Now after death, a respawn in the same world. This time there are generated mapblocks, so these are emerged and searched through to avoid spawning inside decorations:
```
0-4000 main loop 0
mapgen-returned spawn level at point 8
0-10 upwards search loop 0
not air or ignore (mapblock generated)
0-10 upwards search loop 1
not air or ignore (mapblock generated)
0-10 upwards search loop 2
not air or ignore (mapblock generated)
0-10 upwards search loop 3
not air or ignore (mapblock generated)
0-10 upwards search loop 4
not air or ignore (mapblock generated)
0-10 upwards search loop 5
not air or ignore (mapblock generated)
0-10 upwards search loop 6
not air or ignore (mapblock generated)
0-10 upwards search loop 7
not air or ignore (mapblock generated)
0-4000 main loop 1
mapgen-returned spawn level at point 8
0-10 upwards search loop 0
not air or ignore (mapblock generated)
0-10 upwards search loop 1
not air or ignore (mapblock generated)
0-10 upwards search loop 2
not air or ignore (mapblock generated)
0-10 upwards search loop 3
air or ignore
0-10 upwards search loop 4
air or ignore
consecutive air count > 2
is good, final return
```
The first XZ position is avoided, it seems to be a tall tree trunk, the second XZ position succeeds and i spawn on top of a jungletree root.

**Comment by paramat** [comment]
Retested. No longer WIP.

File: src/server.cpp [hunk 1]
```diff
@@ -3512,52 +3512,68 @@ v3f Server::findSpawnPos()
...
+		// Search upwards from 'spawn level' for 2 consecutive empty nodes, to
+		// avoid obstructions in already-generated mapblocks.
+		// In ungenerated mapblocks consisting of 'ignore' nodes, there will be
+		// no obstructions, but mapgen decorations are generated after spawn so
+		// the player may end up inside one.
+		for (s32 i = 0; i < 8; i++) {
 			v3s16 blockpos = getNodeBlockPos(nodepos);
 			map.emergeBlock(blockpos, true);
 			content_t c = map.getNodeNoEx(nodepos).getContent();
 			if (c == CONTENT_AIR || c == CONTENT_IGNORE) {
```
Comment (SmallJoker) [inline src/server.cpp]: While you're improving the code: this should be a check against `drawtype = "airlike"` to allow other realms.

Comment (paramat) [reply src/server.cpp]: Will do, but checking 'air_equivalent = true' may be better, as that is what signifies a node as being some kind of 'atmosphere' or even 'vacuum'.

Comment (paramat) [reply src/server.cpp]: Confirmed this is an issue. If a mod replaces "air" with "airlike" drawtype nodes, such as vacuum, alien atmosphere or fog etc., spawning into an existing world unnecessarily tries to avoid these nodes.

Comment (paramat) [reply src/server.cpp]: Done and tested.

**Comment by paramat** [comment]
2nd commit added. PR is ready.

I wrote a mod that replaces all air with an airlike node in 'register on generated'.
In master, respawn after death tries to avoid these airlike nodes, so respawn is away from 0,0.
In PR, respawn occurs very near 0,0 inside the airlike nodes.
(Note: This has to be tested in mgflat so that 0,0 is always a suitable spawn point. Also 'engine_spawn = true' must be used to disable interference frm the MTG 'spawn' mod.)

My mod code:
```
-- Nodes

minetest.register_node("airlikespawn:airlike", {
	description = "Airlike",
	drawtype = "airlike",
	paramtype = "light",
	is_ground_content = false,
	sunlight_propagates = true,
	walkable = false,
	pointable = false,
	diggable = false,
	buildable_to = true,
	floodable = true,
	post_effect_color = {a = 63, r = 255, g = 255, b = 255},
})

-- Localise data buffer

local data = {}

-- On generated function

minetest.register_on_generated(function(minp, maxp, seed)
	local x0 = minp.x
	local y0 = minp.y
	local z0 = minp.z
	local x1 = maxp.x
	local y1 = maxp.y
	local z1 = maxp.z
	
	local vm, emin, emax = minetest.get_mapgen_object("voxelmanip")
	local area = VoxelArea:new{MinEdge = emin, MaxEdge = emax}
	vm:get_data(data)
	
	local c_air = minetest.get_content_id("air")
	local c_airlike = minetest.get_content_id("airlikespawn:airlike")

	for z = z0, z1 do
	for y = y0, y1 do
		local vi = area:index(x0, y, z)
		for x = x0, x1 do
			if data[vi] == c_air then
				data[vi] = c_airlike
			end
			vi = vi + 1
		end
	end
	end
	
	vm:set_data(data)
	vm:write_to_map(data)
end)
```
