### PR TITLE
Fix types of get_mapgen_setting_noiseparams

### LINKED ISSUE #11962: Noiseparams returned to Lua contain some numbers as strings.
##### Minetest version
Latest
```
5.5.0-dev-7c93b2d7a
```
##### Summary

Noise parameters returned by `minetest.get_mapgen_setting_noiseparams` and `Settings:get_np_group` contain some parameters as string and some others as numbers (only `octaves` and `seed`). Functions taking noise params as input seem to accept string values, but it gets confusing when doing math in Lua with these noiseparams.

The obvious way to workaround it is using `tonumber`, but the fact that this is needed is not documented anywhere (afaik?), and is not logically expected.

This string format has been introduced by a1e1a19 to fix issues in advanced settings formspecs (which need strings) but I consider it's the job of the settings tab to convert to string what it needs, and this should not surface to the modding API.

[c_content.cpp L1697-1719](https://github.com/minetest/minetest/blob/f66ed2c/src/script/common/c_content.cpp#L1697-L1719)

##### Steps to reproduce

```lua
local np_heat = minetest.get_mapgen_setting_noiseparams("mg_biome_np_heat")

local jsonstr = minetest.write_json(np_heat, true)
print(jsonstr)
```

Output in my case:
```json
{
   "flags" : "defaults",
   "lacunarity" : "2",
   "octaves" : 3,
   "offset" : "50",
   "persistence" : "0.5",
   "scale" : "50",
   "seed" : 5349,
   "spread" : {
      "x" : "1000",
      "y" : "1000",
      "z" : "1000"
   }
}
```

### PR DESCRIPTION
**Pull request by appgurueu**
Bugfix. Closes #11962, ready for review. Mainmenu noiseparam setting editing still works. @srifqi

Regarding possible breakage:

* The **documentation** mentions numbers and not strings, so the old behavior was clearly a **bug** nobody should have relied on;
* When passing params to **setters both numbers and strings were, are and continue to be supported** (by means of `tonumber`);
* If somebody **`tonumber`ed the strings, that is a no-op for numbers and works as expected** there;
* If somebody performed **arithmetic** or called **math funcs** on the strings, relying on the implicit conversion Lua does, that will obviously work with numbers too;
* And **even most (all?) string operations will, due to the same implicit string-number conversion, just stringify the number**;

The only thing this would break would be actual typechecks for a buggy type or trying to index the number (something like `noiseparams.something:sub(...)`, but I suppose that hardly matters. Should it be found in the wild, it's *definitely* utter swinecode and on the mod authors, who should be urged to upgrade.

Also note that prior to 5.0, said getter would return numbers.

### CODE REVIEW

**Review by sfan5 — APPROVED** [review]

**Review by SmallJoker — APPROVED** [review]
LGTM

File: builtin/mainmenu/dlg_settings_advanced.lua [hunk 1]
```diff
@@ -517,24 +517,20 @@ end
```
Comment (Gael-de-Sailly) [inline builtin/mainmenu/dlg_settings_advanced.lua:517]: I'm coming too late but `%g` string serialization needs to be applied in the previous function `get_current_np_group` too

Causes rounding issues on the dialogs
image

(I don't know how to make a comment outside the scope of the changes)
