### PR TITLE
Fix minetest.is_nan

### LINKED ISSUE #10121: 'minetest.is_nan' is broken!
##### Minetest version
```
Minetest-5.3.0-dev-80d9e9c18
```

##### Summary
If a passed number to `minetest.is_nan` is NaN actually (you know it e.g. from debugging), it won`t return true. If you check so: 'v ~= v', the way will work fine instead. In my case it was -nan.

##### Steps to reproduce
1. Make sure your number is NaN.
2. Try to call `minetest.is_nan` with passed as its arguments that value.
3. Now try to check via `number ~= number` way.

### PR DESCRIPTION
**Pull request by appgurueu**
Trivial. Closes #10121

### CODE REVIEW

File: builtin/common/misc_helpers.lua [hunk 1]
```diff
@@ -697,3 +697,7 @@ function core.privs_to_string(privs, delim)
 	end
 	return table.concat(list, delim)
 end
+
+function core.is_nan(number)
+	return number ~= number
+end
```
Comment (rubenwardy) [inline builtin/common/misc_helpers.lua:703]: Missing new line

**Comment by rubenwardy** [comment]
LGTM apart from that

**Review by rubenwardy — APPROVED** [review]
