### PR TITLE
Stabilise 'day night ratio' to fix object brightness flicker

### LINKED ISSUE #8416: Objects flicker in brightness between time 6125 and 6375 (and at sunset) (basic shaders on)
Noticed this while when working on something else.

I added printf() lines to src/daynightratio.h.
When basic shaders are on, the `smooth` bool is true so the loop at the end of the function is used.
```
inline u32 time_to_daynight_ratio(float time_of_day, bool smooth)
{
	float t = time_of_day;
	if(t < 0)
		t += ((int)(-t)/24000)*24000;
	if(t >= 24000)
		t -= ((int)(t)/24000)*24000;
	if(t > 12000)
		t = 24000 - t;
	float values[][2] = {
		{4250+125, 150},
		{4500+125, 150},
		{4750+125, 250},
		{5000+125, 350},
		{5250+125, 500},
		{5500+125, 675},
		{5750+125, 875},
		{6000+125, 1000},
		{6250+125, 1000},
	};
	if(!smooth){
		float lastt = values[0][0];
		for(u32 i=1; i<sizeof(values)/sizeof(*values); i++){
			float t0 = values[i][0];
			float switch_t = (t0 + lastt) / 2;
			lastt = t0;
			if(switch_t <= t)
				continue;
			return values[i][1];
		}
		return 1000;
	}

	for (u32 i=0; i < sizeof(values) / sizeof(*values); i++) {
			if (values[i][0] <= t)
				continue;
			if (i == 0)
				return values[i][1];
			float td0 = values[i][0] - values[i-1][0];
			float f = (t - values[i-1][0]) / td0;
			printf(" t %f", t);
			printf(" f %f", f);
			printf(" dnr %f\n", f * values[i][1] + (1.0 - f) * values[i-1][1]);
			return f * values[i][1] + (1.0 - f) * values[i-1][1];
		}
		printf(" dnr %f\n", 1000.0);
		return 1000;
}
```
Also to src/light.h.
```
inline u8 blend_light(u32 daylight_factor, u8 lightday, u8 lightnight)
{
	u32 c = 1000;
	u32 l = ((daylight_factor * lightday + (c - daylight_factor) * lightnight)) / c;
	printf(" bl %d", l);
	if (l > LIGHT_SUN)
		l = LIGHT_SUN;
	return l;
}
```
to print:
* time (t)
* the internal interpolated daynightratio float value (dnr)
* calculated light level for objects (bl)

I discovered that `time_to_daynight_ratio()` behaves like this:

During sunrise until time 6125, day night ratio smoothly increases towards 1000 (full brightness) as it interpolates between the value pairs in the table.

Between time 6125 and 6375 it is interpolating between two 1000 values, but tiny float errors cause the result of the interpolation to jump back and forth between, for example, 999.999995 and 1000.000006. Because the function returns an integer the returned value switches between 999 and 1000.
Printing the light level calculated by `blend_light()` shows that these tiny changes cause the lightlevel to jump back and forth between 14 and 15, causing objects to flicker.
This is only noticeable recently because the visual brightness of light levels 14 and 15 were identical until recently, now they differ.

After time 6375 the function returns 1000 all the time, the calculated light level is always 15 and object brightness stops flickering.

Printed data in terminal:
During flicker:
```
 t 6182.919434 f 0.231678 dnr 999.999994
 t 6182.919434 f 0.231678 dnr 999.999994
 t 6183.259277 f 0.233037 dnr 999.999995
 t 6183.259277 f 0.233037 dnr 999.999995
 t 6183.259277 f 0.233037 dnr 999.999995
 bl 14 bl 14 bl 14 bl 14 bl 14 bl 14 bl 14 bl 14 bl 14 bl 14 bl 14 bl 14 bl 14 bl 14
 t 6183.259277 f 0.233037 dnr 999.999995
 t 6183.259277 f 0.233037 dnr 999.999995
 t 6183.259277 f 0.233037 dnr 999.999995
 t 6183.259277 f 0.233037 dnr 999.999995
 t 6183.259277 f 0.233037 dnr 999.999995
 t 6183.259277 f 0.233037 dnr 999.999995
```
```
 t 6184.917969 f 0.239672 dnr 1000.000004
 t 6184.917969 f 0.239672 dnr 1000.000004
 t 6185.257812 f 0.241031 dnr 1000.000006
 t 6185.257812 f 0.241031 dnr 1000.000006
 t 6185.257812 f 0.241031 dnr 1000.000006
 bl 15 bl 15 bl 15 bl 15 bl 15 bl 15 bl 15 bl 15 bl 15 bl 15 bl 15 bl 15 bl 15 bl 15
 t 6185.257812 f 0.241031 dnr 1000.000006
 t 6185.257812 f 0.241031 dnr 1000.000006
 t 6185.257812 f 0.241031 dnr 1000.000006
 t 6185.257812 f 0.241031 dnr 1000.000006
 t 6185.257812 f 0.241031 dnr 1000.000006
 t 6185.257812 f 0.241031 dnr 1000.000006
```
After time 6375:
```
 dnr 1000.000000
 dnr 1000.000000
 dnr 1000.000000
 dnr 1000.000000
 dnr 1000.000000
 bl 15 bl 15 bl 15 bl 15 bl 15 bl 15 bl 15 bl 15 bl 15 bl 15 bl 15 bl 15 bl 15 bl 15
 dnr 1000.000000
 dnr 1000.000000
 dnr 1000.000000
 dnr 1000.000000
 dnr 1000.000000
 dnr 1000.000000
```
I will fix this soon.
A similar problem may possibly occur when time is between 4375 and 4625, as the interpolation is between 2 identical values.

### PR DESCRIPTION
**Pull request by paramat**
Stabilise 'day night ratio' to fix object brightness flicker

Previously, when basic shaders were enabled, the function
time_to_daynight_ratio() returned values jumping between 149 and 150
between times 4375 and 4625, and values jumping between 999 and 1000
between times 6125 and 6375, (and the corresponding times at sunset)
due to tiny float errors in the interpolation code.

This caused the light level returned by blend_light() to jump between
14 and 15, which became noticeable recently as those light levels were
given different visual brightnesses.

Add early returns to avoid the problematic interpolation, and to
avoid unnecessary running of the loop.
///////////////////////////////

Closes #8416 
Note: The codestyle is bad, table can have fewer entries and needs to be 'static', optimisation of the shaders off case may be possible, but to keep the bugfix clear i am leaving all that to a follow up PR.

The added early returns trigger at the times which would normally cause a fluctuating return value (149<->150 and 999<->1000). The early returns avoid the loop being run unnecessarily.

### CODE REVIEW

File: src/daynightratio.h [hunk 1]
```diff
@@ -52,15 +52,17 @@ inline u32 time_to_daynight_ratio(float time_of_day, bool smooth)
...
 	}
 
+	if (t <= 4625) // 4500 + 125
+		return values[0][1];
+	else if (t >= 6125) // 6000 + 125
+		return 1000;
 	for (u32 i=0; i < sizeof(values) / sizeof(*values); i++) {
 			if (values[i][0] <= t)
 				continue;
-			if (i == 0)
```
Comment (paramat) [inline src/daynightratio.h]: This is removed because it is never true.

File: src/daynightratio.h [hunk 2]
```diff
@@ -52,15 +52,17 @@ inline u32 time_to_daynight_ratio(float time_of_day, bool smooth)
...
-				return values[i][1];
+
 			float td0 = values[i][0] - values[i-1][0];
 			float f = (t - values[i-1][0]) / td0;
 			return f * values[i][1] + (1.0 - f) * values[i-1][1];
 		}
 		return 1000;
```
Comment (paramat) [inline src/daynightratio.h]: This line is no longer necessary but removing it causes a 'function reaches end of control' build warning.

File: src/environment.cpp [hunk 3]
```diff
@@ -47,6 +47,8 @@ u32 Environment::getDayNightRatio()
 	MutexAutoLock lock(this->m_time_lock);
 	if (m_enable_day_night_ratio_override)
 		return m_day_night_ratio_override;
+	printf("t %5.0f", m_time_of_day_f * 24000);
+	printf(" dnr %d\n", time_to_daynight_ratio(m_time_of_day_f * 24000, m_cache_enable_shaders));
```
Comment (paramat) [inline src/environment.cpp]: These 2 lines are just for testing the PR.

Comment (paramat) [reply src/environment.cpp]: Now removed.

**Comment by paramat** [comment]
Tested and testing code removed, ready for review.

**Comment by lhofhansl** [comment]
Can't claim I understand that code. Looks reasonable, though.
One question I had: Why can't we fix the rounding problems in the interpolation code?

**Comment by paramat** [comment]
We can, and probably should, see https://github.com/minetest/minetest/issues/8416#issuecomment-476032514
But i think that should be done in a later PR as that will probably involve creating a new MT function for use in multiple places.

**Comment by paramat** [comment]
Will merge as trivial and move on to follow-up PRs.
