### PR TITLE
Biomemap: Avoid empty biomemap entry to fix failing biome dust 

### LINKED ISSUE #7392: Biome dust and water surface decorations fail when solid surface falls below mapchunk base
screenshot_20180601_054515

screenshot_20180601_054457

^ Below patch of missing dust. (Mgv7. Note icesheet biome has been forced using settings)

'generateBiomes()' constructs the biomemap as it generates biomes. The biome calculated at first stone surface encountered is added to the biomemap:
https://github.com/minetest/minetest/blob/162ffd7fba9d4e79a29f65686f3efbebaee9cee8/src/mapgen/mapgen.cpp#L695
But if no stone surface is encountered in a column of a mapchunk the biomemap is left empty for that position.
Biome 'dust' placement relies on the biomemap to know what dust to place:
https://github.com/minetest/minetest/blob/162ffd7fba9d4e79a29f65686f3efbebaee9cee8/src/mapgen/mapgen.cpp#L780
Decoration placement also relies on the biomemap, so any decorations that are placed on a water surface would fail too.

If in 'generateBiomes()' the mapchunk base is reached without a biomemap entry being made we need to add a biome to the biomemap.

### PR DESCRIPTION
**Pull request by paramat**
'generateBiomes()' constructs the biomemap as it generates biomes.
The biome calculated at first stone surface encountered is added to
the biomemap.
Previously, if no stone surface was encountered in a mapchunk column
the biomemap was left empty for that (x, z) position, causing biome
dust and water surface decoration placement to fail.

If at the base of a mapchunk column the biomemap is empty, add the
currently active biome to the biomemap, or if biome is NULL calculate
it for this position and add it to the biomemap.
/////////////////////////////

screenshot_20180601_062308

^ Fixed, compare with issue screenshot.

screenshot_20180602_011836

^ Fixed, compare with issue screenshot.

Fixes #7392

### CODE REVIEW

File: src/mapgen/mapgen.cpp [hunk 1]
```diff
@@ -761,6 +762,19 @@ void MapgenBasic::generateBiomes()
...
+		// If no stone surface was detected in this mapchunk column the biomemap
+		// will be empty for this (x, z) position. Add the currently active
+		// biome to the biomemap, or if biome is NULL calculate it for this
+		// position.
+		if (biomemap[index] == BIOME_NONE) {
+			if (biome) {
+				biomemap[index] = biome->index;
+			} else {
+				biome =
+					biomegen->getBiomeAtIndex(index, v3s16(x, node_min.Y, z));
```
Comment (paramat) [inline src/mapgen/mapgen.cpp]: Indentation looks weird due to github 8 space indent, but is needed to avoid a long line with 4 space indent.

Comment (SmallJoker) [reply src/mapgen/mapgen.cpp]: It would also be allowed to break the line before it reaches the character limit.

Comment (paramat) [reply src/mapgen/mapgen.cpp]: Oops, thanks will fix that soon.
An alternative line split may be better too.

Comment (paramat) [reply src/mapgen/mapgen.cpp]: Done in #7398
