### PR TITLE
Remove workaround for normals not matching winding order

### LINKED ISSUE #12430: Minetest recalculates normals if they don't match the winding order
##### Minetest version

```
5.6.0-dev
```

This is a regression introduced in https://github.com/minetest/minetest/commit/1175f48d05 @x2048 

##### Summary

In previous Minetest versions, face normals set in the B3D would override the winding order of the triangle. Now the winding order of the triangle overrides the face normal if the calculated normal points in another direction. This requires matching winding order & generated normals when generating models.

##### Steps to reproduce

Verify the normals being completely wrong for the attached B3D model [`cube.zip`](https://github.com/minetest/minetest/files/8883790/cube.zip).

`init.lua`:
```lua
minetest.register_entity("testentities:normals", {
	visual = "mesh",
	mesh = "cube.b3d",
	backface_culling = true
})
```

then `/spawnentity testentities:normals`.

Screenshot

##### Additional context

I don't know whether the winding order or the explicitly set normal should take precedence here. It is possible to trivially fix this by reversing the winding order if the normal points in the opposite direction:

```lua
local function fix_winding_order(indices)
	local poses = {}
	for i = 1, 3 do
		poses[i] = modlib.vector.new(vertices[indices[i]].pos)
	end
	local tri_normal = modlib.vector.triangle_normal(poses)
	if tri_normal:dot(normal) <= 0 then
		modlib.table.reverse(indices)
		modlib.table.reverse(poses)
		tri_normal = modlib.vector.triangle_normal(poses)
		assert(tri_normal:dot(normal) > 0)
	end
	return indices
end
```

Probably low priority.

### PR DESCRIPTION
**Pull request by x2048**
Fixes #12430.

After this, correct shading of entities requires correct or zero normals in the models. There is a related fix for the B3D exporter for Blender: GreenXenith/io_scene_b3d#7.

## To do

This PR is Ready for Review.

## How to test

Use the test from #12430.

@appgurueu

### CODE REVIEW

File: src/client/mesh.cpp [hunk 1]
```diff
@@ -346,19 +346,6 @@ bool checkMeshNormals(scene::IMesh *mesh)
 
 		if (!std::isfinite(length) || length < 1e-10f)
 			return false;
-
-		const u16 count = MYMIN(MAX_FACES_TO_CHECK * 3, buffer->getIndexCount() - 3);
```
Comment (SmallJoker) [inline src/client/mesh.cpp:350]: MAX_FACES_TO_CHECK is now unused. GCC complains.

**Comment by SmallJoker** [comment]
Is the cube supposed to look like this? The shading looks correct now, hence I assume that's the bugfix?

PR:
grafik

master:
grafik

**Comment by appgurueu** [comment]
> Is the cube supposed to look like this? The shading looks correct now, hence I assume that's the bugfix?
> 
> PR: grafik

That's definitely an improvement. The cube is actually supposed to look like a full cube. Looks like backface culling still determines normals based on winding order... Either way this is low-priority for me as I've just made the winding order of my faces match the normals.

**Review by sfan5 — APPROVED** [review]
LGTM

**Review by SmallJoker — APPROVED** [review]
Works better than before :+1:
