### PR TITLE
Attachments: Fix attachments to temporary removed objects

### LINKED ISSUE #8929: Attached player disappears after entity reloads
##### Minetest version

```
5.1.0-dev (latest master)
```

##### Summary
If another player gets attached to an entity (like a cart) and that entity then moves away from you, it unloads after a while which is to be expected. When you get closer to that entity with the player again, the entity reappears but the player is missing.

The player's name tag is stuck at 0,0,0 it seems.

Here is a video that demonstrates the issue: https://ihrfussels-server.de/entitybug.mp4

### PR DESCRIPTION
**Pull request by SmallJoker**
Fixes #8929 by not clearing the attachment upon object removal.

## To do

This PR is Ready for Review.

## How to test

Imported from #8929:
1) Player 1 sits in a car(t), player 2 watches
2) Player 1 drives away, until either the parent object or the player is unloaded client-side
3) Drive back, and all attachments must be the same

Now do this for various combinations of `player_transfer_distance` and `active_block_range`:
 * Where former is notable bigger than latter
 * Where latter is notable bigger than former

Additional tests: #8701 (to confirm that it still works as intended)

### CODE REVIEW

File: src/content_sao.cpp [hunk 1]
```diff
@@ -1109,7 +1109,7 @@ void PlayerSAO::step(float dtime, bool send_recommended)
 
 	// If the object is attached client-side, don't waste bandwidth sending its
 	// position or rotation to clients.
-	if (m_position_not_sent && !isAttached()) {
```
Comment (sfan5) [inline src/content_sao.cpp]: code comment above is no longer correct

File: src/server.cpp [hunk 2]
```diff
@@ -694,19 +694,33 @@ void Server::AsyncRunStep(bool initial_step)
 		// Route data to every client
 		for (const auto &client_it : clients) {
 			RemoteClient *client = client_it.second;
+			PlayerSAO *player = getPlayerSAO(client->peer_id);
 			std::string reliable_data;
 			std::string unreliable_data;
 			// Go through all objects in message buffer
 			for (const auto &buffered_message : buffered_messages) {
 				// If object is not known by client, skip it
```
Comment (sfan5) [inline src/server.cpp]:
```suggestion
				// If object does not exist or is not known by client, skip it
```

**Comment by IhrFussel** [comment]
I tested this PR and it fixes my reported bug it seems.

If the cart with the player is too far away the cart unloads and the player model floats above ground so the position even updates when entity is out of sight which is actually something good think.

**Comment by IhrFussel** [comment]
This PR makes behavior inconsistent between 5.0.1 and 5.1.0 clients though:

**5.1.0 client**

- Sees realtime position of attached player name tag even after entity unloaded

**5.0.1 client**

- Only sees last known position of name tag before entity unloaded
- Additionally the name tag moves to ~ 200 nodes away from 0,0,0 after a bit

**Comment by sfan5** [comment]
We can't fix broken behaviour of older releases of Minetest clients.

**Comment by SmallJoker** [comment]
@IhrFussel I am well aware of this difference. In fact, that could be removed from this PR without any impact, but do you really want to keep this buggy behaviour? Doubt it.
