### PR TITLE
Attachments: Fix interpolation from (0,0,0) after detach

### LINKED ISSUE #8037: Selection/collisionboxes of entities attached to entities not functional further than 200 nodes from (0,0,0)
Tested in singleplayer, at commit a5197eaebc61ac6b555a640f36c0b427faef381d

Below, the highest entity is attached to the middle entity, which is attached to the lowest entity.
The lowest (parent) entity is placed where the player spawns.

screenshot_20181231_052440

^ Using `static_spawnpoint = 0,10,0` or  `static_spawnpoint = 199,10,0` in mgflat. All 3 selectionboxes are visible

screenshot_20181231_053020

^ Using `static_spawnpoint = 201,10,0` in mgflat. Only the parent entity selectionbox is visible

The 200 value suggests this is related to camera offset that is applied every 200 nodes:
https://github.com/minetest/minetest/blob/c6f784f43bca3328c6810c26c8bda2ea507c70e8/src/client/camera.cpp#L432
https://github.com/minetest/minetest/blob/c6f784f43bca3328c6810c26c8bda2ea507c70e8/src/client/camera.cpp#L39

Seems confirmed. If the player spawns at (199,10,0) there is no bug.
Then if the player crosses x = 200 the bug occurs.
Crossing back over x = 200 doesn't fix the bug because camera offset only resets to (0,0,0) once you pass back over x = 0.

Test code:
```
minetest.register_entity("lab:cube", {
	initial_properties = {
		physical = false,
		collide_with_objects = false,
		collisionbox = {-1, -1, -1, 1, 1, 1},
		selectionbox = {-1, -1, -1, 1, 1, 1},
		visual = "cube",
		textures = {
			"lab_no_texture.png",
			"lab_no_texture.png",
			"lab_no_texture.png",
			"lab_no_texture.png",
			"lab_no_texture.png",
			"lab_no_texture.png",
		},
		pointable = true,
	},
})

minetest.after(5, function()
	local pos = minetest.get_player_by_name("singleplayer"):get_pos()
	local ent1 = minetest.add_entity(pos, "lab:cube")
	local ent2 = minetest.add_entity(pos, "lab:cube")
	local ent3 = minetest.add_entity(pos, "lab:cube")
	minetest.after(1, function()
		ent1:set_attach(ent2, "", {x = 0, y = 20, z = 20}, {x = 0, y = 0, z = 0})
		ent2:set_attach(ent3, "", {x = 0, y = 20, z = 20}, {x = 0, y = 0, z = 0})
	end)
end)
```
I'm surprised this hasn't been reported already.
@GreenXenith you seem to be the person who first reported this, do you know if this is a newly-occuring bug?

### LINKED ISSUE #9140: Detachment snaps client side player object to origin, also bad interpolation
5.1.0 and earlier
Dual issue:
- Every time a player object gets detached from an entity, her position is set to 0,0,0 and she then flies back from there into the correct spot.
- The client extrapolates player velocity in this horrible way that makes everyone look like a jack-in-a-box on a really tight spring.

This happens even when dual-clienting on the same machine. (or maybe only in these circumstances? I don't have a server yet)

Gallery of horrors: ( also starring #2813 )
lerp
kill it
wat

### PR DESCRIPTION
**Pull request by SmallJoker**
Fixes #9140.
Fixes #8037. (EDIT)
The position of attached objects was updated in `GenericCAO::step()` but the value was incorrect due to camera shifting.

1) `GenericCAO::getPosition()` now always returns the absolute position
2) Simplify LocalPlayer attachments: introduce `getParent()`
3) Get rid of `LocalPlayer::overridePosition` -> now uses `getPosition()` from `GenericCAO`

~As an effect, the camera position now roughly uses the head position as origin. Thus, this PR is a breaking change for now.~

## To do

This PR is Ready for Review.

- [x] ~Decide whether this is ok: (probably not)~ SOLVED. Old behaviour restored
Offsets

## How to test

1) `functions.lua` in the carts mod (or boost_cart)
2)
```Lua
-- On attach
		player:set_attach(obj, "", {x=12, y=-4, z=12}, {x=12, y=-4, z=12})
		player:set_eye_offset({x=0, y=0, z=0},{x=0, y=0, z=0})
```

### CODE REVIEW

File: src/client/camera.cpp [hunk 1]
```diff
@@ -285,9 +285,11 @@ void Camera::update(LocalPlayer* player, f32 frametime, f32 busytime, f32 tool_r
 	// Smooth the movement when walking up stairs
 	v3f old_player_position = m_playernode->getPosition();
 	v3f player_position = player->getPosition();
-	if (player->isAttached && player->parent)
-		player_position = player->parent->getPosition();
-	//if(player->touching_ground && player_position.Y > old_player_position.Y)
+
+	// This is worse than `LocalPlayer::getPosition()` but keeps mod compat
```
Comment (sfan5) [inline src/client/camera.cpp]: could use some elaboration:
what did mods expect (what do we do)? what should "correctly" happen?

**Comment by SmallJoker** [comment]
Updated.

**Comment by hecktest** [comment]
Nice, does this fix the janky interpolation too or should that be carved out into another bug?

**Comment by SmallJoker** [comment]
@hecktest Please be more precise. Which "janky interpolation" problem do you mean?

**Comment by hecktest** [comment]
No, I'm talking about the springy behavior of player entities other than your own. The gifs in  #9140 illustrate this.

**Comment by SmallJoker** [comment]
@hecktest 
> Fixes #9140. 

This means it closes that particular issue by fixing it. Hence, this PR is a bugfix created to fix that issue. Should be clear enough IMO.

**Comment by SmallJoker** [comment]
Fixes #8037 too. I suspected it might change the situation there a bit but surprisingly the selection and collision boxes now work fine. Testing mod in the issue.

File: src/client/content_cao.cpp [hunk 2]
```diff
@@ -576,11 +580,15 @@ void GenericCAO::addToScene(ITextureSource *tsrc)
 	video::E_MATERIAL_TYPE material_type = (m_prop.use_texture_alpha) ?
 		video::EMT_TRANSPARENT_ALPHA_CHANNEL : video::EMT_TRANSPARENT_ALPHA_CHANNEL_REF;
 
-	if (m_prop.visual == "sprite") {
-		infostream<<"GenericCAO::addToScene(): single_sprite"<<std::endl;
+	auto getMatrixNode = [this] {
```
Comment (sfan5) [inline src/client/content_cao.cpp]: `grabMatrixNode` would be a better name IMO

**Comment by hecktest** [comment]
Can't build this; 'getMatrixNode was not declared in this scope'

**Comment by SmallJoker** [comment]
You're too late.

**Comment by hecktest** [comment]
dang it

**Comment by hecktest** [comment]
good
It's a success, but it made #9139 worse. (while providing some clues to its nature)
