### PR TITLE
Fix float argument check in minetest.set_timeofday()

### LINKED ISSUE #1794: Many Lua C functions are missing type checks
Instead of throwing an error and returning to main menu, some function calls crash Minetest entirely (lack of proper error handling).

``` Lua
-- Gray screen
minetest.add_entity()
minetest.add_item()
minetest.add_node()
minetest.add_node_level()
minetest.add_particle(1,2)
minetest.add_particlespawner(1,2)
minetest.check_single_for_falling()
minetest.create_schematic('',{},{},'')
minetest.delete_area()
minetest.dig_node()
-- cut here - gave up checking all of them
minetest.show_formspec(name, 'test', 'list[inventory_location;list_name;0,0;8,8;]')
-- cut here as well

error()
```

EDIT2: List might be outdated. Please modify/notify.

### PR DESCRIPTION
**Pull request by Zughy**
- Goal of the PR
Avoid an engine assumption crash
- How does the PR work?
I've changed the check, now it doesn't make the whole client crash anymore (only the game)
- Does it resolve any reported issue?
closes #1794 (I've tried all the listed functions, they crash as intended except `set_timeofday`)

I guess there are other functions that might not work as intended with weird values, but testing them all is a suicide. I suggest to solve them on the go, avoiding keeping an issue open - especially because the listed ones are all solved

## To do

This PR is Ready for Review.

## How to test
Make it crash with
```
minetest.register_on_joinplayer(function(player, last_login)
    minetest.set_timeofday(-1)
end)
```

### CODE REVIEW

**Comment by HybridDog** [comment]
I've tested it with the `/time nan` chatcommand.

File: src/script/lua_api/l_env.cpp [hunk 1]
```diff
@@ -751,7 +751,8 @@ int ModApiEnvMod::l_set_timeofday(lua_State *L)
 
 	// Do it
 	float timeofday_f = readParam<float>(L, 1);
-	sanity_check(timeofday_f >= 0.0 && timeofday_f <= 1.0);
+	luaL_argcheck(L, timeofday_f >= 0.0 && timeofday_f <= 1.0, 1,
```
Comment (paramat) [inline src/script/lua_api/l_env.cpp:754]: Although many areas of code do not do this yet, float literals should be stated with an 'f'. So:
0.0f
1.0f

File: src/script/lua_api/l_env.cpp [hunk 2]
```diff
@@ -751,7 +751,8 @@ int ModApiEnvMod::l_set_timeofday(lua_State *L)
...
+		"value must be between 0 and 1");
 	int timeofday_mh = (int)(timeofday_f * 24000.0);
```
Comment (paramat) [inline src/script/lua_api/l_env.cpp:756]: 24000.0f

**Review by SmallJoker — APPROVED** [review]

**Comment by paramat** [comment]
I did not test but code looks fine :+1:
