### PR TITLE
Restore proportional minimap scaling

### LINKED ISSUE #15021: Android minimap is oversized
### Minetest version

```true
Minetest 5.9.0
```

### Irrlicht device

Android

### Operating system and version

Android

### CPU model

_No response_

### GPU model

_No response_

### Active renderer

_No response_

### Summary

image

### Steps to reproduce

Unsure

### PR DESCRIPTION
**Pull request by grorp**
Restores minimap scaling as it was before #14071. Fixes #15021.

## To do

This PR is a Ready for Review.

## How to test

Look at the minimap with different window sizes, see that it scales.

### CODE REVIEW

File: src/client/hud.cpp [hunk 1]
```diff
@@ -545,14 +545,21 @@ void Hud::drawLuaElements(const v3s16 &camera_offset)
...
 					break;
 				// Draw a minimap of size "size"
 				v2s32 dstsize(e->size.X * m_scale_factor,
 				              e->size.Y * m_scale_factor);
-				// (no percent size as minimap would likely be anamorphosed)
+
+				// Only one percentage is supported to avoid distortion.
+				if (e->size.X < 0)
+					dstsize.X = dstsize.Y = m_screensize.X * (e->size.X * -0.01);
+				 else if (e->size.Y < 0)
```
Comment (appgurueu) [inline src/client/hud.cpp:557]:
```suggestion
				else if (e->size.Y < 0)
```

File: src/client/hud.cpp [hunk 2]
```diff
@@ -545,14 +545,21 @@ void Hud::drawLuaElements(const v3s16 &camera_offset)
...
+					dstsize.X = dstsize.Y = m_screensize.Y * (e->size.Y * -0.01);
+
+				if (dstsize.X <= 0 || dstsize.Y <= 0)
```
Comment (appgurueu) [inline src/client/hud.cpp:560]: Can this still happen? It seems me that either we already have `size.X > 0 && size.Y > 0` => doesn't happen (we get the `dstsize` as the product of `size` with something positive then), `size.X < 0 || size.Y < 0` => above code runs, sets it to something positive (because screensize is multiplied with something positive).

**Review by appgurueu — COMMENTED** [review]
Tested, works as expected in singleplayer.

What about a newer server and older (5.9.0) client however? Won't the minimap just be hidden entirely there (since one of `size.X` and `size.Y` is `< 0`)? This probably needs some compatibility code when the HUD elements are sent.

Idea: One of `x` and `y` is unused. That should be a fixed pixel size. Older clients could be sent `x = y = fixed pixel size`.

File: src/client/hud.cpp (hunk 2 above)
Comment (grorp) [reply src/client/hud.cpp:560]: if `size.X == 0 || size.Y == 0`

**Comment by grorp** [comment]
> What about a newer server and older (5.9.0) client however? Won't the minimap just be hidden entirely there (since one of `size.X` and `size.Y` is `< 0`)? This probably needs some compatibility code when the HUD elements are sent.

Indeed.

> Idea: One of `x` and `y` is unused. That should be a fixed pixel size. Older clients could be sent `x = y = fixed pixel size`.

There's a much bigger problem than "how do we encode this": We can't distinguish 5.9.0 and 5.9.1 clients since they have the same protocol version. We need either

1. a protocol version bump for 5.9.1 or
2. a completely different approach where the correct pixel size is determined on the server using `get_player_window_information`

File: src/client/hud.cpp (hunk 2 above)
Comment (appgurueu) [reply src/client/hud.cpp:560]: right, probably replace it with that, would be a bit clearer imo

**Comment by appgurueu** [comment]
> a protocol version bump for 5.9.1 or

Is there a problem with this? A bonus would be that it would help modders distinguish 5.9.0 and 5.9.1, which may be relevant for mod-side workaround of client bugs.

**Comment by grorp** [comment]
> Is there a problem with this?

No idea. Did the protocol version bump now, let's see if anyone complains.

**Review by appgurueu — APPROVED** [review]
- [x] PR server, PR client: Minimap uses proportional size
- [x] PR server, 5.9.0 client: Minimap uses fixed size
- [x] 5.9.0 server, PR client: Minimap uses fixed size

Thanks for addressing this.

(By the way, I'm not sure what the convention surrounding this is, but *perhaps* the protocol version bump should be a separate first commit, making this PR nosquash)

File: src/network/networkprotocol.h [hunk 3]
```diff
@@ -224,9 +224,12 @@ with this program; if not, write to the Free Software Foundation, Inc.,
 		Add TOCLIENT_MOVE_PLAYER_REL
 		Move default minimap from client-side C++ to server-side builtin Lua
 		[scheduled bump for 5.9.0]
+	PROTOCOL VERSION 45:
+		Minimap HUD element supports negative size values as percentages
+		[bump for 5.9.1]
```
Comment (sfan5) [inline src/network/networkprotocol.h:229]: patch releases cannot bump the protocol version

Comment (appgurueu) [reply src/network/networkprotocol.h:229]: why not? a patch can very well require a network protocol extension (as is the case here). detecting a patch release and selectively applying workarounds is also something mods will be interested in.

anyways, going forward under the assumption that we don't bump for 5.9.1, it'd only really be viable to delay this to 5.10.0. which shouldn't be too bad given that we plan to release 5.10.0 in a few months.

Comment (sfan5) [reply src/network/networkprotocol.h:229]: there is a scheduled bump for every minor release
so if we bump for 5.9.1 we need to somehow separately bump 5.10.0 by *two* versions.
not impossible, just a mess and we've never done this.

> it'd only really be viable to delay this to 5.10.0

that works.
other options are stupid workaround like "if it's the first minimap element and the size is 256x256 make it 25% instead"

Comment (grorp) [reply src/network/networkprotocol.h:229]: what problem would bumping the protocol version in 5.9.1 cause? early 5.10.0-dev and 5.9.1 would share the same protocol version, but that doesn't seem problematic.

Comment (sfan5) [reply src/network/networkprotocol.h:229]: I can't think of a concrete problem but this inconsistency doesn't feel good to me.

**Comment by Zughy** [comment]
@grorp rebase needed

**Comment by appgurueu** [comment]
What's the problem with squashing this? I see that you rebased this by "reordering" commits by reverting and reapplying another commit, but I see no reason why we can't squash that such that only the actual changes remain and this back-and-forth doesn't appear in our commit history.

**Comment by grorp** [comment]
> What's the problem with squashing this? I see that you rebased this by "reordering" commits by reverting and reapplying another commit, but I see no reason why we can't squash that such that only the actual changes remain and this back-and-forth doesn't appear in our commit history.

Unfortunately #14321 was merged, which makes things more complicated. There are two possible possible approaches for keeping consistency here:

1. Revert the #14321, do the fix & bump protover, re-apply #14321  
    -> the fix can simply be cherry-picked into 5.9.1 with the correct protover bump happening for 5.9.1 automatically

2. Just do the fix without bumping protover  
    -> the fix can be cherry-picked into 5.9.1, but a manual protover bump to 45 must happen for 5.9.1

So you'd prefer the second approach?

**Comment by cx384** [comment]
The second one makes more sense to me.

**Comment by appgurueu** [comment]
Is cherry-picking https://github.com/minetest/minetest/pull/15022/commits/ad1d7e4b2aabb83b56563a7efa13da3b549bd435) for 5.9.1, but squashing this PR for 5.10.0 (master) not an option?

**Comment by grorp** [comment]
> Is cherry-picking https://github.com/minetest/minetest/pull/15022/commits/ad1d7e4b2aabb83b56563a7efa13da3b549bd435 for 5.9.1, but squashing this PR for 5.10.0 (master) not an option?

ad1d7e4b2aabb83b56563a7efa13da3b549bd435 shouldn't be in 5.9.1, I suspect you meant a different commit?

**Comment by appgurueu** [comment]
> > Is cherry-picking [ad1d7e4](https://github.com/minetest/minetest/commit/ad1d7e4b2aabb83b56563a7efa13da3b549bd435) for 5.9.1, but squashing this PR for 5.10.0 (master) not an option?
> 
> [ad1d7e4](https://github.com/minetest/minetest/commit/ad1d7e4b2aabb83b56563a7efa13da3b549bd435) shouldn't be in 5.9.1, I suspect you meant a different commit?

Sorry, I meant https://github.com/minetest/minetest/pull/15022/commits/d38967bf61532d876dbd29652cfba5100fbcca65, the "middle" one (which depends on the minimap one not having been merged).

**Comment by grorp** [comment]
Yeah, could do that too. It's effectively the same as manually doing the bump for 5.9.1 when cherry-picking.
