### PR TITLE
Restore pass-through of direction keys

### LINKED ISSUE #11775: New handling of direction key bits is not fully backwards-compatible
##### Minetest version

```
1d69a23ba48d99b051dcf2a6be225edd7c644c7b and ongoing
```

##### OS / Hardware
Desktop, not sure if and how this affects the android version. 

##### Summary

Commit https://github.com/minetest/minetest/commit/1d69a23ba48d99b051dcf2a6be225edd7c644c7b deprecates the key direction bits but retains a way to still read them for "full" backwards compatibility. 
However, the `keypress_bits` are computed from the movement direction now, meaning that contradicting keypresses like forward+backward and left+right cancel each other out, in movement as well as `keypress_bits`, which did not happen for latter before and breaks the "full backwards-compatible" promise.
This may be a rather obscure corner case, but it is used by the Draconis mod for example (left+right switches view).

##### Steps to reproduce

In your debugger of choice, add a logpoint to `keypress_bits` at the end of `Game::updatePlayerControl` in `src/client/game.cpp` and press random keys in-game. Observe that cancelling directions produce a `0` starting from mentioned commit.

### PR DESCRIPTION
**Pull request by sfan5**
fixes #11775

also moves relevant code into the `PlayerControl` class and gets rid of separate storage of `keyPressed`.

## To do

This PR is Ready for Review.

## How to test

1.
```lua
local h = {}; local t = {}
minetest.register_on_joinplayer(function(p)
	local n = p:get_player_name(); h[n] = p:hud_add({
		hud_elem_type = "text",
		position = {x = 0.22, y = 0.22},
		scale = {x = 2, y = 2},
		number = 0xFFFFFF,
		style = 4,
	}); t[n] = ""
end)
minetest.register_on_leaveplayer(function(p)
	local n = p:get_player_name(); h[n] = nil; t[n] = nil
end)
local function z(c)
	local function k(s) return c[s] and s:upper() or s end
	return ("      "..k("up").."          "..k("dig").." "..k("place").."\n"..
	k("left").." "..k("down").." "..k("right").."  "..k("jump").." "..k("sneak").."\n"..
	"                 "..k("aux1").."  "..k("zoom"))
end
minetest.register_globalstep(function(_)
	for _, p in ipairs(minetest.get_connected_players()) do
		local n = p:get_player_name(); local i = h[n]
		if i then
			local s = z(p:get_player_control())
			if s ~= t[n] then p:hud_change(i, "text", s); t[n] = s end
		end
	end
end)
```
2. Press left+right keys at the same time, or up+down
3. Confirm that it shows up in the HUD

### CODE REVIEW

File: src/player.cpp [hunk 1]
```diff
@@ -159,6 +160,61 @@ void Player::clearHud()
...
+			keypress_bits |= (u32)1 << 3; // Right
+	}
+
+	return keypress_bits;
+}
+
+void PlayerControl::unpackKeysPressed(u32 keypress_bits)
+{
+	// It would be possible to unpack the direction keys from the bits
+	// but this is handeled differently.
```
Comment (SmallJoker) [inline src/player.cpp:209]: Too vague description. Why can't everything be updated in the same function for consistency?

File: src/player.cpp [hunk 2]
```diff
@@ -159,6 +160,61 @@ void Player::clearHud()
...
+		// rotate entire coordinate system by 90 degree
+		abs_d = movement_direction + M_PI_2;
+		if (abs_d >= M_PI)
+			abs_d -= 2 * M_PI;
+		abs_d = abs(abs_d);
+		// (value now indicates left / right)
+		if (abs_d < 3.0f / 8.0f * M_PI)
+			keypress_bits |= (u32)1 << 2; // Left
+		if (abs_d > 5.0f / 8.0f * M_PI)
+			keypress_bits |= (u32)1 << 3; // Right
```
Comment (SmallJoker) [inline src/player.cpp:200]: a bit late, but is this accurate? What matters is the angle between `yaw` and `movement_direction` to determine left/right.

Comment (sfan5) [reply src/player.cpp:200]: :shrug: Not my code

File: src/player.cpp (hunk 1 above)
Comment (sfan5) [reply src/player.cpp:209]: <i>It just is</i>.
I'll look at dropping `keyPressed` entirely next time I look at this PR.

File: src/player.cpp (hunk 2 above)
Comment (SmallJoker) [reply src/player.cpp:200]: Acceptable. :+1: fixes can be done later by someone who can test this code.

**Review by SmallJoker — APPROVED** [review]
Works on my machine. Thank you very much for the new changes!
