### PR TITLE
Work around driver bug causing shaders to not work

### LINKED ISSUE #10844: Shader error message: failed to retrieve uniform information
##### Minetest version
```
https://minetest.kitsunemimi.pw/builds/win64/minetest-5.4.0-6d7067f-win64.7z
```

##### OS / Hardware
Operating system:windows 7
CPU:i7-3610qm

GPU model:intel hd 4000
OpenGL version:4.0.0

##### Summary
image

##### Steps to reproduce

Download, start minetest (link above) and join a server

### PR DESCRIPTION
**Pull request by appgurueu**
Fixes #10844.

Tested by someone affected, fixes the bug by falling back to `glGetActiveUniformName`. The simpler fallback also works.

### CODE REVIEW

**Comment by TubberPupper** [comment]
Yay hopefully I can finally play Luanti with shaders without crashing instantaneously :D

File: irr/src/COpenGLSLMaterialRenderer.cpp [hunk 1]
```diff
@@ -401,18 +401,32 @@ bool COpenGLSLMaterialRenderer::linkProgram()
 #endif
 
 		if (maxlen == 0) {
-			os::Printer::log("GLSL (> 2.x): failed to retrieve uniform information", ELL_ERROR);
-			return false;
+			// Work around driver bug: There are > 0 uniforms,
+			// yet the driver reports a max. uniform name length of 0.
+			if (GL.GetActiveUniformName) {
```
Comment (sfan5) [inline irr/src/COpenGLSLMaterialRenderer.cpp:406]: AFAIK this is not standards compliant, function pointers can be any junk if version or extension requirements are not met.

File: irr/src/COpenGLSLMaterialRenderer.cpp [hunk 2]
```diff
@@ -401,18 +401,32 @@ bool COpenGLSLMaterialRenderer::linkProgram()
 #endif
 
 		if (maxlen == 0) {
-			os::Printer::log("GLSL (> 2.x): failed to retrieve uniform information", ELL_ERROR);
-			return false;
+			// Work around driver bug: There are > 0 uniforms,
+			// yet the driver reports a max. uniform name length of 0.
```
Comment (sfan5) [inline irr/src/COpenGLSLMaterialRenderer.cpp:405]:
```suggestion
			// Intel driver bug that seems to primarily happen on Win 8.1 or older:
			// There are >0 uniforms yet the driver reports a max name length of 0.
```

**Comment by sfan5** [comment]
Something we should check eventually is if the OpenGL 3 driver is also affected.

File: irr/src/COpenGLSLMaterialRenderer.cpp (hunk 1 above)
Comment (appgurueu) [reply irr/src/COpenGLSLMaterialRenderer.cpp]: Reverted to the simpler workaround, this is too much of a hassle.

**Review by sfan5 — APPROVED** [review]
I can't test this, but should work.

**Comment by appgurueu** [comment]
> untested, but should work.

Note that I've had @TubberPupper test this successfully. (Both the simple version and the more advanced one.)

**Review by grorp — APPROVED** [review]
looks good
