### PR TITLE
Fix detach inventory serialisation

### LINKED ISSUE #8325: Large inventory lists are not sent correctly
##### Issue type
 - Bug report

##### Minetest version
```
Minetest 5.0.0 (Linux)
```

##### Summary
originally reported here https://forum.minetest.net/viewtopic.php?f=6&t=22285
Inventory lists with <b>lots</b> of items are not sent correctly, causing a serialization error on the client.
<pre>
2019-03-06 00:39:15: ERROR[Main]: A serialization error occurred:
2019-03-06 00:39:15: ERROR[Main]: Malformatted inventory list. list=main, read 197 of 3424 ItemStacks.
2019-03-06 00:39:15: ERROR[Main]: The server is probably  running a different version of Minetest.
</pre>

##### Steps to reproduce
register lots of items and enable the creative inventory
```lua
for i = 1, 3000 do
	minetest.register_node(minetest.get_current_modname() .. ":node" .. tostring(i), {
		description = "Grassy Block",
		tiles = {"default_grass.png"},
		groups = {crumbly = 3},
		drop = 'default:dirt',
	})
end
```

##### Debugging effort
checking Wireshark, the inventory list size is correct but the the inventory is unexpectedly cut off
grafik

using some debug code placed in `Server::sendDetachedInventory`, the sizes of sent inventory can be watched:
<pre>
2019-03-06 00:39:15: ACTION[Server]: singleplayer joins game. List of players: singleplayer
2019-03-06 00:39:15: ACTION[Server]: serialized inv sz = 13
2019-03-06 00:39:15: ACTION[Server]: serialized inv sz = 20597
2019-03-06 00:39:15: ACTION[Server]: serialized inv sz = 70647
[ error message from above follows ]
</pre>
suspiciously, the inventory that failed is above 65535 bytes in size

### PR DESCRIPTION
**Pull request by rubenwardy**
Fixes #8325

Please read the summary: https://github.com/minetest/minetest/pull/8331#issuecomment-470288892

Testing:

* Small inventories work
   - [x] 5.0.0 client, 5.0.1 server
   - [x] 5.0.1 client, 5.0.0 server
* Big inventories (>65536)
   - [x] 5.0.1 will work on 5.0.1 server
   - [x] 5.0.0 will crash on either server
   - [x] 5.0.1 will crash on 5.0.0 server (maybe?)

### CODE REVIEW

File: src/network/clientpackethandler.cpp [hunk 1]
```diff
@@ -895,8 +895,10 @@ void Client::handleCommand_DetachedInventory(NetworkPacket* pkt)
 		inv = inv_it->second;
 	}
 
-	std::string contents;
-	*pkt >> contents;
+	u16 ignore;
+	*pkt >> ignore; // HACK: ignore length to support 5.0.0 clients
```
Comment (sfan5) [inline src/network/clientpackethandler.cpp]: I'd put `// this used to be the length of the following string, ignore it` here

File: src/server.cpp [hunk 2]
```diff
@@ -2576,7 +2576,10 @@ void Server::sendDetachedInventory(const std::string &name, session_t peer_id)
 		// Serialization & NetworkPacket isn't a love story
 		std::ostringstream os(std::ios_base::binary);
 		inv_it->second->serialize(os);
-		pkt << os.str();
+
+		std::string os_str = os.str();
+		pkt << (u16)os_str.size(); // HACK: to keep compatibility with 5.0.0 clients
```
Comment (sfan5) [inline src/server.cpp]: should probably be a C++ style cast

**Comment by rubenwardy** [comment]
I've now tested this manually with the creative inventory, with both small and large inventories and different client version pairs

**Comment by ShadMOrdre** [comment]
How can I help?  I can download and compile source on LUbuntu 17.10.

File: src/network/clientpackethandler.cpp [hunk 3]
```diff
@@ -895,8 +895,10 @@ void Client::handleCommand_DetachedInventory(NetworkPacket* pkt)
 		inv = inv_it->second;
 	}
 
-	std::string contents;
-	*pkt >> contents;
+	u16 ignore;
```
Comment (sofar) [inline src/network/clientpackethandler.cpp]: If you do something like this in there, put a "poison" value in there, like 0xdead in this case would work well.

Comment (rubenwardy) [reply src/network/clientpackethandler.cpp]: this would break compatibility with 5.0.0

**Comment by rubenwardy** [comment]
Here's a quick summary.

In 0.4.x, this packet is sent in a form like this:

    headers STRING

In 5.0.0, this packet is sent in a form like this:

    headers LENGTH STRING

The LENGTH part is an unsigned 16 bit value, which limits the string to 65536 characters. This patch essentially lets 5.0.1+ act like 0.4.x does, and not limit the string, whilst keeping the LENGTH part to allow compatibility with 5.0.0.

So, LENGTH is ignored by 5.0.1+ but read by 5.0.0.

As listed in the OP, I've tested this on different combinations of 5.0.0 and 5.0.1 and made sure that it crashes where it should

**Comment by ShadMOrdre** [comment]
@rubenwardy,  Is this a patch, or this going to be the fix going forward?

Does this just remove the length check, or does this increase the string length to 32bit?  I read the irc discussion, but it seems that network protocol compatibility is the big issue.  Forgive me my noob status here, but just want a better understanding of what the plan is for the future, since I plan on releasing a Game sometime soon, that is rather inventory heavy.

**Comment by rubenwardy** [comment]
> Is this a patch, or this going to be the fix going forward?

If this is approved, it will be the fix going forward

> Does this just remove the length check, or does this increase the string length to 32bit?

This removes the length check, as there's no need for it. Changing the length to 32bit would break compatibility

> but it seems that network protocol compatibility is the big issue

It is to me

**Comment by ShadMOrdre** [comment]
Thank you for your response.  I have been playing with this for most of the day so far, and this does seem to solve my issue.

Thanks for your contributions!
