### PR TITLE
Fix after soft node overlays

### LINKED ISSUE #5631: Special drawtypes appear cyan
After updating to latest Git master and recompiling the engine, I noticed a strange issue is now occurring: Drawtypes other than the standard block seem to be colorized in a green / cyan color. I haven't yet tested if this is caused by shaders, and which in particular if so.

As a reminder, I run Minetest on Linux and use the free video drivers (Mesa 17.0.3). My video card is a Radeon R7 370, GCN 1.0 / RadeonSI.

screenshot_20170421_171931

### LINKED ISSUE #5632: Crash when exiting the world via menu
Start the world, type Esc, select "Exit to menu" or "Exit the game", you will have a game crash. Happens on commit 1ffb180, de5ecc9 (yesterday) had no such problem for me.

Debug via gdb mentions this:
```
Program received signal SIGSEGV, Segmentation fault.
0x00000000007470ab in CItemDefManager::~CItemDefManager (this=0xa862b90, __in_chrg=<optimized out>)
    at /media/sf_Exchange/minetest/build/minetest/src/itemdef.cpp:264
264	/media/sf_Exchange/minetest/build/minetest/src/itemdef.cpp: No such file or directory.
```

Backtrace (i did one short and one full):
```
Starting program: d:\Programs\_Dev\TDM-GCC-64\gdb64\bin\mt\bin\minetest.exe 
[New Thread 5008.0x134c]
[New Thread 5008.0x36c]
[New Thread 5008.0x1350]
[New Thread 5008.0xc84]
[New Thread 5008.0x4c0]
[New Thread 5008.0x10b8]
[New Thread 5008.0x4bc]
[New Thread 5008.0x129c]
warning: Loaded texture: d:/Programs/_Dev/TDM-GCC-64/gdb64/bin/mt/textures/base/pack/menu_header.png

[New Thread 5008.0x13b4]
[New Thread 5008.0xaa8]
warning: Loaded texture: d:/Programs/_Dev/TDM-GCC-64/gdb64/bin/mt/textures/base/pack/blank.png

warning: Loaded texture: d:/Programs/_Dev/TDM-GCC-64/gdb64/bin/mt/textures/base/pack/server_flags_favorite.png

warning: Loaded texture: d:/Programs/_Dev/TDM-GCC-64/gdb64/bin/mt/textures/base/pack/server_ping_4.png

warning: Loaded texture: d:/Programs/_Dev/TDM-GCC-64/gdb64/bin/mt/textures/base/pack/server_ping_3.png

warning: Loaded texture: d:/Programs/_Dev/TDM-GCC-64/gdb64/bin/mt/textures/base/pack/server_ping_2.png

warning: Loaded texture: d:/Programs/_Dev/TDM-GCC-64/gdb64/bin/mt/textures/base/pack/server_ping_1.png

warning: Loaded texture: d:/Programs/_Dev/TDM-GCC-64/gdb64/bin/mt/textures/base/pack/server_flags_creative.png

warning: Loaded texture: d:/Programs/_Dev/TDM-GCC-64/gdb64/bin/mt/textures/base/pack/server_flags_damage.png

warning: Loaded texture: d:/Programs/_Dev/TDM-GCC-64/gdb64/bin/mt/textures/base/pack/server_flags_pvp.png

warning: Loaded texture: d:/Programs/_Dev/TDM-GCC-64/gdb64/bin/mt/games/minetest_game/menu/header.png

warning: Loaded texture: d:/Programs/_Dev/TDM-GCC-64/gdb64/bin/mt/games/minetest_game/menu/icon.png

warning: Loaded texture: d:/Programs/_Dev/TDM-GCC-64/gdb64/bin/mt/games/minimal/menu/icon.png

[Thread 5008.0xc84 exited with code 0]
[Thread 5008.0x10b8 exited with code 0]
[Thread 5008.0x129c exited with code 0]
[Thread 5008.0x4c0 exited with code 0]
[Thread 5008.0x4bc exited with code 0]
[New Thread 5008.0xba0]
[New Thread 5008.0x69c]
[New Thread 5008.0x1164]
[New Thread 5008.0x914]
[New Thread 5008.0xd34]
[New Thread 5008.0x114]
[New Thread 5008.0x958]
[New Thread 5008.0x13ac]
[New Thread 5008.0xac8]
[New Thread 5008.0x1398]
[New Thread 5008.0xbc8]
[New Thread 5008.0xdf0]
[Thread 5008.0xac8 exited with code 0]
[Thread 5008.0x958 exited with code 0]
[Thread 5008.0x114 exited with code 0]
[Thread 5008.0xd34 exited with code 0]
[Thread 5008.0xba0 exited with code 0]
[Thread 5008.0x914 exited with code 0]
[Thread 5008.0x13ac exited with code 0]
[Thread 5008.0x1164 exited with code 0]
[Thread 5008.0x69c exited with code 0]

Program received signal SIGSEGV, Segmentation fault.
0x00000000007470ab in CItemDefManager::~CItemDefManager (this=0xa862b90, __in_chrg=<optimized out>)
    at /media/sf_Exchange/minetest/build/minetest/src/itemdef.cpp:264
264	/media/sf_Exchange/minetest/build/minetest/src/itemdef.cpp: No such file or directory.

Thread 22 (Thread 5008.0xdf0):
#0  0x0000000077a1d63a in ntdll!ZwWaitForWorkViaWorkerFactory () from C:\Windows\SYSTEM32\ntdll.dll
#1  0x00000000779eed15 in ntdll!RtlValidateHeap () from C:\Windows\SYSTEM32\ntdll.dll
#2  0x0000000000000000 in ?? ()
Backtrace stopped: previous frame inner to this frame (corrupt stack?)

Thread 21 (Thread 5008.0xbc8):
#0  0x0000000077a1d63a in ntdll!ZwWaitForWorkViaWorkerFactory () from C:\Windows\SYSTEM32\ntdll.dll
#1  0x00000000779eed15 in ntdll!RtlValidateHeap () from C:\Windows\SYSTEM32\ntdll.dll
#2  0x0000000000000000 in ?? ()
Backtrace stopped: previous frame inner to this frame (corrupt stack?)

Thread 20 (Thread 5008.0x1398):
#0  0x0000000077a1d63a in ntdll!ZwWaitForWorkViaWorkerFactory () from C:\Windows\SYSTEM32\ntdll.dll
#1  0x00000000779eed15 in ntdll!RtlValidateHeap () from C:\Windows\SYSTEM32\ntdll.dll
#2  0x0000000000020000 in ?? ()
Backtrace stopped: previous frame inner to this frame (corrupt stack?)

Thread 10 (Thread 5008.0xaa8):
#0  0x0000000077a1bdca in ntdll!ZwRemoveIoCompletion () from C:\Windows\SYSTEM32\ntdll.dll
#1  0x000007fefcee5711 in ?? () from C:\Windows\system32\mswsock.dll
#2  0x0000000000000000 in ?? ()
Backtrace stopped: previous frame inner to this frame (corrupt stack?)

Thread 9 (Thread 5008.0x13b4):
#0  0x0000000077a1c2ea in ntdll!ZwWaitForMultipleObjects () from C:\Windows\SYSTEM32\ntdll.dll
#1  0x00000000779ea3c7 in ntdll!TpIsTimerSet () from C:\Windows\SYSTEM32\ntdll.dll
#2  0x00000000777c59cd in KERNEL32!BaseThreadInitThunk () from C:\Windows\system32\kernel32.dll
#3  0x00000000779fa561 in ntdll!RtlUserThreadStart () from C:\Windows\SYSTEM32\ntdll.dll
#4  0x0000000000000000 in ?? ()
Backtrace stopped: previous frame inner to this frame (corrupt stack?)

Thread 3 (Thread 5008.0x1350):
#0  0x00000000778e9e4a in USER32!SfmDxSetSwapChainStats () from C:\Windows\system32\user32.dll
#1  0x00000000778e611e in USER32!GetMessageA () from C:\Windows\system32\user32.dll
#2  0x000000006b625a6a in MMDevApiMsgProc () from d:\Programs\_Dev\TDM-GCC-64\gdb64\bin\mt\bin\OpenAL32.dll
#3  0x00000000777c59cd in KERNEL32!BaseThreadInitThunk () from C:\Windows\system32\kernel32.dll
#4  0x00000000779fa561 in ntdll!RtlUserThreadStart () from C:\Windows\SYSTEM32\ntdll.dll
#5  0x0000000000000000 in ?? ()
Backtrace stopped: previous frame inner to this frame (corrupt stack?)

Thread 2 (Thread 5008.0x36c):
#0  0x0000000077a1bd7a in ntdll!ZwWaitForSingleObject () from C:\Windows\SYSTEM32\ntdll.dll
#1  0x000007fefda510ac in WaitForSingleObjectEx () from C:\Windows\system32\KernelBase.dll
#2  0x000007fef60ac018 in atigktxx!XopOpenLinkedAdapter () from C:\Windows\system32\atig6txx.dll
#3  0x000007fef60ac089 in atigktxx!XopOpenLinkedAdapter () from C:\Windows\system32\atig6txx.dll
#4  0x000007fef60abe6f in atigktxx!XopOpenLinkedAdapter () from C:\Windows\system32\atig6txx.dll
#5  0x000007fef60b6b7f in atigktxx!XopOpenLinkedAdapter () from C:\Windows\system32\atig6txx.dll
#6  0x000007fef60b6d36 in atigktxx!XopOpenLinkedAdapter () from C:\Windows\system32\atig6txx.dll
#7  0x00000000777c59cd in KERNEL32!BaseThreadInitThunk () from C:\Windows\system32\kernel32.dll
#8  0x00000000779fa561 in ntdll!RtlUserThreadStart () from C:\Windows\SYSTEM32\ntdll.dll
#9  0x0000000000000000 in ?? ()
Backtrace stopped: previous frame inner to this frame (corrupt stack?)

Thread 1 (Thread 5008.0x134c):
#0  0x00000000007470ab in CItemDefManager::~CItemDefManager (this=0xa862b90, __in_chrg=<optimized out>)
    at /media/sf_Exchange/minetest/build/minetest/src/itemdef.cpp:264
#1  0x0000000000747005 in CItemDefManager::~CItemDefManager (this=0xa862b90, __in_chrg=<optimized out>)
    at /media/sf_Exchange/minetest/build/minetest/src/itemdef.cpp:275
#2  0x000000000057499d in Game::~Game (this=0x22f1a0, __in_chrg=<optimized out>)
    at /media/sf_Exchange/minetest/build/minetest/src/game.cpp:1516
#3  0x000000000058511b in the_game (kill=0xb94330 <porting::g_killed>, random_input=false, input=0x6b0de50, device=0x6ad5a00, 
    map_dir="d:\\Programs\\_Dev\\TDM-GCC-64\\gdb64\\bin\\mt\\bin\\..\\worlds\\DamEvasion", playername="singleplayer", password="", 
    address="", port=63742, error_message="", chat_backend=..., reconnect_requested=0x22f8af, gamespec=..., 
    simple_singleplayer_mode=true) at /media/sf_Exchange/minetest/build/minetest/src/game.cpp:4540
#4  0x00000000004027ad in ClientLauncher::run (this=0x22fc50, game_params=..., cmd_args=...)
    at /media/sf_Exchange/minetest/build/minetest/src/client/clientlauncher.cpp:260
#5  0x00000000005d84c4 in main (argc=1, argv=0x4eb86b0) at /media/sf_Exchange/minetest/build/minetest/src/main.cpp:229
Undefined command: "more".  Try "help".

Thread 22 (Thread 5008.0xdf0):
#0  0x0000000077a1d63a in ntdll!ZwWaitForWorkViaWorkerFactory () from C:\Windows\SYSTEM32\ntdll.dll
No symbol table info available.
#1  0x00000000779eed15 in ntdll!RtlValidateHeap () from C:\Windows\SYSTEM32\ntdll.dll
No symbol table info available.
#2  0x0000000000000000 in ?? ()
No symbol table info available.
Backtrace stopped: previous frame inner to this frame (corrupt stack?)

Thread 21 (Thread 5008.0xbc8):
#0  0x0000000077a1d63a in ntdll!ZwWaitForWorkViaWorkerFactory () from C:\Windows\SYSTEM32\ntdll.dll
No symbol table info available.
#1  0x00000000779eed15 in ntdll!RtlValidateHeap () from C:\Windows\SYSTEM32\ntdll.dll
No symbol table info available.
#2  0x0000000000000000 in ?? ()
No symbol table info available.
Backtrace stopped: previous frame inner to this frame (corrupt stack?)

Thread 20 (Thread 5008.0x1398):
#0  0x0000000077a1d63a in ntdll!ZwWaitForWorkViaWorkerFactory () from C:\Windows\SYSTEM32\ntdll.dll
No symbol table info available.
#1  0x00000000779eed15 in ntdll!RtlValidateHeap () from C:\Windows\SYSTEM32\ntdll.dll
No symbol table info available.
#2  0x0000000000020000 in ?? ()
No symbol table info available.
Backtrace stopped: previous frame inner to this frame (corrupt stack?)

Thread 10 (Thread 5008.0xaa8):
#0  0x0000000077a1bdca in ntdll!ZwRemoveIoCompletion () from C:\Windows\SYSTEM32\ntdll.dll
No symbol table info available.
#1  0x000007fefcee5711 in ?? () from C:\Windows\system32\mswsock.dll
No symbol table info available.
#2  0x0000000000000000 in ?? ()
No symbol table info available.
Backtrace stopped: previous frame inner to this frame (corrupt stack?)

Thread 9 (Thread 5008.0x13b4):
#0  0x0000000077a1c2ea in ntdll!ZwWaitForMultipleObjects () from C:\Windows\SYSTEM32\ntdll.dll
No symbol table info available.
#1  0x00000000779ea3c7 in ntdll!TpIsTimerSet () from C:\Windows\SYSTEM32\ntdll.dll
No symbol table info available.
#2  0x00000000777c59cd in KERNEL32!BaseThreadInitThunk () from C:\Windows\system32\kernel32.dll
No symbol table info available.
#3  0x00000000779fa561 in ntdll!RtlUserThreadStart () from C:\Windows\SYSTEM32\ntdll.dll
No symbol table info available.
#4  0x0000000000000000 in ?? ()
No symbol table info available.
Backtrace stopped: previous frame inner to this frame (corrupt stack?)

Thread 3 (Thread 5008.0x1350):
#0  0x00000000778e9e4a in USER32!SfmDxSetSwapChainStats () from C:\Windows\system32\user32.dll
No symbol table info available.
#1  0x00000000778e611e in USER32!GetMessageA () from C:\Windows\system32\user32.dll
No symbol table info available.
#2  0x000000006b625a6a in MMDevApiMsgProc () from d:\Programs\_Dev\TDM-GCC-64\gdb64\bin\mt\bin\OpenAL32.dll
No symbol table info available.
#3  0x00000000777c59cd in KERNEL32!BaseThreadInitThunk () from C:\Windows\system32\kernel32.dll
No symbol table info available.
#4  0x00000000779fa561 in ntdll!RtlUserThreadStart () from C:\Windows\SYSTEM32\ntdll.dll
No symbol table info available.
#5  0x0000000000000000 in ?? ()
No symbol table info available.
Backtrace stopped: previous frame inner to this frame (corrupt stack?)

Thread 2 (Thread 5008.0x36c):
#0  0x0000000077a1bd7a in ntdll!ZwWaitForSingleObject () from C:\Windows\SYSTEM32\ntdll.dll
No symbol table info available.
#1  0x000007fefda510ac in WaitForSingleObjectEx () from C:\Windows\system32\KernelBase.dll
No symbol table info available.
#2  0x000007fef60ac018 in atigktxx!XopOpenLinkedAdapter () from C:\Windows\system32\atig6txx.dll
No symbol table info available.
#3  0x000007fef60ac089 in atigktxx!XopOpenLinkedAdapter () from C:\Windows\system32\atig6txx.dll
No symbol table info available.
#4  0x000007fef60abe6f in atigktxx!XopOpenLinkedAdapter () from C:\Windows\system32\atig6txx.dll
No symbol table info available.
#5  0x000007fef60b6b7f in atigktxx!XopOpenLinkedAdapter () from C:\Windows\system32\atig6txx.dll
No symbol table info available.
#6  0x000007fef60b6d36 in atigktxx!XopOpenLinkedAdapter () from C:\Windows\system32\atig6txx.dll
No symbol table info available.
#7  0x00000000777c59cd in KERNEL32!BaseThreadInitThunk () from C:\Windows\system32\kernel32.dll
No symbol table info available.
#8  0x00000000779fa561 in ntdll!RtlUserThreadStart () from C:\Windows\SYSTEM32\ntdll.dll
No symbol table info available.
#9  0x0000000000000000 in ?? ()
No symbol table info available.
Backtrace stopped: previous frame inner to this frame (corrupt stack?)

Thread 1 (Thread 5008.0x134c):
#0  0x00000000007470ab in CItemDefManager::~CItemDefManager (this=0xa862b90, __in_chrg=<optimized out>)
    at /media/sf_Exchange/minetest/build/minetest/src/itemdef.cpp:264
        cc = 0x11e11800
        i = 
        values = std::vector of length 9, capacity 16 = {0x11e11800, 0x11e56f20, 0x11e53cf0, 0x120534d0, 0x120523d0, 0x11e85720, 
          0x11e16f40, 0x11e63900, 0xa7c1e60}
#1  0x0000000000747005 in CItemDefManager::~CItemDefManager (this=0xa862b90, __in_chrg=<optimized out>)
    at /media/sf_Exchange/minetest/build/minetest/src/itemdef.cpp:275
No locals.
#2  0x000000000057499d in Game::~Game (this=0x22f1a0, __in_chrg=<optimized out>)
    at /media/sf_Exchange/minetest/build/minetest/src/game.cpp:1516
No locals.
#3  0x000000000058511b in the_game (kill=0xb94330 <porting::g_killed>, random_input=false, input=0x6b0de50, device=0x6ad5a00, 
    map_dir="d:\\Programs\\_Dev\\TDM-GCC-64\\gdb64\\bin\\mt\\bin\\..\\worlds\\DamEvasion", playername="singleplayer", password="", 
    address="", port=63742, error_message="", chat_backend=..., reconnect_requested=0x22f8af, gamespec=..., 
    simple_singleplayer_mode=true) at /media/sf_Exchange/minetest/build/minetest/src/game.cpp:4540
        game = {input = 0x6b0de50, client = 0xd845010, server = 0xa75d450, texture_src = 0xa701700, shader_src = 0xd938de0, 
          itemdef_manager = 0xa862b90, nodedef_manager = 0xd978d20, soundfetcher = {<OnDemandSoundFetcher> = {
              _vptr.OnDemandSoundFetcher = 0xa74290 <vtable for GameOnDemandSoundFetcher+16>}, m_fetched = std::set with 0 elements}, 
          sound = 0xd8b77d0, sound_is_dummy = false, soundmaker = 0xd8d6c40, chat_backend = 0x22f790, current_formspec = 0x0, 
          cur_formname = "", eventmgr = 0xd8b7760, quicktune = 0xd8b7590, gui_chat_console = 0x11e182f0, draw_control = 0xd695db0, 
          camera = 0x11e08630, clouds = 0x11e34a20, sky = 0x11e40fd0, local_inventory = 0x11e2a470, hud = 0x11e52de0, 
          mapper = 0xd8b8000, runData = {dig_index = 0, new_playeritem = 0, pointed_old = {type = POINTEDTHING_NOTHING, 
              node_undersurface = {X = 0, Y = 0, Z = 0}, node_abovesurface = {X = 0, Y = 0, Z = 0}, node_real_undersurface = {X = 0, 
                Y = 0, Z = 0}, intersection_point = {X = 0, Y = 0, Z = 0}, intersection_normal = {X = 0, Y = 0, Z = 0}, 
              object_id = -1}, digging = false, ldown_for_dig = false, left_punch = false, update_wielded_item_trigger = false, 
            reset_jump_timer = false, nodig_delay_timer = -2.10100007, dig_time = 0, dig_time_complete = 0, 
            repeat_rightclick_timer = 0, object_hit_delay_timer = -2.10100007, time_from_last_punch = 18.6960945, selected_object = 
    0x0, jump_timer = 0, damage_flash = 0, update_draw_list_timer = 0.119999997, statustext_time = 0, fog_range = 1600, 
            update_draw_list_last_cam_dir = {X = 0.266915441, Y = -0.537299693, Z = 0.800040722}, profiler_current_page = 0, 
            profiler_max_page = 3, time_of_day = 0.658040404, time_of_day_smooth = 0.658039093}, flags = {show_chat = true, 
            show_hud = true, show_minimap = false, force_fog_off = false, show_debug = true, show_profiler_graph = false, 
            disable_camera_update = false}, device = 0x6ad5a00, driver = 0x6ad6d20, smgr = 0x6ae7c30, 
          kill = 0xb94330 <porting::g_killed>, error_message = 0x22f8b0, reconnect_requested = 0x22f8af, skybox = 0x0, 
          random_input = false, simple_singleplayer_mode = true, crack_animation_length = 5, guitext = 0x11e4a670, 
          guitext2 = 0x11e40400, guitext_info = 0x11e405e0, guitext_status = 0x11e17dc0, guitext_chat = 0x11e17fa0, 
          guitext_profiler = 0x11e52770, infotext = L"", m_statustext = L"", keycache = {key = {{Key = irr::KEY_KEY_W, 
                Char = 87 L'W', m_name = "KEY_KEY_W"}, {Key = irr::KEY_KEY_S, Char = 83 L'S', m_name = "KEY_KEY_S"}, {
                Key = irr::KEY_KEY_A, Char = 65 L'A', m_name = "KEY_KEY_A"}, {Key = irr::KEY_KEY_D, Char = 68 L'D', 
                m_name = "KEY_KEY_D"}, {Key = irr::KEY_SPACE, Char = 0 L'\000', m_name = "KEY_SPACE"}, {Key = irr::KEY_KEY_E, 
                Char = 69 L'E', m_name = "KEY_KEY_E"}, {Key = irr::KEY_LSHIFT, Char = 0 L'\000', m_name = "KEY_LSHIFT"}, {
                Key = irr::KEY_KEY_CODES_COUNT, Char = 0 L'\000', m_name = ""}, {Key = irr::KEY_ESCAPE, Char = 0 L'\000', 
                m_name = "KEY_ESCAPE"}, {Key = irr::KEY_KEY_Q, Char = 81 L'Q', m_name = "KEY_KEY_Q"}, {Key = irr::KEY_KEY_I, 
                Char = 73 L'I', m_name = "KEY_KEY_I"}, {Key = irr::KEY_KEY_T, Char = 84 L'T', m_name = "KEY_KEY_T"}, {
                Key = irr::KEY_KEY_CODES_COUNT, Char = 47 L'/', m_name = "/"}, {Key = irr::KEY_PERIOD, Char = 46 L'.', 
                m_name = "KEY_PERIOD"}, {Key = irr::KEY_F10, Char = 0 L'\000', m_name = "KEY_F10"}, {Key = irr::KEY_F9, 
                Char = 0 L'\000', m_name = "KEY_F9"}, {Key = irr::KEY_KEY_K, Char = 75 L'K', m_name = "KEY_KEY_K"}, {
                Key = irr::KEY_KEY_J, Char = 74 L'J', m_name = "KEY_KEY_J"}, {Key = irr::KEY_KEY_H, Char = 72 L'H', 
                m_name = "KEY_KEY_H"}, {Key = irr::KEY_KEY_CODES_COUNT, Char = 0 L'\000', m_name = ""}, {Key = irr::KEY_F12, 
                Char = 0 L'\000', m_name = "KEY_F12"}, {Key = irr::KEY_F1, Char = 0 L'\000', m_name = "KEY_F1"}, {Key = irr::KEY_F2, 
                Char = 0 L'\000', m_name = "KEY_F2"}, {Key = irr::KEY_F3, Char = 0 L'\000', m_name = "KEY_F3"}, {
                Key = irr::KEY_KEY_CODES_COUNT, Char = 0 L'\000', m_name = ""}, {Key = irr::KEY_F5, Char = 0 L'\000', 
                m_name = "KEY_F5"}, {Key = irr::KEY_F6, Char = 0 L'\000', m_name = "KEY_F6"}, {Key = irr::KEY_F7, Char = 0 L'\000', 
                m_name = "KEY_F7"}, {Key = irr::KEY_PLUS, Char = 43 L'+', m_name = "KEY_PLUS"}, {Key = irr::KEY_MINUS, 
                Char = 45 L'-', m_name = "KEY_MINUS"}, {Key = irr::KEY_KEY_R, Char = 82 L'R', m_name = "KEY_KEY_R"}, {
                Key = irr::KEY_KEY_Z, Char = 90 L'Z', m_name = "KEY_KEY_Z"}, {Key = irr::KEY_END, Char = 0 L'\000', 
                m_name = "KEY_END"}, {Key = irr::KEY_HOME, Char = 0 L'\000', m_name = "KEY_HOME"}, {Key = irr::KEY_PRIOR, 
                Char = 0 L'\000', m_name = "KEY_PRIOR"}, {Key = irr::KEY_NEXT, Char = 0 L'\000', m_name = "KEY_NEXT"}, {
                Key = irr::KEY_KEY_P, Char = 80 L'P', m_name = "KEY_KEY_P"}, {Key = irr::KEY_KEY_CODES_COUNT, Char = 0 L'\000', 
                m_name = ""}, {Key = irr::KEY_KEY_CODES_COUNT, Char = 0 L'\000', m_name = ""}, {Key = irr::KEY_KEY_CODES_COUNT, 
                Char = 0 L'\000', m_name = ""}, {Key = irr::KEY_KEY_CODES_COUNT, Char = 0 L'\000', m_name = ""}}, 
            handler = 0x6b0de50}, profiler_interval = {m_accumulator = 3.67900777}, m_cache_doubletap_jump = false, 
          m_cache_enable_clouds = true, m_cache_enable_joysticks = false, m_cache_enable_particles = true, m_cache_enable_fog = true, 
          m_cache_enable_noclip = false, m_cache_enable_free_move = false, m_cache_mouse_sensitivity = 0.200000003, 
          m_cache_joystick_frustum_sensitivity = 170, m_repeat_right_click_time = 0.25, m_cache_cam_smoothing = 1, 
          m_cache_fog_start = 0.699999988, m_invert_mouse = false, m_first_loop_after_window_activation = true, 
          m_camera_offset_changed = false}
        server_address = ""
#4  0x00000000004027ad in ClientLauncher::run (this=0x22fc50, game_params=..., cmd_args=...)
    at /media/sf_Exchange/minetest/build/minetest/src/client/clientlauncher.cpp:260
        game_has_run = true
        text = 0xa6dc160 L"\140\025\203\156"
        video_driver = 0x6ad6d20
        __FUNCTION__ = "run"
        retval = true
        kill = 0xb94330 <porting::g_killed>
        camera = 0xa6da050
        chat_backend = {m_console_buffer = {m_scrollback = 500, m_unformatted = std::vector of length 1, capacity 1 = {{age = 0, 
                name = {m_string = L"", m_colors = std::vector of length 0, capacity 0, m_has_background = false, m_background = {
                    color = 0}}, text = {m_string = L"# Disconnected.", m_colors = std::vector of length 15, capacity 15 = {{
                      color = 4294967295}, {color = 4294967295}, {color = 4294967295}, {color = 4294967295}, {color = 4294967295}, {
                      color = 4294967295}, {color = 4294967295}, {color = 4294967295}, {color = 4294967295}, {color = 4294967295}, {
                      color = 4294967295}, {color = 4294967295}, {color = 4294967295}, {color = 4294967295}, {color = 4294967295}}, 
                  m_has_background = false, m_background = {color = 0}}}}, m_cols = 0, m_rows = 0, m_scroll = 0, 
            m_formatted = std::vector of length 0, capacity 0, m_empty_formatted_line = {
              fragments = std::vector of length 0, capacity 0, first = true}}, m_recent_buffer = {m_scrollback = 6, 
            m_unformatted = std::vector of length 1, capacity 1 = {{age = 0, name = {m_string = L"", 
                  m_colors = std::vector of length 0, capacity 0, m_has_background = false, m_background = {color = 0}}, text = {
                  m_string = L"# Disconnected.", m_colors = std::vector of length 15, capacity 15 = {{color = 4294967295}, {
                      color = 4294967295}, {color = 4294967295}, {color = 4294967295}, {color = 4294967295}, {color = 4294967295}, {
                      color = 4294967295}, {color = 4294967295}, {color = 4294967295}, {color = 4294967295}, {color = 4294967295}, {
                      color = 4294967295}, {color = 4294967295}, {color = 4294967295}, {color = 4294967295}}, 
                  m_has_background = false, m_background = {color = 0}}}}, m_cols = 0, m_rows = 0, m_scroll = 0, 
            m_formatted = std::vector of length 0, capacity 0, m_empty_formatted_line = {
              fragments = std::vector of length 0, capacity 0, first = true}}, m_prompt = {m_prompt = L"]", m_line = L"", 
            m_history = std::vector of length 0, capacity 0, m_history_index = 0, m_history_limit = 500, m_cols = 0, m_view = 0, 
            m_cursor = 0, m_cursor_len = 0, m_nick_completion_start = 0, m_nick_completion_end = 0}}
        error_message = ""
        reconnect_requested = false
        first_loop = false
#5  0x00000000005d84c4 in main (argc=1, argv=0x4eb86b0) at /media/sf_Exchange/minetest/build/minetest/src/main.cpp:229
        retval = 7474517
        cmd_args = {m_settings = std::map with 0 elements, m_defaults = std::map with 0 elements, 
          m_callbacks = std::map with 0 elements, m_callback_mutex = {mutex = {DebugInfo = 0x4fb7810, LockCount = -1, 
              RecursionCount = 0, OwningThread = 0x0, LockSemaphore = 0x0, SpinCount = 0}}, m_mutex = {mutex = {
              DebugInfo = 0x4fb7870, LockCount = -1, RecursionCount = 0, OwningThread = 0x0, LockSemaphore = 0x0, SpinCount = 0}}}
        cmd_args_ok = true
        __debug_stacker = {m_stack = 0x6ab0020, m_overflowed = false}
        __FUNCTION__ = "main"
        game_params = {socket_port = 30000, world_path = "d:\\Programs\\_Dev\\TDM-GCC-64\\gdb64\\bin\\mt\\bin\\..\\worlds\\world", 
          game_spec = {id = "minetest", path = "d:\\Programs\\_Dev\\TDM-GCC-64\\gdb64\\bin\\mt\\bin\\..\\games\\minetest_game", 
            gamemods_path = "d:\\Programs\\_Dev\\TDM-GCC-64\\gdb64\\bin\\mt\\bin\\..\\games\\minetest_game\\mods", 
            addon_mods_paths = std::set with 1 elements = {[0] = "d:\\Programs\\_Dev\\TDM-GCC-64\\gdb64\\bin\\mt\\bin\\..\\mods"}, 
            name = "Minetest Game", 
            menuicon_path = "d:\\Programs\\_Dev\\TDM-GCC-64\\gdb64\\bin\\mt\\bin\\..\\games\\minetest_game\\menu\\icon.png"}, 
          is_dedicated_server = false}
        launcher = {list_video_modes = false, skip_main_menu = false, use_freetype = true, random_input = false, address = "", 
          playername = "", password = "", device = 0x6ad5a00, input = 0x6b0de50, receiver = 0x6ad5960, skin = 0x6ae79c0, font = 0x0, 
          smgr = 0x6ae7c30, gamespec = {id = "minetest", 
            path = "d:\\Programs\\_Dev\\TDM-GCC-64\\gdb64\\bin\\mt\\bin\\..\\games\\minetest_game", 
            gamemods_path = "d:\\Programs\\_Dev\\TDM-GCC-64\\gdb64\\bin\\mt\\bin\\..\\games\\minetest_game\\mods", 
            addon_mods_paths = std::set with 1 elements = {[0] = "d:\\Programs\\_Dev\\TDM-GCC-64\\gdb64\\bin\\mt\\bin\\..\\mods"}, 
            name = "Minetest Game", 
            menuicon_path = "d:\\Programs\\_Dev\\TDM-GCC-64\\gdb64\\bin\\mt\\bin\\..\\games\\minetest_game\\menu\\icon.png"}, 
          worldspec = {path = "d:\\Programs\\_Dev\\TDM-GCC-64\\gdb64\\bin\\mt\\bin\\..\\worlds\\DamEvasion", name = "DamEvasion", 
            gameid = "minetest"}, simple_singleplayer_mode = true, current_playername = "singleplayer", current_password = "", 
          current_address = "", current_port = 63742}
        isServer = false
```

### PR DESCRIPTION
**Pull request by juhdanad**
This removes a segmentation fault and makes node meshes well colorized.

Fixes #5631.
Fixes #5632.

### CODE REVIEW

**Comment by MirceaKitsune** [comment]
Thanks for providing a fix so soon! Will wait for this to be in master and fix the coloring bug.

File: src/wieldmesh.cpp [hunk 1]
```diff
@@ -438,7 +438,7 @@ void getItemMesh(Client *client, const ItemStack &item, ItemMesh *result)
 		g_extrusion_mesh_cache->grab();
 	}
 
-	scene::SMesh *mesh;
+	scene::SMesh *mesh = NULL;
```
Comment (nerzhul) [inline src/wieldmesh.cpp]: non initialized variables can have a strange effect sometimes, especially pointers
