### PR TITLE
Fix HUD multiline text alignment

### LINKED ISSUE #2871: Text alignment of text HUD element is always left-justified for multi-line text
Hi! I think the way how the text HUD element is aligned is pretty weird as soon as you use multiple lines of text (with `\n`).

Here is an example for you to try:

```
player:hud_add({
    hud_elem_type = "text",
    text = "This is an example\ntext with\na\ncouple of\nlines.\n\nThis is the last line.",
    number = 0xFFFFFF,
    position = {x=0.5, y=0.5},
    offset = {x=-0,y=-256},
    direction = 3,
    alignment = {x=0,y=1},
    scale = {x=800,y=600},
})
```

Here I set `alignment.x` to `0`. This means center. _However_, my text is entirely left-justified; it seems that Minetest only moves the entire _text box_ to the center, but does not change the actual text alignment (if you use multiple lines).
Also, `alignment.x` with `1` seems to only move the text box to the right, but the text is not right-justified, but left-justified.

In other words, it is impossible to create a centered or right-justified text HUD element with multiple lines.

I think this needs to change. Changing the `alignment.x` parameter should _also_ affect the text alignment for texts of multiple lines. `alignment.x=0` means “centered text” and `alignment.x=1` should mean right-justified, `alignment.x=-1` should mean left-justified. 
`lua_api.txt` descibed the `alignment` parameter for text simply as “alignment of the text”, so I'd understand it as such.

You might think of this workaround: Simply calling `hud_add` multiple for each line. But this is a bad workaround, because it will break as soon as there is a client who does not use a standard font, a different font size or a different GUI scaling. In this case, the HUD elements would either overlap (if too big) or be too far apart (if too small).

(Version used: 0.4.12)

### PR DESCRIPTION
**Pull request by appgurueu**
Fixes #2871 after 5 years. Ready for review.

Screenshot

### CODE REVIEW

File: src/client/hud.cpp [hunk 1]
```diff
@@ -378,19 +380,23 @@ void Hud::drawLuaElements(const v3s16 &camera_offset)
...
-				else
+					textfont = font_scaled;
 #endif
+				auto wss = std::wstringstream(text);
+				std::wstring line;
+			    while (std::getline(wss, line, L'\n'))
 				{
-					textfont->draw(text.c_str(), size + pos + offset + offs, color);
+					core::dimension2d<u32> linesize = textfont->getDimension(line.c_str());
+					v2s32 line_offset((e->align.X - 1.0) * (linesize.Width / 2), 0);
```
Comment (appgurueu) [inline src/client/hud.cpp:397]: Should probably be negated so that `1` means right justified and `-1` means left justified.

**Comment by LoneWolfHT** [comment]
Could probably add a test for this to devtest

**Comment by SmallJoker** [comment]
@Wuzzy2 Does this PR work as you'd expect?

File: src/client/hud.cpp [hunk 2]
```diff
@@ -378,19 +380,23 @@ void Hud::drawLuaElements(const v3s16 &camera_offset)
...
+					textfont->draw(line.c_str(), size + pos + offset + offs + line_offset, color);
```
Comment (SmallJoker) [inline src/client/hud.cpp:398]: Why is this not handled using the `draw()` function?

https://github.com/minetest/minetest/blob/1946835ee87bdd20c586f6bb79c422da1cad4685/src/irrlicht_changes/CGUITTFont.cpp#L572-L579

Comment (appgurueu) [reply src/client/hud.cpp:398]: Because the draw function doesn't allow for right-aligned text (and hcenter / vcenter didn't seem to work).

**Comment by Wuzzy2** [comment]
Has backwards-compability been tested? What happens to existing multiline HUD texts in which the `alignment` parameter was not set?

**Comment by appgurueu** [comment]
> Has backwards-compability been tested? What happens to existing multiline HUD texts in which the `alignment` parameter was not set?

Alignment not set is equal to `alignment = {x = 0, y = 0}`

**Comment by ExeVirus** [comment]
This would be an awesome thing, I have just recently needed multiline text in hud and center alignment is required.

**Review by SmallJoker — APPROVED** [review]
The documentation to this topic is not entirely clear:
`-1`=left result in right-aligned text (aligned to the left side of the specified position)
`1`=right results in left-aligned text (aligned to the right side of the specified position)

However, the PR works as expected.

File: src/client/hud.cpp [hunk 3]
```diff
@@ -377,15 +379,19 @@ void Hud::drawLuaElements(const v3s16 &camera_offset)
...
 				core::rect<s32> size(0, 0, e->scale.X * m_scale_factor,
-				                     text_height * e->scale.Y * m_scale_factor);
+									 text_height * e->scale.Y * m_scale_factor);
 				v2s32 offs(e->offset.X * m_scale_factor,
-				           e->offset.Y * m_scale_factor);
-
+						   e->offset.Y * m_scale_factor);
+				std::wstringstream wss(text);
+				std::wstring line;
+				while (std::getline(wss, line, L'\n'))
```
Comment (sfan5) [inline src/client/hud.cpp:389]: Can't line splitting be avoided here if align is the default value (0?),

Comment (appgurueu) [reply src/client/hud.cpp:389]: > Can't line splitting be avoided here if align is the default value (0?), I think that's preferable if possible.

Line splitting can be avoided if align is -1 (left justified). Which poses yet another issue: People might rely on the broken behavior to left-justify multiline text HUDs without align values.

Comment (sfan5) [reply src/client/hud.cpp:389]: The old and new left-aligned behavior is perfectly identical isn't it?
I don't quite get which case you're describing.

Comment (appgurueu) [reply src/client/hud.cpp:389]: No matter the value of align, due to the bug described by Wuzzy, all multiline text used to be left-justified.

This fix now centers text with align.x = 0. The default value for align is {x=0, y=0}, so if some modders omit align, they would now get centered text instead of the left justified text they might (wrongly) expect.

Comment (sfan5) [reply src/client/hud.cpp:389]: If it's documented that align=0 creates centered text that's fine.

Comment (appgurueu) [reply src/client/hud.cpp:389]: Alright. I'd love to just split the text on init, but that would require some kind of proper inheritance / class hierarchy instead of the current thing. I wouldn't want to add a `std::vector<std::string> lines` field to all HUD elements.

I doubt that `align = 0` would be much of an improvement in terms of performance - it will just leave Irrlicht / Freetype? to do the line splitting.

Comment (sfan5) [reply src/client/hud.cpp:389]: Okay then.

File: src/client/hud.cpp [hunk 4]
```diff
@@ -377,15 +379,19 @@ void Hud::drawLuaElements(const v3s16 &camera_offset)
 				std::wstring text = unescape_translate(utf8_to_wide(e->text));
 				core::dimension2d<u32> textsize = textfont->getDimension(text.c_str());
 
-				v2s32 offset((e->align.X - 1.0) * (textsize.Width / 2),
-				             (e->align.Y - 1.0) * (textsize.Height / 2));
+				v2s32 offset(0, (e->align.Y - 1.0) * (textsize.Height / 2));
 				core::rect<s32> size(0, 0, e->scale.X * m_scale_factor,
-				                     text_height * e->scale.Y * m_scale_factor);
+									 text_height * e->scale.Y * m_scale_factor);
```
Comment (sfan5) [inline src/client/hud.cpp:384]:
```suggestion
						text_height * e->scale.Y * m_scale_factor);
```

File: src/client/hud.cpp [hunk 5]
```diff
@@ -377,15 +379,19 @@ void Hud::drawLuaElements(const v3s16 &camera_offset)
...
-				v2s32 offset((e->align.X - 1.0) * (textsize.Width / 2),
-				             (e->align.Y - 1.0) * (textsize.Height / 2));
+				v2s32 offset(0, (e->align.Y - 1.0) * (textsize.Height / 2));
 				core::rect<s32> size(0, 0, e->scale.X * m_scale_factor,
-				                     text_height * e->scale.Y * m_scale_factor);
+						text_height * e->scale.Y * m_scale_factor);
 				v2s32 offs(e->offset.X * m_scale_factor,
-				           e->offset.Y * m_scale_factor);
-
+						   e->offset.Y * m_scale_factor);
```
Comment (sfan5) [inline src/client/hud.cpp:386]:
```suggestion
						e->offset.Y * m_scale_factor);
```

**Review by sfan5 — APPROVED** [review]
Looks good.
