### PR TITLE
FormSpec: Optimize formspec form size

### LINKED ISSUE #7603: Formspecs can display larger than game window
##### Issue type

 - Bug report
 
##### Minetest version

```
Minetest 5.0.0-dev-74d27642 (Linux)
Using Irrlicht 1.8.4
BUILD_TYPE=RELEASE
RUN_IN_PLACE=0
USE_GETTEXT=0
USE_SOUND=1
USE_CURL=1
USE_FREETYPE=1
USE_LUAJIT=1
STATIC_SHAREDIR="/usr/local/share/minetest"
```

##### OS / Hardware

Operating system:lubuntu 18.04
CPU:intel

##### Summary

I use the setting gui_scaling = 1.4 and a 1920x1080 screen. The unified inventory is partially hidden:
ou
If I adjust the window size, sometimes the whole formspec window is shown and sometimes a lot is missing (outside the minetest window).

##### Steps to reproduce

Use unified inventory or a similar mod with a big formspec, resize the minetest window and adjust gui_scaling.

### PR DESCRIPTION
**Pull request by v-rob**
This PR optimizes the formspec form size to use the screen space more efficiently and generally makes it more usable.  It does the following:
* Makes `real_coordinates` formspecs use more of the available screen space instead of factoring in the unused spacing and padding.
* Makes all formspecs stay within the screen boundaries (so this PR closes #7603), and also makes a 5% of the screen size spacing on all sides to make sure the formspec doesn't touch the screen edges.
* Removes legacy Android-specific code that uses the wrong numbers and doesn't do what it says.

## To do

This PR is Ready for Review.  Very simple.

## How to test

Try making formspecs of varying sizes in real and old coordinates and ensure that they stay inside the screen but also take full advantage of the space available.

### CODE REVIEW

File: src/gui/guiFormSpecMenu.cpp [hunk 1]
```diff
@@ -3098,22 +3098,36 @@ void GUIFormSpecMenu::regenerateGui(v2u32 screensize)
...
+			if (mydata.real_coordinates) {
+				use_imgsize = std::min(prefer_imgsize,
+						(double)std::min(mydata.screensize.X / mydata.invsize.X,
+						mydata.screensize.Y / mydata.invsize.Y));
+			} else {
+				double fitx_imgsize = mydata.screensize.X /
+					((5.0 / 4.0) * (0.5 + mydata.invsize.X));
+				double fity_imgsize = mydata.screensize.Y /
+					((15.0 / 13.0) * (0.85 * mydata.invsize.Y));
+				double screen_dpi = RenderingEngine::getDisplayDensity() * 96;
```
Comment (SmallJoker) [inline src/gui/guiFormSpecMenu.cpp:3127]: This variable already exists on L3069.

Comment (v-rob) [reply src/gui/guiFormSpecMenu.cpp:3127]: I wonder why GCC didn't give me an unused variable warning since it's no longer used...

**Comment by v-rob** [comment]
Added a 5% border on all sides, and it does look pretty good.  Actually, formspecs were still the wrong size in the Y direction using the old coordinate system; there was a multiplication where there should have been an addition (ever since 0.4.something; this is probably the main reason for #7603).  This is why I took me so long to respond; I couldn't figure out what was the problem :)

I also removed the weird and incorrect Android code which uses the wrong numbers and doesn't even do what the comment says, so Android uses the same code as desktop, except it retains the preferred imgsize.  At least the Android code had the addition instead of multiplication...

**Review by SmallJoker — APPROVED** [review]
Works.

**Comment by paramat** [comment]
v-rob, good to see you are now a core dev.

2 core dev approvals are required to merge a PR.
If a core dev is the author of a PR, their approval of their own PR counts as 1 of the required 2 core dev approvals. This is automatically assumed, so adding the '>= Two approvals' label is not necessary, the label can be left as 'One approval'.
