### PR TITLE
Remove sound attached to active object when active objects is removed

### LINKED ISSUE #8094: Audio attached to object stops moving when object leaves
##### Issue type
 - Bug report
 
##### Minetest version
minetest-5.0.0-a18c310-win64

##### OS / Hardware
Operating system: Windows 10
CPU: Intel(R) Core(TM) i7-6700HQ

##### Summary
Sounds that are attached to an object have issues when the object leaves the object send range.
They remain in the last known location of the object until it either comes back into range, or the audio ends.
This is mostly an issue with constant looping audio on a moving object, such as a car in the following video: (headphones recommended)
https://youtu.be/YoixyZzCTZc

##### Steps to reproduce
Make an object that you can move away from yourself and attach a looping and/or long sound to it.

### LINKED ISSUE #11521: Sound attached to objects do not disappear even when object is removed
##### Minetest version

```
minetest 5.4.1
```

##### OS / Hardware

Operating system: Win10
CPU: amd64

GPU model:
OpenGL version:

##### Summary
When ```minetest.play_sound``` is invoked with an attaching object, the sound still plays at the last position even if object is removed. In another word, if an object is removed, sounds attached to it will exist like a ghost and fix at the object's last position.

advtrains mod has workaround for this bug.

##### Steps to reproduce

```lua
minetest.play_sound("some_sound", {loop=true, object=some_external_obj}
-- ...
-- at another place
some_external_obj:remove()
```

### PR DESCRIPTION
**Pull request by sfence**
Add compact, short information about your PR for easier understanding:

- Goal of the PR
Fixes #11521.
- How does the PR work?
Remove sounds attached to removed active objects on the client side.
- Does it resolve any reported issue?
Bug #11521 and fixes #8094.

## To do

This PR is a Ready for Review.

## How to test

Attach sound in the loop to ActiveObject via jukebox in devtest and destroy an object.
With this fix, sounds should disappear.

### CODE REVIEW

**Review by appgurueu — COMMENTED** [review]
Fix seems straightforward. Why a linear search rather than introducing an additional inverse map `m_objects_to_sounds` though? If you did the latter, you could remove sounds in constant time, and the code complexity would be about the same. (This would effectively be a bidirectional map between object and sound IDs; if you want, you can introduce an template class for that, which would help ensure that the maps stay in sync).

**Comment by sfence** [comment]
> Fix seems straightforward. Why a linear search rather than introducing an additional inverse map `m_objects_to_sounds` though? If you did the latter, you could remove sounds in constant time, and the code complexity would be about the same. (This would effectively be a bidirectional map between object and sound IDs; if you want, you can introduce an template class for that, which would help ensure that the maps stay in sync).

It will have to be something like 
`std::unordered_map<u16, std::vector<sound_handle_t>> m_objects_to_sounds;` in that case.

**Comment by appgurueu** [comment]
> It will have to be something like `std::unordered_map<u16, std::vector<sound_handle_t>> m_objects_to_sounds;` in that case.

Right. That would indeed be slightly more complex, and also have some more overhead. I suppose since there probably aren't that many sounds attached to objects at a time, the linear search is probably fine. Nevermind my comment, then.

File: src/server.cpp [hunk 1]
```diff
@@ -893,6 +893,23 @@ void Server::AsyncRunStep(float dtime, bool initial_step)
...
+	{
+		MutexAutoLock envlock(m_env_mutex);
+
+		for (auto it = m_playing_sounds.begin(); it != m_playing_sounds.end(); it++) {
+			ServerPlayingSound &sound = it->second;
+
+			if (sound.type != SoundLocation::Object)
+				continue;;
+
+			if (!m_env->getActiveObject(sound.object))
```
[the remark this answers is not in the document]
Comment (sfence) [reply src/server.cpp]: moved

File: src/client/client.h [hunk 2]
```diff
@@ -475,6 +475,9 @@ class Client : public con::PeerHandler, public InventoryManager, public IGameDef
 
 	bool canSendChatMessage() const;
 
+	// helper method for manage sounds
```
Comment (sfan5) [inline src/client/client.h:478]: wrong indent on the line below
and this comment is not very meaningful

File: src/server.cpp [hunk 3]
```diff
@@ -2257,6 +2257,20 @@ void Server::fadeSound(s32 handle, float step, float gain)
...
+{
+	assert(id);
+
+	for (const auto &sit: m_playing_sounds) {
+		const ServerPlayingSound &sound = sit.second;
+
+		if (sound.object != id)
+			continue;
+
+		stopSound(sit.first);
```
Comment (sfan5) [inline src/server.cpp:2270]: the client already knows to do this, so why send him a packet?

**Review by sfan5 — CHANGES_REQUESTED** [review]

**Review by sfan5 — APPROVED** [review]
not tested but carefully looked at the code and should work

File: src/server.cpp (hunk 3 above)
Comment (SmallJoker) [reply src/server.cpp]: Will old clients stop the sound on their own?

Comment (sfan5) [reply src/server.cpp]: IMO we shouldn't spend effort working around client bugs

File: src/serverenvironment.cpp [hunk 4]
```diff
@@ -2217,6 +2221,8 @@ void ServerEnvironment::deactivateFarObjects(bool _force_delete)
 		obj->removingFromEnvironment();
 		// Deregister in scripting api
 		m_script->removeObjectReference(obj);
+		// stop attached sounds
+		m_server->stopAttachedSounds(id);
```
Comment (appgurueu) [inline src/serverenvironment.cpp:2225]:
```c++
// Tell the object about removal
obj->removingFromEnvironment();
// Deregister in scripting api
m_script->removeObjectReference(obj);
// stop attached sounds
m_server->stopAttachedSounds(id);
```

Appears 3 times. It would be good to extract it into a function.

File: src/serverenvironment.cpp [hunk 5]
```diff
@@ -1256,6 +1256,8 @@ void ServerEnvironment::clearObjects(ClearObjectsMode mode)
...
```
Comment (appgurueu) [inline src/serverenvironment.cpp:1260]: clearobjects is now O(n²) if every object has a sound btw (but still I don't think there's necessarily any need to prematurely optimize this, since I don't expect thousands of objects or sounds to be around)

**Review by appgurueu — CHANGES_REQUESTED** [review]
I think there's a bug. Attach a looping sound to an object (I used `soundstuff:bigfoot`, which has `static_save = false`, for this), then distance yourself from that object until it is unloaded (on the client, not on the server), then approach that object. Notice that the sound is now gone; it shouldn't be gone. (On master, it isn't; the sound never stops playing to begin with.)

I think the server should "resend" sounds when an object comes back in range?

**Comment by sfan5** [comment]
> I think the server should "resend" sounds when an object comes back in range?

The central problem is that the server has no tracking of sounds.
It looks like the current approach of bandaid fixes on this is not viable and it needs to be addressed properly.

File: src/serverenvironment.cpp (hunk 5 above)
Comment (sfan5) [reply src/serverenvironment.cpp:1260]: I think it *should* be prematurely optimized. It's very easy too:
```cpp
void Server::stopAttachedSounds(const std::unordered_set<u16>&);

void Server::some_function() {
    std::unordered_set<u16> removed_ids;
    for (...) {
        // ...
        m_script->removeObjectReference(obj);
        removed_ids.insert(id);
        // ...
    }
    m_server->stopAttachedSounds(removed_ids);
}
```

**Comment by sfence** [comment]
> > I think the server should "resend" sounds when an object comes back in range?
> 
> The central problem is that the server has no tracking of sounds. It looks like the current approach of bandaid fixes on this is not viable and it needs to be addressed properly.
> Regarding the status of this PR: are we okay with exchanging one bug for another or do we rather want to close this?

The sound resending should be fixed with #14342.

**Comment by appgurueu** [comment]
> Regarding the status of this PR: are we okay with exchanging one bug for another or do we rather want to close this? 

I'm fine with merging this under the premise that we try to get #14342 merged after it (for 5.9). We could also combine these two PRs into a two commit nosquash PR to make it atomic ¯\_(ツ)_/¯

**Review by SmallJoker — APPROVED** [review]
Tested in the devtest game
1. entity spawner: place e.g. cube
2. branding iron: auto-assign object to name `obj:1`
3. place jukebox
  * Sound: `soundstuff_mono`
  * loop=1, no position, object="obj:1"

:ballot_box_with_check: `Client::removeActiveObjectSounds` is called and removes the sound
:ballot_box_with_check: `Server::stopAttachedSounds` is called and removes the sound

PR does what it promises.
:ballot_box_with_check:

**Comment by SmallJoker** [comment]
@appgurueu Would you please be so nice to renew your review? Currently this IMO counts as :-1:  hence the PR does not satisfy the merge requirements.

**Comment by appgurueu** [comment]
> @appgurueu Would you please be so nice to renew your review? Currently this IMO counts as 👎 hence the PR does not satisfy the merge requirements.

Yes, I am fine with merging this. Though I believe [dac6459](https://github.com/minetest/minetest/pull/14341/commits/dac6459bc62b79e85922187b805c4e9dd9b6571b) could have been slightly improved by getting the ID from the object (not that it would matter much).

**Comment by rubenwardy** [comment]
oh sorry, completely missed that negative vote
