### PR TITLE
Fix UB in modulo360f (bugfix for #13960)

### LINKED ISSUE #13960: minetest crashes in Sky::update
### Minetest version

```true
Minetest 5.8.0-dev-7213ff7 (OSX)
Using Irrlicht 1.9.0mt13
Using LuaJIT 2.1.1697887905
BUILD_TYPE=RelWithDebInfo
RUN_IN_PLACE=0
USE_CURL=1
USE_GETTEXT=1
USE_SOUND=1
STATIC_SHAREDIR="minetest.app/Contents/Resources"
STATIC_LOCALEDIR="minetest.app/Contents/Resources/locale"
```

### Active renderer

OpenGL 2.1

### Irrlicht device

OSX

### Operating system and version

MacOS 14.0

### CPU model

M1pro

### GPU model

M1pro

### OpenGL version

2.1

### Summary

minetest crashes in game 

Termination Reason:    Namespace SIGNAL, Code 4 Illegal instruction: 4

Thread 0 Crashed::  Dispatch queue: com.apple.main-thread
0   minetest                      	       0x10291c558 modulo360f(float) + 12 (numeric.h:216) [inlined]
1   minetest                      	       0x10291c558 wrapDegrees_0_360(float) + 12 (numeric.h:229) [inlined]
2   minetest                      	       0x10291c558 Sky::update(float, float, float, bool, CameraMode, float, float) + 1676 (sky.cpp:446)

minetest 5.7.0 "official" installed with brew is not affected

### Steps to reproduce

I did not find the exact trigger yet. Visible sky seems to be a must

build script

cd ~/VSCode
rm -rf minetest
git clone --depth=1 https://github.com/minetest/minetest.git
cd minetest
git clone --depth=1 --branch `cat misc/irrlichtmt_tag.txt` https://github.com/minetest/irrlicht.git lib/irrlichtmt
git clone --depth 1 https://github.com/minetest/minetest_game.git games/minetest_game
mkdir build && cd build
cmake .. -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_OSX_DEPLOYMENT_TARGET=10.14 -DCMAKE_FIND_FRAMEWORK=LAST -DCMAKE_INSTALL_PREFIX=../build/macos/ -DRUN_IN_PLACE=FALSE -DENABLE_GETTEXT=TRUE  -DENABLE_POSTGRESQL=0  -DENABLE_LUAJIT=1 -DENABLE_SPATIAL=0
make -j$(sysctl -n hw.logicalcpu)
make install
codesign --remove-signature macos/minetest.app && codesign --force --deep -s - macos/minetest.app

latest Xcode toolchain

### PR DESCRIPTION
**Pull request by superfloh247**
- Goal of the PR

fix #13960

- How does the PR work?

use fmodf instead of homegrown modulo function (which has UB in it leading to a crash on macOS/arm64)

- Does it resolve any reported issue?

fix #13960

- Does this relate to a goal in [the roadmap](https://github.com/minetest/minetest/blob/master/doc/direction.md)?
- If not a bug fix, why is this PR needed? What usecases does it solve?

### CODE REVIEW

**Review by Desour — APPROVED** [review]
Thanks for the PR! (And sorry that I haven't made it myself earlier already.)

I've added a small commit to your branch, I hope that's fine by you.

It's noteworthy that there are tests for this functions (see `unittest/test_utilities.cpp`), including the following:
`UASSERT(std::fabs(modulo360f(f) - fmodf(f, 360)) < 0.001);`
(Hence this is trivial.)

Further changes, like replacing `modulo360f` calls with `fmodf`, or looking into the performance differences are left to other PRs.

**Comment by superfloh247** [comment]
Naïve question: can the compiler, eg clang17, detect such UB?
Or other code analysis tools?

**Comment by superfloh247** [comment]
OK, google was my friend

-DCMAKE_CXX_FLAGS="-fsanitize=undefined" -DCMAKE_C_FLAGS="-fsanitize=undefined" 

Oh boy, that looks like *a lot* of work

File: src/util/numeric.h [hunk 1]
```diff
@@ -195,30 +195,10 @@ struct MeshGrid {
...
-		sign = 1;
-	}
-
-	whole = f;
-
-	fraction = f - whole;
-	whole %= 360;
-
-	return sign * (whole + fraction);
+	return fmodf(f, 360.0f);
```
Comment (JosiahWI) [inline src/util/numeric.h:201]: Could you include the `<cmath>` header? It is risky to rely on transitive includes.

**Review by JosiahWI — CHANGES_REQUESTED** [review]

**Comment by Desour** [comment]
>Oh boy, that looks like a lot of work

You have to add `-fno-sanitize=vptr` (because irrlicht is built with `-fno-rtti` for some reason).

**Comment by sfan5** [comment]
Has anyone quickly checked the performance difference? If someone went to the trouble of implementing this a while ago it must have been worth it.

**Comment by superfloh247** [comment]
int whole;
whole %= 360;
is UB, we have to change that

**Comment by JosiahWI** [comment]
## With "-O3 -NDEBUG -flto":
```
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
bench is a Catch v2.13.8 host application.
Run with -? for options

-------------------------------------------------------------------------------
some benchmarks
-------------------------------------------------------------------------------
../bench.cpp:32
...............................................................................

benchmark name                       samples       iterations    estimated
                                     mean          low mean      high mean
                                     std dev       low std dev   high std dev
-------------------------------------------------------------------------------
0 degrees custom                               100        159394          0 ns 
                                       0.250391 ns   0.248686 ns   0.254557 ns 
                                      0.0126634 ns 0.00437802 ns  0.0235747 ns 
                                                                               
0 degrees STL                                  100          4989     3.4923 ms 
                                        7.93357 ns    7.92094 ns    7.96442 ns 
                                      0.0908921 ns  0.0429168 ns   0.175506 ns 
                                                                               
30 degrees custom                              100        159507          0 ns 
                                       0.249907 ns   0.247656 ns   0.255831 ns 
                                      0.0163804 ns  0.0032261 ns  0.0332486 ns 
                                                                               
30 degrees STL                                 100          4994     3.4958 ms 
                                        7.92571 ns    7.91696 ns    7.96108 ns 
                                      0.0744893 ns 0.00052603 ns   0.175023 ns 
                                                                               
90 degrees custom                              100        159608          0 ns 
                                        0.24762 ns   0.247393 ns   0.248653 ns 
                                     0.00210041 ns 3.96305e-05 ns 0.00499539 ns 
                                                                               
90 degrees STL                                 100          4918     3.9344 ms 
                                        7.93326 ns    7.92236 ns    7.95375 ns 
                                      0.0730632 ns  0.0403438 ns    0.10908 ns 
                                                                               
720 degrees custom                             100        159838          0 ns 
                                       0.252863 ns   0.249195 ns   0.265107 ns 
                                      0.0300382 ns   0.005328 ns  0.0665111 ns 
                                                                               
720 degrees STL                                100          3816      3.816 ms 
                                        10.3581 ns    10.3303 ns    10.3924 ns 
                                       0.156681 ns   0.123828 ns   0.237774 ns 
                                                                               
8765 degrees custom                            100        158081          0 ns 
                                       0.248982 ns   0.247518 ns   0.255734 ns 
                                      0.0135527 ns  0.0012922 ns  0.0321478 ns 
                                                                               
8765 degrees STL                               100          3137     3.7644 ms 
                                        12.7996 ns    12.7352 ns    12.9665 ns 
                                       0.488957 ns   0.211782 ns     1.0038 ns 
                                                                               

===============================================================================
```

## With "-O3 -NDEBUG -flto -ffast-math":
```
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
bench is a Catch v2.13.8 host application.
Run with -? for options

-------------------------------------------------------------------------------
some benchmarks
-------------------------------------------------------------------------------
../bench.cpp:32
...............................................................................

benchmark name                       samples       iterations    estimated
                                     mean          low mean      high mean
                                     std dev       low std dev   high std dev
-------------------------------------------------------------------------------
0 degrees custom                               100        159423          0 ns 
                                       0.251984 ns   0.247621 ns   0.273065 ns 
                                      0.0419745 ns 0.00177915 ns   0.100058 ns 
                                                                               
0 degrees STL                                  100         78069          0 ns 
                                       0.517244 ns   0.504908 ns   0.537581 ns 
                                      0.0790477 ns  0.0524809 ns   0.107756 ns 
                                                                               
30 degrees custom                              100        152615          0 ns 
                                       0.260261 ns   0.253701 ns    0.27067 ns 
                                      0.0416178 ns  0.0286855 ns  0.0555429 ns 
                                                                               
30 degrees STL                                 100        155794          0 ns 
                                       0.250298 ns   0.249049 ns   0.252167 ns 
                                     0.00772191 ns 0.00563075 ns  0.0101665 ns 
                                                                               
90 degrees custom                              100        157964          0 ns 
                                       0.248006 ns   0.247563 ns   0.249029 ns 
                                     0.00325827 ns 0.00135721 ns 0.00563761 ns 
                                                                               
90 degrees STL                                 100        159343          0 ns 
                                       0.247906 ns   0.247467 ns   0.249019 ns 
                                     0.00310673 ns 0.000318744 ns 0.00567894 ns 
                                                                               
720 degrees custom                             100        159629          0 ns 
                                       0.248083 ns   0.247625 ns   0.249075 ns 
                                     0.00328364 ns  0.0016791 ns 0.00539785 ns 
                                                                               
720 degrees STL                                100        159542          0 ns 
                                       0.331875 ns   0.311725 ns   0.359673 ns 
                                       0.119776 ns  0.0959672 ns   0.186467 ns 
                                                                               
8765 degrees custom                            100        158494          0 ns 
                                       0.248685 ns   0.248041 ns   0.249716 ns 
                                     0.00414432 ns 0.00293873 ns 0.00564388 ns 
                                                                               
8765 degrees STL                               100        158549          0 ns 
                                       0.250697 ns   0.248712 ns   0.255437 ns 
                                      0.0145689 ns 0.00497807 ns   0.025591 ns 
                                                                               

===============================================================================
```

**Comment by sfan5** [comment]
Can you check with `-fno-math-errno -fno-trapping-math -fno-signed-zeros`? We don't use `-ffast-math` as it breaks other calculations.

**Comment by JosiahWI** [comment]
Note that even with `ffast-math`, the p-value for 

> Can you check with `-fno-math-errno -fno-trapping-math -fno-signed-zeros`? We don't use `-ffast-math` as it breaks other calculations.

## With "-O3 -NDEBUG -fno-math-errno -fno-trapping-math -fno-signed-zeros"
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
bench is a Catch v2.13.8 host application.
Run with -? for options

-------------------------------------------------------------------------------
some benchmarks
-------------------------------------------------------------------------------
../bench.cpp:32
...............................................................................

benchmark name                       samples       iterations    estimated
                                     mean          low mean      high mean
                                     std dev       low std dev   high std dev
-------------------------------------------------------------------------------
0 degrees custom                               100        159394          0 ns 
                                       0.250391 ns   0.248686 ns   0.254557 ns 
                                      0.0126634 ns 0.00437802 ns  0.0235747 ns 
                                                                               
0 degrees STL                                  100          4989     3.4923 ms 
                                        7.93357 ns    7.92094 ns    7.96442 ns 
                                      0.0908921 ns  0.0429168 ns   0.175506 ns 
                                                                               
30 degrees custom                              100        159507          0 ns 
                                       0.249907 ns   0.247656 ns   0.255831 ns 
                                      0.0163804 ns  0.0032261 ns  0.0332486 ns 
                                                                               
30 degrees STL                                 100          4994     3.4958 ms 
                                        7.92571 ns    7.91696 ns    7.96108 ns 
                                      0.0744893 ns 0.00052603 ns   0.175023 ns 
                                                                               
90 degrees custom                              100        159608          0 ns 
                                        0.24762 ns   0.247393 ns   0.248653 ns 
                                     0.00210041 ns 3.96305e-05 ns 0.00499539 ns 
                                                                               
90 degrees STL                                 100          4918     3.9344 ms 
                                        7.93326 ns    7.92236 ns    7.95375 ns 
                                      0.0730632 ns  0.0403438 ns    0.10908 ns 
                                                                               
720 degrees custom                             100        159838          0 ns 
                                       0.252863 ns   0.249195 ns   0.265107 ns 
                                      0.0300382 ns   0.005328 ns  0.0665111 ns 
                                                                               
720 degrees STL                                100          3816      3.816 ms 
                                        10.3581 ns    10.3303 ns    10.3924 ns 
                                       0.156681 ns   0.123828 ns   0.237774 ns 
                                                                               
8765 degrees custom                            100        158081          0 ns 
                                       0.248982 ns   0.247518 ns   0.255734 ns 
                                      0.0135527 ns  0.0012922 ns  0.0321478 ns 
                                                                               
8765 degrees STL                               100          3137     3.7644 ms 
                                        12.7996 ns    12.7352 ns    12.9665 ns 
                                       0.488957 ns   0.211782 ns     1.0038 ns 
                                                                               

===============================================================================

**Comment by sfan5** [comment]
Thanks, looks good.

**Review by JosiahWI — APPROVED** [review]
