### PR TITLE
Return shadow_sky_body_orbit_tilt setting

### LINKED ISSUE #13302: MT 5.7 - Skybox broken when using setters from mods
##### Minetest version

```
Server: Minetest 5.6.1 (not sure if this matters)
Client: Minetest 5.7.0-dev-9ef3c8c (OSX)
```

##### OS / Hardware
Operating system: macOS 13.2.1
CPU: X86-64

OpenGL version: 2.1

##### Summary
Seems like when mods (event MTG) use some set methods for skybox (moon, sun, stars, clouds...) it is conflicting with something and sometimes the skybox gets broken. Shadows are where they should not be (due to missing sun), moon/sun skewed and visible (or not) where they should not be.

##### Steps to reproduce
How I can reproduce:
* I have all shaders, pre-post-whatever processing enabled
* login to the world, change the biomes to trigger the sky changes
* logout form world
* disable bloom
* log back in and repeat step 2

(i) not sure if steps 1-3 are really needed, thats just how I know I can reproduce

Video: https://youtu.be/CxICKE5W-HU

### PR DESCRIPTION
**Pull request by x2048**
Used as a default value when the game does not change the value via API (e.g. legacy server)

Fixes #13302.

## To do

This PR is Ready for Review.

## How to test

1. Set the setting `shadow_sky_body_orbit_tilt = 60`
2. Enable shadows
3. Start a 5.7.0 game with shadows, notice the sun orbit tilt is 60 degrees
4. Connect to a 5.6.1 server, notice sun orbit tilt is 60 degrees
5. Add a mod with the following code:
```
minetest.register_on_joinplayer(function(player)
	player:set_sky({body_orbit_tilt = 30})
end)
```
7.  Enable the mod and start the game
8. Notice the orbit tilt is 30 degrees

### CODE REVIEW

**Comment by x2048** [comment]
@Desour the problem was in not having a default value in SkyboxParams when deserialization fails of skips the value. I've returned the setting to act as a drop-in value in these cases.

**Comment by sfan5** [comment]
Are we sure we want to introduce a setting that only works on older server (this is mostly opaque to the user and will cause confusion)? Why not just hardcode 60 as default?

**Comment by x2048** [comment]
It will also work for games that don't change orbit_tilt via API.

File: src/client/sky.h [hunk 1]
```diff
@@ -98,7 +98,9 @@ class Sky : public scene::ISceneNode
 	}
 	void setBodyOrbitTilt(float body_orbit_tilt)
 	{
-		m_sky_params.body_orbit_tilt = body_orbit_tilt;
+		warningstream << "body orbit tilt " << body_orbit_tilt << std::endl;
```
Comment (lhofhansl) [inline src/client/sky.h:101]: Leftover warning?

**Comment by lhofhansl** [comment]
Looks good (minus the warning)

File: src/skyparams.h [hunk 2]
```diff
@@ -19,6 +19,8 @@ with this program; if not, write to the Free Software Foundation, Inc.,
 
 #pragma once
 
+#include <cmath>
```
Comment (sfan5) [inline src/skyparams.h:22]: looks unused

**Comment by sfan5** [comment]
> It will also work for games/servers that don't change orbit_tilt via API.

I see. Didn't review the code prior to commenting.
Will this work correctly with `get_lighting()` (so that it does not return -1024)?

File: src/client/sky.h (hunk 1 above)
Comment (x2048) [reply src/client/sky.h:101]: Yes, debugging code

Comment (x2048) [reply src/client/sky.h]: Removed now

**Comment by x2048** [comment]
I've added an `if` to avoid returning `orbit_tilt` from `get_sky(true)` when the value is 1024. It is not possible for the moders to set that value because of rangelim in `l_set_sky`

**Comment by sfan5** [comment]
should be documented in lua_api.txt that the field can be nil.

**Comment by x2048** [comment]
Expanded the documentation for the parameter, explaining the default behavior and changing the values.
