### PR TITLE
Show warning in the settings menu when shaders are disabled

### LINKED ISSUE #15270: Bad UX when upgrading to 5.10 with shaders disabled
### Minetest version

5.10.0-dev

### Summary

Since #15210, the `enable_shaders` setting is inside advanced settings (hidden by default) and enabling shaders results in a warning. +1 for that.

However, now imagine someone who has `enable_shaders = false` in their minetest.conf upgrades from 5.9.1 to 5.10.0. If they're a normal non-tech-savvy person, ...

1. ... they will be confused because the option to enable shaders again is suddenly gone from the settings, and with it the option to enable all the fancy effects.
2. ... they may not be able find out how to enable shaders again.
3. ... they may not even notice they're missing something.
4. ... they'll likely never see the warning (#15209)

### Solutions

Fixing #15209 wouldn't fully solve the bad UX problem. The user would still need to know about the advanced settings section and manually enable shaders again.

#### Idea 1

Move the `enable_shaders` setting back to the normal settings ("Effects" section) when it's false, only hide it in the advanced settings when it's true

#### Idea 2

Here's a mockup:
shaders disabled mockup

### Steps to reproduce

1. Install Minetest 5.9.1
2. Disable shaders
3. Upgrade to Minetest 5.10.0-dev

### PR DESCRIPTION
**Pull request by grorp**
fixes #15270

screenshot:
screenshot

## To do

This PR is a Ready for Review.

## How to test

Disable shaders. Verify that a warning asking you to enable them is shown in the "Graphics" and "Effects" setting sections. Verify that the warning disappears when you click "Enable".

### CODE REVIEW

File: builtin/mainmenu/settings/shader_warning_component.lua [hunk 1]
```diff
@@ -0,0 +1,40 @@
...
+--(at your option) any later version.
+--
+--This program is distributed in the hope that it will be useful,
+--but WITHOUT ANY WARRANTY; without even the implied warranty of
+--MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
+--GNU Lesser General Public License for more details.
+--
+--You should have received a copy of the GNU Lesser General Public License along
+--with this program; if not, write to the Free Software Foundation, Inc.,
+--51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
```
Comment (sfan5) [inline builtin/mainmenu/settings/shader_warning_component.lua:16]: \*psst\* <sup><sup><sup><sup>SPDX

File: builtin/mainmenu/settings/shader_warning_component.lua [hunk 2]
```diff
@@ -0,0 +1,26 @@
...
+            "box[0,0;", avail_w, ",1.2;", mt_color_orange, "]",
+			"label[0.2,0.4;", fgettext("Shaders are disabled."), "]",
+			"label[0.2,0.8;", fgettext("This is not a recommended configuration."), "]",
+			"button[", avail_w - 2.2, ",0.2;2,0.8;fix_shader_warning;Enable]",
+        }
+		return table.concat(fs, ""), 1.2
+	end,
+	on_submit = function(self, fields)
+		if fields.fix_shader_warning then
+			core.settings:remove("enable_shaders") -- default value is true
```
Comment (chmodsayshello) [inline builtin/mainmenu/settings/shader_warning_component.lua:22]: Wouldn't it be better to directly set this to true in order to avoid surprises in case the default value changes at some point?

File: builtin/mainmenu/settings/shader_warning_component.lua [hunk 3]
```diff
@@ -0,0 +1,26 @@
...
+		shaders_support = true,
+        shaders = false,
+	},
+    full_width = true,
+	get_formspec = function(self, avail_w)
+        local fs = {
+            "box[0,0;", avail_w, ",1.2;", mt_color_orange, "]",
+			"label[0.2,0.4;", fgettext("Shaders are disabled."), "]",
+			"label[0.2,0.8;", fgettext("This is not a recommended configuration."), "]",
+			"button[", avail_w - 2.2, ",0.2;2,0.8;fix_shader_warning;Enable]",
```
Comment (chmodsayshello) [inline builtin/mainmenu/settings/shader_warning_component.lua:16]: "Enable" should also have a translation.

Comment (grorp) [reply builtin/mainmenu/settings/shader_warning_component.lua]: oops

File: builtin/mainmenu/settings/shader_warning_component.lua (hunk 2 above)
Comment (grorp) [reply builtin/mainmenu/settings/shader_warning_component.lua:22]: 1. The default value of `enable_shaders` won't change to false. If it did, showing a warning when `enable_shaders` is false would make no sense anyway.
2. It's better not to clutter the configuration with useless settings

Comment (chmodsayshello) [reply builtin/mainmenu/settings/shader_warning_component.lua:22]: fair enough.

**Review by Ekdohibs — APPROVED** [review]
Works as expected, looks good to me!
