### PR TITLE
[no squash] Fix building unittests & benchmarks by upgrading Catch2

### LINKED ISSUE #14692: Can't build benchmark and unit tests at the same time
```
[ 36%] Linking CXX executable /home/stefan/minetest/bin/minetest
ld.lld: error: duplicate symbol: Catch::StreamEndStop::operator+[abi:cxx11]() const
>>> defined at basic_string.h:235 (/usr/include/c++/14.1.1/bits/basic_string.h:235)
>>>            CMakeFiles/minetest.dir/benchmark/benchmark.cpp.o:(Catch::StreamEndStop::operator+[abi:cxx11]() const)
>>> defined at basic_string.h:235 (/usr/include/c++/14.1.1/bits/basic_string.h:235)
>>>            CMakeFiles/minetest.dir/unittest/test.cpp.o:(.text+0x0)

ld.lld: error: duplicate symbol: Catch::XmlReporter::getStylesheetRef[abi:cxx11]() const
>>> defined at basic_string.h:235 (/usr/include/c++/14.1.1/bits/basic_string.h:235)
>>>            CMakeFiles/minetest.dir/benchmark/benchmark.cpp.o:(Catch::StreamEndStop::operator+[abi:cxx11]() const)
>>> defined at basic_string.h:235 (/usr/include/c++/14.1.1/bits/basic_string.h:235)
>>>            CMakeFiles/minetest.dir/unittest/test.cpp.o:(.text+0x0)

ld.lld: error: duplicate symbol: Catch::NonCopyable::~NonCopyable()
>>> defined at catch.hpp:9943 (/home/stefan/minetest/lib/catch2/catch.hpp:9943)
>>>            CMakeFiles/minetest.dir/benchmark/benchmark.cpp.o:(Catch::NonCopyable::~NonCopyable())
>>> defined at catch.hpp:9943 (/home/stefan/minetest/lib/catch2/catch.hpp:9943)
>>>            CMakeFiles/minetest.dir/unittest/test.cpp.o:(.text+0x20)
[...]
```

### PR DESCRIPTION
**Pull request by appgurueu**
Fixes #14692, alternative to #14693, by simply upgrading Catch2 to v3. Catch uses a separate implementation and header now, which helps resolve the issue. This uses the amalgamation.

Bonus: Catch2 version upgrade.

Small change (I consider this an improvement, but you may differ): Gets rid of `#define CATCH_CONFIG_CONSOLE_WIDTH 160`. I think this (arbitrarily?) chosen number is too large. It is also inconsistent with unit tests. Using the Catch default (80) here is better (and simpler) IMO.

Fun fact: You can run benchmarks via `--run-unittests --test-module <benchmark>` now. Catch2 also prints "Randomness seeded to: \<seed\>" now.

To review, look at the second commit (https://github.com/minetest/minetest/commit/8b026992891d7e1fd868bfe3471f4915b000893e). The first commit updates the vendored copy, which causes a lot of noise.

## How to test

1. Compile with unittests and benchmarks enabled.
2. Confirm that `--run-unittests` and `--run-benchmarks` work as expected.
3. Confirm that both still work as expected if `--test-module` is used.

### CODE REVIEW

**Comment by sfan5** [comment]
> ps. Catch did not go from 20kloc to 200kloc. The git diff is largely from Catch2 test files (text files). Removing the tests would reduce the size of Catch2 by ~5 MB.

Importing 200kLOC is a terrible idea.
We should either vendor the amalgated source, require catch2 to already be installed or consider a submodule. (in order of personal preference) 

> * Gets rid of our "modification" to Catch which forced everything to be formatted as microseconds - now it will format as ns, µs, ms, etc. as appropriate. I prefer this.

I'm pretty sure this was required to make the [automated benchmarks](https://github.com/minetest/benchmarks) work correctly.

**Comment by appgurueu** [comment]
Alright, I'll go with the amalgamated source, and re-apply the patch to output everything in microseconds.

**Comment by appgurueu** [comment]
Alright, switched to the amalgamation. The custom cout / cerr / clog pose a problem, because they cause ODR definition violations vs. Catch internals. We need to tell Catch to always use our redefinitions (for benchmarks as well) which just use `rawstream`, which is what I did now.

File: src/catch.cpp [hunk 1]
```diff
@@ -0,0 +1,18 @@
...
+	std::ostream& cout() {
+		return rawstream;
+	}
+	std::ostream& clog() {
+		return rawstream;
+	}
+	std::ostream& cerr() {
+		return rawstream;
+	}
+}
```
Comment (sfan5) [inline src/catch.cpp:18]: missing newline

Comment (appgurueu) [reply src/catch.cpp:18]: found it

File: lib/catch2/CMakeLists.txt [hunk 2]
```diff
@@ -12,6 +12,7 @@
 # -        return os << duration.value() << ' ' << duration.unitsAsString();
 # +        return os << std::fixed << duration.value() << ' ' << duration.unitsAsString();
 
-add_library(catch2 INTERFACE)
+add_library(catch2 STATIC catch_amalgamated.cpp)
+add_compile_definitions(CATCH_CONFIG_NOSTDOUT CATCH_AMALGAMATED_CUSTOM_MAIN)
```
Comment (JosiahWI) [inline lib/catch2/CMakeLists.txt:16]: Let's use `target_compile_definitions`.

File: src/catch.h [hunk 3]
```diff
@@ -0,0 +1,12 @@
...
+
+// we want to have catch write to rawstream (stderr) instead of stdout
+#define CATCH_CONFIG_NOSTDOUT
+#include <catch_amalgamated.hpp>
+
+namespace Catch {
+	std::ostream& cout();
+	std::ostream& clog();
+	std::ostream& cerr();
+}
```
Comment (JosiahWI) [inline src/catch.h:12]: Missing a newline at the end.

File: src/catch.h [hunk 4]
```diff
@@ -0,0 +1,12 @@
+// Minetest
```
Comment (JosiahWI) [inline src/catch.h:1]: Please explain/document that this header should be included instead of <catch.hpp> because it patches the output streams to rawstream.

File: src/unittest/test.cpp [hunk 5]
```diff
@@ -255,7 +243,12 @@ bool run_tests()
 	}
 
 	rawstream << "Catch test results: " << std::endl;
-	auto num_catch_tests_failed = Catch::Session().run();
+	Catch::Session session{};
+	auto config = session.configData();
+	config.skipBenchmarks = true;
+	config.allowZeroTests = true;
+	session.useConfigData(config);
+	auto num_catch_tests_failed = session.run();
```
Comment (JosiahWI) [inline src/unittest/test.cpp:251]: This returns an exit code now, not the number of tests failed. Let's not hide that under a false name.

**Review by JosiahWI — CHANGES_REQUESTED** [review]
Thank you for fixing the ability to build unittests and benchmarks together. This is a nice clean solution. I will be closing #14693 in favor of this.

File: lib/catch2/CMakeLists.txt (hunk 2 above)
Comment (appgurueu) [reply lib/catch2/CMakeLists.txt]: done

File: src/catch.h (hunk 4 above)
Comment (appgurueu) [reply src/catch.h:1]: done

File: src/unittest/test.cpp (hunk 5 above)
Comment (appgurueu) [reply src/unittest/test.cpp]: indeed, done

**Review by JosiahWI — APPROVED** [review]
LGTM

File: src/unittest/test.cpp [hunk 6]
```diff
@@ -17,10 +17,9 @@ with this program; if not, write to the Free Software Foundation, Inc.,
 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
 */
 
-#define CATCH_CONFIG_RUNNER
 // we want to have catch write to rawstream (stderr) instead of stdout
 #define CATCH_CONFIG_NOSTDOUT
```
Comment (sfan5) [inline src/unittest/test.cpp:21]: duplicate

**Comment by sfan5** [comment]
I also suggest changing the author of the first commit to something artificial to now skew the LoC change statistics.

**Comment by appgurueu** [comment]
> I also suggest changing the author of the first commit to something artificial to not skew the LoC change statistics.

Done, thanks for the reminder. (I remember having done this initially, but it probably got lost when I switched to the amalgamation, redoing the commit.)

**Review by sfan5 — APPROVED** [review]
CI green = good
