### PR TITLE
[no sq] Fix ECF_D32 support in ogles2 video driver

### LINKED ISSUE #15395: Black scene with "ogles2" video driver + post-processing on desktop
### Luanti version

5.10.0-dev

### Irrlicht device

SDL

### Operating system and version

Fedora Linux 40 (Workstation Edition)

### CPU model

Intel® Core™ i7-4790K × 8

### GPU model

NVIDIA GeForce GTX 1080 Ti

### Active renderer

OpenGL ES 3.2 NVIDIA 560.35.03

### Summary

With `video_driver = ogles2` and `enable_post_processing = true`, I get a black scene on my desktop computer (HUD is still rendered)

With `opengl_debug = true`, output looks like this:

```
Irrlicht: GL: 8246 824c GL_INVALID_VALUE error generated. <format> or <internalFormat> not valid.
Irrlicht: GL_INVALID_VALUE COpenGLCoreTexture.h:215
Irrlicht: COpenGLCoreTexture: InternalFormat:0x81a7 PixelFormat:0x1902
Irrlicht: GL: 8246 824c GL_INVALID_FRAMEBUFFER_OPERATION error generated. Operation is not valid because a bound framebuffer is not framebuffer complete.
```

```
#0  0x00007ffff6ea8664 in __pthread_kill_implementation () from /lib64/libc.so.6
#1  0x00007ffff6e4fc4e in raise () from /lib64/libc.so.6
#2  0x0000000000bb9622 in irr::video::COpenGL3DriverBase::debugCb (this=<optimized out>, source=<optimized out>, type=33356, id=<optimized out>, severity=37190, length=73, 
    message=0x7fffdea89200 "GL_INVALID_VALUE error generated. <format> or <internalFormat> not valid.") at /mt/irr/src/OpenGL/Driver.cpp:235
#3  0x00007fffdcc6de20 in ?? () from /lib64/libnvidia-glcore.so.560.35.03
#4  0x00007fffdcc6df6c in ?? () from /lib64/libnvidia-glcore.so.560.35.03
#5  0x00007fffdcc7c625 in ?? () from /lib64/libnvidia-glcore.so.560.35.03
#6  0x00007fffdd1da7b2 in ?? () from /lib64/libnvidia-glcore.so.560.35.03
#7  0x00007fffdd1dab74 in ?? () from /lib64/libnvidia-glcore.so.560.35.03
#8  0x0000000000bc4a28 in irr::video::COpenGLCoreTexture<irr::video::COpenGL3DriverBase>::COpenGLCoreTexture (this=this@entry=0x1a71cc0, name=..., size=..., type=type@entry=irr::video::ETT_2D, format=format@entry=irr::video::ECF_D32, 
    driver=driver@entry=0x174dff0, __in_chrg=<optimized out>, __vtt_parm=<optimized out>) at /mt/irr/src/COpenGLCoreTexture.h:202
#9  0x0000000000bc0b91 in irr::video::COpenGL3DriverBase::addRenderTargetTexture (this=0x174dff0, size=..., name=..., format=format@entry=irr::video::ECF_D32) at /mt/irr/src/OpenGL/Driver.cpp:1734
#10 0x00000000005aebf2 in TextureBuffer::ensureTexture (this=this@entry=0x2ccbeb0, texture=0x2e5df68, definition=..., context=...) at /mt/src/client/render/pipeline.cpp:135
#11 0x00000000005afcff in TextureBuffer::reset (this=0x2ccbeb0, context=...) at /mt/src/client/render/pipeline.cpp:85
#12 0x00000000005adc88 in RenderPipeline::run (this=0x2ce92a0, context=...) at /mt/src/client/render/pipeline.cpp:268
#13 0x00000000005add79 in RenderPipeline::run (this=<optimized out>, context=...) at /mt/src/client/render/pipeline.cpp:271
#14 0x00000000005ac306 in RenderingCore::draw (this=0x2e57ba0, _skycolor=..., _show_hud=true, _draw_wield_tool=true, _draw_crosshair=true) at /mt/src/client/render/core.cpp:36
#15 0x00000000005b7a22 in RenderingEngine::draw_scene (this=<optimized out>, skycolor=..., skycolor@entry=..., show_hud=<optimized out>, draw_wield_tool=<optimized out>, draw_crosshair=<optimized out>)
    at /mt/src/client/renderingengine.cpp:403
#16 0x000000000052efb3 in Game::drawScene (this=this@entry=0x7fffffffcca0, graph=graph@entry=0x7fffffffcb30, stats=stats@entry=0x7fffffffcaf0) at /mt/src/client/game.cpp:4361
#17 0x0000000000531fe5 in Game::updateFrame (this=this@entry=0x7fffffffcca0, graph=graph@entry=0x7fffffffcb30, stats=stats@entry=0x7fffffffcaf0, dtime=0.0501260012, cam=...) at /mt/src/client/game.cpp:4232
#18 0x0000000000534825 in Game::run (this=this@entry=0x7fffffffcca0) at /mt/src/client/game.cpp:1184
#19 0x0000000000535598 in the_game (kill=kill@entry=0xd4a380 <porting::g_killed>, input=0x178c470, rendering_engine=0xe68f60, start_data=..., error_message="", chat_backend=..., reconnect_requested=0x7fffffffcfdf)
    at /mt/src/client/game.cpp:4602
#20 0x00000000004c3de5 in ClientLauncher::run (this=this@entry=0x7fffffffd850, start_data=..., cmd_args=...) at /mt/src/client/clientlauncher.cpp:204
#21 0x000000000049072c in main (argc=<optimized out>, argv=0x7fffffffdf28) at /mt/src/main.cpp:264
```

i.e. it tries to create an `ECF_D32` texture and OpenGL rejects the texture format as invalid. I have a fix.

Possibly related to #13519

### Steps to reproduce

1. Set `video_driver = ogles2` and `enable_post_processing = true`
2. Restart Minetest
3. (Be lucky)

### PR DESCRIPTION
**Pull request by grorp**
fixes #15395

OES_depth32 only talks about support for render buffers, not textures, so it's not relevant here: https://github.com/KhronosGroup/OpenGL-Registry/blob/main/extensions/OES/OES_depth32.txt

This fixes the scene being black with "video_driver = ogles2" and "enable_post_processing = true" on my desktop computer.

## To do

This PR is a Ready for Review.

## How to test

ogles2 on Android: things should work
ogles2 on desktop: things should work

### CODE REVIEW

File: irr/src/COpenGLCoreTexture.h [hunk 1]
```diff
@@ -296,59 +296,6 @@ class COpenGLCoreTexture : public ITexture
...
-					CColorConverter::convert_A8R8G8B8toB8G8R8(src, tmpImage->getDimension().getArea(), dest);
-					break;
-				case ECF_A8R8G8B8:
-					CColorConverter::convert_A8R8G8B8toA8B8G8R8(src, tmpImage->getDimension().getArea(), dest);
-					break;
-				default:
-					passed = false;
-					break;
-				}
-				tmpImage->drop();
```
Comment (sfan5) [inline irr/src/COpenGLCoreTexture.h:351]: removing this will break screenshots, no?

File: irr/src/OpenGLES2/Driver.cpp [hunk 2]
```diff
@@ -98,8 +96,6 @@ void COpenGLES2Driver::initFeatures()
 
 		if (FeatureAvailable[IRR_GL_OES_depth_texture]) {
 			TextureFormats[ECF_D16] = {GL_DEPTH_COMPONENT, GL_DEPTH_COMPONENT, GL_UNSIGNED_SHORT};
-			if (FeatureAvailable[IRR_GL_OES_depth32])
-				TextureFormats[ECF_D32] = {GL_DEPTH_COMPONENT, GL_DEPTH_COMPONENT, GL_UNSIGNED_INT};
```
Comment (sfan5) [inline irr/src/OpenGLES2/Driver.cpp:102]: If I'm reading https://registry.khronos.org/OpenGL/extensions/OES/OES_depth_texture.txt correctly it already defines the combination of `(GL_DEPTH_COMPONENT, GL_UNSIGNED_INT)`

Comment (grorp) [reply irr/src/OpenGLES2/Driver.cpp:102]: Wow, I see, this is more messy than I thought...

**Review by sfan5 — APPROVED** [review]
code looks good, no change on my pc

**Comment by sfan5** [comment]
random thing I found on SO:
> GL_DEPTH_COMPONENT32 is probably overkill, and as of 4.5, isn't a required format for OpenGL implementations to support (though 16 and 24 bit ones are). Consider that higher resolution depth buffers may not be as performant.

maybe we should be preferring `ECF_D24S8` because do we really need 32-bit precision for the depth buffer?
even better we can add `ECF_D24` to avoid wasting memory on a stencil buffer we don't need.

**Comment by grorp** [comment]
> maybe we should be preferring `ECF_D24S8` because do we really need 32-bit precision for the depth buffer?
> even better we can add `ECF_D24` to avoid wasting memory on a stencil buffer we don't need.

Luckily I can declare this "out-of-scope for this PR" 😅
