### PR TITLE
Server: avoid re-use of recent ParticleSpawner and Sound IDs

### LINKED ISSUE #14044: ParticleSpawner (and maybe sound) IDs Reused
### Minetest version

```true
Minetest 5.8.0-dev-70261b8e9 (Linux)
Using Irrlicht 1.9.0mt13
Using LuaJIT 2.1.0-beta3
BUILD_TYPE=Release
RUN_IN_PLACE=1
USE_CURL=1
USE_GETTEXT=1
USE_SOUND=1
STATIC_SHAREDIR="."
STATIC_LOCALEDIR="locale"
```

### Active renderer

OpenGL 4.2

### Irrlicht device

X11

### Operating system and version

Debian 12

### CPU model

Intel i5-3320M (4) @ 3.300GHz

### GPU model

_No response_

### OpenGL version

_No response_

### Summary

Particle spawner IDs are aggressively reused, which can lead to deleting the wrong particle spawner.

It looks like the "ID" that MT returns for a particle spawner is not actually a unique identifier for that spawner, but an address (i.e. index of an array).  So if I create particle spawner X and it gets assigned ID 3, then when I later call delete_particlespawner(3) I am not actually saying "delete particle spawner X", I'm unwittingly saying "delete whatever particle spawner currently occupies index 3".  If X had already been deleted for some other reason (expiry, deletion by some other mod) then some other arbitrary particle spawner may now occupy that slot and be deleted instead.

The correct thing to do would be to use a unique value for each resource.  A mapping of resource unique ID to address could be maintained in the engine.

Ideally the resource identifiers would be opaque to Lua (e.g. userdata) to prevent users from attempting to rely on the content/structure of the values, or to try to serialize and store them, or try to fabricate them.

### Steps to reproduce

**WARNING**: Do **NOT** attempt to test this against NodeCore version `02673309-161dcfb0` or later, as there is already a workaround present that makes the bug unreproducible.

Install this mod code into a worldmod:

```lua
do
	local theta = 0
	local function fx()
		minetest.after(0.25, fx)

		-- singleplayer only
		local players = minetest.get_connected_players()
		local player = players[next(players)]
		if not player then return end

		local pos = player:get_pos()
		pos.y = pos.y + player:get_properties().eye_height
		local look = player:get_look_dir()
		local vert = vector.new(0, 1, 0)
		local horz = vector.cross(look, vert)
		vert = vector.cross(look, horz)
		theta = theta + math.pi / 8
		local targ = vector.add(pos, vector.multiply(look, 5))
		targ = vector.add(targ, vector.multiply(horz, math.sin(theta) * 3))
		targ = vector.add(targ, vector.multiply(vert, math.cos(theta) * 3))

		minetest.add_particlespawner({
				time = 1,
				amount = 50,
				minexptime = 0.5,
				maxexptime = 0.5,
				minpos = vector.offset(targ, -0.5, -0.5, -0.5),
				maxpos = vector.offset(targ, 0.5, 0.5, 0.5),
				minsize = 1,
				maxsize = 1,
				texture = "[combine:1x1^[noalpha",
			})
	end
	minetest.after(0, fx)
end
```

Stand still while looking out into open air, and observe that now a cloud of black particles will revolve around the center of the player's view.  This cloud is "smooth" and has no obvious gaps.

Now, add this code to a worldmod (it doesn't matter if it's in the same or different mod):

```lua
do
	local oldid
	local function fx()
		minetest.after(math.random() * 2, fx)

		-- singleplayer only
		local players = minetest.get_connected_players()
		local player = players[next(players)]
		if not player then return end

		local pos = player:get_pos()
		pos.y = pos.y + player:get_properties().eye_height
		pos = vector.offset(pos, math.random() * 10 - 5, math.random() * 10 - 5,
			math.random() * 10 - 5)
		if oldid then minetest.delete_particlespawner(oldid) end
		oldid = minetest.add_particlespawner({
				time = 1,
				amount = 50,
				minexptime = 0.5,
				maxexptime = 0.5,
				minpos = vector.offset(pos, -0.5, -0.5, -0.5),
				maxpos = vector.offset(pos, 0.5, 0.5, 0.5),
				minsize = 1,
				maxsize = 1,
				texture = "[combine:1x1^[noalpha^[invert:rgb",
			})
	end
	minetest.after(0, fx)
end
```

This will add a cloud of white particles that randomly teleports around the player.

Note that the black particle cloud "clock" will now have visible gaps in it, even though:
- The black particle effect was never modified, nothing it created was publicly accessible, and it never used delete_particlespawner
- The white particle effect code never deleted any particlespawner ID that it wasn't given by the API.

Note that the gaps may be subtle and difficult to differentiate against just the randomness of particle distribution in the cloud, but you an definitely see the difference in smoothness if you watch for a while and compare against the case without the teleporting white clouds.  Some of the black cloud particlespawners are getting deleted *too early*.

### PR DESCRIPTION
**Pull request by SmallJoker**
This improves the reliability when removing and re-adding handles quickly. Looping through the entire ID range avoids collisions caused by any race condition.

Fixes #14044

## To do

This PR is Ready for Review.

## How to test

1. #14044 -> "Steps to reproduce"

### CODE REVIEW

**Comment by appgurueu** [comment]
I think the proper solution would be to *just* autoincrement IDs, keeping the ID -> spawner mapping in an unordered map, and bumping the bit width to 64 bit so we don't have to worry about reusing IDs.

Overflowing is not a problem if you use a 64-bit type. On the Lua side of things, ints up to 2^53 will be accurate. Both of these numbers are high enough that I can guarantee you that it is not physically possible to hit them.

Then the logic in `next*Id` becomes trivial: It would simplify the code, rather than further complicating it. (It also gets rid of the worst case linear time complexity for searching for a free ID, though that is not necessarily relevant.)

File: src/serverenvironment.cpp [hunk 1]
```diff
@@ -1637,16 +1637,16 @@ u32 ServerEnvironment::addParticleSpawner(float exptime)
...
-		id++;
-		std::unordered_map<u32, float>::iterator f = m_particle_spawners.find(id);
-		if (f == m_particle_spawners.end()) {
-			m_particle_spawners[id] = time;
-			break;
-		}
+	u32 free_id = m_particle_spawners_id_last_used;
+	while (free_id == 0 || m_particle_spawners.find(free_id) != m_particle_spawners.end()) {
+		if (free_id == m_particle_spawners_id_last_used)
+			return 0; // full
```
Comment (sfan5) [inline src/serverenvironment.cpp:1643]: is zero a valid id?
I suppose not, would be good to use `std::optional<u32>` for the return one day

**Review by sfan5 — APPROVED** [review]
LGTM

File: src/serverenvironment.cpp (hunk 1 above)
Comment (SmallJoker) [reply src/serverenvironment.cpp:1643]: I currently do not see any indicator that 0 is a reserved ID - neither on client- nor server-side. However, it will at least be more consistent with the ID assignment from ActiveObjectMgr.

**Comment by Desour** [comment]
I didn't find time to test this before, sorry.

This introduced a bug: Sound ids are reused to early.
Reproduction:
* Place 2 devtest jukeboxes.
* With jukebox A, play a short sound, e.g. `soundstuff_mono`. Wait for it to end, do not release the handle.
* With jukebox B, play a long or looped sound, e.g. some music.
* Press stop sound in jukebox A.
* Bug: This stops the sound of jukebox B.

@SmallJoker
