### PR TITLE
Release invlist resizelock while doing the recursive callback in move_somewhere mode

### LINKED ISSUE #13465: set_list(..., {}) incorrectly forbidden in certain cases ("cannot be deleted or resized")
##### Minetest version
```
Minetest 5.8.0-dev-d197ff0f9 (Linux)
Using Irrlicht 1.9.0mt11
Using LuaJIT 2.1.0-beta3
BUILD_TYPE=Release
RUN_IN_PLACE=1
USE_CURL=1
USE_GETTEXT=1
USE_SOUND=1
STATIC_SHAREDIR="."
STATIC_LOCALEDIR="locale"
```

minetest/minetest_game@1e237b8d18da799593ad3a8253cdc5d8a7d772a9

##### OS / Hardware
Operating system: Fedora Linux 37 (Workstation Edition)
CPU: Intel® Core™ i7-4790K × 8

##### Summary & Steps to reproduce

You can put an itemstack into MTG's creative inventory trash field (thus "deleting" the itemstack) by shift-clicking it.

Since 0fb6dbab360813536b5b62a7ee4aa03e7757eeb4, if I try to put any itemstack into the trash by shift-click, Minetest crashes. This does not happen if I put items into the trash field "by hand".

```
AsyncErr: Lua: Runtime error from mod 'creative' in callback detached_inventory_OnPut(): InventoryList 'main' is currently in use and cannot be deleted or resized.
stack traceback:
	[C]: in function 'set_list'
	...n/bin/../games/minetest_game/mods/creative/inventory.lua:135: in function <...n/bin/../games/minetest_game/mods/creative/inventory.lua:134>
```

That this only happens since 0fb6dbab360813536b5b62a7ee4aa03e7757eeb4 (PR #13360) is why I'm opening the issue here rather than in the MTG repo.

### PR DESCRIPTION
**Pull request by Desour**
Fixes #13465.

## To do

This PR is a Ready for Review.

## How to test

* Shift-click something into trash in devtest chest of everything.

### CODE REVIEW

File: src/inventorymanager.cpp [hunk 1]
```diff
@@ -260,12 +260,18 @@ void IMoveAction::apply(InventoryManager *mgr, ServerActiveObject *player, IGame
 		return;
 	}
 
-	InventoryList *list_from = inv_from->getList(from_list);
-	InventoryList *list_to = inv_to->getList(to_list);
+	auto get_brrow_checked_invlist = [](Inventory *inv, const std::string &listname)
```
Comment (SmallJoker) [inline src/inventorymanager.cpp:263]: Spelling issue. -> `get_borrow_checked_invlist`

**Review by SmallJoker — APPROVED** [review]
Although this worsens performance, the PR does indeed fix the issue. Nothing special found with valgrind; seems to be OK.
