### PR TITLE
Fix #16601: Check if object is gone before calling `on_rightclick`

### LINKED ISSUE #16601: luaentity's on_rightclick can get an invalid self.object
### Luanti version

```true
Luanti 5.15.0-dev-debug-35357e430 (Linux)
Using LuaJIT 2.1.1753364724
Built by GCC 15.2
Running on Linux/6.16.8 x86_64
BUILD_TYPE=Debug
RUN_IN_PLACE=1
USE_CURL=1
USE_GETTEXT=1
USE_SOUND=1
STATIC_SHAREDIR="."
STATIC_LOCALEDIR="locale"
```

### Summary

The function `on_rightclick/on_secondary_use` of an item can remove the object/entity received from `pointed_thing`. However, the entity's `on_rightclick` function will still be called even if it no longer exists.

### Steps to reproduce

```lua
core.register_craftitem("test:testitem", {
	on_secondary_use = function(_, _, pointed_thing)
		if pointed_thing.type == "object" then
			pointed_thing.ref:remove()
		end
	end
})

core.register_entity("test:testentity", {
	on_rightclick = function(self)
		core.log("error", dump(self.object:is_valid()))
	end
})
```

### PR DESCRIPTION
**Pull request by appgurueu**
Does what it says, see the issue for further discussion.

The only concern is that this changes behavior, which some mods may not like.
But the bug seems like the bigger problem.

### CODE REVIEW

File: src/network/serverpackethandler.cpp [hunk 1]
```diff
@@ -1198,7 +1198,9 @@ void Server::handleCommand_Interact(NetworkPacket *pkt)
 					SendInventory(player, true);
 			}
 
-			pointed_object->rightClick(playersao);
+			// on_secondary_use might have removed the object
+			if (!pointed_object->isGone())
+				pointed_object->rightClick(playersao);
```
Comment (sfan5) [inline src/network/serverpackethandler.cpp]:
```suggestion
			// on_secondary_use might have removed the object
			if (pointed_object->isGone())
				return;

			pointed_object->rightClick(playersao);
```
