### PR TITLE
Fix segfault in deprecation logging due to tail call, log by default

### LINKED ISSUE #8322: deprecated_lua_api_handling = log causes crash for tail calls of deprecated functions
##### Issue type
 - Bug report

 
##### Minetest version
```
Minetest 5.1.0-dev-a7c5dc50 (Linux)
```

##### Summary
Minetest segfaults when attempting to log deprecated functions called inside on_generated (?)

##### Steps to reproduce
1. Install and use https://github.com/minetest-mods/mg
2. Enable `deprecated_lua_api_handling = log`
3. Force a new chunk to be generated
4. Observe crash

##### Backtrace
<pre>
(gdb) bt
#0  0x00005555558b3f7f in ModApiBase::l_deprecated_function(lua_State*) ()
#1  0x0000555555895db9 in script_exception_wrapper(lua_State*, int (*)(lua_State*)) ()
#2  0x00007ffff64e196c in ?? () from /usr/lib/libluajit-5.1.so.2
#3  0x00007ffff652797c in lua_pcall () from /usr/lib/libluajit-5.1.so.2
#4  0x000055555589abe0 in ScriptApiBase::runCallbacksRaw(int, RunCallbacksMode, char const*) ()
#5  0x000055555589ee94 in ScriptApiEnv::environment_OnGenerated(irr::core::vector3d<short>, irr::core::vector3d<short>, unsigned int) ()
#6  0x00005555559e56ae in EmergeThread::finishGen(irr::core::vector3d<short>, BlockMakeData*, std::map<irr::core::vector3d<short>, MapBlock*, std::less<irr::core::vector3d<short> >, std::allocator<std::pair<irr::core::vector3d<short> const, MapBlock*> > >*) ()
#7  0x00005555559e613c in EmergeThread::run() ()
#8  0x00005555558fff32 in Thread::threadProc(Thread*) ()
#9  0x00007ffff58c5063 in std::execute_native_thread_routine (__p=0x7fffcc0034c0)
    at /build/gcc/src/gcc/libstdc++-v3/src/c++11/thread.cc:80
#10 0x00007ffff61f0a9d in start_thread () from /usr/lib/libpthread.so.0
#11 0x00007ffff559fb23 in clone () from /usr/lib/libc.so.6
</pre>

### PR DESCRIPTION
**Pull request by rubenwardy**
Fixes #8322

This uses a lambda generated by a macro to pass the information into l_deprecated_function. There are cleaner ways to do this (eg: lua_pushcclosure), but they are much more complicated to implement. I think this is less hacky than the current method of checking for duplicates and using a global variable.

Most modders won't know about deprecation warnings or the setting. This PR sets the default to log.

To do:

- [x] Make `l_deprecated_function` respect the setting

### CODE REVIEW

**Comment by SmallJoker** [comment]
FYI: #8322 cannot be fixed and might be the only reason why it's still set to "legacy".

**Comment by rubenwardy** [comment]
"Can't be fixed" is a big statement

**Comment by rubenwardy** [comment]
This uses a lambda generated by a macro to pass the information into `l_deprecated_function`. There are cleaner ways to do this (eg: `lua_pushcclosure`), but they are much more complicated to implement

File: src/script/lua_api/l_base.cpp [hunk 1]
```diff
@@ -100,32 +100,19 @@ bool ModApiBase::registerFunction(lua_State *L, const char *name,
...
 	thread_local std::vector<u64> deprecated_logged;
 
 	u64 start_time = porting::getTimeUs();
 	lua_Debug ar;
 
-	// Get function name for lookup
-	FATAL_ERROR_IF(!lua_getstack(L, 0, &ar), "lua_getstack() failed");
-	FATAL_ERROR_IF(!lua_getinfo(L, "n", &ar), "lua_getinfo() failed");
-
 	// Combine name with line and script backtrace
```
Comment (sfan5) [inline src/script/lua_api/l_base.cpp:112]:
```suggestion
	// Get caller name with line and script backtrace
```

File: src/script/lua_api/l_base.h [hunk 2]
```diff
@@ -75,10 +75,8 @@ class ModApiBase : protected LuaHelper {
 			lua_CFunction func,
 			int top);
 
-	static int l_deprecated_function(lua_State *L);
-	static void markAliasDeprecated(luaL_Reg *reg);
+	static int l_deprecated_function(lua_State *L, const char *good, const char *bad, lua_CFunction func);
 private:
 	// <old_name> = { <new_name>, <new_function> }
```
Comment (sfan5) [inline src/script/lua_api/l_base.h:80]:
```suggestion
```

**Review by SmallJoker — APPROVED** [review]
Works. Sample output, using outdated "mg" mod and custom calls:
```
tity_name (at mods/lab/init_19_deprecated_warning_trigger.lua:7)
2020-10-24 18:42:02: WARNING[Server]: Deprecated call to get_look_pitch, use get_look_vertical instead (at mods/lab/init_19_deprecated_warning_trigger.lua:8)
2020-10-24 18:42:02: WARNING[Server]: Deprecated add_particle call with individual parameters instead of definition (at mods/lab/init_19_deprecated_warning_trigger.lua:18)
2020-10-24 18:42:02: WARNING[Emerge-0]: Call to deprecated function 'get_2d_map_flat', please use 'get2dMap_flat' at mods/mg/init.lua:402
2020-10-24 18:42:02: WARNING[Emerge-0]: Call to deprecated function 'get_2d_map_flat', please use 'get2dMap_flat' at mods/mg/init.lua:403
2020-10-24 18:42:02: WARNING[Emerge-0]: Call to deprecated function 'get_2d_map_flat', please use 'get2dMap_flat' at mods/mg/init.lua:404
2020-10-24 18:42:02: WARNING[Emerge-0]: Call to deprecated function 'get_2d_map_flat', please use 'get2dMap_flat' at mods/mg/init.lua:405
```

File: src/script/lua_api/l_internal.h [hunk 3]
```diff
@@ -29,7 +29,20 @@ with this program; if not, write to the Free Software Foundation, Inc.,
...
+			return l_deprecated_function(L, #bad, #good, &class::l_##good); \
+		}}
+
+#define luamethod_aliased(class, name, alias) \
+		{#name, class::l_##name},             \
+		luamethod_dep(class, name, alias)
+
+#define luamethod_aliased2(class, name, alias1, alias2) \
+		luamethod_aliased(class, name, alias1),         \
+		luamethod_dep(class, name, alias2)
```
Comment (sfan5) [inline src/script/lua_api/l_internal.h:44]: I don't think this is better than just manually inserting another entry for `luamethod_dep(...)`

File: src/script/common/c_internal.cpp [hunk 4]
```diff
@@ -155,24 +155,28 @@ static void script_log(lua_State *L, const std::string &message,
 		infostream << script_get_backtrace(L) << std::endl;
 }
 
-void log_deprecated(lua_State *L, const std::string &message, int stack_depth)
-{
+DeprecatedHandlingMode getDeprecatedLuaAPIHandlingMode() {
 	static thread_local bool configured = false;
-	static thread_local bool do_log = false;
-	static thread_local bool do_error = false;
+	static thread_local DeprecatedHandlingMode ret = DeprecatedHandlingMode::Ignore;
```
Comment (rubenwardy) [inline src/script/common/c_internal.cpp:160]: I copied this from existing code, but I feel like it's premature optimisation

File: src/script/common/c_internal.cpp [hunk 5]
```diff
@@ -155,24 +155,28 @@ static void script_log(lua_State *L, const std::string &message,
 		infostream << script_get_backtrace(L) << std::endl;
 }
 
-void log_deprecated(lua_State *L, const std::string &message, int stack_depth)
-{
+DeprecatedHandlingMode getDeprecatedLuaAPIHandlingMode() {
```
Comment (sfan5) [inline src/script/common/c_internal.cpp:158]: brace needs to be on following line
also global functions need to be snake case

Comment (rubenwardy) [reply src/script/common/c_internal.cpp:158]: Our code style is so incredibly arbitrary

File: src/script/common/c_internal.cpp (hunk 4 above)
Comment (SmallJoker) [reply src/script/common/c_internal.cpp:161]: I don't see any improvement by doing this change. At least the code still works.

File: src/script/lua_api/l_base.cpp [hunk 6]
```diff
@@ -100,32 +100,21 @@ bool ModApiBase::registerFunction(lua_State *L, const char *name,
...
 
-std::unordered_map<std::string, luaL_Reg> ModApiBase::m_deprecated_wrappers;
-bool ModApiBase::m_error_deprecated_calls = false;
-
-int ModApiBase::l_deprecated_function(lua_State *L)
+int ModApiBase::l_deprecated_function(lua_State *L, const char *good, const char *bad, lua_CFunction func)
 {
 	thread_local std::vector<u64> deprecated_logged;
 
+	DeprecatedHandlingMode deprecatedHandlingMode = get_deprecated_handling_node();
```
Comment (SmallJoker) [inline src/script/lua_api/l_base.cpp:107]: thisIsNotAFunction, please use snake case

File: src/script/common/c_internal.cpp [hunk 7]
```diff
@@ -155,24 +155,29 @@ static void script_log(lua_State *L, const std::string &message,
 		infostream << script_get_backtrace(L) << std::endl;
 }
 
-void log_deprecated(lua_State *L, const std::string &message, int stack_depth)
+DeprecatedHandlingMode get_deprecated_handling_node()
```
Comment (ShadowNinja) [inline src/script/common/c_internal.cpp:158]: Typo: node -> mode

**Comment by SmallJoker** [comment]
:+1: Looks good.

File: builtin/settingtypes.txt [hunk 8]
```diff
@@ -1220,10 +1220,10 @@ movement_gravity (Gravity) float 9.81
 [**Advanced]
 
 #    Handling for deprecated Lua API calls:
-#    -    legacy: (try to) mimic old behaviour (default for release).
-#    -    log: mimic and log backtrace of deprecated call (default for debug).
+#    -    none: Ignore deprecations
```
Comment (sfan5) [inline builtin/settingtypes.txt:1223]:
```suggestion
#    -    none: Do not log deprecated calls
```

**Comment by sfan5** [comment]
LGTM
