### PR TITLE
Fix formspec focus

### LINKED ISSUE #12784: Fields don't get initial focus in formspec if any button has an empty name
##### Minetest version

```
5.6.0
```

##### OS / Hardware

Operating system: Linux
CPU: N/A

GPU model: N/A
OpenGL version: N/A

##### Summary

If a button with an empty name exists in a formspec, it always gets focus, even if empty fields exist in the formspec (which are supposed to take priority).

I've tried to debug this myself. If the button has a name, getChildren returns 4 elements when [`setInitialFocus()`](https://github.com/minetest/minetest/blob/9acf2d3db7fe006dc47e3323003c5ef97e8f2f3e/src/gui/guiFormSpecMenu.cpp#L187) is called and the field is correctly focused.

When the formspec with the empty button name is opened, only one element is returned by getChildren() called and it falls back to focusing the first element. I measured the amount of children by adding `std::cout << "Children: " << children.size() << std::endl;` after the loop to remove null values. Maybe getChildren() is only returning the child elements of the button and not the entire formspec for some reason?

##### Steps to reproduce

Run the following chatcommand with WorldEdit installed and observe how the field is focused:
```lua
//lua minetest.show_formspec('singleplayer', 'fs', 'formspec_version[3]size[3,3]button[0,0;3,1;test;Test]field[0,1.5;3,0.8;test;Test;]')
```

Now remove the button's name from the formspec and observe how the button is focused instead:
```lua
//lua minetest.show_formspec('singleplayer', 'fs', 'formspec_version[3]size[3,3]button[0,0;3,1;;Test]field[0,1.5;3,0.8;test;Test;]')
```

The order of the button and field doesn't seem to matter.

### PR DESCRIPTION
**Pull request by Desour**
- Fixes #12784.
- The comparison operators for `Optional` should match those of C++17 `std::optional`.

## To do

This PR is a Ready for Review.

Don't squash.

## How to test

Try to reproduce #12784.

### CODE REVIEW

File: src/gui/guiFormSpecMenu.h [hunk 1]
```diff
@@ -352,13 +353,13 @@ class GUIFormSpecMenu : public GUIModalMenu
...
-	std::string         m_last_formname;
-	u16                 m_formspec_version = 1;
-	std::string         m_focused_element = "";
-	JoystickController *m_joystick;
-	bool m_show_debug = false;
+	IFormSource          *m_form_src;
+	TextDest             *m_text_dst;
+	std::string           m_last_formname;
+	u16                   m_formspec_version = 1;
+	Optional<std::string> m_focused_element = nullopt;
```
Comment (TurkeyMcMac) [inline src/gui/guiFormSpecMenu.h:360]: I've barely touched formspecs, but is `set_focus[]` supposed to reset the focus to nothing, as opposed to the element with an empty name? If so, this might break that, no?

Comment (Desour) [reply src/gui/guiFormSpecMenu.h:360]: According to doc, `set_focus[]` is no special case. So it's supposed to set focus to an element with empty name (if existent).
This should be fine.

(The formspec syntax doesn't differentiate "no arguments" `()` and "one argument with empty string" `(ε,)`).

(Btw. AFAIK there's no reason to have more than one `set_focus` element in a formspec.)

**Review by TurkeyMcMac — APPROVED** [review]
LGTM

**Review by SmallJoker — APPROVED** [review]
A minimal (kinda hacky) alternative solution would be to use a control character (`\x1b`) or other reserved string as reset value. This however seems to be a more professional solution. LGTM.

**Comment by rubenwardy** [comment]
Please wait

**Comment by rubenwardy** [comment]
So, my concern with this is that I'd expect an empty name to be interpreted as no name. This makes sense given how textareas become readonly with no name. With this PR you can still set_focus to empty name, and that's distinct from no name

So my question is - would others consider this more consistent, and would empty=no name break anything?

**Comment by sfan5** [comment]
What's the status here?

**Comment by Desour** [comment]
@rubenwardy expressed concerns (used veto or so).

We could redefine `set_focus[]` to set focus to no element (currently it's focus to element with empty name). This PR currently doesn't touch functionality in this regard.
The PR only changes behaviour if no `set_focus` element is used (default is nothing, not `""`).

No matter what is done, a break is extremely unlikely or only very soft (someone would have to use `set_focus[]` with empty name and rely on an element with empty name to be focused).

Anyway, looking more into it, for consistency the semantics of a `set_focus[]` (that sets the element-to-focus to `nullopt`) would be such that it won't work anymore if you place it after the element with the name, examples:
```
set_focus[foo]
set_focus[]  <- undoes earlier set_focus
element[foo]

set_focus[foo]
element[foo]
element[foo] <- will be focused
set_focus[]  <- useless

set_focus[foo]
element[foo] <- will be focused
set_focus[]
element[foo]
```
This is not too useful.

**Comment by rubenwardy** [comment]
> I doubt it's worth wasting much time to think about this minor detail.

This minor detail relates to the API, which is worth making consistent

I'm fine to go ahead with this though

**Comment by Desour** [comment]
Wouldn't have to be squashed btw.. I'll try to make bigger nosquash signs in the future.
