### PR TITLE
Replace fallback font nonsense with automatic per-glyph fallback

### LINKED ISSUE #9198: Display CJK characters correctly in non-fallback languages
## Problem

cannot display CJK characters

## Solutions

use another font?

## Additional context

(partially) fix https://github.com/minetest/minetest/issues/4638

### LINKED ISSUE #10634: Chinese cannot be entered or displayed in chat console
##### Minetest version

Minetest v5.4.0

##### OS / Hardware

Operating system: centos8

CPU: 2

##### Summary

Chinese cannot be entered or displayed in chat

##### Steps to reproduce

Chinese cannot be entered or displayed in chat

### PR DESCRIPTION
**Pull request by sfan5**
Switching the font depending on the users language is fundamentally flawed, you do obviously want to be able to display Chinese text for Russian users and vice-versa.
Hence this PR implements what any sane font engine should do: it transparently falls back to other font(s) when it encounters a glyph that wasn't found.

fixes #10634, fixes #9198

## To do

This PR is a Ready for Review.

## How to test

1. Test various locales that used to have fallback font disabled (`de`, `ru`, ...) and ones that used to have it enabled (`zh_CN`, `ja`, `ko`, `kk`, ...).
Text should still show up everywhere as usual.
2. Use this test mod and verify that 1) rendering is correct in chat console & "normal" chat and 2) coloring is correct
```lua
core.register_chatcommand("foo", {
	func = function()
		local function u8iter(s, f)
			local i, i2 = 1, 1
			while i <= #s do
				local c = s:sub(i,i); i = i + 1
				while (s:byte(i) or 0) >= 128 and s:byte(i) < 192 do
					c = c .. s:sub(i,i); i = i + 1
				end
				f(i2, c); i2 = i2 + 1
			end
		end

		local colors = {"#f55", "#5f5", "#55f"}
		local s = "foo_bar a我b都c我d都e我f都g我h都i我0都9我_都-我 我都我 foo_bar"
		local r = ""
		u8iter(s, function(n, char)
			r = r .. core.colorize(colors[(n-1) % #colors + 1], char)
		end)
		return true, r
	end
})
```
3. When there is text with mixed fonts (use chinese or japanese to test this), ensure that alignment and kerning is correct and consistent.

### CODE REVIEW

**Comment by rubenwardy** [comment]
Thanks for this, it's something I've been wanting to look into for a while

**Comment by Wuzzy2** [comment]
The test mod works both in chat and when I press F10. I tested in `de` and `ja`. I did not test kerning with mixed font (I don't speak those other languages, so I can't review).

I noticed a problem when inserting a character that is *not* supported by the fallback font. This character will disappear completely; it is invisible.
For example, if you use U+1F6F8 FLYING SAUCER 🛸

As far I understand, you are supposed to print a replacement character in case of a missing glyph.

**Comment by sfan5** [comment]
That's not a regression and it's a bit tricky fixing this with the current code so I'll choose not to.

File: src/client/fontengine.cpp [hunk 1]
```diff
@@ -271,18 +271,8 @@ gui::IGUIFont *FontEngine::initFont(const FontSpec &spec)
...
-			setting_prefix = "fallback_";
-			break;
-		case FM_Mono:
-		case FM_SimpleMono:
-			setting_prefix = "mono_";
-			break;
-		default:
-			break;
-	}
+	if (spec.mode == FM_Mono)
```
Comment (SmallJoker) [inline src/client/fontengine.cpp:274]: What happened to "SimpleMono"?

**Review by SmallJoker — COMMENTED** [review]
Tested, Hypertext formatting still works, and the characters are displayed and colorized correctly.

File: src/client/fontengine.cpp (hunk 1 above)
Comment (sfan5) [reply src/client/fontengine.cpp:274]: That never reaches this method, `initSimpleFont` is called instead.
