### PR TITLE
Disable default password check in single player

### LINKED ISSUE #14457: Setting a default_password will lock singleplayer out of new worlds
First reported by Dear_Roman in ["Singlemode specific"](https://forum.minetest.net/viewtopic.php?p=434111#p434111) on the forums.

### Minetest version

```true
Minetest 5.9.0-dev-d88f0866b (Linux)
Using Irrlicht 1.9.0mt15
Using LuaJIT 2.1.0-beta3
Built by GCC 12.2
Running on Linux/6.1.0-18-amd64 x86_64
BUILD_TYPE=Release
RUN_IN_PLACE=0
USE_CURL=1
USE_GETTEXT=1
USE_SOUND=1
STATIC_SHAREDIR="/usr/local/share/minetest"
STATIC_LOCALEDIR="/usr/local/share/locale"
```

### Irrlicht device

X11

### Operating system and version

Debian 12.5 "Bookworm"

### Summary

If the setting `default_password`, intended for multiplayer, is set, then launching new worlds as `singleplayer` will fail, because launching in singleplayer never asks for a password, even though one is required when using the `default_password` setting.

Singleplayer isn't allowed as a name when running in multiplayer, so the password can't be provided there. And there is no way to require a password of the user when launching singleplayer anyway. The only solution is to unset the default_password setting.

### Steps to reproduce

Open the settings menu.
1. Search for "password" and navigate to the Client and Server -> Server Security section
2. Set a value for the setting "default password".
3. Return to the "Start Game" menu
4. Create a new world
5. Launch the world in singleplayer mode. You get the error "Access denied. Reason: Invalid Password". The OK button returns to the main menu.

### Solution
Singleplayer mode should probably just never require a password, even when `default_password` is set.

### PR DESCRIPTION
**Pull request by src-tinkerer**
Add compact, short information about your PR for easier understanding:

If a default password is provided, the game would try to auth in single player even though single player worlds have no passwords. We basically tell it to not auth if it's single player and a default password is provided.
Fixes #14457

## To do

This PR is Ready for Review.

## How to test

Provide a default password and create a world in single player and join. Should work.

### CODE REVIEW

**Comment by src-tinkerer** [comment]
I think I checked in the wrong place? xD
It should be on the if condition?

File: src/network/serverpackethandler.cpp [hunk 1]
```diff
@@ -261,7 +261,7 @@ void Server::handleCommand_Init(NetworkPacket* pkt)
 		}
 	} else {
```
Comment (src-tinkerer) [inline src/network/serverpackethandler.cpp:262]: It's better if we check if it's not single player here right?

**Review by rubenwardy — APPROVED** [review]
Tested, confirmed this works

There's on other place that `default_password` is used - inside set_privileges at builtin/game/auth.lua:78. I don't think this matters though as this only happens if setting the priv for another player that isn't single player
