### PR TITLE
Fix warnings about dungeongen.cpp memcpy() and unused variable in MapBlock::deSerializeNetworkSpecific()

### LINKED ISSUE #8117: Warning about `struct DungeonParams` when building Minetest (mapgen/mapgen.cpp.o)
##### Issue type

 - Build issue

##### Minetest version

Latest master/head (df6670b28a2f4e1f6094b617a25792a70400b66d as of writing this)

##### OS / Hardware

Operating system: Linux 4.20.3-arch1-1-ARCH x86_64
cmake version 3.13.2

##### Summary
The following warning and note appear during build.

```
[ 40%] Building CXX object src/CMakeFiles/minetest.dir/mapgen/mapgen.cpp.o
/home/dirk/mt5/minetest/src/mapgen/dungeongen.cpp: In constructor 'DungeonGen::DungeonGen(const NodeDefManager*, GenerateNotifier*, DungeonParams*)':
/home/dirk/mt5/minetest/src/mapgen/dungeongen.cpp:54:34: warning: 'void* memcpy(void*, const void*, size_t)' writing to an object of type 'struct DungeonParams' with no trivial copy-assignment; use copy-assignment or copy-initialization instead [-Wclass-memaccess]
   memcpy(&dp, dparams, sizeof(dp));
                                  ^
In file included from /home/dirk/mt5/minetest/src/mapgen/dungeongen.cpp:21:
/home/dirk/mt5/minetest/src/mapgen/dungeongen.h:41:8: note: 'struct DungeonParams' declared here
 struct DungeonParams {
        ^~~~~~~~~~~~~
```

##### Steps to reproduce

Create directory to work in and du a clean build as per instructions.
```
mkdir mt5 ; cd mt5
git clone --depth 1 https://github.com/minetest/minetest.git
cd minetest
git clone --depth 1 https://github.com/minetest/minetest_game.git games/minetest_game
cmake . -DRUN_IN_PLACE=TRUE
make -j 8
```

### LINKED ISSUE #8121: Build warning (unused variable)
At commit f4099192e398d38fede20efdc9985f768ab87da5

/minetest/src/mapblock.cpp: In member function ‘void MapBlock::deSerializeNetworkSpecific(std::istream&)’:
/minetest/src/mapblock.cpp:560:12: warning: unused variable ‘version’ [-Wunused-variable]
   const u8 version = readU8(is);

Will fix.

### PR DESCRIPTION
**Pull request by paramat**
Fix warning about dungeongen.cpp memcpy()

Closes #8117 
Change was suggested by sfan5.
Dungeons tested and ok.
////////////////////////

2nd commit:
Fix unused variable in MapBlock::deSerializeNetworkSpecific()

Closes #8121 
Use 'version' variable while keeping conditional non-functional.
////////////////////////

3rd commit:
Fix unused variable a simpler way

### CODE REVIEW

File: src/mapblock.cpp [hunk 1]
```diff
@@ -558,8 +558,9 @@ void MapBlock::deSerializeNetworkSpecific(std::istream &is)
 {
 	try {
 		const u8 version = readU8(is);
-		//if(version != 1)
-		//	throw SerializationError("unsupported MapBlock version");
+		if (version != 1) {
```
Comment (nerzhul) [inline src/mapblock.cpp]: noop this should not be enabled

File: src/mapgen/dungeongen.cpp [hunk 2]
```diff
@@ -51,7 +51,7 @@ DungeonGen::DungeonGen(const NodeDefManager *ndef,
 #endif
 
 	if (dparams) {
-		memcpy(&dp, dparams, sizeof(dp));
+		dp = *dparams;
```
Comment (nerzhul) [inline src/mapgen/dungeongen.cpp]: memcpy is necessary here. which warning do you want to fix ?

Comment (rubenwardy) [reply src/mapgen/dungeongen.cpp]: the warning is that there is a non trivial copy constructor for this class

File: src/mapblock.cpp (hunk 1 above)
Comment (paramat) [reply src/mapblock.cpp]: ? 'version' has to be used, as it was before bba4563d89b6708d75a4053c69873dff0d747538
What is your code suggestion? Maybe there's another way.

Comment (paramat) [reply src/mapblock.cpp]: Oh, just:
`readU8(is);`
?

Comment (paramat) [reply src/mapblock.cpp]: Ok will do.

Comment (paramat) [reply src/mapblock.cpp]: Done.

**Comment by paramat** [comment]
Updated as requested (i hope). Compiles and seems to run ok.
