### PR TITLE
Clamp player wieldindex when processing hotbar item selection

### LINKED ISSUE #11921: Reducing the hotbar size to something lower than the current selected slot doesn't bring you back to one of those still present
##### Minetest version

```
5.4.2 | 5.5.0-dev (e030d9c, latest)
```

##### Summary
If you have an hotbar slot selected (let's say n°8) and then you reduce the hotbar item count to something that is lower (let's say 5), your hand will still point to slot n°8, that is now out of bounds. This doesn't allow you to do some actions, like opening a chest, interacting with a `signs_lib` sign etc., and every click generates this in the log:
`ACTION[Server]: Player: singleplayer tried to access item=8 out of hotbar_itemcount=5; ignoring.`

It'd be best to automatically select either the biggest of the lowest slot still present in the hotbar, also because it's not something you notice that easily. In fact, I spent an hour debugging and backtracking with a friend the other day, thinking that my mod had broken the game somehow.  
Another case is this minigame called [Sumo](https://content.minetest.net/packages/MisterE/sumo/) that reduces your hotbar to 1, giving you a stick to push people around. If you were on another slot before entering the match, you have to manually select the first slot or you won't be able to play (because you need the stick)

##### Steps to reproduce
```lua
minetest.register_on_joinplayer(function(player)

    player:hud_set_hotbar_itemcount(10)
    
    -- now manually go on the 10th slot and wait
    
    minetest.after(3, function()
        player:hud_set_hotbar_itemcount(8)
    end)

    -- now you're out of bounds

end)
```

### PR DESCRIPTION
**Pull request by iliekprogrammar**
Fixes #11921. Now player wieldindex is shifted to highest index after resizing.

### CODE REVIEW

File: src/client/game.cpp [hunk 1]
```diff
@@ -2140,6 +2139,10 @@ void Game::processItemSelection(u16 *new_playeritem)
 			break;
 		}
 	}
+
+	/* Clamp item selection
+	 */
+	*new_playeritem = std::min(*new_playeritem, (u16)(player->hud_hotbar_itemcount - 1));
```
Comment (TurkeyMcMac) [inline src/client/game.cpp:2145]:
```suggestion
	*new_playeritem = MYMIN(*new_playeritem, max_item);
```

File: src/client/game.cpp [hunk 2]
```diff
@@ -2140,6 +2139,10 @@ void Game::processItemSelection(u16 *new_playeritem)
 			break;
 		}
 	}
+
+	/* Clamp item selection
+	 */
```
Comment (sfan5) [inline src/client/game.cpp:2144]:
```suggestion
	// Clamp selection again in case it wasn't changed but max_item was
```

**Review by sfan5 — APPROVED** [review]

**Review by TurkeyMcMac — APPROVED** [review]
