### PR TITLE
[NO SQUASH] Fix narrow/wide and UTF-16 mess

### LINKED ISSUE #7643: send_chat_message truncates 4 byte utf8 strings (codepoints > 0xFFFF)
##### Minetest version

```
0.4.17.1
```

##### Summary
send_chat_message truncates 4 byte utf8 strings (codepoints > 0xFFFF)

##### Steps to reproduce

Client side mod lua script:
```lua
-- command .dummy
minetest.register_chatcommand("dummy", {
	params = "<arg>",
	description = "Dummy function",
	func = function(param)
		local message = "[\xF0\xA0\x80\x8B]" -- [𠀋] \U0002000B
		minetest.log(message) -- works:  visible in debug.txt
		minetest.display_chat_message(message) -- works: visible in game
		minetest.send_chat_message(message) -- doesn't work: truncated to 0x000B
		
	end
})
```

Note: Sorry, if this is already fixed or duplicate. I couldn't find a relevant issue.

### PR DESCRIPTION
**Pull request by sfan5**
go read the commit descriptions

fixes #7643

## To do

This PR is a Ready for Review.

## How to test

Join a Minetest server and enter your favorite non-ASCII codepoints in chat.

### CODE REVIEW

File: src/util/string.cpp [hunk 1]
```diff
@@ -77,70 +76,65 @@ bool convert(const char *to, const char *from, char *outbuf,
...
 {
-	size_t inbuf_size = input.length() + 1;
+	const size_t inbuf_size = input.length();
 	// maximum possible size, every character is sizeof(wchar_t) bytes
-	size_t outbuf_size = (input.length() + 1) * sizeof(wchar_t);
+	size_t outbuf_size = input.length() * sizeof(wchar_t);
 
-	char *inbuf = new char[inbuf_size];
+	char *inbuf = new char[inbuf_size]; // intentionally NOT null-terminated
 	memcpy(inbuf, input.c_str(), inbuf_size);
```
Comment (numberZero) [inline src/util/string.cpp:97]: Why making a copy?

File: src/util/string.cpp [hunk 2]
```diff
@@ -77,70 +76,65 @@ bool convert(const char *to, const char *from, char *outbuf,
...
-	size_t inbuf_size = (input.length() + 1) * sizeof(wchar_t);
-	// maximum possible size: utf-8 encodes codepoints using 1 up to 6 bytes
-	size_t outbuf_size = (input.length() + 1) * 6;
+	const size_t inbuf_size = input.length() * sizeof(wchar_t);
+	// maximum possible size: utf-8 encodes codepoints using 1 up to 4 bytes
+	size_t outbuf_size = input.length() * 4;
 
-	char *inbuf = new char[inbuf_size];
+	char *inbuf = new char[inbuf_size]; // intentionally NOT null-terminated
 	memcpy(inbuf, input.c_str(), inbuf_size);
```
Comment (numberZero) [inline src/util/string.cpp:125]: here too, why copying?

File: src/util/string.cpp [hunk 3]
```diff
@@ -172,16 +166,13 @@ std::string wide_to_utf8(const std::wstring &input)
...
 	std::wstring ret = utf8_to_wide(std::string(str));
-	size_t len = ret.length();
-	wchar_t *ret_c = new wchar_t[len + 1];
-	memset(ret_c, 0, (len + 1) * sizeof(wchar_t));
-	memcpy(ret_c, ret.c_str(), len * sizeof(wchar_t));
-	return ret_c;
+	size_t buf_size = (ret.length() + 1) * sizeof(wchar_t);
+	u8 *ret_c = new u8[buf_size];
+	memcpy(ret_c, ret.c_str(), buf_size);
+	return reinterpret_cast<wchar_t*>(ret_c);
```
Comment (numberZero) [inline src/util/string.cpp:175]: UB, `u8` is not `wchar_t`. (technically, the UB is not here but at usage and deletion points IIUC)

Comment (sfan5) [reply src/util/string.cpp:175]: `delete[]` is type-specific?

File: src/util/string.cpp (hunk 1 above)
Comment (sfan5) [reply src/util/string.cpp:97]: iconv only takes a mutable input buffer...

File: src/util/string.cpp (hunk 3 above)
Comment (numberZero) [reply src/util/string.cpp:175]: > For the second (array) form, expression must be a null pointer value or a pointer value previously obtained by an array form of new-expression.

`reinterpret_cast` is not `new[]` and is not required to preserve pointer value (which is not simply an address, for whatever language lawying reasons), so I suppose yes.

Anyway, why not doing it the simpler way? Like:
```c++
wchar_t *ret_c = new wchar_t[ret.length() + 1];
memcpy(ret_c, ret.c_str(), (ret.length() + 1) * sizeof(wchar_t)); // copying including NUL terminator
return ret_c;
```
or
```c++
wchar_t *ret_c = new wchar_t[ret.length() + 1];
memcpy(ret_c, ret.data(), ret.length() * sizeof(wchar_t));
ret_c[ret.length()] = L'\0';
return ret_c;
```

Comment (sfan5) [reply src/util/string.cpp:175]: Meh, I'll just switch it back to the old way.

File: src/util/string.cpp (hunk 1 above)
Comment (numberZero) [reply src/util/string.cpp:97]: It takes a `char **` but only reads buffer contents, so `const_cast<char *>` should be fine here. It does change the pointer itself though (thus couldn’t take `char const* const*`).

File: src/util/string.cpp (hunk 2 above)
Comment (numberZero) [reply src/util/string.cpp:125]: also, just found this (`man 3 iconv`):

>The caller of iconv() must ensure that the pointers passed to the       function are suitable for accessing characters in the appropriate       character set.  **This includes ensuring correct alignment on platforms       that have tight restrictions on alignment.**

File: src/util/string.cpp (hunk 1 above)
Comment (sfan5) [reply src/util/string.cpp:97]: Shouldn't it be taking a `const char **inbuf` then?

> but only reads buffer contents

I'm sure it does but the issue is that I don't see this guaranteed by the types or documentation.

File: src/util/string.cpp (hunk 2 above)
Comment (sfan5) [reply src/util/string.cpp:125]: Ugh. I'm inclined to just ignore that because *every* malloc implementation will align to some `N >= 4 = max(sizeof(wchar_t))`.

File: src/util/string.cpp (hunk 1 above)
Comment (numberZero) [reply src/util/string.cpp:97]: > Shouldn't it be taking a const char **inbuf then?

It wouldn’t be able to take `char **` then, there is no implicit conversion (even in C++; in C, rules are stricter so even `char **`→`char const* const*` requires a cast).

File: src/util/string.cpp (hunk 2 above)
Comment (numberZero) [reply src/util/string.cpp:125]: heh, `malloc` is *required* to align the buffer (to max of requirement of builtin types). yet `new` is not required to use `malloc`...

**Comment by numberZero** [comment]
@sfan5 feel free to ignore my last comments, these problems aren’t introduced by this PR so I don’t want to hold it from merge

File: src/network/networkpacket.cpp [hunk 4]
```diff
@@ -160,9 +162,16 @@ NetworkPacket& NetworkPacket::operator>>(std::wstring& dst)
...
-		wchar_t c16 = readU16(&m_data[m_read_offset]);
-		dst.append(&c16, 1);
+	for (u16 i = 0; i < strLen; i++) {
+		wchar_t c = readU16(&m_data[m_read_offset]);
+		if (NEED_SURROGATE_CODING && c >= 0xD800 && c < 0xDC00 && i+1 < strLen) {
+			i++;
+			m_read_offset += sizeof(u16);
+
+			wchar_t c2 = readU16(&m_data[m_read_offset]);
+			c = 0x10000 + ((c & 0x3ff) << 10) | (c2 & 0x3ff);
```
Comment (SmallJoker) [inline src/network/networkpacket.cpp:172]: Does it work as intended?
```
warning: suggest parentheses around arithmetic in operand of ‘|’ [-Wparentheses]
  172 |    c = 0x10000 + ((c & 0x3ff) << 10) | (c2 & 0x3ff);
```

**Comment by SmallJoker** [comment]
Successfully tested (same machine)

 * Old client <--> new server chat messages and "invalid command" messages
 * New client <--> old server chat messages and "invalid command" messages

The unittests pass too. Looks good aside the comment above to clarify.

File: src/network/networkpacket.cpp (hunk 4 above)
Comment (numberZero) [reply src/network/networkpacket.cpp:172]: don’t remember the precedence but it should work either way IIUC

Comment (sfan5) [reply src/network/networkpacket.cpp:172]: This supposed to be `0x10000 + ( ((c & 0x3ff) << 10) | (c2 & 0x3ff) );`, will change.

**Review by SmallJoker — APPROVED** [review]
