### PR TITLE
Remove sound menu and show proper messages if trying to change sound volume when sound if disabled/unsupported

### LINKED ISSUE #9004: Incorrect GUI / messages when sound system is disabled
##### Minetest version
```
5.1.0-RC1
```

##### Summary
If sounds are disabled via `enable_sound=false`, the in-game GUI is incorrect:

- The in-game sound change dialog is still available although it's pointless and does nothing
- If you press the volume up/down or mute key in-game, you get messages as if you enabled the sound or changed the volume. But nothing changes actually because the sound is disabled

##### How it should be like
If sounds are disabled, then:

- Remove the sound menu in the in-game Esc menu
- Display “Sound system is disabled” when pressing the volume up/down or mute key

Is this still possible to do for 5.1.0 before strings are frozen?

### PR DESCRIPTION
**Pull request by Wuzzy2**
Fixes #9004.

## To do

Ready to test.

### Part 1

* Compile Minetest with sound support
* Set `enable_sound=false`
* In-game, open the Esc menu. The sound menu must have disappeared
* In-game, use the volume up/down/mute keys. Message “Sound system is disabled” must appear
* Set `enable_sound=true`
* Repeat the steps. Sound must work like before again

### Part 2

* Compile Minetest without sound support
* In-game, open the Esc menu. The sound menu must have disappeared
* In-game, use the volume up/down/mute keys. Message “Sounds are not supported” must appear

### CODE REVIEW

**Comment by Wuzzy2** [comment]
Bump after 5-6 months.

File: src/client/game.cpp [hunk 1]
```diff
@@ -1903,29 +1903,46 @@ void Game::processKeyInput()
...
+			const wchar_t *str = wgettext("Volume changed to %d%%");
+			swprintf(buf, sizeof(buf) / sizeof(wchar_t), str, myround(new_volume * 100));
+			delete[] str;
+			m_game_ui->showStatusText(buf);
+		} else {
+			m_game_ui->showTranslatedStatusText("Sound system is disabled");
+		}
+#else
+	} else if (wasKeyDown(KeyType::MUTE) || wasKeyDown(KeyType::INC_VOLUME) || wasKeyDown(KeyType::DEC_VOLUME)) {
+		m_game_ui->showTranslatedStatusText("Sounds are not supported");
```
Comment (nerzhul) [inline src/client/game.cpp:1944]: `Sound system not supported on this build` sounds better to me

**Comment by nerzhul** [comment]
only a minor comment, sounds lgtm

**Comment by Wuzzy2** [comment]
Done.

File: src/client/game.cpp [hunk 2]
```diff
@@ -1903,29 +1903,46 @@ void Game::processKeyInput()
...
+			g_settings->setFloat("sound_volume", new_volume);
+			const wchar_t *str = wgettext("Volume changed to %d%%");
+			swprintf(buf, sizeof(buf) / sizeof(wchar_t), str, myround(new_volume * 100));
+			delete[] str;
+			m_game_ui->showStatusText(buf);
+		} else {
+			m_game_ui->showTranslatedStatusText("Sound system is disabled");
+		}
+#else
+	} else if (wasKeyDown(KeyType::MUTE) || wasKeyDown(KeyType::INC_VOLUME) || wasKeyDown(KeyType::DEC_VOLUME)) {
```
Comment (SmallJoker) [inline src/client/game.cpp:1943]: Line too long, please break it.

File: src/client/game.cpp [hunk 3]
```diff
@@ -1903,29 +1903,46 @@ void Game::processKeyInput()
...
+		m_game_ui->showTranslatedStatusText("Sound system not supported on this build");
```
Comment (SmallJoker) [inline src/client/game.cpp:1944]:
```suggestion
		m_game_ui->showTranslatedStatusText("Sound system is not supported on this build");
```
To keep consistency with `"Sound system is disabled"`.

File: src/client/game.cpp [hunk 4]
```diff
@@ -4089,8 +4106,12 @@ void Game::showPauseMenu()
 	}
 
 #ifndef __ANDROID__
-	os		<< "button_exit[4," << (ypos++) << ";3,0.5;btn_sound;"
-		<< strgettext("Sound Volume") << "]";
+#if USE_SOUND
+	if (g_settings->getBool("enable_sound")) {
+		os		<< "button_exit[4," << (ypos++) << ";3,0.5;btn_sound;"
```
Comment (SmallJoker) [inline src/client/game.cpp:4111]: Line touched.
```suggestion
		os << "button_exit[4," << (ypos++) << ";3,0.5;btn_sound;"
```

**Comment by Wuzzy2** [comment]
Done.
