### PR TITLE
Fix wrong reported item counts for inventory actions caused by move somewhere

### LINKED ISSUE #10805: Shift-clicking reports the wrong number of items to callbacks
##### Minetest version
```
5.3.0 and 5.4.0-dev-4b0128282 (and older versions too AFAIK)
```

##### OS / Hardware
Operating system: Windows 10 64-bit
CPU: Intel Core 2 Duo

##### Summary
When shift-clicking items to or from a node inventory, the total number of items reported to the `allow/on_metadata_inventory_put/take` callbacks doesn't match the actual number of items put or taken.

For example, if you have a stack of 90 items in a chest, and 50 in your inventory, and shift-click the items from the chest, the callbacks are called as follows:
```
allow_metadata_inventory_take - 90 items
on_metadata_inventory_take - 90 items
allow_metadata_inventory_take - 41 items
on_metadata_inventory_take - 41 items
```
Which totals 131 items taken, not the 90 that was actually taken.

##### Steps to reproduce
* Create a mod with this code, and place the node into the world:
```lua
minetest.register_node("test:inventory", {
	description = "Inventory tester",
	tiles = {"default_gold_block.png"},
	groups = {oddly_breakable_by_hand = 1},
	on_construct = function(pos)
		local meta = minetest.get_meta(pos)
		meta:set_string("formspec", "size[8,9]list[context;main;0,0;8,4;]list[current_player;main;0,5;8,4;]listring[]")
		meta:get_inventory():set_size("main", 32)
	end,
	allow_metadata_inventory_put = function(pos, listname, index, stack, player)
		minetest.chat_send_all("Allow put: "..stack:get_count())
		return stack:get_count()
	end,
	allow_metadata_inventory_take = function(pos, listname, index, stack, player)
		minetest.chat_send_all("Allow take: "..stack:get_count())
		return stack:get_count()
	end,
	on_metadata_inventory_put = function(pos, listname, index, stack, player)
		minetest.chat_send_all("Put: "..stack:get_count())
	end,
	on_metadata_inventory_take = function(pos, listname, index, stack, player)
		minetest.chat_send_all("Take: "..stack:get_count())
	end,
})
```
* Put a full stack of items into the node's inventory, and a partial stack of items in your own inventory.
* Shift-click the items from the node into your inventory.
* The total number of taken items reported will not equal the number actually taken.

**Note:** not a duplicate of #7239

### PR DESCRIPTION
**Pull request by appgurueu**
Partially closes #10805

## To do

- [x] Fix underflow
- [x] Thorough testing

## How to test

The devtest chest has been modified to output counts in chat.

### CODE REVIEW

File: src/inventorymanager.cpp [hunk 1]
```diff
@@ -384,9 +385,11 @@ void IMoveAction::apply(InventoryManager *mgr, ServerActiveObject *player, IGame
 			src_can_take_count = dst_can_put_count = 0;
 	} else {
 		// Take from one inventory, put into another
+		int src_item_count = src_item.count;
+		if (caused_by_move_somewhere) src_item.count = expected_move_count;
```
Comment (sfan5) [inline src/inventorymanager.cpp:389]: code style

File: src/inventorymanager.cpp [hunk 2]
```diff
@@ -412,9 +415,9 @@ void IMoveAction::apply(InventoryManager *mgr, ServerActiveObject *player, IGame
 
 	/* Modify count according to collected data */
 	count = src_item.count;
-	if (src_can_take_count != -1 && count > src_can_take_count)
+	if (src_can_take_count != -1 && count > src_can_take_count && !caused_by_move_somewhere)
 		count = src_can_take_count;
-	if (dst_can_put_count != -1 && count > dst_can_put_count)
+	if (dst_can_put_count != -1 && count > dst_can_put_count && !caused_by_move_somewhere)
 		count = dst_can_put_count;
```
Comment (SmallJoker) [inline src/inventorymanager.cpp:421]: I don't think this code is yet correct, but writing it like this might help you during development:
```C++
	if (!caused_by_move_somewhere) {
		// ??? limit the moved stack size to what's allowed to put and take
		if (src_can_take_count != -1 && count > src_can_take_count)
			count = src_can_take_count;
		if (dst_can_put_count != -1 && count > dst_can_put_count)
			count = dst_can_put_count;
	}
```

**Comment by appgurueu** [comment]
Alright, part of the remaining issue was move_count not being set to zero in an early return.

File: src/inventorymanager.cpp (hunk 2 above)
Comment (appgurueu) [reply src/inventorymanager.cpp]: You were correct. (Hopefully) fixed by https://github.com/minetest/minetest/pull/10930/commits/69fa52c1593abca3b3501d1b95e8bf0db87dbe8f.

**Comment by sfan5** [comment]
uhh

grafik

**Comment by appgurueu** [comment]
> uhh
> 
> grafik

What in tarnation? Will fix.

File: src/inventorymanager.cpp [hunk 3]
```diff
@@ -503,8 +516,7 @@ void IMoveAction::apply(InventoryManager *mgr, ServerActiveObject *player, IGame
 			<< std::endl;
 
 	// If we are inside the move somewhere loop, we don't need to report
-	// anything if nothing happened (perhaps we don't need to report
-	// anything for caused_by_move_somewhere == true, but this way its safer)
+	// anything if nothing happened
```
Comment (appgurueu) [inline src/inventorymanager.cpp:519]: We do need to report for `caused_by_move_somewhere == true`, as the callbacks take the inventory slots.

File: src/inventorymanager.cpp [hunk 4]
```diff
@@ -558,7 +570,11 @@ void IMoveAction::apply(InventoryManager *mgr, ServerActiveObject *player, IGame
 		}
 		mgr->setInventoryModified(from_inv);
 	} else {
+		int src_item_count = src_item.count;
+		if (caused_by_move_somewhere)
```
Comment (appgurueu) [inline src/inventorymanager.cpp:574]: If inside the move somewhere loop, temporarily set this to the move count.

File: src/inventorymanager.cpp [hunk 5]
```diff
@@ -384,9 +389,13 @@ void IMoveAction::apply(InventoryManager *mgr, ServerActiveObject *player, IGame
 			src_can_take_count = dst_can_put_count = 0;
 	} else {
 		// Take from one inventory, put into another
+		int src_item_count = src_item.count;
+		if (caused_by_move_somewhere)
```
Comment (appgurueu) [inline src/inventorymanager.cpp:393]: If inside the move somewhere loop, temporarily set this to the move count.

File: src/inventorymanager.cpp [hunk 6]
```diff
@@ -352,10 +353,14 @@ void IMoveAction::apply(InventoryManager *mgr, ServerActiveObject *player, IGame
 	bool allow_swap = !list_to->itemFits(to_i, src_item, &restitem)
 		&& restitem.count == src_item.count
 		&& !caused_by_move_somewhere;
+	int expected_move_count = src_item.count - restitem.count;
 
 	// Shift-click: Cannot fill this stack, proceed with next slot
-	if (caused_by_move_somewhere && restitem.count == src_item.count)
+	if (caused_by_move_somewhere && restitem.count == src_item.count) {
+		// Don't forget to update move_count, else it proceeds with an outdated value!
+		move_count = 0;
```
Comment (appgurueu) [inline src/inventorymanager.cpp:361]: This was the cause for weird bugs and the underflow.

File: src/inventorymanager.cpp [hunk 7]
```diff
@@ -413,9 +422,10 @@ void IMoveAction::apply(InventoryManager *mgr, ServerActiveObject *player, IGame
 	/* Modify count according to collected data */
 	count = src_item.count;
 	if (src_can_take_count != -1 && count > src_can_take_count)
-		count = src_can_take_count;
+		count = std::min((int)count, src_can_take_count);
```
Comment (appgurueu) [inline src/inventorymanager.cpp:425]: Probably unneeded?

File: src/inventorymanager.cpp [hunk 8]
```diff
@@ -352,10 +353,14 @@ void IMoveAction::apply(InventoryManager *mgr, ServerActiveObject *player, IGame
 	bool allow_swap = !list_to->itemFits(to_i, src_item, &restitem)
 		&& restitem.count == src_item.count
 		&& !caused_by_move_somewhere;
+	int expected_move_count = src_item.count - restitem.count;
```
Comment (SmallJoker) [inline src/inventorymanager.cpp:356]: How about updating `count` or `src_item` here? 
Normal stack movement: If a swap is necessary, those two variables will be overwritten anyway 
Move somewhere (Shift-Click): no swapping at all, and the loop earlier in this function ensures that the entire stack is moved.

File: src/inventorymanager.cpp (hunk 5 above)
Comment (SmallJoker) [reply src/inventorymanager.cpp:393]: (In conflict with my comment above)
This should be documented/commented. Suggestion:
```
// When moving somewhere: temporarily use the actual movable stack
// size to ensure correct callback execution.
```

File: src/inventorymanager.cpp (hunk 7 above)
Comment (SmallJoker) [reply src/inventorymanager.cpp:425]: Not needed because of the check `count > src_can_take_count` above.

File: src/inventorymanager.cpp (hunk 8 above)
Comment (appgurueu) [reply src/inventorymanager.cpp]: Updated `move_count` instead.

**Review by SmallJoker — APPROVED** [review]
Tested (& passed) cases:
 * Shift-move with allow_move limited to 10 each -> stacks properly separated in stack @ 10
 * Shift-move, partial -> stops moving when all slots were checked. leftover is kept in inventory
 * Shift-move from infinite source -> splits stacks @ 10 (using modified `creative/inventory.lua`)
 * Shift-move, partial from infinite source -> same as regular source
 * Normal stack swap, stack counts <= max allowed count
 * Normal stack swap, stack counts > max allowed count

The reported move counts are all correct from what I can see.

**Review by sfan5 — APPROVED** [review]
Looks good, briefly tested
