### PR TITLE
Fix unnecessary content refreshing

### LINKED ISSUE #14655: Mainmenu performance regression
### Minetest version

6303334cc2f39732697a1278532cbe66ed481da8

The first affected commit is b4be483d3ecb08234685f9a071fd71946d041494.

### Irrlicht device

SDL

### Operating system and version

Fedora Linux 39 (Workstation Edition)

### CPU model

Intel® Core™ i7-4790K × 8

### GPU model

NVIDIA GeForce GTX 1080 Ti

### Active renderer

OpenGL 4.6.0

### Summary

While comparing 5.8.0 and 5.9.0-dev, I noticed that the 5.9.0-dev mainmenu reacts noticeably slower to button clicks etc. than the 5.8.0 one in some situations. This is especially visible when looking at the clouds in the background, which make a small jump each time I click a button.

I have bisected this problem to b4be483d3ecb08234685f9a071fd71946d041494 / #12208 @rubenwardy 

The problem is especially easy to see when going through the pages of the ContentDB dialog. In the following video, 57de599a292d1c7ad43dfc260d36dff2fbb61481 (good) is on the left and b4be483d3ecb08234685f9a071fd71946d041494 (bad) is on the right. For comparability, I used an autoclicker to click with 2 CPS in both videos. 

https://github.com/minetest/minetest/assets/82708541/e527422d-52c8-42a6-b4ef-3d93edabafb8

### Steps to reproduce

In the mainmenu, compare the delay between clicking a button and the result being shown between 5.8.0 and 5.9.0-dev. See that it is longer on 5.9.0-dev and that Minetest may even hang in some cases.

I'm not sure which views are affected by this, but at least the "Content" tab and the ContentDB dialog are definitely affected.

### PR DESCRIPTION
**Pull request by rubenwardy**
Fixes #14655

## To do

This PR is Ready for Review

## How to test

* Use the content tab and the mainmenu. Install, remove, update content.  Use settings

```lua
function pkgmgr.update_translations(list)
	core.log("error", "Updating translations for " .. #list .. " items")
	core.log(debug.traceback())
```

### CODE REVIEW

**Comment by rubenwardy** [comment]
This is ready to review as-is, but it may not fix the issue 100%. There's two things we could do here:

- The texture packs list is currently not cached, meaning that the translations will be loaded every time. So we could cache this.
- We could do translation caching, caching the values set by update_translations by the content path. We'd need to make sure to invalidate translations when updating or removing, including any child resources

File: builtin/mainmenu/content/contentdb.lua [hunk 1]
```diff
@@ -147,6 +147,11 @@ local function start_install(package, reason)
 			start_install(next.package, next.reason)
 		end
 
+		if package.type == "game" then
```
Comment (rubenwardy) [inline builtin/mainmenu/content/contentdb.lua:150]: this should be on line 136

File: builtin/mainmenu/content/contentdb.lua [hunk 2]
```diff
@@ -147,6 +147,11 @@ local function start_install(package, reason)
...
+			pkgmgr.update_gamelist()
+		else
+			pkgmgr.refresh_globals()
+		end
```
Comment (grorp) [inline builtin/mainmenu/content/contentdb.lua:154]: `pkgmgr.install_dir` already does this

**Review by grorp — COMMENTED** [review]
This is already much better.

I suggest this, it makes the debug output more readable by updating translations for all mods at once:

```diff
diff --git a/builtin/mainmenu/content/pkgmgr.lua b/builtin/mainmenu/content/pkgmgr.lua
index 720c435c4..891421100 100644
--- a/builtin/mainmenu/content/pkgmgr.lua
+++ b/builtin/mainmenu/content/pkgmgr.lua
@@ -150,8 +150,6 @@ function pkgmgr.get_mods(path, virtual_path, listing, modpack)
                        toadd.virtual_path = mod_virtual_path
                        toadd.type = "mod"
 
-                       pkgmgr.update_translations({ toadd })
-
                        -- Check modpack.txt
                        -- Note: modpack.conf is already checked above
                        local modpackfile = io.open(mod_path .. DIR_DELIM .. "modpack.txt")
@@ -176,6 +174,8 @@ function pkgmgr.get_mods(path, virtual_path, listing, modpack)
                table.sort(listing, function(a, b)
                        return a.virtual_path:lower() < b.virtual_path:lower()
                end)
+
+               pkgmgr.update_translations(listing)
        end
 end
 
```

I think it would be good to cache texture packs as well. Basically `pkgmgr.get_all()` is called on every single formspec interaction because the "Content" tabheader includes an update count.

```
2024-05-26 11:43:57: ERROR[Main]: Updating translations for 83 items
2024-05-26 11:43:57: [Main]: stack traceback:
	/mt/builtin/mainmenu/content/pkgmgr.lua:795: in function 'update_translations'
	/mt/builtin/mainmenu/content/pkgmgr.lua:194: in function 'get_texture_packs'
	/mt/builtin/mainmenu/content/pkgmgr.lua:220: in function 'get_all'
	/mt/builtin/mainmenu/content/update_detector.lua:128: in function 'get_all'
	/mt/builtin/mainmenu/content/update_detector.lua:151: in function 'get_count'
	/mt/builtin/mainmenu/tab_content.lua:286: in function 'caption'
	/mt/builtin/fstk/tabview.lua:164: in function 'tab_header'
	/mt/builtin/fstk/tabview.lua:86: in function 'get_formspec'
	/mt/builtin/fstk/ui.lua:101: in function 'update'
	/mt/builtin/fstk/ui.lua:204: in function 'event_handler'
	/mt/builtin/mainmenu/serverlistmgr.lua:220: in function /mt/builtin/mainmenu/serverlistmgr.lua:214>
	/mt/builtin/mainmenu/async_event.lua:7: in function /mt/builtin/mainmenu/async_event.lua:4>
```

**Comment by grorp** [comment]
Another problem is that the mod list is still loaded twice on startup. A log excerpt: [log.txt](https://github.com/minetest/minetest/files/15448089/log.txt)

**Comment by rubenwardy** [comment]
> Another problem is that the mod list is still loaded twice on startup. A log excerpt: [log.txt](https://github.com/minetest/minetest/files/15448089/log.txt)

Looks like this is due to the settingtypes loading code

File: builtin/mainmenu/content/contentdb.lua (hunk 2 above)
Comment (rubenwardy) [reply builtin/mainmenu/content/contentdb.lua]: For some reason, removing this causes ContentDB to no longer recognise install changes

Comment (rubenwardy) [reply builtin/mainmenu/content/contentdb.lua]: Ok, worked it out - it's because the `author` has not been set in the package's .conf at this point

**Review by grorp — CHANGES_REQUESTED** [review]
Enabling/disabling texture packs doesn't work properly

File: builtin/mainmenu/settings/dlg_settings.lua [hunk 3]
```diff
@@ -46,49 +57,6 @@ local function add_page(page)
...
-		"safe_dig_and_place",
-		{ heading = fgettext_ne("Movement") },
-		"arm_inertia",
-		"view_bobbing_amount",
-		"fall_bobbing_amount",
-	},
-})
-
-
 local function load_settingtypes()
```
Comment (grorp) [inline builtin/mainmenu/settings/dlg_settings.lua:60]: https://github.com/minetest/minetest/blob/4c9be808a7222e82e04c24d927150664773ad5be/builtin/mainmenu/settings/settingtypes.lua#L443-L444

The mod list is no longer loaded twice on startup, but it's still loaded twice. Why not use `pkgmgr.global_mods` here?

```lua
pkgmgr.load_all()
local mods = pkgmgr.global_mods:get_list()
```

File: builtin/mainmenu/content/tests/pkgmgr_spec.lua [hunk 4]
```diff
@@ -59,11 +62,11 @@ local function reset()
...
-	function env.pkgmgr.update_gamelist()
-		table.insert(calls, { "update_gamelist" })
+	function env.pkgmgr.reload_games()
+		table.insert(calls, { "reload_games" })
 	end
-	function env.pkgmgr.refresh_globals()
-		table.insert(calls, { "refresh_globals" })
+	function env.pkgmgr.reload_global_mods()
+		table.insert(calls, { "reload_global_mods" })
 	end
```
Comment (grorp) [inline builtin/mainmenu/content/tests/pkgmgr_spec.lua:70]: Why do these still exist?

File: builtin/mainmenu/settings/dlg_settings.lua (hunk 3 above)
Comment (rubenwardy) [reply builtin/mainmenu/settings/dlg_settings.lua:60]: I don't know why this uses get_mods rather than `global_mods`, but I've changed it now

File: builtin/mainmenu/content/pkgmgr.lua [hunk 5]
```diff
@@ -197,11 +199,21 @@ function pkgmgr.get_texture_packs()
...
 
-	return retval
+	pkgmgr.texture_packs = retval
+end
+
+--------------------------------------------------------------------------------
+function pkgmgr.get_texture_packs()
+	if not pkgmgr.texture_packs then
+		pkgmgr.reload_texture_packs()
+	end
```
Comment (grorp) [inline builtin/mainmenu/content/pkgmgr.lua:209]: As far as I can see, `pkgmgr.load_all()` is called before every use of `pkgmgr.get_texture_packs()` and this is unnecessary.

And if this is unnecessary, why is there even a getter function?

- `pkgmgr.games` / `pkgmgr.reload_games()`
- `pkgmgr.global_mods:get_list()` / `pkgmgr.reload_global_mods()`
- but: `pkgmgr.get_texture_packs()` / `pkgmgr.reload_texture_packs()`

File: builtin/mainmenu/settings/dlg_settings.lua [hunk 6]
```diff
@@ -129,94 +97,133 @@ local function load_settingtypes()
...
+		sw = "Kiswahili [sw]",
+		--th = " [th]", blacklisted
+		tr = "Türkçe [tr]",
+		tt = "Tatarça [tt]",
+		uk = "Українська [uk]",
+		vi = "Tiếng Việt [vi]",
+		zh_CN = "中文 (简体) [zh_CN]",
+		zh_TW = "正體中文 (繁體) [zh_TW]",
+	}
 end
```
Comment (grorp) [inline builtin/mainmenu/settings/dlg_settings.lua:225]:
```suggestion
end

```

**Review by grorp — COMMENTED** [review]
Tested:

- uninstall reloads by type correctly
- update reloads by type correctly
- install reloads by type correctly
- enabling/disabling texture packs works (and reloads, I guess that would be avoidable)
- builtin/game/mod/client mod settings are loaded

**Review by grorp — APPROVED** [review]
