### PR TITLE
Send chat error when attemping to /set a secure setting

### LINKED ISSUE #11480: /set should not crash on secure settings
Using `/set` on a secure setting (gracefully) crashes.
It should either check for secure before trying to set, or catch the error and return it in console/chat.

### PR DESCRIPTION
**Pull request by GoodClover**
Fixes #11480. Please see my comments there.

This PR:
- Fixes the crash when trying to `/set` a secure setting.

This PR does not:
- Prevent reading secure settings via `/set` (would be an easy change though).
- Prevent mods from causing the crash when attempting to set a secure setting. (No Lua API changes)

## To do

This PR is ready for review.

## How to test

Kablam:
image

### CODE REVIEW

File: builtin/game/chat.lua [hunk 1]
```diff
@@ -621,6 +621,10 @@ core.register_chatcommand("set", {
 
 		setname, setvalue = string.match(param, "([^ ]+) (.+)")
 		if setname and setvalue then
+			if string.match(setname, "^secure.") then
```
Comment (rubenwardy) [inline builtin/game/chat.lua:624]:
```suggestion
			if setname:sub(1, 7) == "secure." then
```

Comment (GoodClover) [reply builtin/game/chat.lua]: Also fixes bug where I forgot to escape the `.` ;)

**Review by rubenwardy — APPROVED** [review]

**Review by SmallJoker — APPROVED** [review]
It would be nice if the error could be caught, but this is also acceptable.
