### PR TITLE
use decrement(value) method to decrease average lag metric

### LINKED ISSUE #10420: max lag sent to serverlist is invalid if prometheus monitoring is enabled
##### Minetest version
```
5.3.0 with -DENABLE_PROMETHEUS=TRUE
```

##### OS / Hardware
Not relevant

##### Summary

If the `prometheus` monitoring feature is enabled then the lag sent to the serverlist will only show the peak-lag of the
server and the value will never decrease.

Some examples (pandorabox and CTF, which i _think_ has prometheus enabled, @rubenwardy correct me if i'm wrong):

The problem is caused by the "averaging" method here:
https://github.com/minetest/minetest/blob/add68369a59af90f8b4203b53695521c6d657d6b/src/server.cpp#L656

The `PrometheusMetricCounter::increment()` function calls the `prometheus-cpp` library with negative values which are then ignored:

https://github.com/jupp0r/prometheus-cpp/blob/de66b57c42cc23b5b412ef4ae01697dbda259da4/core/src/gauge.cc#L11-L16
```cpp
void Gauge::Increment(const double value) {
  if (value < 0.0) {
    return;
  }
  Change(value);
}
```

##### Solutions

A possible solution would be to use the `decrement()` function in case of negative values:

```diff
diff --git a/src/server.cpp b/src/server.cpp
index b8a99f6ae..8aa9a77d3 100644
--- a/src/server.cpp
+++ b/src/server.cpp
@@ -653,7 +653,12 @@ void Server::AsyncRunStep(bool initial_step)
        }
        m_clients.step(dtime);
 
-       m_lag_gauge->increment((m_lag_gauge->get() > dtime ? -1 : 1) * dtime/100);
+       // increase/decrease lag gauge gradually
+       if (m_lag_gauge->get() > dtime){
+               m_lag_gauge->decrement(-1 * dtime/100);
+       } else {
+               m_lag_gauge->increment(1 * dtime/100);
+       }
 #if USE_CURL
        // send masterserver announce
        {
```

##### Steps to reproduce

* Compile minetest with `prometheus` support and serverlist announce
* Start the game and lag the server somehow (mapgen?)
* Observe an ever-increasing max_lag value on the serverlist

### PR DESCRIPTION
**Pull request by BuckarooBanzay**
This PR fixes #10420

It uses the `decrement()` method to decrease the lag value

This PR is Ready for Review.

## How to test

Compile minetest with `prometheus` support
```bash
# compile and install metric server dependency
git clone --depth 1 https://github.com/jupp0r/prometheus-cpp.git -b v0.9.0 && \
  cd prometheus-cpp && \
  git submodule init && \
  git submodule update && \
  cmake . && make -j4 && make install

# minetest directory
cmake . -DENABLE_PROMETHEUS=TRUE && make -j4
```

Add the Test-~~lagatory~~mod:
```lua
-- lag simulation
local lag = 0
minetest.register_chatcommand("lag", {
  description = "simulate server lag",
  params = "<seconds>",
  func = function(_, param)
    lag = tonumber(param or "0") or 0
    return true, "lag = " .. lag .. " s"
  end
})

minetest.register_globalstep(function()
  if lag < 0.01 then
    -- ignore value
    return
  end

  local start = minetest.get_us_time()
  local stop = start + (lag * 1000 * 1000)

  while minetest.get_us_time() < stop do
    -- no-op
  end
end)
```

Start a default minetest game and observe the `minetest_core_latency` value on the metrics website: http://127.0.0.1:30000/metrics

Increase the lag with `/lag 0.5` or decrease again with `/lag 0`

The `minetest_core_latency` metric should rise and fall gradually

### CODE REVIEW

**Review by SmallJoker — APPROVED** [review]
Thanks. LGTM.

File: src/server.cpp [hunk 1]
```diff
@@ -653,7 +653,12 @@ void Server::AsyncRunStep(bool initial_step)
 	}
 	m_clients.step(dtime);
 
-	m_lag_gauge->increment((m_lag_gauge->get() > dtime ? -1 : 1) * dtime/100);
+	// increase/decrease lag gauge gradually
+	if (m_lag_gauge->get() > dtime) {
+		m_lag_gauge->decrement(dtime/100);
+	} else {
+		m_lag_gauge->increment(dtime/100);
+	}
```
Comment (sfan5) [inline src/server.cpp:661]: braces not necessary

Comment (BuckarooBanzay) [reply src/server.cpp:661]: not _necessary_ but they help visually

Comment (sfan5) [reply src/server.cpp:661]: They don't help me but I won't insist.
