### PR TITLE
Inventory mouse shortcut improvements

### LINKED ISSUE #5374: Stack splitting equally by shift click
I saw a really nice feature in Minecraft I really want to see in Minetest too.

For example, if you want to make a lot of fences and you have a stack of 60 sticks, hold down a key, maybe sneak, and place the stack in the first slot. Than click on the next slot and the stack will be splittet between the slots. If you click on the third slot all sticks get splittet between all 3 slots, so each slot has 20 sticks. 

Watch this Video from the position. Maybe pause the video and set playback speed to 0.25

https://youtu.be/EtZ7ZwMyPz8?t=248

### LINKED ISSUE #9456: Shift clicking the craft preview doesn't add into main inventory
##### Minetest version

```

```

##### OS / Hardware

Operating system:Arch Linux
CPU:Ryzen 3 3200G
MEMORY: 16GB ddr4

##### Summary
Using shift clicking on the craft preview with list rings does not work properly between the craftpreview and the main inventory. Creates issues where the player cannot shift click from the craftpreview but can create a glitch where you can shift click into it from the main inventory then, when you pull the items out of the craft preview after shift clicking into it, the game will reset your shift clicked items back into the main as they were before.

##### Steps to reproduce
local inv =	"size[8,7.5]"..
    "image[1,0.6;1,2;player.png]"..
    "list[current_player;main;0,3.5;8,4;]"..
    "list[current_player;craftpreview;7,1;1,1;]"..
    "list[current_player;craft;4,0.5;3,3;]"..
    "listring[current_player;main]listring[current_player;craftpreview]"
    

minetest.register_on_joinplayer(function(player)
	player:set_inventory_formspec(inv)
end)

### LINKED ISSUE #12596: mouse event issue w/ inventory lists
##### Minetest version
```
0.4.17.1 through 5.5.1, 5.6.0-dev-de8ce9a8ff999c7ab9562528a972d5426a9f7cec
```

##### OS / Hardware
Operating system: linux, unsure about mac/windows/etc

##### Summary
There are separate mouse-click events triggered on both press and release. This allows a player to press and hold a mouse button over an item in one slot in an inventory list, drag it to another slot, and release the mouse button it, replacing the other item, and picking up what was in that slot.

There is a separate behavior, whereby a player can click and release the button, resulting in the item being "picked up", while allowing them to drag it around w/out having to hold down the mouse button. Another click will deposit it (or replace what's in the target slot). 

However, a player trying to pick up an item using the second mechanism can quite easily trigger the first behavior accidentally, if they are moving the mouse quickly. The result is that they end up moving the wrong item to the target location, which is a big problem if the target location is e.g. the "trash" slot in unified inventory. 

IMO the solution should be to add a minimum time before the release can trigger an event, some fraction of a second. 

##### Steps to reproduce
While moving the mouse fairly quickly, click on something and release the mouse button (it's easier to replicate if you pause ever-so-slightly before you release.

https://user-images.githubusercontent.com/25628292/181096647-5e93e322-b89b-415a-9c56-2771c0185ce5.mp4

 In this demonstration video, the problematic behavior only happens on the third attempt.

### PR DESCRIPTION
**Pull request by OgelGames**
Re-implementation of #6544 / #7986, with additional features and fixes.

Fixes #5374, fixes #9456, fixes #12596.

**Additions**

- Left-drag to distribute items evenly
- Middle-drag to deposit 10 items in each slot
- Shift-clicking on the craft preview moves items into the inventory (limited, see note below)
- Shift-moving items by dragging (works with left, right and middle buttons)
- Left-drag-moving an item over identical items to pick them up
- Left-double-click to pickup up all of a selected item
- Shift-left-click on an item with an identical item to move all of that item

**Fixes and changes**

- Scrolling with an item now lets you pick the items back up
- Moving an item over another item now requires an additional click to swap
- Mouse button clicks that occur when already holding a button are now ignored

See the short video below for a demonstration of most of the new shortcuts:

https://user-images.githubusercontent.com/48543043/212528991-9c4d106a-9477-4cd8-9d46-b39182cd87ec.mp4

Fixes:

- #5374
- #9456
- #12596

Also link some closed issues:

- #2963
- #5211
- #6757
- #13103

---

A note about the shift-clicking from the craft preview: while right-click and middle-click function as they should (crafting 1x and 10x), left click is limited to 1x. Shift-left-click should craft the maximum possible, but with the slow crafting code (see https://github.com/pandorabox-io/pandorabox.io/issues/543, there doesn't seem to be an issue open here yet) that can cause significant lag spikes when crafting large amounts of items, so it must limited until that code is optimized.

## To do

This PR is Ready for Review.

## How to test

1. Get some items.
2. Use the various combinations of mouse buttons, scroll wheel and the shift key to move items around.

### CODE REVIEW

**Comment by Wuzzy2** [comment]
This is great! This is a massive improvement and one of the best features in years. It's not perfect yet, a few things still feel a bit wrong:

* Double-left-clicking an item to pick up all sometimes picks up weird items. Like, if you have a stack of 80 and a lot of single items in the inventory, and then you double-click the 80 stack, the items are sometimes picked up in a weird way. I don't understand the rule for this yet and it seems kinda random and confusing. Maybe care to elaborate the rule to make testing easier?
* If u hold an item stack and move it around empty slots to distribute them with LMB: The UI looks confusing and it behaves weirdly. Sometimes, the item stack in my cursor disappears while I move my cursor which is VERY irritating.
    * And when I release the mouse button, the item stack I held gets automatically removed from my cursor and lands in an unpredicable slot. I would also like to know the rule for this behavior.
* Bug: If I start pressing Sneak or a mouse button before I hover a slot, and then move to a slot, the slot does not highlight (but the item moving stuff still works)

**Comment by OgelGames** [comment]
> * Double-left-clicking an item to pick up all sometimes picks up weird items. Maybe care to elaborate the rule to make testing easier?

The items should be picked up in order from left to right, top to bottom, until the stack is full. The code ([here](https://github.com/minetest/minetest/pull/13146/files#diff-d518daac1f5499b49517a02957e29771288333e58227308b7711cc5da6bd1544R4575-R4614)) goes through the list in order, moving items to the selected stack until there is no more room, at which point it stops.

> * If u hold an item stack and move it around empty slots to distribute them with LMB: The UI looks confusing and it behaves weirdly. Sometimes, the item stack in my cursor disappears while I move my cursor which is VERY irritating.

The cursor only holds the remainder, so when the items split evenly the cursor won't be holding anything.
  
>   * And when I release the mouse button, the item stack I held gets automatically removed from my cursor and lands in an unpredicable slot. I would also like to know the rule for this behavior.

That doesn't sound right... Whatever items you're holding should stay in the cursor when you release the button, in fact nothing at all should change.

> * Bug: If I start pressing Sneak or a mouse button before I hover a slot, and then move to a slot, the slot does not highlight (but the item moving stuff still works)

Looks like that bug has existed for a while, I checked in 5.4.0 and it happens there too. I'm not sure how to fix that.

**Comment by Emojigit** [comment]
A conflict should be solved:
```diff
diff --cc src/client/client.h
index 44a0de719,489a76956..000000000
--- a/src/client/client.h
+++ b/src/client/client.h
@@@ -438,10 -437,8 +438,15 @@@ public
        {
                return m_env.getLocalPlayer()->formspec_prepend;
        }
++<<<<<<< HEAD
 +      inline MeshGrid getMeshGrid()
 +      {
 +              return m_mesh_grid;
 +      }
++=======
+ 
+       bool m_inhibit_inventory_revert = false;
++>>>>>>> OgelGames/inventory_mouse_shortcuts
  
  private:
        void loadMods();
```
I left both `getMeshGrid()` and `m_inhibit_inventory_revert` when cherry-picking changes to my local client, and it compiles. However, which (or actually both) should be left?

My merging steps:
1. Checkout https://github.com/minetest/minetest/commit/2f9f0c09001b8fbc6f4559cbfdccf0261f1377a4 (detached HEAD)
2. Merge this branch (I've already set a remote for this)
3. solve the conflict by removing the git-generated lines
4. run `git add src/client/client.h && git commit`

**Comment by OgelGames** [comment]
Both, the only change I made to `client.h` was adding `m_inhibit_inventory_revert`, nothing should be removed.

**Comment by OgelGames** [comment]
Anyone know what's holding this PR up? It's been 3 months now...

File: src/client/client.h [hunk 1]
```diff
@@ -440,10 +440,13 @@ class Client : public con::PeerHandler, public InventoryManager, public IGameDef
 	{
 		return m_env.getLocalPlayer()->formspec_prepend;
 	}
+
 	inline MeshGrid getMeshGrid()
 	{
 		return m_mesh_grid;
 	}
+  
+  bool m_inhibit_inventory_revert = false;
```
Comment (SmallJoker) [inline src/client/client.h:449]: Bad indent type

File: src/gui/guiFormSpecMenu.cpp [hunk 2]
```diff
@@ -3767,14 +3772,46 @@ void GUIFormSpecMenu::updateSelectedItem()
...
+			s.inventoryloc = e->getInventoryloc();
+			s.listname = "craftresult";
+			s.i = 0;
+			s.slotsize = e->getSlotSize();
+
+			if (m_shift_craft) {
+				// Try to shift-move the crafted item somewhere,
+				// but not back into the crafting grid
+				for (u32 i = 0; i < m_inventory_rings.size(); i++) {
+					const ListRingSpec &lr = m_inventory_rings[i];
```
Comment (SmallJoker) [inline src/gui/guiFormSpecMenu.cpp:3785]: This likely works well in Minetest Game but if another game defines list rings it might be worse than hardcoding "main" as the destination list (which is de-facto mandatory).

File: src/gui/guiFormSpecMenu.cpp [hunk 3]
```diff
@@ -3767,14 +3772,46 @@ void GUIFormSpecMenu::updateSelectedItem()
...
-			m_selected_item->slotsize = e->getSlotSize();
-			m_selected_amount = item.count;
-			m_selected_dragging = false;
+			GUIInventoryList::ItemSpec s = GUIInventoryList::ItemSpec();
+			s.inventoryloc = e->getInventoryloc();
+			s.listname = "craftresult";
+			s.i = 0;
+			s.slotsize = e->getSlotSize();
+
+			if (m_shift_craft) {
```
Comment (SmallJoker) [inline src/gui/guiFormSpecMenu.cpp:3781]: Suggestion: Invert this condition and use its code block with an early `break;` to reduce indent levels.
Result: Hopefully an easier to follow code structure.

File: src/gui/guiFormSpecMenu.cpp [hunk 4]
```diff
@@ -4174,12 +4215,25 @@ bool GUIFormSpecMenu::OnEvent(const SEvent& event)
...
-		ButtonEventType button = BET_LEFT;
+		// True if the hovered slot is empty
+		bool empty = s.isValid() && list_s->getItem(s.i).empty();
+
+		// True if the hovered item would stack with the selected item
+		bool matching = false;
+		if (m_selected_item && s.isValid()) {
+			ItemStack a = list_selected->getItem(m_selected_item->i);
+			ItemStack b = list_s->getItem(s.i);
+			if (a.name == b.name && a.wear == a.wear && a.metadata == a.metadata)
```
Comment (SmallJoker) [inline src/gui/guiFormSpecMenu.cpp:4232]: `a.itemFits(b, nullptr, itemdef)` should be more reliable than manually checking properties.

File: src/gui/guiFormSpecMenu.cpp [hunk 5]
```diff
@@ -4228,153 +4286,384 @@ bool GUIFormSpecMenu::OnEvent(const SEvent& event)
...
+					//craft_amount = list_s->getItem(s.i).getStackMax(m_client->idef());
+				else
+					craft_amount = 1;
+
+				// Holding shift moves the crafted item to the inventory
+				m_shift_craft = event.MouseInput.Shift;
+
+			} else if (!m_selected_item && button != BET_WHEEL_UP && !empty) {
+				// Non-empty stack has been clicked: select or shift-move it
+				u32 count;
```
Comment (SmallJoker) [inline src/gui/guiFormSpecMenu.cpp:4326]: This variable is possibly uninitialized. Whereas it might be appropriately protected, this will not always be the case in the future.


```suggestion
				u32 count = 0;
```

File: src/gui/guiFormSpecMenu.cpp [hunk 6]
```diff
@@ -4228,153 +4286,384 @@ bool GUIFormSpecMenu::OnEvent(const SEvent& event)
...
-						// no shift: select item
-						m_selected_amount = count;
-						m_selected_dragging = button != BET_WHEEL_DOWN;
-						m_auto_place = false;
-					} else {
-						// shift pressed: move item, right click moves 1
-						shift_move_amount = button == BET_RIGHT ? 1 : count;
+			} else if (m_selected_item) {
+				// Clicked a slot: move
+				if (button == BET_RIGHT || button == BET_WHEEL_UP)
```
Comment (SmallJoker) [inline src/gui/guiFormSpecMenu.cpp:4348]: `BET_WHEEL_UP` is already handled separately in L4355

File: src/gui/guiFormSpecMenu.cpp [hunk 7]
```diff
@@ -4228,153 +4286,384 @@ bool GUIFormSpecMenu::OnEvent(const SEvent& event)
...
+						if (lr.inventoryloc == s.inventoryloc &&
+								lr.listname == s.listname)
+							break;
 					}
-				}
-			} else { // m_selected_item != NULL
-				assert(m_selected_amount >= 1);
+					if (r >= rings) // Not found
+						break;
+					r = (r + 1) % rings;
```
Comment (SmallJoker) [inline src/gui/guiFormSpecMenu.cpp:4374]: Would you please be so nice to move this list ring code to a separate function? That would help to keep the code a bit better structured.

File: src/gui/guiFormSpecMenu.cpp [hunk 8]
```diff
@@ -4408,51 +4697,95 @@ bool GUIFormSpecMenu::OnEvent(const SEvent& event)
...
-			u32 mis = m_inventory_rings.size();
+			// Try to find the list ring for the inventory
+			// the hovered item belongs to
+			u32 rings = m_inventory_rings.size();
 			u32 i = 0;
-			for (; i < mis; i++) {
-				const ListRingSpec &sp = m_inventory_rings[i];
-				if (sp.inventoryloc == s.inventoryloc
-						&& sp.listname == s.listname)
+			for (; i < rings; i++) {
```
Comment (SmallJoker) [inline src/gui/guiFormSpecMenu.cpp:4742]: Same as above: separate function.

File: src/gui/guiFormSpecMenu.cpp [hunk 9]
```diff
@@ -4408,51 +4697,95 @@ bool GUIFormSpecMenu::OnEvent(const SEvent& event)
...
+			ItemStack stack_from = list_s->getItem(s.i);
+			ItemStack stack_to = list_selected->getItem(m_selected_item->i);
+
+			// Only move if the items are exactly the same,
+			// we shouldn't attempt to pickup different items
+			if (matching) {
+				// Check how many items can be moved
+				pickup_amount = stack_from.count = MYMIN(pickup_amount, stack_from.count);
+				ItemStack leftover = stack_to.addItem(stack_from, m_client->idef());
+				if (!leftover.empty()) {
```
Comment (SmallJoker) [inline src/gui/guiFormSpecMenu.cpp:4716]: Useless condition.

File: src/gui/guiFormSpecMenu.cpp [hunk 10]
```diff
@@ -4228,153 +4286,384 @@ bool GUIFormSpecMenu::OnEvent(const SEvent& event)
...
+					m_selected_amount -= split_amount;
+
+				} else {
+					// Reset the stack to it's original state
+					list_to->changeItem(ds.first->i, ds.second);
+
+					// Add the new split to the stack
+					ItemStack add_stack = stack_from;
+					add_stack.count = split_amount;
+					ItemStack leftover = list_to->addItem(ds.first->i, add_stack);
```
Comment (SmallJoker) [inline src/gui/guiFormSpecMenu.cpp:4637]: Q: The list contents apparently change with each iteration. How and where does this trigger the inventory action?

File: src/gui/guiFormSpecMenu.cpp [hunk 11]
```diff
@@ -4228,153 +4286,384 @@ bool GUIFormSpecMenu::OnEvent(const SEvent& event)
...
+					if (slct.name == item.name && slct.wear == item.wear &&
+							slct.metadata == item.metadata) {
+						// Found a match, check if we can pick it up
+						bool full = false;
+						u16 amount = item.count;
+						ItemStack leftover = slct.addItem(item, m_client->idef());
+						if (!leftover.empty()) {
+							amount -= leftover.count;
+							full = true;
+						}
```
Comment (SmallJoker) [inline src/gui/guiFormSpecMenu.cpp:4584]: `item.itemFits(slct, OUTPUT, m_client->idef())` should be shorter and more reliable.

File: src/gui/guiFormSpecMenu.cpp [hunk 12]
```diff
@@ -4228,153 +4286,384 @@ bool GUIFormSpecMenu::OnEvent(const SEvent& event)
...
+
+			ItemStack stack_from = m_left_drag_stack;
+			m_selected_amount = m_left_drag_amount;
+
+			for (auto &ds : m_left_drag_stacks) {
+				Inventory *inv_to = m_invmgr->getInventory(ds.first->inventoryloc);
+				InventoryList *list_to = inv_to->getList(ds.first->listname);
+
+				if (inv_to == inv_selected && list_to == list_selected &&
+						ds.first->i == m_selected_item->i) {
```
Comment (SmallJoker) [inline src/gui/guiFormSpecMenu.cpp:4626]: Use `ItemSpec::operator==(const ItemSpec &other)` (once implemented)

File: src/gui/guiFormSpecMenu.cpp [hunk 13]
```diff
@@ -4228,153 +4286,384 @@ bool GUIFormSpecMenu::OnEvent(const SEvent& event)
...
+							move_amount = MYMIN(m_selected_amount, 10);
+					}
+
+				} else if (m_left_dragging && (empty || matching) &&
+						   m_left_drag_amount > m_left_drag_stacks.size()) {
+					// Add the slot to the left-drag list if it doesn't exist
+					bool found = false;
+					for (auto &ds : m_left_drag_stacks) {
+						if (s.inventoryloc == ds.first->inventoryloc &&
+								s.listname == ds.first->listname && s.i == ds.first->i) {
```
Comment (SmallJoker) [inline src/gui/guiFormSpecMenu.cpp:4530]: Please implement `ItemSpec::operator==(const ItemSpec &other)` instead.

File: src/gui/guiFormSpecMenu.cpp [hunk 14]
```diff
@@ -4228,153 +4286,384 @@ bool GUIFormSpecMenu::OnEvent(const SEvent& event)
...
+							found = true;
```
Comment (SmallJoker) [inline src/gui/guiFormSpecMenu.cpp:4531]: `break;`. This can only match one slot.

File: src/gui/guiFormSpecMenu.h [hunk 15]
```diff
@@ -331,6 +331,13 @@ class GUIFormSpecMenu : public GUIModalMenu
 	u16 m_selected_amount = 0;
 	bool m_selected_dragging = false;
 	ItemStack m_selected_swap;
+	int m_held_button = -1;
+	bool m_shift_craft = false;
+
+	u16 m_left_drag_amount;
+	ItemStack m_left_drag_stack;
+	std::map<GUIInventoryList::ItemSpec *, ItemStack> m_left_drag_stacks;
```
Comment (SmallJoker) [inline src/gui/guiFormSpecMenu.h:339]: `GUIInventoryList::ItemSpec` must be freed within `~GUIFormSpecMenu`.
Possible solution 1: use `std::unique_ptr` to ensure that they're deleted with the map
Suggested solution 2: use `std::vector<std::pair<GUIInventoryList::ItemSpec, ItemStack>>` or a custom struct to hold both values.

File: src/gui/guiFormSpecMenu.h [hunk 16]
```diff
@@ -331,6 +331,13 @@ class GUIFormSpecMenu : public GUIModalMenu
 	u16 m_selected_amount = 0;
 	bool m_selected_dragging = false;
 	ItemStack m_selected_swap;
+	int m_held_button = -1;
+	bool m_shift_craft = false;
```
Comment (SmallJoker) [inline src/gui/guiFormSpecMenu.h:335]: Would you please be so nice to put a short description for each new variable to explain what they're used for?

File: src/gui/guiFormSpecMenu.cpp [hunk 17]
```diff
@@ -4228,153 +4286,384 @@ bool GUIFormSpecMenu::OnEvent(const SEvent& event)
...
-							move_amount = 0;
+					ItemStack slct = list_selected->getItem(m_selected_item->i);
+
+					for (u32 i = 0; i < list_s->getSize(); i++) {
+						// Skip the selected slot
+						if (i == m_selected_item->i)
+							continue;
+						ItemStack item = list_s->getItem(i);
+
+						if (slct.name == item.name && slct.wear == item.wear &&
```
Comment (SmallJoker) [inline src/gui/guiFormSpecMenu.cpp:4392]: Q: What is the goal of this code (in general)? It seems to move all similar items according to the list ring but what happens to the selected item? You previously set `move_amount = 0`, hence that one will not be moved?

File: src/client/client.h (hunk 1 above)
Comment (SmallJoker) [inline src/client/client.h:449]: This variable needs a good description of what it does. Furthermore, consider dropping the `m_` prefix. This is not a private member.

**Review by SmallJoker — COMMENTED** [review]
This code gets more chaotic the more features are added to it. If it is somehow possible to split individual actions into functions, it would be greatly appreciated.

File: src/gui/guiFormSpecMenu.cpp (hunk 9 above)
Comment (OgelGames) [reply src/gui/guiFormSpecMenu.cpp:4713]: How is it useless?

File: src/gui/guiFormSpecMenu.cpp (hunk 10 above)
Comment (OgelGames) [reply src/gui/guiFormSpecMenu.cpp]: Yes, the items are redistributed each time an additional slot is hovered over while dragging. The inventory action only happens when left-click is released. (this is why `inhibit_inventory_revert` is needed to prevent the changes from being reverted)

https://github.com/minetest/minetest/blob/b795b6cdb54a12b0f0101dda064679f1fbfdb6ba/src/gui/guiFormSpecMenu.cpp#L4455-L4493

File: src/gui/guiFormSpecMenu.h (hunk 16 above)
Comment (OgelGames) [reply src/gui/guiFormSpecMenu.h:336]: Why? None of the other variables have or need comments.

File: src/gui/guiFormSpecMenu.cpp (hunk 17 above)
Comment (OgelGames) [reply src/gui/guiFormSpecMenu.cpp:4391]: It aborts the move, and then performs a shift-move for all the matching items. The selected item stays selected at its original location.

File: src/gui/guiFormSpecMenu.cpp (hunk 4 above)
Comment (OgelGames) [reply src/gui/guiFormSpecMenu.cpp:4233]: That function returns false if `b` doesn't completely fit in `a`, so it can't be used. Also the `==` operator compares the count of the items, so that can't be used either.

File: src/gui/guiFormSpecMenu.cpp (hunk 2 above)
Comment (OgelGames) [reply src/gui/guiFormSpecMenu.cpp]: Do you have any suggestions? Would it be better to look for the next list in the ring after "craft"?

File: src/gui/guiFormSpecMenu.cpp (hunk 11 above)
Comment (OgelGames) [reply src/gui/guiFormSpecMenu.cpp:4587]: See other comment regarding this above.

File: src/gui/guiFormSpecMenu.cpp (hunk 2 above)
Comment (SmallJoker) [reply src/gui/guiFormSpecMenu.cpp]: I believe any guesswork overall can result in buggy behaviour, so I would explicitly look for the next list after "craftresult" in the list ring. Default to "main" if there is no such rule given by games.

File: src/gui/guiFormSpecMenu.h (hunk 16 above)
Comment (SmallJoker) [reply src/gui/guiFormSpecMenu.h:339]: Just because they have none does not make it easier to understand. I am not asking for a detailed explanation. In this case it's not clear what the variable stands for:

 * Does it represent a key state while crafting items?
 * Is it an on/off toggle for some crafting mechanic?

And as for `m_held_button` - is it a keyboard key code or related to mouse? Is it derived from an Irrlicht input enum?

Comment (OgelGames) [reply src/gui/guiFormSpecMenu.h]: I've changed the type and renamed both variables to be more clear: `m_held_mouse_button` and `m_shift_move_after_craft`.

I also had to move the `ButtonEventType` enum into `guiFormSpecMenu.h` to allow using that type there.

File: src/gui/guiFormSpecMenu.cpp (hunk 4 above)
Comment (OgelGames) [reply src/gui/guiFormSpecMenu.cpp]: I implemented `ItemStack::stacksWith()`, I think that name makes more sense for the use case: `a.stacksWith(b)`.

File: src/gui/guiFormSpecMenu.cpp (hunk 2 above)
Comment (OgelGames) [reply src/gui/guiFormSpecMenu.cpp]: But "craftresult" isn't in the list ring, because it shouldn't be part of the formspec, which is where the list rings are defined.

I've adjusted the code and added a comment explaining the reasoning. If there is no list after "craft" then the item is selected as normal.

Comment (OgelGames) [reply src/gui/guiFormSpecMenu.cpp]: > It's part of the formspec though, where else would it be?

No, the "craft" (the 3x3 grid) and "craftpreview" (what you click to craft) lists are part of the formspec, but the "craftresult" list is not.

The "craftresult" list shouldn't be part of the formspec because you never need to interact with it directly, and in fact there is code preventing items being moved there: https://github.com/minetest/minetest/blob/180ec92ef982d9fb5c6bdc789f381335f77823c1/src/network/serverpackethandler.cpp#L682-L690

File: src/gui/guiFormSpecMenu.cpp [hunk 18]
```diff
@@ -4228,153 +4290,370 @@ bool GUIFormSpecMenu::OnEvent(const SEvent& event)
...
+						break;
+					InventoryList *list_to = inv_to->getList(to_ring.listname);
+					if (!list_to)
+						break;
+
+					ItemStack slct = list_selected->getItem(m_selected_item->i);
+
+					for (u32 i = 0; i < list_s->getSize(); i++) {
+						// Skip the selected slot
+						if (i == m_selected_item->i)
```
Comment (SmallJoker) [inline src/gui/guiFormSpecMenu.cpp:4382]: `src/gui/guiFormSpecMenu.cpp:4382:55: warning: comparison of integer expressions of different signedness: ‘irr::u32’ {aka ‘unsigned int’} and ‘irr::s32’ {aka ‘int’} [-Wsign-compare]`

I suppose you could use `s32` to iterate unless you'd like to use `u32` in `GUIInventoryList::ItemSpec`.

File: src/gui/guiFormSpecMenu.cpp [hunk 19]
```diff
@@ -4228,153 +4290,370 @@ bool GUIFormSpecMenu::OnEvent(const SEvent& event)
...
+			if (!m_selected_item && !empty)
+				slct = list_s->getItem(s.i);
+			else if (m_selected_item && (identical || empty))
+				slct = list_selected->getItem(m_selected_item->i);
+
+			// Pickup all of the item from the list
+			if (slct.count > 0) {
+				for (u32 i = 0; i < list_s->getSize(); i++) {
+					// Skip the selected slot
+					if (i == s.i)
```
Comment (SmallJoker) [inline src/gui/guiFormSpecMenu.cpp:4562]: `src/gui/guiFormSpecMenu.cpp:4562:47: warning: comparison of integer expressions of different signedness: ‘irr::u32’ {aka ‘unsigned int’} and ‘irr::s32’ {aka ‘int’} [-Wsign-compare]`

(same as above)

File: src/gui/guiFormSpecMenu.h [hunk 20]
```diff
@@ -332,6 +348,13 @@ class GUIFormSpecMenu : public GUIModalMenu
 	u16 m_selected_amount = 0;
 	bool m_selected_dragging = false;
 	ItemStack m_selected_swap;
+	ButtonEventType m_held_mouse_button = BET_OTHER;
+	bool m_shift_move_after_craft = false;
+
+	u16 m_left_drag_amount;
```
Comment (SmallJoker) [inline src/gui/guiFormSpecMenu.h:354]: Possibly uninitialized.

**Review by SmallJoker — COMMENTED** [review]
Found a few minor code issues. The described item movements worked on my side. I could not find any issues.
Even limited stack movement (e.g. max 10 per movement) did work well. Tested with https://github.com/SmallJoker/minetest_lab/blob/master/init_76_inv_callbacks.lua (attempt to move a stack of 99 with any of the stack movement actions).

**Review by SmallJoker — APPROVED** [review]

**Review by srifqi — CHANGES_REQUESTED** [review]
Please rebase to recent `master` branch.

**Review by srifqi — APPROVED** [review]
I tested it and it works. The concept and its implementation look good, except for a few lines. There is a problem with the crafting using <kbd>Shift</kbd> when there is no more room, but I think that has other use cases that I can not think of it for now.

-------

**My tests:**

When using an inventory,
- [x] Other button click is ignored when already a button is being clicked (being held).

When the targetting inventory is full (using <kbd>Shift</kbd> + click),
- [x] No transfer is happening.
- [ ] The crafting still happens. ⚠

<details>
<summary>When holding/selecting a stack of items,</summary>

- [x] Left-click + drag to distribute items evenly
- [x] Middle-click + drag to put 10 items in each slot
- [x] Right-click + drag to put 1 item in each slot
- [x] <kbd>Shift</kbd> + left-click to move all identical stacks to another inventory
- [x] Scroll down to pick 1 identical item from an inventory
- [x] Scroll up to put 1 identical item to an inventory
</details>

<details>
<summary>Over an inventory,</summary>

- [x] <kbd>Shift</kbd> + left-click + drag to transfer hovered stacks between two inventories
- [x] <kbd>Shift</kbd> + middle-click + drag to transfer 10 items of each hovered stack between two inventories
- [x] <kbd>Shift</kbd> + right-click + drag to transfer 1 item of each hovered stack between two inventories
- [x] Left-click + drag to pick/get the hovered identical stack in the inventory
- [x] Left-double-click to pick the hovered stack and its all stack identical to it
- [x] Left-click + drag to pick _then needing to click again_ to swap with a non-identical stack
</details>

<details>
<summary>Over the crafting output slot,</summary>

- [x] Left-click to craft once
- [x] Middle-click to craft 10 times
- [x] Right-click to craft once
- [x] <kbd>Shift</kbd> + left-click to craft once and transfer the result to the player's inventory
- [x] <kbd>Shift</kbd> + middle-click to craft 10 times and transfer the results to the player's inventory
- [x] <kbd>Shift</kbd> + right-click to craft once and transfer the result to the player's inventory
</details>

File: src/gui/guiFormSpecMenu.h [hunk 21]
```diff
@@ -267,6 +282,7 @@ class GUIFormSpecMenu : public GUIModalMenu
 	GUITable* getTable(const std::string &tablename);
 	std::vector<std::string>* getDropDownValues(const std::string &name);
 
+
```
[the remark this answers is not in the document]
Comment (OgelGames) [reply src/gui/guiFormSpecMenu.h:285]: I think it's just a leftover from code that I had added and later moved.

File: src/gui/guiFormSpecMenu.cpp [hunk 22]
```diff
@@ -4117,12 +4162,14 @@ bool GUIFormSpecMenu::OnEvent(const SEvent& event)
...
+	  field while holding left, right, or middle mouse button
 	 */
 	if (event.EventType == EET_MOUSE_INPUT_EVENT &&
 			(event.MouseInput.Event != EMIE_MOUSE_MOVED ||
 			 (event.MouseInput.Event == EMIE_MOUSE_MOVED &&
-			  event.MouseInput.isRightPressed() &&
+				 (event.MouseInput.isLeftPressed()
+			   || event.MouseInput.isRightPressed()
+			   || event.MouseInput.isMiddlePressed()) &&
 			  getItemAtPos(m_pointer).i != getItemAtPos(m_old_pointer).i))) {
```
[the remark this answers is not in the document]
Comment (OgelGames) [reply src/gui/guiFormSpecMenu.cpp:4173]: Yeah, quite ugly that one, but I don't really think it can be changed much. I did notice a redundant part I could remove though:
```cpp
	if (event.EventType == EET_MOUSE_INPUT_EVENT &&
		(event.MouseInput.Event != EMIE_MOUSE_MOVED ||
			((event.MouseInput.isLeftPressed() ||
				event.MouseInput.isRightPressed() ||
				event.MouseInput.isMiddlePressed()) &&
			getItemAtPos(m_pointer).i != getItemAtPos(m_old_pointer).i))) {
```

**Comment by OgelGames** [comment]
> There is a problem with the crafting using Shift when there is no more room

The intended behavior is if the items can't be shifted, they are picked up by the mouse, as if you were not pressing shift. Is it doing something other than that?

**Comment by srifqi** [comment]
If that is the case, it is fine for me. My first thought was that the crafting will be cancelled if there are no more rooms in the targetted inventory.

**Comment by OgelGames** [comment]
Yeah, better to use a nice even number than something specific to a certain stack size.

Also, middle click has been 10x for a long time, this PR just extended the functionality a bit ;)

**Comment by SwissalpS** [comment]
+1 for configurable amount per game.
It has been 10 for a long time and annoying for a long time. 9 makes most sense to me as that is mostly what I need (or a multiple thereof)

(many of the bugs and design 'errors' we fix have been there for a long time, mostly that doesn't stop us from changing them to the better)

Yes OgelGames, out of the scope of your great PR :D
