### PR TITLE
[no sq] Various improvements to the input handler

### LINKED ISSUE #16750: Cannot bind any game controls to mouse buttons 6 and above
### Luanti version

Image

### Operating system and version

Kubuntu 24.04

### CPU model

12 × AMD Ryzen 5 7600 6-Core Processor

### GPU model

AMD Radeon RX 7800 XT

### Active renderer

4.6 / opengl / SDL 2.32.58

### Summary

When binding controls to mouse buttons, button numbers 1-5 are accepted as expected. However, buttons 6 and onward (up to the maximum of 48 in X11 and Wayland) are not recognised by the game at all, and pressing these will cause nothing to happen.
Image

### Steps to reproduce

- Have a mouse with six or more buttons (ensuring that the nth button is bound to mouse button n accordingly) (you may alternatively use a script to create mouse button press events if you don't have one)
- Enter the key binding menu
- Attempt to bind something to one of these mouse buttons

### PR DESCRIPTION
**Pull request by y5nw**
The order of the commits is more or less outlined in https://github.com/luanti-org/luanti/issues/16750#issuecomment-3696865574. I chose to not open 3 pull requests as some commits (particularly the first commit) introduce changes that are obsoleted/removed in later ones.

* ~~Dropped: https://github.com/luanti-org/luanti/pull/16803#issuecomment-3716508977~~
* First commit: Adjustments, among other things:
  * `KeyPress::scancode` is renamed to `KeyPress::value`
  * `KeyPress::getType()` is introduced to get the type of input
  * Calls to `std::variant`-related functions and methods use indices (based on `getType()`) instead of types; this makes it easier to infer the type of input.
* Second commit: Adjusted version of #16215; changes from that PR are split between this commit and the previous commit to ease reviewing
* Third commit: Fixes #16750
  * The `EKEY_CODE` variant is removed from `KeyPress` as it is no longer needed
  * I have chosen to not merge LMB/MMB/RMB button events as a lot of (GUI-related) code have different paths based on the specific mouse button while the in-game input handler is practically the only place with a combined code path for all mouse buttons; in other words, there is IMO little to gain from merging LMB/MMB/RMB events.
  * The keycode migration is only handled in Lua. This allows differentiating mouse button migrations from pre-5.12 keycode migrations, the former of which does not require the user to reconfigure keybindings.

## To do

This PR is a Work in Progress.

## How to test

* First commit: :shrug:
* Second commit: Unbind keys from the keybinding menu and observe that touchscreen buttons continue to work
* Third commit:
  * Bind actions to mouse keys (particularly X1, X2, and beyond) and observe that these continue to work
  * Observe that settings with older mouse buttons (e.g. `keymap_autoforward = KEY_MBUTTON`) are automatically migrated (i.e. continue to work), and the user is not informed about the migration.

### CODE REVIEW

File: irr/include/IEventReceiver.h [hunk 1]
```diff
@@ -510,6 +532,9 @@ struct SEvent
 	//! Any kind of user event.
 	struct SUserEvent
 	{
+		//! The event code
+		s32 code;
```
Comment (sfan5) [inline irr/include/IEventReceiver.h]: this is `EUSER_EVENT_TYPE` I assume?

File: irr/include/IrrlichtDevice.h [hunk 2]
```diff
@@ -346,13 +345,16 @@ class IrrlichtDevice : public virtual IReferenceCounted
...
-	available, the corresponding Irrlicht keycode (represented by the EKEY_CODE component).
+	\return The implementation-dependent scancode for the key (represented by the u32 component) or 0 if a scancode is
+	not available.
 	*/
-	virtual std::variant<u32, EKEY_CODE> getScancodeFromKey(const Keycode &key) const {
+	virtual u32 getScancodeFromKey(const Keycode &key) const {
 		if (auto pv = std::get_if<EKEY_CODE>(&key))
 			return *pv;
-		return (u32)std::get<wchar_t>(key);
+		if (auto scancode = std::get<wchar_t>(key))
```
Comment (sfan5) [inline irr/include/IrrlichtDevice.h]: should be `get_if`? `get` will throw

File: irr/src/CIrrDeviceSDL.cpp [hunk 3]
```diff
@@ -940,54 +922,34 @@ bool CIrrDeviceSDL::run()
...
-				irrevent.EventType = EET_KEY_INPUT_EVENT;
-				irrevent.KeyInput.Key = KEY_XBUTTON1;
-				break;
-
-			case SDL_BUTTON_X2:
-				irrevent.EventType = EET_KEY_INPUT_EVENT;
-				irrevent.KeyInput.Key = KEY_XBUTTON2;
-				break;
+			default: // Other mouse buttons do not have dedicated events:
+				irrevent.MouseInput.Event = is_down ? EMIE_OMOUSE_PRESSED_DOWN : EMIE_OMOUSE_LEFT_UP;
```
Comment (sfan5) [inline irr/src/CIrrDeviceSDL.cpp]: should have `break` for consistency

File: src/client/inputhandler.cpp [hunk 4]
```diff
@@ -26,7 +26,7 @@ void MyEventReceiver::reloadKeybindings()
 	keybindings[KeyType::DIG] = getKeySetting("keymap_dig");
 	keybindings[KeyType::PLACE] = getKeySetting("keymap_place");
 
-	keybindings[KeyType::ESC] = std::vector<KeyPress>{EscapeKey};
+	keybindings[KeyType::ESC] = std::unordered_set<KeyPress>{EscapeKey};
```
Comment (sfan5) [inline src/client/inputhandler.cpp]: IIRC we talked about this and said that `vector` is more efficient than unordered_set for small counts?

File: src/client/inputhandler.cpp [hunk 5]
```diff
@@ -201,29 +203,27 @@ bool MyEventReceiver::OnEvent(const SEvent &event)
...
 			break;
 		case EMIE_MOUSE_WHEEL:
 			mouse_wheel += event.MouseInput.Wheel;
 			break;
 		default:
 			break;
 		}
+	} else if (event.EventType == EET_USER_EVENT && event.UserEvent.code == EUET_GAME_KEY) {
+		KeyPress keyCode(static_cast<GameKeyType>(event.UserEvent.UserData1));
+		setKeyDown(keyCode, event.UserEvent.UserData2);
```
Comment (sfan5) [inline src/client/inputhandler.cpp]:
```suggestion
		setKeyDown(keyCode, event.UserEvent.UserData2 != 0);
```

File: irr/src/CIrrDeviceSDL.cpp [hunk 6]
```diff
@@ -1098,6 +1054,7 @@ bool CIrrDeviceSDL::run()
 
 		case SDL_EVENT_USER:
```
Comment (sfan5) [inline irr/src/CIrrDeviceSDL.cpp:1058]: we don't actually use that from anywhere, correct?

Comment (y5nw) [reply irr/src/CIrrDeviceSDL.cpp:1058]: This is used by this PR to pass touchscreen button events (hence the introduction of `EUSER_EVENT_TYPE`)

Comment (sfan5) [reply irr/src/CIrrDeviceSDL.cpp:1058]: but not via `SDL_EVENT_USER` I mean, right?

File: src/client/inputhandler.cpp (hunk 4 above)
Comment (y5nw) [reply src/client/inputhandler.cpp]: Yes; I dropped that commit now

File: irr/src/CIrrDeviceSDL.cpp (hunk 6 above)
Comment (y5nw) [reply irr/src/CIrrDeviceSDL.cpp:1058]: Not via `SDL_EVENT_USER`. I dropped this in https://github.com/luanti-org/luanti/pull/16815/changes/7795783e2c72882d43a03139d01c16bc16a1a382 now.

---

(Side note: we apparently do not use `SDL_EVENT_USER` directly anywhere :shrug:)

File: irr/include/IEventReceiver.h (hunk 1 above)
Comment (y5nw) [reply irr/include/IEventReceiver.h]: Yes; corrected in https://github.com/luanti-org/luanti/pull/16815/changes/3f3dcfb6329632a94f6dac3934f27abe75cc6bb5

File: irr/include/IrrlichtDevice.h (hunk 2 above)
Comment (y5nw) [reply irr/include/IrrlichtDevice.h]: Corrected in https://github.com/luanti-org/luanti/pull/16815/changes/26fd447e0ec3b15f27daef1504135f6389468d9d

File: irr/src/CIrrDeviceSDL.cpp (hunk 3 above)
Comment (y5nw) [reply irr/src/CIrrDeviceSDL.cpp]: Added in https://github.com/luanti-org/luanti/pull/16815/changes/26fd447e0ec3b15f27daef1504135f6389468d9d

File: irr/include/IEventReceiver.h [hunk 7]
```diff
@@ -86,6 +86,17 @@ enum EEVENT_TYPE
 
 };
 
+//! Enumeration for "user" events (i.e. ones generated by Luanti itself
+enum EUSER_EVENT_TYPE
```
Comment (rubenwardy) [inline irr/include/IEventReceiver.h:90]: Should we start using `enum class` for new enums?

File: irr/include/IEventReceiver.h [hunk 8]
```diff
@@ -86,6 +86,17 @@ enum EEVENT_TYPE
 
 };
 
+//! Enumeration for "user" events (i.e. ones generated by Luanti itself
```
Comment (rubenwardy) [inline irr/include/IEventReceiver.h]:
```suggestion
//! Enumeration for "user" events (i.e. ones generated by Luanti itself)
```

**Review by rubenwardy — COMMENTED** [review]
Some high-level feedback on your PR. Some of this will be stuff for other PRs

* I think that KeyType should be replaced with an `enum class` called `Action` or `InputAction` or similar. This would mean there's no need for the `GameKeyType`. The class wrapping the enum is a hack due to `enum class` not being a thing yet when the code was written. KeyType is also confusing when we have KeyPress and it's not always a key causing the action.
* I think it's weird for KeyPress to have a game key / action value - KeyPress should hold raw input events and then be resolved using input binding to Actions. But I suppose it doesn't matter that much, and means your input methods can always just raise a KeyPress rather than the touchscreen being special cased to raise Actions.
* I'd like the input code to be moved to `src/client/input`

Something for later, but this PR only handles the action case - there's also movement and look direction. The way I solved this problem in my own games was to have an InputProvider interface with implementations for KB+M, touchscreen, and gamepad. The interface could raise actions and could also be queried for movement/look axes. You'd remember the most recently used provider to query for movement/etc - this way you could switch between input mechanisms pretty seamlessly

**Comment by y5nw** [comment]
> * I think that KeyType should be replaced with an `enum class` called `Action` or `InputAction` or similar. This would mean there's no need for the `GameKeyType`. The class wrapping the enum is a hack due to `enum class` not being a thing yet when the code was written. KeyType is also confusing when we have KeyPress and it's not always a key causing the action.

+1. Although I would prefer doing this in a follow-up PR.

> I think it's weird for KeyPress to have a game key / action value - KeyPress should hold raw input events and then be resolved using input binding to Actions.

The latter part is still done by the input handler. The game action variant for KeyPress is only for touchscreen input, for which there is no corresponding user input event that is also sensibly usable.

> But I suppose it doesn't matter that much, and means your input methods can always just raise a KeyPress rather than the touchscreen being special cased to raise Actions.

Fun fact: at some point decoupling touchscreen input from KB+M became my primary motivation for #16803; as it allows said decoupling to be done straightforwardly (i.e. appending a case to a `std::variant`) without adding special handling for touchscreens.

> * I'd like the input code to be moved to `src/client/input`

+1, but IMO this should also be part of a follow-up PR (potentially as the first one in another no-sq PR)

> Something for later, but this PR only handles the action case - there's also movement and look direction.

Movement can (in the short term) be relatively easily implemented by introducing analog input.

Camera rotation (and also movement to a certain extent) is harder in that

* Different modes of input provide values that are _interpreted_ differently. Joystick movements determine the _rate_ at which the camera rotates, while the movement in the relative position of the mouse _directly_ determines the difference in camera rotation.
* Camera rotation introduces certain properties beyond merely ranges (whether it is binary or more continuous).

Realistically I would consider leaving the camera rotation as-is in the short term (or adding camera rotations as bindable actions while keeping special treatment for mouse input). For the long(er) term there should ideally be a further abstraction level on top of input actions to allow creating/defining input types and the corresponding values (potentially relative differences or the rate of change), e.g.:

* Triggers (e.g. jump): passed from the current input handler
* Enums and continuous values (e.g. inventory selection, minimap mode): may consist of multiple actions:
  * Switching to the previous/next mode (e.g. previous/next inventory slot)
  * Selecting a specific value (e.g. specific inventory slot)
* Vector input (e.g. movement): may consist of multiple actions
* Spherical angle input (e.g. camera rotation): may consist of multiple actions

(Different types can be built on top of each other.)

> The way I solved this problem in my own games was to have an InputProvider interface with implementations for KB+M, touchscreen, and gamepad. The interface could raise actions and could also be queried for movement/look axes.

Do you have an example of how such an interface would look like?

**Comment by rubenwardy** [comment]
> Do you have an example of how such an interface would look like?

Here is the interface: https://gitlab.com/rubenwardy/rvwp/-/blob/master/src/client/input/IInputResolver.hpp?ref_type=heads#L12
The root resolver is called "InputController" (equiv of InputHandler) and it delegates to other resolvers (kb+m, gamepad, etc). See the other resolvers in that directory.

Worth noting this is for a game which is rendered in 2D so the camera case is simpler

Oh I did actually support binding - thor::ActionMap essentially is a util that helps go from a raw input (KeyPress) to an action

I'm not sure if this is the best approach - but it has the advantage of making all input mechanisms first-class citizens with a unified interface

File: irr/include/IEventReceiver.h (hunk 7 above)
Comment (y5nw) [reply irr/include/IEventReceiver.h:90]: Not in this particular case as I would like to keep this consistent with the rest of the Irrlicht codebase. That said, I did change `KeyPress::InputType` to an enum class.

**Comment by y5nw** [comment]
> Here is the interface: https://gitlab.com/rubenwardy/rvwp/-/blob/master/src/client/input/IInputResolver.hpp?ref_type=heads#L12 The root resolver is called "InputController" (equiv of InputHandler) and it delegates to other resolvers (kb+m, gamepad, etc). See the other resolvers in that directory.

Looking at this, I think this is simply a matter of unifying input handling at different abstraction layers: your input handler appears to use different resolvers to directly translate input buttons to actions, while the approach in this PR adds a layer in between that first unifies input events to a common class (i.e. `KeyPress`) and operate on that.

Ideally we should use a mix of the two approaches. The current `KeyPress`-based approach is IMO more straightforward for "simple" cases (i.e. basic binary/analog input for action-based abstractions): the event simply needs to be translated into a `KeyPress` value and passed to the input handler. Input resolver classes can be used to handle situations that basic action-based abstractions cannot accomodate (e.g. camera rotation, as stated above).

File: irr/include/IrrlichtDevice.h [hunk 9]
```diff
@@ -346,13 +345,16 @@ class IrrlichtDevice : public virtual IReferenceCounted
...
+	\return The implementation-dependent scancode for the key (represented by the u32 component) or 0 if a scancode is
+	not available.
 	*/
-	virtual std::variant<u32, EKEY_CODE> getScancodeFromKey(const Keycode &key) const {
+	virtual u32 getScancodeFromKey(const Keycode &key) const {
 		if (auto pv = std::get_if<EKEY_CODE>(&key))
 			return *pv;
-		return (u32)std::get<wchar_t>(key);
+		if (auto scancode = std::get_if<wchar_t>(&key))
+			return KEY_KEY_CODES_COUNT + *scancode;
```
Comment (sfan5) [inline irr/include/IrrlichtDevice.h:358]: is it documented somewhere (a comment is enough) that `KEY_KEY_CODES_COUNT` and beyond maps to wchar?

could maybe also define a separate `KEY_WCHAR = 10000`?

File: irr/src/CIrrDeviceSDL.cpp [hunk 10]
```diff
@@ -942,54 +924,35 @@ bool CIrrDeviceSDL::run()
 			if (button == SDL_BUTTON_X2)
 				button = SDL_BUTTON_RIGHT;
 #endif
+			irrevent.MouseInput.Button = button;
+			auto is_down = SDL_event.type == SDL_EVENT_MOUSE_BUTTON_DOWN;
```
Comment (sfan5) [inline irr/src/CIrrDeviceSDL.cpp:928]: this works with SDL3, right?

File: src/client/keycode.cpp [hunk 11]
```diff
@@ -302,58 +293,102 @@ KeyPress::KeyPress(const std::string &name)
...
+	case EMIE_RMOUSE_PRESSED_DOWN:
+	case EMIE_OMOUSE_PRESSED_DOWN:
+	case EMIE_LMOUSE_LEFT_UP:
+	case EMIE_MMOUSE_LEFT_UP:
+	case EMIE_RMOUSE_LEFT_UP:
+	case EMIE_OMOUSE_LEFT_UP:
+		emplace<InputType::MOUSE_BUTTON>(in.Button);
+		break;
+	default:
+		emplace<InputType::MOUSE_BUTTON>(0);
```
Comment (sfan5) [inline src/client/keycode.cpp]: `assert(false)` here?

File: irr/src/CIrrDeviceSDL.cpp (hunk 10 above)
Comment (y5nw) [reply irr/src/CIrrDeviceSDL.cpp:928]: Yes. These are actually used by [SDL3](https://wiki.libsdl.org/SDL3/SDL_MouseButtonEvent); `CIrrDeviceSDL.h` has macros that `#define` them for SDL2: https://github.com/luanti-org/luanti/blob/c432281ac0be5100d1eec33374c90b38407c7646/irr/src/CIrrDeviceSDL.cpp#L55-L56

File: irr/include/IrrlichtDevice.h (hunk 9 above)
Comment (y5nw) [reply irr/include/IrrlichtDevice.h:358]: Added a comment in https://github.com/luanti-org/luanti/pull/16815/changes/39b3c6cc3b5ce9ea850a6bc6e86e0f4d9d07f5db

(As noted, this is a dummy for (IIRC) the null driver. It is not actually used by the SDL device.)

File: src/client/keycode.cpp (hunk 11 above)
Comment (y5nw) [reply src/client/keycode.cpp]: Makes sense. Done in https://github.com/luanti-org/luanti/pull/16815/changes/39b3c6cc3b5ce9ea850a6bc6e86e0f4d9d07f5db

**Review by sfan5 — APPROVED** [review]
Tested a bit, seems ok.

File: src/client/keycode.cpp [hunk 12]
```diff
@@ -302,58 +293,102 @@ KeyPress::KeyPress(const std::string &name)
...
+			return strgettext(name);
+		if (scancode)
+			return fmtgettext("Scancode: %d", scancode);
+		return "";
+	}
+	case InputType::MOUSE_BUTTON: {
+		auto button = get<InputType::MOUSE_BUTTON>();
+		switch (button) {
+		case SDL_BUTTON_LEFT:
+			return strgettext("Left Click");
```
Comment (SmallJoker) [inline src/client/keycode.cpp:347]: Needs a `// TRANSLATORS: Mouse button` prefix like there was before.

File: builtin/mainmenu/dlg_rebind_keys.lua [hunk 13]
```diff
@@ -72,15 +72,32 @@ local function create_rebind_keys_dlg()
 	return dlg
 end
 
+local compatible_keycodes = {
+	-- Keycodes that can be substituted without requiring potential manual reconfiguration
+	KEY_LBUTTON = "MOUSE_BUTTON_1",
```
Comment (SmallJoker) [inline builtin/mainmenu/dlg_rebind_keys.lua:77]: Why 1,2,3,4,5 when L,M,R,X1,X2 would be self-explaining?

File: irr/include/IEventReceiver.h [hunk 14]
```diff
@@ -98,6 +109,9 @@ enum EMOUSE_INPUT_EVENT
 	//! Middle mouse button was pressed down.
 	EMIE_MMOUSE_PRESSED_DOWN,
 
+	//! A mouse button beyond LMB/MMB/RMB was pressed down.
+	EMIE_OMOUSE_PRESSED_DOWN,
```
Comment (SmallJoker) [inline irr/include/IEventReceiver.h]: The other buttons are called X1 and X2, so shouldn't this better be named `XMOUSE`?

File: src/client/keycode.h [hunk 15]
```diff
@@ -17,61 +18,84 @@
...
+
+	template<InputType I>
+	std::add_pointer_t<const value_alternative_t<I>> getIf() const {
+		return std::get_if<static_cast<size_t>(I)>(&value);
+	}
+
+	template<InputType I>
+	void emplace(value_alternative_t<I> newValue) {
+		value.emplace<static_cast<size_t>(I)>(newValue);
+	}
```
Comment (SmallJoker) [inline src/client/keycode.h:102]: IMO variants and these C++17 features (I presume?) make the code very difficult to understand. Maybe it's just me.
Could you please add a few comments to explain what the functions do and what values are?

File: src/client/keycode.h [hunk 16]
```diff
@@ -17,61 +18,84 @@
...
 	}
 
+	// Check whether the keypress is valid
+	operator bool() const;
+
 	static KeyPress getSpecialKey(const std::string &name);
 
 private:
-	using value_type = std::variant<u32, EKEY_CODE>;
+	using value_type = std::variant<u32, u32, GameKeyType>;
```
Comment (SmallJoker) [inline src/client/keycode.h:77]: Out of interest: How can the first `u32` be distinguished from the 2nd one?

File: irr/include/IEventReceiver.h [hunk 17]
```diff
@@ -320,9 +331,17 @@ struct SEvent
...
+		union {
+			//! mouse wheel delta, often 1.0 or -1.0, but can have other values < 0.f or > 0.f;
+			/** Only valid if event was EMIE_MOUSE_WHEEL */
+			f32 Wheel;
+
+			/** The mouse button that was pressed down or left up.
+			 * Only valid for events where a mouse button is pressed down or left up.
+			 * Note that there are dedicated events for the LMB/MMB/RMB being pressed down or left up.
+			 */
+			u32 Button;
```
Comment (SmallJoker) [inline irr/include/IEventReceiver.h:343]: It would be easier to understand this value by having `SDL_BUTTON_*` part of an enum, such that you could use a type as hint here.

File: irr/include/IEventReceiver.h [hunk 18]
```diff
@@ -320,9 +331,17 @@ struct SEvent
...
-		f32 Wheel;
+		union {
+			//! mouse wheel delta, often 1.0 or -1.0, but can have other values < 0.f or > 0.f;
+			/** Only valid if event was EMIE_MOUSE_WHEEL */
+			f32 Wheel;
+
+			/** The mouse button that was pressed down or left up.
+			 * Only valid for events where a mouse button is pressed down or left up.
+			 * Note that there are dedicated events for the LMB/MMB/RMB being pressed down or left up.
+			 */
```
Comment (SmallJoker) [inline irr/include/IEventReceiver.h]:
```suggestion
			/** Changed mouse button.
			 * Only valid for events EMIE_*MOUSE_PRESSED_DOWN and EMIE_*MOUSE_LEFT_UP.
			 * See also: dedicated events, EMOUSE_INPUT_EVENT
			 */
```

File: irr/include/IEventReceiver.h [hunk 19]
```diff
@@ -86,6 +86,17 @@ enum EEVENT_TYPE
 
 };
 
+//! Enumeration for "user" events (i.e. ones generated by Luanti itself)
+enum EUSER_EVENT_TYPE
```
Comment (SmallJoker) [inline irr/include/IEventReceiver.h:90]: Idea: This could be changed to an empty enum with a fixed size (`u32`?) such that Luanti can freely define/extend its values without touching the Irrlicht side.

File: builtin/mainmenu/dlg_rebind_keys.lua (hunk 13 above)
Comment (y5nw) [reply builtin/mainmenu/dlg_rebind_keys.lua:77]: `MOUSE_BUTTON_<num>` is easier to handle internally (compare e.g. scancodes; these are ultimately not user-facing values, unlike e.g. descriptions) and also works with more than 5 buttons.

(A generic `X<n-3>` could work for higher values, but it seems counter-intuive to me.)

File: irr/include/IEventReceiver.h (hunk 14 above)
Comment (y5nw) [reply irr/include/IEventReceiver.h]: Makes sense. (I considered `O` for "other".)

File: src/client/keycode.h (hunk 16 above)
Comment (y5nw) [reply src/client/keycode.h:77]: These are differentiated based on the index, hence the `InputType` enum and the corresponding getter/setter methods you mentioned above.

File: irr/include/IEventReceiver.h (hunk 17 above)
Comment (y5nw) [reply irr/include/IEventReceiver.h:343]: The `SDL_BUTTON_*` values are copied from https://wiki.libsdl.org/SDL3/SDL_MouseButtonFlags as the Luanti source (which also includes this header file) does not have access to SDL3 yet. The best we could do here would be to also copy over the `typedef` for now, but the use of that would be limited in terms of type hints.

File: irr/include/IEventReceiver.h (hunk 18 above)
Comment (y5nw) [reply irr/include/IEventReceiver.h]: (https://github.com/luanti-org/luanti/pull/16815/changes/800afe3c067f0843f5d9ca26093262d7d0fa7fb1)

File: src/client/keycode.h (hunk 15 above)
Comment (y5nw) [reply src/client/keycode.h:102]: I added an explanation to the first commit: https://github.com/luanti-org/luanti/pull/16815/changes/bb3b60d780d779007f7357186814eeb4076f268c#diff-45fd6859795ab8aa68e30315b2bff1613e2cecca793e55d27184e0373fbf7181R77-R79

File: src/client/keycode.h (hunk 16 above)
Comment (y5nw) [reply src/client/keycode.h:77]: https://github.com/luanti-org/luanti/pull/16815#discussion_r3039869521

File: src/client/keycode.cpp (hunk 12 above)
Comment (y5nw) [reply src/client/keycode.cpp:347]: https://github.com/luanti-org/luanti/pull/16815/changes/800afe3c067f0843f5d9ca26093262d7d0fa7fb1#diff-2c34fd65694371b6718661b20786667b477437b03302c166997f05ff2a17892bR352-R360

File: irr/include/IEventReceiver.h (hunk 14 above)
Comment (y5nw) [reply irr/include/IEventReceiver.h]: Done (squashed into https://github.com/luanti-org/luanti/pull/16815/changes/b97d019b20915874ea23d9fa92a992a676ca41da)

File: src/client/keycode.h (hunk 15 above)
Comment (SmallJoker) [reply src/client/keycode.h:102]: Thank you. That makes it easier to understand.

File: builtin/mainmenu/dlg_rebind_keys.lua (hunk 13 above)
Comment (SmallJoker) [reply builtin/mainmenu/dlg_rebind_keys.lua:77]: I see. You're using `KeyPress::loadUnsignedFromPrefix` to map the numbers to the the integer value used by `SDL_BUTTON_*`. This relation is not immediately obvious but at the moment I have no idea how this could be improved - aside from the enum lookup table approach that's being used for most Lua <--> C++ conversions.

File: irr/include/IEventReceiver.h (hunk 19 above)
Comment (y5nw) [reply irr/include/IEventReceiver.h:90]: Another idea here would be to use `s32` (used by SDL's `SDL_UserEvent` in case we want to use that in the future) here and define the actual enum in the Luanti part.

File: builtin/mainmenu/dlg_rebind_keys.lua (hunk 13 above)
Comment (y5nw) [reply builtin/mainmenu/dlg_rebind_keys.lua:77]: I would leave this as-is for now. These are ultimately not user-facing strings, so I don't think the mapping work has a high priority at the moment.

IMO it would make more sense to introduce mouse button names along with scancode names in a separate PR, which would need to wait for SDL headers (for the scancode macros) to be made available to the Luanti source.

File: irr/include/IEventReceiver.h (hunk 19 above)
Comment (SmallJoker) [reply irr/include/IEventReceiver.h:90]: Hm that makes sense too. I don't have any particular preference - the current code may as well stay as-is. Up to you :)

Comment (y5nw) [reply irr/include/IEventReceiver.h:90]: I suppose I will leave it as-is then. I think this will remain the only user event for quite a while, so I don't think user event passing/handling needs to be formalized now.
