### PR TITLE
Bunch of minor fixes

### LINKED ISSUE #10726: Fix errors found by professional static code analyzer
Not so long ago Minetest was checked by the professional static code analyzer called PVS-Studio. The developers published some of the errors they have found in their blog: https://www.viva64.com/en/b/0751/#ID2E6FF31CDC. I think Minetest developers should take them into account and, if possible, fix them.

Please note that I am not a representative of PVS-Studio. I came across this article by chance and thought I should inform developers about the errors. The blog also recommends a full analysis but I'm not sure Minetest can afford it.

### PR DESCRIPTION
**Pull request by sfan5**
closes #10726

Also fixes the following warning:
<pre>
CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.
</pre>
Looking at https://pkgs.org/search/?q=cmake even the most outdated distros (CentOS 6, Ubuntu 14.04) have at least CMake 3.5 installable.

## To do

This PR is a Ready for Review.

### CODE REVIEW

**Comment by lhofhansl** [comment]
Looks good.

File: src/client/content_cao.cpp [hunk 1]
```diff
@@ -1174,7 +1174,7 @@ void GenericCAO::step(float dtime, ClientEnvironment *env)
 	}
 
 	if (!getParent() && m_prop.automatic_face_movement_dir &&
-			(fabs(m_velocity.Z) > 0.001 || fabs(m_velocity.X) > 0.001)) {
+			(fabs(m_velocity.Z) > 0.001f || fabs(m_velocity.X) > 0.001f)) {
```
Comment (kilbith) [inline src/client/content_cao.cpp:1177]: In the end, the floating point registers are internally 80-bit wide anyway. There's no benefit to append the `f`.

Comment (randomMesh) [reply src/client/content_cao.cpp:1177]: > There's no benefit to append the `f`.

It's cleaner to append the 'f', so you can see that's a float and not a double at the first sight.

Comment (sfan5) [reply src/client/content_cao.cpp:1177]: Checking the disassembly, gcc 10.2 generates an extra "Convert Scalar Single-Precision Floating-Point Value to Scalar Double-Precision Floating-Point Value" instruction when using `0.001` over `0.001f`:
```diff
 	c5 f8 54 c1          	vandps xmm0,xmm0,xmm1
-	c5 f8 2e 05 00 00 00 00 	vucomiss xmm0,DWORD PTR [rip+0x0]        # <_ZN10GenericCAO4stepEfP17ClientEnvironment+0xdcb>
-	0f 86 af 00 00 00    	jbe    <_ZN10GenericCAO4stepEfP17ClientEnvironment+0xe80>
+	c5 fa 5a c0          	vcvtss2sd xmm0,xmm0,xmm0
+	c5 f9 2e 05 00 00 00 00 	vucomisd xmm0,QWORD PTR [rip+0x0]        # <_ZN10GenericCAO4stepEfP17ClientEnvironment+0xdcf>
+	0f 86 af 00 00 00    	jbe    <_ZN10GenericCAO4stepEfP17ClientEnvironment+0xe84>
 	49 8b 06             	mov    rax,QWORD PTR [r14]
```

Comment (kilbith) [reply src/client/content_cao.cpp:1177]: So you should be caring about unsigned values that should be `U`´d or ˋUL` if there’s one instruction more...

Comment (sfan5) [reply src/client/content_cao.cpp:1177]: I think gcc can convert signed constants to unsigned but it is not allowed to do so for double -> float since it loses precision.
