### PR TITLE
[no squash] Divorce map database locking from env lock

### LINKED ISSUE #15125: Busy Disks Cause Lag
### Minetest version

```true
Minetest 5.9.0 (Linux)
Using LuaJIT 2.1.0-beta3
Built by GCC 12.2
Running on Linux/6.1.0 x86_64
BUILD_TYPE=RelWithDebInfo
RUN_IN_PLACE=1
USE_CURL=1
USE_GETTEXT=1
USE_SOUND=1
STATIC_SHAREDIR="."
STATIC_LOCALEDIR="locale"
```

### Irrlicht device

N/A (happens on both SP and dedicated servers)

### Operating system and version

Debian 12, various Alpine versions, etc.

### CPU model

Various (Intel i5-3320M (4) @ 3.300GHz, AMD EPYC 7282 (4) @ 2.794GHz, Intel i5-2400 (4) @ 3.400GHz, etc)

### GPU model

N/A (happens on both SP and dedicated servers)

### Active renderer

N/A (happens on both SP and dedicated servers)

### Summary

Background disk activity causes main thread lag on MT servers.

It seems like this may be somewhat worse on some versions than others, but it's present in all versions.

This can significantly worsen the player experience when doing certain things like backups or database maintenance.

Given that MT is already very asynchronous and non-durable (things like map emerge APIs are all async, and writes like mod_storage are already deferred to a timer) there is no reason why the main game thread should ever be waiting on the disk.

### Steps to reproduce

- Install szutilpack from CDB and enable szutil_lagometer for a world.
- Load up the world.
- Run the /lagometer command to enable the lagometer.
- Fly around, loading up terrain.  Note the baseline lag profile.
- Quit the world and restart it (mapblocks are now unloaded again).
- Start a disk-intensive process in the background, like bonnie++.
- Fly around, loading up terrain.  Note the new lag profile.

### Observed

Lag goes through the roof.  You might have some main thread globalsteps that take several seconds to complete.

### Expected

Unloaded terrain remains unloaded for longer, as the disk takes time to respond, but globalstep continues in the meantime.  Lag should remain at roughly the same baseline level as with a quiescent disk.

### PR DESCRIPTION
**Pull request by sfan5**
this means the whole server isn't blocked by map loading

for the record: map saving still happens in the server thread

addresses a big point brought up in #15125

## To do

This PR is Ready for Review.

## How to test

```diff
diff --git a/src/database/database-sqlite3.cpp b/src/database/database-sqlite3.cpp
--- a/src/database/database-sqlite3.cpp
+++ b/src/database/database-sqlite3.cpp
@@ -289,6 +289,8 @@ void MapDatabaseSQLite3::loadBlock(const v3s16 &pos, std::string *block)
        sqlite3_step(m_stmt_read);
        // We should never get more than 1 row, so ok to reset
        sqlite3_reset(m_stmt_read);
+
+       usleep(50*1000);
 }
 
 void MapDatabaseSQLite3::listAllLoadableBlocks(std::vector<v3s16> &dst)
```
1. apply patch, notice how loading is slow as shit but you can still interact with the world

2. check that map loading/saving works correctly generally

```diff
diff --git a/src/script/cpp_api/s_env.cpp b/src/script/cpp_api/s_env.cpp
--- a/src/script/cpp_api/s_env.cpp
+++ b/src/script/cpp_api/s_env.cpp
@@ -54,6 +54,8 @@ void ScriptApiEnv::environment_Step(float dtime)
        // Call callbacks
        lua_pushnumber(L, dtime);
        runCallbacks(1, RUN_CALLBACKS_MODE_FIRST);
+
+       usleep(50*1000);
 }
 
 void ScriptApiEnv::player_event(ServerActiveObject *player, const std::string &type)
```
3. apply different patch, notice how the server is laggy but the world still loads reasonably fast

### CODE REVIEW

**Comment by swagtoy** [comment]
Sorry to ask, but could we get this in a point release? I think its quite serious, esp. considering 5.9.0 got lots of performance improvements, this would fit with it well?

**Comment by sfan5** [comment]
Too high risk for a point release. If you want the latest improvements, use 5.10-dev on your server.

File: src/servermap.cpp [hunk 1]
```diff
@@ -693,47 +706,50 @@ void ServerMap::loadBlock(std::string *blob, v3s16 p3d, MapSector *sector, bool
...
+	// We just loaded it, so it's up-to-date.
+	block->resetModified();
+}
+
+MapBlock* ServerMap::loadBlock(v3s16 blockpos)
+{
+	std::string data;
+	{
+		ScopeProfiler sp(g_profiler, "ServerMap: load block - sync (sum)");
+		MutexAutoLock dblock(m_db.mutex);
```
Comment (nerzhul) [inline src/servermap.cpp:739]: i don't like this, we should instead implement this locking directly in the m_db class to prevent missing locking from callers

**Comment by nerzhul** [comment]
It's  a good improvement, but it increase the risk on busy disks to be desync, anyway, commented the PR , i think we need to go more forward and hide MapDatabase calls completely with this holder which will decide if locking is required or not for each call

File: src/servermap.cpp (hunk 1 above)
Comment (sfan5) [reply src/servermap.cpp:739]: this can be done in the future but I opted not to do it here

**Comment by Warr1024** [comment]
I've noticed one potential problem.  When running this PR, if you create artificial busy lag in the main thread (e.g. using the `/lag 0.1` command from szutil_lag in [szutilpack](https://content.minetest.net/packages/Warr1024/szutilpack/)) it seems like mapblocks emerge much slower, even when the disk is not busy.

File: src/servermap.cpp (hunk 1 above)
Comment (nerzhul) [reply src/servermap.cpp:739]: if you put that on a roadmap somewhere i'm fine, just to make it not lost (and i may work on it after)

Comment (sfan5) [reply src/servermap.cpp:739]: I wrote it down in a todo comment in bbb3fa37fd0e3a6f8d443d433734624d38ec894e

**Comment by Desour** [comment]
Rebased the profiling branch from <https://github.com/minetest/minetest/issues/15125#issuecomment-2339377892> onto rebased PR:
https://github.com/Desour/minetest/tree/tracy_profiling_pr_tmp2_sfan5_whywasitthisway

Issue doesn't look fixed. `initBlockMake` is still keeping the env lock.
(And #15125 is after than still relevant, because map (and auth) saving sometimes costs half a second or so. Super expensive for my taste (I want 60Hz).)

**Comment by sfan5** [comment]
> Issue doesn't look fixed. `initBlockMake` is still keeping the env lock.

There are still calls to `emergeBlock` left, sure. VManips famously synchronously load the map.
In this specific case it tries to load relevant blocks before invoking mapgen. This is much harder to convert to an async approach.

**Comment by Warr1024** [comment]
> I've noticed one potential problem. [under artificial CPU load] ... it seems like mapblocks emerge much slower, even when the disk is not busy.

I noticed sfan5 reacted with 😕 so I'll try to clarify:

The `szutil_lag` mod creates artificial server-side lag by basically just running a `while minetest.get_us_time() < start + delay do end` loop and busy-waiting.  This simulates what happens when there's a lua-side CPU bottleneck, which is very useful for testing issues that are lag-dependent.  While this test was done under "laboratory conditions" I believe it could correspond to a realistic scenario where a server is persistently slightly laggy every step, e.g. due to having a lot of entities running heavy mob mod code, which is a pretty common use-case.  The player experience of steady low-level lag like this (e.g. when dtime is ~150ms even though dedicated_step is 0.09 or less) is not normally disastrous to gameplay, but if it causes map loading to slow down a lot, that could change.

As for _why_ this might be happening, I'm not entirely sure.  I assume that all lua mod code runs under env lock, as it's not uncommon for mod code to make hundreds to thousands of calls that require env lock, and it wouldn't make sense to acquire/release each time.  It seems like now the main thread running lua code can starve the emerge threads of access to env lock.  Maybe this is caused by some kind of race condition, or a change in an existing one due to the emerge thread no longer acquiring and holding the lock _immediately_.  If we acquire and release the lock once for _each mapblock_, then I'd expect to see behavior like this, as the lua thread is always ready to reacquire the lock.

N.B. we have now experienced this problem real-world on NodeCore Community, where I was testing out the patch.  With only like 1 to 3 players connected, everything runs great, and the patched version is noticeably better than 5.9.0.  Once we get up to about 5 players, the server is now getting almost no steps smaller than its dedicated_step setting of 0.05, and suddenly mapblock loading slows to a crawl and players can't travel.  I'll have to remove the patch for now.

**Comment by sfan5** [comment]
> I noticed sfan5 reacted with 😕 so I'll try to clarify:

It sounded a lot like a "if I create lag, there is lag" situation, but your explanation makes sense. I'll try to look into this.

File: src/emerge.cpp [hunk 2]
```diff
@@ -673,9 +679,38 @@ void *EmergeThread::run()
...
+				MutexAutoLock dblock(m_db.mutex);
+				m_db.loadBlock(pos, data);
+			}
+			if (!data.empty()) {
+				MutexAutoLock envlock(m_server->m_env_mutex);
+				m_map->loadBlock(data, pos);
+			}
+			// We took our shot, check again:
+			disk_tried = true;
+			goto retry;
```
Comment (Desour) [inline src/emerge.cpp:703]: Would be easier to understand control flow, imo:
```suggestion
			// We took our shot, check again:
			action = getBlockOrStartGen(pos, false, allow_gen, &block, &bmdata);
			if (action == EMERGE_FROM_MEMORY) {
				// great, but correct the status in case we just loaded it
				action = EMERGE_FROM_DISK;
			}
```

File: src/servermap.cpp [hunk 3]
```diff
@@ -693,47 +706,50 @@ void ServerMap::loadBlock(std::string *blob, v3s16 p3d, MapSector *sector, bool
...
 	}
-}
-
-MapBlock* ServerMap::loadBlock(v3s16 blockpos)
-{
-	ScopeProfiler sp(g_profiler, "ServerMap: load block", SPT_AVG, PRECISION_MICRO);
-	bool created_new = (getBlockNoCreateNoEx(blockpos) == NULL);
 
-	v2s16 p2d(blockpos.X, blockpos.Z);
+	assert(block);
```
Comment (Desour) [inline src/servermap.cpp:710]: Not true if failed to read mapblock version.

File: src/servermap.cpp [hunk 4]
```diff
@@ -693,47 +706,50 @@ void ServerMap::loadBlock(std::string *blob, v3s16 p3d, MapSector *sector, bool
...
 			dispatchEvent(event);
 		}
 	}
-	return block;
+
+	if (save_after_load)
+		saveBlock(block);
+
+	// We just loaded it, so it's up-to-date.
+	block->resetModified();
```
Comment (Desour) [inline src/servermap.cpp:731]: Should this really happen if block was already in memory?

File: src/server.cpp [hunk 5]
```diff
@@ -385,6 +385,7 @@ Server::~Server()
 		// Note that this also deletes and saves the map.
 		delete m_env;
 		m_env = nullptr;
+		m_emerge.reset();
```
[the remark this answers is not in the document]
Comment (sfan5) [reply src/server.cpp:388]: maybe, but how would I do that?

File: src/emerge.cpp [hunk 6]
```diff
@@ -673,9 +679,38 @@ void *EmergeThread::run()
 			continue;
 
 		bool allow_gen = bedata.flags & BLOCK_EMERGE_ALLOW_GEN;
+		bool disk_tried = false;
 		EMERGE_DBG_OUT("pos=" << pos << " allow_gen=" << allow_gen);
 
-		action = getBlockOrStartGen(pos, allow_gen, &block, &bmdata);
+retry:
```
[the remark this answers is not in the document]
Comment (sfan5) [reply src/emerge.cpp:685]: I will change this anyway as it's probably part of the locking problem

File: src/servermap.cpp (hunk 4 above)
Comment (sfan5) [reply src/servermap.cpp:731]: after deserializing the in-memory block will match the db, so yes

**Comment by Desour** [comment]
> > Issue doesn't look fixed. `initBlockMake` is still keeping the env lock.
> 
> There are still calls to `emergeBlock` left, sure. VManips famously synchronously load the map. In this specific case it tries to load relevant blocks before invoking mapgen. This is much harder to convert to an async approach.

Could do something like:
* Get list of block positions in inited area that are not in memory. (needs env lock for map)
* Without env lock, load blocks these positions from db.
* Pass pos to block data map as argument to `initBlockMake`.

Anyway, it's fine with me if that's fixed in another PR.

It would be nice if one day, the `loadBlock(blob,...` would be an `insertBlock(block,...`, and deserialzation and reflow scan would also happen without env lock.

File: src/server.cpp (hunk 5 above)
[the remark this answers is not in the document]
Comment (sfan5) [reply src/server.cpp:388]: guess I'll just add an `initMap(nullptr)` call

[the remark this answers is not in the document]
Comment (Desour) [reply src/server.cpp:388]: Does `m_env` also use `m_emerge`?

Could also use `shared_ptr` for the db holder, btw..

File: src/servermap.cpp (hunk 4 above)
Comment (Desour) [reply src/servermap.cpp:736]: Oh right, it overwrites the block.

But isn't overwriting the existing block wrong? Example:
* [emerge thread] checks for block existence (with env lock), it's not there
* [emerge thread] loads block from db
* [server thread] loads vmanip at block => loads block
* [server thread] sets node in block
* [emerge thread] inserts its old block from db with loadBlock => set-node from server thread is lost

Comment (sfan5) [reply src/servermap.cpp:736]: should be fixed, I also got rid of the goto

File: src/servermap.cpp [hunk 7]
```diff
@@ -654,31 +687,16 @@ void ServerMap::loadBlock(std::string *blob, v3s16 p3d, MapSector *sector, bool
 		}
 
 		{
-			ScopeProfiler sp(g_profiler, "ServerMap: deSer block", SPT_AVG, PRECISION_MICRO);
-			block->deSerialize(is, version, true);
+			std::istringstream iss(blob, std::ios_base::binary);
+			deSerializeBlock(block, iss);
 		}
```
Comment (Desour) [inline src/servermap.cpp:692]: Don't you want a try catch here?
This can still throw, leaving `block` null.

File: src/emerge.cpp [hunk 8]
```diff
@@ -643,7 +674,8 @@ void *EmergeThread::run()
 	BEGIN_DEBUG_EXCEPTION_HANDLER
 
 	v3s16 pos;
-	std::map<v3s16, MapBlock *> modified_blocks;
+	std::map<v3s16, MapBlock*> modified_blocks;
+	std::string databuf;
```
Comment (Desour) [inline src/emerge.cpp:678]: Why declared here?

File: src/emerge.cpp [hunk 9]
```diff
@@ -524,21 +537,39 @@ bool EmergeThread::popBlockEmerge(v3s16 *pos, BlockEmergeData *bedata)
...
-		*block = m_map->loadBlock(pos);
-		if (*block && (*block)->isGenerated())
+		if (!from_db) {
+			// 2). We should attempt loading it
 			return EMERGE_FROM_DISK;
+		}
+		// 2). Second invocation, we have the data
+		if (!from_db->empty()) {
+			*block = m_map->getBlockNoCreateNoEx(pos);
+			if (*block) {
```
Comment (Desour) [inline src/emerge.cpp:562]: This is (almost?) the same as at `1).`, so redundant.

(The claim I made about the data race might've been wrong. I didn't check back then if block existence was already checked in this function.)

File: src/emerge.cpp (hunk 8 above)
Comment (sfan5) [reply src/emerge.cpp:678]: no need to constantly reallocate

File: src/emerge.cpp (hunk 9 above)
Comment (sfan5) [reply src/emerge.cpp:562]: right.
the data race in the previous revision was real.

File: src/servermap.cpp (hunk 7 above)
Comment (sfan5) [reply src/servermap.cpp:692]: it is in a try-catch?

File: src/emerge.cpp [hunk 10]
```diff
@@ -185,10 +186,22 @@ SchematicManager *EmergeManager::getWritableSchematicManager()
...
+	FATAL_ERROR_IF(m_db, "Map database already initialized.");
+	assert(holder->dbase);
+	m_db = holder;
+}
+
+void EmergeManager::initMap(std::nullptr_t)
+{
+	FATAL_ERROR_IF(m_threads_active, "Thread are still active.");
+	m_db = nullptr;
+}
```
[the remark this answers is not in the document]
Comment (sfan5) [reply src/emerge.cpp:200]: I don't think it's that strange but can change if you want

File: src/servermap.cpp (hunk 7 above)
Comment (Desour) [reply src/servermap.cpp:692]: I mean a smaller try catch block.

(Ah, but I'm seeing now, block gets `createBlankBlockNoInsert`-ed before an exception can happen, so it won't be null. But making the try catch block as small as possible would still be cleaner.)

**Comment by sfan5** [comment]
> It seems like now the main thread running lua code can starve the emerge threads of access to env lock.

I debugged this problem and you are correct.
With this PR the EmergeThread spends a flat 30ms waiting for the env lock. On master it's 1-5ms. No wonder it doesn't get anything done.
(That is with 50ms of sleep in `on_globalstep`)

Given the severity this will need to be solved before merging the PR. `std::mutex` is not a fair lock, so we'll need to replace it.

**Comment by sfan5** [comment]
bad news: throwing in a fair lock gets this time down to 10-20ms which is still unplayable.

**Comment by Desour** [comment]
Please add `try_lock()`, and fulfill the *Mutex* named requirement. (Tracy's `TracyLockable` needs this.)

Btw. the we don't need the MutexAutoLock typedef stuff anymore. In C++17, the type gets auto deduced, so you can just replace it with `std::unique_lock` everywhere (or better `std::lock_guard`, which is simpler).

**Comment by Warr1024** [comment]
Tested 904a9eccda61a044a585a9c09c7a8d9d048bc307.  I can't tell if there's a difference from the previous version.

- Mitigation for "busy disk" scenario still seems moderately good.
- Mitigation for "busy CPU" scenario still seems pretty bad.

I don't have a good objective way to measure terrain loading (I'm just watching blocks load in) but it remains incredibly slow.  At /lag of 0.2 I'm seeing only a negligible amount of terrain loading (not enough reach actual terrain features) before the 5 second teleport interval fires.

**Comment by sfan5** [comment]
> Please add `try_lock()`, and fulfill the _Mutex_ named requirement.

done

> I don't have a good objective way to measure terrain loading but it remains incredibly slow

Requesting output with `profiler_print_interval = 5`.

File: src/server.cpp [hunk 11]
```diff
@@ -1100,6 +1103,50 @@ void Server::Receive(float timeout)
...
+	 *
+	 * Workaround: If we detect that the server is overloaded, introduce some careful
+	 * artificial sleeps to leave the emerge thread(s) enough chance to do their job.
+	 *
+	 * In the future the emerge code could be reworked to exclusively use a result
+	 * queue, thereby avoiding this problem.
+	 */
+
+	if (dtime < getStepSettings().steplen)
+		return;
```
[the remark this answers is not in the document]
Comment (sfan5) [reply src/server.cpp:1126]: I get the intent to avoid enabling this due to random fluctuations, but the suggestion is wrong.
Lock contention starts happening as soon as there is no sleep time in the ServerThread, this is precisely when dtime > steplen.

> Also, this check should be in ServerThread::run

I'll move it there

> because there we have more knowledge about how long things actually took.

however isn't it subtly wrong when I don't include the time spent on `Receive`?

**Comment by sfan5** [comment]
> I'm not quite sure what the gain of the EnvAutoLock is supposed to be, why encapsulate the lock like this?

In this case it allows me to swap out the env lock without worrying about the call sites, but it's also good practice in general IMO.

File: src/server.cpp (hunk 11 above)
[the remark this answers is not in the document]
Comment (Desour) [reply src/server.cpp]: The emerge thread may even be already suffering if the dtime is almost the target dtime.

You could measure in `Server::Receive()` how long it has been waiting for packets (and maybe use `TryReceive` before as long as possible). And if the sleep time is not long enough, do the `yieldToOtherThreads`. Shouldn't be hard.

**Comment by Warr1024** [comment]
Tested against f5e78689d7f1079710181b826ff86d2844331743.

Under normal load:

screenshot_20240921_103533

Disks saturated:

screenshot_20240921_103718

Artificial 0.2s/step CPU lag:

screenshot_20240921_103902

It feels like the mapblock loading might still be a bit more sluggish than usual under CPU lag, but it's MUCH better than it was before.

This looks like it deals with the known issue well enough for me to redeploy to my server and see how it performs in the field.

**Comment by Warr1024** [comment]
Looks like I might have to roll this back again a bit early.  It looks like baseline lag is worse overall, when the server is lightly to moderately CPU loaded, and nothing is running in the background.  It's crazy to be seeing step sizes of more than 10x dedicated_step when disk is quiescent and MT is using only 80% CPU.

image

File: src/server.cpp (hunk 11 above)
[the remark this answers is not in the document]
Comment (sfan5) [reply src/server.cpp]: I could also use `EnvAutoLock` to exactly measure the locking time, sure.
But is it worth to invest so much time into a (hopefully) temporary workaround?

**Comment by sfan5** [comment]
> In particular I've noticed at least 50ms of lag added to even the smallest steps, though it seems like larger steps are "spread out" upward, e.g. larger steps are paying a proportionally larger lag "tax".

It doesn't make sense to me why this would be happening. Please provide profiler output and a verbose log.

**Comment by savilli** [comment]
Any reason why we shouldn't merge this? Even if it doesn't fix the problem completely, I think it's a big improvement over all.

File: src/server.cpp [hunk 12]
```diff
@@ -127,9 +127,13 @@ void *ServerThread::run()
 
 		u64 t0 = porting::getTimeUs();
 
-		const Server::StepSettings step_settings = m_server->getStepSettings();
+		const auto step_settings = m_server->getStepSettings();
 
 		try {
+			// see explanation inside
+			if (dtime > step_settings.steplen)
+				m_server->yieldToOtherThreads(dtime);
```
Comment (nerzhul) [inline src/server.cpp:135]: i think we should say dispatch instead of yield

File: src/server.cpp (hunk 11 above)
[the remark this answers is not in the document]
Comment (Desour) [reply src/server.cpp]: If you think it's too much work, and if you say it's just temporary, then I'm fine with this.

File: src/server.cpp [hunk 13]
```diff
@@ -127,9 +127,13 @@ void *ServerThread::run()
 
 		u64 t0 = porting::getTimeUs();
 
-		const Server::StepSettings step_settings = m_server->getStepSettings();
+		const auto step_settings = m_server->getStepSettings();
 
 		try {
+			// see explanation inside
+			if (dtime > step_settings.steplen)
```
Comment (Desour) [inline src/server.cpp:134]: (Would make more sense to compare with the steplen of the previous step. But probably doesn't matter in practice.)

**Review by Desour — APPROVED** [review]
LGTM.

File: src/server.cpp (hunk 11 above)
[the remark this answers is not in the document]
Comment (sfan5) [reply src/server.cpp]: I mean I currently have no plans to continue the work and convert emerging to a queue, but it's not that hard so I'm hoping:
1. that the current workaround is good enough with small enough downsides
2. someone else picks up that task soon *or* I change my opinion in 2 months

File: src/server.cpp (hunk 12 above)
Comment (sfan5) [reply src/server.cpp:135]: yield is the correct term: https://man7.org/linux/man-pages/man2/sched_yield.2.html

**Comment by sfan5** [comment]
> Any reason why we shouldn't merge this? Even if it doesn't fix the problem completely, I think it's a big improvement over all.

I agree. But I don't want to be in the hot seat when the next performance regression issue drops after 5.10 and is bisected to my commits.

**Comment by Warr1024** [comment]
Verbose log of 5.10.0-dev-f5e78689d-dirty with profiler interval of 60 seconds, with one player connected.  I didn't capture a 5.9.1 baseline, do you need one of those too?

[pr15151-verbose.txt.gz](https://github.com/user-attachments/files/17099622/pr15151-verbose.txt.gz)

**Comment by sfan5** [comment]
> Verbose log of 5.10.0-dev-f5e78689d-dirty with profiler interval of 60 seconds, with one player connected.

I checked the log and everything is in order so to speak.
I was too quick to raise the alarm, the time taken by the lock contention workaround is proportional to the dtime so "larger steps are paying a proportionally larger lag tax" is perfectly expected.

A word of advice for production: if your server step is consistently taking longer than the target (= `dedicated_server_step`), consider raising that.

**Comment by Warr1024** [comment]
I have considered raising the target but it doesn't make sense to do.  A target of 0.05 to 0.09 is reasonable, and the game can reach 0.05 pretty easily about 75% of the time on a reasonably healthy system.  The other 25% of the time are 0.20 to 0.25 sized steps caused by the fact that ABMs are all bunched up on a single server step (separate issue) but raising the target to 0.25 would just make this occasional crappiness happen constantly.  I have experimented with the whole "just set the minimum to the observed average" concept and the results were quite bad.

MT's dedicated step config is being used as both a "maximum" step time (if it's larger than this then something is wrong and MT should take corrective action) and a "minimum" step time (if it's smaller then MT should sleep to make up the difference).  This is unsustainable with the way MT is built, with significant things running on fixed timers.

**Comment by sfan5** [comment]
> MT's dedicated step config is being used as both a "maximum" step time (if it's larger than this then something is wrong and MT should take corrective action) and a "minimum" step time (if it's smaller then MT should sleep to make up the difference).

I think this PR is the only time where we use it as a "maximum step time". ABMs have a fixed 200ms limit but that's another topic as you mentioned. Did I miss any?
Problem in this case is that lock contention starts happening if the ServerThread isn't sleeping, so disconnecting that from "minimum step time" interpretation is plainly incorrect.
Fortunately this will go away eventually when the emerge threads are reworked with a result queue.

**Comment by Warr1024** [comment]
That's a fair assessment, but I guess my concern is that if the added sleep time is proportional to the server step time, then very large CPU-bound spikes can cause much higher delays as well. 

Lag in general (aside from the weird bimodal humps from stuff like ABM timers and thundering herd effects from mod code) seems to follow a more or less Zipfian distribution, so even when things "get laggy" there are still likely some short ones mixed in.  In some cases maybe just using a fixed sleep time per step rather than proportional may work better and also mitigate the larger spikes.

It might be best for now just to throw in some way to tune this that's accessible to server operators, just so that at least it can't make things worse, and server owners don't have to recompile each time to try to experiment or tune it.  At least it would make this safer to merge without risking un-work-aroundable regressions and make it easier to get data from the field.

**Comment by sfan5** [comment]
> if the added sleep time is proportional to the server step time, then very large CPU-bound spikes can cause much higher delays as well.

will address as discussed on IRC.

> In some cases maybe just using a fixed sleep time per step rather than proportional may work better and also mitigate the larger spikes.

IIRC I had that before you tested with 200ms where that didn't work fine, so I changed it to be proportional.

**Comment by sfan5** [comment]
@Desour I tuned `yieldToOtherThreads`, which you may want to check again.
see also the irc discussion: https://irc.minetest.net/minetest-dev/2024-09-25

**Comment by Desour** [comment]
> @Desour I tuned `yieldToOtherThreads`, which you may want to check again. see also the irc discussion: https://irc.minetest.net/minetest-dev/2024-09-25

Just adds max time. Makes sense. :+1:
