### PR TITLE
[NO SQ] Formspec: Fix malfunctioning 'Proceed' button on sizeless formspecs

### LINKED ISSUE #16187: Signs seem to be broken when pressing "Proceed" button
As of Luanti 5.10 at least (maybe earlier) `default:sign_wall_steel` and `default:sign_wall_wood` seem to be not working correctly.

Steps:
- Place wood or steel sign
- Right click to edit
- Enter any text
- Press "Proceed" button (note: not Enter - using Enter works correctly)

Result:
Sign text becomes "ExitButton"

Expected:
Sign text to be whatever the user entered

### PR DESCRIPTION
**Pull request by SmallJoker**
This is a direct adoption of the approach from #16194, but removes the `ExitButton` thing entirely. It is undocumented and wasn't sent at all in 5.11.0.

The ~~second~~ 3rd commit is code formatting only and not relevant for the bugfix. It may be discarded if that's preferred.

Fixes #16187

1. Try this testing code for Minetest Game:
```diff
diff --git a/mods/default/nodes.lua b/mods/default/nodes.lua
index 8537d9e..e2f6a18 100644
--- a/mods/default/nodes.lua
+++ b/mods/default/nodes.lua
@@ -2604,6 +2604,7 @@ local function register_sign(material, desc, def)
 			meta:set_string("formspec", "field[text;;${text}]")
 		end,
 		on_receive_fields = function(pos, formname, fields, sender)
+			core.log("action", dump(fields))
 			local player_name = sender:get_player_name()
 			if minetest.is_protected(pos, player_name) then
 				minetest.record_protection_violation(pos, player_name)
```
2. Place a MTG sign
3. Input text
4. Click the "Proceed" button

### 5.11.0 (tested using the Win64 binary in Wine 10.8)
```
2025-05-28 14:14:39: ACTION[Server]: {
        quit = "true",
        text = "test abc 123"
}
2025-05-28 14:14:39: ACTION[Server]: singleplayer wrote "test abc 123" to the sign at (13,5,-24)
```

### Master
```
{
	quit = "true",
	text = "test abc 123",
}
2025-05-28 13:41:48: ACTION[Server]: singleplayer wrote "test abc 123" to the sign at (13,5,-24)
{
	text = "ExitButton",
}
2025-05-28 13:41:48: ACTION[Server]: singleplayer wrote "ExitButton" to the sign at (13,5,-24)
```
(the formspec closes)

### This PR
```
{
	quit = "true",
	text = "test abc 123",
}
2025-05-28 13:49:40: ACTION[Server]: singleplayer wrote "test abc 123" to the sign at (13,5,-24)
```
(the formspec closes)

## To do

This PR is Ready for Review.

## How to test

In addition to previous code, now with `allow_close[false]`. Note: you have to place a new sign because the formspec is only added/modified upon placement.
```diff
diff --git a/mods/default/nodes.lua b/mods/default/nodes.lua
index 8537d9e..0d05c61 100644
--- a/mods/default/nodes.lua
+++ b/mods/default/nodes.lua
@@ -2601,9 +2601,10 @@ local function register_sign(material, desc, def)
 
 		on_construct = function(pos)
 			local meta = minetest.get_meta(pos)
-			meta:set_string("formspec", "field[text;;${text}]")
+			meta:set_string("formspec", "allow_close[false]field[text;;${text}]")
 		end,
 		on_receive_fields = function(pos, formname, fields, sender)
+			core.log("action", dump(fields))
 			local player_name = sender:get_player_name()
 			if minetest.is_protected(pos, player_name) then
 				minetest.record_protection_violation(pos, player_name)
```
Result: (no matter how the formspec is attempted to be closed)
```
2025-05-28 14:37:19: ACTION[Server]: singleplayer wrote "test 1234" to the sign at (13,5,-24)
2025-05-28 14:37:19: ACTION[Server]: {
	text = "test 1234",
	try_quit = "true",
}
```
This is OK because the signs do not need to handle `allow_close[false]`.

### CODE REVIEW

File: src/gui/guiFormSpecMenu.h [hunk 1]
```diff
@@ -68,8 +68,6 @@ struct TextDest
 {
 	virtual ~TextDest() = default;
 
-	// This is deprecated I guess? -celeron55
-	virtual void gotText(const std::wstring &text) {}
```
[the remark this answers is not in the document]
Comment (SmallJoker) [reply src/gui/guiFormSpecMenu.h:72]: I see. My IDE ignored markdown files while searching for occurrences. Well, now it's corrected.

File: src/gui/guiFormSpecMenu.cpp [hunk 2]
```diff
@@ -4821,12 +4821,18 @@ bool GUIFormSpecMenu::OnEvent(const SEvent& event)
...
+		case gui::EGET_TAB_CHANGED:
+			if (!isVisible())
+				break;
+
+				// find the element that was clicked
 			for (GUIFormSpecMenu::FieldSpec &s : m_fields) {
-				if ((s.ftype == f_TabHeader) &&
-						(s.fid == event.GUIEvent.Caller->getID())) {
+				if (s.ftype == f_TabHeader &&
+						s.fid == caller_id) {
```
Comment (v-rob) [inline src/gui/guiFormSpecMenu.cpp:4835]: Can be a single line now.

File: src/gui/guiFormSpecMenu.cpp [hunk 3]
```diff
@@ -4821,12 +4821,18 @@ bool GUIFormSpecMenu::OnEvent(const SEvent& event)
 	}
 
 	if (event.EventType == EET_GUI_EVENT) {
-		if (event.GUIEvent.EventType == gui::EGET_TAB_CHANGED
-				&& isVisible()) {
-			// find the element that was clicked
+		const s32 caller_id = event.GUIEvent.Caller->getID();
+		bool close_on_enter;
```
Comment (v-rob) [inline src/gui/guiFormSpecMenu.cpp:4825]: This appears to only be used in one case, so probably add braces to that case and move the variable there.

**Review by v-rob — COMMENTED** [review]
Code looks pretty good. Will test shortly.

**Review by v-rob — COMMENTED** [review]
Testing seems to show correct behavior in every case. Just one last comment.

File: src/gui/guiFormSpecMenu.cpp [hunk 4]
```diff
@@ -4832,26 +4841,26 @@ bool GUIFormSpecMenu::OnEvent(const SEvent& event)
...
-				m_text_dst->gotText(L"ExitButton");
-				quitMenu();
+			break;
+
+		case gui::EGET_BUTTON_CLICKED:
+		case gui::EGET_CHECKBOX_CHANGED:
+		case gui::EGET_COMBO_BOX_CHANGED:
+		case gui::EGET_SCROLL_BAR_CHANGED:
+			if (caller_id == ID_PROCEED_BTN) {
+				trySubmitClose();
```
[the remark this answers is not in the document]
Comment (SmallJoker) [reply src/gui/guiFormSpecMenu.cpp:4863]: It is technically correct, and a mod could still send a new formspec manually to close it upon submit, e.g. `core.close_formspec()`.

File: src/gui/guiFormSpecMenu.cpp (hunk 3 above)
Comment (SmallJoker) [reply src/gui/guiFormSpecMenu.cpp:4825]: I actually moved the variable outside such that I do not need to add another indent level just for that.

**Review by v-rob — APPROVED** [review]
Looks satisfactory.
