### PR TITLE
Make Mapgen::spreadLight use a queue

### LINKED ISSUE #4399: Mintest crashes when vm:set_lighting({day = 7, night = 7}) or higher
I found a strange bug. I modified the [intersect light](https://forum.minetest.net/viewtopic.php?f=9&t=13414) mod from duane a little bit and set vm:set_lighting({day = 15, night = 15}) to see what happens. Everything works fine, also if I set vm:set_lighting({day = 0, night = 0})

But if I set vm:set_lighting({day = 7, night = 7}) minetest crashes after a few seconds with a memory error. It also crashes with values of 8, 9, 10 and 11, but it takes longer the higher the value is. Maybe it will crash with 15 too, but I never played that long

I had no crash below 7 or it takes extremely long and I didn't try any number yet

Edit: I use the latest dev version from Ubuntu PPA, running on Ubuntu 16.04 64 bit

### LINKED ISSUE #7864: There's something in the attached map that causes a crash with no logged cause
##### Issue type
 - Bug report
 
##### Minetest version

```
minetest-5.0.0-0e306c0-win64 (sfan5's build)
```

##### OS / Hardware

Operating system: Windows 10 Home
CPU: Intel i7-3770K @ 3.5GHz, 8.00 GB ram

##### Summary

I've been working on a mod that, among other things, adds volcanic mountains to any existing mapgen. I have managed to use this mod to generate a particular map block in it that causes Minetest to hard-crash as soon as it attempts to emerge the map block, with no useful information in the debug log (even at verbose) about exactly what it was that caused the crash. I've attached a world folder to this issue with a known example of one of these "poison" map blocks, but this bug can be reproduced in earlier versions of Minetest (I've seen this crash happen in my old 0.4.16 install) and is very consistent whenever I find an example.

Once the world has been generated, my mapgen mod is no longer required - it can be disabled and the crash still happens. No special blocks are being added to the map, nor any fancy metadata.

##### Steps to reproduce

To reproduce the crash in the existing attached world [volc.zip](https://github.com/minetest/minetest/files/2579232/volc.zip):

Join the world in singleplayer mode as "singleplayer". Singleplayer should be located at -1949, 79, 657, adjacent to a large stone mountain with gravel patches on its flanks (this is the volcano generated by my mod). Look in the direction of the mountain and within a few seconds the game will crash. If the logging is in verbose mode the last line of the log will read:

```
INFO[Emerge-0]: initialEmerge: area: (-2048,32,752)(-1937,143,863)=112x112x112=1404928 (5MB)
```

This has been consistent across multiple reproduction attempts, when the game tries to emerge that area it crashes.

The specific version of my mod that was used to generate this map was:

https://github.com/FaceDeer/magma_conduits/tree/e749dfe39f2bb7a871fd8de17bd1d2faa34188a2

With the following settings in minetest.conf to disable various irrelevant features:

```
magma_conduits_magma_veins = false
magma_conduits_glowing_rock = false
magma_conduits_cook_soil = false
magma_conduits_remove_default_lava = false
```

But it should be possible to get this crash to happen without the magma_conduits mod actually being active, since its work is apparently done at this point.

If you want to reproduce this entirely from scratch, create a new world with the name "volc", seed "1", mapgen v7, and Minetest Game. Enable the magma_conduits mod, start playing, /grant singleplayer all, and then /teleport -1949, 79, 657. Look toward the cursed mountain and perish.

Edit: Another volcano that produces a crash in this world is located at 1540, 0, 2760.

### LINKED ISSUE #8763: Segmentation fault in all-lava game.
##### Minetest version

```
Minetest 5.1.0-dev-debug-e788ee28 (Linux)
Using Irrlicht 1.8.4
```

##### Summary
The game segfaults after a few moments of activity in the all-lava game. @jastevenson303 has the same issue.

##### Steps to reproduce
Get the lavaland game by @jastevenson303 https://github.com/jastevenson303/lavaland
I used commit `b0d79cc9b7784b096b685b997a9705a4148edefa`.

Create a new world with that game.
Load it up and splash around, respawn, etc. for a bit. After some time (note the slow mapgen) the game will segfault. This occurs in both debug and release builds.

````
Thread 25 "Emerge-0" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fff9c88f700 (LWP 23018)]
0x0000555555c18993 in VoxelArea::index (this=0x7fff848d8018, p=...) at /home/USER/src/minetest/src/voxel.h:277
277			return index(p.X, p.Y, p.Z);
````

Notably, removing the `paramtype` and `light_source` fields from the lava nodes' definitions will prevent the crash.
Also notably, setting `ulimit -s` from `8192` to `262144` prevents the crash for me.

My guess is a stack overflow due to sheer number of light calculations.

~~@jastevenson303 has said this does not occur when hosting a game, only in singleplayer.~~

##### Backtrace
This is the first page of the backtrace, it continues with Mapgen::lightSpread as far as I can go.
````
#0  0x0000555555c18993 in VoxelArea::index (this=0x7fff848d8018, p=...) at /home/USER/src/minetest/src/voxel.h:277
No locals.
#1  0x0000555555daa324 in Mapgen::lightSpread (this=0x7fff9c88dfc0, a=..., p=..., light=222 '\336') at /home/USER/src/minetest/src/mapgen/mapgen.cpp:443
        vi = 2617835648
        n = @0x7fff9c090080: {param0 = 240, param1 = 9 '\t', param2 = 156 '\234'}
        light_day = 0 '\000'
        light_night = 0 '\000'
#2  0x0000555555daa462 in Mapgen::lightSpread (this=0x7fff9c88dfc0, a=..., p=..., light=222 '\336') at /home/USER/src/minetest/src/mapgen/mapgen.cpp:470
        vi = 196263
        n = @0x7fff8674705c: {param0 = 32, param1 = 222 '\336', param2 = 0 '\000'}
        light_day = 14 '\016'
        light_night = 0 '\000'
#3  0x0000555555daa546 in Mapgen::lightSpread (this=0x7fff9c88dfc0, a=..., p=..., light=31 '\037') at /home/USER/src/minetest/src/mapgen/mapgen.cpp:473
        vi = 208807
        n = @0x7fff8675345c: {param0 = 32, param1 = 31 '\037', param2 = 0 '\000'}
        light_day = 14 '\016'
        light_night = 16 '\020'
#4  0x0000555555daa546 in Mapgen::lightSpread (this=0x7fff9c88dfc0, a=..., p=..., light=47 '/') at /home/USER/src/minetest/src/mapgen/mapgen.cpp:473
        vi = 221351
        n = @0x7fff8675f85c: {param0 = 32, param1 = 47 '/', param2 = 0 '\000'}
        light_day = 14 '\016'
        light_night = 32 ' '
#5  0x0000555555daa546 in Mapgen::lightSpread (this=0x7fff9c88dfc0, a=..., p=..., light=63 '?') at /home/USER/src/minetest/src/mapgen/mapgen.cpp:473
        vi = 233895
        n = @0x7fff8676bc5c: {param0 = 32, param1 = 63 '?', param2 = 0 '\000'}
        light_day = 14 '\016'
        light_night = 48 '0'
#6  0x0000555555daa546 in Mapgen::lightSpread (this=0x7fff9c88dfc0, a=..., p=..., light=79 'O') at /home/USER/src/minetest/src/mapgen/mapgen.cpp:473
        vi = 246439
        n = @0x7fff8677805c: {param0 = 32, param1 = 79 'O', param2 = 0 '\000'}
        light_day = 14 '\016'
        light_night = 64 '@'
#7  0x0000555555daa546 in Mapgen::lightSpread (this=0x7fff9c88dfc0, a=..., p=..., light=95 '_') at /home/USER/src/minetest/src/mapgen/mapgen.cpp:473
        vi = 258983
        n = @0x7fff8678445c: {param0 = 32, param1 = 95 '_', param2 = 0 '\000'}
        light_day = 14 '\016'
        light_night = 80 'P'
#8  0x0000555555daa546 in Mapgen::lightSpread (this=0x7fff9c88dfc0, a=..., p=..., light=111 'o') at /home/USER/src/minetest/src/mapgen/mapgen.cpp:473
        vi = 271527
        n = @0x7fff8679085c: {param0 = 32, param1 = 111 'o', param2 = 0 '\000'}
        light_day = 14 '\016'
        light_night = 96 '`'
#9  0x0000555555daa592 in Mapgen::lightSpread (this=0x7fff9c88dfc0, a=..., p=..., light=127 '\177') at /home/USER/src/minetest/src/mapgen/mapgen.cpp:474
        vi = 271639
        n = @0x7fff86790a1c: {param0 = 32, param1 = 127 '\177', param2 = 0 '\000'}
        light_day = 14 '\016'
        light_night = 112 'p'
#10 0x0000555555daa462 in Mapgen::lightSpread (this=0x7fff9c88dfc0, a=..., p=..., light=143 '\217') at /home/USER/src/minetest/src/mapgen/mapgen.cpp:470
        vi = 259095
        n = @0x7fff8678461c: {param0 = 32, param1 = 143 '\217', param2 = 0 '\000'}
        light_day = 14 '\016'
        light_night = 128 '\200'
#11 0x0000555555daa462 in Mapgen::lightSpread (this=0x7fff9c88dfc0, a=..., p=..., light=159 '\237') at /home/USER/src/minetest/src/mapgen/mapgen.cpp:470
        vi = 246551
        n = @0x7fff8677821c: {param0 = 32, param1 = 159 '\237', param2 = 0 '\000'}
        light_day = 14 '\016'
        light_night = 144 '\220'
````

### PR DESCRIPTION
**Pull request by DS-Minetest**
- Goal of the PR: increase the performance
- How does the PR work? `Mapgen::spreadLight` fills a queue and then makes it empty again.
- Related: #8832 (This PR might be able to replace that and fix its issues, but I'm not sure.)
- Fixes #4399, fixes #7864, fixes #8763

## To do

This PR is a Ready for Review.

## How to test

Fly around and generate new mapblocks. Look into the terminal to see how long `spreadLight` takes.

I've tested this in minimal and in [lavaland](https://github.com/jastevenson303/lavaland). In both subgames the values of this PR were better.

### CODE REVIEW

**Comment by SmallJoker** [comment]
Thanks for your efforts. However, I prefer the other PR for keeping the light updating within the function. This approach should work as well, but spreads the code unnecessary.

**Comment by lhofhansl** [comment]
Personally, I like this approach.

File: src/mapgen/mapgen.cpp [hunk 1]
```diff
@@ -467,12 +468,12 @@ void Mapgen::lightSpread(VoxelArea &a, v3s16 p, u8 light)
...
-	lightSpread(a, p + v3s16(1, 0, 0), light);
-	lightSpread(a, p - v3s16(0, 0, 1), light);
-	lightSpread(a, p - v3s16(0, 1, 0), light);
-	lightSpread(a, p - v3s16(1, 0, 0), light);
+	queue.emplace(p + v3s16(0, 0, 1), light);
+	queue.emplace(p + v3s16(0, 1, 0), light);
+	queue.emplace(p + v3s16(1, 0, 0), light);
+	queue.emplace(p - v3s16(0, 0, 1), light);
+	queue.emplace(p - v3s16(0, 1, 0), light);
+	queue.emplace(p - v3s16(1, 0, 0), light);
```
Comment (sfan5) [inline src/mapgen/mapgen.cpp]: could use `g_6dirs` from util/directiontables.h

File: src/mapgen/mapgen.cpp [hunk 2]
```diff
@@ -551,18 +553,24 @@ void Mapgen::spreadLight(v3s16 nmin, v3s16 nmax)
...
-					lightSpread(a, v3s16(x + 1, y,     z    ), light);
-					lightSpread(a, v3s16(x,     y,     z - 1), light);
-					lightSpread(a, v3s16(x,     y - 1, z    ), light);
-					lightSpread(a, v3s16(x - 1, y,     z    ), light);
+					lightSpread(a, queue, v3s16(x,     y,     z + 1), light);
+					lightSpread(a, queue, v3s16(x,     y + 1, z    ), light);
+					lightSpread(a, queue, v3s16(x + 1, y,     z    ), light);
+					lightSpread(a, queue, v3s16(x,     y,     z - 1), light);
+					lightSpread(a, queue, v3s16(x,     y - 1, z    ), light);
+					lightSpread(a, queue, v3s16(x - 1, y,     z    ), light);
```
Comment (sfan5) [inline src/mapgen/mapgen.cpp]: same here

**Comment by sfan5** [comment]
> In both subgames the values of this PR were better.

I do wonder why this is faster, it doesn't do anything more or less.
Is it the overhead of allocating a new queue for every `lightSpread`?

File: src/mapgen/mapgen.cpp (hunk 1 above)
Comment (DS-Minetest) [reply src/mapgen/mapgen.cpp]: Will do.

**Comment by DS-Minetest** [comment]
> > In both subgames the values of this PR were better.
> 
> I do wonder why this is faster, it doesn't do anything more or less.
> Is it the overhead of allocating a new queue for every `lightSpread`?

Note that I wasn't precise here. The values of this PR are better than those in current master. I haven't compared this to your PR.

The reason why this is faster is probably that there's less spreading in areas that are filled with light.

Also note that, at first, I was filling a the queue without checking, which was a bit slower for minimal subgame.

File: src/mapgen/mapgen.cpp (hunk 1 above)
Comment (DS-Minetest) [reply src/mapgen/mapgen.cpp]: Done.

File: src/mapgen/mapgen.cpp (hunk 2 above)
Comment (DS-Minetest) [reply src/mapgen/mapgen.cpp]: Done.

File: src/mapgen/mapgen.cpp [hunk 3]
```diff
@@ -553,19 +552,18 @@ void Mapgen::spreadLight(v3s16 nmin, v3s16 nmax)
...
-					lightSpread(a, queue, v3s16(x,     y + 1, z    ), light);
-					lightSpread(a, queue, v3s16(x + 1, y,     z    ), light);
-					lightSpread(a, queue, v3s16(x,     y,     z - 1), light);
-					lightSpread(a, queue, v3s16(x,     y - 1, z    ), light);
-					lightSpread(a, queue, v3s16(x - 1, y,     z    ), light);
+					const v3s16 p(x, y, z);
+					// spread to all 6 neighbor nodes
+					for (u8 i = 0; i < 6; i++) {
+						lightSpread(a, queue, p + g_6dirs[i], light);
+					}
```
Comment (sfan5) [inline src/mapgen/mapgen.cpp]:
```c++
for (const auto &dir : g_6dirs)
    lightSpread(a, queue, p + dir, light);
```

Comment (DS-Minetest) [reply src/mapgen/mapgen.cpp]: Huh, TIL that ranged for loops are possible for normal arrays.
Done.

**Comment by sfan5** [comment]
@DS-Minetest please uncomment the performance testing code so this isn't forgotten on merge

**Comment by DS-Minetest** [comment]
Performance test is commented.

(Yey!)

**Comment by DS-Minetest** [comment]
Please wait before merging, I want to try something.

**Comment by DS-Minetest** [comment]
Ok, the last commit makes it ca. 2 times faster.

File: src/mapgen/mapgen.cpp [hunk 4]
```diff
@@ -551,18 +550,24 @@ void Mapgen::spreadLight(v3s16 nmin, v3s16 nmax)
...
-					lightSpread(a, v3s16(x,     y,     z + 1), light);
-					lightSpread(a, v3s16(x,     y + 1, z    ), light);
-					lightSpread(a, v3s16(x + 1, y,     z    ), light);
-					lightSpread(a, v3s16(x,     y,     z - 1), light);
-					lightSpread(a, v3s16(x,     y - 1, z    ), light);
-					lightSpread(a, v3s16(x - 1, y,     z    ), light);
+					const v3s16 p(x, y, z);
+					// spread to all 6 neighbor nodes
+					for (const auto &dir : g_6dirs)
+						lightSpread(a, queue, p + dir, light);
```
Comment (DS-Minetest) [inline src/mapgen/mapgen.cpp]: One might ask, of course, why here `p, light` isn't added to the queue instead. But that would just mean that those values are added to the queue and removed again a bit later in the same order.

**Comment by lhofhansl** [comment]
Nice.

**Comment by SmallJoker** [comment]
Now the order is no longer the same, but that shouldn't matter since the code takes the maximal light for the node.

<details>
<summary>Benchmarks before last commit</summary>
DS-minetest
1. spreadLight: 66ms, 73ms, 75ms, 6ms, 59ms
2. spreadLight: 64ms, 73ms, 72ms, 6ms, 58ms


sfan5
1. spreadLight: 270ms, 307ms, 318ms, 8ms, 389ms
2. spreadLight: 269ms, 309ms, 318ms, 8ms, 379ms

C-style ringbuffer (size = 16^3)
1. spreadLight: 173ms, 189ms, 189ms, 9ms, 96ms
2. spreadLight: 166ms, 185ms, 183ms, 7ms, 94ms
</details>

PS: Please add a comment referencing to `voxelalgorithms.cpp`. There's the same thing, but different.

**Comment by lhofhansl** [comment]
Still looks good to me.

**Comment by DS-Minetest** [comment]
> PS: Please add a comment referencing to `voxelalgorithms.cpp`. There's the same thing, but different.

Umm, where should this comment be added to?

**Comment by SmallJoker** [comment]
> Umm, where should this comment be added to?

Preferably above `void Mapgen::spreadLight()` to leave a hint for future cleanups. But well, it's too late now. At least it's mentioned here.
