### PR TITLE
Fix access violation in create_schematic()

### LINKED ISSUE #11533: Segfault when create_schematic() called with layer probabilities
##### Minetest version
```
Minetest 5.5.0 e1b297a14 (recent)
minetest-5.0.0 ca502fc (from 2018)
I think it's all versions since about 2017
```

##### OS / Hardware
Windows, i7-6700K

##### Summary
When a schematic is saved from a y location greater than 0, an access violation intermittently occurs if layer probabilities are specified.

At [line 601 of mg_schematic.cpp](https://github.com/minetest/minetest/blob/b3b075ea02034306256b486dd45410aa765f035a/src/mapgen/mg_schematic.cpp#L601):
```
for (size_t i = 0; i != splist->size(); i++) {
	s16 y = (*splist)[i].first - p0.Y;       // <- here
	slice_probs[y] = (*splist)[i].second;
}
```

it subtracts p0.Y (the lower schematic map coord ) from the `ypos` in the layer-probability table, but ypos is a value between 0 and the number of layers in the schematic, so for schematics from a higher y location the result is negative. The negative number is then used as an array index in the next line.

##### Steps to reproduce
[Attached is a mod](https://github.com/minetest/minetest/files/6983134/crashy.zip) that reproduces the error, run `/nocrashy` for the mod to save a schematic without crashing, and `/crashy` for it to cause an access violation.

[crashy.zip](https://github.com/minetest/minetest/files/6983134/crashy.zip)

The demo mod basically does this:
```
function saveSchematicWithLayerProbs(crashWhileDoingIt)
	
	local minp
	if crashWhileDoingIt then 	
		minp = vector.new(0, 2, 0) -- the y position of the schematic will get subtracted from the ypos in the probability table, and that negative result used to index an array
	else
		minp = vector.new(0, 0, 0)
	end
	local maxp = vector.add(minp, 5) -- the schematic will have 5 layers
	
	
	local path = minetest.get_worldpath() .. DIR_DELIM .. "temp"
	minetest.mkdir(path) -- Create dir if it doesn't already exist
	
	local ret = minetest.create_schematic(
		minp, maxp,
		{{pos = vector.new(1, 1, 1), prob = 0}},
		path .. DIR_DELIM .. "crashy.mts",
		{{ypos=1, prob=20}} -- specifying layer probabilities causes the crash, (ypos 1 is lower than 2)
	)
end
```

I found that the crash wasn't happening if I called minetest.find_nodes_in_area() before calling create_schematic() (while it didn't crash, it didn't save the layer probabilities either), so if different lua code can prevent the symptom from manifesting, perhaps it might not reproduce on every machines either

### PR DESCRIPTION
**Pull request by Treer**
Fixes #11533, schematics saved from y locations higher than 0 would cause an access violation if layer probabilities were specified

See #11533 for more details

## To do

This PR is Ready for Review.

## How to test

* [Attached is a mod](https://github.com/minetest/minetest/files/6983134/crashy.zip) that reproduces the error, run `/nocrashy` chat command for the mod to save a schematic without crashing, and `/crashy` for it to cause an access violation.
* Operations performed before create_schematic() is called can affect whether Minetest will crash, so different lua code doesn't always reproduce it, and this may also be the case across different machines.
* Testing that layer probabilities are now correctly applied (in addition to not crashing) requires serializing the output of create_schematic() into lua and inspecting the yslice_prob table. The one i tried looked good to me.
* I've not checked whether `l_create_schematic()` sanitizes the `ypos` it receives from lua before using it as an index. (I didn't notice any, but also don't know what the policy is)

### CODE REVIEW

**Review by sfan5 — APPROVED** [review]
Looked at related code, looks correct.

File: src/mapgen/mg_schematic.cpp [hunk 1]
```diff
@@ -598,8 +598,8 @@ void Schematic::applyProbabilities(v3s16 p0,
 	}
 
 	for (size_t i = 0; i != splist->size(); i++) {
-		s16 y = (*splist)[i].first - p0.Y;
-		slice_probs[y] = (*splist)[i].second;
+		s16 slice = (*splist)[i].first;
+		slice_probs[slice] = (*splist)[i].second;
```
Comment (sfan5) [inline src/mapgen/mg_schematic.cpp:602]: one more: checking the bounds like above is a good idea here too
```suggestion
		if (slice < size.Y)
			slice_probs[slice] = (*splist)[i].second;
```
