### PR TITLE
Fix positive borderwidths box style not working

### LINKED ISSUE #16437: Formspec box element positive borderwidths style doesn't work
### Luanti version

Luanti 5.14.0-dev

### Summary

When you use a `box` element with a style containing a positive `borderwidths`, no border is shown, but the documentation says it works.
(For negative `borderwidths` it works.)

Also see https://forum.luanti.org/viewtopic.php?t=31937

### Solutions

- Make it work
- Change the documentation

Also, it would be good to add it to devtest's `/test_formspec `

### Steps to reproduce
``` lua
core.register_chatcommand("tb", {
    func = function(name)
        core.show_formspec(name, "test", "formspec_version[6]size[5,5]style_type[box;borderwidths=5;bordercolors=#FF0000FF;colors=#00FF00FF]box[1,1;1,1;]")
        return true
    end
})
```

### PR DESCRIPTION
**Pull request by Wuzzy2**
Fixes #16437.

## How to test

Use `luacmd` mod, then enter this command in DevTest:

### Test 1

```
/lua core.show_formspec(me:get_player_name(), "test","formspec_version[5]size[5,5]container[1,0]style_type[box;borderwidths=5;bordercolors=#ff0000] box[0,1;1,1;]style_type[box;borderwidths=-5;bordercolors=#0000ff]box[0,3;1,1;]container_end[]")
```

You should two box outlines, the first one is an outer line, the second one is an inner line.

### Test 2

Then run this command:

```
/lua core.show_formspec(me:get_player_name(), "test","formspec_version[5]size[5,5]container[-0.5,0]style_type[box;borderwidths=5;bordercolors=#ff0000] box[0,1;1,1;]style_type[box;borderwidths=-5;bordercolors=#0000ff]box[0,3;1,1;]container_end[]")
```

You should see the same two boxes, but clipped at the left formspec boundary.

### Test 3

Then run this command:

```
/lua core.show_formspec(me:get_player_name(), "test","formspec_version[5]size[5,5]container[-0.5,0]style_type[box;noclip=true;borderwidths=5;bordercolors=#ff0000] box[0,1;1,1;]style_type[box;borderwidths=-5;bordercolors=#0000ff]box[0,3;1,1;]container_end[]")
```

You should see the same two boxes at the left formspec boundary, but *not* clipped (`noclip=true`).

### CODE REVIEW

File: src/gui/guiBox.cpp [hunk 1]
```diff
@@ -96,9 +96,19 @@ void GUIBox::draw()
...
 
+	core::rect<s32> border_rect = core::rect<s32>(
+		topleft_border.X,
+		topleft_border.Y,
+		lowerright_border.X,
+		lowerright_border.Y
+	);
+	if(!isNotClipped()) {
+		border_rect.clipAgainst(Parent->getAbsoluteClippingRect());
+	}
```
Comment (SmallJoker) [inline src/gui/guiBox.cpp:109]:
```suggestion
	// The border rectangle can be larger than 'AbsoluteClippingRect',
	// hence clip against the (generally larger) parent.
	core::rect<s32> border_rect = core::rect<s32>(
		topleft_border.X,
		topleft_border.Y,
		lowerright_border.X,
		lowerright_border.Y
	);
	if (!isNotClipped()) {
		border_rect.clipAgainst(Parent->getAbsoluteClippingRect());
	}
```

**Review by SmallJoker — COMMENTED** [review]
Works. This logic however needs a brief comment like suggested below.

grafik

**Comment by Wuzzy2** [comment]
Comment added.
