### PR TITLE
Slippery: Simplify, make more efficient

### LINKED ISSUE #7080: Player slips on slippery nodes when flying through underground ice with noclip and freemove
##### Issue type
 - Bug report
 
##### Minetest version
```
0.5 dev f9ad0619103ceee40e2a7810b971f93d877a63cd
```
The slippery feature should not affect players flying through slippery nodes with noclip and freemove.
Relevant commits https://github.com/minetest/minetest/commit/2ea26e655d90be538c75aad5cc7ede2c5709179f https://github.com/minetest/minetest/commit/fc13c00ef3e9b6f280146f3d77b6659fcc55a13c
@Wuzzy2 @bendeutsch

### PR DESCRIPTION
**Pull request by SmallJoker**
Use already existing collision results for the nearest colliding node
Fix slippery effect in free_move mode
Also deprecates the variable `is_slipping` in the localplayer class

Fixes #7080

**How to test the bugfix**
1) Walk on ice
2) `free_move` and `noclip` on and move through as many ice nodes as possible
3) Don't feel any slippery effect

**How to test the cleanup**
1) Find an unpatched version
2) Do a side-by-side comparison
3) Don't notice any differences or report them here if you do so

### CODE REVIEW

File: src/localplayer.cpp [hunk 1]
```diff
@@ -1057,49 +1060,20 @@ void LocalPlayer::old_move(f32 dtime, Environment *env, f32 pos_max_d,
...
-	if (!touching_ground)
-		return 1.0f;
-
-	float slip_factor = 1.0f;
 	// Slip on slippery nodes
 	const NodeDefManager *nodemgr = env->getGameDef()->ndef();
 	Map *map = &env->getMap();
 	const ContentFeatures &f = nodemgr->get(map->getNodeNoEx(
-			floatToInt(getPosition() - v3f(0, 0.05f * BS, 0), BS)));
+			getStandingNodePos()));
```
Comment (bendeutsch) [inline src/localplayer.cpp]: I'm not sure, but wasn't `getStandingNodePos` deprecated, or off by half a node, or something? If it isn't, great, but there was some reason it wasn't used in the original.

File: src/localplayer.cpp [hunk 2]
```diff
@@ -1057,49 +1060,20 @@ void LocalPlayer::old_move(f32 dtime, Environment *env, f32 pos_max_d,
...
 	int slippery = 0;
-	if (f.walkable) {
+	if (f.walkable)
 		slippery = itemgroup_get(f.groups, "slippery");
-	} else if (is_slipping) {
-		// slipping over an edge? Check surroundings for slippery nodes
```
Comment (bendeutsch) [inline src/localplayer.cpp]: This entire block exists to "correctly" handle the case where you run full-speed off the edge of an ice floe and suddenly come to a stop at the edge:

```
-->
III
GGGGG
```
where `I` is ice and `G` is grass or other unslippery. Is this feature unnecessary, or is this case handled by `getStandingNodePos`? Or am I missing something?

File: src/localplayer.cpp (hunk 1 above)
Comment (paramat) [reply src/localplayer.cpp]: It's not deprecated.

File: src/localplayer.cpp (hunk 2 above)
Comment (paramat) [reply src/localplayer.cpp]: We'll test this.

Comment (SmallJoker) [reply src/localplayer.cpp]: @bendeutsch As long the collision detects one or multiple nodes which prevent the player from falling (Yspeed = 0), the closest one will be used for the standing node position.

File: src/localplayer.cpp (hunk 1 above)
Comment (SmallJoker) [reply src/localplayer.cpp]: It was touched and extended a few months ago: https://github.com/minetest/minetest/commit/f729b5d2bdc65ce3c51f1004c58cb93a37504b49
Don't worry, I know what I'm doing ;)

**Comment by paramat** [comment]
:+1: tested.
It's actually better than before, now the player continues slipping when slipping off an edge onto another ice node, before the player would slow down a lot at the edge.

**Comment by paramat** [comment]
Also the slipping still occurs when hanging out further over an edge.

File: src/localplayer.cpp (hunk 2 above)
Comment (bendeutsch) [reply src/localplayer.cpp]: Right, you had said above that `getStandingNodePos` had been changed, so that should handle it nicely.

… brb while I check that this change made it to #6219 – that was branched in August 2017 :-P
