### PR TITLE
Guard new objects from being added at shutdown

### LINKED ISSUE #16592: Segfault when on_detach entity callback call core.add_item
### Luanti version

```true
Luanti 5.13 and 5.15.0-dev-a049174f1-dirty on linux
```

### Operating system and version

Arch linux

### CPU model

_No response_

### GPU model

_No response_

### Active renderer

_No response_

### Summary

Error

```
2025-10-18 15:23:09: WARNING[ServerStop]: server::ActiveObjectMgr::~ActiveObjectMgr(): not cleared.
Segmentation fault         (core dumped) ./bin/luanti
```

when exiting the game.

Behaviors should be fixed or documented.

### Steps to reproduce

Create an entity like this:
```
core.register_entity("sfence_bug_catcher:detach_add_item", {
			initial_properties = {
				visual = "sprite",
				textures = {"bad.png"},
				static_save = false
			},
			on_detach = function(self)
				core.add_item(self.object:get_pos(), "basenodes:sand")
				self.object:remove()
			end
		})
```

Add an entity to the world and attach it to another entity.

Image

Exit a game.

```
2025-10-18 15:23:09: WARNING[ServerStop]: server::ActiveObjectMgr::~ActiveObjectMgr(): not cleared.
Segmentation fault         (core dumped) ./bin/luanti
```

Unloading the parent entity or killing it works fine.

### PR DESCRIPTION
**Pull request by sfan5**
fixes #16592

## To do

This PR is Ready for Review.

## How to test

see issue

### CODE REVIEW

File: src/serverenvironment.cpp [hunk 1]
```diff
@@ -278,15 +278,20 @@ void ServerEnvironment::init()
 
 void ServerEnvironment::deactivateBlocksAndObjects()
 {
+	// Prevent any funny business from happening in case further callbacks
+	// try to add new objects.
+	m_shutting_down = true;
```
Comment (SmallJoker) [inline src/serverenvironment.cpp:283]: This feels wrong. The server should set this flag in its ctor.

Comment (sfan5) [reply src/serverenvironment.cpp:283]: `deactivateBlocksAndObjects` is specifically meant to be called only in the destructor.
if I were to change it would look like this:
```cpp
class ServerEnvironment {
    // ...
    void setShutdown() { m_shutting_down = true; }
    // ...
};

Server::~Server() {
    // ...
    m_env->setShutdown();
    m_env->deactivateBlocksAndObjects();
    // ...
}
```
feels pointless

Comment (SmallJoker) [reply src/serverenvironment.cpp:283]: "Shutdown" is a superset of block/object deactivation, thus should technically not be set there.
Anyway, at the moment this does not matter, thus LGTM.

**Review by SmallJoker — APPROVED** [review]
