### PR TITLE
Fix upright sprite entities not animating

### LINKED ISSUE #15105: Upright sprite animation is broken on MT5.9.0
### Minetest version

```true
Minetest-5.9.0
```

### Irrlicht device

_No response_

### Operating system and version

Devuan Daedalus (eq to Debian Bookworm)

### CPU model

_No response_

### GPU model

_No response_

### Active renderer

_No response_

### Summary

While visual="sprite" works fine, visual="upright_sprite" does not animate properly on current Minetest stable. The sprite sits, frozen.

### Steps to reproduce

Load the attached snippet in devtest. Left click places an upright sprite entity, right click a regular sprite one that is otherwise identical. The upright doesn't animate, the player-facing one does.
```
minetest.register_entity("animtest:sprite",{
	initial_properties = {
	   visual = "upright_sprite",
	   collides_with_objects = false,
	   textures = { "testnodes_anim.png",},
	   spritediv = { x = 1, y = 4 },
	},
	on_activate = function(self, dtime, moveresult)
	   self.init = true
	   self.timelimit = 20
	   self.object:set_sprite(nil, 4, .5)
	end,
	on_step = function(self, dtime, moveresult)
	   self.timer = ( self.timer or 0 ) + dtime
	   if self.timer < self.timelimit then return end
	   self.object:remove()
	end,
})

local function set_up_entity(pointed_thing)
	local ppos = pointed_thing.under
	if not vector.check(ppos) then return end

	local pos = vector.new(ppos.x, ppos.y + 1, ppos.z)
	return minetest.add_entity(pos, "animtest:sprite")
end

minetest.register_craftitem("animtest:sprite_item",
  {
     description = "Animated sprite entity test",
     inventory_image = "testnodes_anim.png^[verticalframe:4,1",
     on_use = function(itemstack, user, pointed_thing)
	set_up_entity(pointed_thing)
     end,
     on_place = function(itemstack, user, pointed_thing)
	local ent = set_up_entity(pointed_thing)
	ent:set_properties({ visual = "sprite" })
     end
})

```

### PR DESCRIPTION
**Pull request by appgurueu**
Fixes #15105. We just need to mark the mesh buffers as dirty after manipulating the vertices so that they get reuploaded to the GPU.

### CODE REVIEW

File: src/client/mesh.cpp [hunk 1]
```diff
@@ -199,11 +200,12 @@ void setMeshColor(scene::IMesh *mesh, const video::SColor &color)
 
 void setMeshBufferTextureCoords(scene::IMeshBuffer *buf, const v2f *uv, u32 count)
 {
-	const u32 stride = getVertexPitchFromType(buf->getVertexType());
+	assert(buf->getVertexType() == video::EVT_STANDARD);
```
Comment (appgurueu) [inline src/client/mesh.cpp:203]: This code only makes sense for `EVT_STANDARD` because we treat `vertices` as an array of `S3DVertex` below and we can't really make assumptions about struct layout here.

The only usage of this function is in the upright sprite code, where the type will always be `EVT_STANDARD`, so this is fine.

Comment (sfan5) [reply src/client/mesh.cpp:203]: maybe just copy it there then?

**Review by sfan5 — APPROVED** [review]

**Review by sfan5 — APPROVED** [review]
