### PR TITLE
Inventory: Handle removeItem leftovers

### LINKED ISSUE #8883: InvRef's remove_item(listname, stack) method is giving wrong results when stack is larger than stack_max
##### Issue type
 - Bug report
 
##### Minetest version

```
minetest-5.0.1-win64
```

##### OS / Hardware

Operating system: Windows 10 Home
CPU: Intel i7-3770K @ 3.5GHz, 8.00 GB ram

##### Summary

I was doing a bit of modding where I wanted to remove large amounts of a specific item from an inventory and at first it seemed like using remove_stack would work even when the amount I needed to remove exceeded that item type's max_stack. But I got some very peculiar results - there were no error messages but the math didn't add up correctly. I feel that either this should have worked correctly or an error should have been thrown at some point in the process described below in the steps-to-reproduce section.

##### Steps to reproduce

The following code, placed in the init.lua of a mod that depends on default, will reproduce the behaviour I was seeing:

```
minetest.register_node("test:inventory", {
	description = "Test inventory",
	tiles = {"default_wood.png^[brighten"},
	groups = {oddly_breakable_by_hand = 1},

	on_construct = function(pos)
		local meta = minetest.get_meta(pos)
		local inv = meta:get_inventory()
		inv:set_size("main", 8*4)
		-- Add 150 wood planks in three stacks of 50
		for i = 1, 3 do
			inv:set_stack("main", i, ItemStack("default:wood 50"))
		end
		meta:set_string("formspec", default.chest.get_chest_formspec(pos))
	end,
		
	on_punch = function(pos, node, puncher, pointed_thing)
		local meta = minetest.get_meta(pos)
		local inv = meta:get_inventory()
		minetest.debug("Starting inventory:")
		for i, item in ipairs(inv:get_list("main")) do
			if item:get_count() > 0 then
				minetest.debug(i .. " " .. item:to_string())
			end
		end
		-- This itemstack is one larger than the default stack_max for wood (99)
		local itemstack_to_remove = ItemStack("default:wood 100")
		minetest.debug("Normal stack max is ".. itemstack_to_remove:get_stack_max())
		minetest.debug("Removing: " .. itemstack_to_remove:to_string())
		local removed = inv:remove_item("main", itemstack_to_remove)
		minetest.debug("Removed: " .. removed:to_string())
		minetest.debug("Ending inventory:")
		for i, item in ipairs(inv:get_list("main")) do
			if item:get_count() > 0 then
				minetest.debug(i .. " " .. item:to_string())
			end
		end		
	end,
})
```

When on_punch is triggered the resulting relevant section of the debug log reads:

```
2019-08-31 22:08:34: [Server]: Starting inventory:
2019-08-31 22:08:34: [Server]: 1 default:wood 50
2019-08-31 22:08:34: [Server]: 2 default:wood 50
2019-08-31 22:08:34: [Server]: 3 default:wood 50
2019-08-31 22:08:34: [Server]: Normal stack max is 99
2019-08-31 22:08:34: [Server]: Removing: default:wood 100
2019-08-31 22:08:34: [Server]: Removed: default:wood 99
2019-08-31 22:08:34: [Server]: Ending inventory:
2019-08-31 22:08:34: [Server]: 1 default:wood 49
```

The ending inventory should have had either 50 or 51 wood in it, but instead it had 49. Or if the creation of an ItemStack with more than stack_max should never be allowed in the first place the "local itemstack_to_remove = ItemStack("default:wood 100")" line should have failed in some way, or at least logged an error. The ending inventory having 49 wood without any errors being raised is kind of baffling, and made it rather hard to track down the problem I was having (I've since solved it by manually capping the itemstack_to_remove at stack_max and doing multiple rounds of remove_item to get the right amount out).

### PR DESCRIPTION
**Pull request by SmallJoker**
Fixes #8883

New output:
```
2019-09-01 09:45:11: [Server]: Starting inventory:
2019-09-01 09:45:11: [Server]: 1 default:wood 50
2019-09-01 09:45:11: [Server]: 2 default:wood 50
2019-09-01 09:45:11: [Server]: 3 default:wood 50
2019-09-01 09:45:11: [Server]: 4 default:wood 50
2019-09-01 09:45:11: [Server]: Normal stack max is 99
2019-09-01 09:45:11: [Server]: Removing: default:wood 100
2019-09-01 09:45:11: [Server]: Removed: default:wood 100
2019-09-01 09:45:11: [Server]: Ending inventory:
2019-09-01 09:45:11: [Server]: 1 default:wood 50
2019-09-01 09:45:11: [Server]: 2 default:wood 50
```

## To do

This PR is Ready for Review.

## How to test

1) Take the code from #8883 entirely, override the chest definition
2) Fill in enough stacks
3) Punch the testing node
4) The removed count must be 100 and matches with the leftover items in the inventory.

### CODE REVIEW

File: src/inventory.cpp [hunk 1]
```diff
@@ -680,7 +680,11 @@ ItemStack InventoryList::removeItem(const ItemStack &item)
 	for (auto i = m_items.rbegin(); i != m_items.rend(); ++i) {
 		if (i->name == item.name) {
 			u32 still_to_remove = item.count - removed.count;
-			removed.addItem(i->takeItem(still_to_remove), m_itemdef);
+			ItemStack leftover = removed.addItem(i->takeItem(still_to_remove),
+					m_itemdef);
```
Comment (ClobberXD) [inline src/inventory.cpp]: Continuation lines only require one extra tab of indentation

Comment (SmallJoker) [reply src/inventory.cpp]: But two are OK too

Comment (ClobberXD) [reply src/inventory.cpp]: One is what our code-style demands, though...
