### PR TITLE
Sound refactor and improvements

### LINKED ISSUE #4256: Fade and sound playback with gain <= 0 delete the handle (for mute)
I would suggest the function sound_mute() to mute currently played sounds without stopping them. Parameters are the sound handle and a boolean to turn mute on and off.

Additionally or alternatively the function sound_volume(handle, gain) would be helpful

### LINKED ISSUE #6622: Add warning when stereo sounds are loaded
So I recently learned that stereo sounds are taboo in Minetest.

It took me **weeks** to figure out why the snow sounds in my subgame are so weird and broken. The answer was of course they were in stereo … XD

Here's a suggestion: When Minetest detects that it has loaded a stereo sound, write a warning into the console.

### LINKED ISSUE #6748: minetest.sound_fade doesn't work with positional sounds.

### LINKED ISSUE #9172: Add Doppler effect
## Problem

With the introduction of the advtrains mod, entities were added that move at high speeds (up to 70 km/h), which already causes significant sound distortion due to doppler effect. 

## Solutions

Set the velocity correctly in the OpenAL sound object.

## Alternatives

Unrealistic sounds in advtrains.

## Additional context

I have tried implementing this. However, I have stumbled upon the issue of finding a CAO's velocity, which I do not know how to resolve.

### LINKED ISSUE #10603: Music / large sound files significantly slow down game startup
If your game (or mod) includes large sound files such as a couple of music tracks, the startup of the game is being significantly slowed down.

How to reproduce:
* Create a dummy mod with an empty `init.lua` and a `sounds` directory with 10 random music tracks from your favourite album (In `.ogg` format)
* Start DevTest (or any minimal dummy game) with this mod enabled
* Compare startup time of DevTest without this mod enabled

Version: 5.3.0

### LINKED ISSUE #10979: Audio: Error opening file for decoding
Minetest 5.3.0 **and** 5.4.0
Linux Mint 20.1
Using the stable PPA: ppa:minetestdevs/stable

> 2021-02-18 19:26:06: INFO[Main]: 
> 2021-02-18 19:26:06: INFO[Main]: Audio: Error opening /home/nicu/.minetest/sounds/main_menu.1.ogg for decoding
> 2021-02-18 19:26:06: INFO[Main]: Audio: Error opening /home/nicu/.minetest/sounds/main_menu.2.ogg for decoding
> 2021-02-18 19:26:06: INFO[Main]: Audio: Error opening /home/nicu/.minetest/sounds/main_menu.3.ogg for decoding
> 2021-02-18 19:26:06: INFO[Main]: Audio: Error opening /home/nicu/.minetest/sounds/main_menu.4.ogg for decoding
> 2021-02-18 19:26:06: INFO[Main]: Audio: Error opening /home/nicu/.minetest/sounds/main_menu.5.ogg for decoding
> 2021-02-18 19:26:06: INFO[Main]: Audio: Error opening /home/nicu/.minetest/sounds/main_menu.6.ogg for decoding
> 2021-02-18 19:26:06: INFO[Main]: Audio: Error opening /home/nicu/.minetest/sounds/main_menu.7.ogg for decoding
> 2021-02-18 19:26:06: INFO[Main]: Audio: Error opening /home/nicu/.minetest/sounds/main_menu.8.ogg for decoding
> 2021-02-18 19:26:06: INFO[Main]: Audio: Error opening /home/nicu/.minetest/sounds/main_menu.9.ogg for decoding
> 2021-02-18 19:26:06: INFO[Main]: Audio: Error opening /home/nicu/.minetest/sounds/main_menu.ogg for decoding
> 2021-02-18 19:26:06: INFO[Main]: Audio: Error opening /usr/share/minetest/sounds/main_menu.0.ogg for decoding
> 2021-02-18 19:26:06: INFO[Main]: Audio: Error opening /usr/share/minetest/sounds/main_menu.1.ogg for decoding
> 2021-02-18 19:26:06: INFO[Main]: Audio: Error opening /usr/share/minetest/sounds/main_menu.2.ogg for decoding
> 2021-02-18 19:26:06: INFO[Main]: Audio: Error opening /usr/share/minetest/sounds/main_menu.3.ogg for decoding
> 2021-02-18 19:26:06: INFO[Main]: Audio: Error opening /usr/share/minetest/sounds/main_menu.4.ogg for decoding
> 2021-02-18 19:26:06: INFO[Main]: Audio: Error opening /usr/share/minetest/sounds/main_menu.5.ogg for decoding
> 2021-02-18 19:26:06: INFO[Main]: Audio: Error opening /usr/share/minetest/sounds/main_menu.6.ogg for decoding
> 2021-02-18 19:26:06: INFO[Main]: Audio: Error opening /usr/share/minetest/sounds/main_menu.7.ogg for decoding
> 2021-02-18 19:26:06: INFO[Main]: Audio: Error opening /usr/share/minetest/sounds/main_menu.8.ogg for decoding
> 2021-02-18 19:26:06: INFO[Main]: Audio: Error opening /usr/share/minetest/sounds/main_menu.9.ogg for decoding
> 2021-02-18 19:26:06: INFO[Main]: Audio: Error opening /usr/share/minetest/sounds/main_menu.ogg for decoding

I'm not sure about 5.3.0, but in 5.4.0 I also noticed this after the failed audio files opening:
> 2021-02-24 00:21:06: INFO[Main]: OpenALSoundManager: "main_menu" not found.

Minor thing, but if the game first tried to check the existence of the /sounds/ directory, there would be less attempts to open files. For whatever reason, the PPA packages don't include sounds.

### LINKED ISSUE #11414: Incomplete Documentation of 'params' sound parameter table, used by minetest.sound_play()
## Problem

In the lua doc, a list of all available parameters for a 'sound parameter table' is missing, as is used by the function 'minetest.sound_play()'
Even with the supplied examples, this is lacking compared to the information provided on SimpleSoundSpec in the same section, and leaves several open questions. These can only be answered by looking at least at 3 different places in the source code.

Details:

In the minetest namespace reference section of the docs, the following is written:

```
...
minetest.sound_play(spec, parameters, [ephemeral]): returns a handle

    spec is a SimpleSoundSpec
    parameters is a sound parameter table
    ephemeral is a boolean (default: false) Ephemeral sounds will...
    ...
```

In the 'Sounds' section of the docs, the following is included:

- List of all parameters available in SimpleSoundSpec tables
- Examples of SimpleSoundSpec tables
- Examples of various Sound-Parameter tables for the 'parameters' table (second argument in 'minetest.sound_play')

The following is missing:

- List of all parameters available in 'parameters' table (second argument in 'minetest.sound_play')

There is no other section in the docs which details this 'parameters' table.

Source:
     https://github.com/minetest/minetest/blob/master/doc/lua_api.txt#L848-L896
     https://github.com/minetest/minetest/blob/master/doc/lua_api.txt#L5498-L5504

Version for easier reading:
     https://minetest.gitlab.io/minetest/sounds.html
     https://minetest.gitlab.io/minetest/minetest-namespace-reference.html

## Solutions

Add more clear documentation of available values to set, whether said list is complete, and details on the meaning of individual values.

When simply combining the list of all parameters used in the examples provided for the 'parameters' table of the 'Sound' section in the lua docs, we get the following:
```
--This is a combined list of all parameters used in the examples in 'Sounds' section:

{
to_player=name, 	--play locationless to one player
pos = {x = 1, y = 2, z = 3} -- play at a spot
object = <an ObjectRef>  --play connected to an object
gain=1.0, 		--default
fade=1.0, 		--default
pitch=1,0, 		--default
loop=true,
max_hear_distance=32, 	--default, uses an euclidean metric
exclude_player=name	--heard by anyone *but* the given player
}
```
Even with the above list, there remain the following questions:

1. Are these all parameters that are available? If yes, can we add this list to the documentation? 
2. Can several players be excluded/included?
3. Do the gain and pitch values of this table... override/get replaced by/combine with ...the values given in SimpleSoundSpec?

Results of digging into the code, and answers to the questions above:

1. _Are these all parameters that are available?_
   yes, these are all available parameters for the Sound-Parameter-Table. Source:
       https://github.com/minetest/minetest/blob/master/src/server.h#L94

2. _Can several players be excluded/included?_
    only one player can be specified to be excluded from sound. Source:
        https://github.com/minetest/minetest/blob/master/src/server.cpp#L2085
    one player can be specified to be directly played the sound to. Source:
        https://github.com/minetest/minetest/blob/master/src/server.cpp#L2066

3. _Do the gain and pitch values of this table... override/get replaced by/combine with ...the values given in SimpleSoundSpec?_
    First, the input variables are taken from 'params', and then the values from SimpleSoundSpec(='spec') are taken. ~~Which means, the **pitch** of params is overwritten by the **pitch** defined in SimpleSoundSpec - while it is an optional field to define in SimpleSoundSpec, it is set to '1' (float) by default, so it _should_ always overwrite the pitch in params. _(This is something I'm not 100% certain of.)_~~
    EDIT: actual ingame tests confirmed the opposite: SSS' 'pitch' is completely ignored. SP (sound parameter table)'s 'pitch' value works as expected. When providing both tables with a 'pitch' value, SSS's is still completely ignored and does not alter the result. Thats because while the initial pitch value of SP is overwritten by SSS', when the packet gets created a few lines below, the pitch value is directly taken from SP again.
     Source:
    https://github.com/minetest/minetest/blob/master/src/server.cpp#L2116
    https://github.com/minetest/minetest/blob/master/src/server.cpp#L2123
    https://github.com/minetest/minetest/blob/master/src/sound.h#L29
    
    For the **gain**, it's a different story however: there is an additional line undoing this 'overwriting', which multiplies the **gain** set in the 'params' table with the **gain** set in the SimpleSoundSpec table (='spec'). 
    EDIT: ingame tests confirm this works as expected, both values are taken and multiplied for the result.
    Source:
    https://github.com/minetest/minetest/blob/master/src/server.cpp#L2119

## Alternatives

Keep the current documentation and let everyone search for these things when they come upon it, with a contrast between the documentation quality of 'SimpleSoundSpec' and the sound 'params' table, directly next to each other in the docs. Since there's a lot of files which touch audio, a simple search through the source is also not immediately giving the answers until you narrow it down to these three places. 

This is fine if noone ever uses the minetest.play_sound effect but only uses the inbuilt sounds functionality from node definitions etc., but incomplete when it comes to actually using the command.

EDIT NOTES: correctly included some missing values in the list as sfan5 pointed out.

### LINKED ISSUE #11865: Start a sound at a specific timestamp
## Problem

You cant play a sound starting at a specific timestamp.
This feature is useful for things like pausing music.

**This is different from #10306**

## Solutions

Add a timestamp field to the sound parameters table.

## Alternatives

-

## Additional context

-

### PR DESCRIPTION
**Pull request by Desour**
- Big refactor of the client-side sound manager, and other things related to sounds. See below for a list of changes.
- Does this relate to a goal in [the roadmap](../doc/direction.md): Most of the PR can be considered internal code refactoring.
- PR contains bugfixes.

PR is based on:
* #12766 (If we don't pause sounds, the sound queues for streaming sounds will run empty.)
* #12774

### Changes

This PR includes the following changes (list may miss minor changes that I forgot):

* **Terminology and Documentation:** Definition of "sound groups" (i.e. `sound.1.ogg`, `sound.2.ogg`, ...).
* **Enhancement:** Sounds are loaded lazily. This makes the client connect much faster.
  (fixes #10603, improves #10316)
* **Enhancement:** Long sounds (> 3 seconds) (i.e. music) are streamed (not over network, but from file). So, the client doesn't freeze anymore when music from the sound-pack or dynamic media is played. 
  (makes #8596/#7867 possible)
* **API feature:** ~~`time_offset`~~ `start_time` sound param (offset in seconds into file).
  (fixes #11865; will be needed at some point anyways for players entering max_hear_distance)
  (also fixes #4256)
* **Fix:** Sound is no longer upside-down. (see comment in `sound_openal_internal.h` about sound-space) (test with hrtf)
* **Internal refactor:** Got rid of BS in sound manager.
* **API change:** Sound handles are now userdata. => method syntax; ids are owned and garbage collected
  Edit: Server sound change moved out to #12780.
* **Enhancement/Fix:** Sounds are paused while in pause menu in singleplayer.
* ~~**Fix:** Shader animation timer is also paused. (Has nothing to do with sounds, but I was already at it.)~~
  Edit: Moved out to #12766.
* **Fix:** Warning in ~~errorstream~~ warningstream for positional stereo sounds, ~~and don't play~~.
  (fixes #6622)
* **Fix:** Don't spam (infostream) logs with every file tried in sound-pack.
  (fixes #10979)
* **Documentation:** Add correct documentation of sound params, and more details for gain of positional sounds.
  (fixes #11414)
* **Fix:** Enable fade in for positional sounds.
  (fixes #6748)
* **Fix:** Fade correctly for positional sounds. (`step` is scaled correctly (used to be too slow by a factor of 3). And you can fade to gain>1/3.)
* **Fix:** Vorbis seek callback now supports SEEK_END (is *not* optional according to <https://www.xiph.org/vorbis/doc/vorbisfile/callbacks.html>). (Idk if this has practical relevance.)
* **Enhancement:** ~~Doppler effect.~~ Edit: Disabled. It should be server-controlled.
  (see: #9172)
* **Feature:** Client-side setting for doppler factor (because you can be very fast in minetest).
* ~~**Fix/Enhancement:** Footstep sounds of objects are played at feet (found via collisionbox). (Velocity is still 0, btw..)~~
  Edit: Moved out to #12768.
* **No change:** Player footstep sounds are still position-less (sounds bad otherwise, if running with fast).
* **Internal refactor:** C++ `SimpleSoundSpec` struct was renamed to `SoundSpec`, because it's not simple, and to differentiate from modding `SimpleSoundSpec`.
* **Enhancement:** Testing devices in devtest: jukebox updated; racecar for doppler
* **Internal refactor:** `OnDemandSoundFetcher` was renamed to `SoundLocalFallbackPathsGiver`, as that describes better what it does.
* **Internal refactor:** Some smart-ptr-isation here and there.
* **Internal refactor / design change:** The sound manager API is changed in such a way that the functions could be implemented asynchronously. E.g. soundPlay does not return an id, instead you have to give an id that you allocated before. Moving the sound manager to a different thread would be relatively easy.

### Review help

* The `client/sound*` files contain the most real changes. Everything else is essentially just adjusted to the new interface.
  You can compare behaviour of `sound_openal_internal.h/cpp` with the old `sound_openal.cpp`, but idk if it helps.
  Notice that the new interface handles client sound handles differently.
* `client/client.h/cpp` contains two interesting changes: It creates sound groups based on base names, and `m_sounds_client_to_server` now owns client-handles.
* `game.cpp`: `GameOnDemandSoundFetcher` was moved to `client/sound.cpp`. Also, sounds are paused here.
* `guiEngine.h/cpp`: Uses no more raw ptrs (creates some code-change-noise, but not really much). `MenuMusicFetcher` is simplified, by using base-class functions. `GUIEngine::playSound` is removed, it's only used by mainmenu scripting.
* `clientpackethandler.cpp`: Uses ids. And `time_offset` is added.
* `l_sound.h/cpp`: Is now `l_mainmenu_sound.h/cpp`.
* The scripting changes are much code, but very simple. It's mostly copied code and boilerplate code for userdata handles. Otherwise, it just has the `SoundSpec` renames, and it uses the new id system.
* `server.cpp`: Sends `time_offset`.
* `src/sound.h`: The `use_local_fallback` is currently unused. But it's passed to the sound manager and should be functional, if the sound wasn't played before.
* Everything else is just trivial renaming (`SoundSpec`) and smart-ptrs.

## To do

This PR is a Ready for Review.

## How to test

* Just play and look if there are any warnings or similar.
* Walk to listen to footsteps.
* Punch.
* Press esc (to pause sounds).
* Use the devtest jukebox, e.g. to play a technic track from your sound-pack: <https://wiki.minetest.net/Sound_Packs#Technic>
* `/set sound_doppler_factor` Edit: Doppler effect is disabled, and this setting does not exist.
* Drive around in cart.
* To enable hrtf: `$ alsoft-config` -> HRTF -> HRTF mode: Always on.
* Use the entity spawner item in devtest to spawn a racecar. Give it a name with the branding iron. Play a sound attached to it with the jukebox. Or attach yourself to it with the object attacher devtest tool.

### CODE REVIEW

**Comment by MisterE123** [comment]
I hope this gets merged. I recognized several bugs that I was annoyed at in the game without realizing it.

**Comment by appgurueu** [comment]
> Sounds are loaded lazily. This makes the client connect much faster.

Does this introduce any significant delay in sound playback?

**Comment by rubenwardy** [comment]
> Does this introduce any significant delay in sound playback?

Yeah, sounds shouldn't be lazy loaded. Only music should be. Mods should then choose between music and sound based on what kind of latency then can tolerate

However, I suspect they mean lazy loading from client cache on disk, rather than over the network

**Comment by sfan5** [comment]
I think Minetest should automatically decide whether to pre-load sounds, quoting https://github.com/minetest/minetest/issues/10603#issuecomment-723894636:

> There's a good reason to preload short sounds, but not music or ambient textures, because that's a ton of decoding work and wasted RAM.

> Game engines usually give you both options. Unity for example lets you choose between preloaded ADPCM in memory for short clips, and Vorbis decoded on the fly for longer sounds. We could autodetect this based on the clip length, something like 10 seconds should disqualify a sound from being preloaded.

> The first few seconds of streamed clips could still be cached to give the decoder some time to build a buffer.

<hr>

Feedback as already written on IRC:
* at the very least the "I happened to touch this code and made it better" changes (for code unrelated to sound) should be in a separate commit
* also the addition of ServerSoundRef

**Comment by Desour** [comment]
I consider this PR ready for review now.

It would make sense to review and merge the dependencies first though.

**Comment by Desour** [comment]
Rebased.
And also positional stereo sounds are played now, to keep backwards compatibility. They are still broken tough. There's a warning.

**Comment by Desour** [comment]
Rebased.

**Comment by Desour** [comment]
Rebased.

File: src/client/client.h [hunk 1]
```diff
@@ -67,6 +67,7 @@ class NetworkPacket;
 namespace con {
 class Connection;
 }
+using sound_handle_t = int;
```
Comment (nerzhul) [inline src/client/client.h:70]: why using and not typedef ? doesn't  this typedef should be in sound.h ?

File: src/client/game.cpp [hunk 2]
```diff
@@ -1338,20 +1296,21 @@ bool Game::initSound()
...
-	if (!sound) {
+	if (!sound_manager) {
 		infostream << "Using dummy audio." << std::endl;
-		sound = &dummySoundManager;
-		sound_is_dummy = true;
+		sound_manager = std::make_unique<DummySoundManager>();
 	}
 
-	soundmaker = new SoundMaker(sound, nodedef_manager);
+	soundmaker = new SoundMaker(sound_manager.get(), nodedef_manager);
```
Comment (nerzhul) [inline src/client/game.cpp:1313]: i'm clearly not fan of a unique_ptr passing as regular ptr in many places

File: src/client/client.h (hunk 1 above)
Comment (rubenwardy) [reply src/client/client.h:70]: using should be preferred over typedef.  typedef is C and using is C++

Comment (Desour) [reply src/client/client.h:70]: >doesn't this typedef should be in sound.h ?

It's a using *declaration*. Declarations can be done multiple times in one translation unit as long as they are all the same.
See this as a forward declaration. Like this, we don't need to include sound.h.

File: src/client/game.cpp (hunk 2 above)
Comment (Desour) [reply src/client/game.cpp:1313]: SoundMaker doesn't own its ISoundManager ptr, hence the raw ptr.

File: src/client/client.h (hunk 1 above)
Comment (rubenwardy) [reply src/client/client.h:70]: This `using` should be outside the namespace though, as `using` obeys namespacing rules - unlike `typedef`.

Proof: https://ideone.com/BAB4F5

Comment (rubenwardy) [reply src/client/client.h:70]: ahhhh, the lack of indentation threw me off

**Comment by Zughy** [comment]
@Desour rebase needed

**Comment by Desour** [comment]
I'll rebase once it's no longer waiting.

**Comment by MisterE123** [comment]
It would be amazing to have this for 5.7. Any chance?

**Comment by Desour** [comment]
No longer waiting. Rebased.

**Comment by Zughy** [comment]
@Desour please rebase

**Comment by Desour** [comment]
Rebased.

File: builtin/client/finish_core_api.lua [hunk 3]
```diff
@@ -0,0 +1,10 @@
+
+-- old non-method sound functions
+
+function core.sound_stop(handle, ...)
+	return handle:stop(...)
+end
+
+function core.sound_fade(handle, ...)
+	return handle:fade(...)
+end
```
Comment (sfan5) [inline builtin/client/finish_core_api.lua:10]: why isn't this in misc.lua?

File: src/client/sound.h [hunk 4]
```diff
@@ -19,75 +19,166 @@ with this program; if not, write to the Free Software Foundation, Inc.,
...
+	 */
+	virtual void updateSoundPosVel(sound_handle_t sound, const v3f &pos,
+			const v3f &vel) = 0;
+
+	/**
+	 * Get and reset the list of sounds that were stopped.
+	 */
+	std::vector<sound_handle_t> pollRemovedSounds()
 	{
+		return std::move(m_removed_sounds);
```
Comment (sfan5) [inline src/client/sound.h:145]: I'm not 100% on the state of objects after moving, so this would be better
```suggestion
		std::vector<sound_handle_t> ret;
		std::swap(ret, m_removed_sounds);
		return ret;
```

File: src/client/sound_openal_internal.cpp [hunk 5]
```diff
@@ -0,0 +1,1146 @@
...
+}
+
+static bool can_open_file(const std::string &path) noexcept
+{
+	std::FILE *f = std::fopen(path.c_str(), "r");
+	if (!f)
+		return false;
+	std::fclose(f);
+	return true;
+}
```
Comment (sfan5) [inline src/client/sound_openal_internal.cpp:76]: would `fs::PathExists` suffice?
if not this would still be more modern:
```cpp
std::ifstream fis(path.c_str());
return fis.good();
```

File: src/client/sound_openal_internal.cpp [hunk 6]
```diff
@@ -0,0 +1,1146 @@
...
+
+// Transforms vectors from a left-handed coordinate system to a right-handed one
+// and vice-versa.
+// (Needed because Minetest uses a left-handed one and OpenAL a right-handed one.)
+static v3f swap_handedness(const v3f &v) noexcept
```
Comment (sfan5) [inline src/client/sound_openal_internal.cpp:81]:
```suggestion
static inline v3f swap_handedness(v3f v) noexcept
```

File: src/client/sound_openal_internal.cpp [hunk 7]
```diff
@@ -0,0 +1,1146 @@
...
+			warningstream << "Audio: Error decoding (could not seek) "
+					<< decode_info.name_for_logging << std::endl;
+			return RAIIALSoundBuffer();
+		}
+	}
+
+	const size_t size = static_cast<size_t>(pcm_end - pcm_start)
+			* decode_info.bytes_per_sample;
+
+	std::unique_ptr<char[]> snd_buffer(new char[size]);
```
Comment (sfan5) [inline src/client/sound_openal_internal.cpp:231]: I suggest just using a `std::vector`

File: src/client/sound_openal_internal.cpp [hunk 8]
```diff
@@ -0,0 +1,1146 @@
...
+	} else {
+		return std::make_shared<SoundDataOpenStream>(std::move(oggfile), *decode_info);
+	}
+}
+
+/*
+ * SoundDataUnopenBuffer struct
+ */
+
+std::shared_ptr<ISoundDataOpen> SoundDataUnopenBuffer::open(const std::string &sound_name) &&
```
Comment (sfan5) [inline src/client/sound_openal_internal.cpp:350]: I don't get what "unopen" means here

File: src/client/sound_openal_internal.h [hunk 9]
```diff
@@ -0,0 +1,625 @@
...
+ * * Use `swap_handedness()` to convert between those two coordinate spaces.
+ *
+ *
+ * How sounds are loaded:
+ * ----------------------
+ *
+ * * Step 1:
+ *   `loadSoundFile` or `loadSoundFile` is called. This adds an unopen sound with
+ *   the given name to `m_sound_datas_unopen`.
+ *   Unopen sounds (`ISoundDataUnopen`) are ogg-vorbis files that we did not yet
```
Comment (sfan5) [inline src/client/sound_openal_internal.h:72]: Hmm, if this was named lazy I think that'd be more obvious.

File: src/client/sound_openal_internal.h [hunk 10]
```diff
@@ -0,0 +1,625 @@
...
+	DISABLE_CLASS_COPY(RAIIALSoundBuffer)
+
+	RAIIALSoundBuffer(RAIIALSoundBuffer &&other) noexcept : m_buffer(other.release()) {}
+	RAIIALSoundBuffer &operator=(RAIIALSoundBuffer &&other) noexcept;
+
+	friend void swap(RAIIALSoundBuffer &l, RAIIALSoundBuffer &r) noexcept
+	{
+		using std::swap;
+		swap(l.m_buffer, r.m_buffer); // no reset() needed
+	}
```
Comment (sfan5) [inline src/client/sound_openal_internal.h:170]: I'm wondering, do you actually need to implement these or won't the implicit constructors do everything out-of-the-box? (via `ALLOW_CLASS_MOVE`)

File: src/script/lua_api/l_mainmenu_sound.h [hunk 11]
```diff
@@ -21,13 +21,42 @@ with this program; if not, write to the Free Software Foundation, Inc.,
 #pragma once
 
 #include "lua_api/l_base.h"
+#include "util/basic_macros.h"
 
-class ModApiSound : public ModApiBase
+using sound_handle_t = int;
```
[the remark this answers is not in the document]
Comment (Desour) [reply src/script/lua_api/l_mainmenu_sound.h:26]: It's a forward declaration. (Yes, typedefs and using declarations are declarations, and therefore don't violate ODR.)

File: builtin/client/finish_core_api.lua (hunk 3 above)
Comment (Desour) [reply builtin/client/finish_core_api.lua]: Because misc.lua is loaded after all the other lua files.

But considering the sort of functions defined in misc.lua, this makes sense. Moved.

File: src/client/sound.h [hunk 12]
```diff
@@ -19,75 +19,166 @@ with this program; if not, write to the Free Software Foundation, Inc.,
...
+#include <limits>
+#include <string>
+#include <unordered_map>
+#include <unordered_set>
+#include <vector>
 
-class OnDemandSoundFetcher
+struct SoundSpec;
+
+class SoundLocalFallbackPathsGiver
```
[the remark this answers is not in the document]
Comment (Desour) [reply src/client/sound.h:31]: Done.

File: src/client/sound.h (hunk 4 above)
Comment (Desour) [reply src/client/sound.h:145]: According to reference:
>After the move, other is guaranteed to be empty().

(See std::vector constructor.)

Will still do the suggested change, so nobody asks themselves the same question. *shrug*

File: src/client/sound.h [hunk 13]
```diff
@@ -19,75 +19,166 @@ with this program; if not, write to the Free Software Foundation, Inc.,
...
+	 *                   a sound and store the id also otherwhere.
+	 */
+	sound_handle_t allocateId(u32 num_owners);
+
+	/**
+	 * Free an id allocated via allocateId.
+	 * @param num_owners How much the owner-counter should be decreased. Id can
+	 *                   be reused when counter reaches 0.
+	 */
+	void freeId(sound_handle_t id, u32 num_owners);
```
[the remark this answers is not in the document]
Comment (Desour) [reply src/client/sound.h:161]: I wasn't sure about this, and preferred explicitness. But looking at it again, this probably makes sense.

File: src/client/sound_openal_internal.cpp (hunk 7 above)
Comment (Desour) [reply src/client/sound_openal_internal.cpp:231]: Afaik, it is not easily possible to make a std::vector with uninitialized elements. So that would be slightly slower (and hence less elegant).

This here on the other hand does the same as C++17 std::make_unique_for override.

File: src/client/sound_openal_internal.h (hunk 10 above)
Comment (Desour) [reply src/client/sound_openal_internal.h:170]: I think I misunderstood std::swap. The description of Swappable and the existence of all the specializations for std containers made me think that std::swap was not implemented automatically for user-provided types. Now I think it is.

Removed the swap functions.

File: src/client/sound_openal_internal.cpp (hunk 8 above)
Comment (Desour) [reply src/client/sound_openal_internal.cpp:343]: Added comment to SoundDataUnopenBuffer struct. (See also comment below.)

File: src/client/sound_openal_internal.h (hunk 9 above)
Comment (Desour) [reply src/client/sound_openal_internal.h]: I didn't want to rename the struct to `ISoundDataLazy` because that wouldn't really sound like an antipole to "open". Also, `SoundDataOpenStream` also load lazily in a way.

I added comments though.

**Comment by Desour** [comment]
Thanks for the review!

**Comment by Desour** [comment]
I've disabled doppler effect for now.
We should later add an API for the server to control doppler factor and speed of sound.

File: src/client/sound_openal_internal.cpp (hunk 7 above)
Comment (sfan5) [reply src/client/sound_openal_internal.cpp:224]: Well whatever.

File: src/client/sound_openal_internal.h (hunk 10 above)
Comment (sfan5) [reply src/client/sound_openal_internal.h]: What about `RAIIALSoundBuffer(RAIIALSoundBuffer &&other)`?

File: src/network/networkprotocol.h [hunk 14]
```diff
@@ -215,9 +215,12 @@ with this program; if not, write to the Free Software Foundation, Inc.,
 		new fields for TOCLIENT_SET_LIGHTING and TOCLIENT_SET_SKY
 		Send forgotten TweenedParameter properties
 		[scheduled bump for 5.7.0]
+	PROTOCOL VERSION 43:
+		"time_offset" added to TOCLIENT_PLAY_SOUND
+		[scheduled bump for 5.8.0]
```
[the remark this answers is not in the document]
Comment (sfan5) [reply src/network/networkprotocol.h:220]: Sure I guess, not like we need to do the protocol bump as last as possible.

File: src/client/sound_openal_internal.h (hunk 10 above)
Comment (Desour) [reply src/client/sound_openal_internal.h]: > What about `RAIIALSoundBuffer(RAIIALSoundBuffer &&other)`?

That one already exists, 7 lines above. :upside_down_face:

**Comment by Desour** [comment]
Note:
It looks like I had some misconception about pitch. I thought pitch would change the pitch and resample the sound, so that the playback speed is the same as with pitch=1. However, according to openal spec:
>a pitch-shifted source will have an exaggerated playback speed. For example, you can be 0.500 seconds into a buffer having taken only 0.250 seconds to get there if the pitch is set to 2.0.

In practice this means that streamed sounds run into empty queues if the pitch is too high. However, as `MIN_STREAM_BUFFER_LENGTH` is more than big enough compared to `STREAM_BIGSTEP_TIME`, this will only happen non-rarely if you play some long sound with really high pitch.
As increasing the pitch for music is uncommon anyway, this is probably no relevant issue.

File: src/script/lua_api/l_client_sound.cpp [hunk 15]
```diff
@@ -0,0 +1,148 @@
+/*
+Minetest
+Copyright (C) 2013 celeron55, Perttu Ahola <celeron55@gmail.com>
```
[the remark this answers is not in the document]
Comment (Desour) [reply src/script/lua_api/l_client_sound.cpp:3]: The stuff in these files was initially copied from other files, like `l_sound.cpp`. My only real contribution was the sound handles.
I guess I'll add my name.

File: src/client/sound_openal_internal.cpp [hunk 16]
```diff
@@ -0,0 +1,1129 @@
...
+
+static ALenum warn_if_al_error(const char *desc) noexcept
+{
+	ALenum err = alGetError();
+	if (err == AL_NO_ERROR)
+		return err;
+	try {
+		warningstream << "[OpenAL Error] " << desc << ": " << getAlErrorString(err)
+				<< std::endl;
+	} catch (...) { /* ignore */ }
```
[the remark this answers is not in the document]
Comment (Desour) [reply src/client/sound_openal_internal.cpp:66]: Well, it could throw bad_alloc and similar.
But right, this isn't needed. Terminating (in `~RAIIALSoundBuffer`) in such a case is fine.

**Comment by Zughy** [comment]
.md file instead of lua_api.txt file needed

**Comment by rubenwardy** [comment]
Instructions on how to do that without conflicts: https://github.com/minetest/minetest/pull/12449#issuecomment-1510466466

File: doc/lua_api.txt [hunk 17]
```diff
@@ -898,19 +903,114 @@ from the available ones of the following files:
...
+        max_hear_distance = 32,
+        -- Only play for players that are at most this far away when the sound
+        -- starts playing.
+        -- Needs `pos` or `object` to be set.
+        -- `32` is the default.
+    }
+
+Semantics of `time_offset`, with the sound's length in seconds as `max_time`:
+* Nan and inf are illegal.
+* If `-max_time <= time_offset < 0.0`: The behavior is the same as with
```
[the remark this answers is not in the document]
Comment (Desour) [reply doc/lua_api.txt:992]: I agree, it's overly formal.
Changed it. Please read.

**Comment by Desour** [comment]
Resolved comments and rebased.

File: src/client/sound_openal_internal.h (hunk 10 above)
Comment (sfan5) [reply src/client/sound_openal_internal.h]: No, I mean: Do you need to manually implement it or will the compiler do that automatically via `= default` (when using `ALLOW_CLASS_MOVE`)?

**Comment by Zughy** [comment]
@Desour rebase needed

**Comment by Desour** [comment]
Rebased.

File: doc/lua_api.md [hunk 18]
```diff
@@ -903,20 +908,111 @@ from the available ones of the following files:
...
+    object = <an ObjectRef>,
+    -- Attach the sound to an object.
+    -- Can't be used together with `pos`.
+
+    to_player = name,
+    -- Only play for this player.
+    -- Can't be used together with `exclude_player`.
+
+    exclude_player = name,
+    -- Don't play sound for this player.
```
Comment (sfan5) [inline doc/lua_api.md:991]:
```suggestion
    -- Play sound for everyone except this player.
```

File: src/client/client.cpp [hunk 19]
```diff
@@ -714,22 +720,24 @@ void Client::step(float dtime)
 	if(m_removed_sounds_check_timer >= 2.32) {
 		m_removed_sounds_check_timer = 0;
 		// Find removed sounds and clear references to them
+		std::vector<sound_handle_t> removed_cliend_ids = m_sound->pollRemovedSounds();
```
Comment (sfan5) [inline src/client/client.cpp:723]: `removed_client_ids`*

File: src/client/sound_openal_internal.h [hunk 20]
```diff
@@ -0,0 +1,611 @@
...
+/**
+ * Sound file is in a memory buffer.
+ */
+struct SoundDataUnopenBuffer final : ISoundDataUnopen
+{
+	std::string m_buffer;
+
+	explicit SoundDataUnopenBuffer(std::string &&buffer) : m_buffer(std::move(buffer)) {}
+
+	std::shared_ptr<ISoundDataOpen> open(const std::string &sound_name) && override;
```
Comment (sfan5) [inline src/client/sound_openal_internal.h:341]: what does the `&&` mean here?

File: src/script/lua_api/l_client_sound.cpp [hunk 21]
```diff
@@ -0,0 +1,149 @@
...
+	luaL_checktype(L, narg, LUA_TUSERDATA);
+	void *ud = luaL_checkudata(L, narg, className);
+	if (!ud)
+		luaL_typerror(L, narg, className);
+	return *(ClientSoundHandle**)ud; // unbox pointer
+}
+
+int ClientSoundHandle::gc_object(lua_State *L)
+{
+	std::unique_ptr<ClientSoundHandle> o(*(ClientSoundHandle **)(lua_touserdata(L, 1)));
```
Comment (sfan5) [inline src/script/lua_api/l_client_sound.cpp:87]: explicit free might be more obvious here

File: src/client/sound_openal_internal.h (hunk 20 above)
Comment (rubenwardy) [reply src/client/sound_openal_internal.h:341]: It limits this method to r-values only. See https://irc.minetest.net/minetest-dev/2023-04-13#i_6076260
(definitely needs a comment)

Comment (rubenwardy) [reply src/client/sound_openal_internal.h:341]: See https://stackoverflow.com/questions/15320015/what-does-mean-at-the-end-of-a-function-signature-after-the-closing-parenthe

File: doc/lua_api.md (hunk 18 above)
Comment (Desour) [reply doc/lua_api.md:991]: "everyone" would be inaccurate, as there are other things that limit to whom the sound is played, i.e. `max_hear_distance`.

File: src/client/sound_openal_internal.h (hunk 20 above)
Comment (Desour) [reply src/client/sound_openal_internal.h:343]: Added a comment.

File: doc/lua_api.md [hunk 22]
```diff
@@ -903,20 +908,111 @@ from the available ones of the following files:
...
+    fade = 0.0,
+    -- Overwrites the fade specified in `SimpleSoundSpec`.
+
+    start_time = 0.0,
+    -- Start with a time-offset into the sound.
+    -- The behavior is as if the sound was already playing for this many seconds.
+    -- Negative values are relative to the sound's length, so the sound reaches
+    -- its end in `-start_time` seconds.
+    -- It is unspecified what happens if `loop` is false and `start_time` is
+    -- smaller than minus the sound's length.
```
[the remark this answers is not in the document]
Comment (Desour) [reply doc/lua_api.md:973]: The line above says:
>    -- [...], so the sound reaches
    -- its end in `-start_time` seconds.

So, this is an exception to that rule.

**Comment by Desour** [comment]
Thanks for re-review!
Addressed comments. (And did a trivial rebase.)

**Comment by rubenwardy** [comment]
Code changes look good to me now. Not sure how 100% test this, I guess do our best and have it merged for a long time so we can find stuff before the release

**Review by sfan5 — APPROVED** [review]
I suppose the "just merge it and see" approach is best for this

**Review by rubenwardy — APPROVED** [review]

File: src/script/lua_api/l_mainmenu.cpp [hunk 23]
```diff
@@ -99,7 +99,7 @@ int ModApiMainMenu::l_update_formspec(lua_State *L)
 	//read formspec
 	std::string formspec(luaL_checkstring(L, 1));
 
-	if (engine->m_formspecgui) {
+	if (engine->m_formspecgui != 0) {
```
Comment (sfan5) [inline src/script/lua_api/l_mainmenu.cpp]: ?

Comment (Desour) [reply src/script/lua_api/l_mainmenu.cpp]: I just undid the diff. The file is no longer touched by the PR.
