### PR TITLE
Formspec: Make scrollbars scroll while holding down arrow buttons

### LINKED ISSUE #13747: Scrollbar arrow not working with long clicks in servers list
##### Minetest version 5.7.0

Read the title.
It should be that when you press the arrow
image
for a long time, the menu continues to scroll, but this is not the case.

### PR DESCRIPTION
**Pull request by CrazyladMT**
Fixes #13747

> [!NOTE]
> I used GPT-5 to partially assist with these changes.

Originally #16852. I don't even know what I did, but I messed stuff up while trying to rebase it (still 
learning how to use git _properly_). I apologize for any inconvenience or confusion.

This PR includes all the commits from #16852

## To do

This PR is Ready for Review.

## How to test
1. Navigate to the Join Game tab or About tab
2. Hold down the arrow buttons and observe that it scrolls

[Screencast From 2026-02-04 12-12-56.webm](https://github.com/user-attachments/assets/76ca90d9-7c60-435b-b1e7-71eee4b57bea)

### CODE REVIEW

**Comment by SmallJoker** [comment]
Thanks for the adjustments so far. I would just like to quickly highlight that there's one more comment from the previous PR: https://github.com/luanti-org/luanti/pull/16852#discussion_r2738509042

File: src/gui/guiScrollBar.cpp [hunk 1]
```diff
@@ -220,6 +220,30 @@ void GUIScrollBar::OnPostRender(u32 time_ms)
...
+	m_arrow_counter += last_delta_ms;
+
+	// wait for initial delay
+	if (m_arrow_counter < initial_delay)
+		return;
+
+	// after initial delay, repeat every repeat_delay
+	const s32 autoscroll_stepsize = small_step * (up_pressed ? -1 : 1);
+	setPosInterpolated(getTargetPos() + autoscroll_stepsize);
+	m_arrow_counter -= repeat_delay;
```
Comment (j-r) [inline src/gui/guiScrollBar.cpp]: This will break if - e.g. after adding some configuration knobs later - `repeat_delay` becomes greater than `initial_delay`, because then this subtraction will underflow - unless `last_delta_ms` happens to be sufficiently large - and scroll `2^32/repeat_delay` times.

Making `m_arrow_counter` signed seems the most obvious solution, but there are probably some clever tricks to make the comparison with `initial_delay` above work correctly in the face of underflow (adding `repeat_delay` on both sides should work, I guess, or initializing `m_arrow_counter` to `repeat_delay` instead of zero and add `repeat_delay` to `initial_delay` might be a slightly less obfuscated variant).

Comment (SmallJoker) [reply src/gui/guiScrollBar.cpp]: 1. An `assert` would "document" this assumption of the two values' relation.
2. I suspect that you'd notice any misbehaviour pretty quickly (either due to integer underflows, very fast scrolling or similar).
3. Is there any application that scrolls slower than the first interval? That seems unintuitive.

Honestly I do not see any issue in the current implementation.
EDIT: Disclaimer: I did suggest a portion of these changes yesterday in #luanti-dev.

Comment (SmallJoker) [inline src/gui/guiScrollBar.cpp]: Out of the few GUI toolkits I've tested (Qt and GTK3), the first button press is registered too. Afterwards there's either one or two different intervals. This change will make the first button press go through:
```suggestion
	const u32 initial_delay = 200; // ms before repeating starts
	const u32 repeat_delay  = 150; // ms between repeats
	assert(initial_delay > repeat_delay);

    const bool is_initial = (m_arrow_counter == 0);
	// counter is 0, so start counting
	m_arrow_counter += last_delta_ms;

	// wait for initial delay
	if (m_arrow_counter < initial_delay && !is_initial)
		return;

	// after initial delay, repeat every repeat_delay
	const s32 autoscroll_stepsize = small_step * (up_pressed ? -1 : 1);
	setPosInterpolated(getTargetPos() + autoscroll_stepsize);
	if (!is_initial)
	   m_arrow_counter = repeat_delay;
```

**Comment by SmallJoker** [comment]
Note to reviewers: This only works on textareas and scroll containers. My TODO list still contains the point about merging this implementation with CGUIScrollbar.

File: src/gui/guiScrollBar.cpp (hunk 1 above)
Comment (CrazyladMT) [reply src/gui/guiScrollBar.cpp]: I like this. However, did you mean `-=`?

```c++
if (!is_initial)
	m_arrow_counter -= repeat_delay;
```

I noticed that just `=` causes the bug in https://github.com/luanti-org/luanti/pull/16852#discussion_r2738509042

Also another thing I noticed when I applied these changes is, you can no longer just push the arrow button once to scroll once, it instead scrolls like 2 or 3 times, even with initial_delay something high like 1000.

Comment (SmallJoker) [reply src/gui/guiScrollBar.cpp]: Ah yes, of course, the minus should be there.
About the additional scroll input: This can be fixed by removing the `setPosInterpolated` calls from `case EET_GUI_EVENT:` at L74 onwards.

Comment (CrazyladMT) [reply src/gui/guiScrollBar.cpp]: I added an `assert` as @SmallJoker suggested. Is this resolved now?

Comment (j-r) [reply src/gui/guiScrollBar.cpp]: This is fine with me, but the assert is a rather bigger change than making `m_arrow_counter` signed.

**Review by SmallJoker — APPROVED** [review]

**Comment by CrazyladMT** [comment]
Thanks for the help SmallJoker! Glad to have this feature implemented.

**Comment by CrazyladMT** [comment]
Wait this is ready to be merged, right?

**Comment by SmallJoker** [comment]
Yes, although >= 2 approvals are required for non-trivial PRs.
https://docs.luanti.org/for-engine-devs/git-guidelines/#upstream-commit-rules

File: src/gui/guiScrollBar.cpp [hunk 2]
```diff
@@ -71,16 +71,6 @@ bool GUIScrollBar::OnEvent(const SEvent &event)
 			}
 			break;
 		case EET_GUI_EVENT:
```
Comment (appgurueu) [inline src/gui/guiScrollBar.cpp]: this turns from an always `break`ing or `return`ing case into an implicit fallthrough to the mouse input event case. is this correct? i don't think `event.MouseInput` is initialized for non-mouse events; i think that'd be UB?

TL;DR: shouldn't there be a `break` here? (or the `case` removed entirely?)

Comment (CrazyladMT) [reply src/gui/guiScrollBar.cpp]: True, I could just remove the case since I moved this functionality to `OnPostRender`
