### PR TITLE
Fix some textures not being sent correctly to older clients

### LINKED ISSUE #12209: [combine images render incorrectly on older clients on 5.5+ server
### Repro:

- Use a 5.4 or earlier client
- Connect to a 5.5 or later server
- Find something with a texture that starts with `[combine`, such as NodeCore's Living Sponge or Amalgamation

*N.B. do not try to use the public NodeCore servers to repro this because some of them now have a workaround in place for this bug.*

#### Expected:

- Texture appears as expected on a 5.5+ client.  In the NodeCore cases above, it would be a 16x16 animated texture.

#### Observed:

- For the NodeCore cases above, the texture appears as a single solid color (1x1 texture).  The color is the same every time (it's not a "missing texture" auto-generated random color image).

## Cause:

This appears to be a regression introduced in https://github.com/minetest/minetest/commit/b2eb44afc50976dc0954c868977b5829f3ff8a19#diff-1a57c4608538ac1f37a6e032831761b99629522cea1d851ab0e0e455c21c83b8R213-R217.

The code there suggests that the author accounted for textures beginning with `[png` by assuming they would be the only textures beginning with `[`, and forgetting that `[combine` exists.

This workaround should probably at least be extended to look for `[png` specifically and not finding false positives on `[combine`.

### PR DESCRIPTION
**Pull request by Oblomov**
Since b2eb44afc50976dc0954c868977b5829f3ff8a19, a texture defined as
`[combine:16x512:0,0=some_file.png;etc`
will not be sent correctly from a 5.5 server to a 5.4 client due to the
overeager detection of unsupported base modifier `[` introducing a
spurious `blank.png^` before the modifier.

The fix is to actually check for the `[png:` base modifier before
applying the backwards-safe escaping.

In the future this check might need to be extended to include a table of incompatible modifiers, but currently `[png:` is the only one I know about.

Fixes #12209.

### CODE REVIEW

**Comment by SmallJoker** [comment]
Thanks for the quick PR, but this should be a whitelist rather than blacklist to not re-introduce the same bug in the future.

**Comment by Oblomov** [comment]
Hello @SmallJoker, thanks for the review. So if my understanding is correct, from your comment and from the documentation  I can assume that older clients could accept any of the following _without_ base image: `[combine:`, `[inventorycube: `, and `[lowpart;`. I'll rewrite the commit so that if the string begins with any of these then it is passed unchanged, otherwise a `blank.png` is prefixed.

**Comment by Oblomov** [comment]
(Arguably at least the moment the blacklist is more efficient than the whitelist since it needs less checks, but anyway.)

**Comment by Oblomov** [comment]
(Changed the message and PR title as suggested by @sfan5 on IRC)

**Review by SmallJoker — APPROVED** [review]
LGTM

File: src/nodedef.cpp [hunk 1]
```diff
@@ -213,10 +214,24 @@ void TileDef::serialize(std::ostream &os, u16 protocol_version) const
...
-			os << serializeString16("blank.png^" + name);
-		else
+		// Note that modifiers such as [combine can be used as base textures
+		// and are compatible with older clients, so we could specifically single out [png:,
+		// but this would require the list here to be updated whenever a new base modifier
+		// is introduced. Instead, we whitelist the three cases that are supported by the 
+		// older clients and prefix anything else
+		bool pass_through = true;
+
+		// only check prefixes if the name begins with a [
```
Comment (sfan5) [inline src/nodedef.cpp:224]: redundant comment

File: src/nodedef.cpp [hunk 2]
```diff
@@ -213,10 +214,24 @@ void TileDef::serialize(std::ostream &os, u16 protocol_version) const
...
 		// missing textures. "[png" can be used as base texture, but is not known
 		// on older clients. Hence use "blank.png" to avoid this problem.
-		if (!name.empty() && name[0] == '[')
-			os << serializeString16("blank.png^" + name);
-		else
+		// Note that modifiers such as [combine can be used as base textures
+		// and are compatible with older clients, so we could specifically single out [png:,
+		// but this would require the list here to be updated whenever a new base modifier
+		// is introduced. Instead, we whitelist the three cases that are supported by the 
+		// older clients and prefix anything else
```
Comment (sfan5) [inline src/nodedef.cpp:221]: The comment doesn't mention why to whitelist [combine at all and generally I think this could be shorter:
```suggestion
		// Certain modifiers do not work identically when used with a base image, so we
		// need to exclude them from this workaround.
		// Note that "[png" could be singled out instead of these complex conditions,
		// but this was not done for forward-compatibility reasons.
```

File: src/nodedef.cpp [hunk 3]
```diff
@@ -213,10 +214,24 @@ void TileDef::serialize(std::ostream &os, u16 protocol_version) const
...
+		bool pass_through = true;
+
+		// only check prefixes if the name begins with a [
+		if (!name.empty() && name[0] == '[') {
+			pass_through = str_starts_with(name, "[combine:") ||
+				str_starts_with(name, "[inventorycube:") ||
```
Comment (sfan5) [inline src/nodedef.cpp:227]: this has a different syntax
```suggestion
				str_starts_with(name, "[inventorycube{") ||
```

File: src/nodedef.cpp (hunk 1 above)
Comment (Oblomov) [reply src/nodedef.cpp:224]: I actaully expected an objection to the tune that the extra checks for length > 0 and [ as first character are superfluous, and was tempted to extend the comment to include that this is a perf optimization to only do the later (slower) checks if necessary. but I can remove it altogether.

File: src/nodedef.cpp (hunk 3 above)
Comment (Oblomov) [reply src/nodedef.cpp:227]: Ouch. I'll fix it right away.

**Comment by appgurueu** [comment]
What about `(([inventorycube{a.png{b.png{c.png))`?

**Review by sfan5 — APPROVED** [review]

**Comment by sfan5** [comment]
> What about `(([inventorycube{a.png{b.png{c.png))`?

Hopefully nobody does that.

**Comment by Oblomov** [comment]
@appgurueu as things stand now, with or without my patch, the string would pass unchanged which, in this case, would be fine. The actual issue would be with a name such as `(([png:data))`, but this would have crashed older clients regardless of my patch, because the safety wouldn't trigger. I would argue that this is a separate issue, which is definitely worth addressing, but probably separately from this. Could you please open it so we can keep track of it and try to design a solution for it?

**Comment by appgurueu** [comment]
> Could you please open it so we can keep track of it and try to design a solution for it?

#[12214](https://github.com/minetest/minetest/issues/12214)

**Comment by appgurueu** [comment]
Lua-side patch for those who for some reason won't upgrade/patch their 5.5 servers: https://gist.github.com/appgurueu/dea1d1d9d8494e9c00114d36d58c5932
