### PR TITLE
Fix meta tool capabilities regression

### LINKED ISSUE #16561: ItemStackMetaRef.set_tool_capabilities regression
### Luanti version

```true
Luanti 5.13.0 (Linux)
Using LuaJIT 2.1.1753364724
Built by GCC 15.2
Running on Linux/6.16.10 x86_64
BUILD_TYPE=Release
RUN_IN_PLACE=0
USE_CURL=1
USE_GETTEXT=1
USE_SOUND=1
STATIC_SHAREDIR="/usr/share/luanti"
STATIC_LOCALEDIR="/usr/share/locale"
```

### Operating system and version

Linux archnxt 6.16.10-arch1-1 #1 SMP PREEMPT_DYNAMIC Thu, 02 Oct 2025 19:26:36 +0000 x86_64 GNU/Linux

### CPU model

_No response_

### GPU model

_No response_

### Active renderer

_No response_

### Summary

`ItemStackMetaRef.set_tool_capabilities` correctly writes tool_capabilities to the meta, but `ItemStack:get_tool_capabilities` returns tool_capabilities of hand since commit e0378737b7806cdfa227b8c6614f1fbfc71764ff

### Steps to reproduce

Bisection result: e0378737b7806cdfa227b8c6614f1fbfc71764ff is the first bad commit

I don't have a minimum reproduction project, but I used https://content.luanti.org/packages/VeproGames/100_minerals_to_success/ to bisect the bug which occurs here: https://github.com/veprogames/mt-100mts/blob/c5e1525dfc2c30bf5f74f3f19c9ef72ddde8978e/mods/mts_pickcrafting/PickaxeGenerator.lua#L52

dumping the meta shows the correct groupcaps, but item:get_tool_capabilities doesn't

```lua
print(dump(item:get_meta():to_table())) -- includes groupcaps
print(dump(item:get_tool_capabilities())) --doesn't include groupcaps, uses groupcaps of hand
```

### PR DESCRIPTION
**Pull request by cx384**
It does not work if the item has no preexisting tool capabilities in its item definition table.
Fixes #16561

This is the problem in our current code:
https://github.com/luanti-org/luanti/blob/35fda3710d4b5bd1bf5a637064555436d85342ed/src/inventory.h#L111

## To do

Ready for Review.

## How to test
```lua
core.register_chatcommand("t", {
	func = function(name, param)
		--local item = ItemStack("basetools:pick_mese")
		local item = ItemStack("unittests:stick")
		local meta = item:get_meta()
		meta:set_tool_capabilities({
			groupcaps={
				cracky={times={[3]=333}},
			},
		})
		print(dump(item:get_tool_capabilities()))

		return true
	end,
})
```
With this PR `unittests:stick` also works, because it has no preexisting tool capabilities.
In master only `basetools:pick_mese` works.

### CODE REVIEW

**Comment by sfan5** [comment]
Can you add a small unittest to devtest?

**Comment by veprogames** [comment]
Fixes #16561 for me using the same steps of reproduction as described in the issue

**Comment by cx384** [comment]
Added unittest.

File: games/devtest/mods/unittests/metadata.lua [hunk 1]
```diff
@@ -128,3 +128,40 @@ local function test_node_metadata(player, pos)
...
+			cracky={times={123}},
+		},
+	}
+
+	-- has no tool capabilities
+	local item = ItemStack("unittests:stick")
+	local item_meta = item:get_meta()
+	assert(dump(item:get_tool_capabilities()) == dump(ItemStack(""):get_tool_capabilities()))
+	item_meta:set_tool_capabilities(test_caps)
+	assert(get_cracky_cap(item) == 123)
```
Comment (cx384) [inline games/devtest/mods/unittests/metadata.lua:160]: Can't directly compare the tables, because the pushback to Lua adds extra things to the tool capabilities table.

Comment (SmallJoker) [reply games/devtest/mods/unittests/metadata.lua:160]: Please add this as an in-line comment instead.
