### PR TITLE
fix integer overflow in mapgen

### LINKED ISSUE #11620: Signed integer overflow in src/noise.cpp (using valleys mapgen)
```
src/noise.cpp:178:23: runtime error: signed integer overflow: -1248564286 * 1013 cannot be represented in type 'int'
    #0 0x55f17826c3c7 in noise3d(int, int, int, int) (bin/minetest+0x36383c7)
    #1 0x55f17826c8f1 in noise3d_gradient(float, float, float, int, bool) (bin/minetest+0x36388f1)
    #2 0x55f17826d829 in NoisePerlin3D(NoiseParams const*, float, float, float, int) (bin/minetest+0x3639829)
    #3 0x55f177bf99f5 in MapgenValleys::getSpawnLevelAtPoint(irr::core::vector2d<short>) (bin/minetest+0x2fc59f5)
    #4 0x55f1780db3ca in EmergeManager::getSpawnLevelAtPoint(irr::core::vector2d<short>) (bin/minetest+0x34a73ca)
    #5 0x55f178313d49 in Server::findSpawnPos() (bin/minetest+0x36dfd49)
    #6 0x55f17835fbf9 in ServerEnvironment::loadPlayer(RemotePlayer*, bool*, unsigned short, bool) (bin/minetest+0x372bbf9)
    #7 0x55f17831501c in Server::emergePlayer(char const*, unsigned short, unsigned short) (bin/minetest+0x36e101c)
    #8 0x55f1782ee861 in Server::StageTwoClientInit(unsigned short) (bin/minetest+0x36ba861)
    #9 0x55f177ced442 in Server::handleCommand_ClientReady(NetworkPacket*) (bin/minetest+0x30b9442)
    #10 0x55f17831f04c in Server::handleCommand(NetworkPacket*) (bin/minetest+0x36eb04c)
    #11 0x55f1782efb73 in Server::ProcessData(NetworkPacket*) (bin/minetest+0x36bbb73)
    #12 0x55f1782edd9e in Server::Receive() (bin/minetest+0x36b9d9e)
    #13 0x55f1782d74b0 in ServerThread::run() (bin/minetest+0x36a34b0)
    #14 0x55f177eca28a in Thread::threadProc(Thread*) (bin/minetest+0x329628a)
    #15 0x55f177ecc009 in void std::__invoke_impl<void, void (*)(Thread*), Thread*>(std::__invoke_other, void (*&&)(Thread*), Thread*&&) (bin/minetest+0x3298009)
    #16 0x55f177ecb654 in std::__invoke_result<void (*)(Thread*), Thread*>::type std::__invoke<void (*)(Thread*), Thread*>(void (*&&)(Thread*), Thread*&&) (bin/minetest+0x3297654)
    #17 0x55f177ecd629 in decltype (__invoke((_S_declval<0ul>)(), (_S_declval<1ul>)())) std::thread::_Invoker<std::tuple<void (*)(Thread*), Thread*> >::_M_invoke<0ul, 1ul>(std::_Index_tuple<0ul, 1ul>) (bin/minetest+0x3299629)
    #18 0x55f177ecd4c2 in std::thread::_Invoker<std::tuple<void (*)(Thread*), Thread*> >::operator()() (bin/minetest+0x32994c2)
    #19 0x55f177ecd47c in std::thread::_State_impl<std::thread::_Invoker<std::tuple<void (*)(Thread*), Thread*> > >::_M_run() (bin/minetest+0x329947c)
    #20 0x7f7201dd3b2e  (/lib/x86_64-linux-gnu/libstdc++.so.6+0xbbb2e)
    #21 0x7f7202420fa2 in start_thread /build/glibc-vjB4T1/glibc-2.28/nptl/pthread_create.c:486
    #22 0x7f7200f914ce in clone (/lib/x86_64-linux-gnu/libc.so.6+0xf94ce)
```
(found with UBsan)

**To my knowledge UBsan has no false-positives. Therefore, this issue should be assumed to be a remotely-exploitable security vulnerability on the server, until it is somehow proven that this is not the case.**

### LINKED ISSUE #11621: Signed integer overflow in src/mapgen/mapgen.cpp (using valleys mapgen)
```
src/mapgen/mapgen.cpp:241:56: runtime error: signed integer overflow: -1248566279 * 1013 cannot be represented in type 'int'
    #0 0x55f177b6a67d in Mapgen::getBlockSeed2(irr::core::vector3d<short>, int) (bin/minetest+0x2f3667d)
    #1 0x55f177bf76a2 in MapgenValleys::makeChunk(BlockMakeData*) (bin/minetest+0x2fc36a2)
    #2 0x55f1780dfe58 in EmergeThread::run() (bin/minetest+0x34abe58)
    #3 0x55f177eca28a in Thread::threadProc(Thread*) (bin/minetest+0x329628a)
    #4 0x55f177ecc009 in void std::__invoke_impl<void, void (*)(Thread*), Thread*>(std::__invoke_other, void (*&&)(Thread*), Thread*&&) (bin/minetest+0x3298009)
    #5 0x55f177ecb654 in std::__invoke_result<void (*)(Thread*), Thread*>::type std::__invoke<void (*)(Thread*), Thread*>(void (*&&)(Thread*), Thread*&&) (bin/minetest+0x3297654)
    #6 0x55f177ecd629 in decltype (__invoke((_S_declval<0ul>)(), (_S_declval<1ul>)())) std::thread::_Invoker<std::tuple<void (*)(Thread*), Thread*> >::_M_invoke<0ul, 1ul>(std::_Index_tuple<0ul, 1ul>) (bin/minetest+0x3299629)
    #7 0x55f177ecd4c2 in std::thread::_Invoker<std::tuple<void (*)(Thread*), Thread*> >::operator()() (bin/minetest+0x32994c2)
    #8 0x55f177ecd47c in std::thread::_State_impl<std::thread::_Invoker<std::tuple<void (*)(Thread*), Thread*> > >::_M_run() (bin/minetest+0x329947c)
    #9 0x7f7201dd3b2e  (/lib/x86_64-linux-gnu/libstdc++.so.6+0xbbb2e)
    #10 0x7f7202420fa2 in start_thread /build/glibc-vjB4T1/glibc-2.28/nptl/pthread_create.c:486
    #11 0x7f7200f914ce in clone (/lib/x86_64-linux-gnu/libc.so.6+0xf94ce)
```
(found with UBsan)

**To my knowledge UBsan has no false-positives. Therefore, this issue should be assumed to be a remotely-exploitable security vulnerability on the server, until it is somehow proven that this is not the case.**

### PR DESCRIPTION
**Pull request by JosiahWI**
Some calculations involving the magic seed had overflow because the result of an intermediate arithmetic step could not fit in an s32. By making the magic seed unsigned, the other operand in the equation will be cast to unsigned, and possibly other operands or intermediate operands. This will result in unexpected behavior if an operand is negative, which is technically possible, but logically should not happen.

Because this overflow will no longer occur, maps that were generated with this overflow may not be reproducible. The extent of this effect is unknown. Judging from issues #11620 and #11621, this would only be noticed in the valleys mapgen.

- The PR will make the behavior of the affected mapgen equations well-defined and predictable.
- This is done by making the magic seed unsigned, so that the result of an arithmetic operation with the seed will not overflow.
- Fixes #11620; fixes #11621.

## To do

Ready for Review.

## How to test

I do not know how to properly test this. One could generate a map with the valleys mapgen with a given seed, before and after this commit, and compare the result, but that is not a definitive test of whether the maps match exactly or not.

### CODE REVIEW

**Comment by SmallJoker** [comment]
> I do not know how to properly test this.

You could add a test to `test_noise.cpp`. `Mapgen::getBlockSeed2` is a static function which does not need any initialization. Comparing a few positions+seeds would totally suffice. Also `NOISE_MAGIC_SEED` is already tested by the perlin noise tests in the very same file.

**Comment by SmallJoker** [comment]
@JosiahWI In order to make progress quicker on this PR, would you please be so nice to add a few unittests to current master, and include afterwards into this PR? Even if this change seems trivial, it is better to be safe than sorry.

**Comment by JosiahWI** [comment]
I'm a little confused about what you mean by adding unittests to current master. I can add unit tests directly to this branch, if that's helpful. I'm sorry this is going slowly; I'm very busy and writing unittests isn't something I have experience with. I'll take some time this week to work on getting this finished.

**Comment by SmallJoker** [comment]
@JosiahWI Due to the seemingly random function output, it would be necessary to obtain a few  hash values of fixed points and seeds - say `(9000,0,-1337), 123123` and `(-16000,-9000,666), -888888` - using the original function code (master).
Create a new unittest function in a suitable file. The checks within might look like as follows:
```C++
UASSERTEQ(u32, Mapgen::getBlockSeed2(v3s16(9000,0,-1337), 123123),  ?value from original function?);
UASSERTEQ(u32, Mapgen::getBlockSeed2(v3s16(-16000,-9000,66), -888888),  ?value from original function?);
```

**Comment by erlehmann** [comment]
> Judging from issues #11620 and #11621, this would only be noticed in the valleys mapgen.

This is not true – in Mineclonia, with v7 mapgen with seed “pigs”, the overflow will happen near spawn.

Judging from the source code: For the mapgens carpathian, flat, fractal, v5, v7, valleys, changing `getBlockSeed2()` can affect ore and decoration placement.

I agree with @SmallJoker that this needs more testing.

**Comment by JosiahWI** [comment]
I tested all seeds at a given x, y, z location and verified no change in output on my system. I did not commit those tests because it takes almost a minute to make one pass through the possible seed values.

**Comment by erlehmann** [comment]
> I did not commit those tests because it takes almost a minute to make one pass through the possible seed values.

Please show a branch with the code then. Also, what coordinates did you use?

**Comment by JosiahWI** [comment]
I do not have any revision with that code anymore. It was more of a one-time experiment than a unit test. Coordinates were (4096, 4096, 4096).

**Comment by JosiahWI** [comment]
Is this PR waiting on anything?

**Comment by sfan5** [comment]
I would have expected an unittest of `Mapgen::getBlockSeed2` to make sure it still returns the same values as before.

File: src/noise.cpp [hunk 1]
```diff
@@ -166,6 +167,7 @@ float noise2d(int x, int y, s32 seed)
 {
 	unsigned int n = (NOISE_MAGIC_X * x + NOISE_MAGIC_Y * y
 			+ NOISE_MAGIC_SEED * seed) & 0x7fffffff;
+	// Right bit shift on an unsigned type zero-fills.
```
Comment (sfan5) [inline src/noise.cpp:170]: Obviously, I don't think this is worth writing down.

File: src/mapgen/mapgen.cpp [hunk 2]
```diff
@@ -238,7 +238,8 @@ u32 Mapgen::getBlockSeed(v3s16 p, s32 seed)
 
 u32 Mapgen::getBlockSeed2(v3s16 p, s32 seed)
 {
-	u32 n = 1619 * p.X + 31337 * p.Y + 52591 * p.Z + 1013 * seed;
+	// Unsigned magic seed prevents undefined behavior.
```
Comment (sfan5) [inline src/mapgen/mapgen.cpp:241]:
```suggestion
	// Multiply by unsigned number to avoid signed overflow (UB)
```
could also attach an `U` to all constants on that line, wouldn't hurt

File: src/noise.cpp (hunk 1 above)
Comment (JosiahWI) [reply src/noise.cpp:170]: This is a token of my inexperience as a developer. Thank you for pointing this out, I'll fix it ASAP!

**Comment by JosiahWI** [comment]
If the code doesn't match your expectation, sfan, then it probably isn't clean. I will test getBlockSeed2 directly as well.

File: src/unittest/test_noise.cpp [hunk 3]
```diff
@@ -44,15 +50,42 @@ static TestNoise g_test_instance;
...
 	TEST(testNoise3dBulk);
 	TEST(testNoiseInvalidParams);
 }
 
 ////////////////////////////////////////////////////////////////////////////////
 
+void TestNoise::testNoise2dAtOriginWithZeroSeed()
+{
+	float actual{ noise2d(0, 0, 0) };
+	constexpr float expected{ -0.281791f };
```
Comment (SmallJoker) [inline src/unittest/test_noise.cpp:71]: Why curly brackets?
```suggestion
	float actual = noise2d(0, 0, 0);
	constexpr float expected = -0.281791f;
```
same for the other test functions.

**Comment by SmallJoker** [comment]
I ran the newly added tests in current master (without the other changes) and can confirm that they pass.

System: `g++ (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0`

File: src/unittest/test_noise.cpp (hunk 3 above)
Comment (JosiahWI) [reply src/unittest/test_noise.cpp:71]: This was written before my policy to undo uniform initialization for short commits. Uniform initialization is better, especially for floats because it won't allow initializing with a double value (implicit narrowing conversion) and it's consistent for all initialization.

I'm happy to make this change, but in the future I intend to fight for it because there's nothing in the style guide forbidding uniform initialization, and there is a semantic difference.

**Comment by sfan5** [comment]
> If the code doesn't match your expectation, sfan, then it probably isn't clean. I will test getBlockSeed2 directly as well.

It's not that I think something is wrong, but with this it's not enough to trust my intuition and we should have solid tests.

File: src/unittest/test_noise.cpp (hunk 3 above)
Comment (sfan5) [reply src/unittest/test_noise.cpp:71]: I think if the uniform initialization syntax wasn't so ugly you'd see way less resistance :wink:

**Review by SmallJoker — APPROVED** [review]
In addition to the unittests I created a new world and generated chunks with mgvalleys while switching `master` and this PR back and forth. Same outcome. Works.

**Comment by Df458** [comment]
> This is not true – in Mineclonia, with v7 mapgen with seed “pigs”, the overflow will happen near spawn.

Do you happen to have coordinates for this? I tested this PR recently, saw no difference in mapgen between this and master but was also unable to repro any issues with that mapgen / seed / game combination. Ideally I'd like to be able to confirm this before approving.

**Comment by erlehmann** [comment]
> Do you happen to have coordinates for this? I tested this PR recently, saw no difference in mapgen between this and master but was also unable to repro any issues with that mapgen / seed / game combination. Ideally I'd like to be able to confirm this before approving.

To “see” the overflow, you have to compile the respective version of MInetest with UBsan instrumentation `-fsanitize=ubsan`.

If you enter the world with the Mapgen v7 seed `pigs` you should see a bunch of warnings on the terminal about overflows.

The player will spawn not very far away from (0,0,0). There should be a pig spawner near (6,-6,6) with and without this PR.

**Review by Df458 — APPROVED** [review]
Gave this a second look with the relevant flags. There are still a bunch of reported overflows coming from other noise-related functions, but comparing with master this change has fewer than before so I see no reason to block the fix going through.
