### PR TITLE
Client: Fix crash in 'plantlike' nodes with no textures

### LINKED ISSUE #16791: Game crash when a `plantlike` node have empty `tiles` and `*_image`
### Luanti version

```true
Luanti 5.15.0-dev-975699a95 [3.2.0 - Build 27.20.100.8682]
```

### Operating system and version

Windows 10

### CPU model

Inter Core i5-6200

### GPU model

Intel Graphics 520

### Active renderer

3.2.0 opengl3 SDL 2.32.10

### Summary

In any game or mod, if you create a node with `drawtype = "plantlike"` and `tiles = {}` and `inventory_image = ""` and/or `wield_image = ""`, the game will crash when you try to access those nodes in the game's inventory.

EDIT: I know it's not intended for a modder to create a node with those missing parameters, but I also believe that's not the correct behavior for this specific situation. What I believe should happen is that the node should be displayed in the inventory without textures.

### Steps to reproduce

1. Download any game or mod
2. Modify the definitions of any node with the `plantlike` drawtype. Remove the contents of `tiles`, leaving only the empty table, and also remove the contents of `*_image`, leaving only the empty string.
3. Load the game and try accessing the modified node in your inventory.
4. The game will crash the computer and disappear from the screen.

### PR DESCRIPTION
**Pull request by SmallJoker**
This fixes a regression introduced by 293544fb.

Fixes #16791 --> see https://github.com/luanti-org/luanti/issues/16791#issuecomment-3700268011 for defails.

## To do

This PR is Ready for Review.

## How to test

```diff
diff --git a/mods/default/nodes.lua b/mods/default/nodes.lua
index c18fb0a..33c98e9 100644
--- a/mods/default/nodes.lua
+++ b/mods/default/nodes.lua
@@ -720,9 +720,9 @@ minetest.register_node("default:wood", {
 minetest.register_node("default:sapling", {
 	description = S("Apple Tree Sapling"),
 	drawtype = "plantlike",
-	tiles = {"default_sapling.png"},
-	inventory_image = "default_sapling.png",
-	wield_image = "default_sapling.png",
+	tiles = {},
+	inventory_image = "",
+	wield_image = "",
 	paramtype = "light",
 	sunlight_propagates = true,
 	walkable = false,
```

Open up sfinv and search for "sapling" to trigger the crash. Otherwise have a stack in your inventory and try to wield it.

### CODE REVIEW

File: src/client/wieldmesh.cpp [hunk 1]
```diff
@@ -130,9 +130,7 @@ static video::ITexture *extractTexture(const TileDef &def, const TileLayer &laye
 		assert(ret->getType() == video::ETT_2D);
 		return ret;
 	}
-	if (!def.name.empty())
-		return tsrc->getTextureForMesh(def.name);
-	return nullptr;
+	return tsrc->getTextureForMesh(def.name.size() ? def.name : "no_texture.png");
```
Comment (sfan5) [inline src/client/wieldmesh.cpp]:
```suggestion
	return tsrc->getTextureForMesh(def.name.empty() ? "no_texture.png" : def.name);
```
