### PR TITLE
Fix Minetest blaming the wrong mod for errors

### LINKED ISSUE #12236: Stacktraces reported by Minetest blame the wrong mod
##### Minetest version
```
5.5.0 and earlier; presumably 5.6-dev as well
```

##### Summary
See https://github.com/minetest-mods/wielded_light/issues/21: The stacktrace clearly shows `mesecons` is responsible, but the error message blames the `wielded_light` mod.

##### Steps to reproduce

```lua
//lua table.insert(minetest.registered_globalsteps, function() _ = nil + nil end)
```

### PR DESCRIPTION
**Pull request by appgurueu**
Presumably fixes #12236 for the case that mods *insert their callbacks manually into* minetest.registered_\<callbacks\> (often to achieve a particular order of execution). This is the case with mesecons and used to be the case with modlib.

### CODE REVIEW

File: builtin/game/item.lua [hunk 1]
```diff
@@ -676,9 +676,7 @@ function core.node_dig(pos, node, digger)
 	-- Run script hook
 	for _, callback in ipairs(core.registered_on_dignodes) do
 		local origin = core.callback_origins[callback]
-		if origin then
-			core.set_last_run_mod(origin.mod)
-		end
+		core.set_last_run_mod(origin.mod or "??")
```
Comment (sfan5) [inline builtin/game/item.lua:679]: this should be nil, the `"??"` fallback is generated at the point of use

**Comment by sfan5** [comment]
> This is the case with mesecons

Can you link the code where it does this?

File: builtin/game/item.lua (hunk 1 above)
Comment (appgurueu) [reply builtin/game/item.lua:679]: > this should be nil, the `"??"` fallback is generated at the point of use

But does `core.set_last_run_mod` accept `nil`? I believe it requires the argument to be a `string`; only later on does the C++ func fallback to `??` if the `char*` is a `nullptr`.

**Comment by appgurueu** [comment]
> > This is the case with mesecons
> 
> Can you link the code where it does this?

Sure. [Here it is.](https://github.com/minetest-mods/mesecons/blob/f4070d3e64652837e4c79967f29bf67f0ac559f4/mesecons/actionqueue.lua#L128-L129).

File: builtin/game/item.lua (hunk 1 above)
Comment (sfan5) [reply builtin/game/item.lua:679]: Indeed it only takes strings, I suggest `""` then plus this change:
```diff
diff --git a/src/script/common/c_internal.cpp b/src/script/common/c_internal.cpp
index df82dba14..827cce590 100644
--- a/src/script/common/c_internal.cpp
+++ b/src/script/common/c_internal.cpp
@@ -76,10 +76,10 @@ void script_error(lua_State *L, int pcall_result, const char *mod, const char *f
                err_type = "Unknown";
        }
 
-       if (!mod)
+       if (!mod || !*mod)
                mod = "??";
 
-       if (!fxn)
+       if (!fxn || !*fxn)
                fxn = "??";
 
        const char *err_descr = lua_tostring(L, -1);
```

Comment (appgurueu) [reply builtin/game/item.lua:679]: Looks like `"??"` is set as a default in numerous places:

```
$ grep -r '"??"'
builtin/profiler/instrumentation.lua:	def.mod = def.mod or get_current_modname() or "??"
builtin/common/chatcommands.lua:	def.mod_origin = core.get_current_modname() or "??"
builtin/client/register.lua:			mod = core.get_current_modname() or "??",
builtin/client/register.lua:			name = getinfo(1, "n").name or "??"
builtin/game/item.lua:		core.set_last_run_mod(origin.mod or "??")
builtin/game/register.lua:	spec.mod_origin = core.get_current_modname() or "??"
builtin/game/register.lua:	spec.mod_origin = core.get_current_modname() or "??"
builtin/game/register.lua:	prototype.mod_origin = core.get_current_modname() or "??"
builtin/game/register.lua:	itemdef.mod_origin = core.get_current_modname() or "??"
builtin/game/register.lua:		core.set_last_run_mod(origin.mod or "??")
builtin/game/register.lua:			mod = core.get_current_modname() or "??",
builtin/game/register.lua:			name = debug.getinfo(1, "n").name or "??"
builtin/game/register.lua:			mod = core.get_current_modname() or "??",
builtin/game/register.lua:			name = debug.getinfo(1, "n").name or "??"
builtin/game/register.lua:		mod = core.get_current_modname() or "??",
builtin/game/register.lua:		name = debug.getinfo(1, "n").name or "??"
builtin/game/detached_inventory.lua:	stuff.mod_origin = core.get_current_modname() or "??"
src/script/common/c_internal.cpp:		mod = "??";
src/script/common/c_internal.cpp:		fxn = "??";
src/script/cpp_api/s_base.cpp:	m_last_run_mod = origin ? origin : "??";
doc/lua_api.txt:        -- if it can not find a source, returns "??"
```

File: builtin/client/register.lua [hunk 2]
```diff
@@ -1,5 +1,8 @@
-
-core.callback_origins = {}
+core.callback_origins = setmetatable({}, {
+	__index = function()
+		return {mod = "", name = ""}
```
Comment (appgurueu) [inline builtin/client/register.lua:3]: Not really necessary as there seems to be no `if origin then ... end` in the client code, but a decent default for it to be future-proof.

File: builtin/game/register.lua [hunk 3]
```diff
@@ -404,7 +404,11 @@ function core.override_item(name, redefinition)
 end
 
 
-core.callback_origins = {}
+core.callback_origins = setmetatable({}, {
+	__index = function()
+		return {mod = "", name = ""}
```
Comment (appgurueu) [inline builtin/game/register.lua:409]: Should I turn this into an upvalue in order to not create a garbage object every time this is called?

Comment (sfan5) [reply builtin/game/register.lua]: If we're worrying about the details of a feature that's not even needed may be best to get rid of it for simplicity's sake too :wink:

**Review by sfan5 — APPROVED** [review]
LGTM

**Review by rubenwardy — APPROVED** [review]
