### PR TITLE
Extend bone override capabilities

### LINKED ISSUE #12294: No way to unset bone.
(I accidentally closed this issue last time don't worry about it lol)

This is not only a feature a request, but to some extent a bug report.

When you use :set_bone_position() it is impossible to unset, reset, or otherwise return it to it's original state!
this means, (for example) if you want to make an arm face a certain direction (without permanently disabling animations in that bone) that **you need to: change the player model to a model with BONES WITH SEPERATE NAMES and then set it back when you're done**, there is no way around this, I've faced this problem time and time again, resetting the model does nothing, it is painful.

The clear solution is to add a equivalent objref:unset_bone_position() function, this way you can return the bone to its original state where it is animated according to the model.

There's also a few other ways to go about this;
have returning nil return it to its original state instead of adding a new function
_**OR**_
make an option to have it be an offset type thing like:
objref:set_bone_position([bone, position, rotation], offset)
where "offset" would be a bool indicating whether it removes the animation entirely, this would serve multiple purposes
it would
A: allow for more complex animations to be done with a bone (this is a massive improvement and would open up possibilities)
B: obviously allow it to be reverted back by objref:set_bone_position("arm_right", nil, nil, true) or something of the sort

While the addition to the set_bone_position by creating an option for it to be an offset is a great option, it is not exactly necessary at the moment, and may take more time to implement (though I'm not a core dev so I don't know) if minetest and its development was perfect, I'd choose that option, however for now- **I think it can (hopefully) be a later addition to the API and can wait. What's more important is that there's actually a way to unset bone positions**, as this is a absolutely frustrating issue, and needs to be improved desperately if the modding community is to continue innovating

### LINKED ISSUE #13688: Objects rotation is in radians but bones rotation is in degrees
##### Minetest version
```
pick your fighter
```

##### Summary
It took me 20 minutes to understand what in my code was wrong because I expected bones to use radians as objects do. Not even the docs are mentioning this.  

The soft approach is to mention it in the docs. But I honestly don't understand why we're using two different unit systems for entities. It's very confusing, it's been two days I've been working with entities and it's a pile of problems one after the other, c'mon...

##### Steps to reproduce
With Minetest Game
```lua
minetest.register_on_joinplayer(function(player)
  minetest.after(1, function()
    player:set_bone_position("Head", nil, vector.new(0, 180, 0))
    local _, b_rot = player:get_bone_position("Head")
    minetest.chat_send_all(dump(player:get_look_dir())) -- this is in radians
    minetest.chat_send_all(dump(b_rot))                 -- this is in degrees (if you put `math.pi` instead of 180 the head barely rotates, as it's only 3.14 degrees)
  end)
end
```

### PR DESCRIPTION
**Pull request by appgurueu**
Revival of #10704 - rebased, loads of bugs fixed, code cleaned up. Closes #12294. Fixes the bone rotation interpolation aspect of #10572. Closes #13688

Implements bone overrides supporting *position, rotation and scale*, all of which can be *relative and/or interpolated*.

Ready for review. Extensive testing needed. 

# How to test

1. Use mods like character_anim or playeranim to verify that the old API still works.

2. Use the new, documented API. Example based on @LoneWolfHT's headanim:
    1. Use the `/headanim` chatcommand to toggle the override.

Screenshot 2022-05-30 14-49-23

**`mods/headlessanim/init.lua`:**
```lua
local lastdir = {}

minetest.register_globalstep(function(dtime)
	for _, player in pairs(minetest.get_connected_players()) do
		local pname = player:get_player_name()
		local ldeg = -math.deg(player:get_look_vertical())
		if lastdir[pname] == nil then
			lastdir[pname] = 0
		end
		if lastdir[pname] then
			if math.abs(lastdir[pname] - ldeg) > 4 then
				lastdir[pname] = ldeg
				player:set_bone_override("Head", {rotation = {vector = {x = ldeg, y = 0, z = 0}, absolute = true },
				scale = {vector = { x = 1.5, y = 1.5, z = 1.5 }}})
			end
		end
	end
end)

minetest.register_on_leaveplayer(function(player)
	lastdir[player:get_player_name()] = nil
end)

minetest.register_chatcommand("headanim", {
	func = function(name)
		local player = assert(minetest.get_player_by_name(name))
		if lastdir[name] then
			lastdir[name] = false -- don't update Head in globalstep
			player:set_bone_override"Head" -- clear override
		else
			lastdir[name] = 0
		end
	end
})
```

### CODE REVIEW

File: src/server/unit_sao.cpp [hunk 1]
```diff
@@ -75,20 +75,22 @@ void UnitSAO::setAnimationSpeed(float frame_speed)
 	m_animation_speed_sent = false;
 }
 
-void UnitSAO::setBonePosition(const std::string &bone, v3f position, v3f rotation)
+void UnitSAO::setBoneOverride(const std::string &bone, BonePositionOverride *override)
 {
 	// store these so they can be updated to clients
-	m_bone_position[bone] = core::vector2d<v3f>(position, rotation);
-	m_bone_position_sent = false;
+	m_bone_override[bone] = override;
```
Comment (appgurueu) [inline src/server/unit_sao.cpp:81]: Is this a memleak - should I delete the previous override?

Comment (JosiahWI) [reply src/server/unit_sao.cpp:81]: If the previous override won't be used again then yes.

Comment (JosiahWI) [reply src/server/unit_sao.cpp:81]: If it's kept anywhere else in the code set it to nullptr.

File: doc/lua_api.txt [hunk 2]
```diff
@@ -6727,10 +6727,29 @@ object you are working with still exists.
     object.
 * `set_detach()`
 * `set_bone_position([bone, position, rotation])`
-    * `bone`: string. Default is `""`, the root bone
-    * `position`: `{x=num, y=num, z=num}`, relative, `default {x=0, y=0, z=0}`
-    * `rotation`: `{x=num, y=num, z=num}`, default `{x=0, y=0, z=0}`
+	* Shorthand for `set_bone_override(bone, {position = {x = position.x, y = position.y, z = position.z, absolute = true}, rotation = {x = rotation.x, y = rotation.y, z = rotation.z, absolute = true}})`
```
Comment (SmallJoker) [inline doc/lua_api.txt:6730]:
```suggestion
	* Shorthand for `set_bone_override(bone, {position = ..., rotation = ...})` using absolute values.
```

File: doc/lua_api.txt [hunk 3]
```diff
@@ -6727,10 +6727,29 @@ object you are working with still exists.
...
+	* Supports older servers & clients (< 5.6)
+	* **Deprecated**, use `set_bone_override` instead
 * `get_bone_position(bone)`: returns position and rotation of the bone
+	* Shorthand for `get_bone_override(bone).position.vector, get_bone_override(bone).rotation.vector`
+	* **Deprecated**, use `get_bone_override` instead
+* `set_bone_override(bone, override)`
+    * `bone`: string
+    * `override`: `{ position = property, rotation = property, scale = property }` or `nil`
```
Comment (SmallJoker) [inline doc/lua_api.txt:6738]: +4 spaces for each indent, especially for the `absolute` part above to easier distinguish the sub-lists.

File: src/activeobject.h [hunk 4]
```diff
@@ -72,6 +73,33 @@ enum ActiveObjectCommand {
 	AO_CMD_SET_ANIMATION_SPEED
 };
 
+struct BoneOverride
+{
+	struct PositionProperty
+	{
+		v3f previous{};
```
Comment (SmallJoker) [inline src/activeobject.h:80]: Initializer list is not necessary for classes with default constructors, i.e. `v3*` and `core::quaternion`.

File: src/client/content_cao.cpp [hunk 5]
```diff
@@ -1528,19 +1529,52 @@ void GenericCAO::updateAnimationSpeed()
...
+	for (auto &it : m_bone_override) {
 		std::string bone_name = it.first;
 		scene::IBoneSceneNode* bone = m_animated_meshnode->getJointNode(bone_name.c_str());
-		if (bone) {
-			bone->setPosition(it.second.X);
-			bone->setRotation(it.second.Y);
+		if (!bone)
+			continue;
+
+		BoneOverride *override = it.second;
```
Comment (SmallJoker) [inline src/client/content_cao.cpp:1548]:
```suggestion
		const BoneOverride *spec = it.second;
```
1. To avoid the `override` keyword for syntax highlighting reasons
2. Const to keep the code reasonable and more self-explanatory.

File: src/client/content_cao.cpp [hunk 6]
```diff
@@ -1832,10 +1866,42 @@ void GenericCAO::processMessage(const std::string &data)
...
-		v3f position = readV3F32(is);
-		v3f rotation = readV3F32(is);
-		m_bone_position[bone] = core::vector2d<v3f>(position, rotation);
-
+		BoneOverride *previous = m_bone_override[bone];
+		BoneOverride *override = new BoneOverride();
+		override->position.vector = readV3F32(is);
+		override->rotation.next = core::quaternion(readV3F32(is) * core::DEGTORAD);
+		if (is.eof()) {
+			override->position.absolute = true;
```
Comment (SmallJoker) [inline src/client/content_cao.cpp:1874]: Please include a note for the current protocol version. Even though this does not need a bump, a rough timestamp for this legacy code would be helpful.

Also needs an entry in `networkprotocol.h`.

File: src/client/content_cao.cpp [hunk 7]
```diff
@@ -1832,10 +1866,42 @@ void GenericCAO::processMessage(const std::string &data)
...
+				} else {
+					// disable interpolation
+					override->position.interpolation_duration = 0.0f;
+					override->rotation.interpolation_duration = 0.0f;
+					override->scale.interpolation_duration = 0.0f;
+				}
+				m_bone_override[bone] = override;
+			}
+		}
+		if (previous) delete previous;
```
Comment (SmallJoker) [inline src/client/content_cao.cpp:1904]: This is dangerous. Map assignments and object freeing should happen in the same scope to avoid dangling pointers caused by logic errors.

Generally, I would prefer to not use pointers in this case. A sequential memcpy on this struct is quick to execute during runtime.

File: src/client/content_cao.h [hunk 8]
```diff
@@ -26,6 +26,7 @@ with this program; if not, write to the Free Software Foundation, Inc.,
 #include "itemgroup.h"
 #include "constants.h"
 #include <cassert>
+#include "server/serveractiveobject.h"
```
Comment (SmallJoker) [inline src/client/content_cao.h:29]: Unnecessary include. This slows down the compile process.

```C++
class BoneOverride;
```

(a few lines below, though)

File: src/script/lua_api/l_object.cpp [hunk 9]
```diff
@@ -526,11 +527,19 @@ int ObjectRef::l_set_bone_position(lua_State *L)
...
 
-	std::string bone = readParam<std::string>(L, 2, "");
-	v3f position = readParam<v3f>(L, 3, v3f(0, 0, 0));
-	v3f rotation = readParam<v3f>(L, 4, v3f(0, 0, 0));
-
-	sao->setBonePosition(bone, position, rotation);
+	std::string bone;
+	if (!lua_isnil(L, 2))
+		bone = readParam<std::string>(L, 2);
+	BoneOverride *override = new BoneOverride();
```
Comment (SmallJoker) [inline src/script/lua_api/l_object.cpp:533]: Unfortunate variable name here as well.

File: src/script/lua_api/l_object.cpp [hunk 10]
```diff
@@ -526,11 +527,19 @@ int ObjectRef::l_set_bone_position(lua_State *L)
...
+	if (!lua_isnil(L, 3))
+		override->position.vector = check_v3f(L, 3);
+	if (!lua_isnil(L, 4))
+		override->rotation.next = core::quaternion(check_v3f(L, 4) * core::DEGTORAD);
+	override->position.absolute = true;
+	override->rotation.absolute = true;
+	override->position.interpolation_duration = 0.0f;
+	override->position.interpolation_duration = 0.0f;
```
Comment (SmallJoker) [inline src/script/lua_api/l_object.cpp:541]: These could be specified as defaults in the `BoneOverride` struct directly.

File: src/script/lua_api/l_object.cpp [hunk 11]
```diff
@@ -542,16 +551,128 @@ int ObjectRef::l_get_bone_position(lua_State *L)
...
+	NO_MAP_LOCK_REQUIRED;
+	ObjectRef *ref = checkobject(L, 1);
+	ServerActiveObject *sao = getobject(ref);
+	if (sao == NULL)
+		return 0;
+	std::string bone;
+	if (!lua_isnil(L, 2))
+		bone = readParam<std::string>(L, 2);
+	BoneOverride *override = new BoneOverride();
+	if (lua_isnil(L, 3) || lua_isnone(L, 3)) {
```
Comment (SmallJoker) [inline src/script/lua_api/l_object.cpp:575]:
```suggestion
	if (lua_isnoneornil(L, 3)) {
```

More new lines to separate the sections would improve the code readability too.

File: src/script/lua_api/l_object.cpp [hunk 12]
```diff
@@ -542,16 +551,128 @@ int ObjectRef::l_get_bone_position(lua_State *L)
...
+		sao->setBoneOverride(bone, override);
+		return 0;
+	}
+	lua_getfield(L, 3, "position");
+	if (!lua_isnil(L, -1)) {
+		override->position.vector = check_v3f(L, 4);
```
Comment (SmallJoker) [inline src/script/lua_api/l_object.cpp:581]: Invalid index here and for absolute.

Suggestion: Replace the common `"absolute"` and `"interpolation_duration"` code with a Lambda to reduce redundancy and inconsistency.

File: src/script/lua_api/l_object.cpp [hunk 13]
```diff
@@ -542,16 +551,128 @@ int ObjectRef::l_get_bone_position(lua_State *L)
...
+{
+	lua_newtable(L);
+	lua_newtable(L);
+	push_v3f(L, override->position.vector);
+	lua_setfield(L, -2, "vector");
+	lua_pushnumber(L, override->position.interpolation_duration);
+	lua_setfield(L, -2, "interpolation_duration");
+	lua_pushboolean(L, override->position.absolute);
+	lua_setfield(L, -2, "absolute");
+	lua_setfield(L, -2, "position");
```
Comment (SmallJoker) [inline src/script/lua_api/l_object.cpp:626]: Suggestion: Move to a Lambda, like above.

Also add new lines to separate each section (i.e. table).

File: src/server/serveractiveobject.h [hunk 14]
```diff
@@ -169,14 +170,16 @@ class ServerActiveObject : public ActiveObject
...
 	{}
-	virtual void setBonePosition(const std::string &bone, v3f position, v3f rotation)
-	{}
-	virtual void getBonePosition(const std::string &bone, v3f *position, v3f *lotation)
+	virtual void setBoneOverride(const std::string &bone, BoneOverride *override)
 	{}
+	virtual BoneOverride *getBoneOverride(const std::string &bone)
+	{ return 0; }
+	virtual const std::unordered_map<std::string, BoneOverride*> &getBoneOverrides() const
+	{ static std::unordered_map<std::string, BoneOverride*> rv; return rv; }
```
Comment (SmallJoker) [inline src/server/serveractiveobject.h:178]: Idea: Shorten this map type using a `typedef` somewhere in `activeobject.h`.

File: src/server/unit_sao.cpp [hunk 15]
```diff
@@ -273,15 +277,26 @@ std::string UnitSAO::generateUpdateAttachmentCommand() const
...
+	override->rotation.next.toEuler(euler_rot);
+	writeV3F32(os, euler_rot * core::RADTODEG);
+	writeV3F32(os, override->scale.vector);
+	writeF32(os, override->position.interpolation_duration);
+	writeF32(os, override->rotation.interpolation_duration);
+	writeF32(os, override->scale.interpolation_duration);
+	// clang-format off
+	writeU8(os, override->position.absolute * 1
+	          + override->rotation.absolute * 2
+	          + override->scale.absolute    * 4);
```
Comment (SmallJoker) [inline src/server/unit_sao.cpp:298]:
```suggestion
	writeU8(os, (override->position.absolute & 1) << 0
	          | (override->rotation.absolute & 1) << 1
	          | (override->scale.absolute & 1) << 2);
```
In the same style as `PlayerControl`. This 1. ensures proper values and 2. Obvious bit positions.

File: src/server/unit_sao.h [hunk 16]
```diff
@@ -57,8 +57,10 @@ class UnitSAO : public ServerActiveObject
 	void setAnimationSpeed(float frame_speed);
 
 	// Bone position
-	void setBonePosition(const std::string &bone, v3f position, v3f rotation);
-	void getBonePosition(const std::string &bone, v3f *position, v3f *rotation);
+	void setBoneOverride(const std::string &bone, BoneOverride *override);
+	BoneOverride *getBoneOverride(const std::string &bone);
+	const std::unordered_map<std::string, BoneOverride*> &
+	getBoneOverrides() const;
```
Comment (SmallJoker) [inline src/server/unit_sao.h:63]:
```suggestion
	const std::unordered_map<std::string, BoneOverride*> &getBoneOverrides() const;
```

**Review by SmallJoker — COMMENTED** [review]
The idea is good, but the code generally needs more comments and better pointer handling.

File: src/script/lua_api/l_object.cpp (hunk 10 above)
Comment (appgurueu) [reply src/script/lua_api/l_object.cpp:541]: They should be. This code should be unneeded.

Comment (appgurueu) [reply src/script/lua_api/l_object.cpp:541]: After giving this a second thought, I have come to the following conclusions:

1. Setting `absolute` to `true` is reasonable as `true` would be an unreasonable default for the struct and this is just for legacy support;
2. The `interpolation_duration` already is zero by default. These lines can be safely removed.

File: src/client/content_cao.cpp (hunk 7 above)
Comment (appgurueu) [reply src/client/content_cao.cpp:1905]: And indeed the `if` branch is lacking a map assignment! Will use a boolean var to keep both in the same scope.

File: src/script/lua_api/l_object.cpp [hunk 17]
```diff
@@ -542,16 +549,121 @@ int ObjectRef::l_get_bone_position(lua_State *L)
...
-	return 2;
+	auto read_prop_attrs = [L](auto prop) {
+		lua_getfield(L, -1, "absolute");
+		prop.absolute = lua_toboolean(L, -1);
+		lua_pop(L, 1);
+		lua_getfield(L, -1, "interpolation_duration");
+		if (lua_isnumber(L, -1))
+			prop.interpolation_duration = lua_tonumber(L, -1);
+		lua_pop(L, 1);
+		return prop;
```
Comment (SmallJoker) [inline src/script/lua_api/l_object.cpp:586]: Is `auto &prop` possible? If so, that would eliminate the assignments below.

**Comment by appgurueu** [comment]
Thanks for the thorough review @SmallJoker! Everything should be addressed now, making the code noticeably cleaner and leading me to squish some bugs along the way!

File: src/network/networkprotocol.h [hunk 18]
```diff
@@ -207,7 +207,7 @@ with this program; if not, write to the Free Software Foundation, Inc.,
 		Minimap modes
 	PROTOCOL VERSION 40:
 		TOCLIENT_MEDIA_PUSH changed, TOSERVER_HAVE_MEDIA added
-		AO_CMD_SET_BONE_POSITION extended
+		Added new particlespawner parameters (5.6.0)
```
Comment (sfan5) [inline src/network/networkprotocol.h:210]: It looks like you merged this incorrectly, the bone position comment is now gone

Comment (appgurueu) [reply src/network/networkprotocol.h:210]: I wanted it to be gone since there is no protocol bump for it (or there will be a protocol bump for 5.7 anyways), should I re-add it?

File: doc/lua_api.txt [hunk 19]
```diff
@@ -6909,10 +6909,29 @@ child will follow movement and rotation of that bone.
...
+          setting a property to `nil` is equivalent to no override on that property
+        * `x`, `y` and `z` are in blocksize for position and scale (times ten), and in degrees for rotation
+        * `absolute`: If set to `false`, the override will be relative to the animated property:
+            * Transposition in the case of `position`;
+            * Composition in the case of `rotation`;
+            * Multiplication in the case of `scale`
+        * `interpolation_duration`: Time it takes (on the client, in seconds) to interpolate between the old & new value
+    * Not supported by older servers (< 5.6);
+      older clients (< 5.6) support only position & rotation
+      and will ignore interpolation & relativity entirely
```
[the remark this answers is not in the document]
Comment (appgurueu) [reply doc/lua_api.txt]: The ideas is that if modders use relative or interpolated values, they require their clients to be 5.7+. Other options include:

* Don't send update bone position commands to clients if they don't fully support them (probably the best option; what about interpolation though?)
* Add a new command
* Create a redundant bone position / bone override system to allow sending different values to older clients; this would be best for compat, but worst for the codebase and the effort required

Client visuals will not match what the server expects the client to see either way however, but not overriding the bones at all is probably more graceful than improperly overriding them.

File: src/script/lua_api/l_object.cpp [hunk 20]
```diff
@@ -544,14 +551,122 @@ int ObjectRef::l_get_bone_position(lua_State *L)
...
+	if (sao == NULL)
+		return 0;
 
-	push_v3f(L, position);
-	push_v3f(L, rotation);
-	return 2;
+	std::string bone;
+	if (!lua_isnil(L, 2))
+		bone = readParam<std::string>(L, 2);
+	BoneOverride *props = new BoneOverride();
```
Comment (SmallJoker) [inline src/script/lua_api/l_object.cpp:574]: When an error is thrown in one of the checks below (`check_v3f`), this pointer is not freed. Same issue for `l_set_bone_position`

Suggestion: Use `std::unique_ptr` + `.release()`

File: src/server/unit_sao.cpp [hunk 21]
```diff
@@ -75,20 +75,19 @@ void UnitSAO::setAnimationSpeed(float frame_speed)
...
 
-void UnitSAO::getBonePosition(const std::string &bone, v3f *position, v3f *rotation)
+BoneOverride *UnitSAO::getBoneOverride(const std::string &bone)
 {
-	auto it = m_bone_position.find(bone);
-	if (it != m_bone_position.end()) {
-		*position = it->second.X;
-		*rotation = it->second.Y;
-	}
+	return m_bone_override[bone];
```
Comment (SmallJoker) [inline src/server/unit_sao.cpp:90]:
```suggestion
	auto it = m_bone_override.find(bone);
	return it != m_bone_override.end() ? it->second : nullptr;
```
.. because indexing creates a new entry which then shows up in `player:get_bone_overrides()`.

**Review by SmallJoker — COMMENTED** [review]
Sorry for the separate reviews. Taking a pause did however help to find a few more, although rather minor issues.

File: src/server/unit_sao.cpp [hunk 22]
```diff
@@ -273,15 +272,26 @@ std::string UnitSAO::generateUpdateAttachmentCommand() const
...
 	// command
 	writeU8(os, AO_CMD_SET_BONE_POSITION);
 	// parameters
 	os << serializeString16(bone);
-	writeV3F32(os, position);
-	writeV3F32(os, rotation);
+	writeV3F32(os, props->position.vector);
+	v3f euler_rot;
+	props->rotation.next.toEuler(euler_rot);
+	writeV3F32(os, euler_rot * core::RADTODEG);
```
[the remark this answers is not in the document]
Comment (appgurueu) [reply src/server/unit_sao.cpp:285]: Also compatibility with the old code

File: src/script/lua_api/l_object.cpp (hunk 20 above)
Comment (appgurueu) [reply src/script/lua_api/l_object.cpp]: Like this? https://github.com/minetest/minetest/pull/12388/commits/931f1b53b25d15c7a0a0739b0df7ca39816c1630

Comment (SmallJoker) [reply src/script/lua_api/l_object.cpp]: `props.get()->` can be shortened to `props->` because `std::unique_ptr` overloads the indirection operator.

Comment (appgurueu) [reply src/script/lua_api/l_object.cpp]: > `props.get()->` can be shortened to `props->` because `std::unique_ptr` overloads the indirection operator. EDIT: otherwise fine.

I was suspecting something like that. Thanks.

File: doc/lua_api.txt [hunk 23]
```diff
@@ -6915,10 +6915,28 @@ child will follow movement and rotation of that bone.
     object.
 * `set_detach()`
 * `set_bone_position([bone, position, rotation])`
-    * `bone`: string. Default is `""`, the root bone
-    * `position`: `{x=num, y=num, z=num}`, relative, `default {x=0, y=0, z=0}`
-    * `rotation`: `{x=num, y=num, z=num}`, default `{x=0, y=0, z=0}`
+	* Shorthand for `set_bone_override(bone, {position = ..., rotation = ...})` using absolute values.
+	* Supports older servers & clients (< 5.6)
+	* **Deprecated**; use `set_bone_override` instead
 * `get_bone_position(bone)`: returns position and rotation of the bone
```
Comment (sfan5) [inline doc/lua_api.txt:6921]:
```suggestion
* `get_bone_position(bone)`: returns the previously set position and rotation of the bone
```

File: doc/lua_api.txt [hunk 24]
```diff
@@ -6915,10 +6915,28 @@ child will follow movement and rotation of that bone.
...
+        * `absolute`: If set to `false`, the override will be relative to the animated property:
+            * Transposition in the case of `position`;
+            * Composition in the case of `rotation`;
+            * Multiplication in the case of `scale`
+        * `interpolation_duration`: Time it takes (on the client, in seconds) to interpolate between the old & new value
+    * `override = nil` (including omission) is shorthand for `override = {}` which clears the override
+    * Compatibility note: Clients prior to 5.7.0 only support absolute position and rotation.
+      All values are treated as absolute and are set immediately (no interpolation).
+* `get_bone_override(bone)`: returns `override` in the above format
+* `get_bone_overrides()`: returns bone overrides as table `{[bonename] = override, ...}`
```
Comment (sfan5) [inline doc/lua_api.txt:6939]:
```suggestion
* `get_bone_overrides()`: returns all bone overrides as table `{[bonename] = override, ...}`
```

File: doc/lua_api.txt [hunk 25]
```diff
@@ -6915,10 +6915,28 @@ child will follow movement and rotation of that bone.
...
+	* Shorthand for `set_bone_override(bone, {position = ..., rotation = ...})` using absolute values.
+	* Supports older servers & clients (< 5.6)
+	* **Deprecated**; use `set_bone_override` instead
 * `get_bone_position(bone)`: returns position and rotation of the bone
+	* Shorthand for `get_bone_override(bone).position.vector, get_bone_override(bone).rotation.vector`
+	* **Deprecated**, use `get_bone_override` instead
+* `set_bone_override(bone, override)`
+    * `bone`: string
+    * `override`: `{ position = property, rotation = property, scale = property }` or `nil`
+        * `property`: `{ x = ..., y = ..., z = ..., interpolation_duration = 0, absolute = false}` or `nil`;
```
Comment (sfan5) [inline doc/lua_api.txt:6927]: I think something like `interpolate_dur` or just `interpolate` would be better

--

Also mixing tables too much is annoying.
Any reason not to use `{ pos = {...}, interpolate = 0, absolute = false }`?

Edit: This is double bad because the engine will return a vector with a metatable set and everything but also contains foreign fields. Definitely needs changing.

File: doc/lua_api.txt [hunk 26]
```diff
@@ -6915,10 +6915,28 @@ child will follow movement and rotation of that bone.
...
+            * `x`, `y` and `z` are in blocksize for position and scale (times ten), and in degrees for rotation
```
Comment (sfan5) [inline doc/lua_api.txt:6928]:
```suggestion
            * `x`, `y` and `z` are in same coordinate system as the model, and in degrees for rotation
```

File: src/activeobject.h [hunk 27]
```diff
@@ -72,6 +74,35 @@ enum ActiveObjectCommand {
...
+	{
+		v3f previous;
+		v3f vector{1.0f, 1.0f, 1.0f};
+		bool absolute = false;
+		f32 interpolation_duration = 0;
+	} scale;
+	f32 dtime_passed = 0;
+};
+
+typedef std::unordered_map<std::string, BoneOverride*> BoneOverrideMap;
```
Comment (sfan5) [inline src/activeobject.h:103]: no reason to use pointers here

File: src/activeobject.h [hunk 28]
```diff
@@ -72,6 +74,35 @@ enum ActiveObjectCommand {
...
+		f32 interpolation_duration = 0;
+	} rotation;
+	struct ScaleProperty
+	{
+		v3f previous;
+		v3f vector{1.0f, 1.0f, 1.0f};
+		bool absolute = false;
+		f32 interpolation_duration = 0;
+	} scale;
+	f32 dtime_passed = 0;
```
Comment (sfan5) [inline src/activeobject.h:100]: `interpolate_timer` would be more apt

File: src/client/content_cao.cpp [hunk 29]
```diff
@@ -1514,18 +1515,60 @@ void GenericCAO::updateAnimationSpeed()
...
+		}
+		// Scale
+		{
+			f32 progress = props->dtime_passed / props->scale.interpolation_duration;
+			if (progress > 1.0f || props->scale.interpolation_duration == 0.0f)
+				progress = 1.0f;
+			v3f scale = props->scale.vector.getInterpolated(props->scale.previous, progress);
+			bone->setScale(props->scale.absolute
+					? scale
+					: scale * bone->getScale());
```
Comment (sfan5) [inline src/client/content_cao.cpp:1571]: proper OOP _would_ be to have these implementations inside `BoneOverride`
(not saying you have to)

File: src/client/content_cao.cpp [hunk 30]
```diff
@@ -1817,10 +1860,51 @@ void GenericCAO::processMessage(const std::string &data)
...
+					props->scale.previous = previous->scale.vector;
+				} else {
+					// disable interpolation
+					props->position.interpolation_duration = 0.0f;
+					props->rotation.interpolation_duration = 0.0f;
+					props->scale.interpolation_duration = 0.0f;
+				}
+			}
+		}
+		if (previous)
```
Comment (sfan5) [inline src/client/content_cao.cpp:1900]: it doesn't look necessary here to create a new object instead of reusing whats already there

File: src/network/networkprotocol.h [hunk 31]
```diff
@@ -209,6 +209,9 @@ with this program; if not, write to the Free Software Foundation, Inc.,
 		TOCLIENT_MEDIA_PUSH changed, TOSERVER_HAVE_MEDIA added
 		Added new particlespawner parameters
 		[scheduled bump for 5.6.0]
+	PROTOCOL VERSION 41:
+		AO_CMD_SET_BONE_POSITION extended
+		[scheduled bump for 5.7.0]
```
Comment (sfan5) [inline src/network/networkprotocol.h:214]:
```suggestion
```

File: src/script/lua_api/l_object.cpp [hunk 32]
```diff
@@ -544,14 +551,123 @@ int ObjectRef::l_get_bone_position(lua_State *L)
...
+	if (!lua_isnil(L, -1)) {
+		props->scale.vector = check_v3f(L, -1);
+		read_prop_attrs(props->scale);
+		lua_pop(L, 1);
+	}
+	sao->setBoneOverride(bone, props.release());
+	return 0;
+}
+
+void push_bone_override(lua_State *L, BoneOverride *props)
```
Comment (sfan5) [inline src/script/lua_api/l_object.cpp:613]: static

File: src/server/unit_sao.cpp [hunk 33]
```diff
@@ -273,15 +273,26 @@ std::string UnitSAO::generateUpdateAttachmentCommand() const
...
+	writeV3F32(os, props->scale.vector);
+	writeF32(os, props->position.interpolation_duration);
+	writeF32(os, props->rotation.interpolation_duration);
+	writeF32(os, props->scale.interpolation_duration);
+	// clang-format off
+	writeU8(os, (props->position.absolute & 1) << 0
+	          | (props->rotation.absolute & 1) << 1
+	          | (props->scale.absolute & 1) << 2);
+	// clang-format on
```
Comment (sfan5) [inline src/server/unit_sao.cpp:295]:
```suggestion
	writeU8(os, (props->position.absolute & 1) << 0
	          | (props->rotation.absolute & 1) << 1
	          | (props->scale.absolute & 1) << 2);
```

File: src/server/unit_sao.h [hunk 34]
```diff
@@ -103,7 +105,7 @@ class UnitSAO : public ServerActiveObject
 	ObjectProperties m_prop;
 
 	// Stores position and rotation for each bone name
-	std::unordered_map<std::string, core::vector2d<v3f>> m_bone_position;
+	std::unordered_map<std::string, BoneOverride*> m_bone_override;
```
Comment (sfan5) [inline src/server/unit_sao.h:108]: also no need for pointers here

File: src/server/unit_sao.cpp (hunk 33 above)
Comment (appgurueu) [reply src/server/unit_sao.cpp:295]: what do you mean by that? should I remove the comments?

Comment (sfan5) [reply src/server/unit_sao.cpp:295]: yes

**Comment by appgurueu** [comment]
Rebased.

**Comment by appgurueu** [comment]
@minetest/engine bump.

File: src/script/lua_api/l_object.cpp [hunk 35]
```diff
@@ -535,14 +542,138 @@ int ObjectRef::l_get_bone_position(lua_State *L)
...
+}
+
+static void push_bone_override(lua_State *L, BoneOverride props)
+{
+	lua_newtable(L);
+
+	auto push_prop = [L](const char *name, auto prop, v3f vec) {
+		lua_newtable(L);
+		push_v3f(L, vec);
+		lua_setfield(L, -2, "vector");
```
Comment (SmallJoker) [inline src/script/lua_api/l_object.cpp:626]: Inconsistent with `"vec"` from the input. Perhaps using macros in this file would help to avoid such mismatches....

File: src/script/lua_api/l_object.cpp [hunk 36]
```diff
@@ -535,14 +542,138 @@ int ObjectRef::l_get_bone_position(lua_State *L)
...
+int ObjectRef::l_get_bone_overrides(lua_State *L)
+{
+	NO_MAP_LOCK_REQUIRED;
+	ObjectRef *ref = checkObject<ObjectRef>(L, 1);
+	ServerActiveObject *co = getobject(ref);
+	if (co == NULL)
+		return 0;
+	lua_newtable(L);
+	for (const auto &bone_pos : co->getBoneOverrides()) {
+		push_bone_override(L, bone_pos.second);
```
Comment (SmallJoker) [inline src/script/lua_api/l_object.cpp:673]:
```
2022-10-30 13:27:06: ERROR[Main]: ServerError: AsyncErr: Lua: Runtime error from mod 'lab' in callback on_chat_message(): attempt to index a userdata value
2022-10-30 13:27:06: ERROR[Main]: stack traceback:
2022-10-30 13:27:06: ERROR[Main]: 	[C]: in function 'get_bone_overrides'
2022-10-30 13:27:06: ERROR[Main]: 	XXX/mods/lab/init_126_bone_overrides_12388.lua:29: in function 'func'
```

```lua
		local player = assert(minetest.get_player_by_name(name))
		print(dump(player:get_bone_overrides()))
```

File: src/script/lua_api/l_object.cpp [hunk 37]
```diff
@@ -535,14 +542,138 @@ int ObjectRef::l_get_bone_position(lua_State *L)
...
+	ObjectRef *ref = checkObject<ObjectRef>(L, 1);
+	ServerActiveObject *sao = getobject(ref);
+	if (sao == NULL)
+		return 0;
+
+	std::string bone;
+	if (!lua_isnil(L, 2))
+		bone = readParam<std::string>(L, 2);
+
+	push_bone_override(L, sao->getBoneOverride(bone));
```
Comment (SmallJoker) [inline src/script/lua_api/l_object.cpp:659]:
```
2022-10-30 13:28:04: ERROR[Main]: ServerError: AsyncErr: Lua: Runtime error from mod 'lab' in callback on_chat_message(): attempt to index a string value
2022-10-30 13:28:04: ERROR[Main]: stack traceback:
2022-10-30 13:28:04: ERROR[Main]: 	[C]: in function 'get_bone_override'
2022-10-30 13:28:04: ERROR[Main]: 	XX/mods/lab/init_126_bone_overrides_12388.lua:29: in function 'func'
```

```lua
local player = assert(minetest.get_player_by_name(name))
print(dump(player:get_bone_override("Head")))
```

File: src/server/unit_sao.cpp [hunk 38]
```diff
@@ -273,15 +273,24 @@ std::string UnitSAO::generateUpdateAttachmentCommand() const
 }
 
 std::string UnitSAO::generateUpdateBonePositionCommand(
-		const std::string &bone, const v3f &position, const v3f &rotation)
+		const std::string &bone, const BoneOverride props)
```
[the remark this answers is not in the document]
Comment (appgurueu) [reply src/server/unit_sao.cpp:276]: Sure

**Review by SmallJoker — APPROVED** [review]
Works. Had to modify the sample script a bit to use `"vec"` and to test the getter functions.

**Comment by jordan4ibanez** [comment]
Hello I am bumping this thing with this comment beep boop

**Comment by runsy** [comment]
With this I would get the real default get_bone_position?

**Comment by appgurueu** [comment]
> With this I would get the real default get_bone_position?

No; the server is generally unaware of the media it sends out - it doesn't read it at all, that's done only on the client. You can however work around this using modlib, which contains a b3d reader.

**Comment by appgurueu** [comment]
Conflict resolved.

**Comment by appgurueu** [comment]
Rebased again. Sorry for the mess of commits, I should probably have squashed before rebasing.

**Comment by Zughy** [comment]
@appgurueu rebase needed

**Comment by appgurueu** [comment]
heh, that was trivial to resolve

**Comment by appgurueu** [comment]
Bumped everything for 5.9.0 since we're in feature freeze for 5.8.0 now.

File: doc/lua_api.md [hunk 39]
```diff
@@ -7532,17 +7532,33 @@ child will follow movement and rotation of that bone.
...
-* `get_bone_position(bone)`:
-    * returns bone parameters previously set by `set_bone_position`
-    * returns `position, rotation` of the specified bone (as vectors)
-    * note: position is relative to the object
-* `set_properties(object property table)`:
-    * set a number of object properties in the given table
-    * only properties listed in the table will be changed
-    * see the 'Object properties' section for details
+	* Shorthand for `set_bone_override(bone, {position = position, rotation = rotation:apply(math.rad)})` using absolute values.
+	* Supports older servers & clients (5.8.0 and earlier).
```
Comment (sfan5) [inline doc/lua_api.md:7536]: nitpick: this note seems to encourage using this function, however it is deprecated
that it supports old clients can also be deduced from below information

File: doc/lua_api.md [hunk 40]
```diff
@@ -7532,17 +7532,33 @@ child will follow movement and rotation of that bone.
...
+    * `bone`: string
+    * `override`: `{ position = property, rotation = property, scale = property }` or `nil`
+        * `property`: `{ vec = vector, interpolation = 0, absolute = false}` or `nil`;
+            * `vec` is in the same coordinate system as the model, and in degrees for rotation
+        * `property = nil` is equivalent to no override on that property
+        * `absolute`: If set to `false`, the override will be relative to the animated property:
+            * Transposition in the case of `position`;
+            * Composition in the case of `rotation`;
+            * Multiplication in the case of `scale`
+        * `interpolation`: Time it takes (on the client, in seconds) to interpolate between the old & new value
```
Comment (sfan5) [inline doc/lua_api.md:7553]: dunno
```suggestion
        * `interpolation`: Old and new values are interpolated over this timeframe (in seconds)
```

File: src/activeobject.h [hunk 41]
```diff
@@ -72,6 +74,79 @@ enum ActiveObjectCommand {
 	AO_CMD_SET_ANIMATION_SPEED
 };
 
+struct BoneOverride
+{
+public:
```
Comment (sfan5) [inline src/activeobject.h:79]:
```suggestion
{
```

File: src/network/networkprotocol.h [hunk 42]
```diff
@@ -491,7 +494,7 @@ enum ToClientCommand
 		u8[len] formspec
 	*/
 
-	TOCLIENT_DETACHED_INVENTORY = 0x43,
+	TOCLIENT_DETACHED_INVENTORY = 0x,
```
Comment (sfan5) [inline src/network/networkprotocol.h:497]: rebase mistake (how?)

File: src/script/lua_api/l_object.cpp [hunk 43]
```diff
@@ -517,11 +518,17 @@ int ObjectRef::l_set_bone_position(lua_State *L)
 	if (sao == nullptr)
 		return 0;
 
-	std::string bone = readParam<std::string>(L, 2, "");
-	v3f position = readParam<v3f>(L, 3, v3f(0, 0, 0));
-	v3f rotation = readParam<v3f>(L, 4, v3f(0, 0, 0));
-
-	sao->setBonePosition(bone, position, rotation);
+	std::string bone;
```
Comment (sfan5) [inline src/script/lua_api/l_object.cpp:521]: log_deprecated missing here and below

File: src/script/lua_api/l_object.cpp [hunk 44]
```diff
@@ -535,14 +542,137 @@ int ObjectRef::l_get_bone_position(lua_State *L)
...
+	ServerActiveObject *sao = getobject(ref);
+	if (sao == NULL)
+		return 0;
 
-	push_v3f(L, position);
-	push_v3f(L, rotation);
-	return 2;
+	std::string bone;
+	if (!lua_isnil(L, 2))
+		bone = readParam<std::string>(L, 2);
```
Comment (sfan5) [inline src/script/lua_api/l_object.cpp:564]: if we're introducing a new api `nil` should probably not silent count for `""`, confusing imo

File: src/script/lua_api/l_object.cpp [hunk 45]
```diff
@@ -535,14 +542,137 @@ int ObjectRef::l_get_bone_position(lua_State *L)
...
+		lua_getfield(L, -1, "interpolate");
+		if (lua_isnumber(L, -1))
+			prop.interp_timer = lua_tonumber(L, -1);
+		lua_pop(L, 1);
+	};
+
+	lua_getfield(L, 3, "position");
+	if (!lua_isnil(L, -1)) {
+		lua_getfield(L, -1, "vec");
+		props.position.vector = lua_isnil(L, -1) ? v3f() : check_v3f(L, -1);
```
Comment (sfan5) [inline src/script/lua_api/l_object.cpp:586]: is there a reason for this pattern?
`props.position.vector` will be default initialized already

File: src/script/lua_api/l_object.cpp [hunk 46]
```diff
@@ -535,14 +542,137 @@ int ObjectRef::l_get_bone_position(lua_State *L)
...
+
+		read_prop_attrs(props.scale);
+	}
+	lua_pop(L, 1);
+
+	sao->setBoneOverride(bone, props);
+	return 0;
+}
+
+static void push_bone_override(lua_State *L, BoneOverride props)
```
Comment (sfan5) [inline src/script/lua_api/l_object.cpp:619]:
```suggestion
static void push_bone_override(lua_State *L, const BoneOverride &props)
```

File: src/script/lua_api/l_object.cpp [hunk 47]
```diff
@@ -535,14 +542,137 @@ int ObjectRef::l_get_bone_position(lua_State *L)
...
+{
+	lua_newtable(L);
+
+	auto push_prop = [L](const char *name, auto prop, v3f vec) {
```
Comment (sfan5) [inline src/script/lua_api/l_object.cpp:623]:
```suggestion
	auto push_prop = [L](const char *name, const auto &prop, v3f vec) {
```

File: src/server/luaentity_sao.cpp [hunk 48]
```diff
@@ -256,13 +256,13 @@ std::string LuaEntitySAO::getClientInitializationData(u16 protocol_version)
 	msg_os << serializeString32(getPropertyPacket()); // message 1
 	msg_os << serializeString32(generateUpdateArmorGroupsCommand()); // 2
 	msg_os << serializeString32(generateUpdateAnimationCommand()); // 3
-	for (const auto &bone_pos : m_bone_position) {
+	for (const auto &bone_pos : m_bone_override) {
```
Comment (sfan5) [inline src/server/luaentity_sao.cpp:259]: nitpick: get rid of `bone_pos` if you want to keep the naming consistent

File: src/server/serveractiveobject.h [hunk 49]
```diff
@@ -171,14 +172,16 @@ class ServerActiveObject : public ActiveObject
 	{}
 	virtual void setAnimationSpeed(float frame_speed)
 	{}
-	virtual void setBonePosition(const std::string &bone, v3f position, v3f rotation)
-	{}
-	virtual void getBonePosition(const std::string &bone, v3f *position, v3f *lotation)
+	virtual void setBoneOverride(const std::string &bone, BoneOverride props)
```
Comment (sfan5) [inline src/server/serveractiveobject.h:175]: should be `const BoneOverride &`

File: src/network/networkprotocol.h (hunk 42 above)
Comment (appgurueu) [reply src/network/networkprotocol.h]: oops! fixed. (how: i was lazy and did the edits in GH's web editor. i searched for 43 in case it was mentioned / hardcoded elsewhere in the file; must've accidentally hit replace)

File: src/script/lua_api/l_object.cpp (hunk 43 above)
Comment (appgurueu) [reply src/script/lua_api/l_object.cpp:524]: Inserted the calls at the top of the functions [gs]et_bone_position functions.

File: src/script/lua_api/l_object.cpp (hunk 45 above)
Comment (appgurueu) [reply src/script/lua_api/l_object.cpp:592]: Most probably copy-paste or I didn't think of the default initialization. Maybe I also found this more explicit / less error prone?
Note that in contrast to position, scale needs `v3f(1)`; relying on the implicit default-initialization for position & rotation (but not scale) may be a bit harder on the reader?

Either way I don't feel strongly about this, and I agree that dead code should be eliminated. I assume you would prefer `if (!lua_isnil(L, -1)) props.position.vector = check_v3f(L, -1);` (formatted properly)?

File: src/server/luaentity_sao.cpp (hunk 48 above)
Comment (appgurueu) [reply src/server/luaentity_sao.cpp]: (C++-wise) kept only `generateUpdateBonePositionCommand` with `BonePosition` in its name (given that this method name is based on the historic packet name, I'm somewhat reluctant to rename that method).

File: doc/lua_api.md (hunk 39 above)
Comment (appgurueu) [reply doc/lua_api.md]: Removed

File: src/script/lua_api/l_object.cpp (hunk 45 above)
Comment (appgurueu) [reply src/script/lua_api/l_object.cpp]: Eliminated the unnecessary ternaries for now. Feel free to revert https://github.com/minetest/minetest/pull/12388/commits/61d765addb00839ca061c7c3bac315df87ea5dfd if you found the ternaries more readable.

**Comment by appgurueu** [comment]
Thanks for the review. Should all be addressed now.

File: src/server/luaentity_sao.cpp (hunk 48 above)
Comment (sfan5) [reply src/server/luaentity_sao.cpp]: You can rename it if you want

Comment (appgurueu) [reply src/server/luaentity_sao.cpp]: Alright, done https://github.com/minetest/minetest/pull/12388/commits/e55eafc18678e05ef9624cd216c85a704a940215.

File: src/server/player_sao.cpp [hunk 50]
```diff
@@ -122,7 +122,7 @@ std::string PlayerSAO::getClientInitializationData(u16 protocol_version)
 	msg_os << serializeString32(generateUpdateArmorGroupsCommand()); // 2
 	msg_os << serializeString32(generateUpdateAnimationCommand()); // 3
 	for (const auto &bone_pos : m_bone_override) {
```
Comment (sfan5) [inline src/server/player_sao.cpp:124]: then do `s/bone_pos/it` too :)

Comment (appgurueu) [reply src/server/player_sao.cpp]: oops

File: doc/lua_api.md [hunk 51]
```diff
@@ -7532,17 +7532,32 @@ child will follow movement and rotation of that bone.
...
+            * `vec` is in the same coordinate system as the model, and in degrees for rotation
+        * `property = nil` is equivalent to no override on that property
+        * `absolute`: If set to `false`, the override will be relative to the animated property:
+            * Transposition in the case of `position`;
+            * Composition in the case of `rotation`;
+            * Multiplication in the case of `scale`
+        * `interpolation`: Old and new values are interpolated over this timeframe (in seconds)
+    * `override = nil` (including omission) is shorthand for `override = {}` which clears the override
+    * **Note:** Unlike `set_bone_position`, the rotation is in radians, not degrees.
+    * Compatibility note: Clients prior to 5.8.0 only support absolute position and rotation.
```
Comment (grorp) [inline doc/lua_api.md:7555]:
```suggestion
    * Compatibility note: Clients prior to 5.9.0 only support absolute position and rotation.
```

**Comment by MisterE123** [comment]
Wait, so legboat can actually walk smoothly now? As in, real, interpolated, terrain-based IK is possible?

**Comment by appgurueu** [comment]
After a bug report, I realized that this PR introduced a behavioral change in `get_bone_position` API: Before, it would give you back whatever you put in. Now, it gives you an equivalent rotation (assuming Irrlicht's quaternion to euler angle and vice versa conversions are correct), which can break code which relied on it giving you the very vector you put in.

The possibly affected mods and games are the following: https://content.minetest.net/zipgrep/5296f687-4e1c-4ae1-8520-0119d7940824/. Notably ElCeejo's mods are affected, as well as possibly the Mineclone family.

A simple workaround would be to keep the original euler angles around (which mods could also do themselves). Should I implement that?

**Comment by sfan5** [comment]
No opinion but it'd be best to track this in a new issue.
