### PR TITLE
Fix set_fov-induced grayscreen

### LINKED ISSUE #14499: Greyscreening and unrecoverable game state when switching between FOVs with varied transitions (with transition time nil or 0)
### Minetest version

```true
Minetest 5.8 official windows build.
OpenGL 4.6
Irrlicht device WIN32
```

### Irrlicht device

_No response_

### Operating system and version

Windows 10

### CPU model

_No response_

### GPU model

_No response_

### Active renderer

OpenGL 4.6

### Summary

This problem was found initially by users of the mod I am working on (guns4d) running with another mod that changes FOV as well (spriteguns). This problem appears to occur when FOV "transition" time is varied between `set_fov()` calls (exact specifics are not clear, but the issue is clearly present). The other values of the call don't seem to matter (experimentation is needed for that probably). It's notable that the issue in my mod was fixed by setting a minimum transition time- so this issue seems to only occur when transition time is 0.

Players are unable to see, move, or otherwise interact with the game world after this bug occurs. It's also notable that pitch and yaw are set to NaN. There is no way to escape this, set_fov calls of any type do not appear to fix it. The only way out is to quit to menu and rejoin the world.

### Steps to reproduce

here is simple code to register an item. Click repeatedly (at any given rate) and eventually you will be in an unrecoverable grey-screen with the above symptoms. It seems to happen after around 4 clicks.

```
local flip = false
minetest.register_tool("minetest_is_broke:shitty_test", {
    description = "the dark times are upon us",
    on_use = function(itemstack, user, pointed_thing)
        flip = not flip
        if flip then
            user:set_fov(80,false,.25)
        else
            user:set_fov(80,false,0)
        end
    end
})
```

### PR DESCRIPTION
**Pull request by appgurueu**
Fixes #14499, ready for review.

## How to test

* Read the code and confirm that the new logic (immediately updating `m_fov_transition_active`) makes more sense (and should fix the bug).
* Make sure that you can't reproduce the linked issue with this PR.
* Basic regression test: Alter the example code a bit to `user:set_fov(flip and 80 or 60,false, flip and .25 or 0)`. Confirm that the FOV change to a "wider" FOV ("zooming out") is smooth, whereas "zooming in" is instantaneous. Maybe also test multipliers.

### CODE REVIEW

**Review by grorp — COMMENTED** [review]
https://github.com/minetest/minetest/blob/f1b7b0c4fdbbfed114ccd806f6e6cf7f426b7f2f/src/client/camera.cpp#L102-L112

`m_fov_transition_active` is now set before this code section. At least the comment is wrong because of that. However, the code also doesn't make much sense anymore: Why do we even set `m_old_fov_degrees` if there isn't going to be a transition?

Looking closer, I can see that `m_old_fov_degrees` should be a local variable since it isn't used outside the function. And it's only used if `m_fov_transition_active` is true, so the second half of the "if" block is useless now.

**Comment by appgurueu** [comment]
Thanks for giving this a look. That was sloppy on my part, fixed now. Code for testing:

```lua
minetest.register_tool("testtools:set_fov", {
	description = "test set_fov",
	on_use = function(_, user, _)
		local multiplier = math.random() < 0.5
		local fov = multiplier and 0.5 + math.random() or math.random(40, 120)
		local duration = math.random() < 0.5 and 0 or math.random() * 5
		minetest.chat_send_all((":set_fov(%s, %s, %s)"):format(fov, multiplier, duration))
		user:set_fov(fov, multiplier, duration)
	end
})
```

Use this a few times, check whether what you're seeing roughly matches what's printed in chat.

File: src/client/camera.cpp [hunk 1]
```diff
@@ -97,38 +97,21 @@ void Camera::notifyFovChange()
...
-		m_target_fov_degrees = spec.is_multiplier ? m_cache_fov * spec.fov : spec.fov;
-	}
-
-	if (spec.transition_time > 0.0f)
-		m_fov_transition_active = true;
-
-	// If FOV smooth transition is active, initialize required variables
+	// Remember old FOV in case a transition is wanted
+	f32 m_old_fov_degrees = m_fov_transition_active
+		? m_curr_fov_degrees // FOV is overridden with transition
```
Comment (appgurueu) [inline src/client/camera.cpp:102]: BTW I'm not sure what our conventions for nested ternaries are. Two tab indents look off when nesting ternaries.

File: src/client/camera.cpp [hunk 2]
```diff
@@ -97,38 +97,21 @@ void Camera::notifyFovChange()
...
-	if (spec.fov == 0.0f) {
-		m_server_sent_fov = false;
-		m_target_fov_degrees = m_cache_fov;
-	} else {
-		m_server_sent_fov = true;
-		m_target_fov_degrees = spec.is_multiplier ? m_cache_fov * spec.fov : spec.fov;
-	}
-
-	if (spec.transition_time > 0.0f)
-		m_fov_transition_active = true;
```
Comment (appgurueu) [inline src/client/camera.cpp:129]: Basically, the fix boils down to setting this to `false` *immediately* when appropriate. But we might as well turn `m_old_fov_degrees` into a local variable and use ternaries.

**Comment by grorp** [comment]
For me, these nested ternaries are less readable than the if statements were.

File: src/client/camera.cpp (hunk 1 above)
Comment (sfan5) [reply src/client/camera.cpp:102]: my personal convention for nested ternaries is: don't

**Review by SmallJoker — APPROVED** [review]
:ballot_box_with_check: reproduced the grayscreen issue on master
:ballot_box_with_check: can confirm that the issue is fixed
:ballot_box_with_check: binoculars still work
