### PR TITLE
Fix get_craft_result when called before initHashes

### LINKED ISSUE #8607: minetest.get_craft_result regression
##### Minetest version

```
cf9108433c21bf921603258d757a5b7dad8396bb
```

##### Summary

 #8445 broke `minetest.get_craft_result`.

##### Steps to reproduce

Start a Minimal Development Test game, see assertion fail:
```
ModError: Failed to load and run script from /home/paul/src/minetest/minetest/bin/../games/minimal/mods/default/init.lua:
...test/minetest/bin/../games/minimal/mods/default/init.lua:1857: assertion failed!
stack traceback:
	[C]: in function 'assert'
	...test/minetest/bin/../games/minimal/mods/default/init.lua:1857: in function 'test_get_craft_result'
	...test/minetest/bin/../games/minimal/mods/default/init.lua:1888: in main chunk
```

### PR DESCRIPTION
**Pull request by pauloue**
Fixes #8607

`getCraftResult` was not working before the `initHashes` call because it uses the recipe priority which was not initialized until the hashes are inited.

## To do

This PR is Ready for Review.

## How to test

- Start a world in the minimal game, there should be no assertion failure
- In MTG, try placing a wooden stair or slab in the fuel slot of a furnace

### CODE REVIEW

File: src/craftdef.h [hunk 1]
```diff
@@ -373,10 +366,9 @@ class CraftDefinitionFuel: public CraftDefinition
 public:
 	CraftDefinitionFuel() = delete;
 	CraftDefinitionFuel(const std::string &recipe_,
```
Comment (ClobberXD) [inline src/craftdef.h]:
```suggestion
	CraftDefinitionFuel(
		const std::string &recipe_,
```

Could the first arg be moved to the next line for consistency with the rest of the changes in this file?

**Comment by Kevin-Mok** [comment]
This fixes the assertion error for me, and placing a wooden stair in the fuel slot of a furnace in MTG also works.
