### PR TITLE
ServerEnv: Clean up object lifecycle handling

### LINKED ISSUE #6379: Item entity may become hand after merging
It is possible for item entities to be the hand. This sometimes happens when two item entities merge.

How a dropped hand looks like:

How to reproduce:
1. Create a flat world with seed 0 in Minetest Game
2. Activate the test mod below
3. Start the game
4. Go towards X=0, Z=0 to watch items dropping
5. Now go away from the center and look at the falling items
6. As soon the falling items disappear, go closer again until the items are visible again
7. Repeat the last 2 steps a couple of times
8. Go to the items and collect the wheat seeds

With a bit of luck you will now find a hand. Repeat steps 4-8 as often as you like.

```
-- Spawn a wheat seed item entity at (0,15,0) every second
local t = 0
minetest.register_globalstep(function(dtime)
        t = t + dtime
        if t > 1 then
                minetest.add_item({x=0, y=15, z=0}, "farming:seed_wheat")
                t = 0
        end
end)
```

Successfully reproduced in Minetest 0.4.16 *and* 04cf7a0d8140c5a938a57ac657f4cd282658a1d1!

## Analysis
Possible cause of the problem: In `builtin/game/item_entity.lua`, `try_merge_with` sets `itemstring` to `""` before removing it. However `remove()` doesn't really remove the item and the `on_step` function is still called a couple of times before the item is actually removed (this is another bug which I believe is reported elsewhere, I just can't find it now. Correct me if I am wrong). Now consider this: What if an item entity gets deactivated *just* before the item is *really* deleted? In that case, the itemstring is set to `""` and as soon the entitiy is `on_activate`d again, it will load the `itemstring` of `""`, which is then fed into `set_item` and boom! We have a dropped hand.
This is just a guess because I don't understand the inner workings of the item activate/deactivate/remove logic.

I'm not sure what would be the ideal bugfix for this.

### PR DESCRIPTION
**Pull request by sfan5**
* better code comments to make _correctly_ understanding this in <1h viable
* rename `m_removed` to `m_pending_removal` to better explain its purpose.
* bug: removed objects could be deactivated and saved to disk instead of being removed (fixes #6379)
* bug/oddity: `get_objects_inside_radius` did not ignore objects pending deactivation
* refactor `deactivateFarObjects()`, `removeRemovedObjects()` and `clearObjects()` to deduplicate code
* add warning if a removed/deactivated object ever enters Lua

/cc @celeron55, @Wuzzy2

### CODE REVIEW

File: src/serverenvironment.cpp [hunk 1]
```diff
@@ -1855,22 +1833,14 @@ void ServerEnvironment::activateObjects(MapBlock *block, u32 dtime_s)
...
 		block->m_static_objects.m_stored.push_back(s_obj);
 	}
 
-	// Turn the active counterparts of activated objects not pending for
-	// deactivation
-	for (auto &i : block->m_static_objects.m_active) {
-		u16 id = i.first;
-		ServerActiveObject *object = getActiveObject(id);
-		assert(object);
-		object->m_pending_deactivation = false;
```
Comment (sfan5) [inline src/serverenvironment.cpp]: since the SAOs are newly created in the `for` loop above, they assume the default value...
...which is `false`
-> no-op

File: src/serverenvironment.cpp [hunk 2]
```diff
@@ -2122,6 +2009,69 @@ void ServerEnvironment::deactivateFarObjects(bool _force_delete)
...
+	block->m_static_objects.remove(id);
+	if (mod_reason != MOD_REASON_UNKNOWN) // Do not mark as modified if requested
+		block->raiseModified(MOD_STATE_WRITE_NEEDED, mod_reason);
+
+	obj->m_static_exists = false;
+}
+
+bool ServerEnvironment::saveStaticToBlock(
+		v3s16 blockpos, u16 store_id,
+		ServerActiveObject* obj, const StaticObject &s_obj,
```
Comment (nerzhul) [inline src/serverenvironment.cpp]: * in the wrong place

File: src/serverenvironment.cpp [hunk 3]
```diff
@@ -2122,6 +2009,69 @@ void ServerEnvironment::deactivateFarObjects(bool _force_delete)
...
+		u32 mod_reason)
+{
+	MapBlock *block = NULL;
```
Comment (nerzhul) [inline src/serverenvironment.cpp]: nullptr please

Comment (sfan5) [reply src/serverenvironment.cpp]: `emergeBlock` will return `NULL` not `nullptr` in case of failure
both shouldn't be mixed, right?

Comment (nerzhul) [reply src/serverenvironment.cpp]: as you check if (!block) NULL or nullptr is not a problem, it can be a problem if you check == NULL

**Comment by Wuzzy2** [comment]
So with this PR there are no more dropped hands on the ground?

**Comment by sfan5** [comment]
> So with this PR there are no more dropped hands on the ground?

**Comment by Wuzzy2** [comment]
Hey! I just wanted to test this today but then I saw someone already merged it …
lol.

I have quickly tested this anyway as you requested and the hands don't seem to drop anymore.
