### PR TITLE
Fix builtin statbar backgrounds

### LINKED ISSUE #10741: Health & breathbar ignore max properties
```lua
local health_bar_definition = {
	hud_elem_type = "statbar",
	position = {x = 0.5, y = 1},
	text = "heart.png",
	text2 = "heart_gone.png",
	number = core.PLAYER_MAX_HP_DEFAULT,
	item = core.PLAYER_MAX_HP_DEFAULT,
	direction = 0,
	size = {x = 24, y = 24},
	offset = {x = (-10 * 24) - 25, y = -(48 + 24 + 16)},
}

local breath_bar_definition = {
	hud_elem_type = "statbar",
	position = {x = 0.5, y = 1},
	text = "bubble.png",
	text2 = "bubble_gone.png",
	number = core.PLAYER_MAX_BREATH_DEFAULT,
	item = core.PLAYER_MAX_BREATH_DEFAULT * 2,
	direction = 0,
	size = {x = 24, y = 24},
	offset = {x = 25, y= -(48 + 24 + 16)},
}
```
`number` & `item` should be changed depending on the player properties `hp_max` and `breath_max`.

### LINKED ISSUE #11999: Statbars don't show half-element backgrounds
##### Minetest version
```
5.5-dev, probably all
```

##### Summary
Half background elements of statbars don't get shown. I assume this hasn't been discovered earlier for three reasons:

* Games rarely set a `hp_max` not divisible by two;
* The builtin statbar backgrounds weren't updated at all (see #10741);
* Devtest and MTG have a transparent `heart_gone.png`

##### Steps to reproduce

Test the following with a nontransparent `heart_gone.png`, such as the one from Zughy's soothing32 texture pack. This should show a heart and half a gone heart, but it only shows a heart.

```lua
minetest.register_on_joinplayer(function(player)
	player:hud_add{
		hud_elem_type = "statbar",
		position = {x = 0.5, y = 0.5},
		text = "heart.png",
		text2 = "heart_gone.png",
		number = 2,
		item = 3,
		direction = 0,
		size = {x = 24, y = 24},
	}
end)
```

### PR DESCRIPTION
**Pull request by appgurueu**
Closes #11999. Also closes #10741.

* Half background statbar "off" icons weren't drawn if the HP was even, as the clipping rect zero-defaulted.
* HP & breath were incorrectly scaled: If the max properties were set to something below the default max, the default max was still assumed to be the max. This also `ceil`s the scaled values instead of (implicitly?) `floor`ing them.

## How to test

```lua
local hp = 1
local timer = 0
minetest.register_globalstep(function(dtime)
timer = timer + dtime
	if timer < 1 then return end
	timer = 0
	for _, player in pairs(minetest.get_connected_players()) do
		player:set_properties{hp_max = hp + 3}
		player:set_hp(hp)
	end
	if hp > 30 then
		hp = 1
	else
		hp = hp + 1
	end
end)

minetest.register_on_joinplayer(function(player)
	player:hud_add{
		hud_elem_type = "statbar",
		position = {x = 0.5, y = 0.5},
		text = "heart.png",
		text2 = "heart_gone.png",
		number = 2,
		item = 3,
		direction = 0,
		size = {x = 24, y = 24},
	}
end)
```

### CODE REVIEW

**Comment by appgurueu** [comment]
The second fix might be considered controversial - there are two ways to approach this:

- Show `max` many background icons;
- Correctly scale bars to a fixed max of the default value

Currently, it shows as many foreground icons as players have HP (absolute value) if `max < default`, but shows a fixed-size background.

File: builtin/game/statbars.lua [hunk 1]
```diff
@@ -31,9 +31,8 @@ local function scaleToDefault(player, field)
 	-- Scale "hp" or "breath" to the default dimensions
 	local current = player["get_" .. field](player)
 	local nominal = core["PLAYER_MAX_" .. field:upper() .. "_DEFAULT"]
```
Comment (sfan5) [inline builtin/game/statbars.lua:33]: Shouldn't this scale to whatever is in `item` of the respective definition? Remember that the definitions are changeable by API call.

**Review by sfan5 — APPROVED** [review]
Works, but..

**Comment by sfan5** [comment]
> The second fix might be considered controversial

Interacting with this part of builtin is tricky so I expect interested games/mods to just disable the builtin statbars and re-do them entirely.

File: builtin/game/statbars.lua (hunk 1 above)
Comment (appgurueu) [reply builtin/game/statbars.lua:33]: Sounds reasonable.

File: builtin/game/statbars.lua [hunk 2]
```diff
@@ -1,39 +1,39 @@
...
+		size = {x = 24, y = 24},
+		offset = {x = (-10 * 24) - 25, y = -(48 + 24 + 16)},
+	},
+	breath = {
+		hud_elem_type = "statbar",
+		position = {x = 0.5, y = 1},
+		text = "bubble.png",
+		text2 = "bubble_gone.png",
+		number = core.PLAYER_MAX_BREATH_DEFAULT * 2,
+		item = core.PLAYER_MAX_BREATH_DEFAULT * 2,
```
Comment (Df458) [inline builtin/game/statbars.lua:22]: This is a regression, with the change in this pr I get double bubble icons that disappear in pairs instead of single icons that disappear one at a time. Strangely, the bubble backgrounds also only exist beneath half the icons... presumably the `item` field is halved at some point:
Screenshot-2022-01-28-18:45:23

Comment (sfan5) [reply builtin/game/statbars.lua:22]: Indeed, it's right here:
grafik

Comment (appgurueu) [reply builtin/game/statbars.lua:22]: Indeed, I was too sloppy there - I noted that clearly the initial def was wrong, as fg & bg use the same units (half elements), so both had to be multiplied by two. I missed the multiplier sfan has shown though.

**Review by Df458 — APPROVED** [review]
Looks good to me. The half-background looks a little funny, but so does a half-heart on its own and a full-background is misleading. I think your solution is a clear improvement to the previous behavior.
