### PR TITLE
[no squash] Fix bright sky in caves (without noclip priv)

### LINKED ISSUE #5939: Bright sky underground when noclip enabled without priv
```
	if (m_cache_enable_noclip && m_cache_enable_free_move) {
		direct_brightness = time_brightness;
		sunlight_seen = true;
```
Currently a client can cause the skybox to be bright deep underground by enabling 'freemove' and 'noclip' even if the client does not have those priviledges.
This causes 2 problems:
1. ~~A client can use an 'x-ray' texture pack to cheat and see distant caves, the location of ores in cave walls, and can navigate iin caves without needing torches:~~
EDIT: #5943 merged so no longer possible.

2. With a normal texture pack a client can effectively 'light' a cave by reducing view range to minimum:

screenshot_20170607_030954

These issues came up in #4646 3253b6bd2238eaa8f773f7881f8e47200dc5f42a
Specifically https://github.com/minetest/minetest/pull/4646#issuecomment-254308732
@lhofhansl

### PR DESCRIPTION
**Pull request by sfan5**
old bug described e.g. here https://forum.minetest.net/viewtopic.php?p=410257#p410257
the first commit is there because I first thought it would be useful but it turned out not

Fixes #5939

## To do

This PR is Ready for Review.

## How to test

1. Stare at unloaded blocks in a cave (easy with `max_block_send_distance=1`) during daytime
2. Do *not* have the `noclip` privilege
3. Enable free_move mode
4. Toggle noclip on and off and verify that the unloaded area does not turn bright

### CODE REVIEW

File: src/client/game.cpp [hunk 1]
```diff
@@ -1757,6 +1759,9 @@ void Game::updateDebugState()
 		hud->disableBlockBounds();
 	if (!has_debug)
 		draw_control->show_wireframe = false;
+
+	// noclip
+	draw_control->allow_noclip = m_cache_enable_noclip && client->checkPrivilege("noclip");
```
Comment (SmallJoker) [inline src/client/game.cpp:1764]: Why would this depend on the cached setting value? This may chance at any time, hence I wonder why this was introduced.

File: src/client/game.cpp [hunk 2]
```diff
@@ -3762,7 +3767,10 @@ void Game::updateFrame(ProfilerGraph *graph, RunStats *stats, f32 dtime,
 	float direct_brightness;
 	bool sunlight_seen;
 
-	if (m_cache_enable_noclip && m_cache_enable_free_move) {
+	// When in noclip mode force same sky brightness as above ground so you
+	// can see properly
+	if (draw_control->allow_noclip && m_cache_enable_free_move &&
```
Comment (SmallJoker) [inline src/client/game.cpp:3772]: Same as above for noclip cache.

**Review by SmallJoker — APPROVED** [review]
comparison


Works.
