### PR TITLE
Disallow formspec debug if the player does not have the debug privilege

### LINKED ISSUE #11689: Everybody can see formspec debug
##### Minetest version
```
Minetest 5.5.0-dev-040aed37a
```

##### OS / Hardware
Operating system: Linux Mint 20
CPU: Intel i7

##### Summary
Players without any privs are able to bring up the debug screen overlay on formspecs. I'm creating a formspec where I'm using a transparent image_button that will be in random locations and the player needs to click on it, they can just hit F5 and instantly see where the button is at. As a work around I suppose I can add some extra buttons so they have to guess between them. With the changes to the debug information displayed in the normal F5 it would be nice if the formspec stuff could get put away behind the same priv.

##### Steps to reproduce
Load a world, view a formspec and tap F5 to bring up the debug overlay thing.

### PR DESCRIPTION
**Pull request by l-koehler**
- Goal of the PR
Disallow players that do not have the "debug" privilege from viewing formspec debug info.
- How does the PR work?
It adds a check for the "debug" privilege before toggling the formspec debug view.
- Does it resolve any reported issue?
Fixes #11689

## To do

Ready for Review.

## How to test

Open the inventory (or any other formspec), press F5 with and without the "debug" privilege.
The debug view should only be toggled with the "debug" privilege.

### CODE REVIEW

File: src/gui/guiFormSpecMenu.cpp [hunk 1]
```diff
@@ -4184,8 +4184,10 @@ bool GUIFormSpecMenu::OnEvent(const SEvent& event)
 			m_client->makeScreenshot();
 		}
 
-		if (event.KeyInput.PressedDown && kp == getKeySetting("keymap_toggle_debug"))
+		if (event.KeyInput.PressedDown && kp == getKeySetting("keymap_toggle_debug") &&
+				(m_client != NULL && m_client->checkPrivilege("debug"))) {
 			m_show_debug = !m_show_debug;
```
Comment (sfan5) [inline src/gui/guiFormSpecMenu.cpp:4189]: there's an edge case here: if the player had the "debug" privilege but it was revoked from him, debug mode will stay enabled

Comment (appgurueu) [reply src/gui/guiFormSpecMenu.cpp:4190]: @l-koehler it's not just about allowing them to disable it: If the priv is revoked, `m_show_debug` should always be set to `false`.

So the logic should go something like this: `if (m_client != NULL && !m_client->checkPrivilege("debug"))) m_show_debug = false; else if (... toggle? ...)  m_show_debug = !m_show_debug;`

**Comment by l-koehler** [comment]
Whenever the debug privilege gets removed, it now tries to disable the debug mode (can't do that when no formspec is open, but that doesn't matter as the debug mode does not persist across different formspecs).

File: src/gui/guiFormSpecMenu.cpp [hunk 2]
```diff
@@ -4184,8 +4184,11 @@ bool GUIFormSpecMenu::OnEvent(const SEvent& event)
 			m_client->makeScreenshot();
 		}
 
-		if (event.KeyInput.PressedDown && kp == getKeySetting("keymap_toggle_debug"))
+		// Allows the user to disable debug mode regardless of privilege
```
Comment (appgurueu) [inline src/gui/guiFormSpecMenu.cpp:4187]:
```suggestion
```

**Review by appgurueu — APPROVED** [review]
Thank you. Code is simple and to the point. Tested, works:

* Host server, join with another client.
* Grant other client debug. Press F5 while in inventory formspec: works.
* Revoke debug while other client has formspec debug enabled. The yellow debug overlays disappear immediately.
* Try turning it on again: Doesn't work, as expected.
* Re-grant privilege. Now it can be turned on again.

**Review by grorp — CHANGES_REQUESTED** [review]
Formspec debug no longer works in the mainmenu
