### PR TITLE
Fix broken coloring of wielditems

### LINKED ISSUE #9941: Wielditem coloring broken with shaders enabled
##### Minetest version
```
Minetest 5.3.0-dev-083b285f4
```

##### Summary

screenshot_20200526_174703

* Item coloring does not work for the wielditem (seen right)
* Firelike nodes are black when wielded (seen left)

both of these issues go away when reverting #9537
<b>this is a regression from 5.2.0</b>

##### Steps to reproduce
Take "Firelike Drawtype Test Node" and "Raillike Drawtype Test Node: rail 3" from devtest's chest and wield them.

### PR DESCRIPTION
**Pull request by dcbrwn**
Fixes #9941

## To do

Ready for Review.

## How to test

Take "Firelike Drawtype Test Node" and "Raillike Drawtype Test Node: rail 3" from devtest's chest and wield them.

### CODE REVIEW

**Comment by dcbrwn** [comment]
Without this patch rail-like is rendered incorrectly, but I'm not sure what caused this bug and how to fix it properly

```patch
Index: src/client/wieldmesh.cpp
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- src/client/wieldmesh.cpp	(revision e61ba49e7c9bd18bf3bcf855de20590077c7fe88)
+++ src/client/wieldmesh.cpp	(date 1590846882767)
@@ -385,6 +385,7 @@
 					changeToMesh(nullptr);
 					break;
 				}
+				case NDT_RAILLIKE:
 				case NDT_PLANTLIKE: {
 					setExtruded(tsrc->getTextureName(f.tiles[0].layers[0].texture_id),
 						tsrc->getTextureName(f.tiles[0].layers[1].texture_id),
```

File: src/client/wieldmesh.cpp [hunk 1]
```diff
@@ -481,9 +485,9 @@ void WieldMeshSceneNode::setNodeLightColor(video::SColor color)
 			video::SMaterial &material = m_meshnode->getMaterial(i);
 			material.EmissiveColor = color;
 		}
-	} else {
-		setColor(color);
 	}
+
+	setColor(color);
```
Comment (dcbrwn) [inline src/client/wieldmesh.cpp:490]: I made this unconditional because otherwise something overwrites colors, or mesh is created asynchronously in separate thread and at the time `WieldMeshSceneNode` constructor finishes, buffers are not there yet. Besides, it was working like this before #9537

**Comment by Wuzzy2** [comment]
Possible conflict with #9299 (not tested, just guessing).

**Comment by dcbrwn** [comment]
@Wuzzy2 I didn't include patch for rail-like meshes into this PR and other changes are very generic and only touch lighting and mesh buffer coloring. So it should probably be just fine.
