### PR TITLE
Fix find_nodes_in_area misbehaving with out-of-map coordinates

### LINKED ISSUE #11769: find_nodes_in_area() volume calculation is off by about four million nodes, can crash or hang Minetest
##### Minetest version
Commit 80d12dbed

##### OS / Hardware
Operating system: unknown
CPU: unknown

##### Summary
Last night, some playful kids crashed Oysterity (running Mineclonia) in two different ways.
You can read all about it here: https://git.minetest.land/Mineclonia/Mineclonia/issues/165

Both crashes contained `find_nodes_in_area(): area volume exceeds allowed value of 4096000`.

@appgurueu suggested the volume calculation is wrong for coordinates exceeding s16 boundaries.

I can prove this with the following mod, the included `/areatest` chat command crashes Minetest.
It also prints out the coordinates that you have to give to `find_nodes_in_area()` to reproduce.

##### Steps to reproduce

1. Enter a minetest world with the `badarea` mod from the following zip file active:

data:application/zip;base64,UEsDBAoAAAAAABuNbFMAAAAAAAAAAAAAAAAIABwAYmFkYXJlYS9VVAkAAxaZjmFWno5hdXgLAAEE6AMAAAToAwAAUEsDBBQAAAAIAOSGbFMsW+VyaAAAAIUAAAAQABwAYmFkYXJlYS9tb2QuY29uZlVUCQADW46OYWSOjmF1eAsAAQToAwAABOgDAAAVjTEKAzEMBHu9QrgP3LlPkfxEZwtskO1D0kGeHwu2GmZ3Jw3GN15USZmgshXtt/c1N00pgbduOFZF/t3L2ELFcLGQlEcoXINQlYXJYi4f+XydOxm8uwT67tonLujxtnQTVuE2aE74A1BLAwQUAAAACAAbjWxTQWLKlQUBAABKAgAAEAAcAGJhZGFyZWEvaW5pdC5sdWFVVAkAAxaZjmEamY5hdXgLAAEE6AMAAAToAwAAlZBBboMwEEXXcIqRVyAZRFu16YazoAl2UkvxODKmMkS5e21kSojURRe29eb/8R+NViSdHFxt5VkNTtqu/0LXG62RRMHQSowy43DLTyP10EJ8nDJUEGpZ5idjwYfy2+t70/DwHD4OHF4aECbPojgFsUpqleQq6Yth/qs7yy6mxwtYFGocgutzq11NLNzAt57D1E4c5naG+2aIo2tFwfQte2dsPYxHZ7F3RWjl6c8y+vW6AyGP47mIpYyldsYXTFT7PU57nCOVTyOg30ZAIf6Rjv4xHf0uPeC0x+d0WpKIRh0G+E05KRIdGSGHTlEXe5dIgHVh/BHRr8hQWbYmSBL5cq3nXuY/UEsBAh4DCgAAAAAAG41sUwAAAAAAAAAAAAAAAAgAGAAAAAAAAAAQAO1BAAAAAGJhZGFyZWEvVVQFAAMWmY5hdXgLAAEE6AMAAAToAwAAUEsBAh4DFAAAAAgA5IZsUyxb5XJoAAAAhQAAABAAGAAAAAAAAQAAAKSBQgAAAGJhZGFyZWEvbW9kLmNvbmZVVAUAA1uOjmF1eAsAAQToAwAABOgDAABQSwECHgMUAAAACAAbjWxTQWLKlQUBAABKAgAAEAAYAAAAAAABAAAApIH0AAAAYmFkYXJlYS9pbml0Lmx1YVVUBQADFpmOYXV4CwABBOgDAAAE6AMAAFBLBQYAAAAAAwADAPoAAABDAgAAAAA=

2. Execute the `/areatest` command.

3. Get a crash similar to the following:

```
2021-11-12 17:41:04: [Server]: areamin	32492	-32508	32752
2021-11-12 17:41:04: [Server]: areamax	32508	-32492	32768
2021-11-12 17:41:04: ERROR[Main]: ServerError: AsyncErr: ServerThread::run Lua: Runtime error from mod 'badarea' in callback on_chat_message(): ...hare/src/games/minetest/bin/../mods/badarea/init.lua:22: find_nodes_in_area(): area volume exceeds allowed value of 4096000
2021-11-12 17:41:04: ERROR[Main]: stack traceback:
2021-11-12 17:41:04: ERROR[Main]: 	[C]: in function 'find_nodes_in_area'
2021-11-12 17:41:04: ERROR[Main]: 	...hare/src/games/minetest/bin/../mods/badarea/init.lua:22: in function 'func'
2021-11-12 17:41:04: ERROR[Main]: 	...hare/src/games/minetest/bin/../builtin/game/chat.lua:79: in function '?'
2021-11-12 17:41:04: ERROR[Main]: 	.../src/games/minetest/bin/../builtin/game/register.lua:425: in function <.../src/games/minetest/bin/../builtin/game/register.lua:409>
```

### PR DESCRIPTION
**Pull request by sfan5**
fixes #11769

## To do

This PR is a Ready for Review.

## How to test

```lua
core.register_chatcommand("test", {
	func = function(name, param)
		local areamin = vector.new(32492, -32508, 32752)
		local areamax = vector.new(32508, -32492, 32768)
		minetest.find_nodes_in_area(areamin, areamax, "air")
	end,
})
```

should silently do nothing

### CODE REVIEW

File: src/script/lua_api/l_env.cpp [hunk 1]
```diff
@@ -880,6 +880,21 @@ int ModApiEnvMod::l_find_node_near(lua_State *L)
...
+static void checkArea(v3s16 &minp, v3s16 &maxp)
+{
+	auto volume = VoxelArea(minp, maxp).getVolume();
+	// Volume limit equal to 8 default mapchunks, (80 * 2) ^ 3 = 4,096,000
+	if (volume > 4096000) {
+		throw LuaError("Area volume exceeds allowed value of 4096000");
+	}
+
+	// Clamp to map range to avoid problems
+#define CLAMP(arg) core::clamp(arg, (s16)-MAX_MAP_GENERATION_LIMIT, (s16)MAX_MAP_GENERATION_LIMIT)
```
Comment (appgurueu) [inline src/script/lua_api/l_env.cpp:892]: Generation limit? Shouldn't this be the map limit?

Comment (sfan5) [reply src/script/lua_api/l_env.cpp:892]: This is the map limit. No block are created beyond these positions regardless of any config.

Comment (appgurueu) [reply src/script/lua_api/l_env.cpp:892]: Then that variable is named misleadingly... That's for another PR to fix though.

Comment (erlehmann) [reply src/script/lua_api/l_env.cpp:892]: MAX_MAP_GENERATION_LIMIT is 31000 btw.

Comment (erlehmann) [reply src/script/lua_api/l_env.cpp:892]: I said it on IRC and I will say it again here: **Please do not re-use MAX_MAP_GENERATION_LIMIT.**

This is dangerous.

Comment (erlehmann) [reply src/script/lua_api/l_env.cpp:892]: Empirically, the actual limit of where blocks can exist without crashing the game seems to be *at least* up to x=32687.

This might cause mapgen bugs though, it is *way* too close to the actual limit.

Comment (erlehmann) [reply src/script/lua_api/l_env.cpp:892]: I have verified that minetest.find_nodes_in_area() is used in MineClone2 and Mineclonia mapgen code.

Putting the clamp limit further out (at the exact interval I specified in the bug report) avoids having bugs at the edges.

Comment (erlehmann) [reply src/script/lua_api/l_env.cpp:892]: > This is the map limit. No blocks are created beyond these positions regardless of any config.
> Then that variable is named misleadingly... That's for another PR to fix though.

Actually, @sfan5 is reusing a variable here that should not be reused for this purpose IMO.

The crash and hang I reported happen at the boundaries of s16, not at mapgen boundaries.

By making this function misbehave at mapgen boundaries, it will affect Lua mapgens.

Comment (sfan5) [reply src/script/lua_api/l_env.cpp:892]: I have verified that the map ends at exactly -30912 and 30928 with default settings (so no mapgen limit).
There is no argument to be made here why this function must work beyond -/+31000.

Comment (erlehmann) [reply src/script/lua_api/l_env.cpp:892]: > I have verified that the map ends at exactly -30912 and 30928 with default settings (so no mapgen limit).

That is the visible part of the map. We both know that that there is more after it, presumably up until 31008.

> There is no argument to be made here why this function must work beyond -/+31000.

In vanilla client it is actually possible to have a visible world that ends at x=31007.

It still seems possible to place blocks outside of that, but it is very very crashy there.

It does not matter what was advertised, though. I do not want to make the map bigger, I just want any sketchy behavior to be far away from where the actual world is or where mapgen is doing anything.

My argument in abstract would be “it is wrong to not use the boundaries of s16, but some arbitrary other boundary that has nothing to do with the function logic or the crash encoutered *and is far too close to where actual code could legitimately invoke it and trip over itself*”.

Comment (erlehmann) [reply src/script/lua_api/l_env.cpp:892]: > It still seems possible to place blocks outside of that, but it is very very crashy there.

To clarify: It is crashy when code assumes the 31000 boundary, but (Lua?) mapgen functions try to reach beyond it.

Basically, if the mapgen stops at 31000, but a function – like minetest.find_nodes_in_area() – is called in Lua mapgens, it is not exactly safe to make it misbehave at exactly that boundary. It should misbehave far away from the boundary.

@sfan5 I think the fundamental difference is that you evaluate the function in terms of “logically, should anything be there?” and I evaluate the function in terms of “how can I avoid future bugs (e.g. crashes)”.

Of course nothing *should* be there! But a) there can be something there b) the whole bug report was made initially because some clowns found out how to trigger weird behaviour out of bounds of s16 and not out of bounds of mapgen.

So choosing 31000 seems logical, but will likely lead to further bugs in exactly the space between ±31000 and the boundaries of s16. I want to eliminate that whole category of bugs by making that space as small as possible and putting it as far as possible from legit mapgen activity.

Comment (erlehmann) [inline src/script/lua_api/l_env.cpp:892]: Regardless of the boundaries you choose, I think Minetest should output a warning here if the clamping happens, to detect misbehaving mods, mapgens, and players.

Comment (erlehmann) [inline src/script/lua_api/l_env.cpp:892]: I have figured out that for Lua selftest purposes related to the Lua workaround for the crash this PR is addressing I require an area which is slightly out of MAX_MAP_GENERATION_LIMIT, but can hold nodes. This area exists in current Minetest and this patch seems to introduce an area in which unit tests misbehave.

I once again want to urge you to not re-use MAX_MAP_GENERATION_LIMIT here – it has nothing to do with the crash and is a solution that is simple, obvious, and wrong. Use the boundaries of the underlying s16 data type please to avoid both creating and masking additional bugs.

**Sigh.**

Comment (SmallJoker) [reply src/script/lua_api/l_env.cpp:892]: There's no point in supporting map areas outside this area. `MAX_MAP_GENERATION_LIMIT` was exactly created to avoid such over- and underflow issues in the map generation. Hence it makes perfect sense to also apply those rules to the rest of the API. You can still limit the map generation further using the map_meta.txt settings.

The overflow is likely to happen in 
```C++
		for (p.X = minp.X; p.X <= maxp.X; p.X++)
		for (p.Y = minp.Y; p.Y <= maxp.Y; p.Y++)
		for (p.Z = minp.Z; p.Z <= maxp.Z; p.Z++) {
```

where maxp equals S16_MAX. There must be no area outside of `MAX_MAP_GENERATION_LIMIT`, hence this is a sane solution.

Comment (erlehmann) [reply src/script/lua_api/l_env.cpp:892]: > There's no point in supporting map areas outside this area.

In abstract: By clamping at anything else than the boundaries of the underlying data type you guarantee that Minetest has a function that behaves well only for a subset of the values representable by the data type.

One problem resulting from such a construction (boundaries do not align with underlying data type) exists already – the engine can return positions for players that make it fall over and die when those are given to a Lua function that takes a position: https://github.com/minetest/minetest/issues/11742?

I am trying to prevent more of these kind of mistakes that are essentially type errors.

> MAX_MAP_GENERATION_LIMIT was exactly created to avoid such over- and underflow issues in the map generation.

@sfan5 showed me a comment about that already. I have verified that stopping at MAX_MAP_GENERATION_LIMIT avoids encountering a bunch of overflows during map generation. The problem here is that these overflows still exist and can be abused by attackers if the functions can be called from outside mapgen.

**Masking, i.e. not triggering bugs in mapgen does not magically make them vanish.**

> There must be no area outside of MAX_MAP_GENERATION_LIMIT, hence this is a sane solution.

Ex falso quodlibet – tHe above statement is about as true as the following:

If the Eiffel tower is located in New York, the moon is made out of cheese.

Comment (sfan5) [reply src/script/lua_api/l_env.cpp:892]: > Another problem resulting from such a construction (boundaries do not align with underlying data type) has been found already: #11742

No. The problem highlighted by the other issue exists *because* there is no clamping for the player positions (you also said you don't like that solution).

> The problem here is that these overflows still exist and can be abused by attackers if the functions can be called from outside mapgen.

What does that mean?
The behaviour of `find_nodes_in_area` is exactly the same with this PR inside and outside of mapgen so any claimed difference that could be abused does not exist.

> Ex [...]

Is that a magic chant that allows you to discard an argument without losing a single word on its contents?
Gotta remember that one.

Comment (appgurueu) [reply src/script/lua_api/l_env.cpp:892]: > Is that a magic chant that allows you to discard an argument without losing a single word on its contents?
Gotta remember that one.

It's literally just saying that a logical implication based on a false premise allows you to conclude anything. In other words, erlehmann is saying that

> There must be no area outside of MAX_MAP_GENERATION_LIMIT

is false, as clearly placing nodes there is currently possible for malicious actors; and therefore the conclusion

> hence this is a sane solution.

can't be drawn.

Comment (erlehmann) [reply src/script/lua_api/l_env.cpp:892]: > unnecessarily quirky

Sorry for that, I think I am just overly annoyed that ppl repeat that stuff.

> clearly placing nodes there is currently possible for malicious actors

Worse though – even if it was not possible, they do not even need to.

(It is possible though and I know another crash that I can trigger.)

Comment (appgurueu) [reply src/script/lua_api/l_env.cpp:892]: Perhaps the proper solution is to fix this, making it impossible for players to interact with area outside of `MAX_MAP_GENERATION_LIMIT`?

Comment (sfan5) [reply src/script/lua_api/l_env.cpp:892]: > It's literally just saying that a logical implication based on a false premise allows you to conclude anything

Yes, I know what it means and that it's an axiom. But I didn't see anything about *why* the premise is supposed to be incorrect.
Although nodes could theoretically exist up to (+/-)31007, in my testing the map always ends far before 31000.

**Review by nerzhul — APPROVED** [review]
okay for me, coding errors on boundaries should be thrown. preparing irc drama reading :D

**Review by SmallJoker — APPROVED** [review]
Works, but I did find that the volume check is also horribly slow when checking a pane of total 32001² nodes like here:
```Lua
		local areamin = vector.new(-32492, -32508, 32752)
		local areamax = vector.new(32508, -32492, 32768)
```
After limit function:
```
minp = (-31000,-31000,-31000)
maxp = (31000,-31000,31000)
```

It might make sense to limit by (80 * 2) nodes in each coordinate rather than by volume.
That however is a task for another PR. This one works as expected :+1:
