### PR TITLE
Android progressbar fix

### LINKED ISSUE #5599: Android: loading bar too little
The android bar is too little on Android we should change its size

screenshot_2017-04-16-09-41-16

### PR DESCRIPTION
**Pull request by nerzhul**
Before
screenshot_2017-04-16-09-41-16

After
screenshot_2017-04-16-13-31-19

Fixed #5599

### CODE REVIEW

**Comment by nerzhul** [comment]
#5403

**Comment by celeron55** [comment]
+1

Here's the madness of trying to create a reasonable fix: http://irc.minetest.net/minetest-dev/2017-04-16#i_4877736

File: src/client/tile.cpp [hunk 1]
```diff
@@ -1124,6 +1122,15 @@ video::IImage* TextureSource::generateImage(const std::string &name)
  * @param driver driver to use for image operations
  * @return image or copy of image aligned to npot2
  */
+
+inline u16 get_GL_major_version()
+{
+	const GLubyte *gl_version = glGetString(GL_VERSION);
+	std::string gl_ver((const char *)gl_version);
+	u16 GL_version = stoi(gl_ver.substr(0,1));
+	return GL_version;
```
Comment (sfan5) [inline src/client/tile.cpp]: I know very well that this makes no different perf-wise, but since it's just 1 char you could just:
`return (u16) (gl_version[0] - '0');`

File: src/client/tile.cpp [hunk 2]
```diff
@@ -1134,7 +1141,10 @@ video::IImage * Align2Npot2(video::IImage * image,
 	core::dimension2d<u32> dim = image->getDimension();
 
 	std::string extensions = (char*) glGetString(GL_EXTENSIONS);
-	if (extensions.find("GL_OES_texture_npot") != std::string::npos) {
+
+	// Only GLES2 is trusted to correctly report npot support
```
Comment (sfan5) [inline src/client/tile.cpp]: so in case an Android device only support gles1 we assume npot is needed, correct?

File: src/drawscene.cpp [hunk 3]
```diff
@@ -625,27 +626,21 @@ void draw_load_screen(const std::wstring &text, IrrlichtDevice* device,
...
 			const core::dimension2d<u32> &img_size = progress_img_bg->getSize();
+#ifndef __ANDROID__
 			u32 imgW = rangelim(img_size.Width, 200, 600);
 			u32 imgH = rangelim(img_size.Height, 24, 72);
+#else
+			u32 imgW = rangelim(img_size.Width, 256, 1024);
+			u32 imgH = rangelim(img_size.Height, 48, 128);
+			float imgRatio = (float) imgH / imgW;
+			imgW = screensize.X / 2.2f;
+			imgH = floor(imgW * imgRatio);
```
Comment (sfan5) [inline src/drawscene.cpp]: add a comment what this does/why it's necessary

File: src/client/tile.cpp (hunk 2 above)
Comment (nerzhul) [inline src/client/tile.cpp]: it seems it's the case, on my phone without verifying GL version it was problematic

**Comment by celeron55** [comment]
New changes look ok
