### PR TITLE
Formspec: Move tooltip above cursor when lacking space

### LINKED ISSUE #15467: Clicking on tooltip closes formspec
### Luanti version

```true
Luanti 5.11.0-dev-946b3a422-dirty
OpenGL 4.6.0
```

### Irrlicht device

X11

### Operating system and version

Linux Mint 20.3 Cinnamon

### CPU model

Intel i7-8700K

### GPU model

Nvidia GeForce RTX 3060

### Active renderer

OpenGL 4.6.0

### Summary

If you have a small formspec and a large tooltip, or a formspec anchored to a corner of a window so the tooltip can't move out of the cursors way when you click on the tooltip the formspec will close.

### Steps to reproduce

In Devtest open the inventory and make the game screen tiny. Take an item will a long description, such as the mese pickaxe and put it in the lowest right inventory slot. As you mouse-over the slot the description/tooltip will display. Click on the tooltip and watch the formspec close.
screenshot_20241121_180605
I realize that having a screen that tiny is silly, but I first experienced the problem when working on my game for the game jam. I have a formspec that shows in the lower right corner of the screen, and the button has a tooltip. If you accidentally click on the tooltip it closes the formspec, but doesn't call the button's action.
screenshot_20241121_180656

### PR DESCRIPTION
**Pull request by SmallJoker**
Fixes #15467

## To do

This PR is Ready for Review.

## How to test

Test script N° 174 (for my reference)

```Lua
local lorem = [[
Lorem ipsum dolor sit amet,
consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et
dolore magna aliquyam erat,
sed diam voluptua.
At vero eos et accusam
et justo duo
dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem
ipsum dolor sit amet.
]]

core.register_chatcommand("t", {
	func = function(name)
		local function btn(x, y)
			return (
				("button[%.1f,%.1f;%d,%d;btn_%d_%d;%d %d]"):format(x*3.5,y*1.5, 3,1, x,y, x,y)
				..
				("tooltip[btn_%d_%d;%s;green;black]"):format(x,y, lorem)
			)
		end
		local fs = {
			"size[14,8;true]"
		}
		for y = 0, 4 do
		for x = 0, 4 do
			fs[#fs + 1] = btn(x, y)
		end
		end
		core.show_formspec(name, "lab:test", table.concat(fs))
	end
})
```

1. Open `/t`
2. Have a small game window
3. Look at the tooltip and try to click it

### CODE REVIEW

File: src/gui/guiFormSpecMenu.cpp [hunk 1]
```diff
@@ -3610,10 +3610,25 @@ void GUIFormSpecMenu::showTooltip(const std::wstring &text,
...
-	if (tooltip_x + tooltip_width > (s32)screenSize.X)
-		tooltip_x = (s32)screenSize.X - tooltip_width  - m_btn_height;
-	if (tooltip_y + tooltip_height > (s32)screenSize.Y)
-		tooltip_y = (s32)screenSize.Y - tooltip_height - m_btn_height;
+	// Bottom/Left limited positions (if the tooltip is too far out)
+	s32 tooltip_x_alt = (s32)screenSize.X - tooltip_width  - m_btn_height;
+	s32 tooltip_y_alt = (s32)screenSize.Y - tooltip_height - m_btn_height;
+
+	int collision = (tooltip_x_alt < tooltip_x) + 2 * (tooltip_y_alt < tooltip_y);
+	switch (collision) {
```
Comment (SmallJoker) [inline src/gui/guiFormSpecMenu.cpp:3618]: Hey please don't be mad. This is the most beautiful code I could think of!
