### PR TITLE
Schematic: Properly deal with before/after node resolving and document

### LINKED ISSUE #10995: Crash in serialize_schematic when cached biome schematic is used
##### Minetest version
```
Minetest 5.4.0 (Linux)
Using Irrlicht 1.8.4
Using LuaJIT 2.1.0-beta3
BUILD_TYPE=Release
RUN_IN_PLACE=0
USE_CURL=1
USE_GETTEXT=1
USE_SOUND=1
USE_FREETYPE=1
STATIC_SHAREDIR="/usr/share/minetest"
STATIC_LOCALEDIR="/usr/share/locale"
```
##### OS / Hardware
Operating system: Linux 5.4.0-65-generic Ubuntu SMP x86_64 x86_64 x86_64 GNU/Linux
CPU: Intel(R) Core(TM) i7-5600U CPU @ 2.60GHz

GPU model:
OpenGL version:

##### Summary
I join the minetest 5.4 (release), installed over apt using this PPA: https://launchpad.net/~minetestdevs/+archive/ubuntu/stable, with the MineClone2 subgame (latest git version),  then I'm able to play for a few seconds, then the game crashes with SIGSEGV. It works fine when I use a run-in-place self compiled build, that's why I suspect LuaJIT. It has caused problems with MCL2 earlier: https://git.minetest.land/MineClone2/MineClone2/issues/1128

The problems occur when using a local server / singleplayer. They do not occur when I join one of my public servers, using a RUN_IN_PLACE build as well. The problem did not occur when using the v7 mapgen instead of carpathian, but at some point with v7 the server freezed - the client unaffected, and after about 15 seconds it ran smoothly again the logs were showing
```
2021-02-24 17:07:33: ACTION[Emerge-0]: [mcl_dungeons] Placing new dungeon at (-169,-48,-212)
2021-02-24 17:07:33: ACTION[Emerge-0]: [mcl_dungeons] Placing new dungeon at (-169,-48,-212)
2021-02-24 17:07:33: ACTION[Emerge-0]: [mcl_dungeons] Placing new dungeon at (-137,-43,-259)
2021-02-24 17:07:33: ACTION[Emerge-0]: [mcl_dungeons] Placing new dungeon at (-137,-43,-259)
2021-02-24 17:07:33: ACTION[Emerge-0]: [mcl_dungeons] Placing new dungeon at (-132,-51,-259)
2021-02-24 17:07:33: ACTION[Emerge-0]: [mcl_dungeons] Placing new dungeon at (-132,-51,-259)
2021-02-24 17:07:34: WARNING[Server]: active block modifiers took 51ms (processed 393 of 455 active blocks)
2021-02-24 17:07:34: ACTION[Emerge-0]: [mcl_dungeons] Placing new dungeon at (-176,28,-318)
2021-02-24 17:07:34: ACTION[Emerge-0]: [mcl_dungeons] Placing new dungeon at (7,-24,-296)
2021-02-24 17:07:34: WARNING[Server]: active block modifiers took 51ms (processed 259 of 455 active blocks)
2021-02-24 17:07:36: WARNING[Server]: active block modifiers took 51ms (processed 297 of 475 active blocks)
2021-02-24 17:07:37: WARNING[Server]: active block modifiers took 51ms (processed 398 of 475 active blocks)
2021-02-24 17:07:38: WARNING[Server]: active block modifiers took 51ms (processed 138 of 475 active blocks)
2021-02-24 17:08:10: WARNING[Emerge-0]: Map::getNodeMetadata(): Block not found
```
With the last line repeated about 1000 times (that is not an exaggeration). This might be a MineClone2 problem tho. 

gdb backtrace when using caparthian:
```
__memmove_avx_unaligned_erms () at ../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S:365
365     ../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S: No such file or directory.
(gdb) back
#0  __memmove_avx_unaligned_erms () at ../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S:365
#1  0x00007ffff72a2648 in std::basic_streambuf<char, std::char_traits<char> >::xsputn(char const*, long) () from /lib/x86_64-linux-gnu/libstdc++.so.6
#2  0x00007ffff72949b4 in std::basic_ostream<char, std::char_traits<char> >& std::__ostream_insert<char, std::char_traits<char> >(std::basic_ostream<char, std::char_traits<char> >&, char const*, long) () from /lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x00005555558d550f in ?? ()
#4  0x0000555555985984 in ?? ()
#5  0x00005555559335ca in ?? ()
#6  0x00007ffff760d017 in ?? () from /lib/x86_64-linux-gnu/libluajit-5.1.so.2
#7  0x00007ffff765b4a4 in lua_pcall () from /lib/x86_64-linux-gnu/libluajit-5.1.so.2
#8  0x000055555595d7da in ?? ()
#9  0x0000555555ba224e in ?? ()
#10 0x0000555555bab0ab in ?? ()
#11 0x0000555555bb1f62 in ?? ()
#12 0x0000555555b9882b in ?? ()
#13 0x0000555555b9b0de in ?? ()
#14 0x00005555559ceb97 in ?? ()
#15 0x00007ffff7237d84 in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#16 0x00007ffff75ea609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#17 0x00007ffff6f27293 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

When I started minetest with --server and joined it (also carpathian), a memory leak happened and the process was automatically killed - it did not happen before I joined tho.

A similar SEGFAULT also happened to one of my servers using the v7 mapgen, everytime a specific player joined the game this happened:
```
__memcpy_ssse3 () at ../sysdeps/x86_64/multiarch/memcpy-ssse3.S:104
104     ../sysdeps/x86_64/multiarch/memcpy-ssse3.S: No such file or directory.
(gdb) back
#0  __memcpy_ssse3 () at ../sysdeps/x86_64/multiarch/memcpy-ssse3.S:104
#1  0x00007ffff7c2e648 in std::basic_streambuf<char, std::char_traits<char> >::xsputn(char const*, long) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#2  0x00007ffff7c209b4 in std::basic_ostream<char, std::char_traits<char> >& std::__ostream_insert<char, std::char_traits<char> >(std::basic_ostream<char, std::char_traits<char> >&, char const*, long) ()
   from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x00005555556820f9 in Schematic::serializeToLua (this=0x5555577fcb80, os=0x7fffefffd920, names=std::vector of length 0, capacity 16, use_comments=false, indent_spaces=0)
    at /home/fleckenstein/minetest/src/mapgen/mg_schematic.cpp:441
#4  0x000055555573beda in ModApiMapgen::l_serialize_schematic (L=0x555555c1acd0) at /home/fleckenstein/minetest/src/script/lua_api/l_mapgen.cpp:1745
#5  0x000055555595de37 in luaD_precall (L=0x555555c1acd0, func=0x555559541b80, nresults=1) at /home/fleckenstein/minetest/lib/lua/src/ldo.c:320
#6  0x00005555559744d0 in luaV_execute (L=0x555555c1acd0, nexeccalls=5) at /home/fleckenstein/minetest/lib/lua/src/lvm.c:591
#7  0x000055555595e0ea in luaD_call (L=0x555555c1acd0, func=0x5555595418c0, nResults=0) at /home/fleckenstein/minetest/lib/lua/src/ldo.c:378
#8  0x00005555559559cd in f_call (L=0x555555c1acd0, ud=0x7fffefffe100) at /home/fleckenstein/minetest/lib/lua/src/lapi.c:800
#9  0x000055555595d0f4 in luaD_rawrunprotected (L=0x555555c1acd0, f=0x555555955994 <f_call>, ud=0x7fffefffe100) at /home/fleckenstein/minetest/lib/lua/src/ldo.c:116
#10 0x000055555595e4f4 in luaD_pcall (L=0x555555c1acd0, func=0x555555955994 <f_call>, u=0x7fffefffe100, old_top=32, ef=16) at /home/fleckenstein/minetest/lib/lua/src/ldo.c:464
#11 0x0000555555955a8f in lua_pcall (L=0x555555c1acd0, nargs=2, nresults=0, errfunc=1) at /home/fleckenstein/minetest/lib/lua/src/lapi.c:821
#12 0x000055555571f2f1 in LuaLBM::trigger (this=0x55555aaaa1e0, env=0x55555ab10e20, p=..., n=...) at /home/fleckenstein/minetest/src/script/lua_api/l_env.cpp:136
#13 0x00005555558d7e79 in LBMManager::applyLBMs (this=0x55555ab11028, env=0x55555ab10e20, block=0x7fffe0024a40, stamp=9083373) at /home/fleckenstein/minetest/src/serverenvironment.cpp:284
#14 0x00005555558db6ed in ServerEnvironment::activateBlock (this=0x55555ab10e20, block=0x7fffe0024a40, additional_dtime=0) at /home/fleckenstein/minetest/src/serverenvironment.cpp:973
#15 0x00005555558dd8c8 in ServerEnvironment::step (this=0x55555ab10e20, dtime=0.0900000036) at /home/fleckenstein/minetest/src/serverenvironment.cpp:1378
#16 0x00005555558aa582 in Server::AsyncRunStep (this=0x7fffffffd430, initial_step=false) at /home/fleckenstein/minetest/src/server.cpp:600
#17 0x00005555558a612a in ServerThread::run (this=0x555555bdea20) at /home/fleckenstein/minetest/src/server.cpp:110
#18 0x00005555557831d1 in Thread::threadProc (thr=0x555555bdea20) at /home/fleckenstein/minetest/src/threading/thread.cpp:188
#19 0x000055555578411b in std::__invoke_impl<void, void (*)(Thread*), Thread*> (__f=@0x55555aaaa050: 0x55555578315e <Thread::threadProc(Thread*)>) at /usr/include/c++/9/bits/invoke.h:60
#20 0x0000555555784067 in std::__invoke<void (*)(Thread*), Thread*> (__fn=@0x55555aaaa050: 0x55555578315e <Thread::threadProc(Thread*)>) at /usr/include/c++/9/bits/invoke.h:95
#21 0x0000555555783fb7 in std::thread::_Invoker<std::tuple<void (*)(Thread*), Thread*> >::_M_invoke<0ul, 1ul> (this=0x55555aaaa048) at /usr/include/c++/9/thread:244
#22 0x0000555555783f59 in std::thread::_Invoker<std::tuple<void (*)(Thread*), Thread*> >::operator() (this=0x55555aaaa048) at /usr/include/c++/9/thread:251
#23 0x0000555555783f2a in std::thread::_State_impl<std::thread::_Invoker<std::tuple<void (*)(Thread*), Thread*> > >::_M_run (this=0x55555aaaa040) at /usr/include/c++/9/thread:195
#24 0x00007ffff7bc3d84 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#25 0x00007ffff7dd8609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#26 0x00007ffff78b3293 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```
minetest version of the server:
```
Minetest 5.4.0-dev-debug-e86c93f0b (Linux)
BUILD_TYPE=Debug
RUN_IN_PLACE=1
USE_GETTEXT=0
USE_SOUND=0
USE_CURL=1
USE_FREETYPE=1
USE_LUAJIT=0
STATIC_SHAREDIR="."
```
The OS of the VPS is the exact same as on my PC, and the CPU is `QEMU Virtual CPU version 2.5+`.

Hmm, after looking at the gdb backtrace of the server, it seems like it is actually the same as the one in the Release - so it is probably not the fault of the carpathian mapgen or LuaJIT. Note that these errors happened on the server for the first time after some MineClone2 mapgen changes.

### PR DESCRIPTION
**Pull request by SmallJoker**
Fixes #10995

This fixes an out-of-bounds access crash when a biome-specific decoration is serialized to Lua manually afterwards.

1. The node names are resolved on load (`loadSchematicFromFile`. `ndef` is non-NULL) to content IDs
2. Node names are no longer required [by mapgen] and are dropped in `NodeResolver::nodeResolveInternal`
3. The mod loads the cached schematic (same path) which does not have any node name mapping
4. Serialize to Lua fails because the vector is accessed out-of-range

Alternatives:
 * Keep the content_t/node name vector after node resolving -> slightly higher RAM usage depending on the content ID value
 * Re-write this somehow so that the node names are kept more efficiently (map?)
 * Drop use of `m_nodenames` within serialization and rely on NodeDefManager

## To do

This PR is Ready for Review.

## How to test

1. MineClone 2 world, repository commit roughly 9f66238aa (Feb 27) or earlier
2. This testing mod, depends on `mcl_structures`:
   * https://github.com/minetest/minetest/issues/10995#issuecomment-787438358
3. Execute `/s`
4. Worldedit + `//mtschemecreate filename`
5. Change `//pos1` location
6. `//mtschemplace filename`

### CODE REVIEW

File: src/mapgen/mg_schematic.cpp [hunk 1]
```diff
@@ -436,9 +436,20 @@ bool Schematic::serializeToLua(std::ostream *os,
...
+
+				ss << indent << indent << "{" << "name=\"";
+
+				if (c < names.size()) {
+					// Get node name from cache
+					ss << names[c];
+				} else {
+					// If cache is unavailable (biome decoration)
+					FATAL_ERROR_IF(m_ndef == nullptr, "Invalid node list and missing NodeDefManager");
+					ss << m_ndef->get(c).name;
```
Comment (sfan5) [inline src/mapgen/mg_schematic.cpp:449]: IMO it'd be okay to fill up names again once at the beginning of `serializeToLua` if it's detected that they are missing

Comment (SmallJoker) [reply src/mapgen/mg_schematic.cpp:449]: I could copy the `names` vector and rebuild `m_nodenames` but these serialization functions are currently designed to take an external list of node names rather than relying on their own.

Comment (sfan5) [reply src/mapgen/mg_schematic.cpp:449]: Oh I thought the names vector belonged to the `Schematic` class. This is weird.
Who calls `serializeToLua`? Can we do it there?

Comment (SmallJoker) [reply src/mapgen/mg_schematic.cpp:461]: When this case is reached, the only available content_t -> node name conversion is NodeDefResolver. The other case is a "condensed" (sequential numbered) map of node IDs which requires m_nodenames to look up the names.

**Comment by SmallJoker** [comment]
How can I test whether the MTS files are saved and loaded (= placed) correctly?

**Comment by SmallJoker** [comment]
Tested Mts saving (from map) and placing using worldedit. Cross-tested with old/existing Mts files to ensure it works.
The PR is now significantly larger to properly deal with before/after node resolving cases.

File: src/mapgen/mg_schematic.cpp [hunk 2]
```diff
@@ -584,26 +606,28 @@ void Schematic::applyProbabilities(v3s16 p0,
 }
 
 
-void generate_nodelist_and_update_ids(MapNode *nodes, size_t nodecount,
-	std::vector<std::string> *usednodes, const NodeDefManager *ndef)
+void Schematic::condenseContentIds(size_t nodecount)
```
Comment (sfan5) [inline src/mapgen/mg_schematic.cpp:609]: is there any reason this would not be called on the entire volume?
If not I suggest removing this parameter.

File: src/mapgen/mg_schematic.cpp [hunk 3]
```diff
@@ -584,26 +606,28 @@ void Schematic::applyProbabilities(v3s16 p0,
...
 
+	// Reset node resolve fields
+	NodeResolver::reset();
+
 	for (size_t i = 0; i != nodecount; i++) {
 		content_t id;
-		content_t c = nodes[i].getContent();
+		content_t c = schemdata[i].getContent();
 
 		std::unordered_map<content_t, content_t>::const_iterator it = nodeidmap.find(c);
```
Comment (sfan5) [inline src/mapgen/mg_schematic.cpp:621]:
```suggestion
		auto it = nodeidmap.find(c);
```

File: src/mapgen/mg_schematic.cpp [hunk 4]
```diff
@@ -584,26 +606,28 @@ void Schematic::applyProbabilities(v3s16 p0,
...
 		if (it == nodeidmap.end()) {
 			id = numids;
 			numids++;
 
-			usednodes->push_back(ndef->get(c).name);
+			m_nodenames.push_back(m_ndef->get(c).name);
 			nodeidmap.insert(std::make_pair(c, id));
```
Comment (sfan5) [inline src/mapgen/mg_schematic.cpp:627]:
```suggestion
			nodeidmap.emplace(c, id);
```
C++11 :)

**Review by sfan5 — COMMENTED** [review]
Looks good other than that.

**Comment by SmallJoker** [comment]
Comments addressed.
