### PR TITLE
Apply camera smoothing to 'not touching_ground' stepheight

### LINKED ISSUE #9725: Player noticeably twitches when jumping up a node
##### Minetest version

```
5.3.0-dev-6cf15cf8
```

##### Summary

The player seems to twitch every time I jump up a one node height. This happens consistently, every single time, and it's pretty easy to reproduce. *Occasionally*, the player twitches twice when climbing an 1-node high L-shaped corner.

I suspect this might be introduced by the recent collision fixes.

@TheTermos 

##### Steps to reproduce

- Approach a one-node jump.
- Make sure you're touching the side of the node you're going to jump on.
- Press jump and forward at the same time.
- Observe a twitch mid-jump.

### PR DESCRIPTION
**Pull request by paramat**
Fixes #9725 
~No problems seen on a quick test, but needs consideration and testing for possible problematic side-effects. I cannot yet think of any problems caused.~
See https://github.com/minetest/minetest/issues/9725#issuecomment-642245930 for more details on why the bug occurred and what this fix does.

I tested using the method shown in https://github.com/minetest/minetest/issues/9725#issuecomment-640130523
The player model seen in 3rd person now twitches upwards when jumping up the full node, this indicates that camera smoothing is now functional in that situation.
In 1st person, the sharp camera movement no longer happens.

The code i am changing here is 8 years old. It may have been written before air stepheight existed, such that the author thought camera smoothing was not necessary when the player was in air, but of course it is necessary if we have air stepheight.

### CODE REVIEW

**Comment by paramat** [comment]
@TheTermos any input on that?
I am not clear on how 'touching ground' has changed recently.
The sharp camera movement due to air stepheight started happening a few weeks ago, i am assuming due to changes to collision code.
Relevant comment: https://github.com/minetest/minetest/issues/9725#issuecomment-617671568
> This behavior was intended by whomever coded that part in localplayer.cpp, stepheight is supposed to be 0.2BS when player is in air, except before it didn't always work as intended because of touching_ground being broken.

My impression (i might be wrong) is that the air stepheight of 0.2 nodes has always happened, but previously the camera movement was smoothed due to 'touching ground' being true in mid-jump if you are pressed up against the node.

This comment https://github.com/minetest/minetest/issues/9725#issuecomment-640133905 suggests that air stepheight has always happened, as it seems to explain why a player is able to rapidly run up a slope of full nodes with 1 jump per node, or run over a hole in the ground, or walk across a diagonal slope without fallin ginto the holes.
That comment also explains why it would be bad to remove air stepheight.
So, it seems that air stepheight has always happened, it has not just staretd happening now.

Well, we can find out by testing whether maximum jump height has changed in MT master compared to MT 5.1.0/5.2.0.

**Comment by TheTermos** [comment]
> My impression (i might be wrong) is that the air stepheight of 0.2 nodes has always happened,

Don't know about always, but for as long as I've been around, yes it has.

> previously the camera movement was smoothed due to 'touching ground' being true in mid-jump if you are pressed up against the node.

I haven't investigated the camera so I'm not sure that's the cause, but 'touching ground' used to be true up to 0.15 BS above/below surface, so that's a possibility.

> Since `touching_ground` is now slightly different (is it?) than before, does that mean the player can use step-up in situations where it was not possible before?

No, step up doesn't use touching_ground, which is calculated only after any step up processing.

**Comment by sfan5** [comment]
> My impression (i might be wrong) is that the air stepheight of 0.2 nodes has always happened, but previously the camera movement was smoothed due to 'touching ground' being true in mid-jump if you are pressed up against the node.

This is also what I was thinking, just wanted to confirm it.

> No, step up doesn't use touching_ground, which is calculated only after any step up processing.

Not directly, but stepheight depends on whether you are touching ground:
(getStepHeight returns `0.6f * BS` in minetest_game)
https://github.com/minetest/minetest/blob/80d9e9c1834fdc78588ffe2842766c0177227786/src/client/localplayer.cpp#L290-L291

Does this make any difference with the new collision changes?

**Comment by TheTermos** [comment]
The only difference I can think of is before stepheight could potentially be erroneously set to 0.6 while in air.

**Comment by paramat** [comment]
Thanks for input.
> My question regarding the whole "new" jumping behaviour would be:
Since touching_ground is now slightly different (is it?) than before, does that mean the player can use step-up in situations where it was not possible before?
If not then this PR sounds like the proper fix for #9725.

I think removing the 'touching ground' condition for camera smoothing (as this PR does) is probably necessary whatever the situation is, because 'touching ground' is clearly false when air step-up happens onto a full node, because camera smoothing does not happen.

But of course, more investigation of actual movement is needed, and changes to it may be needed.
I do not want this PR to get too distracted by that though, we probably do not have time to investigate actual movement, make and test changes, before 5.3.0, and doing so would be very risky.
Because this PR only affects camera smoothing, and not actual movement, it a low risk way to avoid the sharp camera movement in 5.3.0.

I am doing some testing of actual movement in MT 5.2.0 (before collision changes) and MT master and will start a new issue for the interesting results, but that is not stuff for 5.3.0 release.

**Comment by paramat** [comment]
This PR applies camera smoothing in more situations where the player is moving upwards. So i tested the different ways a player can move upwards, and watched in 3rd person view for an upward twitch of the player model, which indicates camera smoothing (because the model moves instantly while the smoothed camera lags behind slightly).
Here are the results, includng MT 5.2.0:

//////////////////////////////////

In 5.2.0 and master, camera smoothing indicates 'touching ground' bool is true.
'pressed' means a jump up a full node while pressing against node.
'hole' means walking across a single full node hole in the ground.
Holes can be walked across in all 3 tests, so air stepheight is functional in that situation in all 3 tests.


Camera smoothing?
(Detected by watching for upward twitch of player model in 3rd person view)

5.2.0 (before collision changes)

jump: no (but very brief upward twitch on lift off)
step: yes
air step (pressed): no (but no sharp camera movement, air stepheight non-functional?)
air step (hole): yes
climb up: no
fly up: yes

master (after collision changes)

jump: no (and no very brief upward twitch on lift off)
step: yes
air step (pressed): no (sharp camera movement, air stepheight functional)
air step (hole): yes
climb up: no
fly up: no

PR

jump: yes
step: yes
air step (pressed): yes
air step (hole): yes
climb up: yes
fly up: yes

//////////////////////////////////

Note that camera smoothing happened when flying upwards in MT 5.2.0, but not in MT master, for some currently unknown reason.

So, the only currently known side-effects of this PR, compared to MT 5.2.0, are camera smoothing being applied when jumping and when climbing.
The screenshots below show how far the player model moves up the screen, in 3rd person view, when jumping and when climbing (normally, the crosshair is at head centre):

screenshot_20200611_231828

^ Maximum player model upwards offset when jumping

screenshot_20200611_231915

^ Constant player model upwards offset when climbing

In terms of camera movement in 1st person view:
The side-effect is not really noticeable when climbing, as climbing already starts with a smooth acceleration.
Camera motion when jumping is slightly more noticeably changed because it used to be an instant movement at the start of a jump, now it is a smoothed acceleration. It is now consistent with camera motion when stepping up stairs. I find the change in camera motion barely noticeable and not a problem.

So, unless something else arises, i am happy with this PR and consider it mergeable for 5.3.0.

**Comment by sfan5** [comment]
> I think removing the 'touching ground' condition for camera smoothing (as this PR does) is probably necessary whatever the situation is, because 'touching ground' is clearly false when air step-up happens onto a full node, because camera smoothing does not happen. [...]

My question was aimed at movement behaviour, not the camera smoothing. I think changing the camera smoothing is not an issue at all.

> Note that camera smoothing happened when flying upwards in MT 5.2.0, but not in MT master, for some currently unknown reason.

`touching_ground` can be true while flying if you touch ground at the point when free_move is enabled.
This is a separate thing, a bug and something I fixed in 0ab580810c6ccebfd57497b9565e3e396d250d70.

**Comment by sfan5** [comment]
Okay I quickly tested this and the camera smoothing when jumping (or climbing) definitely looks weird in third person.
I prefer if this could be avoided though I don't consider it a blocking issue.

**Comment by paramat** [comment]
I cannot see how to avoid it, as it is a direct and unavoidable result of camera smoothing.
If we disabled camera smoothing when jumping, then camera smoothing for air stepheight would not function.

How climbing looks is a very minor issue, as it is a small movement and a constant offset.
Jumping looks a little weirder, but i think it may be a case of 'just get used to it', after all, it happens when climbing steps and no-one complains.

**Comment by paramat** [comment]
I forgot about swimming upwards, that is another way to have upwards movement.

2nd commit added.

I realised i can use available information to disable camera smoothing when climbing, swimming or flying.
The upward offset of the player model seen in 3rd person view is small when climbing or swimming, and does not seem a problem to me. But, the upwards offset when flying upwards fast is large and i agree best avoided, you just fixed that after all.
This commit attends to all 3 situations.
So the only issue left is the upward offset when jumping, which seems unavoidable.

3rd commit coming that cleans up duplicated code in Camera::update().

**Comment by paramat** [comment]
Updated history of behaviours:

Camera smoothing?
(Detected by watching for upward twitch of player model in 3rd person view)

5.2.0 (before collision changes)

jump: no (but very brief upward twitch on lift off)
step: yes
air step (pressed): no (but no sharp camera movement, air stepheight non-functional?)
air step (hole): yes
climb up: no
fly up: yes
swim up: no

master (after collision changes)

jump: no (and no very brief upward twitch on lift off)
step: yes
air step (pressed): no (sharp camera movement, air stepheight functional)
air step (hole): yes
climb up: no
fly up: no (recently fixed)
swim up: no

PR

jump: yes
step: yes
air step (pressed): yes (primary purpose of PR)
air step (hole): yes
climb up: yes
fly up: yes
swim up: yes

PR 2nd commit

jump: yes
step: yes
air step (pressed): yes
air step (hole): yes
climb up: no
fly up: no
swim up: no

**Comment by paramat** [comment]
3rd commit added.
Retested that camera soothing is disabled when flying, and tested that view bobbing is still disabled when flying.
PR seems ready to me.

File: src/client/camera.cpp [hunk 1]
```diff
@@ -343,7 +343,11 @@ void Camera::update(LocalPlayer* player, f32 frametime, f32 busytime, f32 tool_r
 		player_position = player->getParent()->getPosition();
 
 	// Smooth the camera movement when the player instantly moves upward due to stepheight
-	if (player_position.Y > old_player_position.Y) {
+	// Disable smoothing if climbing, swimming upwards, or flying, to avoid upwards offset
+	// of player model when seen in 3rd person view.
+	if (player_position.Y > old_player_position.Y && !player->is_climbing &&
+			!player->swimming_vertical &&
+			!(g_settings->getBool("free_move") && m_client->checkLocalPrivilege("fly"))) {
```
Comment (sfan5) [inline src/client/camera.cpp]: Instead of this line it'd be better to apply a fix similar to 0ab580810c6ccebfd57497b9565e3e396d250d70 so that `is_climbing` and `swimming_vertical` can never be true in fly mode.

Comment (sfan5) [reply src/client/camera.cpp]: Hm it appear the same check is already used elsewhere, not exactly clean but I guess it can be left as-is.

Comment (paramat) [reply src/client/camera.cpp]: This line comment refers to outdated code, see 3rd commit.

Comment (paramat) [reply src/client/camera.cpp]: > Instead of this line it'd be better to apply a fix similar to 0ab5808 so that is_climbing and swimming_vertical can never be true in fly mode.

Maybe later, this would be a complex change that i consider too risky for 5.3.0.

**Comment by sfan5** [comment]
There is very noticeable uneven camera movement in the current state of this PR when fast-jumping out of water.
I still dislike that the smoothing applies to all jumps (try jumping in a 2-high space), but that would be acceptable to get this fixes for 5.3.

**Comment by paramat** [comment]
What is 'fast jumping out of water' and how does that differ from 'jumping out of water'?
This might be fixable by keeping camera smoothing while swimming, i will test that.

As discussed earlier, it seems this is a choice between a sharp camera movement on all jumps in 1st and 3rd person, or a slightly unusual player model movement in 3rd person. I think this PR is the 'lesser evil'.

**Comment by sfan5** [comment]
> What is 'fast jumping out of water'

You hold E and space and have the `fast` privilege (while fully submerged in water).

**Comment by paramat** [comment]
> try jumping in a 2-high space

Tested.
In 1st person i cannot see any problem, camera motion is smoother so it seems a little less harsh.
In 3rd person it is no more glitchy and unpleasant than in MT master.

**Comment by paramat** [comment]
Fast mode, ok, but the default 20 nodes per second sprinting makes no sense, sprinting speed should be set to a sane value.
Will test.

**Comment by paramat** [comment]
> very noticeable uneven camera movement in the current state of this PR when fast-jumping out of water.

Tested that at 20 nodes per second. There is no problem in 1st person.

In 3rd person i cannot see any problem. When the player leaves the water it is no longer swimming, it is jumping, so camera smoothing is enabled, which causes an expected upward offset of the player model in 3rd person. The camera and player model movement is smooth and continuous at all times in this situation, it is not 'uneven' or jerky.
The same expected thing happens when jumping out of water at normal speed, but with less player model offset.

But if you prefer, i can enable camera smoothing in water, but this would then cause player model offset when swimming upwards which i think would be less desirable. Again it is a case of choosing the 'lesser evil'.

So i think the PR is in its optimum state.

**Comment by sfan5** [comment]
> In 1st person i cannot see any problem, camera motion is smoother so it seems a little less harsh.

Yes, it's smoother. Jumping in a tight space now produces camera movements similar to "hovering" (holding space) on top of a ladder, which is a confusing experience.

> Tested that at default 20 nodes per second. There is no problem in 1st person.

Do you not see the "snap" to a lower position shortly after exiting the water here?
https://0x0.st/iWJ9.mp4

**Comment by paramat** [comment]
Thanks for the video. Tested again. I can just notice a slight camera jolt when leaving the water at high speed. It took me a few minutes of testing to notice it. Luckily jumping upwards fast out of water is not a very common occurrence.

**Comment by rubenwardy** [comment]
Should this be marked as a blocker?

**Comment by rubenwardy** [comment]
Tested. This looks ok-ish in first person, and very weird in third person

**Comment by KaylebJay** [comment]
Yes please, this should be a blocker. No use releasing 5.3.0 with more bugs.

**Comment by rubenwardy** [comment]
I've marked the issue instead

**Comment by paramat** [comment]
That's odd, the issue and this PR should have been labelled 'blocker' from the start, i must have forgotten.

Generally for development, i think both an issue and the fixing PR should be labelled 'blocker', to be clearer and reduce the chance of overlooking a PR.
> very weird in third person. People don't teleport when walking up stairs, they smoothly move for each step

The upwards jolt of the player model in 3rd person when walking up steps less than stepheight happened before this PR too.

See https://github.com/minetest/minetest/pull/10025#issuecomment-643439212 and the following comment, the only change this PR makes to player model motion in 3rd person is when jumping. As explained above, it seems unavoidable as camera smoothng when jumping is necessary to fix the bug:
>  it seems this is a choice between a sharp camera movement on all jumps in 1st and 3rd person, or a slightly unusual player model movement in 3rd person. I think this PR is the 'lesser evil'.

**Comment by sfan5** [comment]
To be clear I am fine with this PR if the water-related uneven camera movement is fixed (perhaps by always applying smoothing there).

**Comment by paramat** [comment]
I can see what SmallJoker was referring to on IRC:
In 3rd person, jumping up out of water onto land causes a noticeable camera jolt, this might actually be caused by in-air stepheight.
Also, holding 'jump' to tread water causes the model to twitch at the top of the movement.

Both significantly unpleasant.

So, i will re-add camera smoothing to swimming to try to fix these problems.

**Comment by paramat** [comment]
Smoothing added when swimming, tested, fixes the problems mentioned above.

I have noticed a minor problem caused by smoothing being disabled when climbing:
When reaching the top of a ladder, if the player moves forward just before the top, air stepheight applies, causing a sharp camera movement.
But, i think players usually move forward after reaching the top, so this does not seem a big problem. 
But if you prefer, i can add smoothing when climbing, this will cause a slight upwards offset of the player model in 3rd person when climbing upwards (because the camera lags behind the player slightly when smoothing is in effect).
I am not yet sure which behaviour is worse.

**Comment by paramat** [comment]
PR 3rd commit
Camera smoothing?:

jump: yes
step: yes
air step (pressed): yes
air step (hole): yes
climb up: no
fly up: no
swim up: yes
