### PR TITLE
[NOSQUASH :3] Fix some invalid float to integer conversions

### LINKED ISSUE #13979: undefined behavior in client/client.cpp
### Minetest version

```true
Minetest 5.8.0-dev-253eeb81b (OSX)
Using Irrlicht 1.9.0mt13
Using LuaJIT 2.1.1699180677
BUILD_TYPE=RelWithDebInfo
RUN_IN_PLACE=0
USE_CURL=1
USE_GETTEXT=1
USE_SOUND=1
STATIC_SHAREDIR="minetest.app/Contents/Resources"
STATIC_LOCALEDIR="minetest.app/Contents/Resources/locale"
```

### Active renderer

_No response_

### Irrlicht device

_No response_

### Operating system and version

MacOS 14

### CPU model

Apple M1

### GPU model

_No response_

### OpenGL version

_No response_

### Summary

minetest/src/client/client.cpp:1389:20: runtime error: 420 is outside the range of representable values of type 'unsigned char'
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /Users/lindner/VSCode/minetest/src/client/client.cpp:1389:20

u8 wanted_range = map.getControl().wanted_range;

viewing range is stored in an u8, but can be much higher than 255, in my case it's set to 420

### Steps to reproduce

compile with -DCMAKE_CXX_FLAGS="-fsanitize=undefined -fno-sanitize=vptr" -DCMAKE_C_FLAGS="-fsanitize=undefined -fno-sanitize=vptr"

### PR DESCRIPTION
**Pull request by Desour**
* Fixes  #13979, and more.
* There are more easy things left in irrlicht, FYI.
* The bouncy nodes in devtest used invalid color values, so I fixed that, as the invalid values now cause other colors than before. (Issuing warnings for invalid colors might be better, but idk how to do that properly, and without spamming.) (Btw. why does devtest's luacheckrc ignore unused vars?)

## To do

This PR is a Ready for Review.

## How to test

* Read.
* Compile with clang's sanitizers. (gcc doesn't catch these.)
* Start devtest.

### CODE REVIEW

File: games/devtest/mods/testnodes/properties.lua [hunk 1]
```diff
@@ -428,17 +428,17 @@ local MAX_BOUNCE_NONJUMPY = 140
 for i=-MAX_BOUNCE_NONJUMPY, MAX_BOUNCE_JUMPY, 20 do
 	if i ~= 0 then
 		local desc
-		local val = math.floor(((i-20)/200)*255)
-		local val2 = math.max(0, 200 - val)
+		local val = math.floor((math.abs(i)-20)/200*255)
```
Comment (srifqi) [inline games/devtest/mods/testnodes/properties.lua:431]: While we are here,
```suggestion
		local val = math.floor((math.abs(i) - 20) / 200 * 255)
```

**Review by srifqi — APPROVED** [review]

**Review by sfan5 — APPROVED** [review]
LGTM
