### PR TITLE
Avoid packets getting sent to disconnected players

### LINKED ISSUE #14443: Possible SIGABRT when showing formspecs after async without safety checks
### Minetest version

```true
Minetest 5.9.0-dev-b4be483d3 (Linux)
Using Irrlicht 1.9.0mt14
Using LuaJIT 2.1.1702233742
Built by GCC 13.2
Running on Linux/6.7.6-arch1-2 x86_64
BUILD_TYPE=RelWithDebInfo
RUN_IN_PLACE=1
USE_CURL=1
USE_GETTEXT=1
USE_SOUND=1
STATIC_SHAREDIR="."
STATIC_LOCALEDIR="locale"
```

### Irrlicht device

_No response_

### Operating system and version

EndeavourOS / Ubuntu 20.04

### CPU model

_No response_

### GPU model

_No response_

### Active renderer

_No response_

### Summary

I had this crash on the CTF server:
```
Thread 5 "Server" received signal SIGABRT, Aborted.
[Switching to Thread 0x7fff777c3700 (LWP 759547)]
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007ffff7def859 in __GI_abort () at abort.c:79
#2  0x00005555555b445a in fatal_error_fn (msg=0x5555559141b0 "Server::Send() missing peer ID", file=<optimized out>, line=1348, function=0x555555914188 "void Server::Send(NetworkPacket*)") at /home/minetest/minetest/src/debug.cpp:76
#3  0x0000555555693c19 in Server::Send (pkt=<optimized out>, this=<optimized out>) at /home/minetest/minetest/src/server.cpp:1348
#4  0x00005555556a6f8a in Server::Send (this=<optimized out>, pkt=<optimized out>) at /usr/include/c++/9/bits/shared_ptr_base.h:1020
#5  0x00005555557c8a32 in Server::SendShowFormspecMessage (formname="ctf_modebase:mode_select", formspec="\t\t\t\tformspec_version[4]size[8.700000,12.100000]hypertext[0,0.2;8,2.4;title;<center><big>Mode: Classes</big>\nPlease vote on how many matches you would like to play.\nYou can change your default vote for"..., peer_id=<optimized out>, this=0x7fffffffbf80) at /home/minetest/minetest/src/server.cpp:1545
#6  Server::showFormspec (formname="ctf_modebase:mode_select", formspec="\t\t\t\tformspec_version[4]size[8.700000,12.100000]hypertext[0,0.2;8,2.4;title;<center><big>Mode: Classes</big>\nPlease vote on how many matches you would like to play.\nYou can change your default vote for"..., playername=<optimized out>, this=0x7fffffffbf80) at /home/minetest/minetest/src/server.cpp:3367
#7  ModApiServer::l_show_formspec (L=0x7ffff5271380, L@entry=<error reading variable: value has been optimized out>) at /home/minetest/minetest/src/script/lua_api/l_server.cpp:428
#8  0x000055555583821e in script_exception_wrapper (L=0x7ffff5271380, f=<optimized out>) at /home/minetest/minetest/src/script/common/c_internal.cpp:41
#9  0x00007ffff7b2baab in ?? () from /usr/local/lib/libluajit-5.1.so.2
#10 0x00007ffff7b4048f in lua_pcall () from /usr/local/lib/libluajit-5.1.so.2
#11 0x00005555557bb414 in AsyncEngine::stepJobResults (L=0x7ffff5271380, this=0x555555a482c8) at /home/minetest/minetest/src/script/cpp_api/s_async.cpp:197
#12 AsyncEngine::step (L=0x7ffff5271380, this=0x555555a482c8) at /home/minetest/minetest/src/script/cpp_api/s_async.cpp:167
#13 ServerScripting::stepAsync (this=0x555555a48250) at /home/minetest/minetest/src/script/scripting_server.cpp:126
#14 0x0000555555698ac7 in ServerEnvironment::step (this=<optimized out>, dtime=<optimized out>) at /home/minetest/minetest/src/serverenvironment.cpp:1572
#15 0x00005555556b09ed in Server::AsyncRunStep (this=0x7fffffffbf80, dtime=<optimized out>, initial_step=<optimized out>) at /home/minetest/minetest/src/server.cpp:675
#16 0x00005555556bf5bd in ServerThread::run (this=0x555555a2afb0) at /home/minetest/minetest/src/server.cpp:131
#17 0x0000555555789cf8 in Thread::threadProc (thr=0x555555a2afb0) at /home/minetest/minetest/src/threading/thread.cpp:189
#18 0x00007ffff7895df4 in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#19 0x00007ffff7638609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#20 0x00007ffff7eec353 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```
And here's a `bt full` from the script provided below:
```
2024-03-07 14:54:52: ACTION[Server]: LandarVargan2 leaves game. List of players: LandarVargan 
2024-03-07 14:54:52: ERROR[Server]: In thread 7ffef84006c0:
2024-03-07 14:54:52: ERROR[Server]: /home/lv/minetest/src/server.cpp:536: void Server::Send(NetworkPacket*): A fatal error occurred: Server::Send() missing peer ID

Thread 30 "Server" received signal SIGABRT, Aborted.
[Switching to Thread 0x7ffef84006c0 (LWP 36417)]
0x00007ffff6eab32c in ?? () from /usr/lib/libc.so.6
(gdb) bt full
#0  0x00007ffff6eab32c in ?? () from /usr/lib/libc.so.6
No symbol table info available.
#1  0x00007ffff6e5a6c8 in raise () from /usr/lib/libc.so.6
No symbol table info available.
#2  0x00007ffff6e424b8 in abort () from /usr/lib/libc.so.6
No symbol table info available.
#3  0x000055555561e42e in fatal_error_fn (msg=0x555555c22240 "Server::Send() missing peer ID", file=<optimized out>, line=1334, function=0x555555c221f0 "void Server::Send(NetworkPacket*)") at /home/lv/minetest/src/debug.cpp:76
No locals.
#4  0x0000555555a94273 in Server::Send (pkt=<optimized out>, this=<optimized out>) at /home/lv/minetest/src/server.cpp:1334
        __PRETTY_FUNCTION__ = <optimized out>
#5  0x0000555555a7bb66 in Server::Send (this=<optimized out>, pkt=<optimized out>) at /home/lv/minetest/src/server/clientiface.cpp:786
        __PRETTY_FUNCTION__ = <optimized out>
#6  0x00005555559625ce in Server::SendShowFormspecMessage (formname="", formspec="", peer_id=<optimized out>, this=0x555556a92750) at /home/lv/minetest/src/server.cpp:1531
        pkt = {m_data = std::vector of length 6, capacity 8 = {0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000'}, m_datasize = 6, m_read_offset = 6, m_command = 68, m_peer_id = 0}
        pkt = <optimized out>
        it = <optimized out>
#7  Server::showFormspec (formname="", formspec="", playername=<optimized out>, this=0x555556a92750) at /home/lv/minetest/src/server.cpp:3337
        player = 0x7fff704d67c0
        player = <optimized out>
#8  ModApiServer::l_show_formspec (L=0x7ffff5837380, L@entry=<error reading variable: value has been optimized out>) at /home/lv/minetest/src/script/lua_api/l_server.cpp:430
        playername = <optimized out>
        formname = <optimized out>
        formspec = <optimized out>
#9  0x00005555558dc21b in script_exception_wrapper (L=0x7ffff5837380, f=<optimized out>) at /home/lv/minetest/src/script/common/c_internal.cpp:41
No locals.
#10 0x00007ffff7adef6b in ?? () from /usr/lib/libluajit-5.1.so.2
No symbol table info available.
#11 0x00007ffff7af1cb3 in lua_pcall () from /usr/lib/libluajit-5.1.so.2
No symbol table info available.
#12 0x00005555558e155f in AsyncEngine::stepJobResults (this=0x555556760de8, L=0x7ffff5837380) at /home/lv/minetest/src/script/cpp_api/s_async.cpp:197
        j = {function = "\033LJ\002\b,@/home/lv/minetest/bin/../mods/test/init.lua\024\000\001\001\000\000\000\001\006\004\002L\000\002\000\001p\000\000\002\000", params = "", params_ext = std::unique_ptr<PackedValue> = {get() = 0x7fff70518130}, result = "", result_ext = std::unique_ptr<PackedValue> = {
            get() = 0x7fff90001840}, mod_origin = "test", id = 1}
        origin = <optimized out>
        result = <optimized out>
        error_handler = <optimized out>
        script = 0x555556760f80
        autolock = {_M_device = 0x555556760ed0, _M_owns = true}
        __PRETTY_FUNCTION__ = <optimized out>
#13 0x0000555555aa4e83 in AsyncEngine::step (L=<optimized out>, this=0x555556760de8) at /home/lv/minetest/src/script/cpp_api/s_async.cpp:167
No locals.
#14 ServerScripting::stepAsync (this=0x555556760d70) at /home/lv/minetest/src/script/scripting_server.cpp:126
No locals.
#15 ServerEnvironment::step (this=<optimized out>, dtime=<optimized out>) at /home/lv/minetest/src/serverenvironment.cpp:1575
        sp2 = {m_profiler = 0x555555d50560 <_ZL13main_profiler.lto_priv.0>, m_name = "ServerEnv::step() [ms]", m_timer = 0x7fff707cda60, m_type = SPT_AVG}
        start_time = <optimized out>
        end_time = <optimized out>
        server_step = 0.0900000036
        active_object_range = 30
        active_block_range = 4
#16 0x0000555555a8146d in Server::AsyncRunStep (this=<optimized out>, dtime=<optimized out>, initial_step=<optimized out>) at /home/lv/minetest/src/server.cpp:661
        lock = {_M_device = 0x555556a927b8, _M_owns = true}
        max_lag = <optimized out>
        sp = {m_profiler = 0x555555d50560 <_ZL13main_profiler.lto_priv.0>, m_name = "Server::AsyncRunStep() [ms]", m_timer = 0x7fff70075fd0, m_type = SPT_AVG}
        save_interval = 5.30000019
        map_timer_and_unload_dtime = <optimized out>
--Type <RET> for more, q to quit, c to continue without paging--
#17 0x0000555555a76c95 in ServerThread::run (this=0x555556a615e0) at /home/lv/minetest/src/server.cpp:131
        remaining_time = <optimized out>
        spm = {m_profiler = 0x555555d50560 <_ZL13main_profiler.lto_priv.0>, m_name = "Server::RunStep() (max) [ms]", m_timer = 0x7fff7048f4d0, m_type = SPT_MAX}
        t0 = 83869464550
        step_settings = <optimized out>
        dtime = <optimized out>
        __PRETTY_FUNCTION__ = <optimized out>
#18 0x00005555559943ca in Thread::threadProc (thr=0x555556a615e0) at /home/lv/minetest/src/threading/thread.cpp:189
        sf_lock = {_M_device = 0x555556a61640, _M_owns = true}
#19 0x00007ffff70e1943 in std::execute_native_thread_routine (__p=0x555556e3ced0) at /usr/src/debug/gcc/gcc/libstdc++-v3/src/c++11/thread.cc:104
        __t = <optimized out>
#20 0x00007ffff6ea955a in ?? () from /usr/lib/libc.so.6
No symbol table info available.
#21 0x00007ffff6f26a3c in ?? () from /usr/lib/libc.so.6
```

### Steps to reproduce

```lua
minetest.register_on_joinplayer(function(player, last_login)
	if #minetest.get_connected_players() >= 2 then

		minetest.handle_async(function(p)
			return p
		end, function(p2)
			minetest.close_formspec(p2, "")
		end, player:get_player_name())
		minetest.kick_player(player:get_player_name())
	end
end)
```

### PR DESCRIPTION
**Pull request by SmallJoker**
Many functions expect RemotePlayer to have a valid peer ID, this however is not the case immediately after disconnecting where the object is still alive and pending for removal.

ServerEnvironment::getPlayer(const char *, bool) now only returns players that are connected unless forced to.

Fixes #14443

## To do

This PR is Ready for Review.^

## How to test

1. Test script from https://github.com/minetest/minetest/issues/14443 (host server, connect with a 2nd client)
2. ????
3. No error

### CODE REVIEW

File: src/serverenvironment.cpp [hunk 1]
```diff
@@ -583,13 +583,18 @@ RemotePlayer *ServerEnvironment::getPlayer(const session_t peer_id)
...
+RemotePlayer *ServerEnvironment::getPlayer(const char* name, bool match_invalid_peer)
 {
 	for (RemotePlayer *player : m_players) {
-		if (strcmp(player->getName(), name) == 0)
+		if (strcmp(player->getName(), name) != 0)
+			continue;
+
+		if (match_invalid_peer || player->getPeerId() != PEER_ID_INEXISTENT) {
 			return player;
+		}
```
Comment (sfan5) [inline src/serverenvironment.cpp:594]:
```suggestion
		if (match_invalid_peer || player->getPeerId() != PEER_ID_INEXISTENT)
			return player;
```

**Review by sfan5 — APPROVED** [review]
looks sensible

**Review by Ekdohibs — APPROVED** [review]
Looks good; I also checked that you considered all instances of `getPlayer` and this seems to be the case.
