### PR TITLE
Fix Android blank screen

### LINKED ISSUE #12573: Android main menu doesn't render
##### Minetest version
2cf52642fa89a9497b0200f5a4637a25a82f9c3d

##### OS / Hardware

Google Pixel 4a, Android 12

##### Summary

After extracting the assets, a  blank blue screen is shown

```
I/AdrenoGLES-0: Build Config                     : S P 10.0.4 AArch64
I/AdrenoGLES-0: Driver Path                      : /vendor/lib64/egl/libGLESv2_adreno.so
I/AdrenoGLES-0: PFP: 0x016ee190, ME: 0x00000000
W/AdrenoUtils: <ReadGpuID_from_sysfs:197>: Failed to open /sys/class/kgsl/kgsl-3d0/gpu_model
W/AdrenoUtils: <ReadGpuID:221>: Failed to read chip ID from gpu_model. Fallback to use the GSL path
I/libOpenSLES: Emulating old channel mask behavior (ignoring positional mask 0x3, using default mask 0x3 based on channel count of 2)
E/openal: [ALSOFT] (EE) Failed to set real-time priority for thread: Operation not permitted (1)
E/Adreno-UNKNOWN: <glTexParameteriv:151>: GL_INVALID_ENUM
```

##### Steps to reproduce
APKs: https://github.com/rubenwardy/minetest/releases/tag/5.6.0-rc1

### PR DESCRIPTION
**Pull request by rollerozxa**
Fixes #12573, caused by https://github.com/minetest/minetest/commit/051181fa6ee00d8379e8a7dc7442b58342d4352b clamping the screen width and height to at least 1, which breaks on Android where those are set to 0.

## To do
This PR is a Ready for Review.

## How to test
Install the Android version and see so that it actually works again.

### CODE REVIEW

**Comment by rubenwardy** [comment]
Wack. If this needs to be 0, should this be hard coded rather than using the setting?

**Comment by rollerozxa** [comment]
Good idea, I was just about to ask if I should do that.

**Comment by sfan5** [comment]
It sounds like screen_w and screen_h should be allowed to be zero if fullscreen == true instead of adding android specific code.

**Comment by rollerozxa** [comment]
I kept the default settings since they are still getted for [code related to autosaving screen size that still gets run on Android](https://github.com/minetest/minetest/blob/master/src/gui/guiEngine.cpp#L250), might introduce additional issues if that were to be removed.

**Comment by rollerozxa** [comment]
> It sounds like screen_w and screen_h should be allowed to be zero if fullscreen == true instead of adding android specific code.

Setting screen_w and screen_h to zero even when fullscreen is enabled crashes for me on desktop Linux, so I'm pretty sure this would only be a quirk specific to Android.

**Comment by sfan5** [comment]
> Setting screen_w and screen_h to zero even when fullscreen is enabled crashes for me on desktop Linux

Works for me:
`./bin/minetest --config <(echo fullscreen=true;echo screen_w=0;echo screen_h=0)`

**Comment by rollerozxa** [comment]
That's because it clamps to at least 1 with the current code, forgot to say I tried that with the check removed. 😅

File: src/client/renderingengine.cpp [hunk 1]
```diff
@@ -86,8 +86,13 @@ RenderingEngine::RenderingEngine(IEventReceiver *receiver)
 
 	// Resolution selection
 	bool fullscreen = g_settings->getBool("fullscreen");
+#ifdef __ANDROID__
+	u16 screen_w = 0;
+	u16 screen_h = 0;
```
Comment (sfan5) [inline src/client/renderingengine.cpp:91]:
```suggestion
	u16 screen_w = 0, screen_h = 0
```

**Review by sfan5 — APPROVED** [review]
lgtm

**Review by rubenwardy — APPROVED** [review]
