### PR TITLE
Fix inventory drag drop flag

### LINKED ISSUE #2964: right click and drag inventory bug
When you right click and drag a stack on the inventory spreads 1 item per slot into the inventory. But when I click and drag, it doesn't work unless I do it again. It alternates working and not working.
How to reproduce the issue:
1. Start a new world, doesn't matter which game
2. Gather up a stack of 10 or 20 items.
3. Try dragging them across the inventory several times.

### PR DESCRIPTION
**Pull request by asl97**
Fixes #2964

The original fix was incorrect, as in it check for more condition than require,
All that was needed was for it to keep note that the mouse button was released before it start dropping items when dragging.

The variable was renamed to properly reflect that it isn't only for the right mouse button but possibly the middle and left #2963.

### CODE REVIEW

File: src/guiFormSpecMenu.cpp [hunk 1]
```diff
@@ -3499,19 +3499,19 @@ bool GUIFormSpecMenu::OnEvent(const SEvent& event)
...
 			m_selected_dragging = false;
-			// Keep count of how many times right mouse button has been
-			// clicked. One click is drag without dropping. Click + release
-			// + click changes to drop one item when moved mode
-			if (button == 1 && m_selected_item != NULL)
-				m_rmouse_auto_place = !m_rmouse_auto_place;
+			// Keep track of whether the mouse button be released
+			// One click is drag without dropping. Click + release
+			// + click changes to drop item when moved mode
+			if (m_selected_item != NULL)
```
Comment (nerzhul) [inline src/guiFormSpecMenu.cpp]: if (m_selected_item)
