### PR TITLE
Fix/Add inventory_overlay for nodes without inventory_image

### LINKED ISSUE #8430: inventory_overlay is ignored when item does not define inventory_image
##### Issue type

 - Bug report
 
##### Minetest version

```
5.1.0-dev-426bdba7
```

##### Summary

The itemdef field `inventory_overlay` is ignored (i.e. overlay isn't visible) when the item uses `minetest.inventorycube`. This bug is present in `0.4.x` as well.

Context: CTF duplicates all nodes from default, and sets `groups = {immortal = 1}` to make them indestructible, and I'm trying to set an inventory overlay to distinguish indestructible nodes from their normal counterparts. See the relevant bit of code here: https://github.com/ClobberXD/capturetheflag/blob/2884b8046fe8a6993a20e0dfa74461ef222ccb34/mods/ctf/ctf_map/nodes.lua#L768-L775

screenshot_20190329_134038

Both the stacks in the hotbar have the `inventory_overlay` field defined. But as seen in the screenshot, the stack of `ctf_map:snow` displays the overlay correctly, whereas the stack of `ctf_map:stone` doesn't.

##### Steps to reproduce

- Set the `inventory_overlay` itemdef field to a custom image for two items: one that uses a single .png `inventory_image`, and one that uses `minetest.inventorycube` (most nodes from `default` fall under the latter).
- Obtain the items with the `inventory_overlay` field defined.
- Observe that the overlay isn't visible for the item that uses `minetest.inventorycube`.

### PR DESCRIPTION
**Pull request by DS-Minetest**
Closes #8430.
There might be many mistakes.

How to test this:
```lua
minetest.register_node("test_invcube:node", {
	description = "inventorycube node",
	tiles = {"unknown_item.png"},
	inventory_overlay = "camera_btn.png",
	groups = {oddly_breakable_by_hand = 3},
})
```
Here's a sceenshot:
screenshot
As you can see, the rotating of the node also works (`inventory_items_animations`).

If the `inventory_overlay` image is not quadratic, it is squashed in one direction (try with progress bar texture).

### CODE REVIEW

**Comment by ClobberXD** [comment]
Awesome. Will test today.

**Comment by ClobberXD** [comment]
It works! (Note that I've only tested it with the code linked to in #8430)

File: src/client/hud.cpp [hunk 1]
```diff
@@ -693,6 +693,16 @@ void drawItemStack(video::IVideoDriver *driver,
 		driver->setTransform(video::ETS_VIEW, oldViewMat);
 		driver->setTransform(video::ETS_PROJECTION, oldProjMat);
 		driver->setViewPort(oldViewPort);
+
+		// draw the inventory_overlay
+		if (def.type == ITEM_NODE && def.inventory_image.empty() &&
+				!def.inventory_overlay.empty()) {
+			ITextureSource *tsrc = client->getTextureSource();
+			video::ITexture *overlay_texture = tsrc->getTexture(def.inventory_overlay);
+			core::dimension2d<u32> dimens = overlay_texture->getOriginalSize();
```
Comment (rubenwardy) [inline src/client/hud.cpp]: make sure that `getTexture()` doesn't grab the texture and thus require the user to `->drop()` the texture

Comment (DS-Minetest) [reply src/client/hud.cpp]: I think, I'm not sure what you mean.

Comment (DS-Minetest) [reply src/client/hud.cpp]: [`getTexture`](https://github.com/minetest/minetest/blob/42e1a127140965cac1be6e51e48192e341c2a29e/src/client/tile.cpp#L645) [uses](https://github.com/minetest/minetest/blob/42e1a127140965cac1be6e51e48192e341c2a29e/src/client/tile.cpp#L647) [`getTextureId`](https://github.com/minetest/minetest/blob/42e1a127140965cac1be6e51e48192e341c2a29e/src/client/tile.cpp#L463) [which uses](https://github.com/minetest/minetest/blob/42e1a127140965cac1be6e51e48192e341c2a29e/src/client/tile.cpp#L484) [`generateTexture`](https://github.com/minetest/minetest/blob/42e1a127140965cac1be6e51e48192e341c2a29e/src/client/tile.cpp#L558) [which uses](https://github.com/minetest/minetest/blob/42e1a127140965cac1be6e51e48192e341c2a29e/src/client/tile.cpp#L601) [which uses](https://github.com/minetest/minetest/blob/42e1a127140965cac1be6e51e48192e341c2a29e/src/client/tile.cpp#L601) [from the class `video::IVideoDriver`](https://github.com/minetest/minetest/blob/42e1a127140965cac1be6e51e48192e341c2a29e/src/client/tile.cpp#L589) [`irr::video::IVideoDriver::addTexture`](http://irrlicht.sourceforge.net/docu/classirr_1_1video_1_1_i_video_driver.html#abfebeb09a692c0d6b4741d952d97668e) which
>Returns:
    Pointer to the newly created texture. This pointer should not be dropped.

. (However, this function is virtual, ergo that information might be not true, but this would be extremely weird.)
Ergo the texture doesn't need to be dropped, I think.

Comment (DS-Minetest) [reply src/client/hud.cpp]: Also in other places (eg. [here](https://github.com/minetest/minetest/blob/6cb6aea969032e43395ddbad09233e7e20830909/src/client/hud.cpp#L244-L248)) the texture isn't dropped, too.
