### PR TITLE
Restore server description in menu

### LINKED ISSUE #16737: Server description doesn't show when returning to multiplayer tab
### Luanti version

Luanti 5.15.0-dev 87669f982c9d998ca68c86bb50fdb66a8a75fb87

### Steps to reproduce

1. switch to multiplayer tab, select a server with a description
2. restart Luanti
3. server is selected and everything looks right **but** the description is missing

Image

### PR DESCRIPTION
**Pull request by siliconsniffer**
Add compact, short information about your PR for easier understanding:

- Goal of the PR
Restore the server description.
- How does the PR work?
It restores the description from the server object returned by `find_selected_server()`.
- Does it resolve any reported issue?
Closes #16737
- Does this relate to a goal in [the roadmap](https://github.com/luanti-org/luanti/blob/master/doc/direction.md)?
Not directly, maybe 2.3?

## To do

This PR is ready for review.

- [x] Discuss approach / alternatives

## How to test
Select a server → reopen luanti → observe presence of server description

### CODE REVIEW

File: builtin/mainmenu/tab_online.lua [hunk 1]
```diff
@@ -141,6 +141,9 @@ local function get_formspec(tabview, name, tabdata)
 	end
 
 	local selected_server = find_selected_server()
+	if selected_server and selected_server.description then
+		gamedata.serverdescription = selected_server.description
```
Comment (appgurueu) [inline builtin/mainmenu/tab_online.lua]: I'd merge this with the `if selected_server then ...` right below.

Does the `selected_server.description` check make sense? Should we not clear `gamedata.serverdescription` if the current selected server has no description?

**Comment by siliconsniffer** [comment]
I don't think there is a simpler approach than this; a discussion is probably needless.
