### PR TITLE
Fix curl_timeout being ignored for Lua HTTP fetches

### LINKED ISSUE #11269: Can not fetch the serverlist for the short timeout
##### Minetest version

```
Minetest 5.5.0-dev-d44f1aa (Linux)
Using Irrlicht 1.9.0mt2
Using Lua 5.1.5
BUILD_TYPE=Release
RUN_IN_PLACE=1
USE_CURL=1
USE_GETTEXT=1
USE_SOUND=1
USE_FREETYPE=1
STATIC_SHAREDIR="."
STATIC_LOCALEDIR="locale"
```

##### OS / Hardware

Operating system: Ubuntu 20.04.2 LTS
CPU: Intel(R) Xeon(R) CPU E3-1230 v5

##### Summary

```bash
ERROR[AsyncWorker-2]: servers.minetest.net/list?proto_version_min=37&proto_version_max=39 not found (Timeout was reached) (response code 200)
```
The network speed to the server here is relatively slow, so it takes about 3 minutes to retrieve the serverlist.

But the default timeout is only 3 seconds: https://github.com/minetest/minetest/blob/d44f1aabbb25a68e915a4bd5c20b72ca393ba34c/src/script/lua_api/l_http.cpp#L50

### PR DESCRIPTION
**Pull request by sfan5**
fixes #11269

(this was missed in #11135)

## To do

This PR is Ready for Review.

## How to test

Set `curl_timeout = 1`, the server list in the Multiplayer tab must **not** load.

### CODE REVIEW

File: src/script/lua_api/l_http.cpp [hunk 1]
```diff
@@ -44,10 +44,13 @@ void ModApiHttp::read_http_fetch_request(lua_State *L, HTTPFetchRequest &req)
...
 	if (lua_isstring(L, -1))
-		req.useragent = getstringfield_default(L, 1, "user_agent", "");
+		req.useragent = lua_tostring(L, -1);
 	lua_pop(L, 1);
 	req.multipart = getboolfield_default(L, 1, "multipart", false);
-	req.timeout = getintfield_default(L, 1, "timeout", 3) * 1000;
+	lua_getfield(L, 1, "timeout");
+	if (lua_isnumber(L, -1))
+		req.timeout = lua_tointeger(L, -1) * 1000;
+	lua_pop(L, 1);
```
Comment (SmallJoker) [inline src/script/lua_api/l_http.cpp:53]: Alternatively, shorter:
```C++
if (getintfield(L, 1, "timeout", req.timeout))
	req.timeout *= 1000;
```
`nil` values are ignored (i.e. old value is kept), and a proper error message is shown when the API is used wrongly (i.e. wrong types).
Same would be possible for `req.useragent`.
