### PR TITLE
Fix camera jumping on Android when panning past 0/360 mark

### LINKED ISSUE #2599: Android: Random spinning with cinematic_mode enabled
While testing the latest Android build, 0.4.12.12, I noticed that when cinematic_camera_smoothing is enabled, the player will frequently spin while looking around. When I disabled cinematic_camera_smoothing, gameplay was normal.

### PR DESCRIPTION
**Pull request by rubenwardy**
Fixes #2599 

Note that it's fine not to limit yaw to 0-360, as the main desktop version doesn't either

### CODE REVIEW

File: src/touchscreengui.h [hunk 1]
```diff
@@ -147,8 +147,14 @@ class TouchScreenGUI
 
 	void init(ISimpleTextureSource* tsrc);
 
-	double getYaw() { return m_camera_yaw; }
+	double getYawChange() {
+		double res = m_camera_yaw;
```
Comment (est31) [inline src/touchscreengui.h]: would it mean much to rename `m_camera_yaw` to `m_camera_yaw_change`?

**Comment by est31** [comment]
Otherwise :+1: if testing confirms that the issue is fixed.

**Comment by Wayward1** [comment]
👍  This fixes the issue.
