### PR TITLE
Fix UAF in craft recipes

### LINKED ISSUE #11992: Heap UAF in craft recipes
##### Minetest version
```
5.5.0-dev-48e508052
```

##### OS / Hardware
Operating system: Linux Ubuntu 21.04
CPU: Intel(R) Core(TM) i9-9900 CPU @ 3.10GHz

##### Summary
`==11332==ERROR: AddressSanitizer: heap-use-after-free on address 0x60d000005b40 at pc 0x555555bc0f6c bp 0x7fffffff86b0 sp 0x7fffffff86a0`

##### Steps to reproduce
* Create a mod with this code
```lua
minetest.register_craftitem("test:tool1", {
    description = "tool1",
    inventory_image = "unittests_stick.png",
})

minetest.register_craftitem("test:tool2", {
    description = "tool2",
    inventory_image = "unittests_stick.png",
})

minetest.register_craftitem("test:tool3", {
    description = "tool3",
    inventory_image = "unittests_stick.png",
})

minetest.register_craft({
    output = "test:tool2",
    recipe = {{"test:tool1"}},
})

minetest.register_alias_force("test:tool2", "test:tool3")

minetest.clear_craft({
    recipe = {{"test:tool1"}},
})

print(dump(minetest.get_all_craft_recipes("test:tool2")))
```
* Start a server

### LINKED ISSUE #12762: intermittent SegFault when calling minetest.get_all_craft_recipes
##### Minetest version
```
5.6.0
```

##### Summary
The segfault occurs sometimes on a local server while running a huge quantity of mods (the modset on the your-land server). The specific trigger is [this line of unified_inventory](https://github.com/minetest-mods/unified_inventory/blob/fc562ecaa0966e71c8a70cfc27f7f924e3f16556/api.lua#L21). If I put a "log" line above that, to try to see what argument might trigger the crash, the crash does not occur. 

Stacktrace:
```
Using host libthread_db library "/usr/lib/libthread_db.so.1".
Core was generated by `./bin/minetestserver --worldname your-land --gameid minetest --config ./worlds/'.
Program terminated with signal SIGSEGV, Segmentation fault.
gdb) bt
#0  0x000055c461ed6c74 in push_craft_recipe (L=0x7f384c551380, gdef=0x7ffc21a955a0, recipe=0x55c4654c57c0, tmpout=...)
    at /opt/minetest/src/script/lua_api/l_craft.cpp:425
#1  0x000055c461ed7063 in push_craft_recipes (L=0x7f384c551380, gdef=0x7ffc21a955a0, recipes=std::vector of length 1, capacity 1 = {...}, output=...)
    at /opt/minetest/src/script/lua_api/l_craft.cpp:478
#2  0x000055c461ed73cf in ModApiCraft::l_get_all_craft_recipes (L=0x7f384c551380) at /opt/minetest/src/script/lua_api/l_craft.cpp:516
#3  0x000055c461ea2381 in script_exception_wrapper (L=0x7f384c551380, f=0x55c461ed72de <ModApiCraft::l_get_all_craft_recipes(lua_State*)>)
    at /opt/minetest/src/script/common/c_internal.cpp:40
#4  0x00007f384c277f6b in ?? () from /usr/lib/libluajit-5.1.so.2
#5  0x00007f384c28a873 in lua_pcall () from /usr/lib/libluajit-5.1.so.2
#6  0x000055c461eb363b in ScriptApiBase::runCallbacksRaw (this=0x55c462e44e88, nargs=1, mode=RUN_CALLBACKS_MODE_FIRST, 
    fxn=0x55c4621c3d52 "environment_Step") at /opt/minetest/src/script/cpp_api/s_base.cpp:292
#7  0x000055c461eb8960 in ScriptApiEnv::environment_Step (this=0x55c462e44cc0, dtime=0.180000007) at /opt/minetest/src/script/cpp_api/s_env.cpp:56
#8  0x000055c46214c6bd in ServerEnvironment::step (this=0x55c46a39d160, dtime=0.180000007) at /opt/minetest/src/serverenvironment.cpp:1503
#9  0x000055c46211183a in Server::AsyncRunStep (this=0x7ffc21a95590, initial_step=false) at /opt/minetest/src/server.cpp:651
#10 0x000055c46210c9d8 in ServerThread::run (this=0x55c462dfec90) at /opt/minetest/src/server.cpp:120
#11 0x000055c461f47488 in Thread::threadProc (thr=0x55c462dfec90) at /opt/minetest/src/threading/thread.cpp:188
#12 0x000055c461f480ba in std::__invoke_impl<void, void (*)(Thread*), Thread*> (__f=@0x55c46bf2fba0: 0x55c461f47416 <Thread::threadProc(Thread*)>)
    at /usr/include/c++/12.1.1/bits/invoke.h:61
#13 0x000055c461f4803d in std::__invoke<void (*)(Thread*), Thread*> (__fn=@0x55c46bf2fba0: 0x55c461f47416 <Thread::threadProc(Thread*)>)
    at /usr/include/c++/12.1.1/bits/invoke.h:96
#14 0x000055c461f47fad in std::thread::_Invoker<std::tuple<void (*)(Thread*), Thread*> >::_M_invoke<0ul, 1ul> (this=0x55c46bf2fb98)
    at /usr/include/c++/12.1.1/bits/std_thread.h:252
#15 0x000055c461f47f66 in std::thread::_Invoker<std::tuple<void (*)(Thread*), Thread*> >::operator() (this=0x55c46bf2fb98)
    at /usr/include/c++/12.1.1/bits/std_thread.h:259
#16 0x000055c461f47f4a in std::thread::_State_impl<std::thread::_Invoker<std::tuple<void (*)(Thread*), Thread*> > >::_M_run (this=0x55c46bf2fb90)
    at /usr/include/c++/12.1.1/bits/std_thread.h:210
#17 0x00007f384c0682f3 in std::execute_native_thread_routine (__p=0x55c46bf2fb90) at /usr/src/debug/gcc/libstdc++-v3/src/c++11/thread.cc:82
#18 0x00007f384ba5778d in ?? () from /usr/lib/libc.so.6
#19 0x00007f384bad88e4 in clone () from /usr/lib/libc.so.6
```

##### Steps to reproduce
I don't have any steps to reproduce this at the moment other than running minetest w/ the specific mods, and the versions of the mods, as i've got locally. When it occurs and I don't change things, it happens consistently, but I can't figure out a "minimal" replication.

### PR DESCRIPTION
**Pull request by savilli**
Fixes #11992 and fixes #12762.

If you call `minetest.clear_craft` after `minetest.register_alias_force`, the craft definition reference may not be removed from `m_output_craft_definitions` leading to UAF.
The idea is to iterate over every output in `m_output_craft_definitions` to remove the reference instead of guessing in which output it should be.
It's slower than removing the definition from one output. But recipes aren't supposed to be removed in runtime (https://github.com/minetest/minetest/blob/cea5fd56a4b724fe6efe6852dc849d517a61d0e2/src/craftdef.cpp#L1027), so it shouldn't make problems.

## To do

This PR is Ready for Review.

## How to test

Build minetest with address sanitizer. Use test cases from #11992 and #12762.

### CODE REVIEW

File: src/craftdef.cpp [hunk 1]
```diff
@@ -1026,26 +1026,31 @@ class CCraftDefManager: public IWritableCraftDefManager
...
-		if (got_hit)
+
+		if (!defs_to_remove.empty()) {
+			for (auto def : defs_to_remove)
+				delete(def);
+
 			defs.swap(new_defs);
 
-		return got_hit;
+			for (auto &it : m_output_craft_definitions) {
```
Comment (SmallJoker) [inline src/craftdef.cpp:1045]: `sizeof(it)` is 8 in my testing. Reference results in overhead, unless the compiler optimizes that away.

File: src/craftdef.cpp [hunk 2]
```diff
@@ -1026,26 +1026,31 @@ class CCraftDefManager: public IWritableCraftDefManager
...
-			if (it == m_output_craft_definitions.end())
-				continue;
-			std::vector<CraftDefinition *> &outdefs = it->second;
-			outdefs.erase(std::remove(outdefs.begin(), outdefs.end(), def), outdefs.end());
 		}
-		if (got_hit)
+
+		if (!defs_to_remove.empty()) {
+			for (auto def : defs_to_remove)
+				delete(def);
```
Comment (SmallJoker) [inline src/craftdef.cpp:1041]: Please use `delete` like `return`. It's a keyword and not a function.

File: src/craftdef.cpp (hunk 1 above)
Comment (savilli) [reply src/craftdef.cpp:1045]: We can't remove & here, because it would copy `std::vector<CraftDefinition *>`, and we need to change it.

File: src/craftdef.cpp (hunk 2 above)
Comment (savilli) [reply src/craftdef.cpp:1041]: Fixed

File: src/craftdef.cpp (hunk 1 above)
Comment (SmallJoker) [reply src/craftdef.cpp]: As you correctly noticed, I confused it with the iterator where it's in fact a pair. Thank you.

**Review by SmallJoker — APPROVED** [review]
Works.

**Review by sfan5 — APPROVED** [review]
Looks correct
