### PR TITLE
Fix overly strict bounds check in tiniergltf

### LINKED ISSUE #16589: glTF exported from Goxel cannot be parsed
### Luanti version

```true
Luanti 5.15.0-dev-a049174f1 (Linux)
Using LuaJIT 2.1.1753364724
Built by GCC 15.2
Running on Linux/6.17.2 x86_64
BUILD_TYPE=Release
RUN_IN_PLACE=1
USE_CURL=1
USE_GETTEXT=1
USE_SOUND=1
STATIC_SHAREDIR="."
STATIC_LOCALEDIR="locale"
```

### Operating system and version

Linux archnxt 6.17.2-arch1-1 #1 SMP PREEMPT_DYNAMIC Sun, 12 Oct 2025 12:45:18 +0000 x86_64 GNU/Linux

### CPU model

_No response_

### GPU model

_No response_

### Active renderer

_No response_

### Summary

The issue contains a reproduction project (mrp.zip) and the .gox file. Trying to use the exported glTF results in

```
2025-10-17 15:59:24: ERROR[Main]: Irrlicht: error parsing gltf: invalid glTF
2025-10-17 15:59:24: ERROR[Main]: Irrlicht: Attempt to load mesh failed: goxel_gltf_pyramid.gltf
```

Godot and Blender can import the glTF successfully. (in Godot the vertex colors stay, in Blender I don't know how to reexport them).

[mrp.zip](https://github.com/user-attachments/files/22972914/mrp.zip)

[pyramid.gox.zip](https://github.com/user-attachments/files/22972924/pyramid.gox.zip)

### Steps to reproduce

1. Create any model with Goxel (https://goxel.xyz/)
2. Export as glTF
3. Use the glTF as `mesh` in `core.register_node`
4. glTF cannot be parsed

### PR DESCRIPTION
**Pull request by appgurueu**
This makes sure that models exported by Goxel are not falsely rejected. It applies to exporters using strides more broadly.

A workaround is to add padding to the buffer and buffer view.

Fixes #16589 

## How to test

The model from the reproducer in the linked issue should show up:

Screenshot From 2025-10-17 19-01-52

### CODE REVIEW

**Comment by veprogames** [comment]
I can confirm that the glTF is parsed successfully:
 
grafik

The colors seem to be off. I don't know if this is out of scope of this PR. Is red an error/fallback color here?

Before this PR, when I imported the glTF into Blender and then reexported it via Blender, it was fully red.

Reference screenshot from Goxel:

grafik

**Comment by appgurueu** [comment]
> The colors seem to be off. I don't know if this is out of scope of this PR. Is red an error/fallback color here?

It should be out of scope for this bugfix, yes.

I'm not sure where the red is coming from, but in general we do not support model vertex colors at the moment: You need to use textures instead.

**Comment by veprogames** [comment]
In my eyes this can be merged since it fixes #16589 .

File: lib/tiniergltf/tiniergltf.hpp [hunk 1]
```diff
@@ -1252,10 +1258,12 @@ struct GlTF {
...
 				check(*view.byteStride % accessor.componentSize() == 0);
-			check(byteOffset < view.byteLength);
-			// Use division to avoid overflows.
+
 			const auto effective_byte_stride = view.byteStride.value_or(accessor.elementSize());
-			check(count <= (view.byteLength - byteOffset) / effective_byte_stride);
+			// Want: (count-1) * effective_byte_stride + accessor.elementSize() + byteOffset <= view.byteLength
+			// so the last item is still in-bounds and can be read. Be careful to avoid wraparound.
+			const auto remaining_bytes = checkedSub(checkedSub(view.byteLength, byteOffset), accessor.elementSize());
+			check((remaining_bytes/effective_byte_stride) + 1 >= count);
```
Comment (SmallJoker) [inline lib/tiniergltf/tiniergltf.hpp]: Where does the +1 (or -1 in the comment above) come from? I don't know much about this code, and this generic function makes it quite hard to comprehend what we're doing here. Thus, I'd appreciate it if you could add a few in-line comments to help better understanding.

EDIT: Apparently this function is to make sure there's enough bytes to read. Wouldn't `check(remaining_bytes >= effective_byte_stride * (count - 1));` be more intuitive? Sure, that would need special handling for `count == 0`, assuming that is what you'd like to check for.

File: lib/tiniergltf/tiniergltf.hpp [hunk 2]
```diff
@@ -1252,10 +1258,12 @@ struct GlTF {
 			const BufferView &view = bufferViews->at(bufferView);
 			if (view.byteStride.has_value())
 				check(*view.byteStride % accessor.componentSize() == 0);
-			check(byteOffset < view.byteLength);
-			// Use division to avoid overflows.
+
 			const auto effective_byte_stride = view.byteStride.value_or(accessor.elementSize());
-			check(count <= (view.byteLength - byteOffset) / effective_byte_stride);
+			// Want: (count-1) * effective_byte_stride + accessor.elementSize() + byteOffset <= view.byteLength
+			// so the last item is still in-bounds and can be read. Be careful to avoid wraparound.
```
Comment (sfan5) [inline lib/tiniergltf/tiniergltf.hpp]:
```suggestion
			// so the last item is still in-bounds and can be read. Be careful to avoid underflow.
```

File: lib/tiniergltf/tiniergltf.hpp (hunk 1 above)
Comment (appgurueu) [reply lib/tiniergltf/tiniergltf.hpp]: This is effectively `(count-1) * effective_byte_stride + accessor.elementSize() + byteOffset <= view.byteLength` as the "Want:" comment says, but rearranged so that nothing bad can happen if the result of an operation gets too large and wraps around (or if `count == 0`).

Actually `count == 0` should be impossible do to prior validation, but a checked sub wouldn't hurt.

I guess I can write it in a more readable fashion if I introduce a `checkedMul`.

File: lib/tiniergltf/tiniergltf.hpp (hunk 2 above)
Comment (appgurueu) [reply lib/tiniergltf/tiniergltf.hpp]: hmm i think wraparound is a good term since this is unsigned arithmetic mod 2^n

File: lib/tiniergltf/tiniergltf.hpp (hunk 1 above)
Comment (appgurueu) [reply lib/tiniergltf/tiniergltf.hpp]: alright I've tried to refactor this a little: https://github.com/luanti-org/luanti/pull/16590/commits/ad0c19bdb3347d9b2f3fa8eecafb01003adc31de
