### PR TITLE
Textures: Load base pack only as last fallback

### LINKED ISSUE #8955: Game-specified player.png and player_back.png are ignored (engine textures override mod/game textures)
##### Minetest version

```
4271889ef832806e7bd57e552f15b24fdf162c8d-->
```

##### Summary

Game-specified `player.png` and `player_back.png` is ignored. Instead, these images are *always* the “ugly green thing with hat” images, no matter what you do.

Note these images are included in `textures/base/pack`

This is a regression compared to 5.0.1.

##### Steps to reproduce

* Disable the currently active texture pack (EDIT: added by SmallJoker)
* Create an empty dummy game
* Add a dummy mod which includes `player.png` and `player_back.png`
* Start game and change camera mode to see yourself

EXPECTED: You see your custom player images.
ACTUAL: You see the default player images (ugly green thing with hat).

##### Notifications

@paramat

### PR DESCRIPTION
**Pull request by SmallJoker**
Fixes #8955 by skipping the base texture pack for the initial media loading. If the texture does not exist by the time it's used first, it can be loaded from base pack as well.

## To do

Ready for Review

## How to test

1) Disable the currently active texture pack
2) Remove `player_back.png` and `player.png` from any mod that adds those but minimal
3) Use two new/different textures in `base/pack` to later tell the difference
4) Join a minimal world: The minimal game's textures are used
5) Remove the minimal textures as well
6) Join a minimal world: The base pack images are used
7) Finally remove the base pack textures
8) Generates dummy textures (sanity check, or you did something wrong)

### CODE REVIEW

File: src/client/tile.cpp [hunk 1]
```diff
@@ -122,9 +122,11 @@ std::string getImagePath(std::string path)
 
 	Utilizes a thread-safe cache.
 */
-std::string getTexturePath(const std::string &filename)
+std::string getTexturePath(const std::string &filename, bool *is_base_pack)
 {
 	std::string fullpath;
+	if (is_base_pack)
+		*is_base_pack = false;
```
Comment (SmallJoker) [inline src/client/tile.cpp]: There's no way to tell the source of the texture (in a sane way) after caching the path.
It's also not needed, though since this `is_base_pack` is only passed when initializing the textures the first time.

Comment (sfan5) [reply src/client/tile.cpp]: Please note this face in a comment.

Comment (SmallJoker) [reply src/client/tile.cpp]: Done
