### PR TITLE
Make Mapgen (mostly) work multithreaded again

### LINKED ISSUE #8300: Segfault in noise.cpp
##### Issue type
 - Bug report
 
##### Minetest version
```
Minetest 5.0.0-dev-debug-111f1dc9-dirty (Linux)
```

##### OS / Hardware
Operating system: Linux Mint 19
CPU:Intel(R) Core(TM) i5-2400 CPU @ 3.10GHz

##### Summary
Segfault.  I'm getting a segfault on line 656 in noise.cpp, also line 668.  It goes away when I remove num_emerge_threads = 3 from minetest.conf.

##### Steps to reproduce
Put "num_emerge_threads = 3" into minetest.conf, moved across the world quickly until it crashed.  Took a minute or two, but seemed pretty consistent (I tried 5-6 times).  No crashes without num_emerge_threads.

### PR DESCRIPTION
**Pull request by sfan5**
<b>DO NOT SQUASH WHEN MERGING</b>

Problem: The objects managed by `BiomeManager`, `OreManager`, `DecorationManager` and `SchematicManager` are not thread-safe at all, because:
* ore generation code caches noise as a member variable
* schematic may change loaded schematic data for rotation during placing
* many more

Solution: Create a copy of the managers for each mapgen thread, the implementation of the objects can then freely modify its member variables.

-- Why not teach the implementation to be thread-safe then?
This is unfortunately not as easy and likely requires a larger refactoring\*. You can't just e.g. mark the member variables `thread_local`. So instead I opted for creating a copy of everything, which is guaranteed to work fine with the current code.
The whole thing is misdesigned anyway, it mixes the ore/deco/... settings (which could easy be constant and shared between all mapgens) with mutable implementation details such as cached noise buffers.

\* `ObjDefManager` is also not const correct at all, you can receive mutable references from a `const ObjDefManager&`. This PR does not fix that.

## Consequences

fixes #8300
It is possible to safely run with `num_emerge_threads > 1` again, though doing so raises the probability of the following appearing again:

The infamous y=48 bug ~~(#1755, #5125)~~ [mgv7, reproducible 100% with `num_emerge_threads = 12` here]
pic

General decoration weirdness on chunk boundaries(?)
pic

With more sane thread values (e.g. `num_emerge_threads = 2`), these issues are exceedingly rare. So perhaps multiple emerge threads can be enabled by default again soon.

## How to test

Test everything related to mapgen, including:
* Custom biome mods (in particular ones that overwrite biomes)
* Using Lua mapgens
* Any mapgen-related Lua API functions
* test with `num_emerge_threads` > 1

### CODE REVIEW

**Comment by sfan5** [comment]
The general thread unsafeness (in this case: race condition for noise creation) has been present since the very first implementation(s): https://github.com/minetest/minetest/commit/dcbb95338a9b0e2c5c95fcfc6eeceb9d6d93f320#diff-b4aa9def38b10274e96fd012895653f9R248
The particular crash in #8300 though is caused by https://github.com/minetest/minetest/commit/5c1edc58ab2abe8bc1f1bbcbb2f30a5899586968 which adds code that swaps out the noise at runtime.

**Comment by nerzhul** [comment]
nice to see you are working on mutithread fixes

File: src/mapgen/mg_decoration.cpp [hunk 1]
```diff
@@ -269,9 +276,42 @@ size_t Decoration::placeDeco(Mapgen *mg, u32 blockseed, v3s16 nmin, v3s16 nmax)
 }
 
 
+void Decoration::cloneTo(Decoration *def) const
```
Comment (nerzhul) [inline src/mapgen/mg_decoration.cpp:279]: just a question, why implementing clone and not a copy operator directly ?

File: src/emerge.cpp [hunk 2]
```diff
@@ -183,14 +194,67 @@ EmergeManager::~EmergeManager()
...
+	}
+}
+
+
+EmergeParams *EmergeManager::createEmergeParams()
+{
+	EmergeParams *p = new EmergeParams();
+	assert(p);
+
+	p->ndef = ndef;
```
Comment (nerzhul) [inline src/emerge.cpp:246]: can we have a constructor for this object instead of a such affectation outside of the object scope ?
It will be more maintainable like this

File: src/emerge.cpp [hunk 3]
```diff
@@ -183,14 +194,67 @@ EmergeManager::~EmergeManager()
...
 void EmergeManager::initMapgens(MapgenParams *params)
 {
 	FATAL_ERROR_IF(!m_mapgens.empty(), "Mapgen already initialised.");
 
 	mgparams = params;
 
-	for (u32 i = 0; i != m_threads.size(); i++)
-		m_mapgens.push_back(Mapgen::createMapgen(params->mgtype, params, this));
+	for (u32 i = 0; i != m_threads.size(); i++) {
+		EmergeParams *p = createEmergeParams();
```
Comment (nerzhul) [inline src/emerge.cpp:233]: i suggest to create EmergeParams on the stack and not the heap, it will be better in terms of memory manage and we don't need to transport the pointer everywhere

File: src/emerge.cpp [hunk 4]
```diff
@@ -183,14 +194,67 @@ EmergeManager::~EmergeManager()
...
+	EmergeParams *p = new EmergeParams();
+	assert(p);
+
+	p->ndef = ndef;
+	p->enable_mapgen_debug_info = enable_mapgen_debug_info;
+
+	p->gen_notify_on = gen_notify_on;
+	p->gen_notify_on_deco_ids = &gen_notify_on_deco_ids;
+
+	p->biomemgr = biomemgr->clone();
```
Comment (nerzhul) [inline src/emerge.cpp:252]: i suggest that the pointers on these objects become just objects on stack and implement a copy operator instead of a cloning pointer interface.

File: src/mapgen/mg_decoration.cpp (hunk 1 above)
Comment (sfan5) [reply src/mapgen/mg_decoration.cpp:279]: The copy operator was already disabled on these classes, I assume to prevent accidentally copying them. So I implemented it as an explicit function call instead.

File: src/emerge.cpp (hunk 3 above)
Comment (sfan5) [reply src/emerge.cpp:233]: This is kinda complicated because the `Mapgen` takes ownership of the params passed to it.

File: src/mapgen/mg_decoration.cpp (hunk 1 above)
Comment (nerzhul) [reply src/mapgen/mg_decoration.cpp:279]: i think we should find why it's disabled and re-enable it instead of creating our own no ? :)

File: src/emerge.cpp (hunk 3 above)
Comment (nerzhul) [reply src/emerge.cpp]: MapGen can take a copy or we should share something with the thread copy itself ?

**Comment by paramat** [comment]
> The infamous y=48 bug (#1755, #5125)

#1755 is mgv6 only, and is not related to threads at all, that is simply the result of how mgv6 is coded to be inocmpatible with crossing a mapchunk border. For example the mudflow feature alone disallows crossing a mapchunk border.
#5125 is mgvalleys only, and is no longer valid as that was old mgvalleys code which was a horrible mess, a bug at y = 47/48 was not surprising and probably not related to threads. The bug was fixed but i also then completely rewrote the mapgen later.

However i accept that generally there may be some weirdness at mapchunk borders and overlapping areas with multiple emerge threads.

The code changes in this PR are mostly far beyond my understanding, being code architecture stuff, so i will not be qualified approve code changes, but i can test.

**Comment by paramat** [comment]
Looked through the changes, no objections to what you are doing here.

**Comment by sfan5** [comment]
> However i accept that generally there may be some weirdness at mapchunk borders and overlapping areas with multiple emerge threads.

Right. Any chance you could look into why this happens with mgv7 at some point?
As someone unfamiliar with the mapgen code I'd guess it's a problem with overgeneration (since the area the mapgen works on is one mapblock larger in each direction than the actually requested mapchunk).

File: src/mapgen/mg_decoration.cpp (hunk 1 above)
Comment (sfan5) [reply src/mapgen/mg_decoration.cpp:279]: Well I think it's still useful to prevent accidentally copying.

**Comment by tuedel** [comment]
Possibly related: https://github.com/minetest/minetest/issues/5618 https://github.com/minetest/minetest/issues/9357

**Comment by paramat** [comment]
pic

Ah i did not see the above image earlier, Github was acting strange and not loading some images.
>  I'd guess it's a problem with overgeneration (since the area the mapgen works on is one mapblock larger in each direction than the actually requested mapchunk).

Yes exactly that. All the other non-mgv6 mapgens overgenerate 1 up, 1 down too, do they also do this?
However, only mgv7 has a river generation loop that runs after the main generation loop, which might complicate things, i am intending to move the river generation code into the main generation loop, see #7878
The bug in the screenshot was reported in #9357 so may not be caused by this PR?

**Comment by sfan5** [comment]
> The bug in the screenshot above was reported in #9357 so may not be caused by this PR?

Yes, these are existing bugs. This PR just allows you to "experience" them again since `num_emerge_threads > 1` caused crashes before.

> To clarify, are you saying that this PR increases the chances of weirdness with multiple emerge threads, relative to before? Or are you saying the old weirdnesses will just be experienced again?

The latter. From my testing it looks like the more emerge threads you use, the higher the likeliness of these old bugs reappearing.

**Comment by nerzhul** [comment]
At least the crash is fixed, for the emerge part i may work on it after this PR is merged to rewrite the emerge workflow which is quite fine but not so easy to understand.
