### PR TITLE
script: Move SAO usability check so that it covers all functions

### LINKED ISSUE #9684: Segfault in SendPlayerHP
##### Minetest version
```
5.3.0-dev-ba3587e77
```

##### OS / Hardware
Operating system: Ubuntu 18.04
CPU: i

##### Summary

```
Server::SendPlayerHP (this=this@entry=0x7fffffffd810, peer_id=<optimized out>)
    at /home/minetest/minetest_stable/src/server.cpp:1817
1817		SendHP(peer_id, playersao->getHP());
#0  Server::SendPlayerHP (this=this@entry=0x7fffffffd810, 
    peer_id=<optimized out>)
    at /home/minetest/minetest_stable/src/server.cpp:1817
#1  0x00005555558a3838 in Server::SendPlayerHPOrDie (this=0x7fffffffd810, 
    playersao=playersao@entry=0x7fffe727aa80, reason=...)
    at /home/minetest/minetest_stable/src/server.cpp:1374
#2  0x0000555555711851 in ObjectRef::l_punch (L=0x40000378, 
    L@entry=<error reading variable: value has been optimized out>)
    at /home/minetest/minetest_stable/src/script/lua_api/l_object.cpp:200
#3  0x00005555556c77c6 in script_exception_wrapper (L=0x40000378, 
    f=<optimized out>)
    at /home/minetest/minetest_stable/src/script/common/c_internal.cpp:38
#4  0x00007ffff763ee97 in ?? ()
   from /usr/lib/x86_64-linux-gnu/libluajit-5.1.so.2
#5  0x00007ffff768c27c in lua_pcall ()
   from /usr/lib/x86_64-linux-gnu/libluajit-5.1.so.2
#6  0x00005555556cb6c7 in ScriptApiBase::runCallbacksRaw (
    this=0x555555c72890, nargs=1, mode=RUN_CALLBACKS_MODE_FIRST, 
    fxn=0x5555559184f0 <ScriptApiEnv::environment_Step(float)::__FUNCTION__> "environment_Step")
    at /home/minetest/minetest_stable/src/script/cpp_api/s_base.cpp:273
#7  0x00005555556ce926 in ScriptApiEnv::environment_Step (
    this=0x555555c72860, dtime=0.100000001)
    at /home/minetest/minetest_stable/src/script/cpp_api/s_env.cpp:55
#8  0x00005555558ca724 in ServerEnvironment::step (this=0x555556458a40, 
    dtime=0.100000001)
    at /home/minetest/minetest_stable/src/serverenvironment.cpp:1383
#9  0x00005555558b5485 in Server::AsyncRunStep (this=0x7fffffffd810, 
    initial_step=initial_step@entry=false)
    at /home/minetest/minetest_stable/src/server.cpp:546
#10 0x00005555558b78be in ServerThread::run (this=0x555555c444c0)
    at /home/minetest/minetest_stable/src/server.cpp:108
#11 0x0000555555741133 in Thread::threadProc (thr=0x555555c444c0)
    at /home/minetest/minetest_stable/src/threading/thread.cpp:196
#12 0x00007ffff61526df in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#13 0x00007ffff6f956db in start_thread (arg=0x7fffeeb0b700)
    at pthread_create.c:463
#14 0x00007ffff580f88f in clone ()
    at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
A debugging session is active.
```

##### Steps to reproduce
* Unknown. Happens when running CTF

### PR DESCRIPTION
**Pull request by sfan5**
oops
fixes #9684

crash-relevant functions (when called on a player):
* set_pos
* move_to
* punch
* set_hp

## To do

This PR is a Ready for Review.

### CODE REVIEW

File: src/script/lua_api/l_object.cpp [hunk 1]
```diff
@@ -50,6 +50,8 @@ ObjectRef* ObjectRef::checkobject(lua_State *L, int narg)
 ServerActiveObject* ObjectRef::getobject(ObjectRef *ref)
 {
 	ServerActiveObject *co = ref->m_object;
+	if (co && co->isGone())
```
Comment (SmallJoker) [inline src/script/lua_api/l_object.cpp:53]:
```suggestion
	if (!co || co->isGone())
```

File: src/script/lua_api/l_object.cpp [hunk 2]
```diff
@@ -72,8 +72,6 @@ PlayerSAO* ObjectRef::getplayersao(ObjectRef *ref)
 		return NULL;
 	if (obj->getType() != ACTIVEOBJECT_TYPE_PLAYER)
 		return NULL;
-	if (obj->isGone())
-		return NULL;
 	return (PlayerSAO*)obj;
```
Comment (SmallJoker) [inline src/script/lua_api/l_object.cpp:75]: How about Peer ID checks here?

Comment (sfan5) [reply src/script/lua_api/l_object.cpp:75]: Peer ID invalidation always happens together with marking the object as "gone":
https://github.com/minetest/minetest/blob/4e2473ec493689c3bc7d619fe17ee31c7f20945b/src/server/player_sao.cpp#L555-L559
