### PR TITLE
Use player as starting point instead of camera when pointing node

### LINKED ISSUE #8238: Less reach in 3rd person view mode
##### Issue type
 - Bug report
 
##### Minetest version
```
0.4.17.1 (+?)
```

##### Summary
https://forum.minetest.net/viewtopic.php?f=6&t=20929
"I don't know how to describe this well but uh, I used the 3rd person view and for some reason, I can not place anything above, can only place something one block apart in front of me, and can not break anything below unless I am flying. Perhaps I accidentally changed some settings but I don't recall altering the 3rd person view. Any thoughts?"

##### Steps to reproduce
Set FOV to something like 100 and enter 3rd person mode ingame

### PR DESCRIPTION
**Pull request by srifqi**
Use player as starting point instead of camera when pointing node so that we have same pointing area on both camera modes.

Fixes #8238.

### CODE REVIEW

File: src/client/game.cpp [hunk 1]
```diff
@@ -2977,22 +2982,21 @@ void Game::processPlayerInteraction(f32 dtime, bool show_hud, bool show_debug)
...
-		shootline = core::line3d<f32>(camera_position,camera_position);
+		shootline = core::line3d<f32>(camera_position, camera_position);
 	}
 
 #ifdef HAVE_TOUCHSCREENGUI
 
 	if ((g_settings->getBool("touchtarget")) && (g_touchscreengui)) {
 		shootline = g_touchscreengui->getShootline();
 		// Scale shootline to the acual distance the player can reach
-		shootline.end = shootline.start
```
Comment (SmallJoker) [inline src/client/game.cpp]: `shootline.start` is needed here so that mobile players without the crosshair mode can point at the correct position.

Comment (srifqi) [reply src/client/game.cpp]: Will try.

Comment (srifqi) [reply src/client/game.cpp]: Done. This fix is inapplicable for non-crosshair input.

File: src/client/game.cpp [hunk 2]
```diff
@@ -2957,10 +2957,15 @@ void Game::processPlayerInteraction(f32 dtime, bool show_hud, bool show_debug)
 		hlist ? hlist->getItem(0).getDefinition(itemdef_manager) : itemdef_manager->get("");
 
 	v3f player_position  = player->getPosition();
+	v3f player_eye_position = player_position + player->getEyeOffset();
```
Comment (nerzhul) [inline src/client/game.cpp]: i think it's better to implement a Player::getEyePosition() and use it here, it can be useless in some other areas :)

**Comment by nerzhul** [comment]
as the change is relatively small and has been tested i think we can integrate it in #8361

File: src/client/game.cpp (hunk 2 above)
Comment (srifqi) [reply src/client/game.cpp]: Done. ```LocalPlayer::getEyePosition()``` is used instead.

File: src/client/game.cpp [hunk 3]
```diff
@@ -2977,11 +2982,11 @@ void Game::processPlayerInteraction(f32 dtime, bool show_hud, bool show_debug)
 	core::line3d<f32> shootline;
 
 	if (camera->getCameraMode() != CAMERA_MODE_THIRD_FRONT) {
-		shootline = core::line3d<f32>(camera_position,
-			camera_position + camera_direction * BS * d);
+		shootline = core::line3d<f32>(player_eye_position,
+			player_eye_position + camera_direction * BS * d);
 	} else {
 	    // prevent player pointing anything in front-view
```
Comment (DS-Minetest) [inline src/client/game.cpp]: Eww space indention. As you are also adding a space in the line below, could you do
```suggestion
		// prevent player pointing anything in front-view
```
?

Comment (paramat) [reply src/client/game.cpp]: Agreed.

Comment (srifqi) [reply src/client/game.cpp]: Sorry for late response. But, should I do or let other PR fixes this?

Comment (SmallJoker) [reply src/client/game.cpp]: I merged the PR because this request is somewhat trivial and the line was not touched in the patch. Create a PR if you want; not worth the effort IMO.

Comment (paramat) [reply src/client/game.cpp]: I agree, it's not important to fix, but if you want to fix it i'll merge the PR immediately.

Comment (srifqi) [reply src/client/game.cpp]: I'll just leave it as it is.
