### PR TITLE
Remove float vector range checks from scriptapi

### LINKED ISSUE #11742: Giving float vector with x outside of -2.14748e+06 < x < 2.14748e+06 as a function argument crashes server & Minetest returns such vectors
##### Minetest version
commit 80d12dbed
using irrlicht 1.9.0mt2
using lua 5.1.5

##### OS / Hardware

Operating system: x86_64
CPU: Intel something

##### Summary
```
2021-10-29 14:22:03: ERROR[Main]: ServerError: AsyncErr: ServerThread::run Lua: Invalid float vector dimension range 'x' (expected -2.14748e+06 < x < 2.14748e+06 got -2.14748e+06).
```

Note that being that far out of bounds as a player is not an issue per se – in fact, the “obvious” fix of limiting player positions to being inside mapgen boundaries by teleporting or pushing them inside or killing them would both not fix the underlying issue, break existing setups (there exist servers where players, structures, and entities existing out of bounds of the map generator is part of the normal gameplay – singlenode museums would be affected, for example) and is likely to introduce at least one exploitable bug (try to figure it out, but do not say I did not warn you). Not allowing players to drop items out of bounds will also not fix the underlying issue.

The code should simply not crash at this point, but issue a warning.

##### Steps to reproduce

1. Create a minetest_game world with a player.
2. Manually edit players.sqlite of a world, set the x,y,z coordinates of a player to -21474836 each.
3. Enter that world as that player.
4. Drop an item.
5. Crash.

There exists at least one way to get to such coordinates as a player without fiddling with the server player database (and a few more ways that I suspect, but have not verified), which I do not want to reveal here for the obvious reasons that a) it is not necessary to understand the issue b) griefers would probably start crashing minetest servers c) I want developers to fix the problem, not just remove the way that I used to trigger it.

### PR DESCRIPTION
**Pull request by sfan5**
fixes #11742 (fully)

this should not be backported since it's (marginally) higher risk than the existing fix

## To do

This PR is Ready for Review.

## How to test

same steps as #12396, still nothing should be happening

### CODE REVIEW

**Comment by SmallJoker** [comment]
The idea is good, but how would modders notice near-zero divisor errors in their code? At the very least, `nan`, `inf` and `-inf` should be disallowed/warned somehow.

File: src/staticobject.cpp [hunk 1]
```diff
@@ -28,12 +28,12 @@ StaticObject::StaticObject(const ServerActiveObject *s_obj, const v3f &pos_):
...
 }
 
-void StaticObject::serialize(std::ostream &os)
+void StaticObject::serialize(std::ostream &os) const
 {
 	// type
 	writeU8(os, type);
 	// pos
-	writeV3F1000(os, pos);
+	writeV3F1000(os, clampToF1000(pos));
```
Comment (SmallJoker) [inline src/staticobject.cpp:36]: Might it be better to clamp directly in `writeV3F1000` ?

**Review by SmallJoker — APPROVED** [review]
Works, looks good.
