### PR TITLE
Fix short_description fallback order

### LINKED ISSUE #10911: get_short_description's description finding algorithm is flawed
##### Minetest version
```
5.4.0-dev
```

The `lua_api.txt` says:

```
 * `get_short_description()`: returns the short description.
     * Unlike the description, this does not include new lines.
     * The engine uses the same as this function for short item descriptions.
     * Fields for finding the short description, in order:
         * `short_description` in item metadata (See [Item Metadata].)
         * `short_description` in item definition
         * first line of the description (See `get_description()`.)
```

It behaves as promised, and there is no bug,

However, I think this order of finding the short description is a flawed design. If an item has the metadata field `description` set, it is ignored by `get_short_description`, so it will instead use the node definition's `description`. This is awkward and does not make sense IMHO.

Here's how it *should* be:

```
     * Fields for finding the short description, in order:
         * `short_description` in item metadata (See [Item Metadata].)
         * `short_description` in item definition
         * first line of `description` in item metadata (See `get_description()`.)  <<< NEW!
         * first line of `description` in item definition (See `get_description()`.)
```

Since `short_description` is new in 5.4.0-dev, I think it should be fixed before release.

### PR DESCRIPTION
**Pull request by rubenwardy**
`short_description` was always set on the item definition,
meaning that `description` in the metadata was never used.

Fixes #10911

## To do

This PR is  Ready for Review.

## How to test

See that the devtest unit tests pass

(setting: `devtest_unittests_autostart = true`)

### CODE REVIEW

File: builtin/game/item.lua [hunk 1]
```diff
@@ -665,6 +665,10 @@ function core.itemstring_with_color(item, colorstring)
 	return stack:to_string()
 end
 
+function core.get_short_description(item)
+	return ItemStack(item):get_short_description()
+end
```
Comment (SmallJoker) [inline builtin/game/item.lua:670]: Why do we need a function for this?

Comment (rubenwardy) [reply builtin/game/item.lua:670]: I can just move this to the documentation instead. I wanted to make it harder for mods to check the def than to do it correctly

Comment (sfan5) [reply builtin/game/item.lua:670]: Yes, please do.

File: doc/lua_api.txt [hunk 2]
```diff
@@ -6039,18 +6039,18 @@ an itemstring, a table or `nil`.
...
         * item name
-* `get_short_description()`: returns the short description.
+* `get_short_description()`: returns the short description or nil.
     * Unlike the description, this does not include new lines.
-    * The engine uses the same as this function for short item descriptions.
     * Fields for finding the short description, in order:
         * `short_description` in item metadata (See [Item Metadata].)
         * `short_description` in item definition
-        * first line of the description (See `get_description()`.)
+        * first line of the description (From item meta or def, see `get_description()`.)
```
Comment (SmallJoker) [inline doc/lua_api.txt:6052]: Where does this "first line" trimming happen now?

Comment (rubenwardy) [reply doc/lua_api.txt:6052]: The first line of the description, as returned by get_description()

**Review by SmallJoker — APPROVED** [review]
As discussed on IRC.
