### PR TITLE
Move drawing of wield tool into a dedicated step of the pipeline

### LINKED ISSUE #12826: Wieldhand is cut off by water surface
##### Minetest version

```
Minetest 5.7.0-dev-525fc3833 (Linux)
```
But I can reproduce this since <https://github.com/minetest/minetest/commit/ff6dcfea82974df6db5a557e31aaddb6bdb7a71f> (which removed the call to clear the depth buffer).

##### Summary

If some node surface is near the wieldhand, it can be rendered above the wieldhand. If it's a semi-transparent surface it looks like my hand was cut off.

##### Steps to reproduce

screenshot_20221001_014528

cc @x2048

### LINKED ISSUE #13293: MT 5.7 - wield scaled items are cropped on large screens
##### Minetest version
5.7

##### OS / Hardware
Operating system: macOS 13.2.1
CPU: X86-64

##### Summary

MT 5.7 - wield scaled items are cropped on large screens

screenshot_20230306_155404_1920

##### Steps to reproduce
1. Get a big screen/resolution
2. Wield item with `wield_scale` larger than 1

### LINKED ISSUE #13329: MT 5.7 Particle transparency z-index
##### Minetest version

```
Minetest 5.7.0-dev-9ef3c8c (OSX)
```

##### OS / Hardware

Operating system: macOS 13.2.1
CPU: X86-64

OpenGL version: 2.1

##### Summary
 I don't know what the right term for this is (in English) but the particle transparency is cropping through the wield item - this is not happening in 5.6.1

##### Steps to reproduce
Refer to video https://youtu.be/OW4XzIvqKrA

### PR DESCRIPTION
**Pull request by x2048**
Fixes #13329, fixes #13293, fixes #12826  by drawing the wield tool/hand after the post-processing effects.

This also removes the visual effects for the wield tool/hand (bloom, dynamic exposure etc.), restoring the 5.6 behavior.

## To do

This PR is Ready for Review.

## How to test

1. Enable effects and enter any game
2. Fly through blocks / leaves / water
3. See the hand NOT being clipped / cut by the 3D scene.
4. See also the referenced bugs

### CODE REVIEW

**Comment by x2048** [comment]
Note: the changes in camera.cpp are a revert of ff6dcfea82974df6db5a557e31aaddb6bdb7a71f

**Comment by Zughy** [comment]
(@x2048 note for the future: GitHub doesn't recognise the pattern "fixes n1, n2, n3", linking just n1)

**Review by sfan5 — APPROVED** [review]
works

File: src/client/camera.cpp [hunk 1]
```diff
@@ -635,11 +635,14 @@ void Camera::wield(const ItemStack &item)
...
 {
+	// Clear Z buffer so that the wielded tool stays in front of world geometry
+	m_wieldmgr->getVideoDriver()->clearBuffers(video::ECBF_DEPTH);
+
 	// Draw the wielded node (in a separate scene manager)
 	scene::ICameraSceneNode* cam = m_wieldmgr->getActiveCamera();
 	cam->setAspectRatio(m_cameranode->getAspectRatio());
 	cam->setFOV(72.0*M_PI/180.0);
-	cam->setNearValue(40); // give wield tool smaller z-depth than the world in most cases.
+	cam->setNearValue(10); // give wield tool smaller z-depth than the world in most cases.
```
Comment (Desour) [inline src/client/camera.cpp:645]: The comment was added in https://github.com/minetest/minetest/commit/ff6dcfea82974df6db5a557e31aaddb6bdb7a71f. I guess it's now outdated.

**Comment by Desour** [comment]
Tested. The wielded item is no longer colored under water.

**Comment by Desour** [comment]
(You could fix this by drawing post effect after wield.
FYI, for some other thing I'm working on (<https://github.com/Desour/minetest/tree/posteffect_clip>), it would be nice to instead color the wield item, but draw it after the posteffect color. Sadly, idk yet how this can be done with the irrlicht and pipeline stuff.)

File: src/client/camera.cpp (hunk 1 above)
Comment (x2048) [reply src/client/camera.cpp]: Removed

**Review by Desour — APPROVED** [review]
Tested, works. :+1:
