### PR TITLE
Clamp hotbar selection to slots that exist

### LINKED ISSUE #11525: You can move your hotbar selection into a section of the inventory that doesn't exist
##### Minetest version

```
5.5.0 - 2866918f3
```

##### OS / Hardware

Operating system: windows 10
CPU: ryzen 5600x

##### Summary

You can move your hotbar selection into a section of the inventory that doesn't exist if the set_size is less than hud_set_hotbar_itemcount which creates a hard crash when you press the drop button with no error catch

##### Steps to reproduce

player:get_inventory():set_size("main", 1)
player:hud_set_hotbar_itemcount(10)

press drop button

### PR DESCRIPTION
**Pull request by Emojigit**
Limits the wield index to existing slots (i.e. <= main list size).

Fixes #11525

## To do

This PR is Ready for Review.

- [x] Client-side checks
- [x] Server-side checks

### Client-side

Run the following Lua snippet:

```lua
local player = minetest.get_player_by_name("singleplayer")
player:get_inventory():set_size("main", 1)
player:hud_set_hotbar_itemcount(10)
```

Your selection range should be limited to 1 instead of 10.

### Server-side network checking

Undo the changes to `client/game.cpp` and run the above script.

When you roll your mouse wheel so the selection is beyond the list size, the server will print a log saying "tried to access item=# out of main list size=#; ignoring."

### Server-side `hud_get_hotbar_itemcount()`

Run the devtest unittests. `"test_player_hotbar_clamp"` should pass.

### CODE REVIEW

File: src/client/game.cpp [hunk 1]
```diff
@@ -2190,8 +2190,11 @@ void Game::processItemSelection(u16 *new_playeritem)
 
 	/* Item selection using mouse wheel
 	 */
+	Inventory *inventory = &player->inventory;
+	InventoryList *mainlist = inventory->getList("main");
+	s32 mainlist_size = (mainlist == nullptr) ? PLAYER_INVENTORY_SIZE : mainlist->getSize();
```
Comment (Emojigit) [inline src/client/game.cpp:2195]: Is it correct to fall back to `PLAYER_INVENTORY_SIZE` if the main list is undefined / not yet sent?

See also: https://github.com/minetest/minetest/pull/11926#discussion_r790147379

File: doc/lua_api.md [hunk 2]
```diff
@@ -8225,7 +8225,9 @@ child will follow movement and rotation of that bone.
     * See `hud_set_flags` for a list of flags that can be toggled.
 * `hud_set_hotbar_itemcount(count)`: sets number of items in builtin hotbar
     * `count`: number of items, must be between `1` and `32`
+    * If `count` exceeds the `"main"` list size, the list size will be used instead.
 * `hud_get_hotbar_itemcount()`: returns number of visible items
+    * This value is not clamped by the `"main"` list size.
```
Comment (sfan5) [inline doc/lua_api.md:8230]: so it's clamped when setting but not when getting?
doesn't seem useful to behave like this

File: src/client/game.cpp (hunk 1 above)
Comment (sfan5) [reply src/client/game.cpp:2195]: If `mainlist` is not defined I would simply not process hotbar changes

File: src/network/serverpackethandler.cpp [hunk 3]
```diff
@@ -861,6 +861,18 @@ void Server::handleCommand_PlayerItem(NetworkPacket* pkt)
 		return;
 	}
 
+	Inventory *inventory = &player->inventory;
+	InventoryList *mainlist = inventory->getList("main");
+	u32 mainlist_size = (mainlist == nullptr) ? PLAYER_INVENTORY_SIZE : mainlist->getSize();
```
Comment (sfan5) [inline src/network/serverpackethandler.cpp:866]: same here

File: doc/lua_api.md (hunk 2 above)
Comment (Emojigit) [reply doc/lua_api.md]: Fixed in a2e0345d4

File: src/client/game.cpp (hunk 1 above)
Comment (Emojigit) [reply src/client/game.cpp]: Fixed in 10e8aab1c

File: src/network/serverpackethandler.cpp (hunk 3 above)
Comment (Emojigit) [reply src/network/serverpackethandler.cpp]: Fixed in 10e8aab1c

File: src/client/game.cpp [hunk 4]
```diff
@@ -2190,8 +2190,12 @@ void Game::processItemSelection(u16 *new_playeritem)
...
 	/* Item selection using mouse wheel
 	 */
+	Inventory *inventory = &player->inventory;
+	InventoryList *mainlist = inventory->getList("main");
+	if (mainlist == nullptr)
+		return;
 	*new_playeritem = player->getWieldIndex();
-	u16 max_item = MYMIN(PLAYER_INVENTORY_SIZE - 1,
+	u16 max_item = MYMIN((s32) mainlist->getSize() - 1,
 		    player->hud_hotbar_itemcount - 1);
```
Comment (SmallJoker) [inline src/client/game.cpp:2199]: 1. `Player` contains `inventory` and `hud_hotbar_itemcount`
2. This code is technically duplicated: game.cpp (here), hud.cpp, l_object.cpp

Hence it would make sense to add a dedicated function to `Player` that retrieves the correctly limited hotbar count.

File: games/devtest/mods/unittests/player.lua [hunk 5]
```diff
@@ -84,3 +84,23 @@ local function run_player_add_pos_tests(player)
...
 
+--
+-- Hotbar selection clamp
+--
+local function run_player_hotbar_clamp_tests(player)
+	local inv = player:get_inventory()
+	local old_inv_size = inv:get_size("main")
+	local old_bar_size = player:hud_get_hotbar_itemcount()
+
+	inv:set_size("main", 5)
```
Comment (sfan5) [inline games/devtest/mods/unittests/player.lua:95]: not that it matters much but this potentially deletes items from the player's inventory, no?

File: src/client/game.cpp [hunk 6]
```diff
@@ -2190,8 +2190,12 @@ void Game::processItemSelection(u16 *new_playeritem)
 
 	/* Item selection using mouse wheel
 	 */
+	Inventory *inventory = &player->inventory;
+	InventoryList *mainlist = inventory->getList("main");
+	if (mainlist == nullptr)
```
Comment (sfan5) [inline src/client/game.cpp:2195]:
```suggestion
	InventoryList *mainlist = player->inventory.getList("main");
	if (!mainlist)
```

File: src/player.cpp [hunk 7]
```diff
@@ -88,6 +88,12 @@ void Player::setWieldIndex(u16 index)
 	m_wield_index = MYMIN(index, mlist ? mlist->getSize() : 0);
 }
 
+u16 Player::getWieldIndex()
+{
+	const InventoryList *mlist = inventory.getList("main");
+	return MYMIN(m_wield_index, mlist ? mlist->getSize() : 0);
```
Comment (sfan5) [inline src/player.cpp:94]: prefer `std::min`

File: src/client/game.cpp (hunk 4 above)
Comment (Emojigit) [reply src/client/game.cpp]: Done in 22e5e8b92

File: src/player.cpp (hunk 7 above)
Comment (Emojigit) [reply src/player.cpp]: Done in b4f826583

File: games/devtest/mods/unittests/player.lua (hunk 5 above)
Comment (Emojigit) [reply games/devtest/mods/unittests/player.lua:96]: Fixed in f8ac49787

File: src/network/serverpackethandler.cpp [hunk 8]
```diff
@@ -861,6 +861,18 @@ void Server::handleCommand_PlayerItem(NetworkPacket* pkt)
 		return;
 	}
 
+	Inventory *inventory = &player->inventory;
+	InventoryList *mainlist = inventory->getList("main");
+	u32 mainlist_size = (mainlist == nullptr) ? 0 : mainlist->getSize();
```
Comment (sfan5) [inline src/network/serverpackethandler.cpp:866]:
```suggestion
	auto *mainlist = player->inventory.getList("main");
	u32 mainlist_size = mainlist ? mainlist->getSize() : 0;
```

File: src/player.cpp [hunk 9]
```diff
@@ -157,6 +162,12 @@ void Player::clearHud()
 	}
 }
 
+u16 Player::getMaxHotbarItemcount()
+{
+	InventoryList *mainlist = inventory.getList("main");
+	return mainlist ? std::min((s32) mainlist->getSize(), hud_hotbar_itemcount) : 0;
```
Comment (sfan5) [inline src/player.cpp:168]: make more sense to cast the list size to u16 here IMO

**Review by sfan5 — APPROVED** [review]
lgtm otherwise

File: src/player.h [hunk 10]
```diff
@@ -247,6 +247,9 @@ class Player
 	u32 hud_flags;
 	s32 hud_hotbar_itemcount;
 
+	// Get proper max HUD itemcount
```
Comment (sfan5) [inline src/player.h:250]:
```suggestion
	// Get actual usable number of hotbar items (clamped to size of "main" list)
```

Comment (sfan5) [reply src/player.h:250]: could also remove `getHotbarItemcount` to make it clearer that it's not intended way of accessing it

File: src/network/serverpackethandler.cpp (hunk 8 above)
Comment (Emojigit) [reply src/network/serverpackethandler.cpp]: Applied changes. However, I wonder when should I use “auto” in place of exact declarations.

File: src/player.cpp (hunk 9 above)
Comment (Emojigit) [reply src/player.cpp]: Done in d5039d509

File: src/player.h (hunk 10 above)
Comment (Emojigit) [reply src/player.h]: I see getHotbarItemcount using somewhere this internal value is needed, so I am keeping it.

Comment (Emojigit) [reply src/player.h]: Some incorrect use of getHotbarItemcount are fixed in 2f5a13f0e
