### PR TITLE
[NO SQUASH] Mapgen: Fix Y biome boundary regression

### LINKED ISSUE #15485: Grass generates 1 node below water
### Luanti version

```true
5.10.0
```

### Irrlicht device

_No response_

### Operating system and version

GNU/Linux

### CPU model

_No response_

### GPU model

_No response_

### Active renderer

_No response_

### Summary

Since Luanti 5.10.0, newly generated maps start with grass below water at the default water level. This happens in Minetest Game and Repixture.

**This is a regression compared to 5.9.0.**

### Steps to reproduce

1. Start Minetest Game and generate a new map (v7)
2. Fly to a beach with grass
3. Look below the water at water level

There should by any node *but* dirt-with-grass, but there is dirt-with-grass.

### PR DESCRIPTION
**Pull request by SmallJoker**
Fixes #15485, a regression from #15116.

See commit description.

## To do

This PR is Ready for Review.

## How to test

1. New mgv7 world using Minetest Game. Seed = 142552402686142933
2. `/teleport -5990,1,2327`
3. You're standing inside the biome `deciduous_forest` (water level, y=0)
4. The node below you is `deciduous_forest_shore`
5. worldedit: `//lua print(dump(core.get_biome_data(core.get_player_by_name("singleplayer"):get_pos())))`
6. worldedit: `//lua print(dump(core.get_biome_name(23)))`

Even though Lua does report the same biome data for master and PR (or older versions for that matter), the mapgen used the wrong biome to generate the node below water level.

Compare the generated world between 5.9.1 and master. Tip: `backend = dummy` in `world.mt`.

### CODE REVIEW

File: src/mapgen/mg_biome.cpp [hunk 1]
```diff
@@ -54,7 +40,8 @@ BiomeManager::BiomeManager(Server *server) :
 	b->m_nodenames.emplace_back("ignore");
 	b->m_nodenames.emplace_back("ignore");
 	b->m_nodenames.emplace_back("ignore");
-	m_ndef->pendNodeResolve(b);
+	if (m_ndef) // nullptr in TestMapgen
```
Comment (sfan5) [inline src/mapgen/mg_biome.cpp:43]: we have a test gamedef in the tests do there's no need for this special case

File: src/mapgen/mg_biome.cpp [hunk 2]
```diff
@@ -135,13 +124,15 @@ BiomeGenOriginal::BiomeGenOriginal(BiomeManager *biomemgr,
...
+	// Calculate cache of Y transition points. For downwards scanning only!
 	std::vector<s16> values;
 	values.reserve(m_bmgr->getNumObjects() * 2);
 	for (size_t i = 0; i < m_bmgr->getNumObjects(); i++) {
 		Biome *b = (Biome *)m_bmgr->getRaw(i);
 		values.push_back(b->max_pos.Y);
-		values.push_back(b->min_pos.Y);
+		// Optimization: biomes often have perfect Y transitions, resulting in
+		// unnecessary Y pairs. i.e. when (biome A min Y) == (biome B max Y + 1)
+		values.push_back(std::max<s32>((s32)b->min_pos.Y - 1, -MAX_MAP_GENERATION_LIMIT));
```
Comment (sfan5) [inline src/mapgen/mg_biome.cpp:135]: we have ``std::unique`` for that already?

Comment (SmallJoker) [reply src/mapgen/mg_biome.cpp:135]: `max_pos.Y` and `min_pos.Y` are both inclusive, which means that in the following example with 2 biomes (A (above) and B (below)), there are transitions which we don't care about
```
y = max_pos.Y  (first position of biome A) IMPORTANT
 X
 X
 (span of A)
 X
 X
y = min_pos.Y  (last position of biome A) (superfluous)
y = max_pos.Y  (first position of biome B) IMPORTANT
 X
 X
 (span of B)
 X
 X
y = min_pos.Y  (last position of biome B) (superfluous)
```

**Comment by SmallJoker** [comment]
Does anyone have an ARM macOS device? I'd like to know why the unittests fail there. I could dump the values to stdout and re-run the buildbot, but that's not efficient to find the root cause.

File: src/mapgen/mg_biome.cpp (hunk 2 above)
Comment (sfan5) [reply src/mapgen/mg_biome.cpp]: as a practical example we collect positions
`{3000, 2000, 2000, 1000, 1000, 0, 0, -31000}`
and then by running unique on it we get
`{3000, 2000, 1000, 0, -31000}`
or do you mean something else?

Comment (SmallJoker) [reply src/mapgen/mg_biome.cpp]: That is correct. Before you might have
```
{3000, 256, 255, 1, 0, -255, -256, -31000 }
 ^       ^  ^    ^  ^     ^  ^          ^
 ^^^^^^^^^  |    |  |     |  |          |  biome A
            ^^^^^^  |     |  |          |  biome B
                    ^^^^^^^  |          |  biome C
                             ^^^^^^^^^^^^  biome D
```
which can be reduced to
```
{3000, 255, 0, -256 }
 ^     ^    ^  ^     
 ^^^^^^|    |  |     biome A
       ^^^^^|  |     biome B
            ^^^|     biome C
               ^^^^^ biome D (until < -31000)
```
Since we're generating biomes from top to bottom, we only need to fetch the new update at the uppermost coordinate (or also lowermost coordinate if the biomes don't stack perfectly and there's a gap).

File: src/mapgen/mg_biome.cpp [hunk 3]
```diff
@@ -135,13 +123,16 @@ BiomeGenOriginal::BiomeGenOriginal(BiomeManager *biomemgr,
...
-	// Calculate cache of Y transition points
+	// Calculate cache of Y transition points. For downwards scanning only!
 	std::vector<s16> values;
 	values.reserve(m_bmgr->getNumObjects() * 2);
 	for (size_t i = 0; i < m_bmgr->getNumObjects(); i++) {
 		Biome *b = (Biome *)m_bmgr->getRaw(i);
 		values.push_back(b->max_pos.Y);
-		values.push_back(b->min_pos.Y);
+		// Optimization: biomes often have perfect Y transitions, resulting in
+		// unnecessary Y pairs. i.e. when (biome A min Y) == (biome B max Y + 1)
```
Comment (sfan5) [inline src/mapgen/mg_biome.cpp:133]: i now understand what the code does, but isn't the comment misleading?
it's not about optimization but rather if you have a biome from [min, max] then the points at which a different biome starts are:
* max
* min-1

putting `min` in there is just wrong as the biome at min is equal to min+1

File: src/unittest/test_mapgen.cpp [hunk 4]
```diff
@@ -0,0 +1,124 @@
...
+{
+	MockServer server(getTestTempDirectory());
+	MockBiomeManager bmgr(&server);
+	bmgr.setNodeDefManager(gamedef->getNodeDefManager());
+
+	enum FakeNodes : content_t {
+		FN_DIRT_WITH_GRASS = 10,
+		FN_DIRT,
+		FN_STONE,
+	};
```
Comment (sfan5) [inline src/unittest/test_mapgen.cpp:52]: see https://github.com/minetest/minetest/blob/88c845166cc364bdc34341620071db9cecaf7f16/src/unittest/test.h#L108-L114

File: src/unittest/test_mapgen.cpp [hunk 5]
```diff
@@ -0,0 +1,124 @@
...
+
+	{
+		// Add some biomes (equivalent to l_register_biome)
+		// Taken from minetest_game/mods/default/mapgen.lua
+		size_t bmgr_count = bmgr.getNumObjects(); // this is 1 ?
```
Comment (sfan5) [inline src/unittest/test_mapgen.cpp:57]: I believe there's a default biome for everything not covered

File: src/unittest/test_mapgen.cpp [hunk 6]
```diff
@@ -0,0 +1,124 @@
...
+		b->heat_point = 60.0f;
+		b->humidity_point = 68.0f;
+		UASSERT(bmgr.add(b) != OBJDEF_INVALID_HANDLE);
+		UASSERT(bmgr.getNumObjects() - bmgr_count == 2);
+	}
+
+
+	std::unique_ptr<BiomeParams> params(BiomeManager::createBiomeParams(BIOMEGEN_ORIGINAL));
+
+	constexpr v3s16 CSIZE(16, 16, 16);
```
Comment (sfan5) [inline src/unittest/test_mapgen.cpp:88]: note: this is usually 5

File: src/mapgen/mg_biome.cpp (hunk 3 above)
Comment (SmallJoker) [reply src/mapgen/mg_biome.cpp:133]: Currently, this code could handle both cases: top->down (high Y to low Y) and bottom->up scanning.
We're only using top->bottom so far, thus I'll instead comment this "limitation" of `m_transitions_y` in the header.

File: src/unittest/test_mapgen.cpp (hunk 6 above)
Comment (SmallJoker) [reply src/unittest/test_mapgen.cpp:88]: It's unfortunate naming. It seems to be in nodes.
https://github.com/minetest/minetest/blob/ae96a8d4fa9ade70672fe8d2152013c547edfb47/src/emerge.cpp#L193-L194

File: src/mapgen/mg_biome.cpp (hunk 3 above)
Comment (sfan5) [reply src/mapgen/mg_biome.cpp]: yeah it was only meant to do top-down from the start

File: src/unittest/test_mapgen.cpp (hunk 6 above)
Comment (sfan5) [reply src/unittest/test_mapgen.cpp:82]: ah, then 80

File: src/unittest/test_mapgen.cpp [hunk 7]
```diff
@@ -0,0 +1,119 @@
...
+			s16 next_y = biomegen->getNextTransitionY(expected.check_y);
+#if defined(__APPLE__) // HACK TODO REMOVE ME
+			// If something breaks, do log:
+			printf("(%s %s) (%d %d)\n",
+				biome->name.c_str(), expected.name,
+				next_y, expected.next_y
+			);
+#endif
+			UASSERT(biome->name == expected.name);
+			UASSERT(next_y == expected.next_y);
```
Comment (sfan5) [inline src/unittest/test_mapgen.cpp:115]:
```suggestion
			UASSERTCMP(auto, biome->name, expected.name);
			UASSERTCMP(auto, next_y, expected.next_y);
```

File: src/unittest/test_mapgen.cpp [hunk 8]
```diff
@@ -0,0 +1,113 @@
...
+		}
+	};
+}
+
+void TestMapgen::runTests(IGameDef *gamedef)
+{
+	TEST(testMapgen, gamedef);
+}
+
+void TestMapgen::testMapgen(IGameDef *gamedef)
```
Comment (sfan5) [inline src/unittest/test_mapgen.cpp:42]: last suggestion: method should be called `testBiomeGen`

**Review by sfan5 — APPROVED** [review]
lgtm otherwise
