### PR TITLE
Fix infinite viewing_range

### LINKED ISSUE #13224: Infinite view range no longer works
##### Minetest version
```
5.7.0-dev latest master
```
##### OS / Hardware
GPU model: AMD Radeon RX 560
OpenGL version: 4.6

##### Summary
Infinite view range no longer works after commit https://github.com/minetest/minetest/commit/2715cc8bf68a2cc8cd583cd5b0bb732ee13a1b49. It should show all loaded mapblocks independent of the viewing range set.

##### Steps to reproduce
Turn up the view range really high and fly around for a bit. Enable infinite view range and turn down the view range. All previously loaded parts of the terrain should be visible, but aren't.

### PR DESCRIPTION
**Pull request by lhofhansl**
Fixes #13224

When infinite viewing_range is enabled just loops over all loaded blocks, frustum cull, occlusion cull and display them,
Quick and dirty.

## To do

This PR is Ready for Review.

## How to test

Enable infinite viewing_range and make sure all loaded blocks are shown.

### CODE REVIEW

**Comment by lhofhansl** [comment]
Actually this is better. Leaves reporting intact.

Review without whitespace :)

File: src/client/clientmap.cpp [hunk 1]
```diff
@@ -288,206 +283,289 @@ void ClientMap::updateDrawList()
...
+					mesh_sphere_center = intToFloat(block_pos_nodes, BS) + v3f((MAP_BLOCKSIZE * 0.5f - 0.5f) * BS);
+					mesh_sphere_radius = 0.0f;
+				}
+				// Frustum culling
+				// Only do coarse culling here, to account for fast camera movement.
+				// This is needed because this function is not called every frame.
+				float frustum_cull_extra_radius = 300.0f;
+				if (is_frustum_culled(mesh_sphere_center,
+						mesh_sphere_radius + frustum_cull_extra_radius))
+					continue;
```
Comment (sfan5) [inline src/client/clientmap.cpp:329]: can we avoid duplicating this?

File: src/client/clientmap.cpp [hunk 2]
```diff
@@ -288,206 +283,289 @@ void ClientMap::updateDrawList()
...
+			}
+			assert(m_drawlist.empty() || shortlist.empty());
+			for (auto pos : shortlist) {
+				MapBlock * block = getBlockNoCreateNoEx(pos);
+				if (block) {
+					block->refGrab();
+					m_drawlist.emplace(pos, block);
+				}
+			}
+		}
```
Comment (sfan5) [inline src/client/clientmap.cpp:364]: memory leak, this code already exists outside the if

File: src/client/clientmap.cpp [hunk 3]
```diff
@@ -288,206 +283,289 @@ void ClientMap::updateDrawList()
...
+	else {
 
-		// Only visit each block once (it may have been queued up to three times)
-		if ((flags & 0x80) == 0x80)
-			continue;
-		flags |= 0x80;
+		// Uncomment to debug occluded blocks in the wireframe mode
+		// TODO: Include this as a flag for an extended debugging setting
+		// if (occlusion_culling_enabled && m_control.show_wireframe)
+		// 	occlusion_culling_enabled = porting::getTimeS() & 1;
```
Comment (sfan5) [inline src/client/clientmap.cpp:371]: also this part shouldn't be inside the if

File: src/client/clientmap.cpp (hunk 2 above)
Comment (lhofhansl) [reply src/client/clientmap.cpp:364]: Ah. Good catch, I was going to remove this part in favor of calling it at the end.

File: src/client/clientmap.cpp (hunk 1 above)
Comment (lhofhansl) [reply src/client/clientmap.cpp:329]: I do not see how.

File: src/client/clientmap.cpp (hunk 3 above)
Comment (lhofhansl) [reply src/client/clientmap.cpp:363]: This was added for the new culler, so I left it there.

File: src/client/clientmap.cpp (hunk 2 above)
Comment (lhofhansl) [reply src/client/clientmap.cpp]: Fixed now. Just needed to be remove. Was left over when I switched from returning to an if-statement.

File: src/client/clientmap.cpp (hunk 1 above)
Comment (lhofhansl) [reply src/client/clientmap.cpp:329]: In fact seeing how the old culler is actually faster when there are many empty blocks not sent from the server, I want to bring that one back anyway.

**Comment by lhofhansl** [comment]
#13169 was a mistake in hindsight, and now we understand how it works with mesh-chunks. (I have proven it here)

File: src/client/clientmap.cpp (hunk 3 above)
Comment (lhofhansl) [reply src/client/clientmap.cpp]: Moved it up.

**Comment by lhofhansl** [comment]
This should be good now. But... Maybe we should undo #13169 and fix it up for mesh chunking.

File: src/client/clientmap.cpp (hunk 1 above)
Comment (lhofhansl) [reply src/client/clientmap.cpp]: See also #13169

**Comment by x2048** [comment]
I have an idea how the current culler could be made faster in sparse spaces. Can this wait for a few days?

**Comment by lhofhansl** [comment]
@x2048 would that also deal with infinite viewing_range?

**Comment by x2048** [comment]
Yes

**Comment by lhofhansl** [comment]
Maybe i can drop #13207 then too.

**Comment by lhofhansl** [comment]
I'm very curious @x2048 . In these cases of large viewing_ranges with mostly open scenes (i.e. outside), the old algorithm is sometimes 10x faster (it just had to do less work for these.)

**Comment by x2048** [comment]
Do I understand correctly that neither air nor full-stone blocks will be sent to the client, unless within 4 blocks?

**Comment by lhofhansl** [comment]
> Do I understand correctly that neither air nor full-stone blocks will be sent to the client, unless within 4 blocks send optimize distance?

The blocks that are not sent are those that are above-ground and have identical day and night lighting (which includes air-only-blocks).

It almost seems we want both cullers and switch dynamically. If the number of block to be examine is (say) 2x of all loaded blocks we switch to the enumerating culler, if not we switch to the recursive culler.

We just somehow have to make use of the information we get from the set of loaded blocks. I also thought about starting from those, but then you have identify those within the current view-frustum first, by which time you might as well do the occlusion culling and be done. Maybe you solved that one... I'll look at your branch.

In general if we can keep the culling below 15ms for viewing_range 1000 on a reasonable machine, I'd drop #13207.

**Comment by lhofhansl** [comment]
> The idea is to start the BFS search at the loaded blocks

I'd start with the loaded block in the view frustum (that's a quick check), then do the depth-sort as you do. I have no suggestions w.r.t. to the visibility bits of the existing blocks. If we assume that they are transparent we haven't really gained anything.

How do you figure out whether any of the loaded blocks are visible?

**Comment by x2048** [comment]
I have tested the two cullers in this PR a bit, and 'bfs' (breadth-first-search) consistently wins over 'loops' (the old one) when client_mesh_chunk=1, also when the space is sparse. With larger values, 'loops' just skips occlusion culling test for majority of the blocks because mesh == nullptr, so the quality of culling is much lower. Apparently this is compensated by the drop in drawcalls with jumbo meshes. I think if 'bfs' is adapted to a larger mesh grid, it will regain performance and will focus on that.

**Comment by lhofhansl** [comment]
I agree that in most cases bfs "wins". The scene where I saw it slower was mostly ground (no water), where the old culler is faster. No need to fret over this.

Let's just fix this issue: Re-enabling infinite range.
If we do not like this approach here we can close this and do something else. (I'm not attached to this.)

In either looks like https://github.com/minetest/minetest/pull/13207 is still worth it.

**Comment by x2048** [comment]
I've made 'bfs' walk only blocks potentially containing meshes in #13250, which should keep the cost of running constant if view_range and client_mesh_chunk increase proportionally. It's still more expensive than 'loops' in pure air scenarios but should be manageable.

**Comment by x2048** [comment]
Closing this in favor of #13250 for now.

**Comment by lhofhansl** [comment]
Reopening. See discussion on #13250.
I would like to see that one merged first, then I'll adjust and fix this one.

**Comment by sfan5** [comment]
Well this just stops working (with chunked meshes) once rebased, I'll let someone else do it. here's how far I got: https://github.com/sfan5/minetest/tree/pr13225

Anyway I tested this and it works :+1:, here's a screenshot:
screenshot_20230311_144633

**Comment by lhofhansl** [comment]
I'll finish today. Will probably start from scratch.

**Comment by lhofhansl** [comment]
Rebased... Please have a look.
I deliberated kept `isBlockOccluded` (as opposed to `isMeshOccluded`) since we are enumerating blocks (not meshes).

Question: Any interest in bringing the old culler back by config option? In that case I would add a call to `isBlockInSight` if the range is not range-all. About 10 extra lines.

File: src/client/clientmap.cpp [hunk 4]
```diff
@@ -299,213 +291,291 @@ void ClientMap::updateDrawList()
...
+				float frustum_cull_extra_radius = 300.0f;
+				if (is_frustum_culled(mesh_sphere_center,
+						mesh_sphere_radius + frustum_cull_extra_radius)) {
+					blocks_frustum_culled++;
+					continue;
+				}
 
-		blocks_visited++;
+				// Raytraced occlusion culling - send rays from the camera to the block's corners
+				if (occlusion_culling_enabled && mesh
```
Comment (x2048) [inline src/client/clientmap.cpp:343]: Would it make sense to make this also depend on `m_enable_raytraced_culling`?

Comment (lhofhansl) [reply src/client/clientmap.cpp:343]: I was thinking about that, but could not make up my mind :)

You think it should?

File: src/client/clientmap.cpp [hunk 5]
```diff
@@ -299,213 +291,291 @@ void ClientMap::updateDrawList()
...
+					continue;
+				}
 
-		// Get the sector, block and mesh
-		MapSector *sector = this->getSectorNoGenerate(v2s16(block_coord.X, block_coord.Z));
+				if (mesh_grid.cell_size > 1) {
+					// Block meshes are stored in the corner block of a chunk
+					// (where all coordinate are divisible by the chunk size)
+					// Add them to the de-dup set.
+					shortlist.emplace(mesh_grid.getMeshPos(block->getPos()));
```
Comment (x2048) [inline src/client/clientmap.cpp:353]: This emplace essentially overrides isMeshOccluded() above. The best way would be to collect all meshes based on what's loaded + frustum and then call isMeshOccluded on what's in the short list.

The other algorithm is different because it only checks blocks with meshes.

Comment (lhofhansl) [reply src/client/clientmap.cpp:353]: I guess that explains why I didn't notice an improvement when I changed from isBlockOccluded to isMeshOccluded.

In then end, this is for the case where a user wants to see all blocks, and most time will be spent in rendering all those blocks, so I'd like to not complicate this more than needed.

Comment (lhofhansl) [reply src/client/clientmap.cpp:353]: Actually, are you sure isMeshOccluded actually works? I never see any blocks occluded in the debug view (F6), even as I move around or move behind a "mountain".

Comment (lhofhansl) [reply src/client/clientmap.cpp:353]: BTW. I tried what you suggested (calling isMeshOccluded on the shortlisted blocks), but then I get missing blocks on the client.

Comment (lhofhansl) [reply src/client/clientmap.cpp:353]: Oh I see what you are saying. We may occlusion cull a mesh, but then another block from the grid brings the mesh-block back in. T

Comment (lhofhansl) [reply src/client/clientmap.cpp:353]: OK... Last comment... Since in this view we truly want to see all blocks loaded at the client, we also just forgo the occlusion culling.

I tried to do it for each block (mesh or not) and that is too slow.

What do you think, just not do occlusion culling in this case?

**Comment by lhofhansl** [comment]
@x2048 See latest commit. Occlusion culling now only happens when mesh grid size is 1. It is already disabled with grid size >=4, and for 2 and 3 it seems questionable anyway.

**Comment by Desour** [comment]
I don't think we need any ray-based occlusion culling at all at full view range. It's probably slow at far distances (i.e. when the blocks are on the other end of the map), and the player can't expect good performance while in full view range anyway, so no need to cull some blocks.

File: src/client/clientmap.cpp [hunk 6]
```diff
@@ -299,213 +291,290 @@ void ClientMap::updateDrawList()
...
-		auto &flags = meshes_seen.getChunk(cell_coord).getBits(cell_coord);
+				if (mesh) {
+					mesh_sphere_center = intToFloat(block_pos_nodes, BS)
+							+ mesh->getBoundingSphereCenter();
+					mesh_sphere_radius = mesh->getBoundingRadius();
+				} else {
+					mesh_sphere_center = intToFloat(block_pos_nodes, BS)
+							+ v3f((MAP_BLOCKSIZE * 0.5f - 0.5f) * BS);
+					mesh_sphere_radius = 0.0f;
+				}
```
Comment (Desour) [inline src/client/clientmap.cpp:330]: Not needed. As blocks / meshes are not traversed recursively, empty blocks can just be skipped.

This also means that each mesh will only be added once, so `shortlist` could be a simple vector.
(It looks to me like de-duplicating isn't needed in finite view range either, but that's something for later refactor I guess.)

Comment (sfan5) [reply src/client/clientmap.cpp:330]: You still want to add them to `m_keeplist`, so can't skip

**Comment by sfan5** [comment]
Works fine without mesh chunking.
This is super fast with mesh chunking enabled (probably `isBlockOccluded` is a major bottleneck), but it has some weird looking behaviour when the mapblock limit is reached: https://0x0.st/Hi32.mp4
Notice the "rolling" row of empty mapblocks in front of me.

**Comment by lhofhansl** [comment]
@sfan5 I think it is because `ClientMap::touchMapBlocks` does not touch blocks without meshes. So they expire, and when they are reloaded from the server the grid-mesh needs to be regenerated. Let's do that in another PR.

Two more questions on this one:
1. Should I just remove occlusion culling from infinite viewing range?
2. If not, should I gate it with the `enable_raytraced_culling` setting?

I'd vote for (1).

**Comment by sfan5** [comment]
I think occlusion culling is in principle still useful for range_all but we need to ensure that it's super fast.
I vote for (1) _for now_, this can be revisited.
