### PR TITLE
Restore ability to enable flags in settings

### LINKED ISSUE #14893: Settings: enabling flags does not work
### Minetest version

```true
Minetest 5.9.0-dev-7625f88a0 (Linux)
Using LuaJIT 2.1.1720049189
Built by GCC 14.1
Running on Linux/6.10.1 x86_64
BUILD_TYPE=RelWithDebInfo
RUN_IN_PLACE=1
USE_CURL=1
USE_GETTEXT=1
USE_SOUND=1
STATIC_SHAREDIR="."
STATIC_LOCALEDIR="locale"
```

### Summary

Enabling flags defined by the game's settingtypes.txt doesn't work at all.
Disabling them does (?!).

### Steps to reproduce

1. install [Minetest Classic](https://github.com/sfan5/minetest_classic)
2. go to Settings > "Minetest Classic"
3. check any of the checkboxes that aren't already checked
grafik
4. switch away from tab, go back, notice how nothing is saved

### PR DESCRIPTION
**Pull request by appgurueu**
Fixes #14893 by initializing possible flags to `false`. It also should first apply the defaults properly now.

Unfun fact: The background of the query bar blinks briefly when you toggle checkboxes.

### CODE REVIEW

File: builtin/mainmenu/settings/components.lua [hunk 1]
```diff
@@ -306,18 +306,31 @@ function make.flags(setting)
...
-					checkboxes[name:sub(3)] = false
-				elseif name ~= "" then
-					checkboxes[name] = true
+			for _, name in ipairs(setting.possible) do
+				checkboxes[name] = false
+			end
+			local function apply_flags(flag_string)
+				for _, name in ipairs(flag_string:split(",")) do
+					name = name:trim()
+					if name:sub(1, 2) == "no" then
```
Comment (sfan5) [inline builtin/mainmenu/settings/components.lua:318]: I've had this in MCL¹ and it's problematic when you have to flag named `nodes_something`. Need to check the table of known valid flags here.

¹: there's a lack of abbrevations to use for Minetest Classic

Comment (appgurueu) [reply builtin/mainmenu/settings/components.lua:318]: I had assumed such flags weren't a thing judging by the previous code.
I'll implement the proper solution.

BTW, I would abbreviate Minetest Classic as MTC.

Comment (sfan5) [reply builtin/mainmenu/settings/components.lua]: I have a flag called `node_waving` and it's actually missing from the settings tab.

**Review by sfan5 — APPROVED** [review]
works

**Review by sfan5 — APPROVED** [review]
second commit lgtm

**Review by SmallJoker — APPROVED** [review]
:ballot_box_with_check: `WARNING[Main]: Flag drowning in default for setting modernize both enabled and disabled, ignoring` provoked. Does work.
:ballot_box_with_check: `node_waving` now shows up as a checkbox (was previously missing)
:ballot_box_with_check: Checkbox states did already appear correctly, and still appear correctly (unlike what's described in the issue).

File: builtin/mainmenu/settings/components.lua [hunk 2]
```diff
@@ -344,18 +344,16 @@ function make.flags(setting)
 			local y = 0.55
 
 			for _, possible in ipairs(setting.possible) do
-				if possible:sub(1, 2) ~= "no" then
```
Comment (rubenwardy) [inline builtin/mainmenu/settings/components.lua:328]: No flags should be hidden if there's a matching flag without the no

Comment (rubenwardy) [reply builtin/mainmenu/settings/components.lua:328]: Ideally, we'd have a function that parses flag lists and returns a table with true, false, or nil for unspecified. And a corresponding set function. To avoid "noise" being interpreted as no oise, I guess it needs to know which flags are valid.

This is "Add flag util" in https://github.com/minetest/minetest/issues/13476

Comment (appgurueu) [reply builtin/mainmenu/settings/components.lua:328]: > No flags should be hidden if there's a matching flag without the no

Sure, but this is `setting.possible`, the possible flags. There should be no "no" prefixes here, this isn't the default value. This is the "type" rather than the default "value" so to speak.

From `builtin/settingtypes.txt`:

```
#   * flags:
#            Flags are always separated by comma without spaces.
#            - default possible_flags
```

It seems sometimes only a default is provided, in which case the `possible_flags` need to be inferred. *Only then* should settings with `no` prefixes be ignored (which also means that if you provide the `possible_flags` as the docs tell you to, you can have flags such as `noise`).

This is a bug in `builtin/mainmenu/settings/settingtypes.lua`, where it just defaults to `possible = default` without stripping such prefixes.
