### PR TITLE
Fix Enter key after creating a new world

### LINKED ISSUE #11608: Client immediately starts up a world on pressing 'Enter' key when is in the createworld window.
##### Minetest version
```
Minetest-5.5.0-dev and below.
```

##### Summary
When you are in the createworld dialog window and click 'Create' button, your world is created and you get out from that window. All as it should be. However, if you press 'Enter' key on a keyboard, your world is created and immediately that world runs. I think it should close that window instead of the immediate joining.

##### Steps to reproduce
1. Go to the createworld menu.
2. Press 'Create' button.
3. Then again go to that menu and press already 'Enter' key.

### PR DESCRIPTION
**Pull request by srifqi**
**Goal of the PR**
This PR changes the behaviour of <kbd>Enter</kbd> key after creating a new world.

**How does the PR work?**
- Disable <kbd>Enter</kbd> key before opening create world dialog.
- Enable it again if the world creation is cancelled or after the world is created and an <kbd>Enter</kbd> key event is received.

**Does it resolve any reported issue?**
Yes, this PR tries to fix #11608.

**Does this relate to a goal in the roadmap?**
Probably, this PR tries to fix a reported UX issue.

## To do
This PR is Ready for Review.

## How to test
1. Run Minetest.
2. Open the Start Game tab, click New, and fill in the name.
4. Press <kbd>Enter</kbd>.
5. It should **only** create the world (**not** playing it directly).
6. Press <kbd>Enter</kbd> again to play the selected world.
7. It should play the selected world.
8. Restart Minetest (or Exit to Menu).
9. Open the Start Game tab, click New, and click Cancel or press <kbd>Esc</kbd>.
10. Press <kbd>Enter</kbd> to play the selected world.
11. It should play the selected world.

### CODE REVIEW

**Comment by TurkeyMcMac** [comment]
I think the problem is this:

1. In the world creation dialog, the user presses Enter and causes the dialog to close.
2. Back in the world selection screen, the user releases the Enter key. The table element records this as a "doubleclick" event and causes the world to be opened.

I wonder if a good fix would be to make the "doubleclick" event fire on key press rather than release.

File: builtin/mainmenu/tab_local.lua [hunk 1]
```diff
@@ -269,6 +270,14 @@ local function main_button_handler(this, fields, name, tabdata)
 	end
 
 	if fields["play"] ~= nil or world_doubleclick or fields["key_enter"] then
+		if is_in_dlg_create_world then
+			is_in_dlg_create_world = false
+
+			if fields["play"] == nil and not this.is_dlg_create_world_canceled then
```
Comment (TurkeyMcMac) [inline builtin/mainmenu/tab_local.lua:276]: If you create a world without pressing enter then try to play it by pressing enter on it, nothing happens. Another press of enter is necessary.

**Comment by srifqi** [comment]
> I wonder if a good fix would be to make the "doubleclick" event fire on key press rather than release.

Isn't that handler also applied for all mods (not just main menu)? Any change of its behaviours might create modding-related compatibility issues.

File: builtin/mainmenu/tab_local.lua (hunk 1 above)
Comment (srifqi) [reply builtin/mainmenu/tab_local.lua]: Thank you for the catch. It should have been fixed now.

**Review by TurkeyMcMac — COMMENTED** [review]
There is still an issue: If I create a world then confirm by pressing enter and releasing very quickly (before the world list reappears), then I press enter to play the world, the world does not start. I have to press enter again. (This may be platform-dependent. I'm using Linux.)

**Comment by srifqi** [comment]
I decided to try using `core.get_us_time()` for deciding the handling instead. There is a 200 ms cooldown between reactions. But then, if the player decides to hold the <kbd>Enter</kbd> key, the game will start on key up.

File: builtin/mainmenu/tab_local.lua [hunk 2]
```diff
@@ -269,6 +269,12 @@ local function main_button_handler(this, fields, name, tabdata)
 	end
 
 	if fields["play"] ~= nil or world_doubleclick or fields["key_enter"] then
+		local enter_key_duration = core.get_us_time() - this.dlg_create_world_closed_at
```
Comment (TurkeyMcMac) [inline builtin/mainmenu/tab_local.lua:272]: `dlg_create_world_closed_at` should be set to zero as soon as the tab is created. Otherwise it might be `nil` at this point (you can reproduce this by opening the game and trying to enter a world without opening the world creation dialog.)

Comment (srifqi) [reply builtin/mainmenu/tab_local.lua:276]: I added simple initialisation at the start of the `main_button_handler` function.

**Review by TurkeyMcMac — APPROVED** [review]

**Comment by SmallJoker** [comment]
This is caused by a mismatch in behaviour:

 * Button fires action when releasing Enter (guiButton.cpp)
 * Textbox fires action when pressing Enter (guiEditBox.cpp)
 * List table fires action when releasing Enter (guiTable.cpp)

Negating the check here might be a less hacky fix:
https://github.com/minetest/minetest/blob/89e7f72c929fbeef8ad755bc85db22ae6102787d/src/gui/guiTable.cpp#L836-L841

**Comment by srifqi** [comment]
> ... to avoid such issues in the mainmenu and mods.

Is it fine for mods? This fix is "localised" just for this case because of fear from behaviour changes in handling this.

**Comment by SmallJoker** [comment]
I suppose a similar issue could arise when hitting Enter on either a text field or list and releasing it on a formspec that has a button focussed. Unfortunately I do yet not have an idea on how to skip inputs after a formspec change...

**Review by SmallJoker — APPROVED** [review]
I don't like this approach. Someone please come up with a proper solution.
Until then :+1:  for fixing the bug.
