### PR TITLE
Devtest: Fix missing liquid properties causing crash

### LINKED ISSUE #9938: Crash loading devtest world (Assertion `liquid_type == LIQUID_SOURCE' failed.)
##### Minetest version
```
Minetest 5.3.0-dev-debug-083b285f4 (Linux)
Using Irrlicht 1.8.4
BUILD_TYPE=Debug
RUN_IN_PLACE=1
USE_GETTEXT=1
USE_SOUND=1
USE_CURL=1
USE_FREETYPE=1
USE_LUAJIT=1
STATIC_SHAREDIR="."
STATIC_LOCALEDIR="locale"
```

##### OS / Hardware

Operating system: Ubuntu Linux 20.04 LTS (ubuntu proposed repository added to `sources.list` file)
CPU: Pentium(R) Dual-Core  CPU      E6300  @ 2.80GHz

##### Summary
Trying to load a devtest world results in crash while loading.

<details>
<summary>Log while using default settings (no minetest.conf)</summary>

```
Loaded texture: /home/juozas/minetest_dev/games/minetest_game/menu/header.png
Loaded texture: /home/juozas/minetest_dev/games/devtest/menu/icon.png
Loaded texture: /home/juozas/minetest_dev/games/minetest_game/menu/icon.png
Loaded texture: /home/juozas/minetest_dev/games/devtest/menu/background.png
Loaded texture: /home/juozas/minetest_dev/games/devtest/menu/header.png
2020-05-26 14:03:15: ACTION[Main]: [experimental] on_mods_loaded()
        .__               __                   __   
  _____ |__| ____   _____/  |_  ____   _______/  |_ 
 /     \|  |/    \_/ __ \   __\/ __ \ /  ___/\   __\
|  Y Y  \  |   |  \  ___/|  | \  ___/ \___ \  |  |  
|__|_|  /__|___|  /\___  >__|  \___  >____  > |__|  
      \/        \/     \/          \/     \/        
2020-05-26 14:03:15: ACTION[Main]: World at [/home/juozas/minetest_dev/bin/../worlds/Test3]
2020-05-26 14:03:15: ACTION[Main]: Server for gameid="devtest" listening on 0.0.0.0:52891.
minetest: /home/juozas/minetest_dev/src/nodedef.cpp:742: void ContentFeatures::updateTextures(ITextureSource*, IShaderSource*, irr::scene::IMeshManipulator*, Client*, const TextureSettings&): Assertion `liquid_type == LIQUID_SOURCE' failed.
Aborted (core dumped)
```

</details>
<details>
<summary>Log while using --info parameter</summary>

```
2020-05-26 14:03:55: INFO[Main]: Using relative paths (RUN_IN_PLACE)
2020-05-26 14:03:55: INFO[Main]: Detected share path: /home/juozas/minetest_dev/bin/..
2020-05-26 14:03:55: INFO[Main]: Detected user path: /home/juozas/minetest_dev/bin/..
2020-05-26 14:03:55: INFO[Main]: Detected cache path: /home/juozas/minetest_dev/bin/../cache
2020-05-26 14:03:55: INFO[Main]: Using in-place locale directory /home/juozas/minetest_dev/bin/../locale even though a static one was provided.
2020-05-26 14:03:55: INFO[Main]: minetest with SER_FMT_VER_HIGHEST_READ=28, BUILD_TYPE=Debug
2020-05-26 14:03:55: INFO[Main]: RUN_IN_PLACE=1
2020-05-26 14:03:55: INFO[Main]: USE_GETTEXT=1
2020-05-26 14:03:55: INFO[Main]: USE_SOUND=1
2020-05-26 14:03:55: INFO[Main]: USE_CURL=1
2020-05-26 14:03:55: INFO[Main]: USE_FREETYPE=1
2020-05-26 14:03:55: INFO[Main]: USE_LUAJIT=1
2020-05-26 14:03:55: INFO[Main]: STATIC_SHAREDIR="."
2020-05-26 14:03:55: INFO[Main]: STATIC_LOCALEDIR="locale"
2020-05-26 14:03:55: INFO[Main]: Gettext: domainname="minetest" path="/home/juozas/minetest_dev/bin/../locale"
2020-05-26 14:03:55: INFO[Main]: Message locale is now set to: C
2020-05-26 14:03:55: INFO[Main]: Searching worlds...
2020-05-26 14:03:55: INFO[Main]:   In /home/juozas/minetest_dev/bin/../worlds: Flat Worldedit Test Minimal Test1 Test3 Test2 FogTest Test 
2020-05-26 14:03:55: INFO[Main]: 8 found.
2020-05-26 14:03:55: INFO[Main]: Using default world at [/home/juozas/minetest_dev/bin/../worlds/world]
2020-05-26 14:03:55: INFO[Main]: Using default gameid [minetest]
2020-05-26 14:03:55: INFO[Main]: Audio: Global Initialized: OpenAL 1.1 ALSOFT 1.19.1, using OpenAL Soft
2020-05-26 14:03:55: INFO[Main]: Irrlicht: Irrlicht Engine version 1.8.4
2020-05-26 14:03:55: INFO[Main]: Irrlicht: Linux 5.4.0-33-generic #37-Ubuntu SMP Thu May 21 12:53:59 UTC 2020 x86_64
2020-05-26 14:03:56: INFO[Main]: Irrlicht: Using renderer: OpenGL 3.3.0
2020-05-26 14:03:56: INFO[Main]: Irrlicht: GeForce 210/PCIe/SSE2: NVIDIA Corporation
2020-05-26 14:03:56: INFO[Main]: Irrlicht: OpenGL driver version is 1.2 or better.
2020-05-26 14:03:56: INFO[Main]: Irrlicht: GLSL version: 3.3
2020-05-26 14:03:56: INFO[Main]: FontEngine: measured text_height=20
2020-05-26 14:03:56: INFO[Main]: Waiting for other menus
2020-05-26 14:03:56: INFO[Main]: Waited for other menus
2020-05-26 14:03:56: INFO[Main]: Audio: Initialized: OpenAL 
2020-05-26 14:03:56: INFO[Main]: GUIEngine: Initializing Lua
2020-05-26 14:03:56: INFO[AsyncWorker-0]: Initializing Asynchronous environment
2020-05-26 14:03:56: INFO[AsyncWorker-1]: Initializing Asynchronous environment
2020-05-26 14:03:56: INFO[AsyncWorker-2]: Initializing Asynchronous environment
2020-05-26 14:03:56: INFO[Main]: SCRIPTAPI: Initialized main menu modules
2020-05-26 14:03:56: INFO[AsyncWorker-3]: Initializing Asynchronous environment
2020-05-26 14:03:56: INFO[Main]: Searching worlds...
2020-05-26 14:03:56: INFO[Main]:   In /home/juozas/minetest_dev/bin/../worlds: Flat Worldedit Test Minimal Test1 Test3 Test2 FogTest Test 
2020-05-26 14:03:56: INFO[Main]: 8 found.
Loaded texture: /home/juozas/minetest_dev/games/minetest_game/menu/header.png
2020-05-26 14:03:56: INFO[Main]: Audio: Error opening /home/juozas/minetest_dev/bin/../sounds/main_menu.0.ogg for decoding
2020-05-26 14:03:56: INFO[Main]: Audio: Error opening /home/juozas/minetest_dev/bin/../sounds/main_menu.1.ogg for decoding
2020-05-26 14:03:56: INFO[Main]: Audio: Error opening /home/juozas/minetest_dev/bin/../sounds/main_menu.2.ogg for decoding
2020-05-26 14:03:56: INFO[Main]: Audio: Error opening /home/juozas/minetest_dev/bin/../sounds/main_menu.3.ogg for decoding
2020-05-26 14:03:56: INFO[Main]: Audio: Error opening /home/juozas/minetest_dev/bin/../sounds/main_menu.4.ogg for decoding
2020-05-26 14:03:56: INFO[Main]: Audio: Error opening /home/juozas/minetest_dev/bin/../sounds/main_menu.5.ogg for decoding
2020-05-26 14:03:56: INFO[Main]: Audio: Error opening /home/juozas/minetest_dev/bin/../sounds/main_menu.6.ogg for decoding
2020-05-26 14:03:56: INFO[Main]: Audio: Error opening /home/juozas/minetest_dev/bin/../sounds/main_menu.7.ogg for decoding
2020-05-26 14:03:56: INFO[Main]: Audio: Error opening /home/juozas/minetest_dev/bin/../sounds/main_menu.8.ogg for decoding
2020-05-26 14:03:56: INFO[Main]: Audio: Error opening /home/juozas/minetest_dev/bin/../sounds/main_menu.9.ogg for decoding
2020-05-26 14:03:56: INFO[Main]: Audio: Error opening /home/juozas/minetest_dev/bin/../sounds/main_menu.ogg for decoding
2020-05-26 14:03:56: INFO[Main]: OpenALSoundManager: "main_menu" not found.
Loaded texture: /home/juozas/minetest_dev/games/devtest/menu/icon.png
Loaded texture: /home/juozas/minetest_dev/games/minetest_game/menu/icon.png
Loaded texture: /home/juozas/minetest_dev/games/devtest/menu/background.png
Loaded texture: /home/juozas/minetest_dev/games/devtest/menu/header.png
2020-05-26 14:04:02: INFO[Main]: Audio: Deinitializing...
2020-05-26 14:04:02: INFO[Main]: Audio: Deinitialized.
2020-05-26 14:04:02: INFO[Main]: GUIEngine: Deinitializing scripting
2020-05-26 14:04:02: INFO[Main]: Searching worlds...
2020-05-26 14:04:02: INFO[Main]:   In /home/juozas/minetest_dev/bin/../worlds: Flat Worldedit Test Minimal Test1 Test3 Test2 FogTest Test 
2020-05-26 14:04:02: INFO[Main]: 8 found.
2020-05-26 14:04:02: INFO[Main]: Selected world: Test3 [/home/juozas/minetest_dev/bin/../worlds/Test3]
2020-05-26 14:04:02: INFO[Main]: SourceImageCache::getOrLoad(): Loading path "/home/juozas/minetest_dev/bin/../textures/base/pack/progress_bar.png"
2020-05-26 14:04:02: INFO[Main]: SourceImageCache::getOrLoad(): Loading path "/home/juozas/minetest_dev/bin/../textures/base/pack/progress_bar_bg.png"
2020-05-26 14:04:02: INFO[Main]: Attempting to use OpenAL audio
2020-05-26 14:04:02: INFO[Main]: Audio: Initialized: OpenAL 
2020-05-26 14:04:02: INFO[Main]: Server created for gameid "devtest" in simple singleplayer mode
2020-05-26 14:04:02: INFO[Main]: - world:  /home/juozas/minetest_dev/bin/../worlds/Test3
2020-05-26 14:04:02: INFO[Main]: - game:   /home/juozas/minetest_dev/bin/../games/devtest
2020-05-26 14:04:02: INFO[Main]: Initializing world at /home/juozas/minetest_dev/bin/../worlds/Test3
2020-05-26 14:04:02: INFO[Main]: ObjDefManager: added biome: name="default" index=0 uid=60
2020-05-26 14:04:02: INFO[Main]: EmergeManager: using 1 threads
2020-05-26 14:04:02: INFO[Main]: BanManager: loading from /home/juozas/minetest_dev/bin/../worlds/Test3/ipban.txt
2020-05-26 14:04:02: INFO[Main]: BanManager: failed loading from /home/juozas/minetest_dev/bin/../worlds/Test3/ipban.txt
2020-05-26 14:04:02: INFO[Main]: BanManager: creating /home/juozas/minetest_dev/bin/../worlds/Test3/ipban.txt
2020-05-26 14:04:02: INFO[Main]: ServerMap: Metadata loaded from /home/juozas/minetest_dev/bin/../worlds/Test3
2020-05-26 14:04:02: INFO[Main]: Server: Initializing Lua
2020-05-26 14:04:02: INFO[Main]: SCRIPTAPI: Initialized game modules
2020-05-26 14:04:02: INFO[Main]: Server: Loading mods: util_commands unittests testtools testpathfinder testnodes testformspec testfood testentities soundstuff modchannels initial_message experimental dignodes chest_of_everything chest bucket basetools give_initial_stuff basenodes stairs 
2020-05-26 14:04:02: INFO[Main]: tiled mapgen 
2020-05-26 14:04:02: INFO[Main]: Mod "util_commands" loaded after 0 ms
2020-05-26 14:04:02: INFO[Main]: Mod "unittests" loaded after 1 ms
2020-05-26 14:04:02: INFO[Main]: Mod "testtools" loaded after 1 ms
2020-05-26 14:04:02: INFO[Main]: Mod "testpathfinder" loaded after 1 ms
2020-05-26 14:04:02: INFO[Main]: Mod "testnodes" loaded after 27 ms
2020-05-26 14:04:02: INFO[Main]: Mod "testformspec" loaded after 1 ms
2020-05-26 14:04:02: INFO[Main]: Mod "testfood" loaded after 0 ms
2020-05-26 14:04:02: INFO[Main]: Mod "testentities" loaded after 1 ms
2020-05-26 14:04:02: INFO[Main]: Mod "soundstuff" loaded after 2 ms
2020-05-26 14:04:02: INFO[Main]: Mod "modchannels" loaded after 0 ms
2020-05-26 14:04:02: INFO[Main]: Mod "initial_message" loaded after 0 ms
2020-05-26 14:04:02: INFO[Main]: Server creating detached inventory "test_inventory"
2020-05-26 14:04:02: INFO[Main]: [experimental] modname="experimental"
2020-05-26 14:04:02: INFO[Main]: [experimental] modpath="/home/juozas/minetest_dev/bin/../games/devtest/mods/experimental"
2020-05-26 14:04:02: INFO[Main]: [experimental] worldpath="/home/juozas/minetest_dev/bin/../worlds/Test3"
2020-05-26 14:04:02: INFO[Main]: Mod "experimental" loaded after 2 ms
2020-05-26 14:04:02: INFO[Main]: Mod "dignodes" loaded after 2 ms
2020-05-26 14:04:02: INFO[Main]: Server creating detached inventory "everything"
2020-05-26 14:04:02: INFO[Main]: Server creating detached inventory "trash"
2020-05-26 14:04:02: INFO[Main]: Mod "chest_of_everything" loaded after 0 ms
2020-05-26 14:04:02: INFO[Main]: Mod "chest" loaded after 1 ms
2020-05-26 14:04:02: INFO[Main]: Mod "bucket" loaded after 0 ms
2020-05-26 14:04:02: INFO[Main]: Mod "basetools" loaded after 1 ms
2020-05-26 14:04:02: INFO[Main]: Mod "give_initial_stuff" loaded after 0 ms
2020-05-26 14:04:02: INFO[Main]: Mod "basenodes" loaded after 4 ms
2020-05-26 14:04:02: INFO[Main]: Mod "stairs" loaded after 1 ms
2020-05-26 14:04:02: INFO[Main]: Mod "tiled" loaded after 2 ms
2020-05-26 14:04:02: INFO[Main]: ObjDefManager: added biome: name="mapgen:grassland" index=1 uid=18
2020-05-26 14:04:02: INFO[Main]: ObjDefManager: added biome: name="mapgen:grassland_ocean" index=2 uid=28
2020-05-26 14:04:02: INFO[Main]: Mod "mapgen" loaded after 0 ms
2020-05-26 14:04:02: ACTION[Main]: [experimental] on_mods_loaded()
2020-05-26 14:04:02: INFO[Main]: Server: Calculating media file checksums
2020-05-26 14:04:02: INFO[Main]: EmergeManager: Created params 0x56431eabd1a0 for thread 0
2020-05-26 14:04:02: INFO[Main]: ServerEnvironment: Loading default environment metadata
2020-05-26 14:04:02: INFO[Main]: Starting server on 0.0.0.0...
        .__               __                   __   
  _____ |__| ____   _____/  |_  ____   _______/  |_ 
 /     \|  |/    \_/ __ \   __\/ __ \ /  ___/\   __\
|  Y Y  \  |   |  \  ___/|  | \  ___/ \___ \  |  |  
|__|_|  /__|___|  /\___  >__|  \___  >____  > |__|  
      \/        \/     \/          \/     \/        
2020-05-26 14:04:02: ACTION[Main]: World at [/home/juozas/minetest_dev/bin/../worlds/Test3]
2020-05-26 14:04:02: ACTION[Main]: Server for gameid="devtest" listening on 0.0.0.0:51110.
2020-05-26 14:04:02: INFO[Main]: SourceImageCache::getOrLoad(): Loading path "/home/juozas/minetest_dev/bin/../textures/base/pack/minimap_mask_round.png"
2020-05-26 14:04:02: INFO[Main]: SourceImageCache::getOrLoad(): Loading path "/home/juozas/minetest_dev/bin/../textures/base/pack/minimap_overlay_round.png"
2020-05-26 14:04:02: INFO[Main]: SourceImageCache::getOrLoad(): Loading path "/home/juozas/minetest_dev/bin/../textures/base/pack/minimap_mask_square.png"
2020-05-26 14:04:02: INFO[Main]: SourceImageCache::getOrLoad(): Loading path "/home/juozas/minetest_dev/bin/../textures/base/pack/minimap_overlay_square.png"
2020-05-26 14:04:02: INFO[Main]: SourceImageCache::getOrLoad(): Loading path "/home/juozas/minetest_dev/bin/../textures/base/pack/player_marker.png"
2020-05-26 14:04:02: INFO[Main]: SourceImageCache::getOrLoad(): Loading path "/home/juozas/minetest_dev/bin/../textures/base/pack/object_marker_red.png"
2020-05-26 14:04:02: INFO[Main]: Connecting to server at 127.0.0.1:51110
2020-05-26 14:04:02: INFO[Main]: Client packetcounter (30s): sum=0 avg=0/s
2020-05-26 14:04:02: INFO[Main]: Client::peerAdded(): peer->id=1
2020-05-26 14:04:02: INFO[Server]: Server: Maximum lag peaked to 0.278 s
2020-05-26 14:04:02: INFO[Server]: Server: New connection: "singleplayer" from 127.0.0.1 (peer_id=2)
2020-05-26 14:04:02: INFO[Main]: Client: TOCLIENT_HELLO received with serialization_ver=28, auth_mechs=2, proto_ver=39, compression_mode=0. Doing auth with mech 2
2020-05-26 14:04:02: INFO[Server]: Server: TOSERVER_SRP_BYTES_A received with based_on=1 and len_A=256.
2020-05-26 14:04:02: INFO[Main]: Client: Received TOCLIENT_SRP_BYTES_S_B.
2020-05-26 14:04:02: INFO[Main]: Client: received map seed: 9949396603001928797
2020-05-26 14:04:02: INFO[Main]: Client: received recommended send interval 0.09
2020-05-26 14:04:02: INFO[Server]: Server: Sending content to [id=2]
2020-05-26 14:04:02: INFO[Main]: Client: Received item definitions: packet size: 7082
2020-05-26 14:04:02: INFO[Main]: Client: Received node definitions: packet size: 7468
2020-05-26 14:04:02: INFO[Main]: Client: Received media announcement: packet size: 15836
2020-05-26 14:04:02: INFO[Main]: Client: Detached inventory update: "trash", mode=update
2020-05-26 14:04:02: INFO[Main]: Client: Detached inventory update: "everything", mode=update
2020-05-26 14:04:02: INFO[Main]: Client: Detached inventory update: "test_inventory", mode=update
2020-05-26 14:04:02: INFO[Main]: Client::afterContentReceived() started
2020-05-26 14:04:02: INFO[Main]: - Rebuilding images and textures
2020-05-26 14:04:02: INFO[Main]: TextureSource: recreating 9 textures
2020-05-26 14:04:02: INFO[Main]: SourceImageCache::getOrLoad(): No path found for ""
2020-05-26 14:04:02: INFO[Main]: - Rebuilding shaders
2020-05-26 14:04:02: INFO[Main]: - Updating node aliases
2020-05-26 14:04:02: INFO[Main]: - Updating node textures
2020-05-26 14:04:02: INFO[Main]: NodeDefManager::updateTextures(): Updating textures in node definitions
2020-05-26 14:04:02: INFO[Main]: SourceShaderCache::getOrLoad(): Loading path "/home/juozas/minetest_dev/bin/../client/shaders/nodes_shader/opengl_vertex.glsl"
2020-05-26 14:04:02: INFO[Main]: SourceShaderCache::getOrLoad(): Loading path "/home/juozas/minetest_dev/bin/../client/shaders/nodes_shader/opengl_fragment.glsl"
2020-05-26 14:04:02: INFO[Main]: SourceShaderCache::getOrLoad(): No path found for "nodes_shader/opengl_geometry.glsl"
2020-05-26 14:04:02: INFO[Main]: Compiling high level shaders for nodes_shader
2020-05-26 14:04:02: INFO[Main]: getShaderIdDirect(): Returning id=1 for name "nodes_shader"
2020-05-26 14:04:02: INFO[Main]: SourceShaderCache::getOrLoad(): No path found for "nodes_shader/opengl_geometry.glsl"
2020-05-26 14:04:02: INFO[Main]: Compiling high level shaders for nodes_shader
2020-05-26 14:04:02: INFO[Main]: getShaderIdDirect(): Returning id=2 for name "nodes_shader"
2020-05-26 14:04:02: INFO[Main]: SourceShaderCache::getOrLoad(): No path found for "nodes_shader/opengl_geometry.glsl"
2020-05-26 14:04:02: INFO[Main]: Compiling high level shaders for nodes_shader
2020-05-26 14:04:02: INFO[Main]: getShaderIdDirect(): Returning id=3 for name "nodes_shader"
2020-05-26 14:04:02: INFO[Main]: SourceShaderCache::getOrLoad(): No path found for "nodes_shader/opengl_geometry.glsl"
2020-05-26 14:04:02: INFO[Main]: Compiling high level shaders for nodes_shader
2020-05-26 14:04:02: INFO[Main]: getShaderIdDirect(): Returning id=4 for name "nodes_shader"
2020-05-26 14:04:02: INFO[Main]: SourceShaderCache::getOrLoad(): No path found for "nodes_shader/opengl_geometry.glsl"
2020-05-26 14:04:02: INFO[Main]: Compiling high level shaders for nodes_shader
2020-05-26 14:04:02: INFO[Main]: getShaderIdDirect(): Returning id=5 for name "nodes_shader"
2020-05-26 14:04:02: INFO[Main]: SourceShaderCache::getOrLoad(): No path found for "nodes_shader/opengl_geometry.glsl"
2020-05-26 14:04:02: INFO[Main]: Compiling high level shaders for nodes_shader
2020-05-26 14:04:02: INFO[Main]: getShaderIdDirect(): Returning id=6 for name "nodes_shader"
2020-05-26 14:04:02: INFO[Main]: SourceShaderCache::getOrLoad(): No path found for "nodes_shader/opengl_geometry.glsl"
2020-05-26 14:04:02: INFO[Main]: Compiling high level shaders for nodes_shader
2020-05-26 14:04:02: INFO[Main]: getShaderIdDirect(): Returning id=7 for name "nodes_shader"
2020-05-26 14:04:02: INFO[Main]: SourceShaderCache::getOrLoad(): No path found for "nodes_shader/opengl_geometry.glsl"
2020-05-26 14:04:02: INFO[Main]: Compiling high level shaders for nodes_shader
2020-05-26 14:04:02: INFO[Main]: getShaderIdDirect(): Returning id=8 for name "nodes_shader"
2020-05-26 14:04:02: INFO[Main]: SourceShaderCache::getOrLoad(): No path found for "nodes_shader/opengl_geometry.glsl"
2020-05-26 14:04:02: INFO[Main]: Compiling high level shaders for nodes_shader
2020-05-26 14:04:02: INFO[Main]: getShaderIdDirect(): Returning id=9 for name "nodes_shader"
2020-05-26 14:04:02: INFO[Main]: SourceShaderCache::getOrLoad(): No path found for "nodes_shader/opengl_geometry.glsl"
2020-05-26 14:04:02: INFO[Main]: Compiling high level shaders for nodes_shader
2020-05-26 14:04:02: INFO[Main]: getShaderIdDirect(): Returning id=10 for name "nodes_shader"
2020-05-26 14:04:02: INFO[Main]: SourceShaderCache::getOrLoad(): No path found for "nodes_shader/opengl_geometry.glsl"
2020-05-26 14:04:02: INFO[Main]: Compiling high level shaders for nodes_shader
2020-05-26 14:04:02: INFO[Main]: getShaderIdDirect(): Returning id=11 for name "nodes_shader"
2020-05-26 14:04:02: INFO[Main]: SourceShaderCache::getOrLoad(): No path found for "nodes_shader/opengl_geometry.glsl"
2020-05-26 14:04:02: INFO[Main]: Compiling high level shaders for nodes_shader
2020-05-26 14:04:02: INFO[Main]: getShaderIdDirect(): Returning id=12 for name "nodes_shader"
2020-05-26 14:04:02: INFO[Main]: SourceShaderCache::getOrLoad(): No path found for "nodes_shader/opengl_geometry.glsl"
2020-05-26 14:04:02: INFO[Main]: Compiling high level shaders for nodes_shader
2020-05-26 14:04:02: INFO[Main]: getShaderIdDirect(): Returning id=13 for name "nodes_shader"
2020-05-26 14:04:02: INFO[Main]: SourceShaderCache::getOrLoad(): No path found for "nodes_shader/opengl_geometry.glsl"
2020-05-26 14:04:02: INFO[Main]: Compiling high level shaders for nodes_shader
2020-05-26 14:04:02: INFO[Main]: getShaderIdDirect(): Returning id=14 for name "nodes_shader"
minetest: /home/juozas/minetest_dev/src/nodedef.cpp:742: void ContentFeatures::updateTextures(ITextureSource*, IShaderSource*, irr::scene::IMeshManipulator*, Client*, const TextureSettings&): Assertion `liquid_type == LIQUID_SOURCE' failed.
Aborted (core dumped)
```

</details>
<details>
<summary>gdb debug backtrace+log</summary>

```
GNU gdb (Ubuntu 9.1-0ubuntu1) 9.1
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./bin/minetest...
(gdb) set pagination off 
(gdb) r
Starting program: /home/juozas/minetest_dev/bin/minetest 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff29e3700 (LWP 7404)]
[Thread 0x7ffff29e3700 (LWP 7404) exited]
[New Thread 0x7ffff226f700 (LWP 7405)]
[New Thread 0x7ffff226f700 (LWP 7406)]
[Thread 0x7ffff226f700 (LWP 7405) exited]
[New Thread 0x7ffff1a6e700 (LWP 7407)]
[New Thread 0x7ffff1046700 (LWP 7408)]
[New Thread 0x7ffff0911700 (LWP 7409)]
[New Thread 0x7fffd3fff700 (LWP 7410)]
[New Thread 0x7fffd37fe700 (LWP 7411)]
[New Thread 0x7fffd2ffd700 (LWP 7412)]
Loaded texture: /home/juozas/minetest_dev/games/minetest_game/menu/header.png
Loaded texture: /home/juozas/minetest_dev/games/devtest/menu/icon.png
Loaded texture: /home/juozas/minetest_dev/games/minetest_game/menu/icon.png
Loaded texture: /home/juozas/minetest_dev/games/devtest/menu/background.png
Loaded texture: /home/juozas/minetest_dev/games/devtest/menu/header.png
[Thread 0x7fffd2ffd700 (LWP 7412) exited]
[Thread 0x7fffd37fe700 (LWP 7411) exited]
[Thread 0x7fffd3fff700 (LWP 7410) exited]
[Thread 0x7ffff0911700 (LWP 7409) exited]
[New Thread 0x7fffd2ffd700 (LWP 7413)]
[New Thread 0x7fffd37fe700 (LWP 7414)]
2020-05-26 14:08:04: ACTION[Main]: [experimental] on_mods_loaded()
[New Thread 0x7fffd3fff700 (LWP 7415)]
        .__               __                   __   
  _____ |__| ____   _____/  |_  ____   _______/  |_ 
 /     \|  |/    \_/ __ \   __\/ __ \ /  ___/\   __\
|  Y Y  \  |   |  \  ___/|  | \  ___/ \___ \  |  |  
|__|_|  /__|___|  /\___  >__|  \___  >____  > |__|  
      \/        \/     \/          \/     \/        
2020-05-26 14:08:04: ACTION[Main]: World at [/home/juozas/minetest_dev/bin/../worlds/Test3]
2020-05-26 14:08:04: ACTION[Main]: Server for gameid="devtest" listening on 0.0.0.0:58134.
[New Thread 0x7ffff0911700 (LWP 7416)]
[New Thread 0x7fffd257c700 (LWP 7417)]
[New Thread 0x7fffd197b700 (LWP 7418)]
minetest: /home/juozas/minetest_dev/src/nodedef.cpp:742: void ContentFeatures::updateTextures(ITextureSource*, IShaderSource*, irr::scene::IMeshManipulator*, Client*, const TextureSettings&): Assertion `liquid_type == LIQUID_SOURCE' failed.

Thread 1 "minetest" received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) thread apply all backtrace full 

Thread 16 (Thread 0x7fffd197b700 (LWP 7418)):
#0  futex_abstimed_wait_cancelable (private=0, abstime=0x0, clockid=0, expected=0, futex_word=0x555556aa0800) at ../sysdeps/nptl/futex-internal.h:320
        __ret = -512
        op = 393
        __ret = <optimized out>
        oldtype = 0
        err = <optimized out>
        oldtype = <optimized out>
        err = <optimized out>
        __ret = <optimized out>
        clockbit = <optimized out>
        op = <optimized out>
        __ret = <optimized out>
        resultvar = <optimized out>
        __arg6 = <optimized out>
        __arg5 = <optimized out>
        __arg4 = <optimized out>
        __arg3 = <optimized out>
        __arg2 = <optimized out>
        __arg1 = <optimized out>
        _a6 = <optimized out>
        _a5 = <optimized out>
        _a4 = <optimized out>
        _a3 = <optimized out>
        _a2 = <optimized out>
        _a1 = <optimized out>
#1  do_futex_wait (sem=sem@entry=0x555556aa0800, abstime=0x0, clockid=0) at sem_waitcommon.c:112
        err = <optimized out>
#2  0x00007ffff75754e8 in __new_sem_wait_slow (sem=0x555556aa0800, abstime=0x0, clockid=0) at sem_waitcommon.c:184
        _buffer = {__routine = 0x7ffff75753a0 <__sem_wait_cleanup>, __arg = 0x555556aa0800, __canceltype = 1442539228, __prev = 0x0}
        err = <optimized out>
        d = 0
#3  0x0000555555fb5f8a in Semaphore::wait (this=0x555556aa0800) at /home/juozas/minetest_dev/src/threading/semaphore.cpp:105
        ret = 21845
        __PRETTY_FUNCTION__ = "void Semaphore::wait()"
#4  0x0000555555c32f07 in UpdateThread::run (this=0x555556aa0770) at /home/juozas/minetest_dev/src/util/thread.h:209
No locals.
#5  0x0000555555fb674f in Thread::threadProc (thr=0x555556aa0770) at /home/juozas/minetest_dev/src/threading/thread.cpp:196
No locals.
#6  0x0000555555fb7699 in std::__invoke_impl<void, void (*)(Thread*), Thread*> (__f=@0x5555578df230: 0x555555fb66dc <Thread::threadProc(Thread*)>) at /usr/include/c++/9/bits/invoke.h:60
No locals.
#7  0x0000555555fb75e5 in std::__invoke<void (*)(Thread*), Thread*> (__fn=@0x5555578df230: 0x555555fb66dc <Thread::threadProc(Thread*)>) at /usr/include/c++/9/bits/invoke.h:95
No locals.
#8  0x0000555555fb7535 in std::thread::_Invoker<std::tuple<void (*)(Thread*), Thread*> >::_M_invoke<0ul, 1ul> (this=0x5555578df228) at /usr/include/c++/9/thread:244
No locals.
#9  0x0000555555fb74d7 in std::thread::_Invoker<std::tuple<void (*)(Thread*), Thread*> >::operator() (this=0x5555578df228) at /usr/include/c++/9/thread:251
No locals.
#10 0x0000555555fb74a8 in std::thread::_State_impl<std::thread::_Invoker<std::tuple<void (*)(Thread*), Thread*> > >::_M_run (this=0x5555578df220) at /usr/include/c++/9/thread:195
No locals.
#11 0x00007ffff70e6cb4 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
No symbol table info available.
#12 0x00007ffff756b609 in start_thread (arg=<optimized out>) at pthread_create.c:477
        ret = <optimized out>
        pd = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140736709768960, -7662192211799794329, 140737488342174, 140737488342175, 140737488342176, 140736709763968, 7662258939658542439, 7662173736804195687}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = 0
#13 0x00007ffff6dd4103 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
No locals.

Thread 15 (Thread 0x7fffd257c700 (LWP 7417)):
#0  0x00007ffff6dc9f9b in __GI___select (nfds=20, readfds=0x7fffd257ac50, writefds=0x0, exceptfds=0x0, timeout=0x7fffd257ac20) at ../sysdeps/unix/sysv/linux/select.c:41
        resultvar = 18446744073709551102
        sc_cancel_oldtype = 0
        sc_ret = <optimized out>
#1  0x0000555555efefe6 in UDPSocket::WaitData (this=0x555556cee6a0, timeout_ms=500) at /home/juozas/minetest_dev/src/network/socket.cpp:339
        readset = {fds_bits = {524288, 0 <repeats 15 times>}}
        result = 0
        tv = {tv_sec = 0, tv_usec = 381056}
#2  0x0000555555efeb63 in UDPSocket::Receive (this=0x555556cee6a0, sender=..., data=0x7fffb8000df0, size=1500) at /home/juozas/minetest_dev/src/network/socket.cpp:254
        received = -766005936
#3  0x0000555555ee28e9 in con::ConnectionReceiveThread::receive (this=0x555556c7eb50, packetdata=..., packet_queued=@0x7fffd257af5b: false) at /home/juozas/minetest_dev/src/network/connectionthreads.cpp:928
        received_size = 32767
        peer = {m_peer = 0x4}
        channel = 0x7fffd257ae20
        sender = {m_addr_family = 0, m_address = {ipv4 = {sin_family = 0, sin_port = 0, sin_addr = {s_addr = 0}, sin_zero = "\000\000\000\000\000\000\000"}, ipv6 = {sin6_family = 0, sin6_port = 0, sin6_flowinfo = 0, sin6_addr = {__in6_u = {__u6_addr8 = '\000' <repeats 15 times>, __u6_addr16 = {0, 0, 0, 0, 0, 0, 0, 0}, __u6_addr32 = {0, 0, 0, 0}}}, sin6_scope_id = 0}}, m_port = 0}
        peer_id = 47104
        channelnum = 20 '\024'
        peer_address = {m_addr_family = 4294954208, m_address = {ipv4 = {sin_family = 32767, sin_port = 0, sin_addr = {s_addr = 4145360494}, sin_zero = "\001\000\000\000\360\256W\322"}, ipv6 = {sin6_family = 32767, sin6_port = 0, sin6_flowinfo = 4145360494, sin6_addr = {__in6_u = {__u6_addr8 = "\001\000\000\000\360\256W\322\377\177\000\000\r\205\006V", __u6_addr16 = {1, 0, 44784, 53847, 32767, 0, 34061, 22022}, __u6_addr32 = {1, 3528961776, 32767, 1443267853}}}, sin6_scope_id = 21845}}, m_port = 52447}
        strippeddata = {data = 0x7fffd257afa8 "\220,", m_size = 3528961632, refcount = 0x7fffffffccde}
#4  0x0000555555ee2610 in con::ConnectionReceiveThread::run (this=0x555556c7eb50) at /home/juozas/minetest_dev/src/network/connectionthreads.cpp:839
        sp = {m_profiler = 0x5555565b9d80 <main_profiler>, m_name = "ConnectionReceive: [con(19/0)] [ms]", m_timer = 0x7fffb80014b0, m_type = SPT_AVG}
        __PRETTY_FUNCTION__ = "virtual void* con::ConnectionReceiveThread::run()"
        ThreadIdentifier = <incomplete type>
        packet_maxsize = 1500
        packetdata = {data = 0x7fffb8000df0 "OEt\003", m_size = 1500, refcount = 0x7fffb80013e0}
        packet_queued = false
#5  0x0000555555fb674f in Thread::threadProc (thr=0x555556c7eb50) at /home/juozas/minetest_dev/src/threading/thread.cpp:196
No locals.
#6  0x0000555555fb7699 in std::__invoke_impl<void, void (*)(Thread*), Thread*> (__f=@0x555556c96a80: 0x555555fb66dc <Thread::threadProc(Thread*)>) at /usr/include/c++/9/bits/invoke.h:60
No locals.
#7  0x0000555555fb75e5 in std::__invoke<void (*)(Thread*), Thread*> (__fn=@0x555556c96a80: 0x555555fb66dc <Thread::threadProc(Thread*)>) at /usr/include/c++/9/bits/invoke.h:95
No locals.
#8  0x0000555555fb7535 in std::thread::_Invoker<std::tuple<void (*)(Thread*), Thread*> >::_M_invoke<0ul, 1ul> (this=0x555556c96a78) at /usr/include/c++/9/thread:244
No locals.
#9  0x0000555555fb74d7 in std::thread::_Invoker<std::tuple<void (*)(Thread*), Thread*> >::operator() (this=0x555556c96a78) at /usr/include/c++/9/thread:251
No locals.
#10 0x0000555555fb74a8 in std::thread::_State_impl<std::thread::_Invoker<std::tuple<void (*)(Thread*), Thread*> > >::_M_run (this=0x555556c96a70) at /usr/include/c++/9/thread:195
No locals.
#11 0x00007ffff70e6cb4 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
No symbol table info available.
#12 0x00007ffff756b609 in start_thread (arg=<optimized out>) at pthread_create.c:477
        ret = <optimized out>
        pd = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140736722355968, -7662192211799794329, 140737488342238, 140737488342239, 140737488342240, 140736722350976, 7662250693858205031, 7662173736804195687}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = 0
#13 0x00007ffff6dd4103 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
No locals.

Thread 14 (Thread 0x7ffff0911700 (LWP 7416)):
#0  0x00007ffff7575618 in futex_abstimed_wait_cancelable (private=0, abstime=0x7ffff090fe80, clockid=0, expected=0, futex_word=0x555556a904f0) at ../sysdeps/nptl/futex-internal.h:320
        __arg6 = 4294967295
        __arg3 = 0
        _a5 = 0
        _a2 = 393
        __arg4 = 140737229422208
        __arg1 = 93825014498544
        _a6 = 4294967295
        _a3 = 0
        resultvar = <optimized out>
        __arg5 = 0
        __arg2 = 393
        _a4 = 140737229422208
        _a1 = 93825014498544
        __ret = <optimized out>
        clockbit = 256
        op = 393
        __ret = <optimized out>
        oldtype = 0
        err = <optimized out>
        oldtype = <optimized out>
        err = <optimized out>
        __ret = <optimized out>
        clockbit = <optimized out>
        op = <optimized out>
        __ret = <optimized out>
        resultvar = <optimized out>
        __arg6 = <optimized out>
        __arg5 = <optimized out>
        __arg4 = <optimized out>
        __arg3 = <optimized out>
        __arg2 = <optimized out>
        __arg1 = <optimized out>
        _a6 = <optimized out>
        _a5 = <optimized out>
        _a4 = <optimized out>
        _a3 = <optimized out>
        _a2 = <optimized out>
        _a1 = <optimized out>
#1  do_futex_wait (sem=sem@entry=0x555556a904f0, abstime=abstime@entry=0x7ffff090fe80, clockid=0) at sem_waitcommon.c:112
No locals.
#2  0x00007ffff7575743 in __new_sem_wait_slow (sem=0x555556a904f0, abstime=0x7ffff090fe80, clockid=0) at sem_waitcommon.c:184
        _buffer = {__routine = 0x7ffff75755b0 <__sem_wait_cleanup>, __arg = 0x555556a904f0, __canceltype = 0, __prev = 0x0}
        err = <optimized out>
        d = 0
#3  0x0000555555fb60f3 in Semaphore::wait (this=0x555556a904f0, time_ms=50) at /home/juozas/minetest_dev/src/threading/semaphore.cpp:157
        wait_time = {tv_sec = 1590491284, tv_nsec = 805792000}
        now = {tv_sec = 1590491284, tv_usec = 755792}
        ret = -355805827
        __PRETTY_FUNCTION__ = "bool Semaphore::wait(unsigned int)"
#4  0x0000555555edcb7e in con::ConnectionSendThread::run (this=0x555556a90400) at /home/juozas/minetest_dev/src/network/connectionthreads.cpp:101
        sp = {m_profiler = 0x5555565b9d80 <main_profiler>, m_name = "ConnectionSend: [con(19/0)] [ms]", m_timer = 0x7fffcc000f30, m_type = SPT_AVG}
        dtime = 0.050999999
        c = {type = con::CONNCMD_NONE, address = {m_addr_family = 0, m_address = {ipv4 = {sin_family = 0, sin_port = 0, sin_addr = {s_addr = 0}, sin_zero = "\000\000\000\000\000\000\000"}, ipv6 = {sin6_family = 0, sin6_port = 0, sin6_flowinfo = 0, sin6_addr = {__in6_u = {__u6_addr8 = '\000' <repeats 15 times>, __u6_addr16 = {0, 0, 0, 0, 0, 0, 0, 0}, __u6_addr32 = {0, 0, 0, 0}}}, sin6_scope_id = 0}}, m_port = 0}, peer_id = 0, channelnum = 0 '\000', data = {data = 0x0, m_size = 0}, reliable = false, raw = false}
        __PRETTY_FUNCTION__ = "virtual void* con::ConnectionSendThread::run()"
        curtime = 16185171
        lasttime = 16185120
        ThreadIdentifier = <incomplete type>
#5  0x0000555555fb674f in Thread::threadProc (thr=0x555556a90400) at /home/juozas/minetest_dev/src/threading/thread.cpp:196
No locals.
#6  0x0000555555fb7699 in std::__invoke_impl<void, void (*)(Thread*), Thread*> (__f=@0x555556cc6590: 0x555555fb66dc <Thread::threadProc(Thread*)>) at /usr/include/c++/9/bits/invoke.h:60
No locals.
#7  0x0000555555fb75e5 in std::__invoke<void (*)(Thread*), Thread*> (__fn=@0x555556cc6590: 0x555555fb66dc <Thread::threadProc(Thread*)>) at /usr/include/c++/9/bits/invoke.h:95
No locals.
#8  0x0000555555fb7535 in std::thread::_Invoker<std::tuple<void (*)(Thread*), Thread*> >::_M_invoke<0ul, 1ul> (this=0x555556cc6588) at /usr/include/c++/9/thread:244
No locals.
#9  0x0000555555fb74d7 in std::thread::_Invoker<std::tuple<void (*)(Thread*), Thread*> >::operator() (this=0x555556cc6588) at /usr/include/c++/9/thread:251
No locals.
#10 0x0000555555fb74a8 in std::thread::_State_impl<std::thread::_Invoker<std::tuple<void (*)(Thread*), Thread*> > >::_M_run (this=0x555556cc6580) at /usr/include/c++/9/thread:195
No locals.
#11 0x00007ffff70e6cb4 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
No symbol table info available.
#12 0x00007ffff756b609 in start_thread (arg=<optimized out>) at pthread_create.c:477
        ret = <optimized out>
        pd = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140737229428480, -7662192211799794329, 140737488342238, 140737488342239, 140737488342240, 140737229423488, 7662186357932465511, 7662173736804195687}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = 0
#13 0x00007ffff6dd4103 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
No locals.

Thread 13 (Thread 0x7fffd3fff700 (LWP 7415)):
#0  0x00007ffff7575618 in futex_abstimed_wait_cancelable (private=0, abstime=0x7fffd3ffd6f0, clockid=0, expected=0, futex_word=0x5555566c9910) at ../sysdeps/nptl/futex-internal.h:320
        __arg6 = 4294967295
        __arg3 = 0
        _a5 = 0
        _a2 = 393
        __arg4 = 140736750147312
        __arg1 = 93825010538768
        _a6 = 4294967295
        _a3 = 0
        resultvar = <optimized out>
        __arg5 = 0
        __arg2 = 393
        _a4 = 140736750147312
        _a1 = 93825010538768
        __ret = <optimized out>
        clockbit = 256
        op = 393
        __ret = <optimized out>
        oldtype = 0
        err = <optimized out>
        oldtype = <optimized out>
        err = <optimized out>
        __ret = <optimized out>
        clockbit = <optimized out>
        op = <optimized out>
        __ret = <optimized out>
        resultvar = <optimized out>
        __arg6 = <optimized out>
        __arg5 = <optimized out>
        __arg4 = <optimized out>
        __arg3 = <optimized out>
        __arg2 = <optimized out>
        __arg1 = <optimized out>
        _a6 = <optimized out>
        _a5 = <optimized out>
        _a4 = <optimized out>
        _a3 = <optimized out>
        _a2 = <optimized out>
        _a1 = <optimized out>
#1  do_futex_wait (sem=sem@entry=0x5555566c9910, abstime=abstime@entry=0x7fffd3ffd6f0, clockid=0) at sem_waitcommon.c:112
No locals.
#2  0x00007ffff7575743 in __new_sem_wait_slow (sem=0x5555566c9910, abstime=0x7fffd3ffd6f0, clockid=0) at sem_waitcommon.c:184
        _buffer = {__routine = 0x7ffff75755b0 <__sem_wait_cleanup>, __arg = 0x5555566c9910, __canceltype = 0, __prev = 0x0}
        err = <optimized out>
        d = 0
#3  0x0000555555fb60f3 in Semaphore::wait (this=0x5555566c9910, time_ms=30) at /home/juozas/minetest_dev/src/threading/semaphore.cpp:157
        wait_time = {tv_sec = 1590491284, tv_nsec = 801195000}
        now = {tv_sec = 1590491284, tv_usec = 771195}
        ret = 32767
        __PRETTY_FUNCTION__ = "bool Semaphore::wait(unsigned int)"
#4  0x0000555555ecfdb2 in MutexedQueue<con::ConnectionEvent>::pop_front (this=0x5555566c9898, wait_time_max_ms=30) at /home/juozas/minetest_dev/src/util/container.h:164
No locals.
#5  0x0000555555ec9e67 in con::Connection::waitEvent (this=0x5555566c97f0, timeout_ms=30) at /home/juozas/minetest_dev/src/network/connection.cpp:1293
No locals.
#6  0x0000555555eca364 in con::Connection::Receive (this=0x5555566c97f0, pkt=0x7fffd3ffe060, timeout=30) at /home/juozas/minetest_dev/src/network/connection.cpp:1355
        e = {type = 3556759760, peer_id = 32767, data = {data = 0x555556654388 "\360!eVUU", m_size = 3556760704}, timeout = 120, address = {m_addr_family = 21845, m_address = {ipv4 = {sin_family = 55568, sin_port = 54271, sin_addr = {s_addr = 32767}, sin_zero = "M\267\034VUU\000"}, ipv6 = {sin6_family = 55568, sin6_port = 54271, sin6_flowinfo = 32767, sin6_addr = {__in6_u = {__u6_addr8 = "M\267\034VUU\000\000\000\331\377\323\377\177\000", __u6_addr16 = {46925, 22044, 21845, 0, 55552, 54271, 32767, 0}, __u6_addr32 = {1444722509, 21845, 3556759808, 32767}}}, sin6_scope_id = 1449476992}}, m_port = 21845}}
#7  0x0000555555eca7a8 in con::Connection::Receive (this=0x5555566c97f0, pkt=0x7fffd3ffe060) at /home/juozas/minetest_dev/src/network/connection.cpp:1392
        any = false
#8  0x000055555616ece8 in Server::Receive (this=0x555556ab2ee0) at /home/juozas/minetest_dev/src/server.cpp:973
        pkt = {m_data = std::vector of length 0, capacity 0, m_datasize = 0, m_read_offset = 0, m_command = 0, m_peer_id = 0}
        peer_id = 0
        first = true
#9  0x000055555616847e in ServerThread::run (this=0x555556a98570) at /home/juozas/minetest_dev/src/server.cpp:112
No locals.
#10 0x0000555555fb674f in Thread::threadProc (thr=0x555556a98570) at /home/juozas/minetest_dev/src/threading/thread.cpp:196
No locals.
#11 0x0000555555fb7699 in std::__invoke_impl<void, void (*)(Thread*), Thread*> (__f=@0x555556cc7be0: 0x555555fb66dc <Thread::threadProc(Thread*)>) at /usr/include/c++/9/bits/invoke.h:60
No locals.
#12 0x0000555555fb75e5 in std::__invoke<void (*)(Thread*), Thread*> (__fn=@0x555556cc7be0: 0x555555fb66dc <Thread::threadProc(Thread*)>) at /usr/include/c++/9/bits/invoke.h:95
No locals.
#13 0x0000555555fb7535 in std::thread::_Invoker<std::tuple<void (*)(Thread*), Thread*> >::_M_invoke<0ul, 1ul> (this=0x555556cc7bd8) at /usr/include/c++/9/thread:244
No locals.
#14 0x0000555555fb74d7 in std::thread::_Invoker<std::tuple<void (*)(Thread*), Thread*> >::operator() (this=0x555556cc7bd8) at /usr/include/c++/9/thread:251
No locals.
#15 0x0000555555fb74a8 in std::thread::_State_impl<std::thread::_Invoker<std::tuple<void (*)(Thread*), Thread*> > >::_M_run (this=0x555556cc7bd0) at /usr/include/c++/9/thread:195
No locals.
#16 0x00007ffff70e6cb4 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
No symbol table info available.
#17 0x00007ffff756b609 in start_thread (arg=<optimized out>) at pthread_create.c:477
        ret = <optimized out>
        pd = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140736750155520, -7662192211799794329, 140737488342670, 140737488342671, 140737488342672, 140736750150528, 7662253783550303591, 7662173736804195687}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = 0
#18 0x00007ffff6dd4103 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
No locals.

Thread 12 (Thread 0x7fffd37fe700 (LWP 7414)):
#0  0x00007ffff6dc9f9b in __GI___select (nfds=19, readfds=0x7fffd37fcc50, writefds=0x0, exceptfds=0x0, timeout=0x7fffd37fcc20) at ../sysdeps/unix/sysv/linux/select.c:41
        resultvar = 18446744073709551102
        sc_cancel_oldtype = 0
        sc_ret = <optimized out>
#1  0x0000555555efefe6 in UDPSocket::WaitData (this=0x5555566c97f0, timeout_ms=500) at /home/juozas/minetest_dev/src/network/socket.cpp:339
        readset = {fds_bits = {262144, 0 <repeats 15 times>}}
        result = 0
        tv = {tv_sec = 0, tv_usec = 383684}
#2  0x0000555555efeb63 in UDPSocket::Receive (this=0x5555566c97f0, sender=..., data=0x7fffc8001180, size=1500) at /home/juozas/minetest_dev/src/network/socket.cpp:254
        received = -746599088
#3  0x0000555555ee28e9 in con::ConnectionReceiveThread::receive (this=0x555556aaee70, packetdata=..., packet_queued=@0x7fffd37fcf5b: false) at /home/juozas/minetest_dev/src/network/connectionthreads.cpp:928
        received_size = 32767
        peer = {m_peer = 0x4}
        channel = 0x7fffd37fce20
        sender = {m_addr_family = 0, m_address = {ipv4 = {sin_family = 0, sin_port = 0, sin_addr = {s_addr = 0}, sin_zero = "\000\000\000\000\000\000\000"}, ipv6 = {sin6_family = 0, sin6_port = 0, sin6_flowinfo = 0, sin6_addr = {__in6_u = {__u6_addr8 = '\000' <repeats 15 times>, __u6_addr16 = {0, 0, 0, 0, 0, 0, 0, 0}, __u6_addr32 = {0, 0, 0, 0}}}, sin6_scope_id = 0}}, m_port = 0}
        peer_id = 51200
        channelnum = 14 '\016'
        peer_address = {m_addr_family = 4294953168, m_address = {ipv4 = {sin_family = 32767, sin_port = 0, sin_addr = {s_addr = 4145360494}, sin_zero = "\001\000\000\000\360\316\177\323"}, ipv6 = {sin6_family = 32767, sin6_port = 0, sin6_flowinfo = 4145360494, sin6_addr = {__in6_u = {__u6_addr8 = "\001\000\000\000\360\316\177\323\377\177\000\000\r\205\006V", __u6_addr16 = {1, 0, 52976, 54143, 32767, 0, 34061, 22022}, __u6_addr32 = {1, 3548368624, 32767, 1443267853}}}, sin6_scope_id = 21845}}, m_port = 51407}
        strippeddata = {data = 0x7fffd37fcfa8 "`\v", m_size = 3548368480, refcount = 0x7fffffffc8ce}
#4  0x0000555555ee2610 in con::ConnectionReceiveThread::run (this=0x555556aaee70) at /home/juozas/minetest_dev/src/network/connectionthreads.cpp:839
        sp = {m_profiler = 0x5555565b9d80 <main_profiler>, m_name = "ConnectionReceive: [con(18/0)] [ms]", m_timer = 0x7fffc8000ec0, m_type = SPT_AVG}
        __PRETTY_FUNCTION__ = "virtual void* con::ConnectionReceiveThread::run()"
        ThreadIdentifier = <incomplete type>
        packet_maxsize = 1500
        packetdata = {data = 0x7fffc8001180 "OEt\003", m_size = 1500, refcount = 0x7fffc8000c30}
        packet_queued = false
#5  0x0000555555fb674f in Thread::threadProc (thr=0x555556aaee70) at /home/juozas/minetest_dev/src/threading/thread.cpp:196
No locals.
#6  0x0000555555fb7699 in std::__invoke_impl<void, void (*)(Thread*), Thread*> (__f=@0x555556a99470: 0x555555fb66dc <Thread::threadProc(Thread*)>) at /usr/include/c++/9/bits/invoke.h:60
No locals.
#7  0x0000555555fb75e5 in std::__invoke<void (*)(Thread*), Thread*> (__fn=@0x555556a99470: 0x555555fb66dc <Thread::threadProc(Thread*)>) at /usr/include/c++/9/bits/invoke.h:95
No locals.
#8  0x0000555555fb7535 in std::thread::_Invoker<std::tuple<void (*)(Thread*), Thread*> >::_M_invoke<0ul, 1ul> (this=0x555556a99468) at /usr/include/c++/9/thread:244
No locals.
#9  0x0000555555fb74d7 in std::thread::_Invoker<std::tuple<void (*)(Thread*), Thread*> >::operator() (this=0x555556a99468) at /usr/include/c++/9/thread:251
No locals.
#10 0x0000555555fb74a8 in std::thread::_State_impl<std::thread::_Invoker<std::tuple<void (*)(Thread*), Thread*> > >::_M_run (this=0x555556a99460) at /usr/include/c++/9/thread:195
No locals.
#11 0x00007ffff70e6cb4 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
No symbol table info available.
#12 0x00007ffff756b609 in start_thread (arg=<optimized out>) at pthread_create.c:477
        ret = <optimized out>
        pd = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140736741762816, -7662192211799794329, 140737488341198, 140737488341199, 140737488341200, 140736741757824, 7662252683501804903, 7662173736804195687}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = 0
#13 0x00007ffff6dd4103 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
No locals.

Thread 11 (Thread 0x7fffd2ffd700 (LWP 7413)):
#0  0x00007ffff7575618 in futex_abstimed_wait_cancelable (private=0, abstime=0x7fffd2ffbe80, clockid=0, expected=0, futex_word=0x555556a90810) at ../sysdeps/nptl/futex-internal.h:320
        __arg6 = 4294967295
        __arg3 = 0
        _a5 = 0
        _a2 = 393
        __arg4 = 140736733363840
        __arg1 = 93825014499344
        _a6 = 4294967295
        _a3 = 0
        resultvar = <optimized out>
        __arg5 = 0
        __arg2 = 393
        _a4 = 140736733363840
        _a1 = 93825014499344
        __ret = <optimized out>
        clockbit = 256
        op = 393
        __ret = <optimized out>
        oldtype = 0
        err = <optimized out>
        oldtype = <optimized out>
        err = <optimized out>
        __ret = <optimized out>
        clockbit = <optimized out>
        op = <optimized out>
        __ret = <optimized out>
        resultvar = <optimized out>
        __arg6 = <optimized out>
        __arg5 = <optimized out>
        __arg4 = <optimized out>
        __arg3 = <optimized out>
        __arg2 = <optimized out>
        __arg1 = <optimized out>
        _a6 = <optimized out>
        _a5 = <optimized out>
        _a4 = <optimized out>
        _a3 = <optimized out>
        _a2 = <optimized out>
        _a1 = <optimized out>
#1  do_futex_wait (sem=sem@entry=0x555556a90810, abstime=abstime@entry=0x7fffd2ffbe80, clockid=0) at sem_waitcommon.c:112
No locals.
#2  0x00007ffff7575743 in __new_sem_wait_slow (sem=0x555556a90810, abstime=0x7fffd2ffbe80, clockid=0) at sem_waitcommon.c:184
        _buffer = {__routine = 0x7ffff75755b0 <__sem_wait_cleanup>, __arg = 0x555556a90810, __canceltype = 0, __prev = 0x0}
        err = <optimized out>
        d = 0
#3  0x0000555555fb60f3 in Semaphore::wait (this=0x555556a90810, time_ms=50) at /home/juozas/minetest_dev/src/threading/semaphore.cpp:157
        wait_time = {tv_sec = 1590491284, tv_nsec = 807787000}
        now = {tv_sec = 1590491284, tv_usec = 757787}
        ret = -355805827
        __PRETTY_FUNCTION__ = "bool Semaphore::wait(unsigned int)"
#4  0x0000555555edcb7e in con::ConnectionSendThread::run (this=0x555556a90720) at /home/juozas/minetest_dev/src/network/connectionthreads.cpp:101
        sp = {m_profiler = 0x5555565b9d80 <main_profiler>, m_name = "ConnectionSend: [con(18/0)] [ms]", m_timer = 0x7fffc0025ea0, m_type = SPT_AVG}
        dtime = 0.050999999
        c = {type = con::CONNCMD_NONE, address = {m_addr_family = 0, m_address = {ipv4 = {sin_family = 0, sin_port = 0, sin_addr = {s_addr = 0}, sin_zero = "\000\000\000\000\000\000\000"}, ipv6 = {sin6_family = 0, sin6_port = 0, sin6_flowinfo = 0, sin6_addr = {__in6_u = {__u6_addr8 = '\000' <repeats 15 times>, __u6_addr16 = {0, 0, 0, 0, 0, 0, 0, 0}, __u6_addr32 = {0, 0, 0, 0}}}, sin6_scope_id = 0}}, m_port = 0}, peer_id = 0, channelnum = 0 '\000', data = {data = 0x0, m_size = 0}, reliable = false, raw = false}
        __PRETTY_FUNCTION__ = "virtual void* con::ConnectionSendThread::run()"
        curtime = 16185173
        lasttime = 16185122
        ThreadIdentifier = <incomplete type>
#5  0x0000555555fb674f in Thread::threadProc (thr=0x555556a90720) at /home/juozas/minetest_dev/src/threading/thread.cpp:196
No locals.
#6  0x0000555555fb7699 in std::__invoke_impl<void, void (*)(Thread*), Thread*> (__f=@0x5555569ee430: 0x555555fb66dc <Thread::threadProc(Thread*)>) at /usr/include/c++/9/bits/invoke.h:60
No locals.
#7  0x0000555555fb75e5 in std::__invoke<void (*)(Thread*), Thread*> (__fn=@0x5555569ee430: 0x555555fb66dc <Thread::threadProc(Thread*)>) at /usr/include/c++/9/bits/invoke.h:95
No locals.
#8  0x0000555555fb7535 in std::thread::_Invoker<std::tuple<void (*)(Thread*), Thread*> >::_M_invoke<0ul, 1ul> (this=0x5555569ee428) at /usr/include/c++/9/thread:244
No locals.
#9  0x0000555555fb74d7 in std::thread::_Invoker<std::tuple<void (*)(Thread*), Thread*> >::operator() (this=0x5555569ee428) at /usr/include/c++/9/thread:251
No locals.
#10 0x0000555555fb74a8 in std::thread::_State_impl<std::thread::_Invoker<std::tuple<void (*)(Thread*), Thread*> > >::_M_run (this=0x5555569ee420) at /usr/include/c++/9/thread:195
No locals.
#11 0x00007ffff70e6cb4 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
No symbol table info available.
#12 0x00007ffff756b609 in start_thread (arg=<optimized out>) at pthread_create.c:477
        ret = <optimized out>
        pd = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140736733370112, -7662192211799794329, 140737488341198, 140737488341199, 140737488341200, 140736733365120, 7662251583453306215, 7662173736804195687}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = 0
#13 0x00007ffff6dd4103 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
No locals.

Thread 6 (Thread 0x7ffff1046700 (LWP 7408)):
#0  futex_abstimed_wait_cancelable (private=0, abstime=0x0, clockid=0, expected=0, futex_word=0x5555565f0db0) at ../sysdeps/nptl/futex-internal.h:320
        __ret = -512
        op = 393
        __ret = <optimized out>
        oldtype = 0
        err = <optimized out>
        oldtype = <optimized out>
        err = <optimized out>
        __ret = <optimized out>
        clockbit = <optimized out>
        op = <optimized out>
        __ret = <optimized out>
        resultvar = <optimized out>
        __arg6 = <optimized out>
        __arg5 = <optimized out>
        __arg4 = <optimized out>
        __arg3 = <optimized out>
        __arg2 = <optimized out>
        __arg1 = <optimized out>
        _a6 = <optimized out>
        _a5 = <optimized out>
        _a4 = <optimized out>
        _a3 = <optimized out>
        _a2 = <optimized out>
        _a1 = <optimized out>
#1  do_futex_wait (sem=sem@entry=0x5555565f0db0, abstime=0x0, clockid=0) at sem_waitcommon.c:112
        err = <optimized out>
#2  0x00007ffff75754e8 in __new_sem_wait_slow (sem=0x5555565f0db0, abstime=0x0, clockid=0) at sem_waitcommon.c:184
        _buffer = {__routine = 0x7ffff75753a0 <__sem_wait_cleanup>, __arg = 0x5555565f0db0, __canceltype = 0, __prev = 0x0}
        err = <optimized out>
        d = 0
#3  0x00007ffff7811fe9 in ?? () from /usr/lib/x86_64-linux-gnu/libopenal.so.1
No symbol table info available.
#4  0x00007ffff77d72dd in ?? () from /usr/lib/x86_64-linux-gnu/libopenal.so.1
No symbol table info available.
#5  0x00007ffff7811b57 in ?? () from /usr/lib/x86_64-linux-gnu/libopenal.so.1
No symbol table info available.
#6  0x00007ffff756b609 in start_thread (arg=<optimized out>) at pthread_create.c:477
        ret = <optimized out>
        pd = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140737236985600, -7662192211799794329, 140737488344398, 140737488344399, 140737488344544, 140737236980608, 7662187361344200039, 7662173736804195687}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = 0
#7  0x00007ffff6dd4103 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
No locals.

Thread 5 (Thread 0x7ffff1a6e700 (LWP 7407)):
#0  futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x7fffec00bd38) at ../sysdeps/nptl/futex-internal.h:183
        __ret = -512
        oldtype = 0
        err = <optimized out>
        oldtype = <optimized out>
        err = <optimized out>
        __ret = <optimized out>
        resultvar = <optimized out>
        __arg4 = <optimized out>
        __arg3 = <optimized out>
        __arg2 = <optimized out>
        __arg1 = <optimized out>
        _a4 = <optimized out>
        _a3 = <optimized out>
        _a2 = <optimized out>
        _a1 = <optimized out>
#1  __pthread_cond_wait_common (abstime=0x0, clockid=0, mutex=0x5555566837e0, cond=0x7fffec00bd10) at pthread_cond_wait.c:508
        spin = 0
        buffer = {__routine = 0x7ffff7572050 <__condvar_cleanup_waiting>, __arg = 0x7ffff1a6d1e0, __canceltype = 8192, __prev = 0x0}
        cbuffer = {wseq = 536, cond = 0x7fffec00bd10, mutex = 0x5555566837e0, private = 0}
        err = <optimized out>
        g = 0
        flags = <optimized out>
        g1_start = <optimized out>
        signals = <optimized out>
        result = 0
        wseq = 536
        seq = 268
        private = <optimized out>
        maxspin = <optimized out>
        err = <optimized out>
        result = <optimized out>
        wseq = <optimized out>
        g = <optimized out>
        seq = <optimized out>
        flags = <optimized out>
        private = <optimized out>
        signals = <optimized out>
        g1_start = <optimized out>
        spin = <optimized out>
        buffer = <optimized out>
        cbuffer = <optimized out>
        s = <optimized out>
#2  __pthread_cond_wait (cond=0x7fffec00bd10, mutex=0x5555566837e0) at pthread_cond_wait.c:638
No locals.
#3  0x00007ffff294387c in pa_threaded_mainloop_wait () from /usr/lib/x86_64-linux-gnu/libpulse.so.0
No symbol table info available.
#4  0x00007ffff780b496 in ?? () from /usr/lib/x86_64-linux-gnu/libopenal.so.1
No symbol table info available.
#5  0x00007ffff7811b57 in ?? () from /usr/lib/x86_64-linux-gnu/libopenal.so.1
No symbol table info available.
#6  0x00007ffff756b609 in start_thread (arg=<optimized out>) at pthread_create.c:477
        ret = <optimized out>
        pd = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140737247635200, -7662192211799794329, 140737488344206, 140737488344207, 140737488344352, 140737247630208, 7662188164503084391, 7662173736804195687}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = 0
#7  0x00007ffff6dd4103 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
No locals.

Thread 4 (Thread 0x7ffff226f700 (LWP 7406)):
#0  0x00007ffff6dc796f in __GI___poll (fds=0x7fffec009c50, nfds=3, timeout=44) at ../sysdeps/unix/sysv/linux/poll.c:29
        resultvar = 18446744073709551100
        sc_cancel_oldtype = 0
        sc_ret = <optimized out>
#1  0x00007ffff29431d6 in ?? () from /usr/lib/x86_64-linux-gnu/libpulse.so.0
No symbol table info available.
#2  0x00007ffff2934841 in pa_mainloop_poll () from /usr/lib/x86_64-linux-gnu/libpulse.so.0
No symbol table info available.
#3  0x00007ffff2934ec3 in pa_mainloop_iterate () from /usr/lib/x86_64-linux-gnu/libpulse.so.0
No symbol table info available.
#4  0x00007ffff2934f70 in pa_mainloop_run () from /usr/lib/x86_64-linux-gnu/libpulse.so.0
No symbol table info available.
#5  0x00007ffff294311d in ?? () from /usr/lib/x86_64-linux-gnu/libpulse.so.0
No symbol table info available.
#6  0x00007ffff28e157c in ?? () from /usr/lib/x86_64-linux-gnu/pulseaudio/libpulsecommon-13.99.so
No symbol table info available.
#7  0x00007ffff756b609 in start_thread (arg=<optimized out>) at pthread_create.c:477
        ret = <optimized out>
        pd = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140737256027904, -7662192211799794329, 140737488344334, 140737488344335, 140737488344336, 140737256022912, 7662180468458560871, 7662173736804195687}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = 0
#8  0x00007ffff6dd4103 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
No locals.

Thread 1 (Thread 0x7ffff2a33380 (LWP 7400)):
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
        set = {__val = {4096, 93824999284784, 93827783032832, 93825050192208, 93825050192309, 93825050192208, 93825050192208, 93825050192449, 93825050192508, 93825050192208, 93825050192508, 0, 0, 0, 0, 0}}
        pid = <optimized out>
        tid = <optimized out>
        ret = <optimized out>
#1  0x00007ffff6cd7859 in __GI_abort () at abort.c:79
        save_stage = 1
        act = {__sigaction_handler = {sa_handler = 0x555558c9a950, sa_sigaction = 0x555558c9a950}, sa_mask = {__val = {241, 4, 8589934595, 0, 0, 140737335694341, 0, 21474836480, 140737488341104, 93825006024600, 140737335726096, 0, 16918569686419389184, 140737335694341, 140737353805824, 140737335711112}}, sa_flags = 1446035856, sa_restorer = 0x2e6}
        sigs = {__val = {32, 0 <repeats 15 times>}}
#2  0x00007ffff6cd7729 in __assert_fail_base (fmt=0x7ffff6e6d588 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=0x55555630c1ba "liquid_type == LIQUID_SOURCE", file=0x55555630c190 "/home/juozas/minetest_dev/src/nodedef.cpp", line=742, function=<optimized out>) at assert.c:92
        str = 0x555558c9a950 "0\377\304XUU"
        total = 4096
#3  0x00007ffff6ce8f36 in __GI___assert_fail (assertion=0x55555630c1ba "liquid_type == LIQUID_SOURCE", file=0x55555630c190 "/home/juozas/minetest_dev/src/nodedef.cpp", line=742, function=0x55555630c108 "void ContentFeatures::updateTextures(ITextureSource*, IShaderSource*, irr::scene::IMeshManipulator*, Client*, const TextureSettings&)") at assert.c:101
No locals.
#4  0x000055555612acd2 in ContentFeatures::updateTextures (this=0x555558afddc0, tsrc=0x5555565f0f00, shdsrc=0x555556a99860, meshmanip=0x5555569902e0, client=0x555556c95f20, tsettings=...) at /home/juozas/minetest_dev/src/nodedef.cpp:742
        tdef = {{name = "testnodes_liquidsource.png", backface_culling = false, tileable_horizontal = true, tileable_vertical = true, has_color = false, color = {color = 4294967295}, align_style = ALIGN_STYLE_NODE, scale = 0 '\000', animation = {type = TAT_NONE, {vertical_frames = {aspect_w = -20432, aspect_h = 32767, length = 2.80403986e+13}, sheet_2d = {frames_w = -20432, frames_h = 32767, frame_length = 2.80403986e+13}}}}, {name = "testnodes_liquidsource.png", backface_culling = false, tileable_horizontal = true, tileable_vertical = true, has_color = false, color = {color = 4294967295}, align_style = ALIGN_STYLE_NODE, scale = 0 '\000', animation = {type = TAT_NONE, {vertical_frames = {aspect_w = -20432, aspect_h = 32767, length = 2.80403986e+13}, sheet_2d = {frames_w = -20432, frames_h = 32767, frame_length = 2.80403986e+13}}}}, {name = "testnodes_liquidsource.png", backface_culling = false, tileable_horizontal = true, tileable_vertical = true, has_color = false, color = {color = 4294967295}, align_style = ALIGN_STYLE_NODE, scale = 0 '\000', animation = {type = TAT_NONE, {vertical_frames = {aspect_w = -20432, aspect_h = 32767, length = 2.80403986e+13}, sheet_2d = {frames_w = -20432, frames_h = 32767, frame_length = 2.80403986e+13}}}}, {name = "testnodes_liquidsource.png", backface_culling = false, tileable_horizontal = true, tileable_vertical = true, has_color = false, color = {color = 4294967295}, align_style = ALIGN_STYLE_NODE, scale = 0 '\000', animation = {type = TAT_NONE, {vertical_frames = {aspect_w = -20432, aspect_h = 32767, length = 2.80403986e+13}, sheet_2d = {frames_w = -20432, frames_h = 32767, frame_length = 2.80403986e+13}}}}, {name = "testnodes_liquidsource.png", backface_culling = false, tileable_horizontal = true, tileable_vertical = true, has_color = false, color = {color = 4294967295}, align_style = ALIGN_STYLE_NODE, scale = 0 '\000', animation = {type = TAT_NONE, {vertical_frames = {aspect_w = -20432, aspect_h = 32767, length = 2.80403986e+13}, sheet_2d = {frames_w = -20432, frames_h = 32767, frame_length = 2.80403986e+13}}}}, {name = "testnodes_liquidsource.png", backface_culling = false, tileable_horizontal = true, tileable_vertical = true, has_color = false, color = {color = 4294967295}, align_style = ALIGN_STYLE_NODE, scale = 0 '\000', animation = {type = TAT_NONE, {vertical_frames = {aspect_w = -20432, aspect_h = 32767, length = 2.80403986e+13}, sheet_2d = {frames_w = -20432, frames_h = 32767, frame_length = 2.80403986e+13}}}}}
        tdef_overlay = {{name = "", backface_culling = true, tileable_horizontal = true, tileable_vertical = true, has_color = false, color = {color = 4294967295}, align_style = ALIGN_STYLE_NODE, scale = 0 '\000', animation = {type = TAT_NONE, {vertical_frames = {aspect_w = 395008, aspect_h = 117440512, length = 8.40779079e-45}, sheet_2d = {frames_w = 395008, frames_h = 117440512, frame_length = 8.40779079e-45}}}}, {name = "", backface_culling = true, tileable_horizontal = true, tileable_vertical = true, has_color = false, color = {color = 4294967295}, align_style = ALIGN_STYLE_NODE, scale = 0 '\000', animation = {type = TAT_NONE, {vertical_frames = {aspect_w = 16777216, aspect_h = 100663304, length = -2.01562524}, sheet_2d = {frames_w = 16777216, frames_h = 100663304, frame_length = -2.01562524}}}}, {name = "", backface_culling = true, tileable_horizontal = true, tileable_vertical = true, has_color = false, color = {color = 4294967295}, align_style = ALIGN_STYLE_NODE, scale = 0 '\000', animation = {type = TAT_NONE, {vertical_frames = {aspect_w = 1056964608, aspect_h = 1056964736, length = 1.79366203e-43}, sheet_2d = {frames_w = 1056964608, frames_h = 1056964736, frame_length = 1.79366203e-43}}}}, {name = "", backface_culling = true, tileable_horizontal = true, tileable_vertical = true, has_color = false, color = {color = 4294967295}, align_style = ALIGN_STYLE_NODE, scale = 0 '\000', animation = {type = TAT_NONE, {vertical_frames = {aspect_w = 1818850315, aspect_h = 1949983845, length = 1.69284647e+22}, sheet_2d = {frames_w = 1818850315, frames_h = 1949983845, frame_length = 1.69284647e+22}}}}, {name = "", backface_culling = true, tileable_horizontal = true, tileable_vertical = true, has_color = false, color = {color = 4294967295}, align_style = ALIGN_STYLE_NODE, scale = 0 '\000', animation = {type = TAT_NONE, {vertical_frames = {aspect_w = 1769234276, aspect_h = 778331500, length = 9.49867361e-39}, sheet_2d = {frames_w = 1769234276, frames_h = 778331500, frame_length = 9.49867361e-39}}}}, {name = "", backface_culling = true, tileable_horizontal = true, tileable_vertical = true, has_color = false, color = {color = 4294967295}, align_style = ALIGN_STYLE_NODE, scale = 0 '\000', animation = {type = TAT_NONE, {vertical_frames = {aspect_w = 1818850319, aspect_h = 1952408677, length = 1.69284647e+22}, sheet_2d = {frames_w = 1818850319, frames_h = 1952408677, frame_length = 1.69284647e+22}}}}}
        tdef_spec = {{name = "testnodes_liquidsource.png", backface_culling = false, tileable_horizontal = true, tileable_vertical = true, has_color = false, color = {color = 4294967295}, align_style = ALIGN_STYLE_NODE, scale = 0 '\000', animation = {type = TAT_NONE, {vertical_frames = {aspect_w = -20432, aspect_h = 32767, length = 2.80403986e+13}, sheet_2d = {frames_w = -20432, frames_h = 32767, frame_length = 2.80403986e+13}}}}, {name = "testnodes_liquidsource.png", backface_culling = true, tileable_horizontal = true, tileable_vertical = true, has_color = false, color = {color = 4294967295}, align_style = ALIGN_STYLE_NODE, scale = 0 '\000', animation = {type = TAT_NONE, {vertical_frames = {aspect_w = -20432, aspect_h = 32767, length = 2.80403986e+13}, sheet_2d = {frames_w = -20432, frames_h = 32767, frame_length = 2.80403986e+13}}}}, {name = "", backface_culling = true, tileable_horizontal = true, tileable_vertical = true, has_color = false, color = {color = 4294967295}, align_style = ALIGN_STYLE_NODE, scale = 0 '\000', animation = {type = TAT_NONE, {vertical_frames = {aspect_w = -20432, aspect_h = 32767, length = 2.80403986e+13}, sheet_2d = {frames_w = -20432, frames_h = 32767, frame_length = 2.80403986e+13}}}}, {name = "", backface_culling = true, tileable_horizontal = true, tileable_vertical = true, has_color = false, color = {color = 4294967295}, align_style = ALIGN_STYLE_NODE, scale = 0 '\000', animation = {type = TAT_NONE, {vertical_frames = {aspect_w = -20432, aspect_h = 32767, length = 2.80403986e+13}, sheet_2d = {frames_w = -20432, frames_h = 32767, frame_length = 2.80403986e+13}}}}, {name = "", backface_culling = true, tileable_horizontal = true, tileable_vertical = true, has_color = false, color = {color = 4294967295}, align_style = ALIGN_STYLE_NODE, scale = 0 '\000', animation = {type = TAT_NONE, {vertical_frames = {aspect_w = -20432, aspect_h = 32767, length = 2.80403986e+13}, sheet_2d = {frames_w = -20432, frames_h = 32767, frame_length = 2.80403986e+13}}}}, {name = "", backface_culling = true, tileable_horizontal = true, tileable_vertical = true, has_color = false, color = {color = 4294967295}, align_style = ALIGN_STYLE_NODE, scale = 0 '\000', animation = {type = TAT_NONE, {vertical_frames = {aspect_w = -20432, aspect_h = 32767, length = 2.80403986e+13}, sheet_2d = {frames_w = -20432, frames_h = 32767, frame_length = 2.80403986e+13}}}}}
        is_liquid = false
        material_type = 1 '\001'
        __PRETTY_FUNCTION__ = "void ContentFeatures::updateTextures(ITextureSource*, IShaderSource*, irr::scene::IMeshManipulator*, Client*, const TextureSettings&)"
        tile_shader = 13
        overlay_material = 0 '\000'
        overlay_shader = 13
        special_material = 0 '\000'
        special_shader = 13
#5  0x000055555612dd25 in NodeDefManager::updateTextures (this=0x555556a92190, gamedef=0x555556c95f30, progress_callback=0x555555c2f337 <texture_update_progress(void*, unsigned int, unsigned int)>, progress_callback_args=0x7fffffffd050) at /home/juozas/minetest_dev/src/nodedef.cpp:1367
        f = 0x555558afddc0
        i = 22
        client = 0x555556c95f20
        tsrc = 0x5555565f0f00
        shdsrc = 0x555556a99860
        meshmanip = 0x5555569902e0
        tsettings = {leaves_style = LEAVES_FANCY, world_aligned_mode = WORLDALIGN_ENABLE, autoscale_mode = AUTOSCALE_DISABLE, node_texture_size = 64, opaque_water = false, connected_glass = false, use_normal_texture = false, enable_mesh_cache = false, enable_minimap = true}
        size = 240
#6  0x0000555555c2fc0d in Client::afterContentReceived (this=0x555556c95f20) at /home/juozas/minetest_dev/src/client/client.cpp:1772
        __PRETTY_FUNCTION__ = "void Client::afterContentReceived()"
        text = 0x55555856b7e0 L"Initializing nodes"
        tu_args = {guienv = 0x5555566c9540, last_time_ms = 16185176, last_percent = 9, text_base = 0x55555856b7e0 L"Initializing nodes", tsrc = 0x5555565f0f00}
#7  0x0000555555cac41f in Game::createClient (this=0x7fffffffd3e0, playername="singleplayer", password="", address=0x7fffffffd620, port=58134) at /home/juozas/minetest_dev/src/client/game.cpp:1356
        could_connect = true
        connect_aborted = false
        scsf = 0x5555585b65b0
        t = 0x0
        str = Python Exception <class 'OverflowError'> int too big to convert: 

        player = 0x0
#8  0x0000555555caa71f in Game::startup (this=0x7fffffffd3e0, kill=0x5555565b9c60 <porting::g_killed>, random_input=false, input=0x5555569b81e0, map_dir="/home/juozas/minetest_dev/bin/../worlds/Test3", playername="singleplayer", password="", address=0x7fffffffd620, port=58134, error_message="", reconnect=0x7fffffffd77c, chat_backend=0x7fffffffd920, gamespec=..., simple_singleplayer_mode=true) at /home/juozas/minetest_dev/src/client/game.cpp:1065
No locals.
#9  0x0000555555cbf07f in the_game (kill=0x5555565b9c60 <porting::g_killed>, random_input=false, input=0x5555569b81e0, map_dir="/home/juozas/minetest_dev/bin/../worlds/Test3", playername="singleplayer", password="", address="", port=58134, error_message="", chat_backend=..., reconnect_requested=0x7fffffffd77c, gamespec=..., simple_singleplayer_mode=true) at /home/juozas/minetest_dev/src/client/game.cpp:4282
        game = {static clientEventHandler = {{handler = (void (Game::*)(Game * const, ClientEvent *, CameraOrientation *)) 0x555555cb3120 <Game::handleClientEvent_None(ClientEvent*, CameraOrientation*)>}, {handler = (void (Game::*)(Game * const, ClientEvent *, CameraOrientation *)) 0x555555cb3158 <Game::handleClientEvent_PlayerDamage(ClientEvent*, CameraOrientation*)>}, {handler = (void (Game::*)(Game * const, ClientEvent *, CameraOrientation *)) 0x555555cb3354 <Game::handleClientEvent_PlayerForceMove(ClientEvent*, CameraOrientation*)>}, {handler = (void (Game::*)(Game * const, ClientEvent *, CameraOrientation *)) 0x555555cb338e <Game::handleClientEvent_Deathscreen(ClientEvent*, CameraOrientation*)>}, {handler = (void (Game::*)(Game * const, ClientEvent *, CameraOrientation *)) 0x555555cb3434 <Game::handleClientEvent_ShowFormSpec(ClientEvent*, CameraOrientation*)>}, {handler = (void (Game::*)(Game * const, ClientEvent *, CameraOrientation *)) 0x555555cb3636 <Game::handleClientEvent_ShowLocalFormSpec(ClientEvent*, CameraOrientation*)>}, {handler = (void (Game::*)(Game * const, ClientEvent *, CameraOrientation *)) 0x555555cb377e <Game::handleClientEvent_HandleParticleEvent(ClientEvent*, CameraOrientation*)>}, {handler = (void (Game::*)(Game * const, ClientEvent *, CameraOrientation *)) 0x555555cb377e <Game::handleClientEvent_HandleParticleEvent(ClientEvent*, CameraOrientation*)>}, {handler = (void (Game::*)(Game * const, ClientEvent *, CameraOrientation *)) 0x555555cb377e <Game::handleClientEvent_HandleParticleEvent(ClientEvent*, CameraOrientation*)>}, {handler = (void (Game::*)(Game * const, ClientEvent *, CameraOrientation *)) 0x555555cb37f0 <Game::handleClientEvent_HudAdd(ClientEvent*, CameraOrientation*)>}, {handler = (void (Game::*)(Game * const, ClientEvent *, CameraOrientation *)) 0x555555cb3bf2 <Game::handleClientEvent_HudRemove(ClientEvent*, CameraOrientation*)>}, {handler = (void (Game::*)(Game * const, ClientEvent *, CameraOrientation *)) 0x555555cb3c62 <Game::handleClientEvent_HudChange(ClientEvent*, CameraOrientation*)>}, {handler = (void (Game::*)(Game * const, ClientEvent *, CameraOrientation *)) 0x555555cb3f20 <Game::handleClientEvent_SetSky(ClientEvent*, CameraOrientation*)>}, {handler = (void (Game::*)(Game * const, ClientEvent *, CameraOrientation *)) 0x555555cb4520 <Game::handleClientEvent_SetSun(ClientEvent*, CameraOrientation*)>}, {handler = (void (Game::*)(Game * const, ClientEvent *, CameraOrientation *)) 0x555555cb4704 <Game::handleClientEvent_SetMoon(ClientEvent*, CameraOrientation*)>}, {handler = (void (Game::*)(Game * const, ClientEvent *, CameraOrientation *)) 0x555555cb485a <Game::handleClientEvent_SetStars(ClientEvent*, CameraOrientation*)>}, {handler = (void (Game::*)(Game * const, ClientEvent *, CameraOrientation *)) 0x555555cb4918 <Game::handleClientEvent_OverrideDayNigthRatio(ClientEvent*, CameraOrientation*)>}, {handler = (void (Game::*)(Game * const, ClientEvent *, CameraOrientation *)) 0x555555cb4978 <Game::handleClientEvent_CloudParams(ClientEvent*, CameraOrientation*)>}}, input = 0x5555569b81e0, client = 0x555556c95f20, server = 0x555556ab2ee0, texture_src = 0x5555565f0f00, shader_src = 0x555556a99860, itemdef_manager = 0x555556a8d5e0, nodedef_manager = 0x555556a92190, soundfetcher = {<OnDemandSoundFetcher> = {_vptr.OnDemandSoundFetcher = 0x5555564f06a8 <vtable for GameOnDemandSoundFetcher+16>}, m_fetched = std::set with 0 elements}, sound = 0x555556a8e6a0, sound_is_dummy = false, soundmaker = 0x5555569f0520, chat_backend = 0x7fffffffd920, m_chat_log_buf = {<ICombinedLogOutput> = {<ILogOutput> = {_vptr.ILogOutput = 0x55555656aad0 <vtable for LogOutputBuffer+16>}, <No data fields>}, m_buffer = std::queue wrapping: std::deque with 0 elements, m_logger = @0x5555565979e0}, eventmgr = 0x5555569f0040, quicktune = 0x5555569f0480, registration_confirmation_shown = false, m_game_ui = std::unique_ptr<GameUI> = {get() = 0x5555569f4160}, gui_chat_console = 0x0, draw_control = 0x555556cd7590, camera = 0x0, clouds = 0x0, sky = 0x0, hud = 0x0, mapper = 0x0, runData = {dig_index = 0, new_playeritem = 0, pointed_old = {type = POINTEDTHING_NOTHING, node_undersurface = {X = 0, Y = 0, Z = 0}, node_abovesurface = {X = 0, Y = 0, Z = 0}, node_real_undersurface = {X = 0, Y = 0, Z = 0}, object_id = -1, intersection_point = {X = 0, Y = 0, Z = 0}, intersection_normal = {X = 0, Y = 0, Z = 0}, box_id = 0, distanceSq = 0}, digging = false, ldown_for_dig = false, dig_instantly = false, digging_blocked = false, left_punch = false, reset_jump_timer = false, nodig_delay_timer = 0, dig_time = 0, dig_time_complete = 0, repeat_rightclick_timer = 0, object_hit_delay_timer = 0, time_from_last_punch = 10, selected_object = 0x0, jump_timer = 0, damage_flash = 0, update_draw_list_timer = 0, fog_range = 0, update_draw_list_last_cam_dir = {X = 0, Y = 0, Z = 0}, time_of_day_smooth = 0}, m_flags = {force_fog_off = false, disable_camera_update = false}, device = 0x5555565f1310, driver = 0x5555569911a0, smgr = 0x5555569c2140, kill = 0x5555565b9c60 <porting::g_killed>, error_message = 0x7fffffffd7c0, reconnect_requested = 0x7fffffffd77c, skybox = 0x555556657b4d, random_input = false, simple_singleplayer_mode = true, crack_animation_length = 21845, profiler_interval = {m_accumulator = 0}, m_cache_doubletap_jump = false, m_cache_enable_clouds = true, m_cache_enable_joysticks = false, m_cache_enable_particles = true, m_cache_enable_fog = true, m_cache_enable_noclip = false, m_cache_enable_free_move = false, m_cache_mouse_sensitivity = 0.200000003, m_cache_joystick_frustum_sensitivity = 170, m_repeat_right_click_time = 0.25, m_cache_cam_smoothing = 1, m_cache_fog_start = 0.400000006, m_invert_mouse = false, m_first_loop_after_window_activation = true, m_camera_offset_changed = false, m_does_lost_focus_pause_game = false}
        server_address = ""
#10 0x0000555555c58271 in ClientLauncher::run (this=0x7fffffffdd20, game_params=..., cmd_args=...) at /home/juozas/minetest_dev/src/client/clientlauncher.cpp:259
        game_has_run = true
        text = 0x555556a8e1e0 L"\x74736554\x646c0033\x72617020\x74656d61\x205d7265\x77656e5b]nu"
        __PRETTY_FUNCTION__ = "bool ClientLauncher::run(GameParams&, const Settings&)"
        camera = 0x5555569edb50
        chat_backend = {m_console_buffer = {m_scrollback = 500, m_unformatted = std::vector of length 0, capacity 0, m_cols = 0, m_rows = 0, m_scroll = 0, m_formatted = std::vector of length 0, capacity 0, m_empty_formatted_line = {fragments = std::vector of length 0, capacity 0, first = true}}, m_recent_buffer = {m_scrollback = 6, m_unformatted = std::vector of length 0, capacity 0, m_cols = 0, m_rows = 0, m_scroll = 0, m_formatted = std::vector of length 0, capacity 0, m_empty_formatted_line = {fragments = std::vector of length 0, capacity 0, first = true}}, m_prompt = {m_prompt = L"]", m_line = L"", m_history = std::vector of length 0, capacity 0, m_history_index = 0, m_history_limit = 500, m_cols = 0, m_view = 0, m_cursor = 0, m_cursor_len = 0, m_nick_completion_start = 0, m_nick_completion_end = 0}}
        error_message = ""
        reconnect_requested = false
        first_loop = false
        retval = true
        kill = 0x5555565b9c60 <porting::g_killed>
#11 0x00005555560f63ab in main (argc=1, argv=0x7fffffffe0a8) at /home/juozas/minetest_dev/src/main.cpp:221
        retval = 32767
        cmd_args = {m_settings = std::unordered_map with 0 elements, m_defaults = std::unordered_map with 0 elements, m_flags = std::unordered_map with 0 elements, m_callbacks = std::unordered_map with 0 elements, m_callback_mutex = {<std::__mutex_base> = {_M_mutex = pthread_mutex_t = {Type = Normal, Status = Not acquired, Robust = No, Shared = No, Protocol = None}}, <No data fields>}, m_mutex = {<std::__mutex_base> = {_M_mutex = pthread_mutex_t = {Type = Normal, Status = Not acquired, Robust = No, Shared = No, Protocol = None}}, <No data fields>}}
        cmd_args_ok = true
        game_params = {socket_port = 30000, world_path = "/home/juozas/minetest_dev/bin/../worlds/world", game_spec = {id = "minetest", name = "Minetest Game", author = "Minetest", release = 0, path = "/home/juozas/minetest_dev/bin/../games/minetest_game", gamemods_path = "/home/juozas/minetest_dev/bin/../games/minetest_game/mods", addon_mods_paths = std::set with 1 element = {[0] = "/home/juozas/minetest_dev/bin/../mods"}, menuicon_path = "/home/juozas/minetest_dev/bin/../games/minetest_game/menu/icon.png"}, is_dedicated_server = false}
        isServer = false
        __PRETTY_FUNCTION__ = "int main(int, char**)"
        launcher = {list_video_modes = false, skip_main_menu = false, use_freetype = true, random_input = false, address = "", playername = "", password = "", input = 0x5555569b81e0, receiver = 0x7fffec00bbf0, skin = 0x5555569c3820, font = 0x0, gamespec = {id = "devtest", name = "Development Test", author = "", release = 0, path = "/home/juozas/minetest_dev/bin/../games/devtest", gamemods_path = "/home/juozas/minetest_dev/bin/../games/devtest/mods", addon_mods_paths = std::set with 1 element = {[0] = "/home/juozas/minetest_dev/bin/../mods"}, menuicon_path = "/home/juozas/minetest_dev/bin/../games/devtest/menu/icon.png"}, worldspec = {path = "/home/juozas/minetest_dev/bin/../worlds/Test3", name = "Test3", gameid = "devtest"}, simple_singleplayer_mode = true, current_playername = "singleplayer", current_password = "", current_address = "", current_port = 58134}
(gdb) q
A debugging session is active.

	Inferior 1 [process 7400] will be killed.

Quit anyway? (y or n) y
```

</details>

##### Steps to reproduce

1. Build latest minetest from master
2. Create a devtest world, start game
3. Experience a crash while loading

### PR DESCRIPTION
**Pull request by Wuzzy2**
Fixes #9938.

Missing `liquid*` properties are added to all nodes with `drawtype == "liquid"` or `drawtype == "liquidflowing"`.

### CODE REVIEW

File: games/devtest/mods/testnodes/drawtypes.lua [hunk 1]
```diff
@@ -387,6 +392,9 @@ minetest.register_node("testnodes:liquid_waving", {
 
 
 	walkable = false,
+	liquidtype = "source",
+	liquid_range = 1,
+	liquid_viscosity = 0,
 	liquid_alternative_flowing = "testnodes:liquid_flowing",
 	liquid_alternative_source = "testnodes:liquid",
```
Comment (paramat) [inline games/devtest/mods/testnodes/drawtypes.lua:399]: These 2 lines above should be the 'waving' liquids?

File: games/devtest/mods/testnodes/drawtypes.lua [hunk 2]
```diff
@@ -408,6 +416,9 @@ minetest.register_node("testnodes:liquid_flowing_waving", {
 
 
 	walkable = false,
+	liquidtype = "flowing",
+	liquid_range = 1,
+	liquid_viscosity = 0,
 	liquid_alternative_flowing = "testnodes:liquid_flowing",
 	liquid_alternative_source = "testnodes:liquid",
```
Comment (paramat) [inline games/devtest/mods/testnodes/drawtypes.lua:423]: These 2 lines above should be the 'waving' liquids?

**Comment by Wuzzy2** [comment]
Nice, catch, paramat! Oopsie!

**Comment by paramat** [comment]
Did not test but trivial change and i trust your testing :+1:
