### PR TITLE
[manual merge] Use standard shading for inventory rendering

### LINKED ISSUE #17110: Rendering regression of shading for inventory nodes
### Luanti version

```true
Luanti 5.11.0 and above
```

### Operating system and version

Linux (also testing with Windows builds for the older versions)

### CPU model

_No response_

### GPU model

_No response_

### Active renderer

_No response_

### Summary

In Luanti 5.11.0 there seems to have been something that caused a regression in how nodes are rendered in the inventory, specifically the lighting of each side of the isometric render. Previously each side was differently shaded with the light coming from the left (or so), while now both the side textures are shaded the same which looks really dull. I don't think this was an intentional change.

Image
(Left: 5.10, Right: 5.11)

This broken rendering still exists in the latest version, regardless of using `opengl` or `opengl3`.

Image

(Left: 5.10 using `opengl`, Right: 5.15 using `opengl3`)

### Steps to reproduce

Compare the rendering of nodes in the inventory between 5.10.0 and 5.11.0.

If anyone else is able to bisect the exact commit where it happened quicker than I will be able to get to it, that would be appreciated.

### PR DESCRIPTION
**Pull request by appgurueu**
Ready for review, fixes #17110. Implements the "perhaps cleaner" approach from https://github.com/luanti-org/luanti/issues/17110#issuecomment-4272020351.

## How to test

1. Apply eyeballs liberally

Screenshot From 2026-04-18 13-41-30

### CODE REVIEW

File: src/gui/drawItemStack.cpp [hunk 1]
```diff
@@ -134,11 +134,14 @@ void drawItemStack(
 
 			// TODO: could be moved to a shader
 			if (p.needColorize(c)) {
-				buf->setDirty(scene::EBT_VERTEX);
-				if (imesh->needs_shading)
-					colorizeMeshBuffer(buf, &c);
-				else
+				if (imesh->needs_shading) {
+					f32 ambient_light = 0.25f;
```
Comment (appgurueu) [inline src/gui/drawItemStack.cpp:138]: these values are up for discussion, be my guest if you want to tweak them

File: src/client/mesh.cpp [hunk 2]
```diff
@@ -13,14 +13,14 @@
...
-inline static void applyShadeFactor(video::SColor& color, float factor)
+inline static void applyShadeFactor(video::SColor &color, f32 factor)
 {
 	color.setRed(core::clamp(core::round32(color.getRed()*factor), 0, 255));
 	color.setGreen(core::clamp(core::round32(color.getGreen()*factor), 0, 255));
 	color.setBlue(core::clamp(core::round32(color.getBlue()*factor), 0, 255));
 }
 
-void applyFacesShading(video::SColor &color, const v3f normal)
+void applyFacesShading(video::SColor &color, v3f normal)
```
Comment (cx384) [inline src/client/mesh.cpp]: This is a copy, no need to make it const, right?

File: src/client/mesh.cpp [hunk 3]
```diff
@@ -98,19 +98,18 @@ scene::IAnimatedMesh* createCubeMesh(v3f scale)
...
 	const u32 stride = buf->getVertexBuffer()->getElementSize();
 	u32 vertex_count = buf->getVertexCount();
 	u8 *vertices = (u8 *)buf->getVertices();
 	for (u32 i = 0; i < vertex_count; i++) {
 		auto *vertex = (video::S3DVertex *)(vertices + i * stride);
-		transform_vertex(vertex);
+		fn(vertex);
 	}
 	buf->setDirty(scene::EBT_VERTEX);
-	buf->recalculateBoundingBox();
```
Comment (cx384) [inline src/client/mesh.cpp:113]: Seems fine.
Just to be sure `rotateMesh(scene::IMesh *mesh, float degrees)`
does not need `recalculateBoundingBox()`, right?

Never mind, your PR doesn't change it anyway.

File: src/client/mesh.h [hunk 4]
```diff
@@ -104,7 +103,7 @@ scene::SMesh* cloneStaticMesh(scene::IMesh *src_mesh);
 	expand - factor by which cuboids will be resized
 */
 scene::IMesh* convertNodeboxesToMesh(const std::vector<aabb3f> &boxes,
-		const f32 *uv_coords = NULL, float expand = 0);
+		const f32 *uv_coords = NULL, f32 expand = 0);
```
Comment (cx384) [inline src/client/mesh.h:106]:
```suggestion
		const f32 *uv_coords = nullptr, f32 expand = 0.f);
```

**Review by cx384 — COMMENTED** [review]
Looks good.
The shading is a little bit to strong in my opinion, but maybe it's only because I'm not used to it anymore.
The dark (less lid) side may be a little too dark, I would be more confident with an ambient light of `0.4f` ~or maybe change the light direction such that the top side becomes brighter.~

**Comment by rollerozxa** [comment]
Looks good though I agree with @cx384 that the shading on the right side of the node may be a bit too high, though I wouldn't particularly mind a bit more constrast than how it originally was either. Comparison, this PR (top) vs. 5.9 (bottom):

image

File: src/gui/drawItemStack.cpp (hunk 1 above)
Comment (SmallJoker) [reply src/gui/drawItemStack.cpp:138]: IMO the shading should be more similar to 5.9 (https://github.com/luanti-org/luanti/pull/17114#issuecomment-4276105193). Increased ambient light, decreased directional light.

**Comment by appgurueu** [comment]
Now with 0.5 ambient, 0.7 directional, closer to 5.9 but still with a bit more contrast:

image

**Review by SmallJoker — APPROVED** [review]
Looks good. Works.
