### PR TITLE
Fix multiple death messages (#3565)

### LINKED ISSUE #3565: Death message repeats until respawn
It seems that if the player doesn't respawn immediately after dying in fire or lava _(or any node that has a `damage_per_second` field)_.  The death message is triggered over and over again until they respawn or are out of the condition that caused them to die.  This doesn't appear to happen with drowning.

Repeated death message

You can see the repeated message in the top left corner _(though it is hard to see because of the lava)_.  It also appears that `register_on_dieplayer` is triggered until respawn as well.

**EDIT:** Found the offending commit using git bisect: c552d293fa340a1484d0b918b3341d7d141e7931

### PR DESCRIPTION
**Pull request by presstabstart**
Fixes #3565, problem was to do with the fact that there was nothing in place to know whether or not the player was actually dead, so dying happened every damage update.

### CODE REVIEW

File: src/network/serverpackethandler.cpp [hunk 1]
```diff
@@ -1127,7 +1127,7 @@ void Server::handleCommand_Damage(NetworkPacket* pkt)
 		return;
 	}
 
-	if (g_settings->getBool("enable_damage")) {
+	if (g_settings->getBool("enable_damage") && !playersao->getDeadStatus()) {
```
Comment (SmallJoker) [inline src/network/serverpackethandler.cpp]: Couldn't this be done without the new variable and just adding the check `&& playersao->getHP() > 0` here?

Comment (presstabstart) [inline src/network/serverpackethandler.cpp]: ah you're right, whoops. should be fixed now.

**Comment by sfan5** [comment]
I feel like this could be better solved by restricting calls to `SendPlayerHPOrDie` to only cases where the HP actually changed.

**Comment by presstabstart** [comment]
@sfan5: it is though. See serverpackethandler.cpp:1130. It is also called elsewhere, however, so additional checks are in place inside [code]SendPlayerHPOrDie[/code] itself.

**Comment by sofar** [comment]
warning: 1 line adds whitespace errors.

**Comment by sofar** [comment]
Works great though, so please fix the whitespace error. :+1:

**Comment by presstabstart** [comment]
@sofar: OK, should be removed now. I merged the commit into the previous since it's just a whitespace fix.

File: src/server.cpp [hunk 2]
```diff
@@ -1119,16 +1119,15 @@ PlayerSAO* Server::StageTwoClientInit(u16 peer_id)
 	// Send inventory
 	SendInventory(playersao);
 
-	// Send HP
-	SendPlayerHPOrDie(playersao);
+	// Send HP or death screen
+	if (playersao->isDead())
```
Comment (sfan5) [inline src/server.cpp]: this is quite confusing, whats the difference between `isDead()` and `getDeadStatus()`?

File: src/content_sao.h [hunk 3]
```diff
@@ -244,6 +244,8 @@ class PlayerSAO : public UnitSAO
 	s16 readDamage();
 	u16 getBreath() const { return m_breath; }
 	void setBreath(const u16 breath, bool send = true);
+	void setDeadStatus(const bool dead);
```
Comment (sfan5) [inline src/content_sao.h]: useless `const`

File: src/content_sao.cpp [hunk 4]
```diff
@@ -1090,6 +1091,10 @@ void PlayerSAO::step(float dtime, bool send_recommended)
 	}
 }
 
+void PlayerSAO::setDeadStatus(const bool dead) {
```
Comment (sfan5) [inline src/content_sao.cpp]: useless `const`

Comment (nerzhul) [inline src/content_sao.cpp]: brace on wrong line too

File: src/server.cpp (hunk 2 above)
Comment (presstabstart) [inline src/server.cpp]: They should be functionally the same, but getting rid of getDeadStatus would require storing m_dead in UnitSAO and that means further complications: UnitSAO has the same problem as PlayerSAO in that you can't determine whether or not the unit just died (I think), you just know that the unit is dead. Maybe I should replace `isDead` with `getDeadStatus`? Here it's going to do the same thing, but `getDeadStatus` could potentially get removed later.

**Comment by presstabstart** [comment]
OK, I made the cleanups. Merged again, should I be merging these commits?

File: src/server.cpp (hunk 2 above)
Comment (presstabstart) [inline src/server.cpp]: deaths are handled differently for units and players, so moving m_dead into unitSAO and therefore removing getDeadStatus might complicate things? It still should be done though.

**Comment by presstabstart** [comment]
no idea why the travis ci build is failing. on the one build it does fail the error log says 'There was an error while trying to fetch the log.' All other builds work though?

**Comment by sfan5** [comment]
Travis just seems to be broken right now in general, don't mind it.

**Comment by sorcerykid** [comment]
This PR seems remarkably convoluted. There are so many changes to source files, yet then backtracking of those changes via later commits. I'm not sure what is the rationale for all this complexity.

I suggested a solution in #5257 that conforms to the existing convention found elsewhere in serverpackethandler.cpp of checking playersao->isDead() and outputting debug information for ignored packets. Additional member functions and variables aren't necessary.

**Comment by Fixer-007** [comment]
Some servers have problem due to this bug (mainly spam from death messages mod), will this move forward?

**Comment by sofar** [comment]
The "view all" option shows a fairly simple patch, I don't see why we can't merge this.

:+1:

**Comment by sorcerykid** [comment]
Per my comment above:
a) Why is there a for check playersao->getHP() instead of playersao->isDead() ?
b) Why is there no debug information generated for the ignored packet?

**Comment by Fixer-007** [comment]
Action needed

File: src/network/serverpackethandler.cpp [hunk 5]
```diff
@@ -1128,6 +1128,13 @@ void Server::handleCommand_Damage(NetworkPacket* pkt)
 	}
 
 	if (g_settings->getBool("enable_damage")) {
+		if (playerSAO->isDead()) {
+			verbosestream << "Server::ProcessData(): Info: "
+				"Ignoring damage as player " << player->getName()
+				<< " is already dead." << std::endl;
+			return;
+		}
+
```
Comment (nerzhul) [inline src/network/serverpackethandler.cpp]: note if i finish my pr on damage only serverside this will become obsolete

File: src/server.cpp (hunk 2 above)
Comment (nerzhul) [inline src/server.cpp]: SendPlayerHPorDie already check if player is dead and send the death screen + HP. Here you forget to send player HP
