### PR TITLE
Fix active object adding to not generated block

### LINKED ISSUE #4759: minetest.add_item and minetest.add_entity are unreliable
While trying to debug my [Tutorial subgame](https://forum.minetest.net/viewtopic.php?t=10192), I have had trouble with using `minetest.add_item`. I use this function to spawn the items around the tutorial world.

This function seems to be pretty unreliable. After several test runs I figured out that `minetest.add_item` may or may not actually spawn an item at the specified position. The really sad part is, I always get an `ObjectRef` returned, and apparently I only get `nil` when I plugged in blatantly incorrect information. So this function is useless in determining whether the spawning was successful.
The problem is, currently `minetest.add_item` can not be used to reliably spawn items.

In a simple flat test world, I have used the `luacmd` mod to debug this function a bit more. And I noticed some patterns:
If I spawn an item close to me, it always spawns. If I spawn an item far away from me, but still in a generated chunk, it does seem to spawn. It is not instantly visible but when I move to the coords, the item quickly appears. When I spawn the item very far from me, in a non-generated chunk, and then immediately teleport to this place, the item is NOT there. Which is odd since I still get an `ObjectRef` returned, and not `nil`.

Also, the documentation of this function is rather poor IMO. Corner cases are not explained at all.

I think the function should be fixed to guarantee an item spawn for correct input, or at least return `nil` if spawning failed for some reason.

An improvement of the docs would also be appreciated, in case this behaviour is somehow intentional or there is another way I am supposed to go.

Tested in c05aac3766e88530fcf5d38a8c25c994b792b324

### PR DESCRIPTION
**Pull request by sfence**
- Goal of the PR
Fix #4759.
- How does the PR work?
It disables saving Active objects to a blank map block, so the error is not masked.
- Does it resolve any reported issue?
Fix #4759.

## To do

This PR is a Ready for Review.

## How to test

Try to spawn an entity with the command `/spawnentity` in not generated part of the map and teleport to that part.

### CODE REVIEW

**Comment by Zughy** [comment]
(Unrelated: have you considered proposing as a core dev?)

File: src/serverenvironment.cpp [hunk 1]
```diff
@@ -1926,9 +1921,16 @@ u16 ServerEnvironment::addActiveObjectRaw(std::unique_ptr<ServerActiveObject> ob
 			errorstream<<"ServerEnvironment::addActiveObjectRaw(): "
```
Comment (lhofhansl) [inline src/serverenvironment.cpp:1921]: So we never actually hit this branch before? (Because ServerMap::emergeBlock by default will create a blank block.)

**Comment by lhofhansl** [comment]
I looked through the issue. Is it actually a good idea to allow entities (items, objects) for non-existing blocks?

**Comment by appgurueu** [comment]
Tested.

On master, you simply get an (invalid?) object ref; `/spawnentity testentities:selectionbox 1000,1000,1000` does not complain, but when you `/teleport 1000,1000,1000`, the entity isn't there.

With this PR, you get an "ERROR[Server]: ServerEnvironment::addActiveObjectRaw(): could not emerge block for storing id=5 statically (pos=(1000,1001,1000))" (?), but also an invalid object ref. I'm not sure that's what we want; what's the expected behavior here? Do we want adding the object to fail (loudly), do we want a (somewhat weird) error message for that?

**Comment by sfan5** [comment]
FWIW `saveStaticToBlock` does effectively the same, so the fix would need to be applied there too.

Actual question is however: why doesn't this work right now?
If I spawn an entity far away the engine creates a blank block, saves the static data there (initially), the entity is soon deactivated and the static data should be written there again.
If I visit the block sure the mapgen might run but the entity should be there.
-> more debugging needed, this is maybe not the right fix


> With this PR, you get [an error], but also an invalid object ref.

This should logically not happen. Are you sure you tested right?

**Comment by appgurueu** [comment]
> This should logically not happen. Are you sure you tested right?

Sorry, I should have written a `nil` value. The object ref is in the former case.

**Comment by sfence** [comment]
It looks like active objects created in nongenerated areas are stored well.
But when the block is generated, this line is called: 
https://github.com/minetest/minetest/blob/cb689b5f64c80ea6d173a3e840c0c4fdb0b9c3b1/src/serverenvironment.cpp#L1055

**Comment by sfence** [comment]
This is probably source of the problem:

https://github.com/minetest/minetest/blob/cb689b5f64c80ea6d173a3e840c0c4fdb0b9c3b1/src/mapblock.h#L531-L535

Because a nongenerated block is saved before it is activated and removed from active blocks.

**Comment by sfence** [comment]
So, the timestamp of the block is updated when object status data is saved to the block in `addActiveObjectRaw` now.
Looks like adding objects to the nongenerated area works now.

File: src/serverenvironment.cpp [hunk 2]
```diff
@@ -1926,9 +1922,16 @@ u16 ServerEnvironment::addActiveObjectRaw(std::unique_ptr<ServerActiveObject> ob
...
 				<<"could not emerge block for storing id="<<object->getId()
 				<<" statically (pos="<<p<<")"<<std::endl;
```
Comment (sfan5) [inline src/serverenvironment.cpp:1924]: consider replacing the above with a call to `saveStaticToBlock`. it implements the same.

**Comment by sfan5** [comment]
I see a conceptual problem here: Everytime a block is loaded without running through `ServerEnvironment::activateBlock` the "remove objects if they should be" logic is skipped. If static objects are then modified you risk them getting deleted.

e.g. following case: block is activated and saved once, clearobject called, block is loaded to add new static object, block is loaded for real afterwards -> new object deleted too

However we can't just increase the timestamp to fix it because the delta is also used by other code.
Fixing this is not possible without somehow separating the "clearobjects detection value" from the timestamp.

Anyway as the currently best fix I suggest *not* calling `clearStored` when the timestamp is undefined. (I don't see the logic in that anyway.)

File: src/serverenvironment.cpp (hunk 2 above)
Comment (sfence) [reply src/serverenvironment.cpp:1924]: It does not look so.

`saveStaticToBlock` does not call `block->m_static_objects.setActive`.
Only the error message is similar.

Comment (sfan5) [reply src/serverenvironment.cpp:1923]: Indeed you are right.

File: src/serverenvironment.cpp [hunk 3]
```diff
@@ -1926,9 +1921,16 @@ u16 ServerEnvironment::addActiveObjectRaw(std::unique_ptr<ServerActiveObject> ob
...
```
Comment (sfan5) [inline src/serverenvironment.cpp:1923]: not directly related but it would be a good opportunity to clean the message a bit:
```suggestion
			errorstream << "ServerEnvironment::addActiveObjectRaw(): "
				<< "could not emerge block " << p << " for storing id="
				<< object->getId() << " statically" << std::endl;
```

**Review by sfan5 — DISMISSED** [review]
works

File: src/serverenvironment.cpp [hunk 4]
```diff
@@ -1051,7 +1051,7 @@ void ServerEnvironment::activateBlock(MapBlock *block, u32 additional_dtime)
 			<<stamp<<", game time: "<<m_game_time<<std::endl;*/
 
 	// Remove stored static objects if clearObjects was called since block's timestamp
-	if (stamp == BLOCK_TIMESTAMP_UNDEFINED || stamp < m_last_clear_objects_time) {
+	if (stamp < m_last_clear_objects_time) {
```
Comment (sfan5) [inline src/serverenvironment.cpp:1054]:
```suggestion
	// Note that non-generated blocks may still have stored static objects
	if (stamp != BLOCK_TIMESTAMP_UNDEFINED && stamp < m_last_clear_objects_time) {
```

**Comment by rubenwardy** [comment]
Please can you amend the lua API to define what happens when adding to a not generated/loaded area?

File: src/serverenvironment.cpp [hunk 5]
```diff
@@ -1922,16 +1927,14 @@ u16 ServerEnvironment::addActiveObjectRaw(std::unique_ptr<ServerActiveObject> ob
...
+			m_script->removeObjectReference(object);
 			m_ao_manager.removeObject(object->getId());
 			return 0;
 		}
 	}
 
-	// Register reference in scripting api (must be done before post-init)
-	m_script->addObjectReference(object);
-	// Post-initialize object
-	object->addedToEnvironment(dtime_s);
```
Comment (sfan5) [inline src/serverenvironment.cpp]: why?

Comment (sfence) [reply src/serverenvironment.cpp]: Because
https://github.com/minetest/minetest/blob/ca0a57d8eafc8079e23d8ad053d72fb81c5c6235/src/staticobject.cpp#L24-L29
`StaticObject` constructor calls `get_staticdata` from the lua entity -> https://github.com/minetest/minetest/blob/ca0a57d8eafc8079e23d8ad053d72fb81c5c6235/src/server/luaentity_sao.cpp#L286

So it should be called after `on_activate` and `on_activate` is called from  https://github.com/minetest/minetest/blob/ca0a57d8eafc8079e23d8ad053d72fb81c5c6235/src/server/luaentity_sao.cpp#L99

So moving these calls after https://github.com/minetest/minetest/blob/ca0a57d8eafc8079e23d8ad053d72fb81c5c6235/src/serverenvironment.cpp#L1913 can result in saving uninitialized data and also modder expect in `get_staticdata` call, that `on_activate` has been processed, and some additional fields in `luaentity` has been set. So there is a bigger chance of Lua error in `get_staticdata` call if `get_staticdata` will be called before `on_activate`.

Comment (sfan5) [reply src/serverenvironment.cpp]: `LuaEntitySAO::getStaticData` only interacts with the script api if `m_registered` is true.
`m_registered` is only set to true in `LuaEntitySAO::addedToEnvironment`

**Comment by appgurueu** [comment]
I asked over on the issue what the expected behavior is, and here's Wuzzy's reply: https://github.com/minetest/minetest/issues/4759#issuecomment-1913715085 - it seems not spawning the object is considered expected behavior by Wuzzy, and he makes a good point: We probably don't want active objects in unloaded areas.

We could have a second variant of `add_entity`, which adds objects to unloaded areas (or rather, schedules them to be spawned when the block is generated), but doesn't return an active object ref.

File: src/serverenvironment.cpp (hunk 5 above)
Comment (sfence) [reply src/serverenvironment.cpp]: I missed this. Changed back.

Checked with entity callbacks:callback, `get_staticdata` is still called before saving.

**Comment by sfence** [comment]
@appgurueu Something as is done in the last commit, can be?

To test both modes, change line https://github.com/minetest/minetest/blob/ca0a57d8eafc8079e23d8ad053d72fb81c5c6235/builtin/game/chat.lua#L892
to `local obj = core.add_entity(p, entityname, "", true)`.

File: src/serverenvironment.cpp [hunk 6]
```diff
@@ -1923,12 +1919,20 @@ u16 ServerEnvironment::addActiveObjectRaw(std::unique_ptr<ServerActiveObject> ob
 					MOD_REASON_ADD_ACTIVE_OBJECT_RAW);
 		} else {
 			v3s16 p = floatToInt(objectpos, BS);
-			errorstream<<"ServerEnvironment::addActiveObjectRaw(): "
-				<<"could not emerge block for storing id="<<object->getId()
-				<<" statically (pos="<<p<<")"<<std::endl;
+			errorstream << "ServerEnvironment::addActiveObjectRaw(): "
```
Comment (lhofhansl) [inline src/serverenvironment.cpp:1922]: As I said before, this branch cannot be reached, since ServerMap::emergeBlock defaults to creating a blank block and will never return null unless false is passed in its second argument.

Comment (sfence) [reply src/serverenvironment.cpp:1922]: Moving the `emergeBlock` call into `l_add_entity` should satisfy it.

Comment (sfan5) [reply src/serverenvironment.cpp:1922]: There's one reason it could return null but that's currently not handled correctly.
`ServerMap::createSector` throws an exception if the position is out of bounds but it's not caught.

**Comment by sfan5** [comment]
What's with all the unnecessary changes? This PR is only getting further from a mergeable state (IMO).

All the modder wants to do is spawn an entity. Then we add a check that prevents spawning it. But in case the modder *really* wants to he can tell the engine to "actually do it anyway" with a new parameter.
I don't know why Wuzzy only wants to spawn entities in loaded blocks. But if that's a concern he can use `minetest.compare_block_status` or even `minetest.get_node_or_nil` to check before spawning.
There is no need to complicate it for everyone else.

**Comment by sfence** [comment]
Looks like adding two modes is controversial. 
The last 3 commits reverted.

Now add_entity will work for loaded, unloaded, and nongenerated blocks as well.

File: src/serverenvironment.cpp (hunk 1 above)
Comment (sfence) [reply src/serverenvironment.cpp]: Resolved based on sfan5 comment below.

**Comment by sfan5** [comment]
> We probably don't want active objects in unloaded areas.

btw this isn't as problematic as it sounds.
What happens is that the entity is spawned as active object and an ObjectRef returned. Quickly afterwards (not sure if on the same step, but at earliest on the next step) it is unloaded and saved as a static object to disk.

Consider that objects can also teleport or move right into unloaded blocks.

**Review by sfan5 — APPROVED** [review]

File: src/serverenvironment.cpp (hunk 6 above)
Comment (lhofhansl) [reply src/serverenvironment.cpp:1922]: So, as is, we can just remove the else branch, no? (Assuming the exception case is fixed.)

File: doc/lua_api.md [hunk 7]
```diff
@@ -5948,8 +5948,11 @@ Environment access
 * `minetest.add_entity(pos, name, [staticdata])`: Spawn Lua-defined entity at
   position.
     * Returns `ObjectRef`, or `nil` if failed
+    * Entities with `static_save = true` can be added also 
+      to unloaded/nongenerated blocks.
```
Comment (grorp) [inline doc/lua_api.md:5952]: to make sure that nobody thinks they are the same, an explicit "and" instead of the slash would be good

also, I think it should be spelled "non-generated"?

File: src/serverenvironment.cpp (hunk 6 above)
Comment (sfan5) [reply src/serverenvironment.cpp:1922]: as of 9da1354f3ae5bb62f9cf067c3ae38d87d956d603 the else branch is no longer dead code

**Comment by grorp** [comment]
I've tested that this PR fixes the test case provided in https://github.com/minetest/minetest/issues/4759#issuecomment-322212639 by Wuzzy. It also correctly returns errors for entities outside the map boundaries.


I extended the test code as follows: https://sprunge.us/MKuZU6?lua. When activating all entities two times by flying back and forth along the line generated by `/spawntest`, this was the output:

```
Server for gameid="minetest" listening on 0.0.0.0:30000.
grorp [127.0.0.1] joins game. List of players: grorp
[on_activate] got right staticdata for dtime_s == 0 (×1000)
2024-02-01 14:56:38: ERROR[Server]: minetest.add_entity reported 1000 succeeded spawns.
2024-02-01 14:56:38: ERROR[Server]: minetest.add_entity reported 0 failed spawns.
[on_activate] got wrong staticdata for dtime_s == 0: "later staticdata" (×932)
[on_activate] got right staticdata for dtime_s != 0 (×1032)
grorp leaves game. List of players: 
Server: Shutting down
2024-02-01 14:58:42: [Main]: INFO: signal_handler(): Ctrl-C pressed, shutting down.
```

The `[on_activate] got wrong staticdata for dtime_s == 0: "later staticdata" (×932)` first confused me, but now I realize it makes sense: The block containing the object is not generated yet, the block timestamp is `BLOCK_TIMESTAMP_UNDEFINED` and thus `dtime_s` is 0 when activating the object.

**Comment by sfence** [comment]
> (Unrelated: have you considered proposing as a core dev?)

(Unrelated: Have no idea what responsibilities come with it.)

**Review by grorp — APPROVED** [review]
