### PR TITLE
LocalPlayer: Fix sneaking on nodes with large collisionboxes

### LINKED ISSUE #12612: Broken movement if you sneak on collision box that lies entirely in another node
##### Minetest version
```
5.5.1, 5.6.0-dev-de8ce9a8ff999c7ab9562528a972d5426a9f7cec
```

##### OS / Hardware
Operating system: linux

##### Summary
when a node's nodebox exists entirely within another node, startling behavior develops when you stand on it and press "sneak"

##### Steps to reproduce
1. load this mod:
```lua
local no_flicker = 1 / 4096

minetest.register_node("nodebox_jank:node", {
	drawtype = "nodebox",
	paramtype2 = "facedir",
	node_box = {
		type = "fixed",
		fixed = {{
	         -1 / 2 + no_flicker,
	         -1 / 2 + no_flicker,
	         -1 / 32 + 1,
	         1 / 2 - no_flicker,
	         1 / 2 - no_flicker,
	         1 / 32 + 1
         }},
	},
})
```

2. place a line of these. param2 matters, though it works in all directions. 
3. jump on top of the first in the series (it is directional, pay attention).
4. press sneak

result:

https://user-images.githubusercontent.com/25628292/181864685-9ce283cc-6b25-45f3-87ee-09f157a4152f.mp4

possibly related:
* #9993

### PR DESCRIPTION
**Pull request by SmallJoker**
Fixes #12612 by taking the nodebox extent center into account.

## To do

This PR is Ready for Review.

## How to test

1. Example node from #12612
2. Enable sneak_glitch (there's a mod for it) to ensure the ladder still work
3. Optimal test setup:
screenshot_20220801_123133

### CODE REVIEW

File: src/script/cpp_api/s_security.cpp [hunk 1]
```diff
@@ -417,6 +417,13 @@ void ScriptApiSecurity::setLuaEnv(lua_State *L, int thread)
 
 bool ScriptApiSecurity::isSecure(lua_State *L)
 {
+#ifndef SERVER
+	auto script = ModApiBase::getScriptApiBase(L);
+	// CSM keeps no globals backup but is always secure
+	if (script->getType() == ScriptingType::Client)
```
Comment (sfan5) [inline src/script/cpp_api/s_security.cpp:423]: :green_apple:

Comment (SmallJoker) [reply src/script/cpp_api/s_security.cpp]: It never happened

File: src/client/localplayer.cpp [hunk 2]
```diff
@@ -55,9 +55,12 @@ static aabb3f getNodeBoundingBox(const std::vector<aabb3f> &nodeboxes)
 	return b_max;
 }
 
+
 bool LocalPlayer::updateSneakNode(Map *map, const v3f &position,
 	const v3f &sneak_max)
 {
+	// Acceptable distance to node center
+	constexpr f32 allowed_range = (0.5f + 0.1f) * BS;
```
Comment (appgurueu) [inline src/client/localplayer.cpp:63]: This seems pretty hardcoded and arbitrary to me

Comment (SmallJoker) [reply src/client/localplayer.cpp:63]: I could've as well changed nothing and nobody would ever complain.

It's good as is and should be kept like that.

Comment (appgurueu) [reply src/client/localplayer.cpp:63]: I would at least annotate this as a hack. The "allowed range" should be based on nodebox extent.

Comment (sfan5) [reply src/client/localplayer.cpp:63]: setting it to nodebox extent = no range checking = the bug seen in OP issue

**Review by TurkeyMcMac — COMMENTED** [review]
I still notice some issues when sneaking on the janky nodes:

1. When sneaking onto a janky node whose plane is vertical, my point of view sometimes gets snapped into a different position, suddenly moving horizontally.
2. When I am on a janky node whose plane is horizontal and I start sneaking then walk off the edge, nothing stops my movement.

These things occur with or without the sneak glitch enabled.

**Comment by SmallJoker** [comment]
@TurkeyMcMac Could you please provide an image of what nodes you tested? Is this a regression or behaviour that already exists in master?

**Comment by TurkeyMcMac** [comment]
Setup for issue 1:
screenshot_20221012_153814

Setup for issue 2:
screenshot_20221012_153844

Issue 1 seems to be new with this PR, while issue 2 also occurs on master.

**Comment by SmallJoker** [comment]
The fix for the first issue is to use the distance between the player and node collision box (using the nearest manhattan point). Currently I am using the center point of each the nodeboxes for simplcity. However I cannot think of a trivial implementation to fix this issue, as it would also have to be repeated for each node in range, making the code slower than it already is.

**Comment by TurkeyMcMac** [comment]
Alright, it's good to have this fix anyway.

**Review by TurkeyMcMac — APPROVED** [review]

**Comment by lhofhansl** [comment]
This seems to break auto-jump.
