### PR TITLE
Mgv6 mudflow: Remove decoration if 'dirt with grass' below flows away

### LINKED ISSUE #5796: Floating decorations in v6 at default settings (caused by mudflow?)
Minetest generates floating plants/decorations in mapgen v6 at default settings:

Above screenshot is made with almost default v6 settings (I disabled trees for this screenshot, but I tested if with trees with no impact on the bug). Note it is **not** part of the bug report that the grass spawns all over the place, this is intentional! I edited the decorations in Minetest Game to make the bug very easy to spot.

I am pretty sure this bug is caused by the `mudflow` flag of v6 mapgen settings. Here is the same spot *without* mudflow:

How to reproduce:
* Use any simple subgame with v6 support (Minetest Game or Minimal development test work just fine)
* Define a simple decoration with a very high offset so it is generated everywhere
* Make sure to use default v6 mapgen settings, but disable trees
* Create a v6 world with seed 555
* Teleport to: X=-189, Y=15, Z=106

Note: This is *not* the same bug as this one: https://github.com/minetest/minetest/issues/1274

This bug occours for me in:
* ec490abf5889e06c88887e17f1746043de3b10fe
* 0.4.15
* Probably many versions before 0.4.15 if my memory is not failing me

### PR DESCRIPTION
**Pull request by paramat**
Mudflow of a neighbouring mapchunk extends into a mapchunk's edge, and could
remove 'dirt with grass' from under a decoration, creating unsupported
decorations.

Remove any decoration above if a 'dirt with grass' node is removed by mudflow.
//////////////////////////////////////

Fixes #5796 
Tested.

screenshot_20170522_121603

^ Same hill as shown on issue, no floating grasses.

The 'node above' the removed 'dirt with grass' node is the newly-added 'Mapnode *n3'. The PR gets 'n3' at low cost, at a place in the code where 'node above' is already being tested. Then 'n3' is used later.

### CODE REVIEW

**Comment by Wuzzy2** [comment]
I can confirm removal of floating plants at these coordinates above.

However, I found a different place with floating decorations (v6, default settings):



Whether this is caused by mudflow or something else needs to be seen. Probably needs a new issue, am I right?

**Comment by Wuzzy2** [comment]
I have to take back my recommendation for merging:



Floating papyrus. :D
And this definitely looks related to mudflow.

**Comment by Wuzzy2** [comment]
Yep. This definitely is not done yet (again, papyrus spawn rate artificually inflated for testing):



* Coordinates and seed: See previous screenshot
* Mapgen: v6
* Default mapgen settings, but v6 trees are disabled

**Comment by paramat** [comment]
Well that's caused by my code removing the one node above the flowed dirt node, so it removes the lowest papyrus node and leaves the rest. Papyrus on a mudflow node will be rare so it's not a big problem.
But if a fix is necessary perhaps it could search upwards until it finds air, to remove any stacked decoration. This will slow mapgen a tiny bit so it's a balance.
So i still think this is mergeable, but maybe also improveable.

**Comment by Wuzzy2** [comment]
@paramat: I agree, it can still be merged in this current form because it contains an obvious bugfix. I will simply post new issues later then. :stuck_out_tongue:

Why not preventing placement of decorations on mudflow'ed decorations altogether?

**Comment by paramat** [comment]
The decorations above large caves is a similar issue, the decorations were placed on 'dirt with grass' but then the caves in a neighbouring mapchunk generated out beyond a mapchunk border and removed the ground from under the decorations. This would be much more intensive to fix and i think not worth slowing mapgen for.

**Comment by Wuzzy2** [comment]
@paramat: I agree, it can still be merged in this current form because it contains an obvious bugfix. I will simply post new issues later then. :stuck_out_tongue:

Why not preventing placement of decorations on mudflow'ed decorations altogether, instead of trying and guessing where decorations may have been spawned?

Yes, it is extremely rare in Minetest Game but this may be different in mods or other subgames. Anyway, let's count that as different issues, then.

**Comment by paramat** [comment]
Mgv6 has mostly hardcoded mapgen and decorations, so subgames tend to nor alter mgv6 as much as other mapgens.

> Why not preventing placement of decorations on mudflow'ed decorations altogether, instead of trying and guessing where decorations may have been spawned?

Not possible, in chunk 'A' the decorations are placed after mudflow on 'dirt with grass'. Then chunk 'B' generates and the mudflow operations extend beyond the border of chunk B into the edge of chunk A and remove nodes from under the decorations in chunk A.

**Comment by Wuzzy2** [comment]
> Mgv6 has mostly hardcoded mapgen and decorations, so subgames tend to nor alter mgv6 as much as other mapgens.

MineClone 2 is the exception from the rule, it has many decorations. :D 
Anyway, thanks for the work so far. Let's discuss this later in other issues.

> Not possible, in chunk 'A' the decorations are placed after mudflow on 'dirt with grass'. Then chunk 'B' generates and the mudflow operations extend beyond the border of chunk B into the edge of chunk A and remove nodes from under the decorations in chunk A.

Argh, crap! xD

File: src/mapgen_v6.cpp [hunk 1]
```diff
@@ -836,13 +836,17 @@ void MapgenV6::flowMud(s16 &mudflow_minpos, s16 &mudflow_maxpos)
...
+				// Check that upper is walkable. Cancel
+				// dropping if upper keeps it in place.
 				u32 i3 = i;
 				vm->m_area.add_y(em, i3, 1);
-				if (vm->m_area.contains(i3) == true &&
-						ndef->get(vm->m_data[i3]).walkable)
-					continue;
+				MapNode *n3 = NULL;
+
+				if (vm->m_area.contains(i3) == true) {
```
Comment (nerzhul) [inline src/mapgen_v6.cpp]: useless == true, you can remove if it's implicit

Comment (paramat) [inline src/mapgen_v6.cpp]: Oops.

Comment (paramat) [inline src/mapgen_v6.cpp]: It's because the existing code is full of '== false' and '== true'. Maybe after release i will go through mgv6 code and clean it up.

**Comment by paramat** [comment]
Updated to remove useless '== true' and also a typo in comments.

**Comment by paramat** [comment]
Retested.
