### PR TITLE
Fix bone-attached entities

### LINKED ISSUE #2813: Attachments experience movement delays, triggered randomly
I found a weird and annoying issue with attachments. As much as I implemented the initial attachment code, I cannot figure out what is causing this and why. It might be an Irrlicht bug, although I'm inclined to suspect something Minetest side as well.

When an object is attached via obj:set_attach, there will be times when it follows its parent smoothly as it moves around, instead of instantly duplicating its position and rotation like it should. The problem is only triggered randomly too: Sometimes I would restart the game and it works fine, at other times there's the movement delay.

I only tried this by parenting a Lua entity to a bone on my player's model, then watching myself in 3rd person view as I moved around. Some of the objects are firmly attached to me, while others follow me slowly and it looks off... which does which is always random whenever I start the game.

### LINKED ISSUE #10010: Entities disappear in 3rd person mode when running set_attach()
##### Minetest version
```
Minetest 5.3.0-dev-8fc9e7eb1 (Windows)
```

##### OS / Hardware
Operating system: Windows 10
CPU: Ryzen 3200G

GPU model: 8192MB ATI Radeon RX 580 Series (XFX Pine Group)
OpenGL version: 4.6

##### Summary
Entities do not appear/disappear in 3rd person mode when running set_attach() to a player.

##### Steps to reproduce
Run code which runs ```entity:set_attach(player,"Body",vector.new(0,0,0),vector.new(0,0,0)) ``` and they will disappear until camera change.

##### Fun Fact
10010 is binary for ```?```

### PR DESCRIPTION
**Pull request by hecktest**
Closes #2813 after a mere five years. May close #10010. Fixes other bugs that may or may not be known.

Skeletal animations were updated without evaluating parent transforms first. This meant that depending on the order in which things were processed by irrlicht, the parent might not have had a chance to update the absolute position, and would still use the position from its previous frame.
laghat

Additionally, a subtle bug was caught while looking for the above. Due to a bug in irrlicht, positions of joints would not be updated internally when EJUOR_CONTROL is used. This would result in things being attached to the animated bone position, and not the one set by the user.
offhat
**Upgrade note: if you were querying bone positions and resetting attachments to work around this, you might have to delete that code.** Attachment positions on bones are now always in the bone's local space, even if the bone has an override on it.

Here is a testing mod with a skinned mesh player wearing a hat and using set_bone_position on the head bone.
[coolhat.zip](https://github.com/minetest/minetest/files/4754858/coolhat.zip)

### CODE REVIEW

**Comment by oilboi** [comment]
Please god let this be merged

**Comment by SmallJoker** [comment]
Wouldn't it be a saner approach to update the entire tree in (any only in) the topmost parent? This way you're updating the same model multiple times per step which looks a bit inefficient.

**Comment by hecktest** [comment]
I tried different approaches like sorting the step calls by hierarchy. I tried evaluating the skeleton both before step and after step. I tried many more things. Out of all the possible combinations, this is the only one that worked.

This only evaluates something twice if two skinned meshes share a parent. Possible when sharing a vehicle but not as common as it seems at first. I haven't seen a whole lot of multi-user spider tanks in minetest, as sad as that is.
Updating a transform twice happens in the best of game engines, since you can't always predict how the objects are going to affect one another. The one thing that could help is marking transforms as dirty and deferring the evaluation until the position is actually needed, but that would require a whole refactor, and I just want to patch this hole and get it merged quickly.

File: src/client/content_cao.cpp [hunk 1]
```diff
@@ -917,11 +926,6 @@ void GenericCAO::updateNodePos()
 
 void GenericCAO::step(float dtime, ClientEnvironment *env)
 {
-	if (m_animated_meshnode) {
```
Comment (hecktest) [inline src/client/content_cao.cpp:920]: Since the positions of bones depend on the position of the model, the skeleton must be processed last. So this block is now at the end of step.

File: src/client/content_cao.cpp [hunk 2]
```diff
@@ -1131,6 +1135,19 @@ void GenericCAO::step(float dtime, ClientEnvironment *env)
 		rot_translator.val_current = m_rotation;
 		updateNodePos();
 	}
+
+	if (m_animated_meshnode) {
+		// Everything must be updated; the whole transform
+		// chain as well as the animated mesh node.
+		// Otherwise, bone attachments would be relative to
+		// a position that's one frame old.
+		if(m_matrixnode){
```
Comment (hecktest) [inline src/client/content_cao.cpp:1144]: Irrlicht does this before render, but by that time it's already too late since we're animating the model right here. Note that we only evaluate transforms if we have an animated mesh node, other kinds of CAOs will not take this code path. We'll have to eat the occasional redundant evaluate until a more robust transform system is implemented.

File: src/client/content_cao.cpp [hunk 3]
```diff
@@ -1432,6 +1449,17 @@ void GenericCAO::updateBonePosition()
 			bone->updateAbsolutePosition();
 		}
 	}
```
Comment (hecktest) [inline src/client/content_cao.cpp:1451]: This is almost line for line what irrlicht does in CAnimatedMeshSceneNode, in its EJUOR_READ path. Due to an oversight, the other code paths do not do this, and some lines above we've just set EJUOR_CONTROL so we're sure to miss it.

File: src/client/content_cao.cpp [hunk 4]
```diff
@@ -1432,6 +1449,17 @@ void GenericCAO::updateBonePosition()
...
+	// The following is needed for set_bone_pos to propagate to
+	// attached objects correctly.
+	// Irrlicht ought to do this, but doesn't when using EJUOR_CONTROL.
+	for (u32 i = 0; i < m_animated_meshnode->getJointCount(); ++i) {
+		auto bone = m_animated_meshnode->getJointNode(i);
+		// Look for the root bone.
+		if (bone != NULL && bone->getParent() == m_animated_meshnode) {
```
Comment (hecktest) [inline src/client/content_cao.cpp:1458]: This is almost line for line what irrlicht does in CAnimatedMeshSceneNode, in its EJUOR_READ path. Possibly by mistake, the other code paths do not do this, and some lines above we've just set EJUOR_CONTROL so we're sure to miss it.

**Comment by theviper121** [comment]
The issue described in #9807 is old mods making use of the old broken behavior. I need to add legacy support for these mods so that backwards compatibility is maintained. I tested and this fix has no effect on the issue.

**Comment by LoneWolfHT** [comment]
So this will fix things like wielditems being in the wrong place for a few frames?

**Comment by hecktest** [comment]
> 
> 
> So this will fix things like wielditems being in the wrong place for a few frames?

If by wrong place you mean lagging behind, then yes. Combined with #10008, other placement and rendering issues are also gone. Bone attachments are finally stable enough to safely use.

**Comment by Jordach** [comment]
Does this also fix rare cases of two attached entities (when attached to an animated) with (bone) animated meshes from flickering every frame?

**Comment by hecktest** [comment]
> 
> 
> Does this also fix rare cases of two attached entities (when attached to an animated) with (bone) animated meshes from flickering every frame?

I don't know. Could you describe a specific test case?

**Comment by hecktest** [comment]
Just in case, I tried attaching an animated mesh to another animated mesh. Worked.
stack
Then I tried attaching two, and that worked as well.
rollin
But why stop there? Science demands and so I deliver. Works.
chain

**Comment by oilboi** [comment]
Merge it, merge it, merge it!

**Comment by oilboi** [comment]
Well the last line of what I said was right >:D

File: src/client/content_cao.cpp [hunk 5]
```diff
@@ -1432,6 +1448,17 @@ void GenericCAO::updateBonePosition()
...
+	// The following is needed for set_bone_pos to propagate to
+	// attached objects correctly.
+	// Irrlicht ought to do this, but doesn't when using EJUOR_CONTROL.
+	for (u32 i = 0; i < m_animated_meshnode->getJointCount(); ++i) {
+		auto bone = m_animated_meshnode->getJointNode(i);
+		// Look for the root bone.
+		if (bone && bone->getParent() == m_animated_meshnode) {
+			// Update entire skeleton.
+			bone->updateAbsolutePositionOfAllChildren();
+		}
```
Comment (sfan5) [inline src/client/content_cao.cpp:1460]: Can there be more than one root bone or could a `break` statement be added here?

Comment (hecktest) [reply src/client/content_cao.cpp:1461]: Done

**Comment by hecktest** [comment]
If anybody cares, I tested the last commit extensively again, because it occured to me that multiple roots might in fact be possible. But I couldn't force it to bug out, even by manipulating the scene file manually. I inserted several "competing" object hierarchies with alphabetically higher names, before and after the original, so that the old root would under no circumstances be first in anything. Irrlicht still correctly animated everything and each of the duplicate cool dudes could wear the hat with their head turned.
cool GANG

I don't know about B3D but it's very unlikely that it would behave any different.

File: src/client/content_cao.cpp [hunk 6]
```diff
@@ -1131,6 +1135,18 @@ void GenericCAO::step(float dtime, ClientEnvironment *env)
...
 	}
+
+	if (m_animated_meshnode) {
+		// Everything must be updated; the whole transform
+		// chain as well as the animated mesh node.
+		// Otherwise, bone attachments would be relative to
+		// a position that's one frame old.
+		if (m_matrixnode)
+			updatePositionRecursive(m_matrixnode);
+		m_animated_meshnode->updateAbsolutePosition();
```
Comment (SmallJoker) [inline src/client/content_cao.cpp:1146]: Is this necessary? The absolute position is updated in `updateBonePosition` -> `updateAbsolutePositionOfAllChildren`

https://github.com/zaki/irrlicht/blob/master/source/Irrlicht/CBoneSceneNode.cpp#L92

Comment (hecktest) [reply src/client/content_cao.cpp:1146]: It's called on the root bone, not this scene node itself. This is one level above. (and must be updated first)

Comment (SmallJoker) [reply src/client/content_cao.cpp:1146]: Thanks. That explains it.
