### PR TITLE
Fix ESC in error dialog from closing Minetest

### LINKED ISSUE #10332: Pressing ESC in the main menu error screen should not close the client
##### Minetest version
```
Minetest 5.3-stable
```

##### Summary
Pressing ESC in an error screen of the main menu to quickly dismiss the message instead closes Minetest. This is very unintuitive and destructive behavior. In Windows and Mac operating systems, the ESC key is not customarily used to quit an application.

For the longest time I figured this was just a personal nuiscance, so I didn't report it. But then I noticed the same concern raised in https://github.com/minetest/minetest/issues/8930#issuecomment-531357588, so I decided to go ahead and open an issue.

### PR DESCRIPTION
**Pull request by yamanq**
Closes #10332 

## To do

Ready for Review.

## How to test

1. Create an error, for example by connecting to an unknown domain
2. Press escape

### CODE REVIEW

**Comment by rubenwardy** [comment]
This feels like a hack, it would be better to avoid `MenuQuit` being triggered twice

**Comment by yamanq** [comment]
I am not sure what you mean @rubenwardy 
From everything I can tell, MenuQuit is only being called once but since error messages directly override any ui element, pressing escape in the error menu is the same as pressing escape in the tabview. To test this, I added a logging line above guiFormSpecMenu.cpp:4071.

I'm not sure which part of the code feels hacky. If it's the introduction of ui.override, I can remove it.

File: builtin/fstk/ui.lua [hunk 1]
```diff
@@ -18,6 +18,7 @@
 ui = {}
 ui.childlist = {}
 ui.default = nil
+ui.override = false
```
Comment (rubenwardy) [inline builtin/fstk/ui.lua:21]: Please call this 


```suggestion
-- Whether fstk is currently showing its own formspec instead of active ui elements.
ui.overridden = false
```

File: builtin/fstk/ui.lua [hunk 2]
```diff
@@ -185,6 +188,14 @@ end
 
 --------------------------------------------------------------------------------
 core.event_handler = function(event)
+	-- Handle error messages
+	if (ui.override and event == "MenuQuit") then
```
Comment (rubenwardy) [inline builtin/fstk/ui.lua:192]:
```suggestion
	if ui.overridden then
		if event == "MenuQuit" then
			gamedata.errormessage = nil
			ui.override = false
			ui.update()
		end
		return
	end
	
```

File: builtin/fstk/ui.lua [hunk 3]
```diff
@@ -71,6 +72,7 @@ function ui.update()
 			"button[2,6.6;4,1;btn_reconnect_yes;" .. fgettext("Reconnect") .. "]",
 			"button[8,6.6;4,1;btn_reconnect_no;" .. fgettext("Main menu") .. "]"
 		}
+		ui.override = true
```
Comment (rubenwardy) [inline builtin/fstk/ui.lua:75]:
```suggestion
		ui.overridden = true
```

File: builtin/fstk/ui.lua [hunk 4]
```diff
@@ -89,6 +91,7 @@ function ui.update()
 				error_title, error_message),
 			"button[5,6.6;4,1;btn_error_confirm;" .. fgettext("OK") .. "]"
 		}
+		ui.override = true
```
Comment (rubenwardy) [inline builtin/fstk/ui.lua:94]:
```suggestion
		ui.overridden = true
```

**Review by rubenwardy — COMMENTED** [review]
OK: looking into it, this PR is currently the best way to do it. (IMO, the error dialog should eventually be changed into an actual dialog.)

Please add

```lua
ui.overridden = false
```

to top of ui.update()

**Comment by yamanq** [comment]
Thank you for the review. I have implemented all the suggestions. I also thought the error formspec overriding the ui could be to allow an error caused by a ui element to be displayed even if the rendering of the ui might be broken.

File: builtin/fstk/ui.lua [hunk 5]
```diff
@@ -18,6 +18,8 @@
 ui = {}
 ui.childlist = {}
 ui.default = nil
+-- Whether fstk is currently showing its own formspec instead of active ui elements.
+ui.overriden = false
```
Comment (rubenwardy) [inline builtin/fstk/ui.lua:22]: Two `d`s

**Comment by yamanq** [comment]
Fixed spelling mistake.

**Review by rubenwardy — APPROVED** [review]

**Review by SmallJoker — APPROVED** [review]
Works as expected.
