### PR TITLE
clear_craft: Return false instead of Lua error if recipe not found

### LINKED ISSUE #6513: minetest.clear_craft should return false instead of throwing an exception when it can't find the recipe it's given
In the course of working on my crafting system mod [[simplecrafting_lib]](https://github.com/minetest-mods/simplecrafting_lib) I've run into a great deal of trouble dealing with minetest.clear_craft. In a nutshell, it would be a lot easier to work with if it returned a true/false success value rather than throwing an exception when attempting to clear a craft that doesn't exist.

The problems I'm having stem from my [recipe import code](https://github.com/minetest-mods/simplecrafting_lib/blob/master/legacy.lua). It is meant to cycle through all registered items, call minetest.get_all_craft_recipes on each item, and then potentially call clear_craft if the licensee for simplecrafting_lib has registered a filter for that recipe. But if I inadvertently call clear_craft with a recipe that is "the same" as a recipe that I've previously cleared, the game throws an exception and exits to main menu.

To work around this I've resorted to keeping track of the recipes that I've already called clear_craft with and wrapping clear_craft in a "safe_clear_craft" method that will only call clear_craft if the recipe hasn't been cleared before. But it's proving complicated to figure out what recipes count as "the same", as far as clear_craft is concerned. For example:

	minetest.register_craft({
	output = "default:chest",
	recipe = {
		{"default:wood", "default:wood", "default:wood"},
		{"default:wood", "", ""},
		{"default:wood", "", ""}
	}})
	minetest.register_craft({
	output = "default:chest",
	recipe = {
		{"group:wood", "group:wood", "group:wood"},
		{"group:wood", "", ""},
		{"group:wood", "", ""}
	}})

	local crafts = minetest.get_all_craft_recipes("default:chest")
	for _, recipe in pairs(crafts) do
		minetest.debug(dump(recipe))
	end

	minetest.clear_craft({recipe = {
		{"default:wood", "default:wood", "default:wood"},
		{"default:wood", "", ""},
		{"default:wood", "", ""}
	}})
	minetest.clear_craft({recipe = {
		{"group:wood", "group:wood", "group:wood"},
		{"group:wood", "", ""},
		{"group:wood", "", ""}
	}})

This code will throw a "No crafting specified for input" exception when I try to clear the second recipe, since the crafting system code has decided that clearing the "default:wood" recipe means that the "group:wood" one should also be removed. Note that both of those registered recipes are definitely present in the crafting system before the first clear_craft call, that debug dump I stuck in the middle shows that they're both registered for default:chest.

The end result is that I've written ~140 lines of Lua code to reproduce the checking that clear_craft is doing in order to make sure that I never tell clear_craft to remove "the same" recipe twice. It would be much easier to work with this - and much more bug-resistant and future-proof - to just have clear_craft return false if it's unable to find the recipe it's been given. It looks like it'd be a simple change at the end of l_clear_craft in l_craft.cpp.

### PR DESCRIPTION
**Pull request by paramat**
Closes #6513 
@FaceDeer @VanessaE

### CODE REVIEW

**Comment by VanessaE** [comment]
stable 0.4 branch also?

**Comment by paramat** [comment]
Maybe, not sure, it's borderline bugfix.

**Comment by paramat** [comment]
Works when specifying 'output', but not when specifying recipe. Very possible i've done something silly.
Testing mod:
```
-- clear_craft({[output=item], [recipe={{item00,item10},{item01,item11}}])

local success = minetest.clear_craft({
	output = 'default:torch',
	--[[
	recipe = {
		{'default:coal_lump'},
		{'group:stick'},
	}
	--]]
})
if success then
	print("success")
elseif not success then
	print("fail")
end

--[
success = minetest.clear_craft({
	output = 'default:torch',
	--[[
	recipe = {
		{'default:coal_lump'},
		{'group:stick'},
	}
	--]]
})
if success then
	print("success")
elseif not success then
	print("fail")
end
--]]
```

File: src/script/lua_api/l_craft.cpp [hunk 1]
```diff
@@ -295,10 +295,10 @@ int ModApiCraft::l_clear_craft(lua_State *L)
 	CraftOutput c_output(output, 0);
 	if (!output.empty()) {
 		if (craftdef->clearCraftRecipesByOutput(c_output, getServer(L)))
-			return 0;
+			return 1;
```
Comment (rubenwardy) [inline src/script/lua_api/l_craft.cpp]: You return the craft table passed to `clear_craft` here. Did you mean to return `true`?

In which case it's:

```c++
lua_pushboolean(L, true);
return 1;
```

File: src/script/lua_api/l_craft.cpp [hunk 2]
```diff
@@ -295,10 +295,10 @@ int ModApiCraft::l_clear_craft(lua_State *L)
...
 
-		throw LuaError("No craft recipe known for output"
-				" (output=\"" + output + "\")");
+		warningstream << "No craft recipe known for output" << std::endl;
+		return 0;
```
Comment (rubenwardy) [inline src/script/lua_api/l_craft.cpp]: This returns `nil`, it would be better to return `false`:

```lua
lua_pushboolean(L, false);
return 1;
```

File: src/script/lua_api/l_craft.cpp [hunk 3]
```diff
@@ -347,10 +347,13 @@ int ModApiCraft::l_clear_craft(lua_State *L)
 	} else {
 		throw LuaError("Unknown crafting definition type: \"" + type + "\"");
 	}
+
 	if (!craftdef->clearCraftRecipesByInput(method, width, recipe, getServer(L)))
-		throw LuaError("No crafting specified for input");
+		warningstream << "No craft recipe matches input" << std::endl;
```
Comment (rubenwardy) [inline src/script/lua_api/l_craft.cpp]: missing `{}`

File: src/script/lua_api/l_craft.cpp [hunk 4]
```diff
@@ -347,10 +347,13 @@ int ModApiCraft::l_clear_craft(lua_State *L)
...
+		return 0;
```
Comment (rubenwardy) [inline src/script/lua_api/l_craft.cpp]: returns `nil`, not `false`

File: src/script/lua_api/l_craft.cpp [hunk 5]
```diff
@@ -347,10 +347,13 @@ int ModApiCraft::l_clear_craft(lua_State *L)
...
+
 	lua_pop(L, 1);
-	return 0;
+	return 1;
```
Comment (rubenwardy) [inline src/script/lua_api/l_craft.cpp]: Same again, you return the craft table passed to `clear_craft` here

```c++
lua_pushboolean(L, true);
return 1;
```

File: src/script/lua_api/l_craft.cpp (hunk 1 above)
Comment (paramat) [reply src/script/lua_api/l_craft.cpp]: Yes i meant to return true.
I did try using `lua_pushboolean()` throughout but it didn't work for some reason, i'll try again.

File: src/script/lua_api/l_craft.cpp (hunk 3 above)
Comment (paramat) [reply src/script/lua_api/l_craft.cpp]: Ugh ok this is why the correct form didn't work :)

**Comment by paramat** [comment]
Updated, tested and works. However i am unsure about keeping `lua_pop()` now that i am returning bools.

Sorry for my ignorance but, what do `return 0` and `return 1` do? I'm guessing they determine if something is returned or not?

**Comment by rubenwardy** [comment]
You don't need the pop, Lua will clean it up for you.

Lua uses a stack to pass values to C functions. You return the number of elements to pop from the stack and return as the result. So `return 1` pops 1 element from the stack and returns it to Lua

**Comment by paramat** [comment]
Thanks, updated and docs added.
