### PR TITLE
L-System trees fix fruit node resolver

### LINKED ISSUE #15506: L-system trees: `R-Key` does not work
### Luanti version

```true
Luanti 5.11.0-dev-e9080f91f (Linux)
Using LuaJIT 2.1.1725453128
Built by GCC 14.2
Running on Linux/6.10.13 x86_64
BUILD_TYPE=Release
RUN_IN_PLACE=1
USE_CURL=1
USE_GETTEXT=1
USE_SOUND=1
STATIC_SHAREDIR="."
STATIC_LOCALEDIR="locale"
```

### Irrlicht device

_No response_

### Operating system and version

Manjaro Linux

### CPU model

_No response_

### GPU model

_No response_

### Active renderer

_No response_

### Summary

When using `core.spawn_tree(pos, tree_def)`, the `R`-Key in axioms does no longer work. Instead of the fruit-node, air is placed.

Looks like it first broke with https://github.com/minetest/minetest/commit/60810c2d375a8c63e096669dd6c6cd791f2c5075

image

### Steps to reproduce

```lua
core.spawn_tree(vector.new(0,0,0), {
    axiom = "TRT",
    trunk = "mapgen_tree",
    fruit = "mapgen_apple",
    leaves = "mapgen_stone"
})
```

### PR DESCRIPTION
**Pull request by cx384**
Fixes #15506

Sorry for the inconvenience, I must have though `fruit` works just like `leaves2`.

Also note, `fruit` defaults to `"air"` to not trigger node resolver errors when it is not defined.
(Unlike `trunk` and `leaves` which will trigger an error in any case if they are not defined.)

There should be proper error handling when parsing tree defs, but this would be too much for this PR.

## How to test

``` lua
core.register_chatcommand("t", {
    func = function(name)
        local player = core.get_player_by_name(name)
        core.spawn_tree(player:get_pos(), {
		axiom = "TRT",
		trunk = "mapgen_tree",
		fruit = "mapgen_apple",
		leaves = "mapgen_stone"
	})
    end,
})
```

### CODE REVIEW

**Review by sfan5 — APPROVED** [review]
seems ok

File: src/script/common/c_content.cpp [hunk 1]
```diff
@@ -2033,11 +2033,11 @@ bool read_tree_def(lua_State *L, int idx, const NodeDefManager *ndef,
 	getboolfield(L, idx, "thin_branches", tree_def.thin_branches);
 	tree_def.fruit_chance = 0;
 	getstringfield(L, idx, "fruit", fruit);
-	if (!fruit.empty()) {
+	if (fruit.empty())
+		fruit = "air";
```
Comment (SmallJoker) [inline src/script/common/c_content.cpp:2037]: Why do we need this branch?
```C++
	tree_def.fruit_chance = 0;
	getstringfield(L, idx, "fruit", fruit);
	getintfield(L, idx, "fruit_chance", tree_def.fruit_chance);
```
seems to work as well.

Comment (cx384) [reply src/script/common/c_content.cpp:2037]: As I wrote, to not trigger a node resolver error when `fruit` is left empty.
e.g. try this:
``` lua
core.register_chatcommand("t", {
    func = function(name)
        local player = core.get_player_by_name(name)
        core.spawn_tree(player:get_pos(), {
		axiom = "TT",
		trunk = "mapgen_tree",
		leaves = "mapgen_stone"
	})
    end,
})
```

Alternatively, you would have to tell the node resolver somehow to not resolve the node.
(previously `fruit_chance` was used, but this caused the bug)

Comment (SmallJoker) [reply src/script/common/c_content.cpp:2037]: I see. Whereas there is a fallback option in `getIdFromNrBacklog`, we cannot differentiate between "no value" and "invalid node" there. That's unfortunate.
In this case I'd recommend to set `fruit = "air"` before `getstringfield`. Lua-provided empty strings would then get caught by the node resolver and logged appropriately.

Comment (cx384) [reply src/script/common/c_content.cpp]: Oh right, I changed it, now `fruit = ""` does not default to `fruit = "air"` and you get any error by the node resolver instead.

**Review by sfan5 — APPROVED** [review]
lgtm

**Comment by SmallJoker** [comment]
Sorry. Forgot to approve. Post-mortem :+1:.
