### PR TITLE
Restore `.x` models to working state

### LINKED ISSUE #15544: `.x` model rendering regression
### Luanti version

```true
5.11.0-dev (202412121819)
```

### Irrlicht device

Wayland

### Operating system and version

Kubuntu 25.04

### CPU model

AMD 7840HS

### GPU model

AMD Radeon 780M

### Active renderer

OpenGL 4.6

### Summary

Latest build seems to have some weird model issues, most mobs appear fine but lava flan specifically does not show properly but inside out and tiny. Worked fine before this.

### Steps to reproduce

Create world, add mobs redo and mobs monsters and spawn in a lava flan, instead of the tall proud lava blob he usually is with eyes and mouth, he appears like an inside out floating tiny lava worm.

Same happens with mobs_horse...

### PR DESCRIPTION
**Pull request by appgurueu**
Fixes #15544. First commit adds a test, second commit fixes a silly oversight by me, third commit restores previous logic.

It seems possible that the `.x` loader (or at least some models) are relying on buggy behavior but I don't want to debug it so I have just returned it to the previous state.

## How to test

Verify that the included lava flan is not inside out.

### CODE REVIEW

File: irr/src/CXMeshFileLoader.cpp [hunk 1]
```diff
@@ -966,7 +967,7 @@ bool CXMeshFileLoader::parseDataObjectSkinWeights(SXMesh &mesh)
 	u32 i;
 
 	const u32 jointStart = joint->Weights.size();
-	joint->Weights.resize(jointStart + nWeights);
+	joint->Weights.reserve(jointStart + nWeights);
```
Comment (sfan5) [inline irr/src/CXMeshFileLoader.cpp:970]: so where is `joint->Weights` actually resized then?

File: games/devtest/mods/testentities/models/testentities_lava_flan.x [hunk 2]
```diff
@@ -0,0 +1,3506 @@
+xof 0303txt 0032
```
Comment (sfan5) [inline games/devtest/mods/testentities/models/testentities_lava_flan.x:1]: can't we convert this to binary? it's quite big...

File: irr/src/CXMeshFileLoader.cpp (hunk 1 above)
Comment (appgurueu) [reply irr/src/CXMeshFileLoader.cpp:970]: In the loop below. `AnimatedMesh->addWeight(joint)` adds a weight to `joint->Weights`. Amended the commit to add a comment.

File: games/devtest/mods/testentities/models/testentities_lava_flan.x (hunk 2 above)
Comment (appgurueu) [reply games/devtest/mods/testentities/models/testentities_lava_flan.x:1]: I should have used `.gitattributes` properly here.
I think it is a GitHub limitation that this is not respected.
Locally it is hidden in the diff as a "binary file" just fine for me.

I think in terms of file size, this is acceptable for a model file - it is around the size of Sam.

I would also want to keep this as a text file (and ideally as the exact file used in mobs_redo) since these take slightly different code paths. (And I don't have software set up to reliably convert it into a binary .x file).
