### PR TITLE
Fix glitch through celiing with Sneak Glitch

### LINKED ISSUE #11081: Can glitch through ceiling with Sneak Glitch
##### Minetest version
```
5.4.0
```

##### Summary
If a player has `sneak_glitch=true` and `new_move=false` physics, they can glitch through the ceiling with sneak ladders with ease. This issue is basically a revival of #3045, except this time, it depends on specific player physics settings.

Sneak Glitch with New Move seems to work, however (phew!).

This image shows it perfectly:

https://user-images.githubusercontent.com/55103816/109354355-f74a0300-787d-11eb-9d9b-8e2a41ccd4bd.gif

##### Steps to reproduce
* Install and enable the `luacmd` mod
* `/lua me:set_physics_override({sneak_glitch=true, new_move=false})`
* Build a sneak ladder with a solid node ceiling at the top (see image above)
* Go to the bottom
* Hold down the sneak and jump key and climb the sneak ladder

If there's a bug, you glitch through the ceiling. If not, the ceiling stops you.

##### See also

<b>Originally reported here</b> https://github.com/minetest/minetest/issues/7107#issuecomment-786896145

### PR DESCRIPTION
**Pull request by sfence**
- Goal of the PR
Fix jump-related bugs.
- How does the PR work?
Check if there is free space for a jump if sneak_glitch is applied and if the player is not in a collision when the normal jump will happen.
- Does it resolve any reported issue?
Fix #11081

## To do

This PR is a  Ready for Review.

## How to test

See #11081.

before:

https://github.com/minetest/minetest/assets/17455197/443124b2-5ed2-489f-a7e0-e8ca247e301e

after;

https://github.com/minetest/minetest/assets/17455197/4f560f8f-6e42-44f9-8e32-550ca24b206c

### CODE REVIEW

File: src/client/localplayer.cpp [hunk 1]
```diff
@@ -492,6 +497,12 @@ void LocalPlayer::move(f32 dtime, Environment *env, f32 pos_max_d,
 	// Prevent sliding on the ground when jump speed is 0
 	m_can_jump = m_can_jump && jumpspeed != 0.0f;
 
+	// Prevent jump if in node/object
+	if (m_can_jump) {
+		if (collisionInCollision(env, m_client, m_collisionbox, initial_position))
+			m_can_jump = false;
+	}
```
Comment (grorp) [inline src/client/localplayer.cpp:504]: Preventing jumping because the player is inside a node is quite problematic.

If you repeatedly jump up while placing nodes below yourself (["pillaring"](https://minecraft.wiki/w/Tutorials/Pillar_jumping)), you are often partially inside a node for a short time (see #14068). With this change, you often get stuck while pillaring.

Also, other players can place nodes inside you on a multiplayer server. If you can't escape by sideways movement, the only way to escape is jumping, which is made impossible by this change.

File: src/collision.cpp [hunk 2]
```diff
@@ -222,74 +222,16 @@ static inline void getNeighborConnectingFace(const v3s16 &p,
...
-		MYMAX(pos_f->X, newpos_f.X),
-		MYMAX(pos_f->Y, newpos_f.Y),
-		MYMAX(pos_f->Z, newpos_f.Z)
-	);
-	v3s16 min = floatToInt(minpos_f + box_0.MinEdge, BS) - v3s16(1, 1, 1);
-	v3s16 max = floatToInt(maxpos_f + box_0.MaxEdge, BS) + v3s16(1, 1, 1);
+	return (box.MinEdge.X < edge.X) && (edge.X < box.MaxEdge.X) &&
+			(box.MinEdge.Y < edge.Y) && (edge.Y < box.MaxEdge.Y) &&
+			(box.MinEdge.Z < edge.Z) && (edge.Z < box.MaxEdge.Z);
+}
```
Comment (grorp) [inline src/collision.cpp:230]: reimplementation of `aabbox3d::isPointTotalInside`

File: src/client/localplayer.cpp [hunk 3]
```diff
@@ -392,15 +392,20 @@ void LocalPlayer::move(f32 dtime, Environment *env, f32 pos_max_d,
...
-			position.Y = std::min(position.Y, bmax.Y);
-			m_speed.Y = 0.0f;
+			// Check if there is space for sneak glitch
+			v3f pos(position.X, position.Y + y_diff * dtime * 22.0f + BS * 0.01f, position.Z);
+			if (!collisionInCollision(env, m_client, m_collisionbox, pos)) {
+				// Smoothen the movement (based on 'position.Y = bmax.Y')
+				position.Y += y_diff * dtime * 22.0f + BS * 0.01f;
+				position.Y = std::min(position.Y, bmax.Y);
+				m_speed.Y = 0.0f;
+			}
```
Comment (grorp) [inline src/client/localplayer.cpp:402]: this is calculating the new Y position twice

also, couldn't you use `wouldCollideWithCeiling` instead of adding a new function to `collision.cpp`?

**Review by grorp — CHANGES_REQUESTED** [review]

File: src/client/localplayer.cpp (hunk 1 above)
Comment (sfence) [reply src/client/localplayer.cpp:504]: Understand.
Bug prevention does not work without it. But I added a sneak condition to that check.

File: src/collision.cpp (hunk 2 above)
Comment (sfence) [reply src/collision.cpp]: fixed

File: src/client/localplayer.cpp (hunk 3 above)
Comment (sfence) [reply src/client/localplayer.cpp:402]: I have tried to use wouldCollideWithCeiling to replace
https://github.com/minetest/minetest/blob/d802230718221c9d7587bbcc91f6fcc2b9c292c4/src/collision.cpp#L677-L696.
But it does not work as expected.

File: src/collision.cpp [hunk 4]
```diff
@@ -614,3 +636,69 @@ collisionMoveResult collisionMoveSimple(Environment *env, IGameDef *gamedef,
...
+		checkbox.MinEdge += pos_f;
+		checkbox.MaxEdge += pos_f;
+
+		/*
+			Go through every nodebox, find nearest collision
+		*/
+		for (u32 boxindex = 0; boxindex < cinfo.size(); boxindex++) {
+			const NearbyCollisionInfo &box_info = cinfo[boxindex];
+
+			if (collisionEngeInBox(checkbox.MinEdge, box_info.box) ||
```
Comment (appgurueu) [inline src/collision.cpp]: The purpose of this seems to be to check whether `checkbox` and `box_info` collide? If so, then this would be incorrect, since it just checks min/max edges. There are many cases that doesn't cover (including cases where boxes intersect despite no corner of either box being inside the other box). You should then simply replace this with [`checkbox.intersectsWithBox(box_info.box)`](https://irrlicht.sourceforge.io/docu/classirr_1_1core_1_1aabbox3d.html#a5d3d9d09354c4c362625dab7a15dcedb`).

Comment (sfence) [reply src/collision.cpp]: changed

File: src/client/localplayer.cpp [hunk 5]
```diff
@@ -392,10 +392,14 @@ void LocalPlayer::move(f32 dtime, Environment *env, f32 pos_max_d,
...
 			// the ledge is climbed on the next step.
 
-			// Smoothen the movement (based on 'position.Y = bmax.Y')
-			position.Y += y_diff * dtime * 22.0f + BS * 0.01f;
-			position.Y = std::min(position.Y, bmax.Y);
-			m_speed.Y = 0.0f;
+			// Check if there is space for sneak glitch
+			v3f pos(position.X, position.Y + y_diff * dtime * 22.0f + BS * 0.01f, position.Z);
+			if (!collisionInCollision(env, m_client, m_collisionbox, pos)) {
+				// Smoothen the movement (based on 'position.Y = bmax.Y')
```
Comment (SmallJoker) [inline src/client/localplayer.cpp:398]: This comment belongs to the formula with the magic numbers. Please move it too.

File: src/collision.cpp [hunk 6]
```diff
@@ -222,74 +222,9 @@ static inline void getNeighborConnectingFace(const v3s16 &p,
 		*neighbors |= v;
 }
 
-collisionMoveResult collisionMoveSimple(Environment *env, IGameDef *gamedef,
-		f32 pos_max_d, const aabb3f &box_0,
-		f32 stepheight, f32 dtime,
-		v3f *pos_f, v3f *speed_f,
-		v3f accel_f, ActiveObject *self,
-		bool collideWithObjects)
+static bool addAreaNodeBoxes(const v3s16 &min, const v3s16 &max, IGameDef *gamedef, Map *map, std::vector<NearbyCollisionInfo> &cinfo)
```
Comment (SmallJoker) [inline src/collision.cpp:225]: 1. static functions should use snake_case
https://dev.minetest.net/Code_style_guidelines

2. Suggestion: consider to change `v3s16 &` to `v3s16`. Copying once should be faster than dereferencing often.

File: src/collision.cpp [hunk 7]
```diff
@@ -614,3 +629,66 @@ collisionMoveResult collisionMoveSimple(Environment *env, IGameDef *gamedef,
 
 	return result;
 }
+
+bool collisionInCollision(Environment *env, IGameDef *gamedef,
```
Comment (SmallJoker) [inline src/collision.cpp:633]: How about "collisionCheckIntersection" ? The current name confused me.

File: src/collision.cpp [hunk 8]
```diff
@@ -355,6 +290,151 @@ collisionMoveResult collisionMoveSimple(Environment *env, IGameDef *gamedef,
...
+			lplayer_collisionbox.MinEdge += lplayer_pos;
+			lplayer_collisionbox.MaxEdge += lplayer_pos;
+			ActiveObject *obj = (ActiveObject*) lplayer->getCAO();
+			cinfo.emplace_back(obj, 0, lplayer_collisionbox);
+		}
+	}
+#endif
+}
+
+collisionMoveResult collisionMoveSimple(Environment *env, IGameDef *gamedef,
```
Comment (SmallJoker) [inline src/collision.cpp:371]: Might it be possible to move this function above `addAreaNodeBoxes` to avoid unnecessarily changed lines? At least in the web view it's very hard to tell which lines were changed or which that were moved.

File: src/collision.cpp [hunk 9]
```diff
@@ -614,3 +629,66 @@ collisionMoveResult collisionMoveSimple(Environment *env, IGameDef *gamedef,
...
+	ServerEnvironment *s_env = dynamic_cast<ServerEnvironment*>(env);
+
+	ScopeProfiler sp(g_profiler, PROFILER_NAME("collisionInCollision()"), SPT_AVG);
+
+	/*
+		Collect node boxes
+	*/
+	std::vector<NearbyCollisionInfo> cinfo;
+	{
+	//TimeTaker tt2("collisionMoveSimple collect boxes");
```
Comment (SmallJoker) [inline src/collision.cpp:648]: Bad indent level.

File: src/collision.cpp [hunk 10]
```diff
@@ -355,6 +290,151 @@ collisionMoveResult collisionMoveSimple(Environment *env, IGameDef *gamedef,
 			cinfo.emplace_back(true, 0, p, box);
 		}
 	}
+	return any_position_valid;
+}
+
+static void addObjectBoxes(Environment *env,
```
Comment (SmallJoker) [inline src/collision.cpp:296]: 1. snake_case
2. Did you touch any of these lines or were they only moved?

**Review by SmallJoker — COMMENTED** [review]
Generally OK but there's too many lines that show up as modified even though they weren't.

File: src/collision.cpp (hunk 10 above)
Comment (sfence) [reply src/collision.cpp:296]: I only moved them to not duplicate code.

File: src/client/localplayer.cpp [hunk 11]
```diff
@@ -393,9 +393,13 @@ void LocalPlayer::move(f32 dtime, Environment *env, f32 pos_max_d,
...
 
 			// Smoothen the movement (based on 'position.Y = bmax.Y')
-			position.Y += y_diff * dtime * 22.0f + BS * 0.01f;
-			position.Y = std::min(position.Y, bmax.Y);
-			m_speed.Y = 0.0f;
+			// Check if there is space for sneak glitch
+			v3f pos(position.X, position.Y + y_diff * dtime * 22.0f + BS * 0.01f, position.Z);
+			if (!collisionCheckIntersection(env, m_client, m_collisionbox, pos)) {
+				position.Y = pos.Y;
+				position.Y = std::min(position.Y, bmax.Y);
```
Comment (SmallJoker) [inline src/client/localplayer.cpp:400]: Can be simplified to `std::min(pos.Y, bmax.Y)`

File: src/client/localplayer.cpp [hunk 12]
```diff
@@ -492,6 +496,12 @@ void LocalPlayer::move(f32 dtime, Environment *env, f32 pos_max_d,
 	// Prevent sliding on the ground when jump speed is 0
 	m_can_jump = m_can_jump && jumpspeed != 0.0f;
 
+	// Prevent jump if in node/object
+	if (m_can_jump && could_sneak) {
+		if (collisionCheckIntersection(env, m_client, m_collisionbox, initial_position))
```
Comment (SmallJoker) [inline src/client/localplayer.cpp:501]: Isn't this already calculated in L398 - or are those two positions considerably different? Couldn't you keep `sneak_can_jump = false` in L407 in that case?

**Review by SmallJoker — COMMENTED** [review]
Thank you for splitting the code. I like where this is going so far.

File: src/client/localplayer.cpp (hunk 12 above)
Comment (sfence) [reply src/client/localplayer.cpp:501]: The different position argument is used in those locations. So these calls are not equivalent.

File: src/client/localplayer.cpp (hunk 11 above)
Comment (sfence) [reply src/client/localplayer.cpp]: fixed

**Review by SmallJoker — COMMENTED** [review]
Sneak code performance measurement (code: see below)

master
 * sneak: 1.97 us
 * no sneak: 0.82 us

PR:
 * sneak: 10.3 us
 * no sneak: 1.00 us

----

Bug 1:

1. hold sneak until further notice
2. hold the forward key. collide horizontally with a node
4. try to jump - at some chance you can't.
5. release forward key. still cannot jump

This seems to work better when being further away from spawn (e.g. 10000,10,10000)

----

Code for the performance measurement:
```C++
diff --git a/src/client/localplayer.cpp b/src/client/localplayer.cpp
index 9e410d1ac..376351114 100644
--- a/src/client/localplayer.cpp
+++ b/src/client/localplayer.cpp
@@ -27,6 +27,7 @@ with this program; if not, write to the Free Software Foundation, Inc.,
 #include "map.h"
 #include "client.h"
 #include "content_cao.h"
+#include "profiler.h"
 
 /*
        LocalPlayer
@@ -361,6 +362,8 @@ void LocalPlayer::move(f32 dtime, Environment *env, f32 pos_max_d,
                sneak_max = v3f(0.4f * BS, 0.0f, 0.4f * BS);
        }
 
+       TimeTaker tt("", nullptr, TimePrecision::PRECISION_MICRO);
+
        /*
                If sneaking, keep on top of last walked node and don't fall off
        */
@@ -503,6 +506,7 @@ void LocalPlayer::move(f32 dtime, Environment *env, f32 pos_max_d,
 
        // Autojump
        handleAutojump(dtime, env, result, initial_position, initial_speed, pos_max_d);
+       g_profiler->avg("Client: sneak [us]", tt.stop());
 }
 
 void LocalPlayer::move(f32 dtime, Environment *env, f32 pos_max_d)
```

**Comment by sfence** [comment]
@grorp What kind of change is needed now?

**Comment by grorp** [comment]
SmallJoker reported a bug in https://github.com/minetest/minetest/pull/14332#pullrequestreview-1906812718 on Feb 28, which has not been fixed as far as I can see.

**Comment by sfence** [comment]
The bug reported by @SmallJoker should be fixed now.

I am not able to reproduce the original glitch. Hopefully due to the new collision detection logic.
But I removed the part of the code, the fix does not work without it before.

So, more testing that the glitch cannot be reproduced is welcome.

**Comment by sfence** [comment]
Windows build failed due to: 
```
CMake Error at irr/src/CMakeLists.txt:267 (message):
SDL2 is too old, required is at least 2.0.10!
```

File: src/collision.cpp [hunk 13]
```diff
@@ -614,3 +489,212 @@ collisionMoveResult collisionMoveSimple(Environment *env, IGameDef *gamedef,
...
 	return result;
 }
+
+bool collisionCheckIntersection(Environment *env, IGameDef *gamedef,
+		const aabb3f &box_0, const v3f &pos_f, ActiveObject *self,
+		bool collideWithObjects)
+{
+	#define PROFILER_NAME(text) (s_env ? ("Server: " text) : ("Client: " text))
+	Map *map = &env->getMap();
+	ServerEnvironment *s_env = dynamic_cast<ServerEnvironment*>(env);
```
Comment (grorp) [inline src/collision.cpp:499]: Multiple issues:
 - `PROFILER_NAME` macro duplicated -> should only be defined once

 - `ServerEnvironment *s_env = dynamic_cast<ServerEnvironment*>(env);` duplicated and only used for the `PROFILER_NAME` macro -> should be moved there

- `Map *map = &env->getMap();` only exists for passing the map into `add_area_node_boxes` -> should at least be moved closer to `add_area_node_boxes` OR you could instead pass the Environment pointer into `add_area_node_boxes` and do it there

File: src/collision.cpp [hunk 14]
```diff
@@ -614,3 +489,212 @@ collisionMoveResult collisionMoveSimple(Environment *env, IGameDef *gamedef,
...
+
+	ScopeProfiler sp(g_profiler, PROFILER_NAME("collisionInCollision()"), SPT_AVG);
```
Comment (grorp) [inline src/collision.cpp:501]: wrong name

File: src/collision.cpp [hunk 15]
```diff
@@ -614,3 +489,212 @@ collisionMoveResult collisionMoveSimple(Environment *env, IGameDef *gamedef,
...
+
+		v3s16 min = floatToInt(pos_f + box_0.MinEdge, BS) - v3s16(1, 1, 1);
+		v3s16 max = floatToInt(pos_f + box_0.MaxEdge, BS) + v3s16(1, 1, 1);
+
+		bool any_position_valid = add_area_node_boxes(min, max, gamedef, map, cinfo);
+
+		// Do not move if world has not loaded yet, since custom node boxes
+		// are not available for collision detection.
+		// This also intentionally occurs in the case of the object being positioned
+		// solely on loaded CONTENT_IGNORE nodes, no matter where they come from.
```
Comment (grorp) [inline src/collision.cpp:519]: duplicated comment

File: src/collision.cpp [hunk 16]
```diff
@@ -614,3 +489,212 @@ collisionMoveResult collisionMoveSimple(Environment *env, IGameDef *gamedef,
...
+{
+	#define PROFILER_NAME(text) (s_env ? ("Server: " text) : ("Client: " text))
+	Map *map = &env->getMap();
+	ServerEnvironment *s_env = dynamic_cast<ServerEnvironment*>(env);
+
+	ScopeProfiler sp(g_profiler, PROFILER_NAME("collisionInCollision()"), SPT_AVG);
+
+	/*
+		Collect node boxes
+	*/
```
Comment (grorp) [inline src/collision.cpp:505]: unhelpful comment (also misleading since there isn't a similar header comment for the collection of object boxes)

File: src/collision.cpp [hunk 17]
```diff
@@ -614,3 +489,212 @@ collisionMoveResult collisionMoveSimple(Environment *env, IGameDef *gamedef,
...
+		// This also intentionally occurs in the case of the object being positioned
+		// solely on loaded CONTENT_IGNORE nodes, no matter where they come from.
+		if (!any_position_valid) {
+			return true;
+		}
+	} // tt2
+
+	if(collideWithObjects)
+	{
+		/* add object boxes to cinfo */
```
Comment (grorp) [inline src/collision.cpp:527]: unhelpful comment, which you've also duplicated three times

File: src/collision.cpp [hunk 18]
```diff
@@ -614,3 +489,212 @@ collisionMoveResult collisionMoveSimple(Environment *env, IGameDef *gamedef,
...
+		v3f speed;
+		add_object_boxes(env, box_0, 0, pos_f, speed, self, cinfo);
+	} //tt3
```
Comment (grorp) [inline src/collision.cpp:530]: tt3 doesn't exist

File: src/collision.cpp [hunk 19]
```diff
@@ -614,3 +489,212 @@ collisionMoveResult collisionMoveSimple(Environment *env, IGameDef *gamedef,
...
+
+	ScopeProfiler sp(g_profiler, PROFILER_NAME("collisionInCollision()"), SPT_AVG);
+
+	/*
+		Collect node boxes
+	*/
+	std::vector<NearbyCollisionInfo> cinfo;
+	{
+		//TimeTaker tt2("collisionMoveSimple collect boxes");
+		ScopeProfiler sp2(g_profiler, PROFILER_NAME("collision collect boxes"), SPT_AVG);
```
Comment (grorp) [inline src/collision.cpp:509]: wrong names

File: src/collision.cpp [hunk 20]
```diff
@@ -614,3 +489,212 @@ collisionMoveResult collisionMoveSimple(Environment *env, IGameDef *gamedef,
...
+	*/
+
+	{
+		aabb3f checkbox = box_0;
+		checkbox.MinEdge += pos_f;
+		checkbox.MaxEdge += pos_f;
+
+		/*
+			Go through every nodebox, find nearest collision
+		*/
```
Comment (grorp) [inline src/collision.cpp:543]: wrong comment

File: src/collision.cpp [hunk 21]
```diff
@@ -614,3 +489,212 @@ collisionMoveResult collisionMoveSimple(Environment *env, IGameDef *gamedef,
...
+		for (u32 boxindex = 0; boxindex < cinfo.size(); boxindex++) {
+			const NearbyCollisionInfo &box_info = cinfo[boxindex];
+
+			if (box_info.box.intersectsWithBox(checkbox))
+				return true;
+		}
```
Comment (grorp) [inline src/collision.cpp:549]: unecessarily complicated loop, we don't need the index here. instead:

```cpp
for (const NearbyCollisionInfo &box_info : cinfo) {
```

**Review by grorp — CHANGES_REQUESTED** [review]

**Comment by grorp** [comment]
Also, please take a look at the [Code style guidelines](https://dev.minetest.net/Code_style_guidelines) and adjust newly written code accordingly. (The old code you've only moved can stay as is, that makes reviewing easier.)

File: src/collision.cpp (hunk 16 above)
Comment (sfence) [reply src/collision.cpp:505]: There are no similar header comment fox object boxes in `collisionMoveSimple`, should I fix it somehow?

File: src/collision.cpp (hunk 15 above)
Comment (sfence) [reply src/collision.cpp:511]: removed

File: src/collision.cpp (hunk 16 above)
Comment (sfence) [reply src/collision.cpp]: Fixed also in `collisionMoveSimple`

File: src/collision.cpp (hunk 17 above)
Comment (sfence) [reply src/collision.cpp:519]: Fixed also in `collisionMoveSimple`.

**Comment by sfence** [comment]
> Also, please take a look at the [Code style guidelines](https://dev.minetest.net/Code_style_guidelines) and adjust newly written code accordingly. (The old code you've only moved can stay as is, that makes reviewing easier.)

Checked. Hopefully, I do not miss something.

**Review by SmallJoker — COMMENTED** [review]
Whereas this PR technically does what it promises, it does break the sneak glitch slightly.

1. Stand in front of the pillar from the video in the main PR post
2. Hold down forward key
3. Hold down the sneak key
4. Hold down the jump key and sneak-move up by a few steps
5. Release the jump key
 * master: player stops at the ledge (minus the sideway movement due to still holding forward)
 * PR: falls down

Sometimes this also happens when not moving forward but I found it to be easiest to reproduce this way.

**Comment by sfence** [comment]
@SmallJoker 
Should be fixed now.

File: src/client/localplayer.cpp [hunk 22]
```diff
@@ -442,13 +442,19 @@ void LocalPlayer::move(f32 dtime, Environment *env, f32 pos_max_d,
 			// Move player to the maximal height when falling or when
 			// the ledge is climbed on the next step.
 
-			// Smoothen the movement (based on 'position.Y = bmax.Y')
-			// Check if there is space for sneak glitch
 			v3f pos(position.X, position.Y + y_diff * dtime * 22.0f + BS * 0.01f, position.Z);
-			if (!collision_check_intersection(env, m_client, m_collisionbox, pos)) {
+			if (y_diff < BS * 0.6f) {
```
Comment (grorp) [inline src/client/localplayer.cpp:446]: `y_diff < BS * 0.6f` condition duplicated

File: src/client/localplayer.cpp [hunk 23]
```diff
@@ -442,13 +442,19 @@ void LocalPlayer::move(f32 dtime, Environment *env, f32 pos_max_d,
...
+				// Smoothen the movement (based on 'position.Y = bmax.Y')
 				position.Y = std::min(pos.Y, bmax.Y);
 				m_speed.Y = 0.0f;
 			}
+			else {
+				// Check if there is space for sneak glitch
+				if (!collision_check_intersection(env, m_client, m_collisionbox, pos)) {
+					position.Y = std::min(pos.Y, bmax.Y);
+					m_speed.Y = 0.0f;
```
Comment (grorp) [inline src/client/localplayer.cpp:455]: These two lines are duplicated too, it should be possible to have them in one `if`

File: src/collision.cpp [hunk 24]
```diff
@@ -586,3 +603,51 @@ collisionMoveResult collisionMoveSimple(Environment *env, IGameDef *gamedef,
...
+	{
+		v3f speed;
+		add_object_boxes(env, box_0, 0, pos_f, speed, self, cinfo);
+	}
+
+	/*
+		Collision detection
+	*/
+
+	{
```
Comment (grorp) [inline src/collision.cpp:638]: Unnecessary added scope

**Review by SmallJoker — APPROVED** [review]
The recently mentioned sneak issue is now solved
Collision still works properly. Tested by colliding with a `mob_horse` entity.

File: src/collision.cpp [hunk 25]
```diff
@@ -336,62 +273,55 @@ collisionMoveResult collisionMoveSimple(Environment *env, IGameDef *gamedef,
...
-	}
-
-	/*
-		Collect object boxes in movement range
-	*/
-
-	auto process_object = [] (ActiveObject *object) {
+static void add_object_boxes(Environment *env,
+		const aabb3f &box_0, f32 dtime,
+		const v3f &pos_f, const v3f &speed_f, ActiveObject *self,
```
Comment (sfan5) [inline src/collision.cpp:281]: I don't suggest passing `v3f` by reference either

File: src/client/localplayer.cpp [hunk 26]
```diff
@@ -437,15 +437,17 @@ void LocalPlayer::move(f32 dtime, Environment *env, f32 pos_max_d,
...
-				(physics_override.sneak_glitch || y_diff < BS * 0.6f)) {
+		if (y_diff > 0 && m_speed.Y <= 0.0f) {
 			// Move player to the maximal height when falling or when
 			// the ledge is climbed on the next step.
 
-			// Smoothen the movement (based on 'position.Y = bmax.Y')
-			position.Y += y_diff * dtime * 22.0f + BS * 0.01f;
-			position.Y = std::min(position.Y, bmax.Y);
-			m_speed.Y = 0.0f;
+			v3f pos(position.X, position.Y + y_diff * dtime * 22.0f + BS * 0.01f, position.Z);
```
Comment (sfan5) [inline src/client/localplayer.cpp:444]: this could be clearer:
```c
    v3f check_pos = position;
    check_pos.Y += y_diff * dtime * 22.0f + BS * 0.01f;
    // ...
```

**Review by grorp — APPROVED** [review]
OK

**Comment by grorp** [comment]
(trivially rebased after #14654)
