### PR TITLE
OpenGL3: Add subpixel offset for 2D image rendering

### LINKED ISSUE #15524: 2D images are distorted with opengl3 driver
### Luanti version

```true
5.11-dev, latest

-- BUILD_CLIENT: TRUE
-- BUILD_SERVER: FALSE
-- BUILD_UNITTESTS: TRUE
-- BUILD_BENCHMARKS: FALSE
-- BUILD_DOCUMENTATION: TRUE
-- RUN_IN_PLACE: 1
-- Using imported IrrlichtMt at subdirectory 'irr'
-- *** Building IrrlichtMt ***
-- Device: SDL
-- OpenGL: ON
-- OpenGL 3: ON
-- OpenGL ES 2: OFF
```

### Irrlicht device

SDL

### Operating system and version

Pop!_OS 22.04 LTS

### CPU model

_No response_

### GPU model

GeForce GTX 1060

### Active renderer

4.6.0 NVIDIA 560.35.03 (what?)

### Summary

I noticed that with Soothing32, this happens (notice the 4th heart)  

image

It also incorrectly renders the stamina of Block League, which is a perfect rectangle  

image

comparison with 5.10

image

### Steps to reproduce

1. Download Soothing32 texture pack
2. Enable it
3. Open whatever devtest world

In alternative, join A.E.S. server

### PR DESCRIPTION
**Pull request by ExeVirus**
PR addresses 2D image rendering issues with the OpenGL 3 pipeline, specifically where we are calculating pixel coords precisly on pixel boundaries rather than to the center of pixels. The solution is to add an offset, identical to the one used in the shader code for the Fixed Function Pipeline. In this case, we move it to C++ Irrlicht code instead of infecting our Shader. 

Before on top, after on bottom. Refer to the issue below for details:

image

closes #15524

Longer explanation for this PR is provided in that issue as a comment at the bottom as for why this is the correct fix (or at least the same fix as the fixed function pipeline)

This PR is Ready for Review.

## How to test

1. Download soothing32, and minetest_game/devtest
2. open a new world with damage enabled, and the opengl3 pipeline enabled
3. Screen capture the hearts being rendered
      a. if you don't see a problem, restart 1-2 times, and you'll see it in one of them
4. Now rebuild with this change, retest, and issue should be gone.

### CODE REVIEW

File: irr/src/OpenGL/Driver.cpp [hunk 1]
```diff
@@ -769,10 +769,11 @@ void COpenGL3DriverBase::draw2DImage(const video::ITexture *texture, const core:
 				clipRect->getWidth(), clipRect->getHeight());
 	}
 
-	f32 left  = (f32)destRect.UpperLeftCorner.X;
-	f32 right = (f32)destRect.LowerRightCorner.X;
-	f32 down  = (f32)destRect.LowerRightCorner.Y;
-	f32 top   = (f32)destRect.UpperLeftCorner.Y;
+	const f32 offset = 0.375f; // Render to pixel centers, not their corners.
```
Comment (sfan5) [inline irr/src/OpenGL/Driver.cpp]: we have more than this single 2D function, so this won't suffice.
how about?
```diff
diff --git a/client/shaders/Irrlicht/Renderer2D.vsh b/client/shaders/Irrlicht/Renderer2D.vsh
--- a/client/shaders/Irrlicht/Renderer2D.vsh
+++ b/client/shaders/Irrlicht/Renderer2D.vsh
@@ -18,7 +18,8 @@ varying vec4 vVertexColor;
 
 void main()
 {
-	gl_Position = uProjection * inVertexPosition;
+	// Subpixel offset to fix 2D image distortion
+	gl_Position = uProjection * (inVertexPosition + vec4(0.375, 0.375, 0.0, 0.0));
 	gl_PointSize = uThickness;
 	vTextureCoord = inTexCoord0;
 	vVertexColor = inVertexColor.bgra;
```

Comment (ExeVirus) [reply irr/src/OpenGL/Driver.cpp]: Yep, that also fixes it, I assume it catches more spots as you point out.

File: client/shaders/Irrlicht/Renderer2D.vsh [hunk 2]
```diff
@@ -18,7 +18,8 @@ varying vec4 vVertexColor;
 
 void main()
 {
-	gl_Position = uProjection * inVertexPosition;
+	// Subpixel offset to fix 2D image distortion
+	gl_Position = uProjection * (inVertexPosition + vec4(0.375, 0.375, 0.0, 0.0));
```
Comment (SmallJoker) [inline client/shaders/Irrlicht/Renderer2D.vsh:24]: What is the origin of these magic numbers? Please add the formula or a reference to other code to help understanding.

Comment (sfan5) [reply client/shaders/Irrlicht/Renderer2D.vsh:24]: any value `0 < x < 0.5` is probably fine, as long as it's big enough to make a difference
this is just the same value as used by the legacy driver :shrug: 
safe bet IMO

Comment (Desour) [reply client/shaders/Irrlicht/Renderer2D.vsh:24]: Apparently, 0.375 is recommended in some guides, see <https://community.khronos.org/t/the-meaning-of-the-0-375-pixel-translation/56046>. (I didn't have time to look into the details yet.)

**Review by SmallJoker — APPROVED** [review]

File: client/shaders/Irrlicht/Renderer2D.vsh [hunk 3]
```diff
@@ -18,7 +18,9 @@ varying vec4 vVertexColor;
 
 void main()
 {
-	// Subpixel offset to fix 2D image distortion
+	// Subpixel offset to render pixel-perfect 2D images
+	// This is a compromise that is expected to work well on most drivers.
+	// Explanation: https://jvm-gaming.org/t/pixel-perfect-rendering-in-2d/26261/4
```
Comment (appgurueu) [inline client/shaders/Irrlicht/Renderer2D.vsh:23]: Okay, this explanation is satisfying 👍
