### PR TITLE
MetaData: restore undocumented set_string behaviour

### LINKED ISSUE #14391: 6ca214fefc9e1eb707f006631d39c1e4dbafe1b5 changes handling of nil in MetaDataRef:set_string (breaking e.g. Digtron)
### Minetest version

6ca214fefc9e1eb707f006631d39c1e4dbafe1b5

### Operating system and version

Debian Oldstable (no upgrade path available)

### Summary

The commit effectively replaces tolstring with checklstring.

The documentation doesn't say anything about nil. If I understand the code correctly nil is handled as an empty string which  is documented to have the effect of removing an entry. So nil isn't really needed for anything, but since assigning nil is the LUA way of removing a mapping, it probably should be kept functional.

### Steps to reproduce

Get a MetaDataRef in LUA and call set_string("something", nil) on it

### PR DESCRIPTION
**Pull request by SmallJoker**
Fixes #14391

## To do

This PR is Ready for Review.>

## How to test

1. Devtest game
2. `/unittests`
3. All tests must pass.

### CODE REVIEW

File: games/devtest/mods/unittests/metadata.lua [hunk 1]
```diff
@@ -77,6 +77,29 @@ local function test_metadata(meta)
 	assert(not meta:equals(compare_meta))
 end
 
+local function test_metadata_compat(meta)
+	-- key/value removal using set_string (undocumented, deprecated way)
+	meta:set_string("key", "value")
+	assert(meta:get_string("key") == "value")
+	meta:set_string("key", nil) -- ignore warning
+	assert(meta:to_table().fields["key"] == nil)
```
Comment (sfan5) [inline games/devtest/mods/unittests/metadata.lua:85]: cleaner imo
```suggestion
	assert(not meta:contains("key"))
```

**Review by sfan5 — APPROVED** [review]
looks good otherwise

File: games/devtest/mods/unittests/metadata.lua (hunk 1 above)
Comment (SmallJoker) [reply games/devtest/mods/unittests/metadata.lua:85]: This is to check the `to_table()` functionality. Setters + `to_table` were already tested previously but not removing keys. It *should not* make a difference after all, but I found this to be a good addition to the already existing checks.
