### PR TITLE
Android: Segmentation fault fix, PendingIntent flag, and other fixes

### LINKED ISSUE #12952: Minetest crash on Android
##### Minetest version

```
00eb659
```

##### OS / Hardware

Operating system: Android 12 (API 31)
CPU: Snapdragon 685

GPU model: 
OpenGL version:

##### Summary

When I install and open the app, the app crash instantly 

https://user-images.githubusercontent.com/87801676/201289947-24f57499-2289-49d1-a680-e70d499e84a5.mp4

I'm sure a commit breaks it, but I'm not sure which was it ...

##### Steps to reproduce

- install from debug build
- open 
- crash :(

### PR DESCRIPTION
**Pull request by srifqi**
**Goal of the PR**
This PR fixes several bugs and warnings (from the linter) for the Android build.

**How does the PR work?**
- Information about the crosshair is sent after camera initialisation.
- Since API 31, `PendingIntent` [requires mutability flag](https://developer.android.com/about/versions/12/behavior-changes-12#pending-intent-mutability).
- `super` (class) is called in `onRequestPermissionsResult()`.
- `GameActivity` suppresses "unused" warning since most of its methods are called from native code.
- [Non-null safety](https://docs.oracle.com/javase/8/docs/api/java/util/Objects.html#requireNonNull-T-java.lang.String-) is added for nullable function calls.
- Warning/error logging is added for various function calls' return value.

**Does it resolve any reported issue?**
Yes, this PR tries to fix bugs and warnings (from Android Studio's linter):
- This PR tries to fix #12952 which is `UnzipService` can not create notification while copying since #12911.
- I made a mistake when creating #12910 as a fix. Minetest can not play any world because the camera has not been initialised.

**Does this relate to a goal in the roadmap?**
Probably, this PR tries to fix crashes and bugs specifically for the Android build.

## To do
This PR is Ready for Review.

## How to test
1. Compile Minetest for Android.
2. There should be no compilation error.
3. Run Minetest and play any world.
4. There should be no runtime error while playing.

### CODE REVIEW

**Comment by AbduSharif** [comment]
Still can't access any world, I made a new Minetest and MineClone2 world, still fails at:
```
ERROR[Main]: Some exception: ""
```

**Comment by srifqi** [comment]
I noticed that some newer issues might also be the same as #12792 that is caused by unassigned key for the range select button beside the issues that this PR fixes.

---

Can we have a follow up on #12792, @rubenwardy?

**Comment by Anonymous1231-dev** [comment]
@srifqi pls fix also #12958

**Comment by SmallJoker** [comment]
I do not have a setup to test this PR, but the changes do look correct. If desired, I will :+1: so that further issues can be addressed in upcoming PRs.

**Comment by TurkeyMcMac** [comment]
I don't have the issue of the crash at startup, maybe because I have an old phone. However, I can confirm that this PR does not break app startup on my phone. I can't confirm that things still work in-game, since starting a game does not work. However, that seems to be a separate issue.

**Review by TurkeyMcMac — APPROVED** [review]
I can now confirm that the segmentation fault is fixed. I still can't test the `pendingIntentFlag` change, but this should be fine as long as the other reviewer does so. Hopefully this can be merged soon.

File: android/app/src/main/java/net/minetest/minetest/UnzipService.java [hunk 1]
```diff
@@ -210,7 +216,9 @@ private void migrate(Notification.Builder notificationBuilder, File newLocation)
 			return;
 
 		publishProgress(notificationBuilder, R.string.migrating, 0);
-		newLocation.mkdir();
+		if (!newLocation.mkdir()) {
```
Comment (nerzhul) [inline android/app/src/main/java/net/minetest/minetest/UnzipService.java:219]: if it failed, why we should continue ? if the failure cannot permit to continue code we will just trigger side effects

File: android/app/src/main/java/net/minetest/minetest/Utils.java [hunk 2]
```diff
@@ -10,7 +11,8 @@ public class Utils {
 	public static @NonNull File createDirs(File root, String dir) {
 		File f = new File(root, dir);
 		if (!f.isDirectory())
-			f.mkdirs();
+			if (!f.mkdirs())
```
Comment (nerzhul) [inline android/app/src/main/java/net/minetest/minetest/Utils.java:14]: same here, if we failed to create then f has no insurance to be wrote no ?

**Comment by srifqi** [comment]
(replying to nerzhul's review)

The directory creation has been like that since its first added (see 62ae7adab2bebde04864c12543caefbffab24963 and 6901c5fae54eafb05494823b60d4e26c14b342f1). I just added some logging for the operation to make it easier (probably) from debugging perspective. I did not intend to change any behaviour of these lines of code.

-------

Now they said that, how should we report/log it?
1. return false
2. throw exception

Another question would be how should we show these errors to user/player?
1. show the error directly
2. "Installation has failed" with option to retry

What if it is an update? These errors will cause a huge side-effect by changing only _some_ of the files/directories. An option would be using separate folder and then renaming it.

... and those are outside of the scope of this PR in my view.

File: android/app/src/main/java/net/minetest/minetest/UnzipService.java (hunk 1 above)
Comment (srifqi) [reply android/app/src/main/java/net/minetest/minetest/UnzipService.java:219]: (see [my comment](https://github.com/minetest/minetest/pull/12960#issuecomment-1327972518))

File: android/app/src/main/java/net/minetest/minetest/Utils.java (hunk 2 above)
Comment (srifqi) [reply android/app/src/main/java/net/minetest/minetest/Utils.java:14]: (see [my comment](https://github.com/minetest/minetest/pull/12960#issuecomment-1327972518))

File: android/app/src/main/java/net/minetest/minetest/GameActivity.java [hunk 3]
```diff
@@ -180,11 +181,17 @@ public void openURI(String uri) {
 	}
 
 	public String getUserDataPath() {
-		return Utils.getUserDataDirectory(this).getAbsolutePath();
+		return Objects.requireNonNull(
```
Comment (sfan5) [inline android/app/src/main/java/net/minetest/minetest/GameActivity.java:184]: please move the non-null check info `getUserDataDirectory`

Comment (srifqi) [reply android/app/src/main/java/net/minetest/minetest/GameActivity.java:184]: I rearranged some codes regarding non-null-ness.

**Comment by srifqi** [comment]
I rearranged some codes regarding non-null-ness. I also rebased this to recent `master`.

**Review by sfan5 — APPROVED** [review]
LGTM
