### PR TITLE
Scale culler steps proportionally to the mesh sizes

### LINKED ISSUE #13224: Infinite view range no longer works
##### Minetest version
```
5.7.0-dev latest master
```
##### OS / Hardware
GPU model: AMD Radeon RX 560
OpenGL version: 4.6

##### Summary
Infinite view range no longer works after commit https://github.com/minetest/minetest/commit/2715cc8bf68a2cc8cd583cd5b0bb732ee13a1b49. It should show all loaded mapblocks independent of the viewing range set.

##### Steps to reproduce
Turn up the view range really high and fly around for a bit. Enable infinite view range and turn down the view range. All previously loaded parts of the terrain should be visible, but aren't.

### PR DESCRIPTION
**Pull request by x2048**
This is an attempt to make culler work faster at larger sizes of client_mesh_chunk and larger view ranges.

The PR also includes the following:
* raytraced occlusion culling is disabled for mesh chunk sizes of 4x4x4 and larger due to high cost

## To do

This PR is Ready for review

## How to test

* Tune client_mesh_chunk and view_range according to the table below
* Start the game
* updateDrawList should take reasonable time(~10-15ms)

| client_mesh_chunk | view_range |
|----|------------------|
| 1 | 125 |
| 2 | 250 |
| 4 | 500 | 
| 8 | 1000 |

### CODE REVIEW

**Comment by x2048** [comment]
@lhofhansl Can you check if it improves the culler performance in your setup?

**Comment by lhofhansl** [comment]
Hmm... With viewing_range 700, this culler seems to start off better, staying below 10, but then as more and more blocks are loaded it takes 70-75ms. Without this PR the worst case is 21ms. So there now seems to be some bad behavior when many blocks are loaded.

**Comment by lhofhansl** [comment]
Without PR:
screenshot_20230224_181215

With PR:
screenshot_20230224_181919

**Comment by lhofhansl** [comment]
With fewer blocks, this PR seems to be better.

**Comment by x2048** [comment]
Is it a client_mesh_chunk = 8?

**Comment by lhofhansl** [comment]
Yes... Sorry forgot to mention. client_mesh_chunk = 8

**Comment by x2048** [comment]
I've noticed that `enable_raytraced_culling` impacts the performance significantly and does little good with `client_mesh_chunk` 4 and above. I'm going to disable it unconditionally for these chunk sizes.

**Comment by lhofhansl** [comment]
Now it's pretty cool. updateDrawList stays below 0.6ms (where it was over 70ms before, and 21ms without this PR).
Nice. Is the raytraced culler useful for 2x2x2 meshes?

**Comment by lhofhansl** [comment]
And infinite range work too. Good looks good.

**Comment by lhofhansl** [comment]
Now `updateDrawListShadow` and `touchMapBlocks` are the most expensive non-drawing operations.

**Comment by x2048** [comment]
Yes, the culler still helps for 2x2x2 meshes.

**Review by lhofhansl — APPROVED** [review]

**Comment by lhofhansl** [comment]
Would be good to get this one in. @sfan5 I think this is waiting for a review from you.

File: src/client/clientmap.cpp [hunk 1]
```diff
@@ -553,17 +567,24 @@ void ClientMap::touchMapBlocks()
...
+				range >	m_control.wanted_range * BS + mesh_sphere_radius)
 				continue; // Out of range, skip.
 
 			// Keep the block alive as long as it is in range.
 			block->resetUsageTimer();
 			blocks_in_range_with_mesh++;
 		}
 	}
+
+	m_control.loaded_range = loaded_range / BS;
```
Comment (sfan5) [inline src/client/clientmap.cpp:586]: what's this used for?

Comment (x2048) [reply src/client/clientmap.cpp:586]: This is the limit for "unlimited view range" in updateDrawList

Comment (sfan5) [reply src/client/clientmap.cpp:586]: Is the reason for this limit that the culler can't possibly operate on the entire map?
or could we just pass 65536 to `getBlocksInViewRange`?

Comment (lhofhansl) [reply src/client/clientmap.cpp:586]: This is needed to limit the search-space, otherwise we'd recurse unnecessarily through many un-loaded (and assumed-transparent) blocks.

@x2048 Now that I look at the code again... A simple style nit is to always pass the range to `getBlocksInViewRange` and remove the -1.0f default and handling. The it could even be made static (if only to indicate that it does not access any members.)

Comment (sfan5) [reply src/client/clientmap.cpp:586]: I'm wondering: If the culler does not traverse the entire world how does it know where the farthest-out block is?

In any case this does actually work in practice...

**Comment by sfan5** [comment]
...however it's way too slow (this isn't even that many blocks):
grafik

**Comment by sfan5** [comment]
I think we may have to revive #13225.

File: src/client/clientmap.cpp (hunk 1 above)
Comment (x2048) [reply src/client/clientmap.cpp:586]: The culler traverses up to the loaded_range which is calculated from the blocks the are loaded

**Comment by lhofhansl** [comment]
We need this one too, because it significantly speeds up the normal (not-infinite) case.
I suggest we merge this one for the perf improvement. Then follow-up with speeding up the infinite case (which may or may not be a version of #13225)

**Comment by lhofhansl** [comment]
QQ: How far away is this, and what is your `client_mesh_size` setting?

File: src/client/clientmap.cpp (hunk 1 above)
Comment (Desour) [reply src/client/clientmap.cpp:586]: Traversing non-existing blocks infinitely far is not ok.
I've tried teleporting ca. 20000 nodes away with full view range enabled, and the game (as to expect) got completely hung up.

Possible solutions:
* Don't do any  occlusion checks at all if full view range is enabled, and only iterate through all existing blocks.
* Like above, but do occlusion checks for nearby blocks (for better performance in many situations).
* Do (new-style) occlusion testing per set of existing connected blocks: First, find all these sets of connected blocks (i.e. by traversing all existing blocks). Then, for each of these sets, start by considering all blocks that have non-existing blocks next to them towards the camera direction, and do the usual traversal from there (you might have to traverse sorted by distance now though, as blocks are no longer inserted in distance-sorted order). Don't traverse non-existing blocks. If full view range is disabled, do traverse non-existing blocks, as the end condition is view distance (which is small), not exhaustiveness of visited existing blocks.

**Comment by x2048** [comment]
I've now removed all the code related to infinite viewing range, so it only includes mesh grid optimizations for the culler.

> Traversing non-existing blocks infinitely far is not ok.
> I've tried teleporting ca. 20000 nodes away with full view range enabled, and the game (as to expect) got completely hung up.

There is a code that limits traveral to what's loaded, but teleporting between distant locations is definitely the worst case for the algorithm - you get a bounding box of ~ 20000^3 with a vast volume of no blocks inside. With the current implementation of map it is not possible to detect and walk through vast empty volumes efficiently. An octree could help.

> Don't do any occlusion checks at all if full view range is enabled, and only iterate through all existing blocks.
> Like above, but do occlusion checks for nearby blocks (for better performance in many situations).

This is roughly what #13225 does. 

> Do (new-style) occlusion testing per set of existing connected blocks: First, find all these sets of connected blocks (i.e. by traversing all existing blocks). Then, for each of these sets, start by considering all blocks that have non-existing blocks next to them towards the camera direction, and do the usual traversal from there (you might have to traverse sorted by distance now though, as blocks are no longer inserted in distance-sorted order). Don't traverse non-existing blocks. If full view range is disabled, do traverse non-existing blocks, as the end condition is view distance (which is small), not exhaustiveness of visited existing blocks.

I've tried a similar approach, but abandoned it because it did not really cull anything. The reason is that the algorithm relies on ignoring the subtrees of  blocks it decides should not be visited. If we force-queue all mesh-containing blocks from the sets, we essentially override the result.

**Comment by lhofhansl** [comment]
@x2048 Let's merge this already :)
I'll then rebase/fix #13225

File: src/client/clientmap.h [hunk 2]
```diff
@@ -143,6 +143,7 @@ class ClientMap : public Map, public scene::ISceneNode
 protected:
 	void reportMetrics(u64 save_time_us, u32 saved_blocks, u32 all_blocks) override;
 private:
+	bool isMeshOccluded(MapBlock *mesh_block, u16 mesh_size, v3s16 cam_pos_nodes);
```
Comment (sfan5) [inline src/client/clientmap.h:146]: one more sorry: can this be made static?

Comment (x2048) [reply src/client/clientmap.h]: Done.

**Review by sfan5 — APPROVED** [review]

**Comment by lhofhansl** [comment]
Wait... Is it static now or not? See the last commit was reverted.

**Comment by sfan5** [comment]
It's not, I noticed afterwards that it still needs access to class members so `static` doesn't make a whole lot of sense. Sorry.
