### PR TITLE
Enforce limits of settings that could cause buggy behaviour

### LINKED ISSUE #11738: Setting gui_scaling=128 in minetest.conf hangs entire computer
##### Minetest version
commit 80d12dbed

##### OS / Hardware

Operating system: GNU/Linux
CPU: Intel Core i7-8565U

GPU model: Intel something?
OpenGL version: 3.0?

##### Summary

Setting gui_scaling to 128 in minetest.conf the game hangs the entire computer upon starting.
(I used a high-end computer – a Thinkpad X390 – to test this, so that it is taken seriously.)

##### Steps to reproduce

1. Set gui_scaling to 128 in minetest.conf.
2. Start game.
3. Observe hang.
4. ???
5. Restart.

### LINKED ISSUE #11739: Setting gui_scaling=512 in minetest.conf makes game crash (division by zero)
##### Minetest version
commit 80d12dbed

##### OS / Hardware

Operating system: GNU/Linux
CPU: Intel Core i7-8565U

GPU model: Intel something?
OpenGL version: 3.0?

##### Summary

Setting gui_scaling to 512 in minetest.conf the game crashes (division by zero) upon starting.
(I used a high-end computer – a Thinkpad X390 – to test this, so that it is taken seriously.)

I think the crash happens here, near line 190 of `src/irrlicht_changes/CGUITTFont.cpp`:
```
	core::vector2di page_position(
		(page->used_slots % (texture_side_length / font_size)) * font_size,
		(page->used_slots / (texture_side_length / font_size)) * font_size
		);
```

I guess `font_size` became zero somehow?

##### Steps to reproduce

1. Set gui_scaling to 512 in minetest.conf.
2. Start game.
3. Observe crash.

### PR DESCRIPTION
**Pull request by SmallJoker**
Enforces the setting value bounds that are currently only limited by the GUI (settingtypes.txt).

See: #9000 and #11463

Fixes #11738 and fixes #11739

## To do

This PR is Ready for Review.

## How to test

1. Code review
2. Get creative

### CODE REVIEW

**Comment by Zughy** [comment]
This will fix #11738 and #11739

**Comment by appgurueu** [comment]
I don't like the duplication of these limits here.

File: builtin/mainmenu/dlg_contentstore.lua [hunk 1]
```diff
@@ -191,7 +191,7 @@ end
 
 local function queue_download(package, reason)
 	local max_concurrent_downloads = tonumber(core.settings:get("contentdb_max_concurrent_downloads"))
-	if number_downloading < max_concurrent_downloads then
+	if number_downloading < math.max(max_concurrent_downloads, 1) then
```
Comment (nerzhul) [inline builtin/mainmenu/dlg_contentstore.lua:194]: 0 or 1 ?

**Review by nerzhul — CHANGES_REQUESTED** [review]

File: builtin/mainmenu/dlg_contentstore.lua (hunk 1 above)
Comment (SmallJoker) [reply builtin/mainmenu/dlg_contentstore.lua:194]: 1. you want at least 1 download in the queue.

File: src/client/renderingengine.cpp [hunk 2]
```diff
@@ -633,7 +633,8 @@ float RenderingEngine::getDisplayDensity()
 
 float RenderingEngine::getDisplayDensity()
 {
-	return (g_settings->getFloat("screen_dpi") / 96.0) * g_settings->getFloat("display_density_factor");
+	return (std::max(g_settings->getFloat("screen_dpi"), 1.0f) / 96.0) *
+		g_settings->getFloat("display_density_factor");
```
Comment (sfan5) [inline src/client/renderingengine.cpp:637]: `display_density_factor` needs limiting too, the end result may not be zero or negative
(might be easier to just check that once before returning)

File: src/emerge.cpp [hunk 3]
```diff
@@ -169,8 +169,8 @@ EmergeManager::EmergeManager(Server *server, MetricsBackend *mb)
 		);
 	}
 
-	s16 nthreads = 1;
-	g_settings->getS16NoEx("num_emerge_threads", nthreads);
+	u16 nthreads = 1;
+	g_settings->getU16NoEx("num_emerge_threads", nthreads);
```
Comment (sfan5) [inline src/emerge.cpp:173]: better to change `nthreads == 0` to `nthreads <= 0` here

File: src/gui/guiFormSpecMenu.cpp [hunk 4]
```diff
@@ -3208,8 +3208,8 @@ void GUIFormSpecMenu::regenerateGui(v2u32 screensize)
 			offset = v2s32(0,0);
 		}
 
-		double gui_scaling = g_settings->getFloat("gui_scaling");
-		double screen_dpi = RenderingEngine::getDisplayDensity() * 96;
+		const double gui_scaling = rangelim(g_settings->getFloat("gui_scaling"), 0.5f, 42.0f);
```
Comment (sfan5) [inline src/gui/guiFormSpecMenu.cpp:3211]: this comes up a lot, maybe add a helper in some gui header that computes this

File: src/map.cpp [hunk 5]
```diff
@@ -340,7 +341,7 @@ void Map::timerUpdate(float dtime, float unload_timeout, u32 max_loaded_blocks,
 	beginSave();
 
 	// If there is no practical limit, we spare creation of mapblock_queue
-	if (max_loaded_blocks == U32_MAX) {
+	if (max_loaded_blocks < 0) {
```
[the remark this answers is not in the document]
Comment (SmallJoker) [reply src/map.cpp:344]: This setting explicitly accepts the negative value `-1` which was then converted to an unsigned 32-bit integer. This change is the most straight-forward to handle all negative values instead of silently letting `-2` and alikes "underflow" during the cast. Even though that would result in a very high limit, the code should still skip unneeded calculations in that case and assume negative values are used to disable the limit.

File: src/gui/guiFormSpecMenu.cpp (hunk 4 above)
Comment (SmallJoker) [reply src/gui/guiFormSpecMenu.cpp]: :heavy_check_mark:

**Comment by Zughy** [comment]
Will this also take care of #8979 (and #11740) ?

**Comment by SmallJoker** [comment]
@Zughy A future PR might. After this one is merged, I will update that issue accordingly.

File: src/map.cpp (hunk 5 above)
[the remark this answers is not in the document]
Comment (sfan5) [reply src/map.cpp:344]: I see

File: src/client/camera.cpp [hunk 6]
```diff
@@ -75,11 +75,11 @@ Camera::Camera(MapDrawControl &draw_control, Client *client, RenderingEngine *re
 	 *       (as opposed to the this local caching). This can be addressed in
 	 *       a later release.
 	 */
-	m_cache_fall_bobbing_amount = g_settings->getFloat("fall_bobbing_amount");
-	m_cache_view_bobbing_amount = g_settings->getFloat("view_bobbing_amount");
+	m_cache_fall_bobbing_amount = g_settings->getFloat("fall_bobbing_amount", 0.0f, 100.0f);
```
Comment (rubenwardy) [inline src/client/camera.cpp:78]: settingtypes.txt only has a min of 0, it's worth adding a max there too

File: src/client/camera.cpp [hunk 7]
```diff
@@ -75,11 +75,11 @@ Camera::Camera(MapDrawControl &draw_control, Client *client, RenderingEngine *re
...
+	m_cache_view_bobbing_amount = g_settings->getFloat("view_bobbing_amount", 0.0f, 7.9f);
 	// 45 degrees is the lowest FOV that doesn't cause the server to treat this
 	// as a zoom FOV and load world beyond the set server limits.
-	m_cache_fov                 = std::fmax(g_settings->getFloat("fov"), 45.0f);
+	m_cache_fov                 = g_settings->getFloat("fov", 45.0f, 180.0f);
```
Comment (rubenwardy) [inline src/client/camera.cpp:82]: settingtypes.txt has max as 160

File: src/client/hud.cpp [hunk 8]
```diff
@@ -55,7 +55,7 @@ Hud::Hud(Client *client, LocalPlayer *player,
 	this->player      = player;
 	this->inventory   = inventory;
 
-	m_hud_scaling      = g_settings->getFloat("hud_scaling");
+	m_hud_scaling      = std::max(g_settings->getFloat("hud_scaling"), 0.1f);
```
Comment (rubenwardy) [inline src/client/hud.cpp:58]: shouldn't this be max 20 too?

File: src/client/renderingengine.cpp [hunk 9]
```diff
@@ -598,7 +598,7 @@ static float calcDisplayDensity()
 float RenderingEngine::getDisplayDensity()
 {
 	static float cached_display_density = calcDisplayDensity();
-	return cached_display_density * g_settings->getFloat("display_density_factor");
+	return std::max(cached_display_density * g_settings->getFloat("display_density_factor"), 0.01f);
```
Comment (rubenwardy) [inline src/client/renderingengine.cpp:601]: settingtypes for display_density_factor should be updated too

File: src/gui/guiTable.cpp [hunk 10]
```diff
@@ -84,7 +84,7 @@ GUITable::GUITable(gui::IGUIEnvironment *env,
 #endif
 	core::rect<s32> relative_rect = m_scrollbar->getRelativePosition();
 	s32 width = (relative_rect.getWidth() / (2.0 / 3.0)) * density *
-			g_settings->getFloat("gui_scaling");
+			std::max(g_settings->getFloat("gui_scaling"), 0.5f);
```
Comment (rubenwardy) [inline src/gui/guiTable.cpp:87]: max of 20 too?

File: src/gui/modalMenu.cpp [hunk 11]
```diff
@@ -40,7 +40,7 @@ GUIModalMenu::GUIModalMenu(gui::IGUIEnvironment* env, gui::IGUIElement* parent,
 		m_menumgr(menumgr),
 		m_remap_dbl_click(remap_dbl_click)
 {
-	m_gui_scale = g_settings->getFloat("gui_scaling");
+	m_gui_scale = std::max(g_settings->getFloat("gui_scaling"), 0.5f);
```
Comment (rubenwardy) [inline src/gui/modalMenu.cpp:43]: max of 20 too?

File: src/mapgen/mapgen.cpp [hunk 12]
```diff
@@ -1042,6 +1042,8 @@ void MapgenParams::readParams(const Settings *settings)
 	settings->getS16NoEx("chunksize", chunksize);
 	settings->getFlagStrNoEx("mg_flags", flags, flagdesc_mapgen);
 
+	chunksize = rangelim(chunksize, 1, 10);
```
Comment (rubenwardy) [inline src/mapgen/mapgen.cpp:1045]: settingtypes has limits of 1 and 5

**Comment by appgurueu** [comment]
Manually implementing this on the C++ side of things is error-prone code duplication. Couldn't C++ be made to read `settingtypes.txt` to apply the limits? Alternatively, C++ could use Lua to do the clamping to not duplicate the settingtypes reading code (create settings object -> read settingtypes -> do clamping / erroring).

**Comment by SmallJoker** [comment]
@appgurueu Could? Yes sure, it's possible if someone's willing to spend their time on it. A similar attempt (but much more into depth) was made in #6728.
In the future, a `Settings` could (for example) have `std::map<settingname, const limitdata> limits` which is read from `settingtypes.txt` once, and looked up for each `getXXX` function call.

**Comment by SmallJoker** [comment]
PR updated with limits to fix #12493 because the relevant C++ line was touched anyway.

**Comment by Zughy** [comment]
@SmallJoker please don't go lower than the default, or people can still cheat of half a second per block if they know about the parameter

File: builtin/settingtypes.txt [hunk 13]
```diff
@@ -95,7 +95,7 @@ always_fly_fast (Always fly fast) bool true
 
 #    The time in seconds it takes between repeated node placements when holding
 #    the place button.
-repeat_place_time (Place repetition interval) float 0.25 0.001
+repeat_place_time (Place repetition interval) float 0.25 0.2 2
```
Comment (sfan5) [inline builtin/settingtypes.txt:98]: not 0.25?

File: src/client/renderingengine.cpp [hunk 14]
```diff
@@ -86,8 +86,8 @@ RenderingEngine::RenderingEngine(IEventReceiver *receiver)
 
 	// Resolution selection
 	bool fullscreen = g_settings->getBool("fullscreen");
-	u16 screen_w = g_settings->getU16("screen_w");
-	u16 screen_h = g_settings->getU16("screen_h");
+	u16 screen_w = std::max<u16>(g_settings->getU16("screen_w"), 1);
```
Comment (sfan5) [inline src/client/renderingengine.cpp:89]: this probably works
```suggestion
	u16 screen_w = std::max(g_settings->getU16("screen_w"), 1U);
```

File: src/map.cpp [hunk 15]
```diff
@@ -323,9 +323,10 @@ struct TimeOrderedMapBlock {
 /*
 	Updates usage timers
 */
-void Map::timerUpdate(float dtime, float unload_timeout, u32 max_loaded_blocks,
+void Map::timerUpdate(float dtime, float unload_timeout, s32 max_loaded_blocks,
 		std::vector<v3s16> *unloaded_blocks)
 {
+	unload_timeout = std::max(unload_timeout, 0.0f);
```
Comment (sfan5) [inline src/map.cpp:329]: there is a call where this is -1:
<pre>
src/map.cpp
464-
465-void Map::unloadUnreferencedBlocks(std::vector<v3s16> *unloaded_blocks)
466-{
467:	timerUpdate(0.0, -1.0, 0, unloaded_blocks);
468-}
469-
470-void Map::deleteSectors(std::vector<v2s16> &sectorList)
</pre>

File: builtin/settingtypes.txt (hunk 13 above)
Comment (appgurueu) [reply builtin/settingtypes.txt:98]: well, should the min be 5 or 4 placements per second?

Comment (sfan5) [reply builtin/settingtypes.txt:98]: I thought we wanted to minimum to be exactly as the default.

Comment (SmallJoker) [reply builtin/settingtypes.txt]: Done.

**Review by sfan5 — APPROVED** [review]
