### PR TITLE
Make formspec elements real elements for draw order and clipping

### LINKED ISSUE #8036: In formspecs dropdown lists drop down behind other elements
##### Issue type

 - Bug report
 
##### Minetest version

```
Minetest 0.4.17.1 (Linux)
Using Irrlicht 1.8.4
Build info: VER=0.4.17.1 BUILD_TYPE=Release RUN_IN_PLACE=0 USE_GETTEXT=1 USE_SOUND=1 USE_CURL=1 USE_FREETYPE=1 USE_LUAJIT=1 STATIC_SHAREDIR="/usr/share/minetest"
```

##### OS / Hardware

Operating system: Linux 4.19.12-arch1-1-ARCH x86_64
CPU: Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz

GPU model: NVIDIA Corporation GP104 [GeForce GTX 1080] (rev a1)
OpenGL version: 4.6.0 NVIDIA 415.2

##### Summary
When creating formspecs with dropdown lists the drop-down drops down behind other elements as shown here:

2018-12-31-021705_790x510_scrot

According to [the forum discussion](https://forum.minetest.net/viewtopic.php?t=21691) this seems to be a bug in how formspecs are created (mixed Irrlicht and custom elements).

##### Steps to reproduce
1. Install this minimal working example as mod.
    
    ~~~~
    minetest.register_node('test:test', {
        description = 'Test Node',
        tiles = { 'default_wood.png^[colorize:#ffff0055' },
        groups = { oddly_breakable_by_hand = 1 },
        after_place_node = function(pos, placer)
            local meta = minetest.get_meta(pos)
            meta:set_string('formspec', [[
            size[8,5]
            list[current_player;main;0,1;8,4;]
            dropdown[0,0;8;category;Item 1,Item 2,Item 3,Item 4,Item 5;1]
            ]])
        end,
    })
    ~~~~
2. Enable the mod and start a world
3. From creative inventory search `Test Node` and place it
4. Rightclick it to open the meta formspec
5. Use the drop-down

### PR DESCRIPTION
**Pull request by DS-Minetest**
- Currently the formspec element draw order can't be changed for most elements. This is because they are drawn manually.
Also the clipping doesn't work correctly for many elements.
- This PR implements (nearly) all formspec elements as real gui elements and fixes those issues.
- The changes are taken from #8591 to make that PR simpler. #4844 is related but not fixed. Lists are still drawn at last because changing this is more difficult, but they are clippable.
Closes #8036.

## To do

This PR is a Ready for Review.

## How to test

<details><summary>Here is some lua code for testing.</summary>

```lua
-- edit this formspec,
-- especially change the order of the elements,
-- then compare. also compare to master

local my_formspec =
	"formspec_version[3]".. -- comment this to test backwards compatibility
	"size[10,8]"..
	"real_coordinates[true]"..

	"button[2.5,0.5;1,1;bla;Bla]"..
	"box[0,0;3,2;#00ff00ff]"..
	"tooltip[bla;Blatt;#f00;#000]"..
	"style[button_noclip;noclip=true]"..
	"button[-1,2.5;3,1;button_noclip;Noclip Button]"..
	"style[field_noclip;noclip=true]"..
	"field[-0.5,2.8;2,1;field_noclip;noclip field;some default text]"..
	"box[1,1;1,2;#1111ff]"..
	"bgcolor[;true]"..
	"background[1.5,1;2,2;default_wood.png;true]"..

	-- here are more elements, uncomment and test them
	--~ "scrollbar[7.5,0;0.3,4;vertical;scrbar;0]"..
	--~ "pwdfield[2,2;1,1;baum2;Baum]"..
	--~ "list[current_player;main;4,4;1,5;]"..
	--~ "image[3,1;bubble.png]"..
	--~ "item_image[2,6;3,2;default:mese]"..
	--~ "label[2,15;bla baum\nfoo bar]"..
	--~ "textarea[2,10;5,6;txtarea;Baum;bla]"..
	--~ "item_image_button[2,3;1,1;default:dirt_with_grass;itemimagebutton;ItemImageButton]"..
	--~ "tooltip[0,11;3,2;Blatt;#f00;#000]".."box[0,11;3,2;#00ff00]"..
	--~ "checkbox[2,25;chb;ChB;false]",
	--~ "bgcolor[#aa0a]"..
	--~ "tablecolumns[text,bla]"..
	--~ "table[1,23;3,1;tbl;a,b,c,d;2]"..
	--~ "textlist[0,5;2,0.5;txtlst;a,b,c]"..
	--~ "dropdown[0,6;2;hmdrpdwn;apfel,birne;1]"..
	--~ "tabheader[-1,9;mytabheader;a,b,c;2;false;false]"..
	--~ "background[5,5;1,1;testbg.png;true;10]"..
	""


minetest.register_on_player_receive_fields(function(player, formname, fields)
	if formname ~= "my_formspec" then
		print("other formname: "..formname)
		return
	end
	print(dump(fields))
end)


minetest.register_node("test:node", {
	description = "test node",
	tiles = {"default_wood.png^heart.png"},
	groups = {choppy = 3, oddly_breakable_by_hand = 3},
	on_rightclick = function(pos, node, clicker, itemstack, pointed_thing)
		minetest.show_formspec(clicker:get_player_name(), "my_formspec", my_formspec)
	end,
})
```
</details>

(Note that you might also want to test using `style`.)

### CODE REVIEW

**Comment by rubenwardy** [comment]
The how to test section is intended to be used to show test code. Please test using a mod which demonstrates reordering

**Comment by DS-Minetest** [comment]
Sorry, done.

**Comment by DS-Minetest** [comment]
Rebased.

File: src/gui/guiItemImage.h [hunk 1]
```diff
@@ -0,0 +1,47 @@
...
+public:
+	GUIItemImage(gui::IGUIEnvironment *env, gui::IGUIElement *parent, s32 id,
+		const core::rect<s32> &rectangle, const std::string &item_name,
+		gui::IGUIFont *font, Client *client);
+
+	virtual void draw();
+
+	virtual void setText(const wchar_t *text)
+	{
+		m_label = core::stringw();
```
Comment (red-001) [inline src/gui/guiItemImage.h]: `irr::core::string` seems a have a assignment operator for c-style strings so you should be able to just do
```suggestion
		m_label = text;
```

Comment (DS-Minetest) [reply src/gui/guiItemImage.h]: Thanks!
(I wonder, why I did that. I thought, this was copied from somewhere, but no.)

File: src/client/guiscalingfilter.h [hunk 2]
```diff
@@ -53,4 +53,5 @@ void draw2DImageFilterScaled(video::IVideoDriver *driver, video::ITexture *txr,
  * 9-slice / segment drawing
  */
 void draw2DImage9Slice(video::IVideoDriver *driver, video::ITexture *texture,
-		const core::rect<s32> &rect, const core::rect<s32> &middle);
+		const core::rect<s32> &rect, const core::rect<s32> &middle,
+		const core::rect<s32> *cliprect = 0);
```
[the remark this answers is not in the document]
Comment (DS-Minetest) [reply src/client/guiscalingfilter.h]: Done.

File: src/gui/guiFormSpecMenu.cpp [hunk 3]
```diff
@@ -1806,35 +1913,45 @@ void GUIFormSpecMenu::parseItemImageButton(parserData* data, const std::string &
...
-			pos = getElementBasePos(true, &v_pos);
+		// the spec for the item-image
+		FieldSpec speci(
+			"",
+			L"",
+			L"",
+			258 + m_fields.size()
+		);
+
+		GUIItemImage *e2 = new GUIItemImage(Environment, e, speci.fid,
```
Comment (rubenwardy) [inline src/gui/guiFormSpecMenu.cpp]: bad name, use `e_img` or smth

File: src/gui/guiFormSpecMenu.cpp [hunk 4]
```diff
@@ -1806,35 +1913,45 @@ void GUIFormSpecMenu::parseItemImageButton(parserData* data, const std::string &
...
+		// the spec for the button
+		FieldSpec specb(
 			name,
 			utf8_to_wide(label),
 			utf8_to_wide(item_name),
 			258 + m_fields.size()
 		);
 
-		gui::IGUIButton *e = Environment->addButton(rect, this, spec.fid, L"");
+		gui::IGUIButton *e = Environment->addButton(rect, this, specb.fid, L"");
```
Comment (rubenwardy) [inline src/gui/guiFormSpecMenu.cpp]: `e_btn`

**Comment by rubenwardy** [comment]
Buttons have disappeared from the scrollbar:

image


(this is with /formspec on minimal dev test)

File: src/gui/guiFormSpecMenu.cpp [hunk 5]
```diff
@@ -507,7 +534,8 @@ void GUIFormSpecMenu::parseCheckbox(parserData* data, const std::string &element
 			Environment->setFocus(e);
 		}
 
-		m_checkboxes.emplace_back(spec,e);
+		e->grab();
```
[the remark this answers is not in the document]
Comment (DS-Minetest) [reply src/gui/guiFormSpecMenu.cpp]: Because of the complaints of stu, all pointers in `m_checkboxes`, `m_inventorylists` and co. are dropped when these containers are cleared. The `IGUICheckBox *` was not made with `new` but with an `add…` function. All pointers in `m_checkboxes` and co. are not only grabbed by the environment but also by the `GUIFormSpecMenu` code.

File: src/gui/guiFormSpecMenu.cpp [hunk 6]
```diff
@@ -641,17 +707,29 @@ void GUIFormSpecMenu::parseItemImage(parserData* data, const std::string &elemen
...
+		FieldSpec spec(
+			"",
+			L"",
+			L"",
+			258 + m_fields.size()
+		);
+
+		GUIItemImage *e = new GUIItemImage(Environment, this, spec.fid,
+				core::rect<s32>(pos, pos + geom), name,	m_font, m_client);
+		e->drop();
```
[the remark this answers is not in the document]
Comment (DS-Minetest) [reply src/gui/guiFormSpecMenu.cpp]: Yes, that's the reason.

File: src/gui/guiFormSpecMenu.cpp [hunk 7]
```diff
@@ -1046,14 +1145,14 @@ void GUIFormSpecMenu::parseDropDown(parserData* data, const std::string &element
...
-			258+m_fields.size()
+			258 + m_fields.size()
 		);
 
 		spec.ftype = f_DropDown;
 		spec.send = true;
 
 		//now really show list
-		gui::IGUIComboBox *e = Environment->addComboBox(rect, this,spec.fid);
+		gui::IGUIComboBox *e = Environment->addComboBox(rect, this, spec.fid);
```
[the remark this answers is not in the document]
Comment (DS-Minetest) [reply src/gui/guiFormSpecMenu.cpp]: It is not made with `new` or `create…`, but with `add…`. See http://irrlicht.sourceforge.net/docu/classirr_1_1_i_reference_counted.html#details.

**Comment by DS-Minetest** [comment]
(Huh, I didn't know about that chatcommand. >_<)

The error page seems to be Krock's fault, see https://github.com/minetest/minetest/pull/8731#issuecomment-519588432. (I wonder how he did that.)

File: src/gui/guiBackgroundImage.cpp [hunk 8]
```diff
@@ -0,0 +1,71 @@
+/*
+Minetest
+Copyright (C) 2013 celeron55, Perttu Ahola <celeron55@gmail.com>
```
[the remark this answers is not in the document]
Comment (DS-Minetest) [reply src/gui/guiBackgroundImage.cpp]: Actually, a big part of the code is from you, too. (The 9-slice background.)

I've copied from `guiVolumeChange.h`, done.

File: src/gui/guiBackgroundImage.h [hunk 9]
```diff
@@ -0,0 +1,39 @@
+/*
+Minetest
+Copyright (C) 2013 celeron55, Perttu Ahola <celeron55@gmail.com>
```
[the remark this answers is not in the document]
Comment (DS-Minetest) [reply src/gui/guiBackgroundImage.h]: Done

File: src/gui/guiFormSpecMenu.cpp (hunk 3 above)
Comment (DS-Minetest) [reply src/gui/guiFormSpecMenu.cpp]: Done.

File: src/gui/guiFormSpecMenu.cpp (hunk 4 above)
Comment (DS-Minetest) [reply src/gui/guiFormSpecMenu.cpp]: Done.

**Comment by DS-Minetest** [comment]
The scrollbar buttons aren't there because they are set to not visible here:
https://github.com/minetest/minetest/blob/d1c27c7e8037e9f438741ee5f7d3b6bda22d22a0/src/gui/guiScrollBar.cpp#L422-L424
with this `border_size`:
https://github.com/minetest/minetest/blob/d1c27c7e8037e9f438741ee5f7d3b6bda22d22a0/src/gui/guiScrollBar.cpp#L337
(The scrollbar is not long enough relative to it's wideness.)

This will happen in other PRs that use the new scrollbar, too, like #8530.

Related: #8507 
>Notice in the second screenshot that the up/down arrow buttons are now automatically hidden when there is not enough space to fully accommodate them.

**Comment by DS-Minetest** [comment]
`box` is the one element that commonly overlaps, I could use [`sendToBack`](http://irrlicht.sourceforge.net/docu/classirr_1_1gui_1_1_i_g_u_i_element.html#a9b1880048e7542dbe289295de69e77cd) on boxes if there's not `real_coordinates`.

**Comment by DS-Minetest** [comment]
Rebased, the error window error is fixed.

**Comment by rubenwardy** [comment]
https://forum.minetest.net/viewtopic.php?t=23286

**Comment by Linuxdirk** [comment]
Just a quick question. Does it fix this?

https://github.com/minetest/minetest/issues/8036

**Comment by rubenwardy** [comment]
> Just a quick question. Does it fix this?

Yes, for all elements except inventory list items, as the actual rendering of items in inventory lists is done last

**Comment by DS-Minetest** [comment]
As #8036 is probably mostly fixed after this PR (except of with combination with inventory lists, which will make it a duplicate of #4844), I'll add an automatic close thing to this PR.

**Comment by Linuxdirk** [comment]
> mostly fixed after this PR (except of with combination with inventory lists

Since the combination with inventory lists is the only thing mentioned in said issue it is not fixed at all then? :smile:

**Comment by DS-Minetest** [comment]
> > mostly fixed after this PR (except of with combination with inventory lists
> 
> Since the combination with inventory lists is the only thing mentioned in said issue it is not fixed at all then? smile

Well, the title says "behind other elements".
That inventory lists are drawn first is already covered in #8036. Please, don't say, that your issue is a duplicate, we need to reach the status of being a game with a thousand issues. :slightly_smiling_face:

**Comment by DS-Minetest** [comment]
Rebased and made this a non-breaking change.
I've added a new function `GUIFormSpecMenu::legacySortElements` to sort the elements into old order (for fs version < 2).

File: src/gui/guiFormSpecMenu.cpp [hunk 10]
```diff
@@ -2648,16 +2802,27 @@ void GUIFormSpecMenu::regenerateGui(v2u32 screensize)
...
 	pos_offset = v2f32();
 
+	// used for formspec versions < 2
+	core::list<IGUIElement *>::Iterator legacy_sort_start = Children.getLast();
+
 	if (enable_prepends) {
 		// Backup the coordinates so that prepends can use the coordinates of choice.
 		bool rc_backup = mydata.real_coordinates;
-		bool version_backup = m_formspec_version;
+		u16 version_backup = m_formspec_version;
```
Comment (rubenwardy) [inline src/gui/guiFormSpecMenu.cpp]: this should be fixed on master before this PR is merged

File: src/gui/guiFormSpecMenu.cpp [hunk 11]
```diff
@@ -2707,6 +2872,66 @@ void GUIFormSpecMenu::regenerateGui(v2u32 screensize)
...
+void GUIFormSpecMenu::legacySortElements(core::list<IGUIElement *>::Iterator from)
+{
+	/*
+	 * The order was:
+	 * (0. background colors and backgrounds)
+	 * 1. boxes
+	 * 2. all normal elements (like buttons)
+	 * 3. images
+	 * 4. item images
+	 * 5. item lists (TODO)
```
Comment (rubenwardy) [inline src/gui/guiFormSpecMenu.cpp]: Is this needed given that the new system draws inv lists in front anyway? This would explain why this is todo

Comment (DS-Minetest) [reply src/gui/guiFormSpecMenu.cpp]: Yes, the lists are still drawn in front with this PR. But this should be fixed at some point, hence the todo.

**Comment by rubenwardy** [comment]
Segfault in main menu

```
0x00007ffff66ddda8 in __cxxabiv1::__dynamic_cast (src_ptr=0x5555564cede0, 
    src_type=0x555555d68438 <typeinfo for irr::gui::IGUIElement>, 
    dst_type=0x555555d6a300 <typeinfo for GUIBox>, src2dst=0)
    at /build/gcc/src/gcc/libstdc++-v3/libsupc++/dyncast.cc:68
68	/build/gcc/src/gcc/libstdc++-v3/libsupc++/dyncast.cc: No such file or directory.
(gdb) bt full
#0  0x00007ffff66ddda8 in __cxxabiv1::__dynamic_cast (src_ptr=0x5555564cede0, 
    src_type=0x555555d68438 <typeinfo for irr::gui::IGUIElement>, 
    dst_type=0x555555d6a300 <typeinfo for GUIBox>, src2dst=0)
    at /build/gcc/src/gcc/libstdc++-v3/libsupc++/dyncast.cc:68
        vtable = 0x7ffff7d566a8 <vtable for irr::gui::CGUITabControl+32>
        prefix = 0x7ffff7d56698 <vtable for irr::gui::CGUITabControl+16>
        whole_ptr = 0x5555564cede0
        whole_type = 0x0
        result = {dst_ptr = 0x0, 
          whole2dst = __cxxabiv1::__class_type_info::__unknown, 
          whole2src = __cxxabiv1::__class_type_info::__unknown, 
          dst2src = __cxxabiv1::__class_type_info::__unknown, 
          whole_details = 16}
        whole_vtable = 0x7ffff7d566a8 <vtable for irr::gui::CGUITabControl+32>
        whole_prefix = 0x7ffff7d56698 <vtable for irr::gui::CGUITabControl+16>
#1  0x000055555587df10 in GUIFormSpecMenu::legacySortElements(irr::core::list<irr::gui::IGUIElement*>::Iterator) ()
No symbol table info available.
#2  0x00005555558a2a57 in GUIFormSpecMenu::regenerateGui(irr::core::vector2d<unsigned int>) ()
No symbol table info available.
#3  0x0000555555896f86 in GUIFormSpecMenu::drawMenu() ()
No symbol table info available.
--Type <RET> for more, q to quit, c to continue without paging--
#4  0x00005555558ef128 in GUIModalMenu::draw() ()
No symbol table info available.
#5  0x00007ffff7bc7142 in irr::gui::CGUIStaticText::draw() () from /usr/lib/libIrrlicht.so.1.8
No symbol table info available.
#6  0x00007ffff7b73d5a in irr::gui::CGUIEnvironment::drawAll() () from /usr/lib/libIrrlicht.so.1.8
No symbol table info available.
#7  0x000055555587afb1 in GUIEngine::run() ()
No symbol table info available.
#8  0x000055555587bb30 in GUIEngine::GUIEngine(JoystickController*, irr::gui::IGUIElement*, IMenuManager*, MainMenuData*, bool&) ()
No symbol table info available.
#9  0x00005555557208b8 in ClientLauncher::main_menu(MainMenuData*) ()
No symbol table info available.
#10 0x00005555557217b3 in ClientLauncher::launch_game(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, bool, GameParams&, Settings const&) ()
No symbol table info available.
#11 0x0000555555723d12 in ClientLauncher::run(GameParams&, Settings const&) ()
No symbol table info available.
#12 0x00005555556f85e9 in main ()
No symbol table info available.
```

**Comment by DS-Minetest** [comment]
The rect of inventory lists is now calculated correctly:
screenshot_20190915_185104
Thanks for testing!

**Comment by rubenwardy** [comment]
```
Thread 1 "minetest" received signal SIGSEGV, Segmentation fault.
irr::core::list<irr::gui::IGUIElement*>::Iterator::operator++ (this=0x7fffffffc9f8) at /usr/include/irrlicht/irrList.h:45
45			Iterator  operator ++(s32) { Iterator tmp = *this; Current = Current->Next; return tmp; }
(gdb) bt full
#0  irr::core::list<irr::gui::IGUIElement*>::Iterator::operator++ (this=0x7fffffffc9f8) at /usr/include/irrlicht/irrList.h:45
        tmp = {Current = 0x0}
#1  0x0000555555d60968 in GUIFormSpecMenu::regenerateGui (this=0x555556b402d0, screensize=...) at /home/ruben/dev/minetest/src/gui/guiFormSpecMenu.cpp:2878
        mydata = {explicit_size = false, real_coordinates = false, invsize = {X = 0, Y = 0}, size = {X = 100, Y = 100}, offset = {X = 0.5, Y = 0.5}, anchor = {X = 0.5, Y = 0.5}, rect = {
            UpperLeftCorner = {X = 0, Y = 0}, LowerRightCorner = {X = 0, Y = 0}}, basepos = {X = 139, Y = 145}, screensize = {X = 858, Y = 591}, focused_fieldname = "", 
          table_options = std::vector of length 0, capacity 0, table_columns = std::vector of length 0, capacity 0, table_dyndata = std::unordered_map with 0 elements}
        focused_element = 0x555556b402d0
        __PRETTY_FUNCTION__ = "virtual void GUIFormSpecMenu::regenerateGui(v2u32)"
        elements = std::vector of length 1, capacity 1 = {""}
        i = 1
        enable_prepends = true
        skin = 0x55555694c180
        old_font = 0x555556b295a0
        legacy_sort_start = {Current = 0x0}
#2  0x0000555555da9749 in GUIModalMenu::draw (this=0x555556b402d0) at /home/ruben/dev/minetest/src/gui/modalMenu.cpp:76
        driver = 0x5555568d6520
        screensize = {X = 858, Y = 591}
#3  0x00007ffff7bc7142 in irr::gui::CGUIStaticText::draw() () from /usr/lib/libIrrlicht.so.1.8
No symbol table info available.
#4  0x00007ffff7b73d5a in irr::gui::CGUIEnvironment::drawAll() () from /usr/lib/libIrrlicht.so.1.8
No symbol table info available.
#5  0x0000555555d47390 in GUIEngine::run (this=0x7fffffffd070) at /home/ruben/dev/minetest/src/gui/guiEngine.cpp:296
        current_screen_size = @0x5555568d6620: {Width = 858, Height = 591}
        driver = 0x5555568d6520
        text_height = 20
        previous_screen_size = {Width = 858, Height = 591}
        sky_color = {color = 4287412986}
#6  0x0000555555d467be in GUIEngine::GUIEngine (this=0x7fffffffd070, joystick=0x555556b268c8, parent=0x555556a30f10, menumgr=0x55555646fc60 <g_menumgr>, data=0x7fffffffd310, 
    kill=@0x5555564a2800: false) at /home/ruben/dev/minetest/src/gui/guiEngine.cpp:196
        soundfetcher = {<OnDemandSoundFetcher> = {_vptr.OnDemandSoundFetcher = 0x5555563ff668 <vtable for MenuMusicFetcher+16>}, m_fetched = std::set with 1 element = {[0] = "main_menu"}}
        rect = {UpperLeftCorner = {X = 4, Y = 0}, LowerRightCorner = {X = 4, Y = 20}}
        soundfetcher = <optimized out>
        rect = <optimized out>
        texture = <optimized out>
        __for_range = <optimized out>
        __for_begin = <optimized out>
        __for_end = <optimized out>
        e = <optimized out>
#7  0x0000555555bf2d6d in ClientLauncher::main_menu (this=0x7fffffffdbe0, menudata=0x7fffffffd310) at /home/ruben/dev/minetest/src/client/clientlauncher.cpp:560
        kill = 0x5555564a2800 <porting::g_killed>
        driver = 0x5555568d6520
        mymenu = {_vptr.GUIEngine = 0x5555563ff648 <vtable for GUIEngine+16>, m_parent = 0x555556a30f10, m_menumanager = 0x55555646fc60 <g_menumgr>, m_smgr = 0x555556b1b0f0, 
          m_data = 0x7fffffffd310, m_texture_source = 0x555556b3fc50, m_sound_manager = 0x555556b400e0, m_formspecgui = 0x555556b3fbd0, m_buttonhandler = 0x555556b400a0, 
          m_menu = 0x555556b402d0, m_kill = @0x5555564a2800, m_startgame = false, m_script = 0x555556b3a430, m_scriptdir = "/home/ruben/dev/minetest/bin/../builtin/mainmenu", m_textures = {
            {texture = 0x0, tile = false, minsize = 0}, {texture = 0x0, tile = 128, minsize = 32767}, {texture = 0x555556b28b90, tile = false, minsize = 16}, {texture = 0x0, tile = 192, 
              minsize = 32767}}, m_irr_toplefttext = 0x555556a092b0, m_toplefttext = {m_string = L"Minetest Game", m_colors = std::vector of length 13, capacity 16 = {{color = 4294967295}, 
              {color = 4294967295}, {color = 4294967295}, {color = 4294967295}, {color = 4294967295}, {color = 4294967295}, {color = 4294967295}, {color = 4294967295}, {
                color = 4294967295}, {color = 4294967295}, {color = 4294967295}, {color = 4294967295}, {color = 4294967295}}, m_has_background = false, m_background = {color = 0}}, 
          m_clouds_enabled = true, m_cloud = {dtime = 0.0340000018, lasttime = 193, clouds = 0x555556509a90, camera = 0x5555569d80d0}}
#8  0x0000555555bf1e00 in ClientLauncher::launch_game (this=0x7fffffffdbe0, error_message="", reconnect_requested=false, game_params=..., cmd_args=...)
    at /home/ruben/dev/minetest/src/client/clientlauncher.cpp:424
        newport = 32767
        worldspecs = std::vector of length -35394917066724837, capacity -87413170238280657 = {<error reading variable worldspecs (Cannot access memory at address 0x74752e42475f6e65)>
        menudata = {servername = "", serverdescription = "", address = "", port = "30000", name = "rubenwardy", password = "", do_reconnect = false, selected_world = 0, 
          simple_singleplayer_mode = false, script_data = {reconnect_requested = false, errormessage = ""}}
--Type <RET> for more, q to quit, c to continue without paging--
        __PRETTY_FUNCTION__ = "bool ClientLauncher::launch_game(std::string&, bool, GameParams&, const Settings&)"
#9  0x0000555555bf0654 in ClientLauncher::run (this=0x7fffffffdbe0, game_params=..., cmd_args=...) at /home/ruben/dev/minetest/src/client/clientlauncher.cpp:218
        game_has_run = false
        text = 0x555556b3ffb0 L"\x55ee4310啕\x55eb2506啕\x55ee05e8啕\x61754c\x656c61\060"
        __PRETTY_FUNCTION__ = "bool ClientLauncher::run(GameParams&, const Settings&)"
        camera = 0x555556b33d40
        chat_backend = {m_console_buffer = {m_scrollback = 500, m_unformatted = std::vector of length 0, capacity 0, m_cols = 0, m_rows = 0, m_scroll = 0, 
            m_formatted = std::vector of length 0, capacity 0, m_empty_formatted_line = {fragments = std::vector of length 0, capacity 0, first = true}}, m_recent_buffer = {
            m_scrollback = 6, m_unformatted = std::vector of length 0, capacity 0, m_cols = 0, m_rows = 0, m_scroll = 0, m_formatted = std::vector of length 0, capacity 0, 
            m_empty_formatted_line = {fragments = std::vector of length 0, capacity 0, first = true}}, m_prompt = {m_prompt = L"]", m_line = L"", 
            m_history = std::vector of length 0, capacity 0, m_history_index = 0, m_history_limit = 500, m_cols = 0, m_view = 0, m_cursor = 0, m_cursor_len = 0, 
            m_nick_completion_start = 0, m_nick_completion_end = 0}}
        error_message = ""
        reconnect_requested = false
        first_loop = true
        retval = true
        kill = 0x5555564a2800 <porting::g_killed>
#10 0x000055555602230b in main (argc=1, argv=0x7fffffffdf58) at /home/ruben/dev/minetest/src/main.cpp:217
        retval = 21845
        cmd_args = {m_settings = std::unordered_map with 0 elements, m_defaults = std::unordered_map with 0 elements, m_callbacks = std::unordered_map with 0 elements, 
          m_callback_mutex = {<std::__mutex_base> = {_M_mutex = {__data = {__lock = 0, __count = 0, __owner = 0, __nusers = 0, __kind = 0, __spins = 0, __elision = 0, __list = {
                    __prev = 0x0, __next = 0x0}}, __size = '\000' <repeats 39 times>, __align = 0}}, <No data fields>}, m_mutex = {<std::__mutex_base> = {_M_mutex = {__data = {__lock = 0, 
                  __count = 0, __owner = 0, __nusers = 0, __kind = 0, __spins = 0, __elision = 0, __list = {__prev = 0x0, __next = 0x0}}, __size = '\000' <repeats 39 times>, 
                __align = 0}}, <No data fields>}}
        cmd_args_ok = true
        game_params = {socket_port = 30000, world_path = "/home/ruben/dev/minetest/bin/../worlds/world", game_spec = {id = "minetest", name = "Minetest Game", author = "Minetest", 
            release = 0, path = "/home/ruben/dev/minetest/bin/../games/minetest_game", gamemods_path = "/home/ruben/dev/minetest/bin/../games/minetest_game/mods", 
            addon_mods_paths = std::set with 1 element = {[0] = "/home/ruben/dev/minetest/bin/../mods"}, 
            menuicon_path = "/home/ruben/dev/minetest/bin/../games/minetest_game/menu/icon.png"}, is_dedicated_server = false}
        isServer = false
        __PRETTY_FUNCTION__ = "int main(int, char**)"
        launcher = {list_video_modes = false, skip_main_menu = false, use_freetype = true, random_input = false, address = "", playername = "rubenwardy", password = "", 
          input = 0x555556b268c0, receiver = 0x7fffe800bbd0, skin = 0x55555694c180, font = 0x0, gamespec = {id = "", name = "", author = "", release = 0, path = "", gamemods_path = "", 
            addon_mods_paths = std::set with 0 elements, menuicon_path = ""}, worldspec = {path = "/home/ruben/dev/minetest/bin/../worlds/world", name = "[--world parameter] [new]", 
            gameid = "minetest"}, simple_singleplayer_mode = false, current_playername = "inv£lid", current_password = "", current_address = "does-not-exist", current_port = 0}
```

**Comment by DS-Minetest** [comment]
The bugs should be fixed now.

**Comment by jastevenson303** [comment]
Tested with Lavaland, quickly.

Noticed that I was unable to use the [List] [Ok] buttons or type a name in the field on this formspec (beds)
screenshot_20190916_045511  The other buttons and checkbox work, however.

Formspecs look different?  A regular field:
screenshot_20190916_045451

File: src/gui/guiBackgroundImage.h [hunk 12]
```diff
@@ -0,0 +1,37 @@
+/*
+Part of Minetest
```
Comment (ClobberXD) [inline src/gui/guiBackgroundImage.h]: Why `part of`? Other files just have `Minetest`.

File: src/gui/guiBox.cpp [hunk 13]
```diff
@@ -0,0 +1,38 @@
...
+{
+}
+
+void GUIBox::draw()
+{
+	if (!IsVisible)
+		return;
+
+	Environment->getVideoDriver()->draw2DRectangle(
+			m_color, AbsoluteRect, &AbsoluteClippingRect);
```
Comment (ClobberXD) [inline src/gui/guiBox.cpp]: Extra indent

File: src/gui/guiFormSpecMenu.cpp [hunk 14]
```diff
@@ -395,7 +394,35 @@ void GUIFormSpecMenu::parseList(parserData* data, const std::string &element)
 
 		if(!data->explicit_size)
 			warningstream<<"invalid use of list without a size[] element"<<std::endl;
-		m_inventorylists.emplace_back(loc, listname, pos, geom, start_i, data->real_coordinates);
+
+		FieldSpec spec(
+			"",
+			L"",
+			L"",
+			258 + m_fields.size()
```
Comment (ClobberXD) [inline src/gui/guiFormSpecMenu.cpp]: Couldn't these be placed in one line?

**Comment by DS-Minetest** [comment]
Thanks for testing, @jastevenson303!
The first bug should actually already be fixed by https://github.com/minetest/minetest/pull/8740/commits/6055a5f7b32c36232e49d366c09fb5bb169d9fc9. Did you test with the newest version of this PR?
I can reproduce the second thing and will look into it.

File: src/gui/guiFormSpecMenu.cpp [hunk 15]
```diff
@@ -1235,21 +1338,26 @@ void GUIFormSpecMenu::createTextField(parserData *data, FieldSpec &spec,
...
 		rect.UpperLeftCorner.Y -= font_height;
 		rect.LowerRightCorner.Y = rect.UpperLeftCorner.Y + font_height;
-		gui::StaticText::add(Environment, spec.flabel.c_str(), rect, false, true,
-			this, 0);
+		IGUIElement *t = gui::StaticText::add(Environment, spec.flabel.c_str(),
+				rect, false, true, this, 0);
+
+		if (t) {
+			t->setNotClipped(style.getBool(StyleSpec::NOCLIP, false));
+		}
```
Comment (ClobberXD) [inline src/gui/guiFormSpecMenu.cpp]: Braces :D

File: src/gui/guiFormSpecMenu.cpp [hunk 16]
```diff
@@ -2760,9 +2991,9 @@ GUIFormSpecMenu::ItemSpec GUIFormSpecMenu::getItemAtPos(v2s32 p) const
 				y = (i/s.geom.X) * spacing.Y;
 			}
 			v2s32 p0(x,y);
-			core::rect<s32> rect = imgrect + s.pos + p0;
-			if(rect.isPointInside(p))
-			{
+			core::rect<s32> rect = imgrect + base_pos + p0;
+			rect.clipAgainst(clipping_rect);
+			if (rect.getArea() > 0 && rect.isPointInside(p)) {
```
Comment (ClobberXD) [inline src/gui/guiFormSpecMenu.cpp]: Braces :D

**Comment by DS-Minetest** [comment]
The simple field is now fixed.

**Comment by jastevenson303** [comment]
This is with ad4b58dd93ae2bd9dcf7786bcb3e2c57bdf48659 @DS-Minetest

**Comment by DS-Minetest** [comment]
@jastevenson303 I think, the problem is that you have set the height to 4 but the inventory only has a size to allow a height of 3. Therefor the list overlaps with invisible slots.
I'd suggest to change the 4 [here](https://github.com/jastevenson303/Lavaland/blob/f06266f693e07f8f8a732e62442af06c2230d1eb/mods/beds/api.lua#L142) to a 3.

I'm not sure how I could fix such things.

File: src/gui/guiFormSpecMenu.cpp [hunk 17]
```diff
@@ -3346,7 +3468,7 @@ void GUIFormSpecMenu::acceptInput(FormspecQuitMode quitmode=quit_mode_no)
 				else if (s.ftype == f_TabHeader) {
 					// no dynamic cast possible due to some distributions shipped
 					// without rttzi support in irrlicht
-					IGUIElement * element = getElementFromId(s.fid);
+					IGUIElement * element = getElementFromId(s.fid, true);
```
[the remark this answers is not in the document]
Comment (DS-Minetest) [reply src/gui/guiFormSpecMenu.cpp]: Done.
(Github can be weird sometimes. Why does it show the number 3471 up there? My editor says 3470 (and it starts counting at 1). The change suggestion also says 3470:
2019-09-16-183836_1920x1080_scrot)

File: src/gui/guiFormSpecMenu.cpp [hunk 18]
```diff
@@ -3361,7 +3483,7 @@ void GUIFormSpecMenu::acceptInput(FormspecQuitMode quitmode=quit_mode_no)
 				else if (s.ftype == f_CheckBox) {
 					// no dynamic cast possible due to some distributions shipped
 					// without rtti support in irrlicht
-					IGUIElement * element = getElementFromId(s.fid);
+					IGUIElement * element = getElementFromId(s.fid, true);
```
[the remark this answers is not in the document]
Comment (DS-Minetest) [reply src/gui/guiFormSpecMenu.cpp]: Done.

File: src/gui/guiFormSpecMenu.cpp [hunk 19]
```diff
@@ -3377,13 +3499,12 @@ void GUIFormSpecMenu::acceptInput(FormspecQuitMode quitmode=quit_mode_no)
...
 					// no dynamic cast possible due to some distributions shipped
 					// without rtti support in irrlicht
-					IGUIElement * element = getElementFromId(s.fid);
-					gui::IGUIScrollBar *e = NULL;
-					if ((element) && (element->getType() == gui::EGUIET_SCROLL_BAR)) {
-						e = static_cast<gui::IGUIScrollBar*>(element);
-					}
+					IGUIElement *element = getElementFromId(s.fid, true);
+					GUIScrollBar *e = nullptr;
+					if ((element) && (element->getType() == gui::EGUIET_ELEMENT))
```
[the remark this answers is not in the document]
Comment (DS-Minetest) [reply src/gui/guiFormSpecMenu.cpp]: Done.

File: src/gui/guiFormSpecMenu.cpp [hunk 20]
```diff
@@ -4176,6 +4295,17 @@ std::string GUIFormSpecMenu::getNameByID(s32 id)
 	return "";
 }
 
+
+FormspecFieldType GUIFormSpecMenu::getTypeByID(s32 id)
+{
+	for (FieldSpec &spec : m_fields) {
+		if (spec.fid == id) {
```
[the remark this answers is not in the document]
Comment (DS-Minetest) [reply src/gui/guiFormSpecMenu.cpp]: The function was copied from `getNameByID`. I've removed braces there and in the other function, too.
I've kept the outer `for` braces:
>Also, use braces when a loop contains more than a single simple statement:

https://www.kernel.org/doc/html/latest/process/coding-style.html#placing-braces-and-spaces

File: src/network/networkprotocol.h [hunk 21]
```diff
@@ -228,6 +228,7 @@ with this program; if not, write to the Free Software Foundation, Inc.,
 	FORMSPEC VERSION 2:
 		Forced real coordinates
 		background[]: 9-slice scaling parameters
+		Formspec elements are drawn in correct order
```
[the remark this answers is not in the document]
Comment (DS-Minetest) [reply src/network/networkprotocol.h]: Done.

File: src/client/guiscalingfilter.cpp [hunk 22]
```diff
@@ -224,7 +225,7 @@ void draw2DImage9Slice(video::IVideoDriver *driver, video::ITexture *texture,
 
 			draw2DImageFilterScaled(driver, texture, dest,
 					src,
-					NULL/*&AbsoluteClippingRect*/, colors, true);
+					cliprect, colors, true);
```
[the remark this answers is not in the document]
Comment (DS-Minetest) [reply src/client/guiscalingfilter.cpp]: When I see something weird, I always think that there's a reason behind it, else it wouldn't be done like this. Therefor I had not changed this.
Done.

File: src/gui/guiBackgroundImage.cpp [hunk 23]
```diff
@@ -0,0 +1,69 @@
...
+	video::IVideoDriver *driver = Environment->getVideoDriver();
+
+	if (m_middle.getArea() == 0) {
+		const video::SColor color(255, 255, 255, 255);
+		const video::SColor colors[] = {color, color, color, color};
+		draw2DImageFilterScaled(driver, texture, AbsoluteRect,
+				core::rect<s32>(core::position2d<s32>(0, 0),
+						core::dimension2di(
+								texture->getOriginalSize())),
+				&AbsoluteClippingRect, colors, true);
```
[the remark this answers is not in the document]
Comment (DS-Minetest) [reply src/gui/guiBackgroundImage.cpp]: I've tried my best. Done.

File: src/gui/guiBackgroundImage.cpp [hunk 24]
```diff
@@ -0,0 +1,69 @@
...
+	} else {
+		core::rect<s32> middle = m_middle;
+		// `-x` is interpreted as `w - x`
+		if (middle.LowerRightCorner.X < 0) {
+			middle.LowerRightCorner.X += texture->getOriginalSize().Width;
+		}
```
[the remark this answers is not in the document]
Comment (DS-Minetest) [reply src/gui/guiBackgroundImage.cpp]: Done.

File: src/gui/guiBackgroundImage.cpp [hunk 25]
```diff
@@ -0,0 +1,69 @@
...
+		if (middle.LowerRightCorner.Y < 0) {
+			middle.LowerRightCorner.Y += texture->getOriginalSize().Height;
+		}
+		draw2DImage9Slice(driver, texture, AbsoluteRect, middle,
+				&AbsoluteClippingRect);
```
[the remark this answers is not in the document]
Comment (DS-Minetest) [reply src/gui/guiBackgroundImage.cpp]: Afaik, there's no rule that forbids this.
And it looks better (= more readable) with two indents because of the two `if` statements above (less monotonous).

File: src/gui/guiBackgroundImage.h (hunk 12 above)
Comment (DS-Minetest) [reply src/gui/guiBackgroundImage.h]: Afaik, it means that the file is part of minetest.

See also https://github.com/minetest/minetest/pull/8740#discussion_r312014639.

File: src/gui/guiBox.cpp (hunk 13 above)
Comment (DS-Minetest) [reply src/gui/guiBox.cpp]: Afaik, it's allowed.

File: src/gui/guiFormSpecMenu.cpp (hunk 14 above)
Comment (DS-Minetest) [reply src/gui/guiFormSpecMenu.cpp]: They could, but all field specs are created in this format. Hence changing one would require changing all, making this PR even larger.

File: src/gui/guiFormSpecMenu.cpp (hunk 15 above)
Comment (DS-Minetest) [reply src/gui/guiFormSpecMenu.cpp]: Done.

File: src/gui/guiFormSpecMenu.cpp (hunk 16 above)
Comment (DS-Minetest) [reply src/gui/guiFormSpecMenu.cpp]: Done.

**Comment by DS-Minetest** [comment]
Thanks for the code style review @ClobberXD!

**Comment by jastevenson303** [comment]
Haha, that's funny, so you're saying your PR exposed a bug in my formspec
that the old version didn't show :D  Congrats!

File: src/gui/guiBackgroundImage.h (hunk 12 above)
Comment (ClobberXD) [reply src/gui/guiBackgroundImage.h]: All files are part of Minetest tho. Also, the linked comment says nothing about adding "Part of"

File: src/gui/guiFormSpecMenu.cpp (hunk 20 above)
[the remark this answers is not in the document]
Comment (ClobberXD) [reply src/gui/guiFormSpecMenu.cpp]: Even if there's only one single statement, we generally always use braces for loops, I think. So that's not a problem :)

File: src/gui/guiBackgroundImage.cpp (hunk 23 above)
[the remark this answers is not in the document]
Comment (ClobberXD) [reply src/gui/guiBackgroundImage.cpp]: No pressures, thanks.

File: src/gui/guiBackgroundImage.cpp (hunk 25 above)
[the remark this answers is not in the document]
Comment (ClobberXD) [reply src/gui/guiBackgroundImage.cpp]: If you think that's more readable, no problemo, thanks

File: src/gui/guiFormSpecMenu.cpp (hunk 14 above)
Comment (ClobberXD) [reply src/gui/guiFormSpecMenu.cpp]: Understood; I noticed that too.

**Comment by DS-Minetest** [comment]
Ok, I've fixed your bug, @jastevenson303.
In your particular situation, it is a bug caused by you, evil you. But there might be many people who do the same mistake (because of lazy copying). Because of this I've fixed this.
Also, now there won't be warnings anymore in the draw function if the inventory or the list does not exist (in most cases; there might still be warnings if the inventory somehow disappears). (The warnings were like torturous screams of horror.)

**Comment by DS-Minetest** [comment]
Thanks!

(The last commit has no functional changes.)

File: src/gui/guiFormSpecMenu.cpp [hunk 26]
```diff
@@ -2707,6 +2900,68 @@ void GUIFormSpecMenu::regenerateGui(v2u32 screensize)
...
+		from++;
+
+	core::list<IGUIElement *>::Iterator to = Children.end();
+
+	// step 1: move all boxes to back and all images to front
+	// (drawn in back = drawn first = in front of list)
+	for (auto i = from; i != to;) {
+		if (getTypeByID((*i)->getID()) == f_Box) {
+			auto e = *i;
+			i = Children.erase(i);
```
Comment (SmallJoker) [inline src/gui/guiFormSpecMenu.cpp]: `std::sort` could do this. You'd only need a function to get the priority, and one to compare one element's priority with another.

Example:
https://github.com/minetest/minetest/pull/8603/files#diff-6ba6d577c564534741b34ee55c76e5b8R343
https://github.com/minetest/minetest/pull/8603/files#diff-6ba6d577c564534741b34ee55c76e5b8R446

Just for your information. I think this code will work good as well.

File: src/gui/guiFormSpecMenu.cpp [hunk 27]
```diff
@@ -3392,12 +3538,10 @@ void GUIFormSpecMenu::acceptInput(FormspecQuitMode quitmode=quit_mode_no)
 							fields[name] = "VAL:" + os.str();
  					}
 				}
-				else
-				{
-					IGUIElement* e = getElementFromId(s.fid);
-					if(e != NULL) {
+				else {
```
Comment (SmallJoker) [inline src/gui/guiFormSpecMenu.cpp]: `} else {`

File: src/gui/guiFormSpecMenu.cpp [hunk 28]
```diff
@@ -3392,12 +3538,10 @@ void GUIFormSpecMenu::acceptInput(FormspecQuitMode quitmode=quit_mode_no)
...
+					IGUIElement *e = getElementFromId(s.fid, true);
+					if(e)
```
Comment (SmallJoker) [inline src/gui/guiFormSpecMenu.cpp]: Space

File: src/gui/guiFormSpecMenu.cpp [hunk 29]
```diff
@@ -4169,13 +4313,22 @@ bool GUIFormSpecMenu::OnEvent(const SEvent& event)
...
-		if (spec.fid == id) {
+		if (spec.fid == id)
 			return spec.fname;
-		}
 	}
 	return "";
 }
 
+
+FormspecFieldType GUIFormSpecMenu::getTypeByID(s32 id)
```
Comment (SmallJoker) [inline src/gui/guiFormSpecMenu.cpp]: This function could be merged with `getLabelByID`: `getFieldSpecById`, returning the entire fieldspec (or a default one).

File: src/gui/guiFormSpecMenu.cpp [hunk 30]
```diff
@@ -812,8 +919,31 @@ void GUIFormSpecMenu::parseBackground(parserData* data, const std::string &eleme
...
-		m_backgrounds.emplace_back(name, pos, geom, middle, clip);
+		FieldSpec spec(
+			name,
+			L"",
+			L"",
+			258 + m_fields.size()
+		);
+
+		core::rect<s32> rect;
+		if (!clip)
```
[the remark this answers is not in the document]
Comment (DS-Minetest) [reply src/gui/guiFormSpecMenu.cpp]: Done.

File: src/gui/guiFormSpecMenu.cpp [hunk 31]
```diff
@@ -1807,35 +1939,45 @@ void GUIFormSpecMenu::parseItemImageButton(parserData* data, const std::string &
 						m_default_tooltip_bgcolor,
 						m_default_tooltip_color);
 
-		FieldSpec spec(
+		// the spec for the button
+		FieldSpec specb(
```
[the remark this answers is not in the document]
Comment (DS-Minetest) [reply src/gui/guiFormSpecMenu.cpp]: Done.

File: src/gui/guiFormSpecMenu.cpp [hunk 32]
```diff
@@ -1807,35 +1939,45 @@ void GUIFormSpecMenu::parseItemImageButton(parserData* data, const std::string &
...
+		rect += data->basepos-padding;
+		specb.rect = rect;
+		m_fields.push_back(specb);
 
-		if (data->real_coordinates)
-			pos = getRealCoordinateBasePos(true, v_pos);
-		else
-			pos = getElementBasePos(true, &v_pos);
+		// the spec for the item-image
+		FieldSpec speci(
```
[the remark this answers is not in the document]
Comment (DS-Minetest) [reply src/gui/guiFormSpecMenu.cpp]: Done.

File: src/gui/guiFormSpecMenu.cpp (hunk 26 above)
Comment (DS-Minetest) [reply src/gui/guiFormSpecMenu.cpp]: Would that ensure that the order otherwise stays the same? Eg. `button[1]box[1]image[1]button[2]box[2]button[3]image[2]` has to be `box[1]box[2]button[1]button[2]button[3]image[1]image[2]` and the internal order of boxes, buttons or images here has to be 123.

File: src/gui/guiFormSpecMenu.cpp (hunk 27 above)
Comment (DS-Minetest) [reply src/gui/guiFormSpecMenu.cpp]: This is adapted to the code style of the whole if else construct here. I would have to change it everywhere.
(Also it's quite readable.)

File: src/gui/guiFormSpecMenu.cpp (hunk 28 above)
Comment (DS-Minetest) [reply src/gui/guiFormSpecMenu.cpp]: Done.

File: src/gui/guiFormSpecMenu.cpp (hunk 29 above)
Comment (DS-Minetest) [reply src/gui/guiFormSpecMenu.cpp]: `getLabelByID` is inherited from `GUIModalMenu`:
https://github.com/minetest/minetest/blob/9519d57017cfa28eb4f2fbf3c780f826017bbb00/src/gui/modalMenu.h#L62-L63
See also: https://github.com/minetest/minetest/search?q=getLabelByID&unscoped_q=getLabelByID

File: src/gui/guiFormSpecMenu.cpp (hunk 27 above)
Comment (SmallJoker) [reply src/gui/guiFormSpecMenu.cpp]: Only needed for touched lines

File: src/gui/guiFormSpecMenu.cpp (hunk 10 above)
Comment (DS-Minetest) [reply src/gui/guiFormSpecMenu.cpp]: Done.

File: src/gui/guiFormSpecMenu.cpp (hunk 26 above)
Comment (SmallJoker) [reply src/gui/guiFormSpecMenu.cpp]: Same elements have the same priority, hence their relative positions never change.

**Comment by DS-Minetest** [comment]
Rebased.

File: src/gui/guiFormSpecMenu.cpp (hunk 29 above)
Comment (SmallJoker) [reply src/gui/guiFormSpecMenu.cpp]: :man_shrugging: well then, OK.

**Comment by DS-Minetest** [comment]
Luckily the `bgcolor` fix PR's drawback has shown me a bug here. Fixed.
(The size of the rect of the form is not given in prepends.)

**Comment by DS-Minetest** [comment]
`override` added. See also #8957.

**Comment by DS-Minetest** [comment]
Why was this removed from the milestone?

Most of the complaints of travis and its suggestions don't meet the code style guidelines.

**Comment by rubenwardy** [comment]
It may still be merged if you pester Krock. But it's not a blocker and the feature freeze is in 5 days

**Comment by SmallJoker** [comment]
Seen, noted. I don't see an urgent need for this PR to be in 5.1.0. The code is good and works (will do some testing, though), but waiting until after release will give some more time to find & fix edge-cases, if there are any.

**Comment by rubenwardy** [comment]
That is also true. This is a relatively risky PR given its nature

**Comment by DS-Minetest** [comment]
Rebased.

**Comment by SmallJoker** [comment]
Quick update: Tested the PR with various mods, and also on a remote server with different formspecs. Could yet not find any visual difference, but until I feel safe to give an approval I'll study the code in the next few days. Interesting that you could get rid of the absolute position calculations.

**Comment by DS-Minetest** [comment]
I guess I should bump the formspec version, right?

**Comment by SmallJoker** [comment]
@DS-Minetest Yes, that would be great if you could make this depend on version 3.

**Comment by DS-Minetest** [comment]
Done.

**Comment by SmallJoker** [comment]
Minetest freezes when there's an error from Lua:
```
Thread 1 "minetest" received signal SIGINT, Interrupt.
0x000055555582a04e in GUIFormSpecMenu::legacySortElements(irr::core::list<irr::gui::IGUIElement*>::Iterator) ()
(gdb) bt
#0  0x000055555582a04e in GUIFormSpecMenu::legacySortElements(irr::core::list<irr::gui::IGUIElement*>::Iterator) ()
#1  0x000055555584d926 in GUIFormSpecMenu::regenerateGui(irr::core::vector2d<unsigned int>) ()
#2  0x000055555584267d in GUIFormSpecMenu::drawMenu() ()
#3  0x00005555558a3024 in GUIModalMenu::draw() ()
#4  0x00007ffff78afce2 in irr::gui::CGUIStaticText::draw() ()
   from /usr/lib/x86_64-linux-gnu/libIrrlicht.so.1.8
#5  0x00007ffff786472a in irr::gui::CGUIEnvironment::drawAll() ()
   from /usr/lib/x86_64-linux-gnu/libIrrlicht.so.1.8
```
Code used:
```Lua
) end
```

**Comment by DS-Minetest** [comment]
Ugh, I can reproduce.
What does actually happen when there's a lua error?

**Comment by DS-Minetest** [comment]
Fixed.

Inserting an element in front of a removed iterator caused the problem.

The crash actually just happened because the error window has a box in its back.

Thanks[,](http://irc.minetest.net/minetest-dev/2019-10-31#i_5607630) Krock!

**Comment by DS-Minetest** [comment]
Rebased.

**Comment by DS-Minetest** [comment]
Yey! :tada:
