### PR TITLE
[no sq] Misc fixes

### LINKED ISSUE #15584: `core.get_modpath` can return relative path, which breaks `core.register_decoration`
### Luanti version

```true
Luanti 5.11.0-dev (Linux)
Using LuaJIT 2.1.0-beta3
Built by GCC 9.4
Running on Linux/5.15.0 x86_64
BUILD_TYPE=Release
RUN_IN_PLACE=0
USE_CURL=1
USE_GETTEXT=1
USE_SOUND=1
```

### Irrlicht device

_No response_

### Operating system and version

Ubuntu 20.04

### CPU model

Intel Core i5-14600KF

### GPU model

NVIDIA GeForce RTX 4060 Ti

### Active renderer

OpenGL 4.6.0

### Summary

When registering a decoration containing a schematic, the path to the mod is duplicated when resolved if using custom path to world and the mod is in the worldmods directory.

```
minetest.register_decoration({
    ...
    schematic = minetest.get_modpath("mymode") .. "/schematics/myscheme.mts"
    ...
})
```

I expect, the path will be resolved to `path_to_world/worldmods/mymode/schematics/myscheme.mts`. But actually Luanti is trying to register path `path_to_world/worldmods/mymode/path_to_world/worldmods/mymode/schematics/myscheme.mts`.

I believe this problem relates to this piece of code: https://github.com/minetest/minetest/blob/a37bdbf8b7778336c6740f994164097ebb4129e6/src/script/lua_api/l_mapgen.cpp#L167-L168
But I don't know how to fix it properly and safe

### Steps to reproduce

1. Create new world in custom location
2. Make directory `worldmods` inside and put some suitable mod (for example terraria) into
3. Launch with command `luanti --gameid minetest --world ./myworld --server`

You will get errors in the terminal

### LINKED ISSUE #15652: Globalsteps continue executing well after an error is thrown
### Summary

Globalstep functions continue to run even after a Lua error was thrown from a globalstep. It appears this has always been an issue (I have not verified how far back it goes before 5.7.0) as the step will always overshoot by at least a few steps. But after 322c4a5b2b8343c3942555c6a337e765ef84c3c4 (#13370, server step rework) the overshoot increased to a few hundred steps. ad5e9aa5e38bed7f3407321fa8eb3cb1d8afff73 (#14182) made a trivial change and increased the overshoot to tens of thousands of steps.

In other words, while the server is "stopping" the server step drops to around 0 and runs as fast as it can until it actually stops. Each step may still throw an error, though I am not sure which error it decides to show; this was discovered due to an overshot step throwing an error due to an earlier step throwing an entirely different error (which you would expect to see instead, but no), but my minimal attempt to recreate overriding an inital error did not succeed.

This makes debugging rather difficult when globalsteps can override an earlier error with a new one ... its also just not acceptable that logic continues running _after errors_.

Discovered by @fatalisterror.

### Steps to reproduce

```lua
local step = 0
core.register_globalstep(function(dtime)
    step = step + 1
    print(step, dtime) -- You should see this a few thousand times; dtime will drop significantly after 31(?) steps
    if step > 30 then -- arbitrary number of steps I chose
        error("this is an error")
    end
    print("you cant see me after 30 steps")
end)
```

### LINKED ISSUE #15658: Reading too large VoxelManip segfaults
Luanti e5542e5b024719bc5f1b111fb2e3eded3fbffca6

reported by @cheapie 

```
Thread 30 "Server" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffc21f96c0 (LWP 11362)]
0x00007ffff6b4d595 in ?? () from /usr/lib/libc.so.6
#0  0x00007ffff6b4d595 in ?? () from /usr/lib/libc.so.6
#1  0x0000555555bc787b in VoxelManipulator::copyFrom (this=0x7fff6805e780, src=0x7fff68466770, src_area=..., from_pos=..., to_pos=..., size=...) at /home/stefan/minetest/src/voxel.cpp:216
#2  0x0000555555b4048c in MapBlock::copyTo (this=<optimized out>, dst=...) at /home/stefan/minetest/src/mapblock.cpp:168
#3  0x0000555555b3d08c in MMVManip::initialEmerge (this=0x7fff6805e780, blockpos_min=..., blockpos_max=..., load_if_inexistent=true) at /home/stefan/minetest/src/map.cpp:806
#4  0x00005555559fe171 in LuaVoxelManip::l_read_from_map (L=0x7fffec04f380) at /home/stefan/minetest/src/script/lua_api/l_vmanip.cpp:43
#5  0x0000555555981caa in script_exception_wrapper (L=0x7ffb2fe79f50, f=0x7fff68466770) at /home/stefan/minetest/src/script/common/c_internal.cpp:27
#6  0x00007ffff7a81f7b in ?? () from /usr/lib/libluajit-5.1.so.2
#7  0x00007ffff7a960aa in lua_pcall () from /usr/lib/libluajit-5.1.so.2
[...]
```

Reproducer: `//lua local v1=vector.new(0,0,0);local v2=vector.new(1500,1500,1500);VoxelManip(v1,v1):read_from_map(v2,v2)`

<hr>

~~not entirely sure what is going on here as `read_from_map(v2,v2)` should only be a single block~~, but probably some integer overflowing that we need to prevent by putting a max limits on the area size

### PR DESCRIPTION
**Pull request by sfan5**
commit 1: :man_shrugging: 
commit 2: fixes #15658
commit 3: fixes #15652
commit 4: fixes #15584

## To do

This PR is Ready for Review.

## How to test

maybe ask ChatGPT, idk

### CODE REVIEW

**Comment by HybridDog** [comment]
> maybe ask ChatGPT, idk

I think Microsoft would have more elation if we ask the Copilot. I have done this and am very unsatisfied with the result:

### How to test the changes proposed in PR [#15661](https://github.com/minetest/minetest/pull/15661):

1. **Review the Pull Request Description**:
   - The description mentions "maybe ask ChatGPT, idk" indicating there are no specific testing instructions provided by the author.

2. **Review the Changed Files**:
   - The PR changes 17 files including `doc/lua_api.md`, `irr/include/SMaterial.h`, `irr/include/SMaterialLayer.h`, and several files in the `src/client` and `src/content` directories.
   - You can view the list of changed files [here](https://github.com/minetest/minetest/pull/15661/files).

3. **Clone the Repository and Checkout the PR Branch**:
   ```sh
   git clone https://github.com/minetest/minetest.git
   cd minetest
   git fetch origin pull/15661/head:pr-15661
   git checkout pr-15661
   ```

4. **Build and Test the Project**:
   - Follow the project's build and test instructions, typically found in the `README.md` or `CONTRIBUTING.md` files.
   - Ensure you thoroughly test the areas affected by the changes.

If you have further questions or need additional guidance, feel free to ask!

**Review by Mizokuiam — COMMENTED** [review]
The implementation is clean. Consider adding more error handling...

File: src/map.h [hunk 1]
```diff
@@ -344,4 +341,6 @@ class MMVManip : public VoxelManipulator
 		value = flags describing the block
 	*/
 	std::map<v3s16, u8> m_loaded_blocks;
+
+	static constexpr u8 VMANIP_BLOCK_DATA_INEXIST = 1;
```
Comment (SmallJoker) [inline src/map.h:345]: I think that an enum (despite being 1 entry) would be more intuitive. Same approach as seen in `VOXELFLAG_NO_DATA`.

```suggestion
	enum : u8 {
		VMANIP_BLOCK_DATA_INEXIST = 1 << 0,
	};
```

File: doc/lua_api.md [hunk 2]
```diff
@@ -5059,9 +5059,11 @@ inside the VoxelManip.
 Methods
 -------
 
-* `read_from_map(p1, p2)`:  Loads a chunk of map into the VoxelManip object
+* `read_from_map(p1, p2)`: Loads a chunk of map into the VoxelManip object
   containing the region formed by `p1` and `p2`.
     * returns actual emerged `pmin`, actual emerged `pmax`
+    * Note that calling this multiple times will *add* to the area loaded in the
+      VManip, and not reset it.
```
Comment (SmallJoker) [inline doc/lua_api.md:5066]:
```suggestion
      VoxelManip, and not reset it.
```
To use consistent terminology. `vmanip` is yet only used as variable name.

**Review by SmallJoker — COMMENTED** [review]
Tested the error handling with the code provided in #15652, modified to do 60 steps.
```
you cant see me after 60 steps
58	0.017416000366211
you cant see me after 60 steps
59	0.016967000439763
you cant see me after 60 steps
60	0.018226999789476
you cant see me after 60 steps
61	0.016819000244141
```
Works.

The other changes look good. Please assume :+1: after the minor comments are handled.
