### PR TITLE
Fix issues with earlier CSM HUD commit

### LINKED ISSUE #6937: Stamina fails to work with commit 9649e47
See https://github.com/minetest-mods/stamina

Today the Stamina mod exhibits some strange, unpredictable behavior, though it mostly just kills the hunger bar right after you log on.

### LINKED ISSUE #6968: Client crashes when connecting to server [0.5.0-dev]
##### Issue type

 - Bug report
 
##### Minetest version

```
Minetest 0.5.0-dev (Linux)
Using Irrlicht 1.8.4
BUILD_TYPE=None
RUN_IN_PLACE=0
USE_GETTEXT=1
USE_SOUND=1
USE_CURL=1
USE_FREETYPE=1
USE_LUAJIT=1

```

##### OS / Hardware

Operating system: Ubuntu 17.10
CPU: Intel Q8300

GPU model: nvidia GT730
OpenGL version: 4.5.0

##### Summary
Whenever i try to play on some servers (many of them but not all), my client crashes just after connecting. My character spawns for a couple seconds then the game window closes.
Some servers are unaffected so it may be a mod issue.

##### Steps to reproduce

I've been using minetest 0.5.0-dev for a while without problem, the crashes started to occur a few days ago (a week tops). I tried to delete ~/.minetest directory and reinstall minetest to no avail.
Crash occurs any time i try and connect to some servers.

```
2018-01-26 05:32:05: WARNING[Main]: Irrlicht: PNG warning: Interlace handling should be turned on when using png_read_image
2018-01-26 05:32:05: WARNING[Main]: Irrlicht: PNG warning: Interlace handling should be turned on when using png_read_image
2018-01-26 05:32:05: WARNING[Main]: Irrlicht: PNG warning: Interlace handling should be turned on when using png_read_image
2018-01-26 05:32:06: WARNING[Main]: Irrlicht: PNG warning: iCCP: known incorrect sRGB profile
2018-01-26 05:32:14: WARNING[Main]: Irrlicht: PNG warning: Interlace handling should be turned on when using png_read_image
2018-01-26 05:32:14: ERROR[Main]: generateImage(): Could not load image "yum_vanilla_icecream_block.png" while building texture; Creating a dummy image
2018-01-26 05:32:14: ERROR[Main]: generateImage(): Could not load image "yum_vanilla_icecream_block.png" while building texture; Creating a dummy image
2018-01-26 05:32:15: ERROR[Main]: generateImage(): Could not load image "darkage_marble_tile.png" while building texture; Creating a dummy image
2018-01-26 05:32:15: ERROR[Main]: generateImage(): Could not load image "darkage_marble_tile.png" while building texture; Creating a dummy image
2018-01-26 05:32:18: ERROR[Main]: generateImage(): Could not load image "moretrees_acacia_wood.png" while building texture; Creating a dummy image
2018-01-26 05:32:18: ERROR[Main]: generateImage(): Could not load image "moretrees_acacia_wood.png" while building texture; Creating a dummy image
2018-01-26 05:32:18: ERROR[Main]: generateImage(): Could not load image "mv_technic_machine_bottom.png" while building texture; Creating a dummy image
2018-01-26 05:32:18: ERROR[Main]: generateImage(): Could not load image "mv_technic_machine_bottom.png" while building texture; Creating a dummy image
2018-01-26 05:32:19: ERROR[Main]: generateImage(): Could not load image "hv_technic_machine_bottom.png" while building texture; Creating a dummy image
2018-01-26 05:32:19: ERROR[Main]: generateImage(): Could not load image "hv_technic_machine_bottom.png" while building texture; Creating a dummy image
2018-01-26 05:32:20: WARNING[Main]: TextureSource::getPalette(): the specified palette image "unifieddyes_palette_extended.png" is larger than 256 pixels, using the first 256.
2018-01-26 05:32:48: ERROR[Main]: generateImage(): Could not load image "hiking_illuminated_pole_sign_bottom_.png" while building texture; Creating a dummy image
2018-01-26 05:32:50: WARNING[Main]: Client side mods are disabled by configuration.
2018-01-26 05:32:50: ERROR[Main]: In thread 7f1d8667cd80:
2018-01-26 05:32:50: ERROR[Main]: /build/minetest-vNgBwG/minetest-201801241734/src/game.cpp:a26: void Game::handleClientEvent_HudAdd(ClientEvent*, CameraOrientation*): An engine assumption 'new_id == id' failed.
```

### PR DESCRIPTION
**Pull request by red-001**
## Issue
It appears the issue was caused by events being queued together before being processed, this either didn't happen before (event refactor?) or it happened to a lesser degree and I somehow missed it while testing the PR.

## Fix
Move generating client IDs for HUD elements sent by the server to the event handler for HUD creation.

I think it fixes #6937 and also should fix #6968

### CODE REVIEW

File: src/client.h [hunk 1]
```diff
@@ -554,10 +557,6 @@ class Client : public con::PeerHandler, public InventoryManager, public IGameDef
 	// And relations to objects
 	std::unordered_map<int, u16> m_sounds_to_objects;
 
-	// HUD
-	// Mapping from server hud ids to internal hud ids
-	std::unordered_map<u32, u32> m_hud_server_to_client;
```
Comment (nerzhul) [inline src/client.h]: please add ref getter instead of make it public

Comment (red-001) [reply src/client.h]: sure

**Comment by mtango688** [comment]
Looks good here.

**Comment by red-001** [comment]
@mtango688 thanks.

**Comment by lhofhansl** [comment]
I can confirm that that fixes the issues with hud-bars I've seen recently.

File: src/client.h [hunk 2]
```diff
@@ -422,6 +422,11 @@ class Client : public con::PeerHandler, public InventoryManager, public IGameDef
 		return m_csm_noderange_limit;
 	}
 
+	inline std::unordered_map<u32, u32> *GetHUDMapping()
```
Comment (SmallJoker) [inline src/client.h]: Should start with lowercase. Perhaps name it `getHUDTranslationMap` or `getHUDMap`?

**Comment by red-001** [comment]
@SmallJoker done
