### PR TITLE
Windows: Fix user directory opening in the wrong place

### LINKED ISSUE #12631: "Open User Data Directory" opens wrong directory
##### Minetest version
5.6.0-2cf52642f-win64

##### OS / Hardware
Windows 10

##### Summary
Main menu > About > button Open User Data Directory has tooltip: "Opens the directory that contains user-provided worlds, games, mods, and texture packs in a file manager / explorer." - which is not true, it opens "bin" folder with *.dlls and minetest.exe.

### PR DESCRIPTION
**Pull request by SmallJoker**
Fixes #12631

Tested on Windows 10, compiled with mingw64_14.1.0_MFC 

## To do

This PR is Ready for Review.

## How to test

1. Open the main menu
2. Click the user directory button -> must open to where minetest.conf is
3. Click the website button -> must open the website

### CODE REVIEW

**Comment by SmallJoker** [comment]
I could also move it to `open_directory` if that's preferred. At the end it should not really matter.

File: src/porting.cpp [hunk 1]
```diff
@@ -881,15 +881,29 @@ int mt_snprintf(char *buf, const size_t buf_size, const char *fmt, ...)
...
 	}
+	verbosestream << "Opening URI: " << uri << std::endl;
 
 #if defined(_WIN32)
-	return (intptr_t)ShellExecuteA(NULL, NULL, uri.c_str(), NULL, NULL, SW_SHOWNORMAL) > 32;
+	if (1)
+#else
+	if (0)
+#endif
+	{
```
Comment (rubenwardy) [inline src/porting.cpp]: I think this code should be in open_directory, below. Also no need to do the if 1/0 thing, can just put it in the `#if`. Also could maybe do this on all platforms

File: src/porting.cpp [hunk 2]
```diff
@@ -887,9 +887,10 @@ static bool open_uri(const std::string &uri)
 		errorstream << "Unable to open URI as it is invalid, contains new line: " << uri << std::endl;
 		return false;
 	}
+	verbosestream << "Opening URI: " << uri << std::endl;
 
 #if defined(_WIN32)
-	return (intptr_t)ShellExecuteA(NULL, NULL, uri.c_str(), NULL, NULL, SW_SHOWNORMAL) > 32;
+	return (intptr_t)ShellExecuteA(NULL, "open", uri.c_str(), NULL, NULL, SW_SHOWNORMAL) > 32;
```
Comment (sfan5) [inline src/porting.cpp]: intentional change?
for example the docs say:
> **open**
> Opens the item specified by the lpFile parameter. The item can be a file or folder.

does that mean `"open"` won't work for URLs? I think we shouldn't risk it and leave this as-is.

File: src/porting.cpp [hunk 3]
```diff
@@ -920,7 +921,16 @@ bool open_directory(const std::string &path)
 		return false;
 	}
 
-	return open_uri(path);
+	std::string uri = path;
+
+	// This is a workaround for Windows (10, ... ?). The relative part of paths such as
+	// in "bin\.." are discarded by 'ShellExecuteA'. Hence, resolve it manually.
+	// This is done on all platforms because why not.
+	if (fs::IsDir(uri)) {
```
Comment (rubenwardy) [inline src/porting.cpp]: IsDir will always be true here because if it's not this function early returns. See above check

File: src/porting.cpp (hunk 2 above)
Comment (SmallJoker) [reply src/porting.cpp]: Partially. I found that it made no functional difference, and having the action (MS calls it "operation") clearly defined is IMO better.

**Review by sfan5 — APPROVED** [review]
ok
