### PR TITLE
Take screenshot from back buffer when using double buffering

### LINKED ISSUE #14901: Completely black screenshots on wayland
### Minetest version

```true
Minetest 5.9.0-dev-90fccc1 (Linux)
Using LuaJIT 2.1.1693350652
Built by GCC 13.2
Running on Linux/6.6.34 x86_64
BUILD_TYPE=Release
RUN_IN_PLACE=0
USE_CURL=1
USE_GETTEXT=1
USE_SOUND=1
STATIC_SHAREDIR="/nix/store/gixslm1ibmc75ix53kyd5asys3rvngn2-minetest-unstable/share/minetest"
STATIC_LOCALEDIR="/nix/store/gixslm1ibmc75ix53kyd5asys3rvngn2-minetest-unstable/share/locale"
```

### Irrlicht device

SDL (with SDL_VIDEODRIVER=wayland)

### Operating system and version

NixOS Linux 24.05

Window manager: sway

### CPU model

AMD Ryzen 7 7840U

### GPU model

Radeon  780M

### Active renderer

OpenGL 4.6

### Summary

All screenshots I take are the right size but completely black. Using SDL_VIDEODRIVER=x11 works, but then I get all the problems related to xwayland.

### Steps to reproduce

1. Start minetest with `SDL_VIDEODRIVER=wayland minetest`
2. Load a world
3. Take a screenshot

### PR DESCRIPTION
**Pull request by fgaz**
Fixes #14901 (black screenshots on Wayland).

This fix works with both `SDL_VIDEODRIVER` set to `wayland` and `x11` on my machine.

I am not knowledgeable in graphics programming, so I'm not 100% sure this is an appropriate solution.

## To do

This PR is Ready for Review.

## How to test

See #14901

### CODE REVIEW

File: irr/src/COpenGLDriver.cpp [hunk 1]
```diff
@@ -3018,7 +3018,8 @@ IImage *COpenGLDriver::createScreenShot(video::ECOLOR_FORMAT format, video::E_RE
 	if (newImage)
 		pixels = static_cast<u8 *>(newImage->getData());
 	if (pixels) {
-		glReadBuffer(GL_FRONT);
+		if (!Params.Doublebuffer)
```
Comment (appgurueu) [inline irr/src/COpenGLDriver.cpp:3021]: Suggestion: Write this as `glReadBuffer(Params.Doublebuffer ? GL_BACK : GL_FRONT);` instead. Then you can get rid of the somewhat dubious `glReadBuffer(GL_BACK);` a few lines below.

Comment (appgurueu) [reply irr/src/COpenGLDriver.cpp:3021]: I was under the impression that no, but after a closer look, there are two calls to `glCopyTexImage2D` which *might* rely on this. So it's probably safer to restore it. Still, two thoughts:

* "It is an error to specify a nonexistent buffer to glReadBuffer" - shouldn't we restore to `GL_FRONT` if we are to support a singlebuffer configuration?
* I wonder whether this fix should also be applied to the OGLES driver.

File: irr/src/COpenGLDriver.cpp [hunk 2]
```diff
@@ -3018,10 +3018,10 @@ IImage *COpenGLDriver::createScreenShot(video::ECOLOR_FORMAT format, video::E_RE
...
+		glReadBuffer(Params.Doublebuffer ? GL_FRONT : GL_BACK);
 		glReadPixels(0, 0, ScreenSize.Width, ScreenSize.Height, fmt, type, pixels);
 		testGLError(__LINE__);
-		glReadBuffer(GL_BACK);
```
Comment (sfan5) [inline irr/src/COpenGLDriver.cpp:3024]: don't just remove this

File: irr/src/COpenGLDriver.cpp (hunk 1 above)
Comment (fgaz) [reply irr/src/COpenGLDriver.cpp]: > * "It is an error to specify a nonexistent buffer to glReadBuffer" - shouldn't we restore to `GL_FRONT` if we are to support a singlebuffer configuration?

Good point. I applied your suggestion.



> * I wonder whether this fix should also be applied to the OGLES driver.

I just tested it and I can't reproduce the bug, but maybe it's just luck and it will resurface in a different hardware/sofrware configuration. Should I apply an equivalent patch anyway?

File: irr/src/COpenGLDriver.cpp (hunk 2 above)
Comment (fgaz) [reply irr/src/COpenGLDriver.cpp:3024]: @appgurueu's argument for removing it is convincing. Why do you think it should be kept?

Comment (sfan5) [reply irr/src/COpenGLDriver.cpp:3024]: I would rather not change this due to the risk of introducing some obscure bug due to it.

Comment (fgaz) [reply irr/src/COpenGLDriver.cpp:3024]: I added it back

File: irr/src/COpenGLDriver.cpp (hunk 1 above)
Comment (appgurueu) [reply irr/src/COpenGLDriver.cpp]: > I just tested it and I can't reproduce the bug, but maybe it's just luck and it will resurface in a different hardware/sofrware configuration. Should I apply an equivalent patch anyway?

I'd leave it untouched in that case.

**Review by appgurueu — APPROVED** [review]
Tested on stock Fedora 40 (GNOME on Wayland), works, didn't work before. Thanks.

**Review by SmallJoker — APPROVED** [review]
:ballot_box_with_check: Linux x11 without shaders (if shaders matter at all?)
:ballot_box_with_check: Linux x11 with shaders (shadowmaps)
:ballot_box_with_check: MSVC build + Wine 9.13 + Linux x11

Does not break anything on my side, thus LGTM.
