### PR TITLE
Limit light_source in the engine

### LINKED ISSUE #4807: Client crash (lighting related)
Backtrace. Happened to me on redcat server at least 5 times. Could not catch the backtrace with debug build, had to use release with debug info build.

On line 262 of voxelalgorithms.cpp rel_pos is a valid reference. From there, exececution leads to line 268 of voxelalgorithms.cpp and at that point rel_pos is a null reference. I am suspecting a race condition at this early point in time.
```

Thread 15 (Thread 0x7fffdd9ef700 (LWP 29739)):
#0  0x00007ffff4a0de67 in do_futex_wait.constprop () from /lib64/libpthread.so.0
No symbol table info available.
#1  0x00007ffff4a0df14 in __new_sem_wait_slow.constprop.0 () from /lib64/libpthread.so.0
No symbol table info available.
#2  0x00007ffff4a0dfba in sem_wait@@GLIBC_2.2.5 () from /lib64/libpthread.so.0
No symbol table info available.
#3  0x0000000000561355 in Semaphore::wait (this=<optimized out>) at /home/crobbins/minetest/src/threading/semaphore.cpp:105
No locals.
#4  0x00000000005f0c88 in UpdateThread::run (this=0x1911030) at /home/crobbins/minetest/src/util/thread.h:217
        __debug_stacker = {m_stack = 0x7fffcc000c60, m_overflowed = false}
        __PRETTY_FUNCTION__ = "virtual void* UpdateThread::run()"
#5  0x0000000000561452 in Thread::threadProc (param=0x1911030) at /home/crobbins/minetest/src/threading/thread.cpp:252
        thr = 0x1911030
#6  0x00007ffff4a0661a in start_thread () from /lib64/libpthread.so.0
No symbol table info available.
#7  0x00007ffff2f0a5fd in clone () from /lib64/libc.so.6
No symbol table info available.

Thread 14 (Thread 0x7fffdd1d6700 (LWP 29723)):
#0  0x00007ffff4a0de67 in do_futex_wait.constprop () from /lib64/libpthread.so.0
No symbol table info available.
#1  0x00007ffff4a0df14 in __new_sem_wait_slow.constprop.0 () from /lib64/libpthread.so.0
No symbol table info available.
#2  0x00007ffff4a0dfba in sem_wait@@GLIBC_2.2.5 () from /lib64/libpthread.so.0
No symbol table info available.
#3  0x0000000000561355 in Semaphore::wait (this=<optimized out>) at /home/crobbins/minetest/src/threading/semaphore.cpp:105
No locals.
#4  0x00000000005f0c88 in UpdateThread::run (this=0xf8ede0) at /home/crobbins/minetest/src/util/thread.h:217
        __debug_stacker = {m_stack = 0x7fffd800c060, m_overflowed = false}
        __PRETTY_FUNCTION__ = "virtual void* UpdateThread::run()"
#5  0x0000000000561452 in Thread::threadProc (param=0xf8ede0) at /home/crobbins/minetest/src/threading/thread.cpp:252
        thr = 0xf8ede0
#6  0x00007ffff4a0661a in start_thread () from /lib64/libpthread.so.0
No symbol table info available.
#7  0x00007ffff2f0a5fd in clone () from /lib64/libc.so.6
No symbol table info available.

Thread 13 (Thread 0x7fffdc9d5700 (LWP 29722)):
#0  0x00007ffff2f00903 in select () from /lib64/libc.so.6
No symbol table info available.
#1  0x00000000007e9236 in UDPSocket::WaitData (this=0x19313c0, timeout_ms=timeout_ms@entry=50) at /home/crobbins/minetest/src/socket.cpp:560
        readset = {fds_bits = {524288, 0 <repeats 15 times>}}
        result = <optimized out>
        tv = {tv_sec = 0, tv_usec = 48989}
#2  0x00000000004f4bce in con::ConnectionReceiveThread::receive (this=this@entry=0x1931670) at /home/crobbins/minetest/src/network/connection.cpp:2143
        packetdata = {data = 0x7fffc0000940 "OEt\003", m_size = 1500, refcount = 0x7fffc0000f30}
        packet_queued = false
        loop_count = 3
#3  0x00000000004f5c58 in con::ConnectionReceiveThread::run (this=0x1931670) at /home/crobbins/minetest/src/network/connection.cpp:2066
        __PRETTY_FUNCTION__ = "virtual void* con::ConnectionReceiveThread::run()"
#4  0x0000000000561452 in Thread::threadProc (param=0x1931670) at /home/crobbins/minetest/src/threading/thread.cpp:252
        thr = 0x1931670
#5  0x00007ffff4a0661a in start_thread () from /lib64/libpthread.so.0
No symbol table info available.
#6  0x00007ffff2f0a5fd in clone () from /lib64/libc.so.6
No symbol table info available.

Thread 12 (Thread 0x7fffd3ffe700 (LWP 29721)):
#0  0x00007ffff4a0e055 in do_futex_wait () from /lib64/libpthread.so.0
No symbol table info available.
#1  0x00007ffff4a0e11f in __new_sem_wait_slow () from /lib64/libpthread.so.0
No symbol table info available.
#2  0x00007ffff4a0e1d2 in sem_timedwait () from /lib64/libpthread.so.0
No symbol table info available.
#3  0x00000000005613e8 in Semaphore::wait (this=this@entry=0x1931640, time_ms=time_ms@entry=50) at /home/crobbins/minetest/src/threading/semaphore.cpp:155
        wait_time = {tv_sec = 1479997196, tv_nsec = 227003000}
        now = {tv_sec = 1479997196, tv_usec = 177003}
        ret = <optimized out>
#4  0x00000000004f1f52 in con::ConnectionSendThread::run (this=0x1931578) at /home/crobbins/minetest/src/network/connection.cpp:1295
        c = {type = con::CONNCMD_NONE, address = {m_addr_family = 0, m_address = {ipv4 = {sin_family = 0, sin_port = 0, sin_addr = {s_addr = 0}, sin_zero = "\000\000\000\000\000\000\000"}, ipv6 = {sin6_family = 0, sin6_port = 0, sin6_flowinfo = 0, sin6_addr = {__in6_u = {__u6_addr8 = '\000' <repeats 15 times>, __u6_addr16 = {0, 0, 0, 0, 0, 0, 0, 0}, __u6_addr32 = {0, 0, 0, 0}}}, sin6_scope_id = 0}}, m_port = 0}, peer_id = 0, channelnum = 2 '\002', data = {data = 0x0, m_size = 0}, reliable = false, raw = false}
        curtime = 29161928
        lasttime = <optimized out>
        __PRETTY_FUNCTION__ = "virtual void* con::ConnectionSendThread::run()"
#5  0x0000000000561452 in Thread::threadProc (param=0x1931578) at /home/crobbins/minetest/src/threading/thread.cpp:252
        thr = 0x1931578
#6  0x00007ffff4a0661a in start_thread () from /lib64/libpthread.so.0
No symbol table info available.
#7  0x00007ffff2f0a5fd in clone () from /lib64/libc.so.6
No symbol table info available.

Thread 11 (Thread 0x7fffde2f0700 (LWP 29720)):
#0  0x00007ffff4a0bb08 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
No symbol table info available.
#1  0x00007fffe4fc6e88 in pa_threaded_mainloop_wait () from /lib64/libpulse.so.0
No symbol table info available.
#2  0x00007ffff5c65a79 in ALCpulsePlayback_mixerProc () from /lib64/libopenal.so.1
No symbol table info available.
#3  0x00007ffff5c69607 in althrd_starter () from /lib64/libopenal.so.1
No symbol table info available.
#4  0x00007ffff4a0661a in start_thread () from /lib64/libpthread.so.0
No symbol table info available.
#5  0x00007ffff2f0a5fd in clone () from /lib64/libc.so.6
No symbol table info available.

Thread 10 (Thread 0x7fffd37fd700 (LWP 29719)):
#0  0x00007ffff2efeb7d in poll () from /lib64/libc.so.6
No symbol table info available.
#1  0x00007fffe4fc68a1 in poll_func () from /lib64/libpulse.so.0
No symbol table info available.
#2  0x00007fffe4fb7ec1 in pa_mainloop_poll () from /lib64/libpulse.so.0
No symbol table info available.
#3  0x00007fffe4fb855e in pa_mainloop_iterate () from /lib64/libpulse.so.0
No symbol table info available.
#4  0x00007fffe4fb8610 in pa_mainloop_run () from /lib64/libpulse.so.0
No symbol table info available.
#5  0x00007fffe4fc6836 in thread () from /lib64/libpulse.so.0
No symbol table info available.
#6  0x00007fffe4d66c78 in internal_thread_func () from /usr/lib64/pulseaudio/libpulsecommon-7.1.so
No symbol table info available.
#7  0x00007ffff4a0661a in start_thread () from /lib64/libpthread.so.0
No symbol table info available.
#8  0x00007ffff2f0a5fd in clone () from /lib64/libc.so.6
No symbol table info available.

Thread 1 (Thread 0x7ffff7fac8c0 (LWP 29696)):
#0  voxalgo::ChangingLight::ChangingLight (this=<optimized out>) at /home/crobbins/minetest/src/voxelalgorithms.cpp:183
No locals.
#1  std::_Construct<voxalgo::ChangingLight, voxalgo::ChangingLight> (__value=..., __p=<optimized out>) at /usr/include/c++/5.3.1/bits/stl_construct.h:83
No locals.
#2  std::__uninitialized_copy<false>::__uninit_copy<voxalgo::ChangingLight*, voxalgo::ChangingLight*> (__result=0x2aeea520, __last=0x7fffffffbde0, __first=0x7fffffffeff0) at /usr/include/c++/5.3.1/bits/stl_uninitialized.h:75
        __cur = 0x2aeed740
#3  std::uninitialized_copy<voxalgo::ChangingLight*, voxalgo::ChangingLight*> (__result=<optimized out>, __last=0x7fffffffbde0, __first=0x7fffffffbdd0) at /usr/include/c++/5.3.1/bits/stl_uninitialized.h:126
        __assignable = true
#4  std::__uninitialized_copy_a<voxalgo::ChangingLight*, voxalgo::ChangingLight*, voxalgo::ChangingLight> (__result=<optimized out>, __last=0x7fffffffbde0, __first=0x7fffffffbdd0) at /usr/include/c++/5.3.1/bits/stl_uninitialized.h:281
No locals.
#5  std::__uninitialized_move_if_noexcept_a<voxalgo::ChangingLight*, voxalgo::ChangingLight*, std::allocator<voxalgo::ChangingLight> > (__alloc=..., __result=<optimized out>, __last=0x7fffffffbde0, __first=0x7fffffffbdd0) at /usr/include/c++/5.3.1/bits/stl_uninitialized.h:304
No locals.
#6  std::vector<voxalgo::ChangingLight, std::allocator<voxalgo::ChangingLight> >::_M_insert_aux (this=0x7fffffffbad8, __position=..., __x=...) at /usr/include/c++/5.3.1/bits/vector.tcc:370
        __elems_before = <optimized out>
        __new_finish = 0x0
#7  0x0000000000806c21 in std::vector<voxalgo::ChangingLight, std::allocator<voxalgo::ChangingLight> >::push_back (__x=..., this=<optimized out>) at /usr/include/c++/5.3.1/bits/stl_vector.h:925
No locals.
#8  voxalgo::LightQueue::push (source_dir=6 '\006', block=0x27a37640, block_pos=<synthetic pointer>, rel_pos=<synthetic pointer>, light=17 '\021', this=0x7fffffffb940) at /home/crobbins/minetest/src/voxelalgorithms.cpp:268
No locals.
#9  voxalgo::update_lighting_nodes (map=map@entry=0x10958d0, ndef=ndef@entry=0xf85390, oldnodes=..., modified_blocks=...) at /home/crobbins/minetest/src/voxelalgorithms.cpp:652
        block = 0x27a37640
        new_light = 17 '\021'
        p = {X = 1496, Y = 4, Z = 2912}
        rel_pos = {X = 8, Y = 4, Z = 0}
        block_pos = {X = 93, Y = 0, Z = 182}
        n = {param0 = 8292, param1 = 0 '\000', param2 = 0 '\000'}
        old_light = 13 '\r'
        it = {_M_current = 0x2b75ea10}
        disappearing_lights = {lights = {{<std::_Vector_base<voxalgo::ChangingLight, std::allocator<voxalgo::ChangingLight> >> = {_M_impl = {<std::allocator<voxalgo::ChangingLight>> = {<__gnu_cxx::new_allocator<voxalgo::ChangingLight>> = {<No data fields>}, <No data fields>}, _M_start = 0x2b80d8a0, _M_finish = 0x2b80d8a0, _M_end_of_storage = 0x2b80f8a0}}, <No data fields>}, {<std::_Vector_base<voxalgo::ChangingLight, std::allocator<voxalgo::ChangingLight> >> = {_M_impl = {<std::allocator<voxalgo::ChangingLight>> = {<__gnu_cxx::new_allocator<voxalgo::ChangingLight>> = {<No data fields>}, <No data fields>}, _M_start = 0x2b59b9d0, _M_finish = 0x2b59b9d0, _M_end_of_storage = 0x2b59d9d0}}, <No data fields>}, {<std::_Vector_base<voxalgo::ChangingLight, std::allocator<voxalgo::ChangingLight> >> = {_M_impl = {<std::allocator<voxalgo::ChangingLight>> = {<__gnu_cxx::new_allocator<voxalgo::ChangingLight>> = {<No data fields>}, <No data fields>}, _M_start = 0x2b6a1df0, _M_finish = 0x2b6a1df0, _M_end_of_storage = 0x2b6a3df0}}, <No data fields>}, {<std::_Vector_base<voxalgo::ChangingLight, std::allocator<voxalgo::ChangingLight> >> = {_M_impl = {<std::allocator<voxalgo::ChangingLight>> = {<__gnu_cxx::new_allocator<voxalgo::ChangingLight>> = {<No data fields>}, <No data fields>}, _M_start = 0x2b5d3750, _M_finish = 0x2b5d3750, _M_end_of_storage = 0x2b5d5750}}, <No data fields>}, {<std::_Vector_base<voxalgo::ChangingLight, std::allocator<voxalgo::ChangingLight> >> = {_M_impl = {<std::allocator<voxalgo::ChangingLight>> = {<__gnu_cxx::new_allocator<voxalgo::ChangingLight>> = {<No data fields>}, <No data fields>}, _M_start = 0x2b40a680, _M_finish = 0x2b40a680, _M_end_of_storage = 0x2b40c680}}, <No data fields>}, {<std::_Vector_base<voxalgo::ChangingLight, std::allocator<voxalgo::ChangingLight> >> = {_M_impl = {<std::allocator<voxalgo::ChangingLight>> = {<__gnu_cxx::new_allocator<voxalgo::ChangingLight>> = {<No data fields>}, <No data fields>}, _M_start = 0x2c0d7160, _M_finish = 0x2c0d7160, _M_end_of_storage = 0x2c0d9160}}, <No data fields>}, {<std::_Vector_base<voxalgo::ChangingLight, std::allocator<voxalgo::ChangingLight> >> = {_M_impl = {<std::allocator<voxalgo::ChangingLight>> = {<__gnu_cxx::new_allocator<voxalgo::ChangingLight>> = {<No data fields>}, <No data fields>}, _M_start = 0x2b71a580, _M_finish = 0x2b71a580, _M_end_of_storage = 0x2b71c580}}, <No data fields>}, {<std::_Vector_base<voxalgo::ChangingLight, std::allocator<voxalgo::ChangingLight> >> = {_M_impl = {<std::allocator<voxalgo::ChangingLight>> = {<__gnu_cxx::new_allocator<voxalgo::ChangingLight>> = {<No data fields>}, <No data fields>}, _M_start = 0x2c16c5d0, _M_finish = 0x2c16c5d0, _M_end_of_storage = 0x2c16e5d0}}, <No data fields>}, {<std::_Vector_base<voxalgo::ChangingLight, std::allocator<voxalgo::ChangingLight> >> = {_M_impl = {<std::allocator<voxalgo::ChangingLight>> = {<__gnu_cxx::new_allocator<voxalgo::ChangingLight>> = {<No data fields>}, <No data fields>}, _M_start = 0x2b502b90, _M_finish = 0x2b502b90, _M_end_of_storage = 0x2b504b90}}, <No data fields>}, {<std::_Vector_base<voxalgo::ChangingLight, std::allocator<voxalgo::ChangingLight> >> = {_M_impl = {<std::allocator<voxalgo::ChangingLight>> = {<__gnu_cxx::new_allocator<voxalgo::ChangingLight>> = {<No data fields>}, <No data fields>}, _M_start = 0x2b6843d0, _M_finish = 0x2b6843d0, _M_end_of_storage = 0x2b6863d0}}, <No data fields>}, {<std::_Vector_base<voxalgo::ChangingLight, std::allocator<voxalgo::ChangingLight> >> = {_M_impl = {<std::allocator<voxalgo::ChangingLight>> = {<__gnu_cxx::new_allocator<voxalgo::ChangingLight>> = {<No data fields>}, <No data fields>}, _M_start = 0x2b68b440, _M_finish = 0x2b68b440, _M_end_of_storage = 0x2b68d440}}, <No data fields>}, {<std::_Vector_base<voxalgo::ChangingLight, std::allocator<voxalgo::ChangingLight> >> = {_M_impl = {<std::allocator<voxalgo::ChangingLight>> = {<__gnu_cxx::new_allocator<voxalgo::ChangingLight>> = {<No data fields>}, <No data fields>}, _M_start = 0x2be04be0, _M_finish = 0x2be04be0, _M_end_of_storage = 0x2be06be0}}, <No data fields>}, {<std::_Vector_base<voxalgo::ChangingLight, std::allocator<voxalgo::ChangingLight> >> = {_M_impl = {<std::allocator<voxalgo::ChangingLight>> = {<__gnu_cxx::new_allocator<voxalgo::ChangingLight>> = {<No data fields>}, <No data fields>}, _M_start = 0x2c0b5bb0, _M_finish = 0x2c0b5bb0, _M_end_of_storage = 0x2c0b7bb0}}, <No data fields>}, {<std::_Vector_base<voxalgo::ChangingLight, std::allocator<voxalgo::ChangingLight> >> = {_M_impl = {<std::allocator<voxalgo::ChangingLight>> = {<__gnu_cxx::new_allocator<voxalgo::ChangingLight>> = {<No data fields>}, <No data fields>}, _M_start = 0x2b7246b0, _M_finish = 0x2b7246b0, _M_end_of_storage = 0x2b7266b0}}, <No data fields>}, {<std::_Vector_base<voxalgo::ChangingLight, std::allocator<voxalgo::ChangingLight> >> = {_M_impl = {<std::allocator<voxalgo::ChangingLight>> = {<__gnu_cxx::new_allocator<voxalgo::ChangingLight>> = {<No data fields>}, <No data fields>}, _M_start = 0x2b525690, _M_finish = 0x2b525690, _M_end_of_storage = 0x2b527690}}, <No data fields>}, {<std::_Vector_base<voxalgo::ChangingLight, std::allocator<voxalgo::ChangingLight> >> = {_M_impl = {<std::allocator<voxalgo::ChangingLight>> = {<__gnu_cxx::new_allocator<voxalgo::ChangingLight>> = {<No data fields>}, <No data fields>}, _M_start = 0x2b4dcc50, _M_finish = 0x2b4dcc50, _M_end_of_storage = 0x2b4dec50}}, <No data fields>}}, max_light = 15 '\017'}
        light_sources = {lights = {{<std::_Vector_base<voxalgo::ChangingLight, std::allocator<voxalgo::ChangingLight> >> = {_M_impl = {<std::allocator<voxalgo::ChangingLight>> = {<__gnu_cxx::new_allocator<voxalgo::ChangingLight>> = {<No data fields>}, <No data fields>}, _M_start = 0x2b14c8d0, _M_finish = 0x2b14c8d0, _M_end_of_storage = 0x2b14e8d0}}, <No data fields>}, {<std::_Vector_base<voxalgo::ChangingLight, std::allocator<voxalgo::ChangingLight> >> = {_M_impl = {<std::allocator<voxalgo::ChangingLight>> = {<__gnu_cxx::new_allocator<voxalgo::ChangingLight>> = {<No data fields>}, <No data fields>}, _M_start = 0x2b549ce0, _M_finish = 0x2b549ce0, _M_end_of_storage = 0x2b54bce0}}, <No data fields>}, {<std::_Vector_base<voxalgo::ChangingLight, std::allocator<voxalgo::ChangingLight> >> = {_M_impl = {<std::allocator<voxalgo::ChangingLight>> = {<__gnu_cxx::new_allocator<voxalgo::ChangingLight>> = {<No data fields>}, <No data fields>}, _M_start = 0x2acafd50, _M_finish = 0x2acafd50, _M_end_of_storage = 0x2acb1d50}}, <No data fields>}, {<std::_Vector_base<voxalgo::ChangingLight, std::allocator<voxalgo::ChangingLight> >> = {_M_impl = {<std::allocator<voxalgo::ChangingLight>> = {<__gnu_cxx::new_allocator<voxalgo::ChangingLight>> = {<No data fields>}, <No data fields>}, _M_start = 0x2b260930, _M_finish = 0x2b260930, _M_end_of_storage = 0x2b262930}}, <No data fields>}, {<std::_Vector_base<voxalgo::ChangingLight, std::allocator<voxalgo::ChangingLight> >> = {_M_impl = {<std::allocator<voxalgo::ChangingLight>> = {<__gnu_cxx::new_allocator<voxalgo::ChangingLight>> = {<No data fields>}, <No data fields>}, _M_start = 0x2b0c7be0, _M_finish = 0x2b0c7be0, _M_end_of_storage = 0x2b0c9be0}}, <No data fields>}, {<std::_Vector_base<voxalgo::ChangingLight, std::allocator<voxalgo::ChangingLight> >> = {_M_impl = {<std::allocator<voxalgo::ChangingLight>> = {<__gnu_cxx::new_allocator<voxalgo::ChangingLight>> = {<No data fields>}, <No data fields>}, _M_start = 0x2b285ab0, _M_finish = 0x2b285ab0, _M_end_of_storage = 0x2b287ab0}}, <No data fields>}, {<std::_Vector_base<voxalgo::ChangingLight, std::allocator<voxalgo::ChangingLight> >> = {_M_impl = {<std::allocator<voxalgo::ChangingLight>> = {<__gnu_cxx::new_allocator<voxalgo::ChangingLight>> = {<No data fields>}, <No data fields>}, _M_start = 0x2b7b0800, _M_finish = 0x2b7b0800, _M_end_of_storage = 0x2b7b2800}}, <No data fields>}, {<std::_Vector_base<voxalgo::ChangingLight, std::allocator<voxalgo::ChangingLight> >> = {_M_impl = {<std::allocator<voxalgo::ChangingLight>> = {<__gnu_cxx::new_allocator<voxalgo::ChangingLight>> = {<No data fields>}, <No data fields>}, _M_start = 0x2b75a2c0, _M_finish = 0x2b75a2c0, _M_end_of_storage = 0x2b75c2c0}}, <No data fields>}, {<std::_Vector_base<voxalgo::ChangingLight, std::allocator<voxalgo::ChangingLight> >> = {_M_impl = {<std::allocator<voxalgo::ChangingLight>> = {<__gnu_cxx::new_allocator<voxalgo::ChangingLight>> = {<No data fields>}, <No data fields>}, _M_start = 0x2b1374e0, _M_finish = 0x2b1374e0, _M_end_of_storage = 0x2b1394e0}}, <No data fields>}, {<std::_Vector_base<voxalgo::ChangingLight, std::allocator<voxalgo::ChangingLight> >> = {_M_impl = {<std::allocator<voxalgo::ChangingLight>> = {<__gnu_cxx::new_allocator<voxalgo::ChangingLight>> = {<No data fields>}, <No data fields>}, _M_start = 0x2b3ee060, _M_finish = 0x2b3ee060, _M_end_of_storage = 0x2b3f0060}}, <No data fields>}, {<std::_Vector_base<voxalgo::ChangingLight, std::allocator<voxalgo::ChangingLight> >> = {_M_impl = {<std::allocator<voxalgo::ChangingLight>> = {<__gnu_cxx::new_allocator<voxalgo::ChangingLight>> = {<No data fields>}, <No data fields>}, _M_start = 0x2b379c30, _M_finish = 0x2b379c30, _M_end_of_storage = 0x2b37bc30}}, <No data fields>}, {<std::_Vector_base<voxalgo::ChangingLight, std::allocator<voxalgo::ChangingLight> >> = {_M_impl = {<std::allocator<voxalgo::ChangingLight>> = {<__gnu_cxx::new_allocator<voxalgo::ChangingLight>> = {<No data fields>}, <No data fields>}, _M_start = 0x2bdf0ec0, _M_finish = 0x2bdf0ec0, _M_end_of_storage = 0x2bdf2ec0}}, <No data fields>}, {<std::_Vector_base<voxalgo::ChangingLight, std::allocator<voxalgo::ChangingLight> >> = {_M_impl = {<std::allocator<voxalgo::ChangingLight>> = {<__gnu_cxx::new_allocator<voxalgo::ChangingLight>> = {<No data fields>}, <No data fields>}, _M_start = 0x2b397e60, _M_finish = 0x2b397e60, _M_end_of_storage = 0x2b399e60}}, <No data fields>}, {<std::_Vector_base<voxalgo::ChangingLight, std::allocator<voxalgo::ChangingLight> >> = {_M_impl = {<std::allocator<voxalgo::ChangingLight>> = {<__gnu_cxx::new_allocator<voxalgo::ChangingLight>> = {<No data fields>}, <No data fields>}, _M_start = 0x2b2d8cc0, _M_finish = 0x2b2d8cc0, _M_end_of_storage = 0x2b2dacc0}}, <No data fields>}, {<std::_Vector_base<voxalgo::ChangingLight, std::allocator<voxalgo::ChangingLight> >> = {_M_impl = {<std::allocator<voxalgo::ChangingLight>> = {<__gnu_cxx::new_allocator<voxalgo::ChangingLight>> = {<No data fields>}, <No data fields>}, _M_start = 0x2b950bd0, _M_finish = 0x2b950bd0, _M_end_of_storage = 0x2b952bd0}}, <No data fields>}, {<std::_Vector_base<voxalgo::ChangingLight, std::allocator<voxalgo::ChangingLight> >> = {_M_impl = {<std::allocator<voxalgo::ChangingLight>> = {<__gnu_cxx::new_allocator<voxalgo::ChangingLight>> = {<No data fields>}, <No data fields>}, _M_start = 0x2b708e80, _M_finish = 0x2b708e80, _M_end_of_storage = 0x2b70ae80}}, <No data fields>}}, max_light = 15 '\017'}
        i = <optimized out>
        is_valid_position = true
#10 0x0000000000717032 in Map::addNodeAndUpdate (this=0x10958d0, p=..., n=..., modified_blocks=..., remove_metadata=remove_metadata@entry=true) at /home/crobbins/minetest/src/map.cpp:835
        ndef = 0xf85390
        rollback_oldnode = {name = {static npos = 18446744073709551615, _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, _M_p = 0x2c17b990 "default:water_flowing"}, _M_string_length = 21, {_M_local_buf = "\036", '\000' <repeats 14 times>, _M_allocated_capacity = 30}}, param1 = 221, param2 = 7, meta = {static npos = 18446744073709551615, _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, _M_p = 0x7fffffffbbb8 ""}, _M_string_length = 0, {_M_local_buf = '\000' <repeats 15 times>, _M_allocated_capacity = 0}}}
        oldnode = {param0 = 644, param1 = 221 '\335', param2 = 7 '\a'}
        oldnodes = {<std::_Vector_base<std::pair<irr::core::vector3d<short>, MapNode>, std::allocator<std::pair<irr::core::vector3d<short>, MapNode> > >> = {_M_impl = {<std::allocator<std::pair<irr::core::vector3d<short>, MapNode> >> = {<__gnu_cxx::new_allocator<std::pair<irr::core::vector3d<short>, MapNode> >> = {<No data fields>}, <No data fields>}, _M_start = 0x2b75ea10, _M_finish = 0x2b75ea1a, _M_end_of_storage = 0x2b75ea1a}}, <No data fields>}
        dirs = {{X = 1496, Y = 4, Z = 2912}, {X = 644, Y = 2013, Z = 185}, {X = 0, Y = 0, Z = -32712}, {X = 185, Y = 0, Z = 0}, {X = -32712, Y = 185, Z = 0}, {X = 0, Y = -32712, Z = 185}, {X = 0, Y = 0, Z = -32672}}
#11 0x00000000005ef55f in Client::addNode (this=this@entry=0x1910fd0, p=..., n=..., remove_metadata=true) at /home/crobbins/minetest/src/client.cpp:1377
        modified_blocks = {_M_t = {_M_impl = {<std::allocator<std::_Rb_tree_node<std::pair<irr::core::vector3d<short> const, MapBlock*> > >> = {<__gnu_cxx::new_allocator<std::_Rb_tree_node<std::pair<irr::core::vector3d<short> const, MapBlock*> > >> = {<No data fields>}, <No data fields>}, _M_key_compare = {<std::binary_function<irr::core::vector3d<short>, irr::core::vector3d<short>, bool>> = {<No data fields>}, <No data fields>}, _M_header = {_M_color = std::_S_red, _M_parent = 0x20607ef0, _M_left = 0x20607ef0, _M_right = 0x20607ef0}, _M_node_count = 1}}}
#12 0x00000000004da7f5 in Client::handleCommand_AddNode (this=0x1910fd0, pkt=0x7fffffffbf20) at /home/crobbins/minetest/src/network/clientpackethandler.cpp:278
        p = {X = 1496, Y = 4, Z = 2912}
        n = {param0 = 8292, param1 = 0 '\000', param2 = 0 '\000'}
        remove_metadata = <optimized out>
        index = <optimized out>
#13 0x00000000005eaa20 in Client::handleCommand (pkt=0x7fffffffbf20, this=0x1910fd0) at /home/crobbins/minetest/src/client.cpp:866
        opHandle = <optimized out>
#14 Client::ProcessData (this=this@entry=0x1910fd0, pkt=pkt@entry=0x7fffffffbf20) at /home/crobbins/minetest/src/client.cpp:921
        __debug_stacker = {m_stack = 0xb97b80, m_overflowed = false}
        __PRETTY_FUNCTION__ = "void Client::ProcessData(NetworkPacket*)"
        command = TOCLIENT_ADDNODE
        sender_peer_id = 1
#15 0x00000000005eabac in Client::Receive (this=this@entry=0x1910fd0) at /home/crobbins/minetest/src/client.cpp:860
        __debug_stacker = {m_stack = 0xb97b80, m_overflowed = false}
        __PRETTY_FUNCTION__ = "void Client::Receive()"
        pkt = {m_data = {<std::_Vector_base<unsigned char, std::allocator<unsigned char> >> = {_M_impl = {<std::allocator<unsigned char>> = {<__gnu_cxx::new_allocator<unsigned char>> = {<No data fields>}, <No data fields>}, _M_start = 0x2b9478c0 <incomplete sequence \330>, _M_finish = 0x2b9478cb "+", _M_end_of_storage = 0x2b9478cb "+"}}, <No data fields>}, m_datasize = 11, m_read_offset = 6, m_command = 33, m_peer_id = 1}
#16 0x00000000005eae53 in Client::ReceiveAll (this=this@entry=0x1910fd0) at /home/crobbins/minetest/src/client.cpp:841
        __debug_stacker = {m_stack = 0xb97b80, m_overflowed = false}
        __PRETTY_FUNCTION__ = "void Client::ReceiveAll()"
#17 0x00000000005ef6c3 in Client::step (this=0x1910fd0, dtime=0.0160000008) at /home/crobbins/minetest/src/client.cpp:355
        __debug_stacker = {m_stack = 0xb97b80, m_overflowed = false}
        __PRETTY_FUNCTION__ = "void Client::step(float)"
        initial_step = false
        map_timer_and_unload_dtime = <optimized out>
        counter = <optimized out>
#18 0x0000000000692a48 in Game::step (dtime=0x7fffffffc1fc, this=0x7fffffffc5c0) at /home/crobbins/minetest/src/game.cpp:3450
        dtime = 0x7fffffffc1fc
        this = 0x7fffffffc5c0
#19 Game::run (this=this@entry=0x7fffffffc5c0) at /home/crobbins/minetest/src/game.cpp:2048
        cam_smoothing = <optimized out>
        graph = {m_log = {<std::_Deque_base<ProfilerGraph::Piece, std::allocator<ProfilerGraph::Piece> >> = {_M_impl = {<std::allocator<ProfilerGraph::Piece>> = {<__gnu_cxx::new_allocator<ProfilerGraph::Piece>> = {<No data fields>}, <No data fields>}, _M_map = 0x205a09f0, _M_map_size = 78, _M_start = {_M_cur = 0x2b420230, _M_first = 0x2b4200e0, _M_last = 0x2b4202c0, _M_node = 0x205a0b78}, _M_finish = {_M_cur = 0x2b4fe6e0, _M_first = 0x2b4fe590, _M_last = 0x2b4fe770, _M_node = 0x205a0c18}}}, <No data fields>}, m_log_max_size = 200}
        stats = {drawtime = 16, beginscenetime = 0, endscenetime = 14, dtime_jitter = {max = 0.000328263268, min = 0, avg = 0.0166644678, counter = -2.43309832, max_sample = 0.00321418419, min_sample = 0, max_fraction = 0.181787714}, busy_time_jitter = {max = 0, min = -3318.85425, avg = 3334.85425, counter = -2.43309832, max_sample = 0, min_sample = -3307.51147, max_fraction = 0}}
        cam_view_target = {camera_yaw = 310.40036, camera_pitch = 4.9000268}
        cam_view = {camera_yaw = 310.40036, camera_pitch = 4.9000268}
        draw_times = {last_time = 210462, busy_time = 16, sleep_time = 0}
        dtime = 0.0160000008
        dummyvalues = {_M_t = {_M_impl = {<std::allocator<std::_Rb_tree_node<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, float> > >> = {<__gnu_cxx::new_allocator<std::_Rb_tree_node<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, float> > >> = {<No data fields>}, <No data fields>}, _M_key_compare = {<std::binary_function<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool>> = {<No data fields>}, <No data fields>}, _M_header = {_M_color = std::_S_red, _M_parent = 0x20101c00, _M_left = 0x20100a00, _M_right = 0x20100960}, _M_node_count = 4}}}
#20 0x000000000069478c in the_game (kill=kill@entry=0xb26700 <porting::g_killed>, random_input=<optimized out>, input=0xf1c3f0, device=0xbb0ad0, map_dir=..., playername=..., password=..., address=..., port=30000, error_message=..., chat_backend=..., reconnect_requested=0x7fffffffcf0f, gamespec=..., simple_singleplayer_mode=false) at /home/crobbins/minetest/src/game.cpp:4714
        game = {input = 0xf1c3f0, client = 0x1910fd0, server = 0x0, texture_src = 0xf851c0, shader_src = 0x108a700, itemdef_manager = 0x108d180, nodedef_manager = 0xf85390, soundfetcher = {<OnDemandSoundFetcher> = {_vptr.OnDemandSoundFetcher = 0x84cc90 <vtable for GameOnDemandSoundFetcher+16>}, m_fetched = {_M_t = {_M_impl = {<std::allocator<std::_Rb_tree_node<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >> = {<__gnu_cxx::new_allocator<std::_Rb_tree_node<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >> = {<No data fields>}, <No data fields>}, _M_key_compare = {<std::binary_function<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool>> = {<No data fields>}, <No data fields>}, _M_header = {_M_color = std::_S_red, _M_parent = 0x0, _M_left = 0x7fffffffc608, _M_right = 0x7fffffffc608}, _M_node_count = 0}}}}, sound = 0xfbc710, sound_is_dummy = false, soundmaker = 0x104cdf0, chat_backend = 0x7fffffffd0b0, current_formspec = 0x0, cur_formname = {static npos = 18446744073709551615, _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, _M_p = 0x7fffffffc668 ""}, _M_string_length = 0, {_M_local_buf = "\000ews\000\000\000\000`{\245\363\377\177\000", _M_allocated_capacity = 1937204480}}, eventmgr = 0x1057ed0, quicktune = 0x104f6b0, gui_chat_console = 0x1ffb2a20, draw_control = 0xeaa5b0, camera = 0x1ff900d0, clouds = 0x1ffc82d0, sky = 0x1ffe1570, local_inventory = 0x1ff7e7f0, hud = 0x20100a70, mapper = 0x109a800, runData = {dig_index = 0, new_playeritem = 0, pointed_old = {type = POINTEDTHING_NOTHING, node_undersurface = {X = 0, Y = 0, Z = 0}, node_abovesurface = {X = 0, Y = 0, Z = 0}, object_id = -1}, digging = false, ldown_for_dig = false, left_punch = false, update_wielded_item_trigger = false, reset_jump_timer = false, nodig_delay_timer = -6.26399994, dig_time = 0, dig_time_complete = 0, repeat_rightclick_timer = 0, object_hit_delay_timer = -6.26399994, time_from_last_punch = 196.563217, selected_object = 0x0, jump_timer = 0, damage_flash = 0, update_draw_list_timer = 0.0340000018, statustext_time = 0, fog_range = 900, update_draw_list_last_cam_dir = {X = 0.758751154, Y = -0.0854173899, Z = 0.645755887}, profiler_current_page = 0, profiler_max_page = 3, time_of_day = 0.994258821, time_of_day_smooth = 0.993994117}, flags = {invert_mouse = false, show_chat = true, show_hud = true, show_minimap = false, force_fog_off = false, show_debug = false, show_profiler_graph = false, disable_camera_update = false, first_loop_after_window_activation = true, camera_offset_changed = false}, device = 0xbb0ad0, driver = 0xef4f30, smgr = 0xf25a60, kill = 0xb26700 <porting::g_killed>, error_message = 0x7fffffffcf10, reconnect_requested = 0x7fffffffcf0f, gamedef = 0x1910fe0, skybox = 0x0, random_input = false, simple_singleplayer_mode = false, crack_animation_length = 5, guitext = 0x1ffb54a0, guitext2 = 0x1ffb56a0, guitext_info = 0x1ffb58d0, guitext_status = 0x1ffb2420, guitext_chat = 0x1ffb2660, guitext_profiler = 0x201003e0, infotext = {static npos = 18446744073709551615, _M_dataplus = {<std::allocator<wchar_t>> = {<__gnu_cxx::new_allocator<wchar_t>> = {<No data fields>}, <No data fields>}, _M_p = 0x2402b520 L""}, _M_string_length = 0, {_M_local_buf = L"?\000\xffffcc20ç¿¿", _M_allocated_capacity = 63}}, statustext = {static npos = 18446744073709551615, _M_dataplus = {<std::allocator<wchar_t>> = {<__gnu_cxx::new_allocator<wchar_t>> = {<No data fields>}, <No data fields>}, _M_p = 0x7fffffffc7f0 L""}, _M_string_length = 0, {_M_local_buf = L"\000ç¿¿\xffffe0a0ç¿¿", _M_allocated_capacity = 140733193388032}}, keycache = {key = {{Key = irr::KEY_KEY_W, Char = 87 L'W', m_name = {static npos = 18446744073709551615, _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, _M_p = 0x7fffffffc818 "KEY_KEY_W"}, _M_string_length = 9, {_M_local_buf = "KEY_KEY_W\000\377\377\377\177\000", _M_allocated_capacity = 6870598896554952011}}}, {Key = irr::KEY_KEY_S, Char = 83 L'S', m_name = {static npos = 18446744073709551615, _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, _M_p = 0x7fffffffc840 "KEY_KEY_S"}, _M_string_length = 9, {_M_local_buf = "KEY_KEY_S\000\377\377\377\177\000", _M_allocated_capacity = 6870598896554952011}}}, {Key = irr::KEY_KEY_A, Char = 65 L'A', m_name = {static npos = 18446744073709551615, _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, _M_p = 0x7fffffffc868 "KEY_KEY_A"}, _M_string_length = 9, {_M_local_buf = "KEY_KEY_A\000\000\000\000\000\000", _M_allocated_capacity = 6870598896554952011}}}, {Key = irr::KEY_KEY_D, Char = 68 L'D', m_name = {static npos = 18446744073709551615, _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, _M_p = 0x7fffffffc890 "KEY_KEY_D"}, _M_string_length = 9, {_M_local_buf = "KEY_KEY_D\000\377\377\377\177\000", _M_allocated_capacity = 6870598896554952011}}}, {Key = irr::KEY_SPACE, Char = 0 L'\000', m_name = {static npos = 18446744073709551615, _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, _M_p = 0x7fffffffc8b8 "KEY_SPACE"}, _M_string_length = 9, {_M_local_buf = "KEY_SPACE\000\000\000\000\000\000", _M_allocated_capacity = 4846242993039557963}}}, {Key = irr::KEY_KEY_E, Char = 69 L'E', m_name = {static npos = 18446744073709551615, _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, _M_p = 0x7fffffffc8e0 "KEY_KEY_E"}, _M_string_length = 9, {_M_local_buf = "KEY_KEY_E\000\000\000\061\000\000", _M_allocated_capacity = 6870598896554952011}}}, {Key = irr::KEY_LSHIFT, Char = 0 L'\000', m_name = {static npos = 18446744073709551615, _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, _M_p = 0x7fffffffc908 "KEY_LSHIFT"}, _M_string_length = 10, {_M_local_buf = "KEY_LSHIFT\000\377\377\177\000", _M_allocated_capacity = 5280562150574212427}}}, {Key = irr::KEY_KEY_CODES_COUNT, Char = 0 L'\000', m_name = {static npos = 18446744073709551615, _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, _M_p = 0x7fffffffc930 ""}, _M_string_length = 0, {_M_local_buf = "\000\311\377\377\377\177\000\000\b\000\000\000\000\000\000", _M_allocated_capacity = 140737488341248}}}, {Key = irr::KEY_ESCAPE, Char = 0 L'\000', m_name = {static npos = 18446744073709551615, _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, _M_p = 0x7fffffffc958 "KEY_ESCAPE"}, _M_string_length = 10, {_M_local_buf = "KEY_ESCAPE\000\367\377\177\000", _M_allocated_capacity = 4702693993322464587}}}, {Key = irr::KEY_KEY_Q, Char = 81 L'Q', m_name = {static npos = 18446744073709551615, _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, _M_p = 0x7fffffffc980 "KEY_KEY_Q"}, _M_string_length = 9, {_M_local_buf = "KEY_KEY_Q\000K\367\377\177\000", _M_allocated_capacity = 6870598896554952011}}}, {Key = irr::KEY_KEY_I, Char = 73 L'I', m_name = {static npos = 18446744073709551615, _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, _M_p = 0x7fffffffc9a8 "KEY_KEY_I"}, _M_string_length = 9, {_M_local_buf = "KEY_KEY_I\000\377\377\377\177\000", _M_allocated_capacity = 6870598896554952011}}}, {Key = irr::KEY_KEY_T, Char = 84 L'T', m_name = {static npos = 18446744073709551615, _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, _M_p = 0x7fffffffc9d0 "KEY_KEY_T"}, _M_string_length = 9, {_M_local_buf = "KEY_KEY_T\000\000\000\000\000\000", _M_allocated_capacity = 6870598896554952011}}}, {Key = irr::KEY_KEY_CODES_COUNT, Char = 47 L'/', m_name = {static npos = 18446744073709551615, _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, _M_p = 0x7fffffffc9f8 "/"}, _M_string_length = 1, {_M_local_buf = "/\000\000\000\000\000\000\000minetest", _M_allocated_capacity = 47}}}, {Key = irr::KEY_F10, Char = 0 L'\000', m_name = {static npos = 18446744073709551615, _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, _M_p = 0x7fffffffca20 "KEY_F10"}, _M_string_length = 7, {_M_local_buf = "KEY_F10\000H\341\377\367\377\177\000", _M_allocated_capacity = 13564977199269195}}}, {Key = irr::KEY_F9, Char = 0 L'\000', m_name = {static npos = 18446744073709551615, _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, _M_p = 0x7fffffffca48 "KEY_F9"}, _M_string_length = 6, {_M_local_buf = "KEY_F9\000\000\262\035\000\000\000\000\000", _M_allocated_capacity = 62974410179915}}}, {Key = irr::KEY_KEY_K, Char = 75 L'K', m_name = {static npos = 18446744073709551615, _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, _M_p = 0x7fffffffca70 "KEY_KEY_K"}, _M_string_length = 9, {_M_local_buf = "KEY_KEY_K\000\240\364\377\177\000", _M_allocated_capacity = 6870598896554952011}}}, {Key = irr::KEY_KEY_J, Char = 74 L'J', m_name = {static npos = 18446744073709551615, _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, _M_p = 0x7fffffffca98 "KEY_KEY_J"}, _M_string_length = 9, {_M_local_buf = "KEY_KEY_J\000\273\000\000\000\000", _M_allocated_capacity = 6870598896554952011}}}, {Key = irr::KEY_KEY_H, Char = 72 L'H', m_name = {static npos = 18446744073709551615, _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, _M_p = 0x7fffffffcac0 "KEY_KEY_H"}, _M_string_length = 9, {_M_local_buf = "KEY_KEY_H\000\000\000\000\000\000", _M_allocated_capacity = 6870598896554952011}}}, {Key = irr::KEY_KEY_CODES_COUNT, Char = 0 L'\000', m_name = {static npos = 18446744073709551615, _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, _M_p = 0x7fffffffcae8 ""}, _M_string_length = 0, {_M_local_buf = "\000\000\000\000\000\000\000\000\020\313\377\377\377\177\000", _M_allocated_capacity = 0}}}, {Key = irr::KEY_F12, Char = 0 L'\000', m_name = {static npos = 18446744073709551615, _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, _M_p = 0x7fffffffcb10 "KEY_F12"}, _M_string_length = 7, {_M_local_buf = "KEY_F12\000\200~\377\367\377\177\000", _M_allocated_capacity = 14127927152690507}}}, {Key = irr::KEY_F1, Char = 0 L'\000', m_name = {static npos = 18446744073709551615, _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, _M_p = 0x7fffffffcb38 "KEY_F1"}, _M_string_length = 6, {_M_local_buf = "KEY_F1\000\000\000\000\000\000\000\000\000", _M_allocated_capacity = 54178317157707}}}, {Key = irr::KEY_F2, Char = 0 L'\000', m_name = {static npos = 18446744073709551615, _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, _M_p = 0x7fffffffcb60 "KEY_F2"}, _M_string_length = 6, {_M_local_buf = "KEY_F2\000\000\000\351\240I\305\346\337O", _M_allocated_capacity = 55277828785483}}}, {Key = irr::KEY_F3, Char = 0 L'\000', m_name = {static npos = 18446744073709551615, _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, _M_p = 0x7fffffffcb88 "KEY_F3"}, _M_string_length = 6, {_M_local_buf = "KEY_F3\000\000\310F\273\000\000\000\000", _M_allocated_capacity = 56377340413259}}}, {Key = irr::KEY_KEY_CODES_COUNT, Char = 0 L'\000', m_name = {static npos = 18446744073709551615, _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, _M_p = 0x7fffffffcbb0 ""}, _M_string_length = 0, {_M_local_buf = "\000\314\377\377\377\177\000\000\b\314\377\377\377\177\000", _M_allocated_capacity = 140737488342016}}}, {Key = irr::KEY_F5, Char = 0 L'\000', m_name = {static npos = 18446744073709551615, _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, _M_p = 0x7fffffffcbd8 "KEY_F5"}, _M_string_length = 6, {_M_local_buf = "KEY_F5\000\000\020\314\377\377\377\177\000", _M_allocated_capacity = 58576363668811}}}, {Key = irr::KEY_F6, Char = 0 L'\000', m_name = {static npos = 18446744073709551615, _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, _M_p = 0x7fffffffcc00 "KEY_F6"}, _M_string_length = 6, {_M_local_buf = "KEY_F6\000\000\000\000\000\000\000\000\000", _M_allocated_capacity = 59675875296587}}}, {Key = irr::KEY_F7, Char = 0 L'\000', m_name = {static npos = 18446744073709551615, _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, _M_p = 0x7fffffffcc28 "KEY_F7"}, _M_string_length = 6, {_M_local_buf = "KEY_F7\000\000\000\000\000\000\000\000\000", _M_allocated_capacity = 60775386924363}}}, {Key = irr::KEY_PLUS, Char = 43 L'+', m_name = {static npos = 18446744073709551615, _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, _M_p = 0x7fffffffcc50 "KEY_PLUS"}, _M_string_length = 8, {_M_local_buf = "KEY_PLUS\000\n\273\000\000\000\000", _M_allocated_capacity = 6004789586249205067}}}, {Key = irr::KEY_MINUS, Char = 45 L'-', m_name = {static npos = 18446744073709551615, _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, _M_p = 0x7fffffffcc78 "KEY_MINUS"}, _M_string_length = 9, {_M_local_buf = "KEY_MINUS\000\377\377\377\177\000", _M_allocated_capacity = 6146931138068301131}}}, {Key = irr::KEY_KEY_R, Char = 82 L'R', m_name = {static npos = 18446744073709551615, _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, _M_p = 0x7fffffffcca0 "KEY_KEY_R"}, _M_string_length = 9, {_M_local_buf = "KEY_KEY_R\000\000\000\000\000\000", _M_allocated_capacity = 6870598896554952011}}}, {Key = irr::KEY_KEY_Z, Char = 90 L'Z', m_name = {static npos = 18446744073709551615, _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, _M_p = 0x7fffffffccc8 "KEY_KEY_Z"}, _M_string_length = 9, {_M_local_buf = "KEY_KEY_Z\000mazin", _M_allocated_capacity = 6870598896554952011}}}, {Key = irr::KEY_END, Char = 0 L'\000', m_name = {static npos = 18446744073709551615, _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, _M_p = 0x7fffffffccf0 "KEY_END"}, _M_string_length = 7, {_M_local_buf = "KEY_END\000\b\315\377\377\377\177\000", _M_allocated_capacity = 19226358275720523}}}, {Key = irr::KEY_HOME, Char = 0 L'\000', m_name = {static npos = 18446744073709551615, _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, _M_p = 0x7fffffffcd18 "KEY_HOME"}, _M_string_length = 8, {_M_local_buf = "KEY_HOME\000\242\370\000\000\000\000", _M_allocated_capacity = 4993734734079673675}}}, {Key = irr::KEY_PRIOR, Char = 0 L'\000', m_name = {static npos = 18446744073709551615, _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, _M_p = 0x7fffffffcd40 "KEY_PRIOR"}, _M_string_length = 9, {_M_local_buf = "KEY_PRIOR\000\262\000\000\000\000", _M_allocated_capacity = 5713188107446732107}}}, {Key = irr::KEY_NEXT, Char = 0 L'\000', m_name = {static npos = 18446744073709551615, _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, _M_p = 0x7fffffffcd68 "KEY_NEXT"}, _M_string_length = 8, {_M_local_buf = "KEY_NEXT\000#\371\000\000\000\000", _M_allocated_capacity = 6077683900045935947}}}, {Key = irr::KEY_KEY_P, Char = 80 L'P', m_name = {static npos = 18446744073709551615, _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, _M_p = 0x7fffffffcd90 "KEY_KEY_P"}, _M_string_length = 9, {_M_local_buf = "KEY_KEY_P\000\000\000\000\000\000", _M_allocated_capacity = 6870598896554952011}}}, {Key = irr::KEY_KEY_CODES_COUNT, Char = 0 L'\000', m_name = {static npos = 18446744073709551615, _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, _M_p = 0x7fffffffcdb8 ""}, _M_string_length = 0, {_M_local_buf = "\000\000\000\000\000\000\000\000@\316\377\377\377\177\000", _M_allocated_capacity = 0}}}, {Key = irr::KEY_KEY_CODES_COUNT, Char = 0 L'\000', m_name = {static npos = 18446744073709551615, _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, _M_p = 0x7fffffffcde0 ""}, _M_string_length = 0, {_M_local_buf = "\000\000\000\000\000\000\000\000\377\377\377\377\377\377\377\377", _M_allocated_capacity = 0}}}, {Key = irr::KEY_KEY_CODES_COUNT, Char = 0 L'\000', m_name = {static npos = 18446744073709551615, _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, _M_p = 0x7fffffffce08 ""}, _M_string_length = 0, {_M_local_buf = "\000\000\000\000\000\000\000\000\005\000\000\000\000\000\000", _M_allocated_capacity = 0}}}, {Key = irr::KEY_KEY_CODES_COUNT, Char = 0 L'\000', m_name = {static npos = 18446744073709551615, _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, _M_p = 0x7fffffffce30 ""}, _M_string_length = 0, {_M_local_buf = "\000\000\000\000\000\000\000\000\037\370|\000\000\000\000", _M_allocated_capacity = 0}}}}, handler = 0xf1c3f0}, profiler_interval = {m_accumulator = 1.56702662}, m_cache_doubletap_jump = false, m_cache_enable_clouds = true, m_cache_enable_joysticks = false, m_cache_enable_particles = true, m_cache_enable_fog = true, m_cache_enable_noclip = true, m_cache_enable_free_move = false, m_cache_mouse_sensitivity = 0.200000003, m_cache_joystick_frustum_sensitivity = 170, m_repeat_right_click_time = 0.25}
        server_address = {static npos = 18446744073709551615, _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, _M_p = 0x7fffffffc4f0 "51.254.216.93"}, _M_string_length = 13, {_M_local_buf = "51.254.216.93\000\000", _M_allocated_capacity = 3615884953904886069}}
#21 0x00000000004c3403 in ClientLauncher::run (this=this@entry=0x7fffffffe1a0, game_params=..., cmd_args=...) at /home/crobbins/minetest/src/client/clientlauncher.cpp:263
        game_has_run = <optimized out>
        text = <optimized out>
        video_driver = <optimized out>
        camera = <optimized out>
        chat_backend = {m_console_buffer = {m_scrollback = 500, m_unformatted = {<std::_Vector_base<ChatLine, std::allocator<ChatLine> >> = {_M_impl = {<std::allocator<ChatLine>> = {<__gnu_cxx::new_allocator<ChatLine>> = {<No data fields>}, <No data fields>}, _M_start = 0x2b51fe50, _M_finish = 0x2b520758, _M_end_of_storage = 0x2b520f50}}, <No data fields>}, m_cols = 0, m_rows = 0, m_scroll = 0, m_formatted = {<std::_Vector_base<ChatFormattedLine, std::allocator<ChatFormattedLine> >> = {_M_impl = {<std::allocator<ChatFormattedLine>> = {<__gnu_cxx::new_allocator<ChatFormattedLine>> = {<No data fields>}, <No data fields>}, _M_start = 0x0, _M_finish = 0x0, _M_end_of_storage = 0x0}}, <No data fields>}, m_empty_formatted_line = {fragments = {<std::_Vector_base<ChatFormattedFragment, std::allocator<ChatFormattedFragment> >> = {_M_impl = {<std::allocator<ChatFormattedFragment>> = {<__gnu_cxx::new_allocator<ChatFormattedFragment>> = {<No data fields>}, <No data fields>}, _M_start = 0x0, _M_finish = 0x0, _M_end_of_storage = 0x0}}, <No data fields>}, first = true}}, m_recent_buffer = {m_scrollback = 6, m_unformatted = {<std::_Vector_base<ChatLine, std::allocator<ChatLine> >> = {_M_impl = {<std::allocator<ChatLine>> = {<__gnu_cxx::new_allocator<ChatLine>> = {<No data fields>}, <No data fields>}, _M_start = 0x2af73f50, _M_finish = 0x2af74280, _M_end_of_storage = 0x2af74390}}, <No data fields>}, m_cols = 0, m_rows = 0, m_scroll = 0, m_formatted = {<std::_Vector_base<ChatFormattedLine, std::allocator<ChatFormattedLine> >> = {_M_impl = {<std::allocator<ChatFormattedLine>> = {<__gnu_cxx::new_allocator<ChatFormattedLine>> = {<No data fields>}, <No data fields>}, _M_start = 0x0, _M_finish = 0x0, _M_end_of_storage = 0x0}}, <No data fields>}, m_empty_formatted_line = {fragments = {<std::_Vector_base<ChatFormattedFragment, std::allocator<ChatFormattedFragment> >> = {_M_impl = {<std::allocator<ChatFormattedFragment>> = {<__gnu_cxx::new_allocator<ChatFormattedFragment>> = {<No data fields>}, <No data fields>}, _M_start = 0x0, _M_finish = 0x0, _M_end_of_storage = 0x0}}, <No data fields>}, first = true}}, m_prompt = {m_prompt = {static npos = 18446744073709551615, _M_dataplus = {<std::allocator<wchar_t>> = {<__gnu_cxx::new_allocator<wchar_t>> = {<No data fields>}, <No data fields>}, _M_p = 0x7fffffffd190 L"]"}, _M_string_length = 1, {_M_local_buf = L"]\000\000", _M_allocated_capacity = 93}}, m_line = {static npos = 18446744073709551615, _M_dataplus = {<std::allocator<wchar_t>> = {<__gnu_cxx::new_allocator<wchar_t>> = {<No data fields>}, <No data fields>}, _M_p = 0x7fffffffd1b0 L""}, _M_string_length = 0, {_M_local_buf = L"\000ç¿¿\000", _M_allocated_capacity = 140733193388032}}, m_history = {<std::_Vector_base<std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> >, std::allocator<std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> > > >> = {_M_impl = {<std::allocator<std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> > >> = {<__gnu_cxx::new_allocator<std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> > >> = {<No data fields>}, <No data fields>}, _M_start = 0x0, _M_finish = 0x0, _M_end_of_storage = 0x0}}, <No data fields>}, m_history_index = 0, m_history_limit = 500, m_cols = 0, m_view = 0, m_cursor = 0, m_cursor_len = 0, m_nick_completion_start = 0, m_nick_completion_end = 0}}
        error_message = {static npos = 18446744073709551615, _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, _M_p = 0x7fffffffcf20 ""}, _M_string_length = 0, {_M_local_buf = "\000ain\000\000\000\000\240\316\377\377\377\177\000", _M_allocated_capacity = 1852399872}}
        reconnect_requested = false
        first_loop = false
        retval = true
#22 0x00000000004bb3e6 in main (argc=<optimized out>, argv=<optimized out>) at /home/crobbins/minetest/src/main.cpp:225
        game_params = {socket_port = 30000, world_path = {static npos = 18446744073709551615, _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, _M_p = 0xbb03a0 "/home/crobbins/.minetest/worlds/world"}, _M_string_length = 37, {_M_local_buf = "%\000\000\000\000\000\000\000]\275\064\001\000\000\000", _M_allocated_capacity = 37}}, game_spec = {id = {static npos = 18446744073709551615, _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, _M_p = 0x7fffffffe0d8 "minetest"}, _M_string_length = 8, {_M_local_buf = "minetest\000\341\377\377\377\177\000", _M_allocated_capacity = 8391162081313712493}}, path = {static npos = 18446744073709551615, _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, _M_p = 0xbb0900 "/home/crobbins/.minetest/games/minetest_game"}, _M_string_length = 44, {_M_local_buf = ",\000\000\000\000\000\000\000C\000\000\000\000\000\000", _M_allocated_capacity = 44}}, gamemods_path = {static npos = 18446744073709551615, _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, _M_p = 0xbb0570 "/home/crobbins/.minetest/games/minetest_game/mods"}, _M_string_length = 49, {_M_local_buf = "1\000\000\000\000\000\000\000\037\000\000\000\000\000\000", _M_allocated_capacity = 49}}, addon_mods_paths = {_M_t = {_M_impl = {<std::allocator<std::_Rb_tree_node<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >> = {<__gnu_cxx::new_allocator<std::_Rb_tree_node<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >> = {<No data fields>}, <No data fields>}, _M_key_compare = {<std::binary_function<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool>> = {<No data fields>}, <No data fields>}, _M_header = {_M_color = std::_S_red, _M_parent = 0xbb0770, _M_left = 0xbb0770, _M_right = 0xbb0770}, _M_node_count = 1}}}, name = {static npos = 18446744073709551615, _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, _M_p = 0x7fffffffe168 "Minetest Game"}, _M_string_length = 13, {_M_local_buf = "Minetest Game\000\000", _M_allocated_capacity = 8391162081313712461}}, menuicon_path = {static npos = 18446744073709551615, _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, _M_p = 0xbb0350 "/home/crobbins/.minetest/games/minetest_game/menu/icon.png"}, _M_string_length = 58, {_M_local_buf = ":\000\000\000\000\000\000\000\361I\265$\000\000\000", _M_allocated_capacity = 58}}}, is_dedicated_server = false}
        launcher = {list_video_modes = false, skip_main_menu = false, use_freetype = true, random_input = false, address = {static npos = 18446744073709551615, _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, _M_p = 0x7fffffffe1b8 "51.254.216.93"}, _M_string_length = 13, {_M_local_buf = "51.254.216.93\000\000", _M_allocated_capacity = 3615884953904886069}}, playername = {static npos = 18446744073709551615, _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, _M_p = 0x7fffffffe1d8 "Zeno"}, _M_string_length = 4, {_M_local_buf = "Zeno\000\000\000\000\224\004\066\f\000\000\000", _M_allocated_capacity = 1869505882}}, password = {static npos = 18446744073709551615, _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, _M_p = 0x7fffffffe1f8 "d3mazin"}, _M_string_length = 7, {_M_local_buf = "d3mazin\000\250\001\347\355\000\000\000", _M_allocated_capacity = 31078221779645284}}, device = 0xbb0ad0, input = 0xf1c3f0, receiver = 0xbb07c0, skin = 0xf19e20, font = 0x0, smgr = 0xf25a60, gamespec = {id = {static npos = 18446744073709551615, _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, _M_p = 0x7fffffffe248 ""}, _M_string_length = 0, {_M_local_buf = "\000\253\336\367\377\177\000\000\037\000\000\000\000\000\000", _M_allocated_capacity = 140737351953152}}, path = {static npos = 18446744073709551615, _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, _M_p = 0x7fffffffe268 ""}, _M_string_length = 0, {_M_local_buf = "\000q\262\000\000\000\000\000\310q\262\000\000\000\000", _M_allocated_capacity = 11694336}}, gamemods_path = {static npos = 18446744073709551615, _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, _M_p = 0x7fffffffe288 ""}, _M_string_length = 0, {_M_local_buf = "\000\343\377\377\377\177\000\000\002\000\000\000\000\000\000", _M_allocated_capacity = 140737488347904}}, addon_mods_paths = {_M_t = {_M_impl = {<std::allocator<std::_Rb_tree_node<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >> = {<__gnu_cxx::new_allocator<std::_Rb_tree_node<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >> = {<No data fields>}, <No data fields>}, _M_key_compare = {<std::binary_function<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool>> = {<No data fields>}, <No data fields>}, _M_header = {_M_color = std::_S_red, _M_parent = 0x0, _M_left = 0x7fffffffe2a0, _M_right = 0x7fffffffe2a0}, _M_node_count = 0}}}, name = {static npos = 18446744073709551615, _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, _M_p = 0x7fffffffe2d8 ""}, _M_string_length = 0, {_M_local_buf = "\000\000\000\000\060\000\000\000\000\000\000\000\000\000\000", _M_allocated_capacity = 206158430208}}, menuicon_path = {static npos = 18446744073709551615, _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, _M_p = 0x7fffffffe2f8 ""}, _M_string_length = 0, {_M_local_buf = '\000' <repeats 15 times>, _M_allocated_capacity = 0}}}, worldspec = {path = {static npos = 18446744073709551615, _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, _M_p = 0xf91270 "/home/crobbins/.minetest/worlds/world"}, _M_string_length = 37, {_M_local_buf = "%", '\000' <repeats 14 times>, _M_allocated_capacity = 37}}, name = {static npos = 18446744073709551615, _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, _M_p = 0xf92120 "[--world parameter] [new]"}, _M_string_length = 25, {_M_local_buf = "\036\000\000\000\000\000\000\000\001\000\000\000\000\000\000", _M_allocated_capacity = 30}}, gameid = {static npos = 18446744073709551615, _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, _M_p = 0x7fffffffe358 "minetest"}, _M_string_length = 8, {_M_local_buf = "minetest\000\000\000\000\000\000\000", _M_allocated_capacity = 8391162081313712493}}}, simple_singleplayer_mode = false, current_playername = {static npos = 18446744073709551615, _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, _M_p = 0x7fffffffe380 "Zeno"}, _M_string_length = 4, {_M_local_buf = "Zeno\000lid\000\000\000\000\000\000\000", _M_allocated_capacity = 7235433025472718170}}, current_password = {static npos = 18446744073709551615, _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, _M_p = 0x7fffffffe3a0 "d3mazin"}, _M_string_length = 7, {_M_local_buf = "d3mazin\000P[a\000\000\000\000", _M_allocated_capacity = 31078221779645284}}, current_address = {static npos = 18446744073709551615, _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, _M_p = 0x7fffffffe3c0 "51.254.216.93"}, _M_string_length = 13, {_M_local_buf = "51.254.216.93\000\000", _M_allocated_capacity = 3615884953904886069}}, current_port = 30000}
        retval = <optimized out>
        cmd_args = {m_settings = {_M_t = {_M_impl = {<std::allocator<std::_Rb_tree_node<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, SettingsEntry> > >> = {<__gnu_cxx::new_allocator<std::_Rb_tree_node<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, SettingsEntry> > >> = {<No data fields>}, <No data fields>}, _M_key_compare = {<std::binary_function<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool>> = {<No data fields>}, <No data fields>}, _M_header = {_M_color = std::_S_red, _M_parent = 0xb97650, _M_left = 0xb97650, _M_right = 0xb97650}, _M_node_count = 1}}}, m_defaults = {_M_t = {_M_impl = {<std::allocator<std::_Rb_tree_node<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, SettingsEntry> > >> = {<__gnu_cxx::new_allocator<std::_Rb_tree_node<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, SettingsEntry> > >> = {<No data fields>}, <No data fields>}, _M_key_compare = {<std::binary_function<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool>> = {<No data fields>}, <No data fields>}, _M_header = {_M_color = std::_S_red, _M_parent = 0x0, _M_left = 0x7fffffffdff8, _M_right = 0x7fffffffdff8}, _M_node_count = 0}}}, m_callbacks = {_M_t = {_M_impl = {<std::allocator<std::_Rb_tree_node<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::vector<std::pair<void (*)(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, void*), void*>, std::allocator<std::pair<void (*)(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, void*), void*> > > > > >> = {<__gnu_cxx::new_allocator<std::_Rb_tree_node<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::vector<std::pair<void (*)(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, void*), void*>, std::allocator<std::pair<void (*)(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, void*), void*> > > > > >> = {<No data fields>}, <No data fields>}, _M_key_compare = {<std::binary_function<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool>> = {<No data fields>}, <No data fields>}, _M_header = {_M_color = std::_S_red, _M_parent = 0x0, _M_left = 0x7fffffffe028, _M_right = 0x7fffffffe028}, _M_node_count = 0}}}, m_callback_mutex = {mutex = {__data = {__lock = 0, __count = 0, __owner = 0, __nusers = 0, __kind = 0, __spins = 0, __elision = 0, __list = {__prev = 0x0, __next = 0x0}}, __size = '\000' <repeats 39 times>, __align = 0}}, m_mutex = {mutex = {__data = {__lock = 0, __count = 0, __owner = 0, __nusers = 0, __kind = 0, __spins = 0, __elision = 0, __list = {__prev = 0x0, __next = 0x0}}, __size = '\000' <repeats 39 times>, __align = 0}}}
        cmd_args_ok = <optimized out>
        __debug_stacker = {m_stack = 0xb97b80, m_overflowed = false}
        __PRETTY_FUNCTION__ = "int main(int, char**)"

```

### PR DESCRIPTION
**Pull request by juhdanad**
Fixes #4807.
This commit limits nodes' light_source to 14.
Some old servers send nodes with light_source>15.

### CODE REVIEW

**Comment by est31** [comment]
I know that players who have underground farms won't like it, but we can't help. One only has to adjust the farming code to allow smaller light levels for growth...

:+1: if the pointed out issue is fixed.

File: src/script/common/c_content.cpp [hunk 1]
```diff
@@ -526,6 +526,9 @@ ContentFeatures read_content_features(lua_State *L, int index)
 	// Amount of light the node emits
 	f.light_source = getintfield_default(L, index,
 			"light_source", f.light_source);
+	if (f.light_source > LIGHT_MAX) {
+		f.light_source = LIGHT_MAX;
```
Comment (juhdanad) [inline src/script/common/c_content.cpp]: It is normally emitted in lua. It is just here if somebody overwrites minetest.register_node().

Comment (est31) [inline src/script/common/c_content.cpp]: I see, okay then.

Comment (paramat) [inline src/script/common/c_content.cpp]: https://github.com/minetest/minetest/commit/5091cb5ecdac39a49bce2317d7054d69ed43f2c1

**Comment by paramat** [comment]
I support this, but has anyone tested that it fixes the crash?

**Comment by juhdanad** [comment]
@est31 I added the warning, it might make debugging easier someday.

**Comment by juhdanad** [comment]
@paramat I have tested it. I made a big waterfall with lamps near the original one to speed testing up. My old client crashed all of the three tries, in 30sec, 2sec, 3sec. The client with this PR applied didn't crash in ten minutes. I think it is fixed.

File: src/script/common/c_content.cpp [hunk 2]
```diff
@@ -526,6 +526,12 @@ ContentFeatures read_content_features(lua_State *L, int index)
 	// Amount of light the node emits
 	f.light_source = getintfield_default(L, index,
 			"light_source", f.light_source);
+	if (f.light_source > LIGHT_MAX) {
+		warningstream << "Node " << f.name.c_str()
+			<< " had greater light_source than 14, it was reduced."
+			<< std::endl;
+		f.light_source = LIGHT_MAX;
+	}
```
Comment (sfan5) [inline src/script/common/c_content.cpp]: this duplicates the code in `builtin`, not needed

File: src/nodedef.cpp [hunk 3]
```diff
@@ -1442,6 +1445,9 @@ void ContentFeatures::deSerializeOld(std::istream &is, int version)
 		liquid_alternative_source = deSerializeString(is);
 		liquid_viscosity = readU8(is);
 		light_source = readU8(is);
+		if (light_source > LIGHT_MAX) {
+			light_source = LIGHT_MAX;
+		}
```
Comment (sfan5) [inline src/nodedef.cpp]: braces can be removed

File: src/nodedef.cpp [hunk 4]
```diff
@@ -482,6 +482,9 @@ void ContentFeatures::deSerialize(std::istream &is)
 	liquid_viscosity = readU8(is);
 	liquid_renewable = readU8(is);
 	light_source = readU8(is);
+	if (light_source > LIGHT_MAX) {
+		light_source = LIGHT_MAX;
+	}
```
Comment (sfan5) [inline src/nodedef.cpp]: braces can be removed

File: src/script/common/c_content.cpp (hunk 2 above)
Comment (juhdanad) [inline src/script/common/c_content.cpp]: If a modder made a mod that overwrote minetest.register_node(), that modder could crash the server with a too high light value. It causes a segmentation fault which is hard to debug, so IMO it is better to check twice than have a bad error.

File: src/nodedef.cpp [hunk 5]
```diff
@@ -482,6 +482,8 @@ void ContentFeatures::deSerialize(std::istream &is)
 	liquid_viscosity = readU8(is);
 	liquid_renewable = readU8(is);
 	light_source = readU8(is);
+	if (light_source > LIGHT_MAX)
```
Comment (kwolekr) [inline src/nodedef.cpp]: Could replace these with MYMIN()

**Comment by kwolekr** [comment]
Great job, I had a suspicion that it could've been a light source value out of bound, since the backtrace showed a clear case of heap corruption, and the only place where memory could logically overflow is writing to the light level array.  I reasoned this probably wasn't the problem because I thought light_source got checked on registration, but I guess I was wrong :P

File: src/script/common/c_content.cpp (hunk 2 above)
Comment (kwolekr) [inline src/script/common/c_content.cpp]: Agreed, clearly that check did not help in the case of that server with the node causing the crash.  I think an additional sanity check here is well warranted.

File: src/script/common/c_content.cpp [hunk 6]
```diff
@@ -526,6 +526,12 @@ ContentFeatures read_content_features(lua_State *L, int index)
 	// Amount of light the node emits
 	f.light_source = getintfield_default(L, index,
 			"light_source", f.light_source);
+	if (f.light_source > LIGHT_MAX) {
+		warningstream << "Node " << f.name.c_str()
+			<< " had greater light_source than 14, it was reduced."
```
Comment (kwolekr) [inline src/script/common/c_content.cpp]: Could you change this to "had light_source > " << LIGHT_MAX << ", it was reduced" instead?

LIGHT_MAX very well could change if/when I (or somebody else!) ever get around to implementing the RGB lighting model.

File: src/nodedef.cpp (hunk 3 above)
Comment (kwolekr) [inline src/nodedef.cpp]: Braces *can* be removed but that doesn't mean they need to be.

Our code style supports either.  The only thing we ask is that an author stays consistent with the rest of the surrounding code.

**Comment by kwolekr** [comment]
One more thing, could you add some ASSERT(light <= LIGHT_MAX) in your original lighting code?

This way, the error could get caught much quicker (if larger light values ever come from a different origin in the engine)

File: src/script/common/c_content.cpp (hunk 2 above)
Comment (est31) [inline src/script/common/c_content.cpp]: The check itself makes sense IMO, as builtin may be overwritten.

**Comment by juhdanad** [comment]
All modifications are done!

File: src/voxelalgorithms.cpp [hunk 7]
```diff
@@ -264,6 +264,7 @@ struct LightQueue {
 		const mapblock_v3 &block_pos, MapBlock *block,
 		direction source_dir)
 	{
+		assert(light <= LIGHT_SUN);
```
Comment (sfan5) [inline src/voxelalgorithms.cpp]: use `SANITY_CHECK` as assert is debug-only

**Comment by juhdanad** [comment]
I updated my commit.

**Comment by kwolekr** [comment]
sfan5:  I think it assert() is much more appropriate here.  We don't need such a heavyweight check always active; doing this also removes the possibility of the compiler inlining push().  It's an assertion that the code is getting the right values, but it's not something that needs to be checked all the time because it's honestly not likely to happen.

So for those reasons, I prefer ASSERT() to FATAL_ERROR() in this case.

**Comment by juhdanad** [comment]
I don't think SANITY_CHECK matters a lot, but if you wish, I can change. What do others think?

**Comment by sfan5** [comment]
I guess an `assert()` is fine too

**Comment by juhdanad** [comment]
Okay, I changed it to `assert()`.

**Comment by Zeno-** [comment]
Before this is merged, I'd like to know the *actual* root cause and why it was not an issue before. I'm ok with this fix in general but I'd like the mystery solved. Also this solution is very different to my own (which since I decided to have an actual weekend for once never got to be a PR)

**Comment by Zeno-** [comment]
Also, wouldn't it be better to fix this problem (out of range light values) much, much earlier instead of like this fix does (e.g. couldn't it be fixed so that it can never be out of range by the time it gets to this point in the code in the first place; if it's a mod then it should be fixed when loading the mod (and a warning emitted, for example). To clarify, is there a point "higher" in the code where the problem can be eliminated?

**Comment by paramat** [comment]
I added a limit in node registration a while ago, this PR is to stop light levels that are already existing in a world from causing a crash.

**Comment by Zeno-** [comment]
Thanks paramat. I've scanned the IRC logs and the related conversation. Seems to be all cool after the assert is replaced with SANITY_CHECK

**Comment by kwolekr** [comment]
I didn't realize such a trivial issue would be a point of contention.  Could we get a tally of votes for SANITY_CHECK() vs assert()?

:+1: assert() for me.

**Comment by paramat** [comment]
I'm not sure @Zeno-  is insisting on 'sanity check'.

**Comment by Zeno-** [comment]
ok, leaving it as assert and merging. I really think it should be SANITY_CHECK so it remains in release but, it's very very minor and it'll crash anyway if things are insane, so *shrug*

**Comment by juhdanad** [comment]
@Zeno- I would like to explain what caused the crash.
Red Cat Creative is an outdated server, where builtin does not check light_source.
There was a mod 'darkage', which registered a node with light_source=18.
The server did not crash, because it uses the old light spreading code, which checks light levels and limits them to 15.
So there are no nodes on any Minetest world that have light brighter than 15. It is impossible.
The client accepted light_source=18 from the server, but the client used my new light spreading code.
When light would spread from a node, it caused a crash.
On the server, there is a waterfall lit by these light sources.
When a water block was placed next to a lamp, it triggered a light update.
This is why a waterfall could make the client crash, but not the server.
