### PR TITLE
Fix touch input on Linux

### LINKED ISSUE #14111: [regression] touchscreen stopped working with 5.8.0 on Linux
### Minetest version

```true
Minetest 5.8.0 (Linux)
Using Irrlicht 1.9.0mt13
Using LuaJIT 2.1.0-beta3
BUILD_TYPE=Release
RUN_IN_PLACE=0
USE_CURL=1
USE_GETTEXT=1
USE_SOUND=1
STATIC_SHAREDIR="/usr/share/minetest"
STATIC_LOCALEDIR="/usr/share/locale"
```

### Active renderer

irrelevant

### Irrlicht device

X11

### Operating system and version

Alpine Linux (postmarketOS)

### CPU model

aarch64

### GPU model

Adreno 630

### OpenGL version

irrelevant

### Summary

While with 5.7.0 touchscreen worked well, with 5.8.0 isn't possible to enter the game from the menu.

### Steps to reproduce

Run the game. Cannot be controlled by touch-screen.

### PR DESCRIPTION
**Pull request by grorp**
Fixes #14111.

The code relied on touch IDs being consecutive. This is true on Android, but not on Linux. Therefore, touch input on Linux was broken since 53886dcdb52de80d862539e22950c84fbf88df88.

## To do

This PR is a Ready for Review.

## How to test

Play Minetest on Android. Verify that touchscreen input, and especially stack splitting, still work.

Play Minetest on Linux with a touchscreen. Verify that touchscreen input, and especially stack splitting, work again.

### CODE REVIEW

**Comment by okias** [comment]
> Play Minetest on Linux with a touchscreen. Verify that touchscreen input, and especially stack splitting, work again.

Issue is resolved by this patch! Thank you.

**Comment by srifqi** [comment]
The issue with this PR's approach is that each touch-pointer can no longer be independently moved.

`5.8.0`:

https://github.com/minetest/minetest/assets/4017302/c751151e-e9a8-4a1e-97ad-1ac4291feed5

This PR:

https://github.com/minetest/minetest/assets/4017302/f41574c8-66d7-43a8-954c-335629b9781f

-------

In my opinion, your original approach in the touch-screen support for SDL (minetest/irrlicht PR 262) is good. For now, that approach can be applied for Linux/X11 ([my attempt](https://github.com/srifqi/irrlicht/tree/linux-touch-id)).

**Comment by okias** [comment]
> The issue with this PR's approach is that each touch-pointer can no longer be independently moved.
> 
> `5.8.0`:
> Minetest-5.8.0-Android-place-one.mp4
> 
> This PR:
> Minetest-14117-Android-place-one.mp4
> 
> In my opinion, your original approach in the touch-screen support for SDL (minetest/irrlicht PR 262) is good. For now, that approach can be applied for Linux/X11 ([my attempt](https://github.com/srifqi/irrlicht/tree/linux-touch-id)).

This works for me in Linux. (not saying SDL isn't the right way) :wink:

**Comment by srifqi** [comment]
> This works for me in Linux.

Sorry, which _this_ did you mean?

**Comment by okias** [comment]
> > This works for me in Linux.
> 
> Sorry, which _this_ did you mean?

I tried to reproduce what you did on the video and it worked with patched 5.8.0 build.

File: src/gui/modalMenu.cpp [hunk 1]
```diff
@@ -273,7 +273,7 @@ bool GUIModalMenu::preprocessEvent(const SEvent &event)
 		irr_ptr<GUIModalMenu> holder;
 		holder.grab(this); // keep this alive until return (it might be dropped downstream [?])
 
-		if (event.TouchInput.ID == 0) {
```
Comment (sfan5) [inline src/gui/modalMenu.cpp:276]: ouch, this shouldn't have passed code review. easy to miss however.

It sounds like what the code should be doing is remember the ID of the first and second touch when they begin.

**Comment by grorp** [comment]
Another possibility: Add a pointer index (as opposed to pointer ID) field to Irrlicht's `STouchInput`, and use that here. What my fix/workaround in minetest/irrlicht#262 did was essentially that it turned pointer IDs into pointer indexes.

File: src/gui/modalMenu.cpp (hunk 1 above)
Comment (srifqi) [reply src/gui/modalMenu.cpp:276]: I did not realise that the ID assignment is different for each device. I just checked on my phone and thought that it resets to zero when there is no touch. My bad.

**Comment by srifqi** [comment]
> Which solution do we choose?

How about a global helper that "remember" the order/index of each active touch? It can be in Minetest or Irrlicht (for each device type). If done this way, the other part does not have to check for the index.

**Comment by grorp** [comment]
After thinking about this some more, I believe this PR should be merged as is.

The limitation @srifqi is describing - that moving the first pointer doesn't work if a second pointer exists - only applies in formspecs and has existed approximately forever. Nobody ever complained about it AFAIK - probably because there is only a use case for tapping the screen with a second finger, not for keeping a second finger on the screen.

This PR just restores the state before the regression. More improvements would be nice, but should not be expected from a PR that is supposed to fix a regression.

Merging this soon would also be good so as not to block further work on the touchscreen code.
