### PR TITLE
"Browse online content" formspec improvement

### LINKED ISSUE #10069: ContentDB uninstall button slightly too small for translation
##### Minetest version
```
0a1181f7637adab6fe1ba5d3c09038912a06b37f
```

##### Summary
The button size in ContentDB is a little bit too small for the German translation.

Specifically, the “Uninstall” button (“Deinstallieren”). The button is just a few pixels short, so it's only a minor problem. Please fix this by giving more space.

BTW: ContentDB as a whole could be stretched fullscreen instead of leaving ca. 50% of screen width empty. But this true for most of the main menu, so it's semi-off-topic.

##### Steps to reproduce
* Activate German
* Open ContentDB
* Scroll to a thing that is already installed (or install one if nothing is installed)

### PR DESCRIPTION
**Pull request by Zughy**
Closes #10069 

image
image

1) Descriptions have been moved in tooltips. It now says "Install `mod name`" and such when hovering on buttons
2) Irrlicht screws pixel art up when it's scaled with a decimal value, but apparently more details make it less evident
3) There were tons of table concatenations. I kept some, but in some other cases they made the code incomprehensible, so I got rid of them
4) Download icon is animated, but my PC is a toaster and I can't record a decent GIF
5) "View" string has been removed, it was too generic
6) Yes, main menu needs a complete overhaul, but in the meanwhile this allows me to drop a few decent icons and to make it less ugly
7) PLEASE don't lose yourself in tiny aesthetic details, this is an easy one. Ask yourself: is this better than before? Yes/no. If the answer is yes and the code is good, approve it. If no, junk it

## To do

This PR is Ready for Review

## How to test

Open MT, open CDB formspec, click icons

### CODE REVIEW

**Comment by runsy** [comment]
Cool icons and colors, I love them instead of the labeled buttons.

**Comment by rubenwardy** [comment]
These icons are a definite improvement

File: builtin/mainmenu/dlg_contentstore.lua [hunk 1]
```diff
@@ -439,48 +447,48 @@ function store.get_formspec(dlgdata)
...
 		elseif not package.path then
-			formspec[#formspec + 1] = "button[-3,0;1.5,0.8;install_"
-			formspec[#formspec + 1] = tostring(i)
-			formspec[#formspec + 1] = ";"
-			formspec[#formspec + 1] = fgettext("Install")
-			formspec[#formspec + 1] = "]"
+			local elem_name = "install_" .. i .. ";"
+			formspec[#formspec + 1] = "style[" .. elem_name .. "bgcolor=#71aa34]"
+			formspec[#formspec + 1] = left_base .. "cdb_add.png;" .. elem_name .. "]"
+			formspec[#formspec + 1] = "tooltip[" .. elem_name .. fgettext("Install") ..
```
Comment (rubenwardy) [inline builtin/mainmenu/dlg_contentstore.lua:467]: Bad translation. You should only ever do `..` with a translation if you're concatenating _complete sentences_. This isn't the case, so you should do this instead:

```lua
fgettext("Install $1", package.title) .. tooltip_colors
```

File: builtin/mainmenu/dlg_contentstore.lua [hunk 2]
```diff
@@ -439,48 +447,48 @@ function store.get_formspec(dlgdata)
...
-				formspec[#formspec + 1] = "button[-4.5,0;1.5,0.8;install_"
-				formspec[#formspec + 1] = tostring(i)
-				formspec[#formspec + 1] = ";"
-				formspec[#formspec + 1] = fgettext("Update")
-				formspec[#formspec + 1] = "]"
-			end
+				local elem_name = "install_" .. i .. ";"
+				formspec[#formspec + 1] = "style[" .. elem_name .. "bgcolor=#28ccdf]"
+				formspec[#formspec + 1] = left_base .. "cdb_update.png;" .. elem_name .. "]"
+				formspec[#formspec + 1] = "tooltip[" .. elem_name .. fgettext("Update") ..
```
Comment (rubenwardy) [inline builtin/mainmenu/dlg_contentstore.lua:476]:
```lua
fgettext("Update $1", package.title) .. tooltip_colors`
```

File: builtin/mainmenu/dlg_contentstore.lua [hunk 3]
```diff
@@ -439,48 +447,48 @@ function store.get_formspec(dlgdata)
...
 
-			formspec[#formspec + 1] = "button[-3,0;1.5,0.8;uninstall_"
-			formspec[#formspec + 1] = tostring(i)
-			formspec[#formspec + 1] = ";"
-			formspec[#formspec + 1] = fgettext("Uninstall")
-			formspec[#formspec + 1] = "]"
+				local elem_name = "uninstall_" .. i .. ";"
+				formspec[#formspec + 1] = "style[" .. elem_name .. "bgcolor=#a93b3b]"
+				formspec[#formspec + 1] = left_base .. "clear.png;" .. elem_name .. "]"
+				formspec[#formspec + 1] = "tooltip[" .. elem_name .. fgettext("Uninstall") ..
```
Comment (rubenwardy) [inline builtin/mainmenu/dlg_contentstore.lua:483]:
```lua
fgettext("Uninstall $1", package.title) .. tooltip_colors`
```

File: builtin/mainmenu/dlg_contentstore.lua [hunk 4]
```diff
@@ -439,48 +447,48 @@ function store.get_formspec(dlgdata)
...
+					" " .. package.title .. tooltip_colors
+			end
 		end
 
-		formspec[#formspec + 1] = "button[-1.5,0;1.5,0.8;view_"
+		formspec[#formspec + 1] = "image_button[-0.7,0;0.7,0.7;" ..
```
Comment (rubenwardy) [inline builtin/mainmenu/dlg_contentstore.lua:488]: tooltip?

**Review by rubenwardy — COMMENTED** [review]
FYI: `formspec[#formspec + 1]` is used so much because `..` is expensive in Lua, especially with large strings.

Small uses of `..` are probably OK though. If you're `..` lots of things, using `.format` is also a good alternative. But a lot of the concats here are only with 3 things

**Comment by rubenwardy** [comment]
The internet icon doesn't look very clear to me. There's a lot of lines that all merge together. Could it be simplified a bit somehow?

File: builtin/mainmenu/dlg_contentstore.lua [hunk 5]
```diff
@@ -439,48 +447,48 @@ function store.get_formspec(dlgdata)
 
 		-- buttons
 		local description_width = W - 0.375*5 - 1 - 2*1.5
```
Comment (rubenwardy) [inline builtin/mainmenu/dlg_contentstore.lua:449]: This can be moved down to immediately where it is moved.

Also, there is unused space. The red line (on the right) should be the same as the green line (on the left).

image

(left/right included for colorblind readers)

**Comment by rubenwardy** [comment]
You've accidentally included the clear icon in this PR

File: builtin/mainmenu/dlg_contentstore.lua (hunk 1 above)
Comment (Zughy) [reply builtin/mainmenu/dlg_contentstore.lua:467]: I created tooltips because I didn't want to eliminate already existing strings. In this way, though, it means creating new strings and I guess you don't want to mess up with new strings so.. is better if I just get rid of the tooltips?

Comment (rubenwardy) [reply builtin/mainmenu/dlg_contentstore.lua:467]: Well, you could remove the package.title from the tooltip. But I don't think creating new strings is _too_ much of a problem

Comment (Zughy) [reply builtin/mainmenu/dlg_contentstore.lua:466]: I'm gonna play it safe and I'll keep the same string

**Comment by Zughy** [comment]
New icon, it should be clearer now
imagen

All requests have been addressed. I also used the new code style length in some cases, where 95 has been used as a soft limit (I've reached 100 characters, max)

**Comment by rubenwardy** [comment]
Yeah, that's better

**Review by rubenwardy — APPROVED** [review]

File: po/minetest.pot [hunk 6]
```diff
@@ -218,7 +218,7 @@ msgid "Uninstall"
 msgstr ""
 
 #: builtin/mainmenu/dlg_contentstore.lua
-msgid "View"
+msgid "View more information in a web browser"
```
Comment (sfan5) [inline po/minetest.pot:221]: Please revert this change, it will be done automatically by a script.

Comment (sfan5) [reply po/minetest.pot]: Did that myself since I checkout out your branch to run `optipng` anyway.

**Review by sfan5 — APPROVED** [review]
Looks good.

File: po/minetest.pot (hunk 6 above)
Comment (Zughy) [reply po/minetest.pot]: Huh, I missed those two files, my bad
