### PR TITLE
Formspec: make bgcolor element less confusing and allow setting fullscreen color

### LINKED ISSUE #8985: Formspec element "bgcolor[<some_color>;false]" does not work
##### Minetest version
```
26b39f1eae1f576669cbf49c6db94ef4ed8624df
```

##### Summary
The formspec element `bgcolor` fails if the 2nd argument is literally `false` instead of being empty.

##### Steps to reproduce

1. Use `luacmd`
2. Use Minimal Development Test
3. In console, write: `/lua me:set_formspec_prepend("bgcolor[#FF0000FF;false]")`
4. Open your inventory menu
5. For comparison, write in console:  `/lua me:set_formspec_prepend("bgcolor[#FF0000FF]")`
6. Open your inventory menu

EXPECTED AFTER STEP 4/6:
Inner rectangle is red.

ACTUAL AFTER STEP 4:
Inner rectangle is black translucent (default formspec color).

ACTUAL AFTER STEP 6:
Inner rectangle is red.
(steps 5 and 6 were just added for comparison)

##### Notifications
@SmallJoker
@DS-Minetest

### LINKED ISSUE #9169: Formspec bgcolor ignores the color when fullscreen
5.1.0

It's impossible to set a background color for a form when the fullscreen parameter is set to true as well. The client just ignores the color.

Repro: Show a formspec with bgcolor[#fff;true]
It's gonna display a transparent black rather than the expected white.
Flip the boolean to false and the color will suddenly work.

### PR DESCRIPTION
**Pull request by DS-Minetest**
- Goal of the PR: less confusion and full backwards-compatibility
- Now that minetest uses formspec versions, it is possible to add a new parameter to an old element. The `bgcolor` element now uses 3 parameters: The `bgcolor`, an enum parameter to choose whether the `bgcolor`, the fullscreen background color, both or neither are drawn and the color for the fulscreen background.
- Fixes #8985.
Closes #8992. (I haven't see that PR before making this one. \>\_\<)
Closes #9018, if this PR is merged first.
Fixes #9169.

## To do

This PR is a Ready for Review.

## How to test

```lua
local base_formspec =
	"formspec_version[3]"..
	"size[10,8]"..
	"button[3.5,6.5;3,1;btn;Set]"..
	"textarea[1,1;8,5;ta;Formspec elements in here:;"

local clicked_node_pos

minetest.register_node("test:node", {
	description = "test node",
	tiles = {"default_wood.png^heart.png"},
	groups = {choppy = 3, oddly_breakable_by_hand = 3},
	on_construct = function(pos)
		local meta = minetest.get_meta(pos)
		meta:set_string("mformspec", "bgcolor[;;]")
		meta:mark_as_private("mformspec")
	end,
	on_rightclick = function(pos, node, clicker, itemstack, pointed_thing)
		local f = minetest.get_meta(pos):get_string("mformspec")
		minetest.show_formspec(clicker:get_player_name(), "test:node_formspec",
				base_formspec .. minetest.formspec_escape(f) .. "]" .. f)
		clicked_node_pos = pos
	end,
})

minetest.register_on_player_receive_fields(function(player, formname, fields)
	if formname ~= "test:node_formspec" then
		return
	end
	if fields.btn and fields.ta then
		local f = fields.ta
		minetest.get_meta(clicked_node_pos):set_string("mformspec", f)
		minetest.show_formspec(player:get_player_name(), "test:node_formspec",
				base_formspec .. minetest.formspec_escape(f) .. "]" .. f)
	end
end)


minetest.register_chatcommand("bgcolor", {
	params = "<bgcolor>;<fullscreen>;<fbgcolor>",
	description = "open a formspec with the given values as parameters to bgcolor",
	privs = {},
	func = function(name, param)
		minetest.show_formspec(name, "test:chatcommand_formspec",
				"formspec_version[3]size[10,8]bgcolor[" .. param .. "]")
		return true, "showing formspec"
	end,
})
```

### CODE REVIEW

**Comment by DS-Minetest** [comment]
Added testing code and fixes some stupid mistakes.

**Comment by paramat** [comment]
@rubenwardy

**Comment by SmallJoker** [comment]
Whatever you're changing, it has to be compatible with 5.0.1.
5.0.1 code:
https://github.com/minetest/minetest/blob/76325d0ba925cfdd18e387ae96d27921136e98e5/src/gui/guiFormSpecMenu.cpp#L1557-L1575

Old behaviour:
 * `bgcolor[#1234]` and `bgcolor[#1234;false]` set the formspec background
 * `bgcolor[#1234;true]` sets the fullscreen background

Possible options:
 * limit this feature to formspec version 2 (by documenting it)
 * introduce a new element
 * or why not this: (?)
```C++
bool fullscreen = parts.size() == 1 || is_yes(parts[1]);
parseColorString(parts[0], fullscreen ? m_bgcolor : m_fullscreen_bgcolor, false);

// In Lua, set them separately:
// bgcolor[#000;false]
// bgcolor[#FFF;true]
```

**Comment by DS-Minetest** [comment]
> Old behaviour:
> ...
>     * `bgcolor[#1234;true]` sets the fullscreen background

No, in the old behaviour you weren't able to set the fullscreen background color:
https://github.com/minetest/minetest/blob/76325d0ba925cfdd18e387ae96d27921136e98e5/src/gui/guiFormSpecMenu.cpp#L1563
https://github.com/minetest/minetest/blob/76325d0ba925cfdd18e387ae96d27921136e98e5/src/gui/guiFormSpecMenu.cpp#L2485-L2488

:thinking: Something that still is different is that `bgcolor[red;]` in 5.0.1 sets `m_bgfullscreen` to `false` while with this PR it doesn't change anything.
If requested, I can keep this behaviour for formspec versions \< 2.

Oh, and 5.0.1 clients will show error-messages for empty color parameters.

File: src/gui/guiFormSpecMenu.cpp [hunk 1]
```diff
@@ -1886,21 +1886,35 @@ void GUIFormSpecMenu::parseBox(parserData* data, const std::string &element)
...
+
+	// bgcolor
+	if (parameter_count >= 1 && parts[0] != "")
+		parseColorString(parts[0], m_bgcolor, false);
+
+	// fullscreen
+	if (parameter_count >= 2) {
+		if (parts[1] == "both") {
+			m_bgnotfullscreen = true;
+			m_bgfullscreen = true;
```
Comment (sfan5) [inline src/gui/guiFormSpecMenu.cpp]: `m_bgfullscreen = m_bgnotfullscreen = true;`

File: src/gui/guiFormSpecMenu.cpp [hunk 2]
```diff
@@ -1886,21 +1886,35 @@ void GUIFormSpecMenu::parseBox(parserData* data, const std::string &element)
...
+		} else if (parts[1] == "neither") {
+			m_bgnotfullscreen = false;
+			m_bgfullscreen = false;
```
Comment (sfan5) [inline src/gui/guiFormSpecMenu.cpp]: `m_bgfullscreen = m_bgnotfullscreen = false;`

File: doc/lua_api.txt [hunk 3]
```diff
@@ -2092,15 +2092,17 @@ Elements
...
-### `bgcolor[<color>;<fullscreen>]`
-
-* If `color` is a valid `ColorString`, the fullscreen background color
-  is set to `color`.
-* If `fullscreen` is a true value, the fullscreen background color is drawn.
+### `bgcolor[<bgcolor>;<fullscreen>;fbgcolor]`
+
+* Sets background color of formspec.
+* `bgcolor` and `fbgcolor` are `ColorString`s, they define the color of the
+  not-fullscreen and the fullscreen background.
```
Comment (sfan5) [inline doc/lua_api.txt]: should say `non-fullscreen` everywhere

File: src/gui/guiFormSpecMenu.cpp (hunk 1 above)
Comment (DS-Minetest) [reply src/gui/guiFormSpecMenu.cpp]: >Don't put multiple assignments on a single line either.

https://www.kernel.org/doc/html/latest/process/coding-style.html#indentation

File: src/gui/guiFormSpecMenu.cpp (hunk 2 above)
Comment (DS-Minetest) [reply src/gui/guiFormSpecMenu.cpp]: Same as above.

**Comment by sfan5** [comment]
From looking at the code, this is perfectly compatible:

<b>5.0.1</b>:

formspec | fsbg drawn | bg drawn
-------- | ---------- | --------
`bgcolor[#FFF]` | no | yes (default values)
`bgcolor[#FFF;true]` | yes | no
`bgcolor[#FFF;false]` | no | yes
`bgcolor[#0FF;both;#FF0]` | no | yes
`bgcolor[#FFF;neither]` | no | yes

<b>this PR</b>:

formspec | fsbg drawn | bg drawn
-------- | ---------- | --------
`bgcolor[#FFF]` | no | yes (default values)
`bgcolor[#FFF;true]` | yes | no
`bgcolor[#FFF;false]` | no | yes
`bgcolor[#0FF;both;#FF0]` | yes | yes
`bgcolor[#FFF;neither]` | no | no

**Comment by DS-Minetest** [comment]
>From looking at the code, this is perfectly compatible:

(Well, things like `bgcolor[#fff;true]bgcolor[#fff;]` act differently, so it's nearly perfectly. (As written before, I could fix this.))

Thanks for reviewing!

**Comment by SmallJoker** [comment]
> Whatever you're changing, it has to be compatible with 5.0.1.

In other words - as soon 3 (or more) parameters are used, 5.0.1 clients will see an error.
You can either ignore this, and tell the mobile users to update or make the new parameter require formspec_version 2.

File: doc/lua_api.txt [hunk 4]
```diff
@@ -2092,15 +2092,17 @@ Elements
...
+### `bgcolor[<bgcolor>;<fullscreen>;fbgcolor]`
+
+* Sets background color of formspec.
+* `bgcolor` and `fbgcolor` are `ColorString`s, they define the color of the
+  non-fullscreen and the fullscreen background.
+* `fullscreen` can be one of the following:
+  * `false`: Only the non-fullscreen background-color is drawn. (default)
+  * `true`: Only the fullscreen background-color is drawn.
+  * `both`: The non-fullscreen and the fullscreen background-color are drawn.
+  * `neither`: No background-color is drawn.
```
Comment (SmallJoker) [inline doc/lua_api.txt]: The dash is not needed for `background color`. It's unusual to read it this way, but can't say whether it's "proper" English.

**Comment by sfan5** [comment]
After some IRC discussion: this PR is good, but only to be merged for 5.2.0 since it needs to be backwards compatible. And that backwards compatibility can only be achieved using the `formspec_version[]` mechanism.

File: doc/lua_api.txt (hunk 4 above)
Comment (DS-Minetest) [reply doc/lua_api.txt]: Done.

**Comment by DS-Minetest** [comment]
It should be backwards compatible now. (The modder is forced to use `formspec_version[2]`. (The "both" and "neither" still work in version 1.))

**Comment by DS-Minetest** [comment]
Rebased.

**Comment by DS-Minetest** [comment]
Rebased.

File: doc/lua_api.txt [hunk 5]
```diff
@@ -2104,11 +2104,19 @@ Elements
...
 
-### `bgcolor[<color>;<fullscreen>]`
-
-* Sets background color of formspec as `ColorString`
-* If `true`, a fullscreen background is drawn and the color is ignored
-  (does not affect the size of the formspec)
+### `bgcolor[<bgcolor>;<fullscreen>;<fbgcolor>]`
+
+* Sets background color of formspec.
+* `bgcolor` and `fbgcolor` are `ColorString`s, they define the color of the
```
Comment (SmallJoker) [inline doc/lua_api.txt]: `fbgcolor (optional)`

Also `fullscreen` should be mentioned as optional argument.

**Comment by SmallJoker** [comment]
PR works. Minor doc adjustments requested.
