### PR TITLE
Fix gray screen on Lua error

### LINKED ISSUE #4482: Gray screen on Lua error (completely freezes Minetest)
Hi, here's an issue I encountered quite often in Minetest 0.4.14 and earlier versions while modding:

When one of the mods has a Lua error, sometimes instead of just halting the server and showing the Lua error, the entire Minetest screen becomes gray, nothing else is visible and Minetest doesn't react to almost anything, not matter what keys I try to press. I have to manually close the Minetest window. At least Minetest reacts to normal closing; it is not neccessary to kill (`SIGKILL`) the application.
That's pretty much like the infamous blue screen in Windows, only that it's gray and without text. ;-)

I know this “gray screen” occours on Lua errors because on every occurance `debug.txt` shows a Lua error. When I fix this Lua error, the gray screen is gone. It has never happened to me that I got a gray screen _without_ a Lua error being reported into `debug.txt` before.

The expected behaviour is of course that Minetest still works, but it displays the Lua error and maybe halts the server if needed, so that the user doesn't have to restart Minetest entirely.

I am not sure what causes this bug. But from my experience so far it seems to be more likely to happen when a critical (=causes server to halt) Lua error happens while a formspec or the console is opened.
More research on this needs to be done, obviously.

Note: I am using Minetest 0.4.14 on GNU/Linux.

### PR DESCRIPTION
**Pull request by pauloue**
Fixes #4482 

`Game::shutdown` was not being run when the server throws an exception, so the menus weren't getting deleted. So after `the_game` returns and [`main_menu`](https://github.com/minetest/minetest/blob/914dbeaa0be4b5ef87506b605ef4e241cd3732dc/src/client/clientlauncher.cpp#L537) is called, `isMenuActive()` returns true and the gray background is drawn. ~I have no idea what that code was supposed to do so I deleted it. It was added in https://github.com/minetest/minetest/commit/405347769a2f8c73aead3bc2b64fdc4d81763921.~

## To do

This PR is a Ready for Review.

## How to test

Trigger a Lua error while the chat console or a form is open using e.g.:
```lua
minetest.after(4, function() fail() end)
```
Before: gray screen
After: shutdown message then error dialog in the main menu

### CODE REVIEW

File: src/client/clientlauncher.cpp [hunk 1]
```diff
@@ -537,19 +537,6 @@ bool ClientLauncher::launch_game(std::string &error_message,
 void ClientLauncher::main_menu(MainMenuData *menudata)
 {
 	bool *kill = porting::signal_handler_killstatus();
-	video::IVideoDriver *driver = RenderingEngine::get_video_driver();
-
-	infostream << "Waiting for other menus" << std::endl;
-	while (RenderingEngine::get_raw_device()->run() && !*kill) {
-		if (!isMenuActive())
-			break;
-		driver->beginScene(true, true, video::SColor(255, 128, 128, 128));
```
Comment (sfan5) [inline src/client/clientlauncher.cpp:546]: Doesn't the other change already fix the bug?
I'd rather leave this code in.

Comment (pauloue) [reply src/client/clientlauncher.cpp]: yes, the other change is enough.

**Comment by sfan5** [comment]
This introduces a very noticable delay (1-2s) from when the Lua error happens and when it is actually displayed since the game shuts down first.
