### PR TITLE
Fix inventory: Quickly picking up item and placing it again no longer works

### LINKED ISSUE #14233: Inventory: Quickly picking up item and placing it again no longer works
### Minetest version

```true
5.8.0
```

### Active renderer

_No response_

### Irrlicht device

_No response_

### Operating system and version

GNU/Linux

### CPU model

_No response_

### GPU model

_No response_

### OpenGL version

_No response_

### Summary

If you click on an item stack in the inventory and click again, sometimes you only pick up the item stack but won't place it back.

This is a regression because previously, this would have placed back the item.

I think this bug might have been caused with the new inventory shortcuts added to 5.8.0. Specifically, there is a new feature that will put all the items of the same kind in the inventory towards your cursor if you doubleclick it. Normally, this is very useful but what if the item you doubleclicked was the only one in the inventory? Then your item stack does not change and you do not put it back as well (which you would expect).

This is very irritating because the player will think that clicking in the inventory is sometimes broken. I think the proper bugfix would be to always put the item back after a double click it this no additional item was added to the cursor.

@OgelGames

### Steps to reproduce

1. Empty the inventory
2. Put one item inside inventory
3. Move the cursor over this item and make sure it's over the slot, too
4. Quickly click two times on the single item, make sure the cursor remains on the slot

Expected behavior: You quickly pick up the item stack with the first click and place it back with the 2nd click.
Actual behavior: You only pick up the item stack, so it appears to the player that clicking in the inventory is sometimes randomly broken.

### PR DESCRIPTION
**Pull request by sfence**
- Goal of the PR
Fix #14233
- How does the PR work?
Disable `left_dragging` only if there are items to pickup by double click.
- Does it resolve any reported issue?
#14233

## To do

Ready for Review.

## How to test

See #14233

### CODE REVIEW

**Review by SmallJoker — APPROVED** [review]
Tested a few inventory movements. Inside the player inventory and from player inventory to a chest. No issues found.

Works.

File: src/gui/guiFormSpecMenu.cpp [hunk 1]
```diff
@@ -4658,6 +4653,12 @@ bool GUIFormSpecMenu::OnEvent(const SEvent& event)
 						}
 
 						if (amount > 0) {
+							if (m_left_dragging) {
```
Comment (grorp) [inline src/gui/guiFormSpecMenu.cpp:4656]: If `!m_left_dragging`, we already abort earlier:

https://github.com/minetest/minetest/blob/2a40c2af39e917d65244e7865e34f068d9237558/src/gui/guiFormSpecMenu.cpp#L4621-L4626

so `m_left_dragging` is always true here, isn't it?

**Review by grorp — APPROVED** [review]
