### PR TITLE
Fix collisions with long dtime, in particular with bouncing

### LINKED ISSUE #15027: Bounciness issues with large dtime steps
### Minetest version

```true
Minetest 5.9.0 (Linux)
Using LuaJIT 2.1.1719379426 (OpenResty)
Built by GCC 14.2
Running on Linux/6.8.12 x86_64
BUILD_TYPE=Release
RUN_IN_PLACE=0
USE_CURL=1
USE_GETTEXT=1
USE_SOUND=1
STATIC_SHAREDIR="/usr/share/minetest"
STATIC_LOCALEDIR="/usr/share/locale"
```

### Irrlicht device

X11

### Operating system and version

Debian sid

### CPU model

_No response_

### GPU model

Intel

### Active renderer

_No response_

### Summary

When there is lag in the server (generating map chunks, spawning structures, mobs...) and it misses some dtime steps, entities can bounce badly on beds. Seen for example in Voxelibre and Mineclonia.

The reason is an incomplete interpolation in collision.cpp.

First the acceleration is applied over the entire dtime:
https://github.com/minetest/minetest/blob/dc21924f31ff52174553c4441ce8c861f842c6f9/src/collision.cpp#L365-L367

then a collision is searched with the updated speed (this is probably okay as an approximation).
Then when a collision was found, it is assumed it was at the updated speed:
https://github.com/minetest/minetest/blob/dc21924f31ff52174553c4441ce8c861f842c6f9/src/collision.cpp#L505

When not bouncing that likely does not matter as much, because the collision sets the speed to 0, but not when on bouncy material (such as beds in Voxelibre and Mineclonia):
https://github.com/minetest/minetest/blob/dc21924f31ff52174553c4441ce8c861f842c6f9/src/collision.cpp#L538

A perfect simulation would of course mean checking some parabola, which is expensive. I think checking a linear movement from the start to the destination is okay as an approximation, but the error in the collision speed causes larger issues with bouncyness.

### Steps to reproduce

1. Mineclonia + World Edit
2. Place a bed
3. Place a villager onto it
4. run `//lua local t0 = os.time() while os.time() < t0+2 do end`
5. [Result](https://github.com/minetest/minetest/issues/15027#issuecomment-2299898047)

### PR DESCRIPTION
**Pull request by kno10**
Closes #15027

When there is lag in the server (generating map chunks, spawning structures, mobs...) and it misses some steps and we have a large dtime, entities can bounce badly on beds. Seen for example in Voxelibre and Mineclonia.

The main issue is that `speed_f` is the speed at the end of the movement, not at collision time. For a large timestep, this speed can be much too large (consider a mob just over a bed, accelerated by gravity for a long timestep).

This patch (A) introduces `aspeed_f`, which is the average movement speed not the maximum (B) on collision, the speed is updated according to the estimated dtime until collision.

For the villager example above, in particular (B) means a much smaller velocity when bouncing.

For further detail, see #15027

### CODE REVIEW

**Comment by sfan5** [comment]
It's hard to tell which are cosmetic changes and which are functional changes that fix the bug. Is it `aspeed_f`?

**Comment by kno10** [comment]
> This patch (A) introduces aspeed_f, which is the average movement speed not the maximum (B) on collision, the speed is updated according to the estimated dtime until collision.

So yes, `aspeed_f` is the most important *part* of it. The old code used the speed at the end of the movement, not the average speed during the time step. But further down, aspeed is updated not with the full dtime, but with `nearest_dtime`
```
aspeed_f = *speed_f + accel_f * 0.5f * nearest_dtime;
*pos_f += truncate(aspeed_f * nearest_dtime, 100.0f);
```
This could probably be one line, but the important thing is that speed during the partial time `nearest_dtime` is correct, and not includes the acceleration over the full `dtime` as before (which caused a very high impact speed on bouncy materials with lag).

**Comment by sfan5** [comment]
Can you separate the fix and the style changes into two commits?

**Comment by kno10** [comment]
I will not have the time for this soon, I fear.

File: src/collision.cpp [hunk 1]
```diff
@@ -453,7 +449,14 @@ collisionMoveResult collisionMoveSimple(Environment *env, IGameDef *gamedef,
...
 			// No collision with any collision box.
-			*pos_f += truncate(*speed_f * dtime, 100.0f);
+			*pos_f += truncate(aspeed_f * dtime, 100.0f);
+			// Final speed:
+			*speed_f += accel_f * dtime;
+			// Limit speed for avoiding hangs
+			speed_f->Y = rangelim(speed_f->Y, -5000, 5000);
+			speed_f->X = rangelim(speed_f->X, -5000, 5000);
+			speed_f->Z = rangelim(speed_f->Z, -5000, 5000);
+			*speed_f = truncate(*speed_f, 10000.0f);
```
Comment (SmallJoker) [inline src/collision.cpp:459]: This code is repeated 3 times. Would you please be so nice to move this to a separate function?

File: src/collision.cpp [hunk 2]
```diff
@@ -464,10 +467,12 @@ collisionMoveResult collisionMoveSimple(Environment *env, IGameDef *gamedef,
 		bool step_up = false;
 		if (nearest_collided != COLLISION_AXIS_Y) {
 			aabb3f stepbox = movingbox;
-			stepbox.MinEdge.X += speed_f->X * dtime;
-			stepbox.MinEdge.Z += speed_f->Z * dtime;
-			stepbox.MaxEdge.X += speed_f->X * dtime;
-			stepbox.MaxEdge.Z += speed_f->Z * dtime;
+			// Look slightly ahead  for checking the height when stepping
```
Comment (SmallJoker) [inline src/collision.cpp:470]: Why? What kind of issue does this fix? Please extend the comment.

Comment (kno10) [reply src/collision.cpp:470]: A precise computation is supposed to clip the X and Z values to just before the collision. But the `wouldCollideWithCeiling` function should check the ceiling also *after* stepping up, not assuming to stop before. Because the old computation used a too high speed, it would overestimate the position and hence test over the stair (usually, unless dtime is much too large).

Without this check, this might allow a "glitch elevator" for example by running against a stack of stairs.

**Comment by kno10** [comment]
This would be really nice to have in 5.9.1 IMHO.

File: src/collision.cpp [hunk 3]
```diff
@@ -454,8 +443,7 @@ collisionMoveResult collisionMoveSimple(Environment *env, IGameDef *gamedef,
 			// Find nearest collision of the two boxes (raytracing-like)
 			f32 dtime_tmp = nearest_dtime;
 			CollisionAxis collided = axisAlignedCollision(box_info.box,
```
Comment (appgurueu) [inline src/collision.cpp:445]: Thought: This is still some kind of linear approximation of a quadratic function, just now with the average speed, isn't it?

We could make `axisAlignedCollision` take acceleration into account properly: If acceleration on an axis is zero, the current code is fine. Otherwise, exactly solve the quadratic equation for the first point in time >= 0 where the faces touch. (We might want doubles here?)

So for example if we're checking for an X axis collision, we look at the current velocity. Say the X component is > 0. So we want to check whether our +X face smashes into another the -X face of another box. Now we have the distance between those faces and we want to find the point in time at which they touch; we then check whether the YZ projections of the AABBs overlap. That's what the code is essentially currently doing for all three axes, except it doesn't take acceleration into account: It's just `dtime = distance / std::abs(speed.Y);` when it should be $vt + 1/2at = d$ where $d$ is the distance between the faces solved for $t$.

Comment (kno10) [reply src/collision.cpp:445]: I did not previously check `axisAlignedCollision`, and this fix here is quite *urgent* IMHO - there are plenty of complaints in minetest games such as Voxelibre and Mineclonia about mobs bouncing (on beds) through roofs.
Hence I opened #15236 to discuss this part. But there also is #15227 which further complicates things when considering two *moving* objects (although it should be possible to compute this similarly by using their relative positions and relative speeds, which should reduce this to the base case again).

**Review by SmallJoker — APPROVED** [review]
Did the villager drop test + 6 seconds server delay.
```
ACTION[Server]: singleplayer executed local t0 = os.time() while os.time() < t0+6 do end
WARNING[Server]: collisionMoveSimple: maximum step interval exceeded, lost movement details!
```

Works. As far as I can tell, there's no noticeable difference for the client-side physics because its step size is small enough.

**Comment by appgurueu** [comment]
I will review this properly in a couple days when the feature freeze starts (till then I will prioritize reviewing feature PRs; since this is a bug fix it can be merged during feature freeze).

**Comment by Zughy** [comment]
@appgurueu reminder

File: src/collision.cpp [hunk 4]
```diff
@@ -85,6 +85,14 @@ inline v3f truncate(const v3f vec, const f32 factor)
 	);
 }
 
+inline v3f rangelimv(const v3f vec, const f32 low, const f32 high)
```
Comment (appgurueu) [inline src/collision.cpp:88]:
```suggestion
inline v3f rangelimv(const v3f &vec, const f32 low, const f32 high)
```

**Review by appgurueu — APPROVED** [review]
Fixes the issue it claims to fix. The math should at least be less bogus than before, on average, now. This seems fine as a quick fix for 5.10.0.

---

I was hoping there would be a simpler fix lurking here (by simply using the current speed before applying acceleration in the linear approximation), but I tried to implement it and it's not as simple (specifically the "no collisions" case poses a major problem; we do want to apply acceleration there, but we don't know whether by doing so we overshoot because there will be an early collision). I think ultimately I'll implement https://github.com/minetest/minetest/pull/15029/files?diff=split&w=1#r1786903169.

File: src/collision.cpp [hunk 5]
```diff
@@ -466,96 +454,126 @@ collisionMoveResult collisionMoveSimple(Environment *env, IGameDef *gamedef,
...
+			if (!step_up) {
+				if (nearest_collided == COLLISION_AXIS_X)
+					pos_f->X += aspeed_f.X * nearest_dtime;
+				if (nearest_collided == COLLISION_AXIS_Y)
+					pos_f->Y += aspeed_f.Y * nearest_dtime;
+				if (nearest_collided == COLLISION_AXIS_Z)
+					pos_f->Z += aspeed_f.Z * nearest_dtime;
 			}
+		} else if (nearest_dtime > 0) {
+			aspeed_f = *speed_f + accel_f * 0.5f * nearest_dtime;
```
[the remark this answers is not in the document]
Comment (kno10) [reply src/collision.cpp:505]: The 0.5 comes from adding the *average* acceleration over the interval `nearest_dtime`.
So it's fine as long as `nearest_dtime` is accurate (which it is not entirely, as discussed elsewhere).
As we only simulate up to `nearest_dtime` in this iteration, we have to update the average speed to match this segment only. We could iterate multiple times here to approximate this numerically (recheck the collision with the new aspeed until the change is tiny), but I believe this will be fine and is better fixed by improving the `axisAlignedCollision` function.
But when `nearest_dtime` is much smaller than `dtime`, then this version will be more accurate than not updating `aspeed_f` (because the initial `aspeed_f` then was not very accurate).

File: src/collision.cpp [hunk 6]
```diff
@@ -76,7 +76,7 @@ inline f32 truncate(const f32 val, const f32 factor)
 	return truncf(val * factor) / factor;
 }
 
-inline v3f truncate(const v3f vec, const f32 factor)
+inline v3f truncate(const v3f &vec, const f32 factor)
```
Comment (grorp) [inline src/collision.cpp:79]: This is reverting a change made by 2e89529eef23c678414b0a1a60a04a35724d4df5

https://dev.minetest.net/index.php?title=Code_style_guidelines&diff=6508&oldid=6489

Comment (appgurueu) [reply src/collision.cpp:79]: Huh, I was not aware of that revision. (Frankly I also don't agree with the reasoning - if passing the value directly is more efficient than passing the const ref, surely the compiler can figure that out, especially with LTO or an inline function as in this case - but I don't mind much either way.)

**Comment by kno10** [comment]
@grorp ok, reverted back to `const v3f vec`

**Comment by kno10** [comment]
Improved version #15408 - please consider that for 5.11
