### PR TITLE
Builtin: Sanity-check /time inputs

### LINKED ISSUE #11816: Builtin /time command does not validate input, causes Lua error
##### Minetest version
Commit 1dc1305ada07da8c2a278b46a34d58af86184af9

##### OS / Hardware
Operating system: Debian GNU/Linux
CPU: Intel(R) Core(TM) Duo CPU      T2400  @ 1.83GHz

##### Summary
The following commands all crash Minetest:

```
/time NaN
/time -Inf
/time 1e30
```

This happens, very broadly speaking, because the function that handles the `/time` command does not fully validate its arguments before processing them.

##### Steps to reproduce
Enter one of the following commands:

```
/time NaN
/time -Inf
/time 1e30
```

### PR DESCRIPTION
**Pull request by SmallJoker**
Fixes #11816. User inputs in chat commands must not cause errors, hence the documented parameter bounds are now enforced.

## To do

This PR is Ready for Review.

## How to test

1. `/time -inf`, `/time nan`, `/time -1` in master and with this PR

### CODE REVIEW

File: builtin/game/chat.lua [hunk 1]
```diff
@@ -1034,12 +1034,11 @@ core.register_chatcommand("time", {
 		end
 		local hour, minute = param:match("^(%d+):(%d+)$")
 		if not hour then
-			local new_time = tonumber(param)
-			if not new_time then
-				return false, S("Invalid time.")
+			local new_time = tonumber(param) or -1
+			if new_time ~= new_time or new_time < 0 or new_time > 24000 then
```
Comment (SwissalpS) [inline builtin/game/chat.lua:1038]: ```new_time ~= new_time``` shouldn't that be ```nil ~= new_time```?

Comment (SwissalpS) [inline builtin/game/chat.lua:1038]: ```new_time ~= new_time``` is always false and can be left out:
```lua
if new_time < 0 or new_time > 24000 then
```
since you already check for nil in the line above and adjust to -1

Comment (SwissalpS) [reply builtin/game/chat.lua:1038]: weird, this is not referencing the line I meant

Comment (SwissalpS) [inline builtin/game/chat.lua:1038]: ```new_time ~= new_time``` is always false
can't that be left out?

Comment (rubenwardy) [reply builtin/game/chat.lua:1038]: This is a NaN check

**Review by rubenwardy — APPROVED** [review]

File: builtin/game/chat.lua (hunk 1 above)
Comment (sfan5) [reply builtin/game/chat.lua:1038]: Should probably be `core.is_nan` then

Comment (appgurueu) [reply builtin/game/chat.lua:1038]: I don't think `tonumber` ever returns NaN.

Comment (SwissalpS) [reply builtin/game/chat.lua:1038]: Thanks. Lua keeps surprising me. That is so not intuitive.

Comment (appgurueu) [reply builtin/game/chat.lua:1038]: > Thanks. Lua keeps surprising me. That is so not intuitive.

That's not specific to Lua though - languages which comply to the float spec (IEEE 754) have to do it this way.

File: builtin/game/chat.lua [hunk 2]
```diff
@@ -1034,12 +1034,11 @@ core.register_chatcommand("time", {
...
+				return false, S("Invalid time (must be between 0 and 24000).")
 			end
-			-- Backward compatibility.
-			core.set_timeofday((new_time % 24000) / 24000)
```
Comment (erlehmann) [inline builtin/game/chat.lua:1042]: I see that the code now does not make sense to keep, but why was this even necessary in the first place?
