### PR TITLE
Fix entity lighting

### LINKED ISSUE #9482: Entity shading is broken
##### Minetest version

9ca0b3739cbaceaa291ac5062ab219e0aa7c49cb

##### Summary

The entity visuals cube and sprite are broken. Their shading no longer works (they are pitch black). 

It appears that falling nodes and dropped items are sometimes affected, too, but I haven't figured out  when this happens.

This is a regression from Minetest 5.1.1.

##### Steps to reproduce

* Play the devtest game
* Give yourself the entity spawner (testtools:entity_spawner)
* Punch to select entity type, place to spawn entity
* Spawn the following entities: testentities:cube, testentities:sprite (feel free to spawn the other entities, too)

Expected: All entities are shaded properly.
Actual: They are pitch black.

All of the entities worked in 5.1.1.

(note: split from #9479)

### PR DESCRIPTION
**Pull request by dcbrwn**
Fixes #9482. I've extracted a method to set node lighting. It's weird that there is updateLightNoCheck _with_ checks.

## How to test

Use https://git.minetest.land/Wuzzy/devtest to spawn all the entities possible. They should be rendered correctly now.

### CODE REVIEW

File: src/client/content_cao.cpp [hunk 1]
```diff
@@ -824,39 +818,43 @@ void GenericCAO::updateLightNoCheck(u8 light_at_pos)
...
-				m_spritenode->setColor(color);
+			for (u32 i = 0; i < node->getMaterialCount(); ++i) {
+				video::SMaterial &material = node->getMaterial(i);
+				material.EmissiveColor = color;
 			}
 		}
+	} else {
+		if (m_meshnode) {
+			setMeshColor(m_meshnode->getMesh(), color);
+		} else if (m_animated_meshnode) {
```
Comment (MoNTE48) [inline src/client/content_cao.cpp]: maybe, without { }?

Comment (dcbrwn) [reply src/client/content_cao.cpp]: If it's not enforced by the linter, I think it's better to leave this as it was before.

Comment (appgurueu) [reply src/client/content_cao.cpp]: Well, our style guide would probably say omit the braces.

Comment (SmallJoker) [reply src/client/content_cao.cpp]: Feel free to suggest such code style in newly written code. For moved/re-indented code such trivial changes are not required IMO.

Comment (paramat) [reply src/client/content_cao.cpp]: This is ok as it is, uisng braces increases clarity.
Our code style guidelines do not insist on omitting the braces for single-line actions, either is allowed.

Comment (paramat) [reply src/client/content_cao.cpp]: Also, it is important to remember that the linter often makes very bad suggestions, only do what the linter suggests if it makes sense and is readable code, otherwise whitelist the file to silence the linter.

**Comment by paramat** [comment]
Confirmed fixes lighting of "sprite" and "cube" entity visuals.
