### PR TITLE
[no squash] Send ActiveObjects along with definitions once connection is established

### LINKED ISSUE #8833: Commit fb6f1fd breaks world loading when damage is disabled
The commit fb6f1fd breaks world loading because of the function myplayer->isDead() defined in 3c395d9, when damage is disabled.

To reproduce, create a world in current master with damage disabled. World will not load further until you place a node.

### PR DESCRIPTION
**Pull request by ClobberXD**
- ActiveObjects are also sent once along with itemdefs and nodedefs, once the client reaches `CS_InitDone`.
  - This means that active objects are sent to the client earlier than in master, which sends activeobjects after all definitions are sent (the next step). While this isn't much of a difference, it becomes more noticeable the more the client is lagging.
  - This required some refactoring in `server.cpp` to prevent substantial code duplication.
- `LocalPlayer::isDead` always returned false if damage had been disabled, and that is now fixed - The method checks whether the player's CAO is immortal, and then whether the CAO's HP is 0.
- Lots of code-style fixes in `localplayer.cpp` and `Client::sendPlayerPos` (in client.cpp), including
  - Pointer placement
  - Spacing between keywords, parenthesis and braces. e.g. `if (` and `) {`
  - Spacing around operators in expressions
  - Merging braces and `else` keyword into one line. i.e. `} else {`
  - Removal of double-tab indents where not required.
  - Addition of missing literal `f` for floats.

### CODE REVIEW

File: src/client/localplayer.h [hunk 1]
```diff
@@ -149,7 +149,7 @@ class LocalPlayer : public Player
 
 	bool getAutojump() const { return m_autojump; }
 
-	bool isDead() const { return hp <= 0; }
+	bool isDead() const;
```
Comment (ClobberXD) [inline src/client/localplayer.h]: Moved the function's definition to the cpp file as it now references `GenericCAO::getHP` and `GenericCAO::getGroups`.

File: src/client/localplayer.h [hunk 2]
```diff
@@ -196,12 +196,14 @@ class LocalPlayer : public Player
...
 	aabb3f m_collisionbox = aabb3f(-BS * 0.30f, 0.0f, -BS * 0.30f, BS * 0.30f,
-			BS * 1.75f, BS * 0.30f);
+		BS * 1.75f, BS * 0.30f);
 	float m_eye_height = 1.625f;
 	float m_zoom_fov = 0.0f;
 	bool m_autojump = false;
 	float m_autojump_time = 0.0f;
+
 	v3f added_velocity = v3f(0.0f, 0.0f, 0.0f); // cleared on each move()
+	// TODO: Rename to adhere to convention: added_velocity --> m_added_velocity
```
Comment (ClobberXD) [inline src/client/localplayer.h]: TODO

**Comment by ClobberXD** [comment]
This PR is ready for review!

@SmallJoker I haven't removed `LocalPlayer::hp` in this PR, as this PR is quite large already, and replacing direct accesses to this variable with `getCAO()->setHP()` means even more changes. I'm afraid it'll have to wait for a little more. :)

**Comment by ClobberXD** [comment]
This PR is ready for review!

@SmallJoker I haven't removed `LocalPlayer::hp` in this PR, as this PR is quite large already, and replacing direct accesses to this variable with `getCAO()->setHP()` means even more changes. I'm afraid it'll have to wait for a little more. :)

**Comment by ClobberXD** [comment]
This PR is ready for review!

@SmallJoker I haven't removed `LocalPlayer::hp` in this PR, as this PR is quite large already, and replacing direct accesses to this variable with `getCAO()->setHP()` means even more changes. I'm afraid it'll have to wait for a little more. :)

File: src/client/localplayer.cpp [hunk 3]
```diff
@@ -106,8 +106,8 @@ bool LocalPlayer::updateSneakNode(Map *map, const v3f &position,
 		f32 distance_f = diff.getLength();
 
 		if (distance_f > min_distance_f ||
-				fabs(diff.X) > (.5 + .1) * BS + sneak_max.X ||
-				fabs(diff.Y) > (.5 + .1) * BS + sneak_max.Z)
+				fabs(diff.X) > 0.6f * BS + sneak_max.X ||
+				fabs(diff.Y) > 0.6f * BS + sneak_max.Z)
```
Comment (SmallJoker) [inline src/client/localplayer.cpp]: Intentional. `0.5` indicates 1/2 of a regular sized node. `+ 0.1` is for tolerances and sneaking on the edge.

File: src/client/localplayer.cpp [hunk 4]
```diff
@@ -250,7 +247,7 @@ void LocalPlayer::move(f32 dtime, Environment *env, f32 pos_max_d,
 	/*
 		Check if player is in liquid (the stable value)
 	*/
-	pp = floatToInt(position + v3f(0,0,0), BS);
+	pp = floatToInt(position + v3f(), BS);
```
Comment (SmallJoker) [inline src/client/localplayer.cpp]: What's this?

File: src/client/localplayer.cpp [hunk 5]
```diff
@@ -292,7 +288,7 @@ void LocalPlayer::move(f32 dtime, Environment *env, f32 pos_max_d,
 	float player_stepheight = (m_cao == nullptr) ? 0.0f :
 		(touching_ground ? m_cao->getStepHeight() : (0.2f * BS));
 
-	v3f accel_f = v3f(0,0,0);
+	v3f accel_f = v3f();
```
Comment (SmallJoker) [inline src/client/localplayer.cpp]: Superfluous

File: src/client/localplayer.cpp [hunk 6]
```diff
@@ -491,8 +484,8 @@ void LocalPlayer::applyControl(float dtime, Environment *env)
 	// All vectors are relative to the player's yaw,
 	// (and pitch if pitch move mode enabled),
 	// and will be rotated at the end
-	v3f speedH = v3f(0,0,0); // Horizontal (X, Z)
-	v3f speedV = v3f(0,0,0); // Vertical (Y)
+	v3f speedH = v3f(); // Horizontal (X, Z)
+	v3f speedV = v3f(); // Vertical (Y)
```
Comment (SmallJoker) [inline src/client/localplayer.cpp]: Superfluous assignments.

File: src/client/localplayer.cpp [hunk 7]
```diff
@@ -694,47 +667,55 @@ void LocalPlayer::applyControl(float dtime, Environment *env)
...
-	float eye_height = camera_barely_in_ceiling ?
-		m_eye_height - 0.125f : m_eye_height;
-	return v3f(0, BS * eye_height, 0);
+	float eye_height = camera_barely_in_ceiling ? m_eye_height - 0.125f : m_eye_height;
+	return v3f(0.0f, BS * eye_height, 0.0f);
+}
+
+bool LocalPlayer::isDead() const
+{
+	FATAL_ERROR_IF(!getCAO(), "LocalPlayer's CAO isn't initialized");
```
Comment (SmallJoker) [inline src/client/localplayer.cpp]: Why is the error needed? You could assume `false` as long it's not initialized.

File: src/client/localplayer.cpp [hunk 8]
```diff
@@ -694,47 +667,55 @@ void LocalPlayer::applyControl(float dtime, Environment *env)
...
+	return (!getCAO()->isImmortal() && hp == 0);
```
Comment (SmallJoker) [inline src/client/localplayer.cpp]: Superfluous parentheses.

File: src/client/localplayer.cpp [hunk 9]
```diff
@@ -884,30 +865,30 @@ void LocalPlayer::old_move(f32 dtime, Environment *env, f32 pos_max_d,
...
 		}
 	}
 
-	// this shouldn't be hardcoded but transmitted from server
-	float player_stepheight = touching_ground ? (BS * 0.6) : (BS * 0.2);
+	// TODO: This shouldn't be hardcoded but decided by the server
+	float player_stepheight = touching_ground ? (BS * 0.6f) : (BS * 0.2f);
 
-	v3f accel_f = v3f(0, 0, 0);
+	v3f accel_f = v3f();
```
Comment (SmallJoker) [inline src/client/localplayer.cpp]: Superfluous. Check for further `= v3f()` occurrences.

File: src/network/serverpackethandler.cpp [hunk 10]
```diff
@@ -312,22 +309,43 @@ void Server::handleCommand_Init2(NetworkPacket* pkt)
...
+
 	// Send time of day
 	u16 time = m_env->getTimeOfDay();
 	float time_speed = g_settings->getFloat("time_speed");
 	SendTimeOfDay(pkt->getPeerId(), time, time_speed);
 
 	SendCSMRestrictionFlags(pkt->getPeerId());
 
+	if (!client)
+	{
```
Comment (SmallJoker) [inline src/network/serverpackethandler.cpp]: Braces

File: src/server.cpp [hunk 11]
```diff
@@ -1089,9 +994,108 @@ PlayerSAO* Server::StageTwoClientInit(session_t peer_id)
...
+		ServerActiveObject* obj = m_env->getActiveObject(id);
+
+		// Add to data buffer for sending
+		writeU16((u8*)buf, id);
+		data_buffer.append(buf, 2);
+
+		// Remove from known objects
+		client->m_known_objects.erase(id);
+
+		if(obj && obj->m_known_by_count > 0)
```
Comment (SmallJoker) [inline src/server.cpp]: Space (3 more in this function)

File: src/client/localplayer.cpp (hunk 3 above)
Comment (ClobberXD) [reply src/client/localplayer.cpp]: Ah ok, I was wondering what this was all about. Done, thanks.

File: src/client/localplayer.cpp (hunk 4 above)
Comment (ClobberXD) [reply src/client/localplayer.cpp]: The default constructor of a `v3f` initialises all three components to 0. I assume this might be confusing to those who read the code, and if required I can make it explicit again, by changing it to `v3f(0.0f)` (single value constructor).

File: src/client/localplayer.cpp (hunk 5 above)
Comment (ClobberXD) [reply src/client/localplayer.cpp]: Oh right, it didn't occur to me, lol :)

File: src/client/localplayer.cpp (hunk 7 above)
Comment (ClobberXD) [reply src/client/localplayer.cpp]: The only function that calls this is when the CAO might not be initialised yet is `Client::sendPlayerPos`, and that checks if the CAO has been initialised before calling it. This error is to prevent other functions in the future to call this before the CAO is initialised and end up hitting a segfault for no apparent reason.

OTOH, if this just returns false, it'd mean that all functions that call `isDead` would process code that is based on the player being alive, while the player _could_ be dead. This, again, has the chance to create similar problems, and segfault or not, it'd take quite a while to figure out why the player is said to be alive while they obviously aren't.

File: src/network/serverpackethandler.cpp (hunk 10 above)
Comment (ClobberXD) [reply src/network/serverpackethandler.cpp]: Fixed

File: src/server.cpp (hunk 11 above)
Comment (ClobberXD) [reply src/server.cpp]: Done

File: src/client/localplayer.cpp (hunk 9 above)
Comment (ClobberXD) [reply src/client/localplayer.cpp]: Removed, thanks

File: src/client/localplayer.cpp (hunk 8 above)
Comment (ClobberXD) [reply src/client/localplayer.cpp]: Fixed

File: src/client/localplayer.cpp (hunk 6 above)
Comment (ClobberXD) [reply src/client/localplayer.cpp]: Removed.

File: src/client/localplayer.cpp (hunk 5 above)
Comment (ClobberXD) [reply src/client/localplayer.cpp]: Fixed

File: src/client/localplayer.cpp (hunk 4 above)
Comment (SmallJoker) [reply src/client/localplayer.cpp]: Adding a null vector is pointless functional-wise, but it's okay to keep it explicit.

File: src/network/clientpackethandler.cpp [hunk 12]
```diff
@@ -463,6 +463,11 @@ void Client::handleCommand_ActiveObjectRemoveAdd(NetworkPacket* pkt)
 		infostream << "handleCommand_ActiveObjectRemoveAdd: " << e.what()
 				<< ". The packet is unreliable, ignoring" << std::endl;
 	}
+
+	// m_activeobjects_received is false before the first
+	// TOCLIENT_ACTIVE_OBJECT_REMOVE_ADD packet is received
+	if (!m_activeobjects_received)
+		m_activeobjects_received = true;
```
Comment (SmallJoker) [inline src/network/clientpackethandler.cpp]: You could just set the variable without checking - the compiler probably does the same.

Comment (ClobberXD) [reply src/network/clientpackethandler.cpp]: I got a little greedy for performance and tried to reduce variable setting overhead by checking for the value first ;)

I'll change it though.

File: src/client/localplayer.cpp (hunk 4 above)
Comment (ClobberXD) [reply src/client/localplayer.cpp]: Alright, I'll make it explicit by using the single value constructor. Thanks

**Comment by ClobberXD** [comment]
@SmallJoker I've addressed all your line comments.

File: src/network/serverpackethandler.cpp [hunk 13]
```diff
@@ -312,22 +309,42 @@ void Server::handleCommand_Init2(NetworkPacket* pkt)
...
 	// Send time of day
 	u16 time = m_env->getTimeOfDay();
 	float time_speed = g_settings->getFloat("time_speed");
 	SendTimeOfDay(pkt->getPeerId(), time, time_speed);
 
 	SendCSMRestrictionFlags(pkt->getPeerId());
 
+	if (!client) {
+		MutexAutoLock(m_con);
+		client = getClient(pkt->getPeerId(), CS_InitDone);
```
Comment (SmallJoker) [inline src/network/serverpackethandler.cpp]: Already checked in L318. Why?

Comment (ClobberXD) [reply src/network/serverpackethandler.cpp]: Removed

File: src/client/localplayer.cpp (hunk 8 above)
Comment (ClobberXD) [reply src/client/localplayer.cpp]: Fixed

**Comment by sfan5** [comment]
What happens when you connect to an older (say 5.0) server? Will autoforward still be broken?

**Comment by ClobberXD** [comment]
I haven't tested this scenario, but it should work. This is because the only code that potentially invokes `LocalPlayer::isDead` prior to AOs being sent, is `Client::sendPlayerPos`, which first checks if `m_activeobjects_sent` is true, and only then invokes that function. `m_activeobjects_sent` is false upon initialisation, and is set to true only after the first `TOCLIENT_ACTIVEOBJECTS_REMOVE_ADD` packet is received. That means `LocalPlayer::isDead` won't be invoked at all, if active objects haven't been received by the client.

**Comment by ClobberXD** [comment]
@sfan5 Connecting to an older server does not seem to cause any problems, and I can see all the loaded AOs upon connection without any issues.

**Comment by paramat** [comment]
Needs merge for 5.1.0.

**Comment by paramat** [comment]
My 'W' finger thanks you.
