### PR TITLE
[no sq] Safety and other fixes

### LINKED ISSUE #14435: `VoxelManip:was_modified()` doesn't do what it says
## Problem

`VoxelManip:was_modified()` doesn't work as expected.
See https://forum.minetest.net/viewtopic.php?t=30327

#### What the documentation says

https://github.com/minetest/minetest/blob/e734b3f0d8055ff3ae710f3632726a711603bf84/doc/lua_api.md?plain=1#L4853-L4855

#### What it actually does

It can only return true if it is called on a mapgen VoxelManip.
`minetest.set_data()` does not exist.
Instead, one of those functions can make it true
``` lua
minetest.set_node(pos, node)
minetest.add_node(pos, node)
minetest.remove_node(pos, node)
minetest.swap_node(pos, node)
```
And probably more.
It only happens when `ServerMap::updateVManip(v3s16 pos)` gets called, such that `m_is_dirty` becomes true.

## Solutions

Either 
- update the documentation to describe its current behavior
- completely remove the function (deprecate it)
- or change it such that it does what the documentation claims. Maybe this was the case at some point in the past, but I can't recall that `minetest.set_data()` ever existed.

### PR DESCRIPTION
**Pull request by sfan5**
fixes #14435
fixes https://github.com/orgs/minetest/discussions/111 (internal)
fixes https://github.com/orgs/minetest/discussions/108 (internal)
fixes https://github.com/orgs/minetest/discussions/89 (internal)

## To do

This PR is Ready for Review.

## How to test

see linked discussions

### CODE REVIEW

File: src/unittest/test_voxelarea.cpp [hunk 1]
```diff
@@ -231,143 +249,143 @@ void TestVoxelArea::test_index_xyz_all_pos()
 	VoxelArea v1;
 	UASSERTEQ(s32, v1.index(156, 25, 236), 155);
 
-	VoxelArea v2(v3s16(756, 8854, -875), v3s16(-147, -9547, 669));
-	UASSERTEQ(s32, v2.index(156, 25, 236), 1267138774);
+	VoxelArea v2(v3s16(-147, -9547, -875), v3s16(756, 8854, 669));
```
Comment (sfan5) [inline src/unittest/test_voxelarea.cpp:252]: note: all of these positions were not sorted, causing garbage results

File: src/voxel.cpp [hunk 2]
```diff
@@ -277,46 +259,38 @@ void VoxelManipulator::copyTo(MapNode *dst, const VoxelArea& dst_area,
 	-----------------------------------------------------
 */
 
-void VoxelManipulator::clearFlag(u8 flags)
+void VoxelManipulator::setFlag(const VoxelArea &a, u8 flags)
```
Comment (SmallJoker) [inline src/voxel.cpp:262]: `setFlags` would be more precise. Feel free to ignore if it's not worth the effort.

File: src/voxel.h [hunk 3]
```diff
@@ -231,60 +229,55 @@ class VoxelArea
 
 		assert(contains(a));	// pre-condition
 
+		const auto &take = [&result] (v3s16 min, v3s16 max) {
+			if (max >= min) {
```
Comment (SmallJoker) [inline src/voxel.h:233]: FYI: This operator does not compare all coordinates individually.

File: src/script/lua_api/l_vmanip.cpp [hunk 4]
```diff
@@ -280,16 +285,16 @@ int LuaVoxelManip::l_get_param2_data(lua_State *L)
...
 
 	if (use_buffer)
 		lua_pushvalue(L, 2);
 	else
 		lua_createtable(L, volume, 0);
 
 	for (u32 i = 0; i != volume; i++) {
-		lua_Integer param2 = vm->m_data[i].param2;
+		// Do not push unintialized data to Lua
+		lua_Integer param2 = (vm->m_flags[i] & VOXELFLAG_NO_DATA) ? 0 : vm->m_data[i].getParam2();
```
Comment (SmallJoker) [inline src/script/lua_api/l_vmanip.cpp:297]: `vm->m_flags` and `vm->m_data` could be moved outside the loop if the compiler is not smart enough to do it automatically.

The same remark for `LuaVoxelManip::l_get_data`.

**Review by SmallJoker — COMMENTED** [review]
Looks good, works. Will approve after the few comments were addressed.

File: src/voxel.cpp (hunk 2 above)
Comment (sfan5) [reply src/voxel.cpp:262]: :shrug:

File: src/voxel.h (hunk 3 above)
Comment (sfan5) [reply src/voxel.h:233]: huh? what else would it do?
grafik

File: src/script/lua_api/l_vmanip.cpp (hunk 4 above)
Comment (sfan5) [reply src/script/lua_api/l_vmanip.cpp:297]: I hope it is.

File: src/voxel.h (hunk 3 above)
Comment (Desour) [reply src/voxel.h:233]: It sorts like a tuple, lexicographically. This gives a total order or so, which you need e.g. for std::map.

Comment (Desour) [reply src/voxel.h:233]: `v3s16(1,2,3) < v3s16(2,1,3)`
Why not sort each component individually?

Comment (SmallJoker) [reply src/voxel.h:233]: `max.X >= min.X && max.Y >= min.Y && max.Z >= min.Z` is probably what you intended, thus my comment.

But why exactly is `(b.getVolume() != 0)` not sufficient? Due to potential integer under-/overflows of the edge coordinates?

Comment (sfan5) [reply src/voxel.h:233]: It's not about integer overflow, even just the simple test I wrote triggers the assert. 

I'll fix this in a different way.

**Review by Desour — COMMENTED** [review]
(Comments for 1st commit.)

File: src/voxel.h [hunk 5]
```diff
@@ -134,7 +134,7 @@ class VoxelArea
 	 */
 	bool hasEmptyExtent() const
 	{
-		return MaxEdge - MinEdge == v3s16(-1, -1, -1);
+		return m_cache_extent == v3s16(0,0,0);
```
[the remark this answers is not in the document]
Comment (sfan5) [reply src/voxel.h:135]: My IDE search says nobody writes to MinEdge or MaxEdge.

File: src/script/lua_api/l_vmanip.cpp [hunk 6]
```diff
@@ -108,6 +108,11 @@ int LuaVoxelManip::l_set_data(lua_State *L)
 		lua_pop(L, 1);
 	}
 
+	// FIXME: in theory we should clear VOXELFLAG_NO_DATA here.
+	// However there is no way to tell which values Lua code has intended to set
+	// (if they were VOXELFLAG_NO_DATA before), and which were just not touched.
+	// This potentially causes problems with unloaded areas *shrug*
```
Comment (Desour) [inline src/script/lua_api/l_vmanip.cpp:114]: Worth mentioning: `MMVManip::initialEmerge` is never called with `load_if_inexistent=false` (it's only used in a unittest and benchmarks). So this is only an issue outside of map. (=> If you write with a vmanip outside of map, you still read ignore/0.)

**Review by Desour — COMMENTED** [review]
(2nd commit.)

File: src/voxel.h (hunk 5 above)
[the remark this answers is not in the document]
Comment (Desour) [reply src/voxel.h:136]: Maybe add a comment to `MinEdge`/`MaxEdge` to warn about not writing to them.

(I wish my IDE could do this too.)

File: src/script/lua_api/l_object.h [hunk 7]
```diff
@@ -38,10 +38,12 @@ class ObjectRef : public ModApiBase {
...
 
 	// Creates an ObjectRef and leaves it on top of stack
-	// Not callable from Lua; all references are created on the C side.
+	// NOTE: do not call this, use `ScriptApiBase::objectrefGetOrCreate()`!
 	static void create(lua_State *L, ServerActiveObject *object);
 
-	static void set_null(lua_State *L);
+	// Clear the pointer in the ObjectRef (at -1).
+	// Throws an fatal error if the object pointer wasn't `expect`.
+	static void set_null(lua_State *L, void *expect);
```
Comment (Desour) [inline src/script/lua_api/l_object.h:46]: Why void ptr?

**Review by Desour — COMMENTED** [review]
3rd

File: src/script/lua_api/l_object.h (hunk 7 above)
Comment (sfan5) [reply src/script/lua_api/l_object.h:46]: :shrug:

**Review by Desour — APPROVED** [review]
(Haven't tested much.)

File: src/script/lua_api/l_vmanip.cpp [hunk 8]
```diff
@@ -108,6 +108,12 @@ int LuaVoxelManip::l_set_data(lua_State *L)
 		lua_pop(L, 1);
 	}
 
+	// FIXME: in theory we should clear VOXELFLAG_NO_DATA here
+	// However there is no way to tell which values Lua code has intended to set
+	// (if they were VOXELFLAG_NO_DATA before), and which were just not touched.
+	// In practice this doesn't cause problems because load_from_map() will cause
+	// all covered blocks to be loaded.
```
[the remark this answers is not in the document]
Comment (sfan5) [reply src/script/lua_api/l_vmanip.cpp:115]: yes

File: src/voxel.h (hunk 5 above)
[the remark this answers is not in the document]
Comment (SmallJoker) [reply src/voxel.h:136]: It might be worth to make `(Max|Min)Edge` private and expose them through functions to ensure there's no-one writing to them. Currently this does appear to be somewhat insecure and error-prone.

**Review by SmallJoker — APPROVED** [review]
Re-read the code and checked a few singleplayer worlds with Lua mapgens. No issue found. No new valgrind error appears.
