### PR TITLE
minetest.serialize: Reversible number serialization

### LINKED ISSUE #7925: minetest.serialize truncates big numbers on some systems (Raspberry Pi for instance)
##### Issue type
 - Bug report
 
##### Minetest version
Minetest Server Version 0.4.17-1 compiled from source

##### OS / Hardware
Operating system: Raspbian Lite (Debian 9.6)
Machine: Raspberry Pi 2 / Raspberry Pi 3

##### Summary
Using `minetest.serialize` and `minetest.deserialize` on Raspberry Pi with long numbers (> 32 bits) truncates the number to a max 32 bit number.

##### Steps to reproduce
A good case is serializing a table storing a position hash. This is a simplified extract of code storing a position hash in an entity static data:
```
local pos = {...}
local staticdata = minetest.serialize({pos=minetest.hash_node_position(pos)})
...
local data = minetest.deserialize(staticdata)
```
Retrieved pos hash is not identical before and after.

Some more information can be found in the original issue involving position loss: https://github.com/pyrollo/display_modpack/issues/19

What I suspect is that the "%q" `string.format` flag is not working the same way on this system than on x64 systems.

Unfortunately I do not have any Rapberry and can not investigate further.

### PR DESCRIPTION
**Pull request by HybridDog**
The hexadecimal format is less human-readable, but for human-readable output the dump function should be used instead of minetest.serialize anyways.

This should fix #7925.
Please test and review.

### CODE REVIEW

**Comment by sfan5** [comment]
Minetest's built-in Lua is 5.1 so this is a no-go.

**Comment by HybridDog** [comment]
> What about "%.30g" instead?

I've changed it; it seems to work.

File: builtin/common/tests/serialize_spec.lua [hunk 1]
```diff
@@ -18,6 +18,18 @@ describe("serialize", function()
 		assert.same(test_in, test_out)
 	end)
 
+	it("handles precise numbers", function()
+		local test_in = 0x1.ae2d159cp-1
```
Comment (sfan5) [inline builtin/common/tests/serialize_spec.lua:22]: This is not valid syntax in Lua 5.1, which is why the test fail.

**Comment by sfan5** [comment]
`%.30g` might be more than what's needed, `%.17g` should work just as well (https://github.com/minetest/minetest/issues/7925#issuecomment-443524908):
<pre>
Lua 5.1.5  Copyright (C) 1994-2012 Lua.org, PUC-Rio
> val = 0.269594915894577
> =tostring(val)
0.26959491589458
> =string.format("%.30g", val)
0.269594915894577014103816736679
> =(0.269594915894577014103816736679 == val)
true
> =string.format("%.17g", val)
0.26959491589457701
> =(0.26959491589457701 == val)
true
</pre>

File: builtin/common/tests/serialize_spec.lua [hunk 2]
```diff
@@ -18,6 +18,18 @@ describe("serialize", function()
 		assert.same(test_in, test_out)
 	end)
 
+	it("handles precise numbers", function()
+		local test_in = math.random()
```
Comment (sfan5) [inline builtin/common/tests/serialize_spec.lua:22]: A deterministic value here is better.
```suggestion
		local test_in = 0.269594915894577
```
