### PR TITLE
Re-show death screen when a formspec is closed while player is dead

### LINKED ISSUE #11523: If player receives a formspec while in the death screen, the death screen disappears, breaking the game
##### Minetest version
```
5.5.0
```

##### Summary
If you receive a formspec with `minetest.show_formspec` while you're in the death screen, the death screen is overwritten by the new formspec. You can close the new formspec normally and you now can walk, while still being dead (0 HP), around the world but you can't interact with it and you can't respawn. It's a very broken state of gameplay that causes lots of bugs. The only way to get out of this "zombie state" is to rejoin.

##### Steps to reproduce
1. Get `luacmd` mod
2. Start any game
3. `/lua me:set_hp(0); minetest.after(3, function() minetest.show_formspec("singleplayer", "title", "size[5,5]") end)`
4. Do nothing for 3 seconds

Expected result:
You should die and the death screen is not overwritten, nor will you end up in a weird or broken player state.

Actual result:
You will die, but after 3 seconds, the death screen is replaced by a simple dummy formspec (see above). You can close it and walk around the world with 0 HP. You can't respawn because the respawn button, which is the only way to respawn, is gone for good.

##### Possible solutions
A) While the death screen is open, reject any incoming formspecs so that the death screen and the respawn button does not disappear.
B) Open the formspec as usual, but when the player closes it, the Death Screen immediately appears again. Basically, the idea is to instantly open the death screen when HP=0 and no "normal" formspec is open
C) Refactor the Death Screen completely. Instead of using a normal formspec
C) Something else?

I personally prefer solution A because it's the simplest but it will need proper documentation and a warning in `lua_api.txt`.

##### Related issues

* #7879
* #2945

### PR DESCRIPTION
**Pull request by sofar**
If a mod sends a formspec via show_formspec() while the player is on the death screen, it replaces the death screen. When the player closes that formspec, they enter a "zombie state" — walking at 0 HP with no way to respawn, requiring a reconnect.

Fix by re-showing the death screen whenever a non-death formspec is closed (fields.quit) while the player has 0 HP.

To reproduce, register a chat command that kills the player and sends a formspec after a delay:

    core.register_chatcommand("test_death_formspec", {
        privs = {server = true},
        func = function(name)
            local player = core.get_player_by_name(name)
            player:set_hp(0, {type = "set_hp"})
            core.after(3, function()
                core.show_formspec(name, "test:dialog",
                    "size[5,3]label[1,1;Test]button_exit[1.5,2;2,0.5;ok;OK]")
            end)
        end,
    })

Run /test_death_formspec, wait for the dialog, close it. Without the fix, the player is stuck as a zombie. With the fix, the death screen re-appears.

Fixes #11523

Co-Authored-By: Claude Opus 4.6 (1M context) <noreply@anthropic.com>

### CODE REVIEW

File: builtin/game/death_screen.lua [hunk 1]
```diff
@@ -27,5 +27,12 @@ core.register_on_player_receive_fields(function(player, formname, fields)
 		player:respawn()
 		core.log("action", player:get_player_name() .. " respawns at " ..
 				player:get_pos():to_string())
+		return
+	end
+
+	-- If a non-death formspec was closed while the player is dead,
+	-- re-show the death screen to prevent the "zombie state" (see #11523).
+	if formname ~= "__builtin:death" and fields.quit and player:get_hp() == 0 then
+		core.show_death_screen(player, nil)
```
Comment (sfan5) [inline builtin/game/death_screen.lua:37]: might be useful if it ever causes problems
```suggestion
		core.log("info", "Re-showing death screen to " .. player:get_player_name())
		core.show_death_screen(player, nil)
```

Comment (sofar) [reply builtin/game/death_screen.lua:37]: Adopted, thanks.
