### PR TITLE
Fix builtin inventory list crash when size = 0

### LINKED ISSUE #7296: Inventory list size 0 crash for "craft" and "craftpreview"
##### Minetest version
```
Any recent version as of 180504
```

##### Summary
For "craftpreview":
```
2018-05-04 18:21:06: ERROR[Server]: /data/Minetest/minetest/src/server.cpp:b2a: void Server::UpdateCrafting(RemotePlayer*): An engine assumption 'plist' failed.
2018-05-04 18:21:06: ERROR[Server]: Debug stacks:
2018-05-04 18:21:06: ERROR[Server]: DEBUG STACK FOR THREAD 7f9c30f70700: 
2018-05-04 18:21:06: ERROR[Server]: #0  virtual void* UpdateThread::run()
2018-05-04 18:21:06: ERROR[Server]: DEBUG STACK FOR THREAD 7f9c31ffb700: 
2018-05-04 18:21:06: ERROR[Server]: #0  virtual void* EmergeThread::run()
2018-05-04 18:21:06: ERROR[Server]: DEBUG STACK FOR THREAD 7f9c33fff700: 
2018-05-04 18:21:06: ERROR[Server]: #0  virtual void* ServerThread::run()
2018-05-04 18:21:06: ERROR[Server]: #1  void Server::Receive()
2018-05-04 18:21:06: ERROR[Server]: #2  void Server::ProcessData(NetworkPacket*)
2018-05-04 18:21:06: ERROR[Server]: #3  void Server::SendInventory(PlayerSAO*)
2018-05-04 18:21:06: ERROR[Server]: #4  void Server::UpdateCrafting(RemotePlayer*)
```
"craft" (segfault)
```
#0  0x000055555596fe20 in InventoryList::getSize() const ()
#1  0x00005555556e37fd in ScriptApiItem::item_CraftPredict(ItemStack&, ServerActiveObject*, InventoryList const*, InventoryLocation const&) ()
#2  0x0000555555a95232 in Server::UpdateCrafting(RemotePlayer*) ()
#3  0x0000555555a956bb in Server::SendInventory(PlayerSAO*) ()
#4  0x0000555555a9dd09 in Server::setInventoryModified(InventoryLocation const&, bool) ()
#5  0x000055555570e14d in InvRef::l_set_size(lua_State*) ()
#6  0x00005555556d2c66 in script_exception_wrapper(lua_State*, int (*)(lua_State*)) ()
#7  0x00007ffff666ce97 in ?? () from /usr/lib/x86_64-linux-gnu/libluajit-5.1.so.2
#8  0x00007ffff66ba27c in lua_pcall () from /usr/lib/x86_64-linux-gnu/libluajit-5.1.so.2
#9  0x00005555556d81c7 in ScriptApiBase::runCallbacksRaw(int, RunCallbacksMode, char const*) ()
#10 0x00005555556ea19a in ScriptApiPlayer::on_joinplayer(ServerActiveObject*) ()
```

##### Steps to reproduce
```Lua
minetest.register_on_joinplayer(function(player)
	local inv = player:get_inventory()
	inv:set_size("craft", 0) -- either this = 0
	inv:set_size("craftpreview", 0) -- or this = 0
end)
```

### PR DESCRIPTION
**Pull request by SmallJoker**
Fixes #7296 

Testing code:
```Lua
minetest.register_on_joinplayer(function(player)
	local inv = player:get_inventory()
	inv:set_size("craft", 0) -- either this = 0
	inv:set_size("craftpreview", 0) -- or this = 0
end)
```

`minetest.register_craft_predict` is still triggered when "craft" has at least one slot, even when "craftresult" has the size 0. This might seem a bit weird but makes it possible to implement custom crafting methods, which work differently to what we currently have.

### CODE REVIEW

File: src/server.cpp [hunk 1]
```diff
@@ -2685,20 +2685,24 @@ void Server::DeleteClient(session_t peer_id, ClientDeletionReason reason)
 
 void Server::UpdateCrafting(RemotePlayer *player)
 {
+	InventoryList *clist = player->inventory.getList("craft");
+	if (!clist || clist->getSize() < 1)
```
Comment (nerzhul) [inline src/server.cpp]: getSize can be lesser than zero ? if not just zero check

Comment (SmallJoker) [reply src/server.cpp]: Unlike the `size()` getter functions in container classes, this here returns a `u32`. Changed it to `== 0` now, whereas it will have the same effect.
