### PR TITLE
Merge colorized buffers after meshgen

### LINKED ISSUE #16756: Hardware colors and overlay for nodes cause massive framerate drops
### Luanti version

```true
Luanti 5.14.0 (Windows)
Using LuaJIT 2.1.1736781742
Built by Clang 20.1
Running on Windows/10.0.19041 x86_64
BUILD_TYPE=Release
RUN_IN_PLACE=1
USE_CURL=1
USE_GETTEXT=1
USE_SOUND=1
STATIC_SHAREDIR="."
STATIC_LOCALEDIR="locale"
```

### Operating system and version

Windows 10 x86_64

### CPU model

Intel Core i9-10900F

### GPU model

NVIDIA GeForce RTX 3060

### Active renderer

4.6.0 OpenGL SDL 2.32.2

### Summary

Using `paramtype2 = "color"` with some `palette` and `overlay_tiles` both causes huge performance impact (about 10x times worse than normal nodes in worst case scenario), especially on a mapblock loading stage.

Here are some examples of an (almost) single layer of grass nodes tinted with hardware coloring. All screenshots were done in the same place with range of 512 nodes in a pre-generated world.

First screenshot was taken without any tint and overlay, average FPS is around 320:
Image

Second screenshot - just tinting, no overlay, average FPS is around 100:
Image

Activating overlay drops FPS to 70:
Image

And FPS drops to 10-30 during mapblock loading and mesh updates (which happens commonly when camera rotates or moves), which makes game state unplayable:
Image

Additionally camera rotation and movements causes constant game freezes that can't be captured with internal lagometer.

### Steps to reproduce

Create a simple node that uses `paramtype2 = "color",` and some palette, add some `overlay_tiles` and place many of these nodes in the world.

Here is a simple game that has tinted grass and where that bug can be reproduced in any fresh generated world: https://github.com/paulevsGitch/Betatest-1.7.3

### PR DESCRIPTION
**Pull request by sfan5**
Did you know git can handle non-ASCII branch names?

fixes #16756

### CODE REVIEW

**Comment by user333dev** [comment]
> Did you know git can handle non-ASCII branch names?

Nope!

File: src/client/meshgen/collector.cpp [hunk 1]
```diff
@@ -4,6 +4,21 @@
 
 #include "collector.h"
 #include <stdexcept>
+#include <cassert>
+
+bool PreMeshBuffer::append(const PreMeshBuffer &other)
+{
+	const size_t nv = vertices.size();
```
Comment (SmallJoker) [inline src/client/meshgen/collector.cpp:11]: Might an `assert` make sense here to ensure that the two `TileLayer` are equal? Currently you're doing this in `applyColorAndMerge`, and I doubt that's the best fitting place.

File: src/client/meshgen/collector.cpp [hunk 2]
```diff
@@ -4,6 +4,21 @@
...
+	const size_t ni = indices.size();
+	if (nv + other.vertices.size() > U16_MAX)
```
Comment (SmallJoker) [inline src/client/meshgen/collector.cpp:13]: "What is the origin of this magic number?"

Please add a reference that we assume that the vertex limit is given by the type `video::EIT_16BIT`.

File: src/client/tile.h [hunk 3]
```diff
@@ -167,6 +167,22 @@ struct TileLayer
 	bool has_color = false;
 };
 
+template<>
+struct std::hash<TileLayer>
+{
+	/// @note expresses the same relationship as TileLayer::operator==
```
Comment (SmallJoker) [inline src/client/tile.h]: Not quite. `operator==(const TileLayer &other)`  includes 6 members. This one here is only 3. If somehow possible, I would appreciate to give this comparator a unique name such that its purpose (or use-case) is clear.

File: src/client/mapblock_mesh.cpp [hunk 4]
```diff
@@ -585,6 +587,47 @@ void PartialMeshBuffer::draw(video::IVideoDriver *driver) const
...
+static void applyColorAndMerge(std::vector<PreMeshBuffer> &prebuffers)
+{
+	// TODO: we should change the meshgen so it already applies the tile color
+	// so that we don't need to this extra step.
+	// However currently the CAO code relies on the ability to erase the vertex
+	// colors (light data) before applying the tile colors.
+
+	for (auto &p : prebuffers) {
+		p.applyTileColor();
+		// erase color information for later comparisons
```
Comment (SmallJoker) [inline src/client/mapblock_mesh.cpp:600]: Is this color information no longer relevant because the vertices are now colorized?
If so, then I would suggest to include a comment:

`The color information is now baked into 'p.vertices' and thus no longer relevant.`

File: src/client/mapblock_mesh.cpp [hunk 5]
```diff
@@ -585,6 +587,47 @@ void PartialMeshBuffer::draw(video::IVideoDriver *driver) const
...
+		if (dst.append(p)) {
+			p = PreMeshBuffer();
+		} else {
+			// other buffer full, this one becomes the new target
+			it->second = i;
+		}
+	}
+
+	{
+		auto &c = prebuffers;
```
Comment (SmallJoker) [inline src/client/mapblock_mesh.cpp]: 1. This does IMO not improve readability and would prefer the more verbose notation - which also happens to make the separate code block unneeded.
2. Wouldn't it be cheaper to leave those empty entries, and skip them in the `MapBlockMesh::MapBlockMesh` loop?

File: src/client/meshgen/collector.cpp (hunk 1 above)
Comment (sfan5) [reply src/client/meshgen/collector.cpp:11]: responsibility of the caller IMO

File: src/client/meshgen/collector.cpp (hunk 2 above)
Comment (sfan5) [reply src/client/meshgen/collector.cpp:13]: IMO the fact that we're working entirely with 16-bit indices should be obvious to someone familiar with graphics.
Also note that no Irrlicht buffers are involved, so there's no `EIT_XXX` to be defined anywhere.

File: src/client/tile.h (hunk 3 above)
Comment (sfan5) [reply src/client/tile.h]: I can reword this to "Any layers equal according to `TileLayer::operator==` will have the same hash value according to this function" to be exact. But fundamentally a hash is not a fully unique representation of an object, so it's okay to not hash all properties.

 > If somehow possible, I would appreciate to give this comparator a unique name such that its purpose (or use-case) is clear.

You could argue that `TileLayer::operator==` should be renamed (and consequently the hash too) because it's not actually an equality check, but then that's out-of-scope for this PR. Also note that this will make it more complicated to use this class in STL containers.

File: src/client/mapblock_mesh.cpp (hunk 5 above)
Comment (sfan5) [reply src/client/mapblock_mesh.cpp]: > Wouldn't it be cheaper to leave those empty entries, and skip them in the MapBlockMesh::MapBlockMesh loop?

I tried that, but it breaks things. I think there's some reliance on the buffer indices in the final mesh. :shrug:

File: src/client/meshgen/collector.cpp (hunk 2 above)
Comment (sfan5) [reply src/client/meshgen/collector.cpp:13]: I could introduce a `static constexpr u32 MAX_INDEX = U16_MAX;` in `PreMeshBuffer` if that's helpful

Comment (SmallJoker) [reply src/client/meshgen/collector.cpp:13]: Fair point. Yes, those who deal with the code are likely to understand this. Fine by me, resolved.

File: src/client/mapblock_mesh.cpp (hunk 5 above)
Comment (SmallJoker) [reply src/client/mapblock_mesh.cpp]: Hm that's strange but acceptable. Then let's keep it like this. Thank you for the comment inside the loop.

**Review by SmallJoker — APPROVED** [review]
