### PR TITLE
Mapgen v6: Various mudflow code improvements and bugfixes 

### LINKED ISSUE #8784: V6 mudflow doesn’t work as intended
##### Minetest version
`master`

##### Summary
https://github.com/minetest/minetest/blob/2f879e8bbd8329e4c796dc1f7eeea9bdc3be2b3d/src/mapgen/mapgen_v6.cpp#L779-L787
This code was probably intended to run several iterations mud flow in different directions. But in fact, 0th and 2nd iterations are only executed for the last position.

https://github.com/minetest/minetest/blob/2f879e8bbd8329e4c796dc1f7eeea9bdc3be2b3d/src/mapgen/mapgen_v6.cpp#L796-L798
That should be single loop. Also `i` needs to be changed on each iteration, otherwise it may go out of sync with `y`. It will actually, should the loop reach dirt on non-dirt, due to `continue` at line 831.

https://github.com/minetest/minetest/blob/2f879e8bbd8329e4c796dc1f7eeea9bdc3be2b3d/src/mapgen/mapgen_v6.cpp#L824-L827
This check is wrong. Either the area has enough margin below the chunk generated, and the check always passes, or it hasn’t, so that `y` can touch the area bottom, but then `add_y` will make `i2` index node out of column but not out of area, generally.

### PR DESCRIPTION
**Pull request by paramat**
Mapgen v6: Various mudflow code improvements and bugfixes

Calculate 'i' inside 'y' loop to avoid 'i' and 'y' becoming
out of step due to the uses of 'continue'.
Simplify calculation of 'p2d' when coordinates are inverted.
Remove some unnecessary and unreliable 'index out of
voxelmanip' checks.
Move calculation of '&em' out of loops.
For 'Loop further down until not air' code, use y coordinate
to detect being out of voxelmanip, instead of checking index
which did not detect that.
Add and improve comments.
Indent the 'for (;; y--) {' loop.
Improve format and fix codestyle issues.
/////////////////////////////////

screenshot_20190823_230841

^ PR

mudflow_master

^ Master branch

Closes #8784 attends to remaining issues.

Something i missed in #8795 : i realised that
```
			// Invert coordinates on second iteration to process columns in
			// opposite order, to avoid a directional bias.
			if (k == 1) {
				p2d = v2s16(node_min.X, node_min.Z) + v2s16(
					mudflow_maxpos - (x - mudflow_minpos),
					mudflow_maxpos - (z - mudflow_minpos));
			} else {
				p2d = v2s16(node_min.X, node_min.Z) + v2s16(x, z);
			}
```
can be simplified to
```
			// Invert coordinates on second iteration to process columns in
			// opposite order, to avoid a directional bias.
			if (k == 1)
				p2d = v2s16(node_max.X, node_max.Z) - v2s16(x, z);
			else
				p2d = v2s16(node_min.X, node_min.Z) + v2s16(x, z);
```

### CODE REVIEW

File: src/mapgen/mapgen_v6.cpp [hunk 1]
```diff
@@ -807,51 +806,44 @@ void MapgenV6::flowMud(s16 &mudflow_minpos, s16 &mudflow_maxpos)
...
-
-					// Don't flow it if the stuff under it is not mud
+					// Don't flow it if the stuff under it is not mud,
+					// to leave at least 1 node of mud.
 					{
 						u32 i2 = i;
 						VoxelArea::add_y(em, i2, -1);
-						// Cancel if out of area
-						if (!vm->m_area.contains(i2))
-							continue;
```
Comment (paramat) [inline src/mapgen/mapgen_v6.cpp]: Unnecessary check because:
At this point in code, y is no lower than node_min.Y (mapchunk base), voxelmanip base is 16 nodes below node_min.Y, so y - 1 is obviously inside area.

File: src/mapgen/mapgen_v6.cpp [hunk 2]
```diff
@@ -807,51 +806,44 @@ void MapgenV6::flowMud(s16 &mudflow_minpos, s16 &mudflow_maxpos)
...
 
-				// Check that upper is walkable. Cancel
-				// dropping if upper keeps it in place.
+				// Check if node above is walkable. If so, cancel
+				// flowing as if node above keeps it in place.
 				u32 i3 = i;
 				VoxelArea::add_y(em, i3, 1);
-				MapNode *n3 = NULL;
-
-				if (vm->m_area.contains(i3)) {
```
Comment (paramat) [inline src/mapgen/mapgen_v6.cpp]: Unnecessary check removed because:
At this point in code, y is no higher than node_max.Y (mapchunk top), voxelmanip top is 16 nodes above node_max.Y, so y + 1 is obviously inside area.

File: src/mapgen/mapgen_v6.cpp [hunk 3]
```diff
@@ -865,8 +857,6 @@ void MapgenV6::flowMud(s16 &mudflow_minpos, s16 &mudflow_maxpos)
 						continue;
 					// Check that under side is air
 					VoxelArea::add_y(em, i2, -1);
-					if (!vm->m_area.contains(i2))
-						continue;
```
Comment (paramat) [inline src/mapgen/mapgen_v6.cpp]: Unnecessary check removed because:
The previous 'out of voxelmanip' check a few lines above ensures this column is horizontally inside the voxelmanip.
y is somewhere between node_min.Y and node_max.Y, so y - 1 is well within the voxelmanip.

**Comment by paramat** [comment]
Hmmm  i wonder if this:
```
			s16 y = node_max.Y;

			while (y >= node_min.Y) {

			for (;; y--) {
```
is identical to, and should be changed to
```
			for (s16 y = node_max.Y; y >= node_min.Y; y--) {
```
?
Keeping in mind y is modified inside the loop.

File: src/mapgen/mapgen_v6.cpp (hunk 3 above)
Comment (numberZero) [reply src/mapgen/mapgen_v6.cpp]: No it doesn’t. `max_spread_amount` does (unless I missed something), it is one less than the mapblock size specifically for that, to let you step that one node away fearlessly. Otherwise wrong node would be accessed sometimes.

Remember: `VoxelArea::contains` only checks that some linear combination λ = αx + βy + γz + δ is a valid index. If (x, y, z) is inside the area, λ is actually index of the node at that position. But that position is non-unique; one step out of area usually gives you such an “alternative” position, for which λ is the same as for some node in area.

Comment (paramat) [reply src/mapgen/mapgen_v6.cpp]: Good point, thanks.
Due to the value of `max_spread_amount` the `// Move to side` check above isn't really needed, but i left it in to be safe, maybe i should remove it too. Will think on this further, however the PR is still good as it is.

Comment (paramat) [reply src/mapgen/mapgen_v6.cpp]: These 'area contains index' checks aren't very reliable then. Will reconsider, WIP.

Comment (paramat) [reply src/mapgen/mapgen_v6.cpp]: All attended to now.

**Comment by paramat** [comment]
Updated with thanks to NumberZero for highlighting some more issues.
Retested, latest screenshots in first post.

The 'index out of voxelmanip' checks were removed, firstly because they were unnecessary, secondly because they do not actually detect the corresponding position being out of the voxelmanip, they only check that the index value is between 0 and 112^3.

File: src/mapgen/mapgen_v6.cpp [hunk 4]
```diff
@@ -781,120 +783,106 @@ void MapgenV6::flowMud(s16 &mudflow_minpos, s16 &mudflow_maxpos)
...
-			}
 
-			const v3s16 &em = vm->m_area.getExtent();
-			u32 i = vm->m_area.index(p2d.X, node_max.Y, p2d.Y);
 			s16 y = node_max.Y;
 
 			while (y >= node_min.Y) {
+				for (;; y--) {
+					u32 i = vm->m_area.index(p2d.X, y, p2d.Y);
+					MapNode *n = NULL;
```
Comment (sfan5) [inline src/mapgen/mapgen_v6.cpp]: `nullptr`

File: src/mapgen/mapgen_v6.cpp [hunk 5]
```diff
@@ -781,120 +783,106 @@ void MapgenV6::flowMud(s16 &mudflow_minpos, s16 &mudflow_maxpos)
...
+						// to leave at least 1 node of mud.
+						{
+							u32 i2 = i;
+							VoxelArea::add_y(em, i2, -1);
+							MapNode *n2 = &vm->m_data[i2];
+							if (n2->getContent() != c_dirt &&
+									n2->getContent() != c_dirt_with_grass)
+								// Find next mud node in column
+								continue;
+						}
```
Comment (sfan5) [inline src/mapgen/mapgen_v6.cpp]: the scope ends here anyway, the `{ ... }` block isn't useful

File: src/mapgen/mapgen_v6.cpp [hunk 6]
```diff
@@ -781,120 +783,106 @@ void MapgenV6::flowMud(s16 &mudflow_minpos, s16 &mudflow_maxpos)
...
+					MapNode *n3 = &vm->m_data[i3];
+					if (ndef->get(*n3).walkable)
+						// Find next mud node in column
+						continue;
 
-				if (n->getContent() == c_dirt ||
-						n->getContent() == c_dirt_with_grass) {
-					// Make it exactly mud
-					n->setContent(c_dirt);
+					static const v3s16 dirs4[4] = {
```
Comment (sfan5) [inline src/mapgen/mapgen_v6.cpp]: move to function beginning?

Comment (paramat) [reply src/mapgen/mapgen_v6.cpp]: Yes will do.

**Comment by paramat** [comment]
Thanks will attend to all those.

**Comment by paramat** [comment]
Retested, test screenshot in first post.

**Comment by SmallJoker** [comment]
Why do you need the `for (;; y--)` loop? Both loops modify `y`, so this would be the equivalent:
```C++
	s16 y = node_max.Y + 1;

	while (y >= node_min.Y) {
		y--;
		u32 i = vm->m_area.index(p2d.X, y, p2d.Y);
		// ......
		if (foo)
			continue; //used to be break;
```

**Comment by paramat** [comment]
Indeed i suspect simplification can be done there, but i'm concerned this is intentional and necessary due to how y is modified inside the loop and due to the uses of 'break' and 'continue'. See https://github.com/minetest/minetest/issues/8784#issuecomment-522259758 and after.
Essentially i doubt my ability to be sure a simplified version would be identical.

**Comment by paramat** [comment]
I find it hard to be confident your suggestion would have identical behaviour. The uses of 'break' and 'continue', and the way y progresses down the column, make this tricky.
How it is doesn't seem harmful.
Please can we leave that to a future PR as i can't get my head around it?
