### PR TITLE
Work around #16221 by updating parent chains

### LINKED ISSUE #16221: Camera position flickering when attached to (some?) moving entity
### Luanti version

```true
(Custom version based on origin/master fde6384a099143a4a3033e090d61296b1d15f051 without any other client-side visual-related changes)
Luanti 5.13.0-1f616emo-f7d27a6e9 (Linux)
Using LuaJIT 2.1.1741730670
Built by GCC 15.1
Running on Linux/6.14.7 x86_64
BUILD_TYPE=RelWithDebInfo
RUN_IN_PLACE=1
USE_CURL=1
USE_GETTEXT=1
USE_SOUND=1
STATIC_SHAREDIR="."
STATIC_LOCALEDIR="locale"
```

### Operating system and version

Arch Linux

### CPU model

11th Gen Intel i5-11600K (12) @ 4.900GHz

### GPU model

NVIDIA GeForce GTX 1060 6GB

### Active renderer

4.6.0 / opengl / SDL 2.32.56

### Summary

This is a regression which, according to `git bisect` results, was introduced with fde6384a099143a4a3033e090d61296b1d15f051 (#15722).

When I am attached to an Advtrains wagon, and after it moves, my camera starts flickering until I leave the wagon.

[regression footage (JR E231 Series)](https://downloads-th2.1f616emo.xyz/tmp/Luanti-regression-15722-1.mp4)
[regression footage (Basic Subway Wagon)](https://downloads-th2.1f616emo.xyz/tmp/Luanti-regression-15722-3.mp4)

It can be seen that the camera position weirdly flickers, and it doesn't stop even if the entity halts.

Weirdly, this does not apply to carts. This might be related to the fact that Advtrains constantly updates entity position.

[a known bad commit with carts](https://downloads-th2.1f616emo.xyz/tmp/Luanti-regression-15722-2.mp4)

### Steps to reproduce

1. Get on a (specific type of?) moving entity
2. Observe the camera position and the visual results

### PR DESCRIPTION
**Pull request by appgurueu**
Closes #16221 as discussed.

### CODE REVIEW

File: src/client/content_cao.cpp [hunk 1]
```diff
@@ -343,13 +344,30 @@ bool GenericCAO::getSelectionBox(aabb3f *toset) const
 	return true;
 }
 
+void GenericCAO::updateParentChain() const
+{
+	if (!m_matrixnode)
```
Comment (appgurueu) [inline src/client/content_cao.cpp:349]: This is unnecessary at the moment but deliberate so this function makes sense.

In the future I plan to see whether I can selectively apply this at a couple (~3) locations to get the same effect without having to do this for all CAO::getPosition calls.

**Comment by lhofhansl** [comment]
I can confirm that the flickering and rubberbanding I have seen with Steampunk Blimp mod (and others) is gone.

File: src/client/content_cao.cpp [hunk 2]
```diff
@@ -343,13 +344,30 @@ bool GenericCAO::getSelectionBox(aabb3f *toset) const
...
 const v3f GenericCAO::getPosition() const
 {
 	if (!getParent())
 		return pos_translator.val_current;
 
 	// Calculate real position in world based on MatrixNode
 	if (m_matrixnode) {
+		// FIXME work around #16221 which is caused by the camera position and thus
+		// offset not being in sync with the player (parent) CAO position.
+		// A better solution might restrict this update to the local player only
```
Comment (lhofhansl) [inline src/client/content_cao.cpp:368]: If we can, it might be good to restrict to local player. But this works.

**Review by SmallJoker — APPROVED** [review]
Makes sense and looks good.
I did not test this, but https://github.com/luanti-org/luanti/issues/16221#issuecomment-3121057579 did, and the code is functionally identical.

File: src/client/content_cao.cpp (hunk 1 above)
Comment (SmallJoker) [reply src/client/content_cao.cpp:349]: ~~You could also start the `for` loop with `m_matrixnode->getParent()` to skip non-attached entities, but I don't think that would make any difference in terms of performance.~~ That would no longer update `m_matrix`, which is undesired.
