### PR TITLE
Raise MAX_REGISTERED_CONTENT

### LINKED ISSUE #6101: Do not use signed integer for registering nodes to allow more than 32768 registered nodes
This is kind of an edge case here.

I am the author of a mod that registers a lot of nodes due to what the mod is made for. It registers more nodes the more nodes are already registered when the mod loads. This means, that under some circumstances there could be more than 32768 registered nodes [which causes Minetest to crash](https://github.com/dsohler/xtend_modpack/issues/2) with the following message …

~~~~
2017-07-05 08:49:34: ERROR[Main]: ModError: Failed to load and run script from /home/alex/.minetest/mods/xtend/xfurniture/init.lua:
2017-07-05 08:49:34: ERROR[Main]: Number of registerable nodes (32768) exceeded (xfurniture:slab_half_node_moreblocks_trap_stone)
2017-07-05 08:49:34: ERROR[Main]: stack traceback:
2017-07-05 08:49:34: ERROR[Main]: [C]: in function 'register_item_raw'
2017-07-05 08:49:34: ERROR[Main]: /usr/share/minetest/builtin/game/register.lua:180: in function 'register_item'
2017-07-05 08:49:34: ERROR[Main]: /usr/share/minetest/builtin/game/register.lua:206: in function 'really_register_node'
~~~~

32768 is the maximum number of a signed integer in C. I suggest switching to `unsigned int` to allow 65536 nodes (or even better `long` for 42,949,672,96 possible nodes) to be registered.

### PR DESCRIPTION
**Pull request by sfan5**
this is now much safer after #16790

fixes #6101

## To do

This PR is a Ready for Review.

## How to test

```lua
for i = 1, 34210 do
	minetest.register_node("test2:dummy" .. i, {
		description = "dummy node " .. i,
		tiles = {"default_wood.png^[transformFY"},
		groups = {crumbly = 3},
	})
end
```

(the creative inventory will be kinda laggy and you also can't take items from the last few pages :thinking:)

### CODE REVIEW

File: src/script/lua_api/l_item.cpp [hunk 1]
```diff
@@ -613,26 +605,27 @@ int ModApiItem::l_register_item_raw(lua_State *L)
...
 
 		if (id > MAX_REGISTERED_CONTENT) {
-			throw LuaError("Number of registerable nodes ("
-					+ itos(MAX_REGISTERED_CONTENT+1)
-					+ ") exceeded (" + name + ")");
+			throw LuaError("Number of registerable nodes (about "
+					+ itos(MAX_REGISTERED_CONTENT)
+					+ ") exceeded: " + f.name);
 		}
+		sanity_check(id != CONTENT_IGNORE);
```
Comment (Desour) [inline src/script/lua_api/l_item.cpp]: LBMs can allocate node ids. And mods can call `register_node` with pcall. So it is possible that `ndef->set` returns `CONTENT_IGNORE` here.

Suggestion: Change `if` cond above to:
`if (id > MAX_REGISTERED_CONTENT || id == CONTENT_IGNORE) {`

**Review by Desour — COMMENTED** [review]
:+1: 

6.4k unknown nodes ought to be enough for anyone. -- Bill Gates
