### PR TITLE
Server-side authority for attached players

### LINKED ISSUE #10908: Anticheat misbehaving by resetting players location and viewdirection when attached to entity with move_to(pos, true) being called
##### Minetest version

```
Minetest 5.4.0-yl_0.1.2-40ad976-dirty (Linux)
Using Irrlicht 1.8.4
Using LuaJIT 2.1.0-beta3

--note that yl_0.1.2 indicates a version for YourLand game, but the 2 minor changes that it makes have nothing to do with the following bug report
```

##### Summary

AliasAlreadyTaken and I tested my Wormball minigame with 5.4 dev. It completely breaks the game. Wormball creates entities to attach players to. Then players are attached, and every 0.4 sec (in a globalstep) players are moved by moving the entity with `ent:move_to(pos,true)` Players' view direction is used to steer and determine which cardinal direction to move next. 

-BUG/antifeature-
5.4 differs from 5.3 in that when move_to is called on the entities, the players view direction is set to the entity's forward direction.

This completely breaks gameplay and makes Wormball annoying, confusing, and difficult to use.

note that mods, if they _wish_ to set players' view direction after a move_to(), are perfectly capable of doing so. However, there will be other applications like my Wormball minigame that doing this ruins the mod.

##### Steps to reproduce

to reproduce exactly, install arena_lib, signs_lib, and Wormball on a 5.4 and a 5.3 version. Set up arenas in both, and compare gameplay (or the lack thereof in 5.4)

For a simple test of the anti-feature, create a mod that attaches a player to an entity, then repeatedly call move_to(pos,true) on that entity with the player attached. While you are riding the entity, try to look around. Your view point will be repeatedly snapped back to the entity's forward direction.

https://content.minetest.net/packages/Zughy/arena_lib/
https://content.minetest.net/packages/VanessaE/signs_lib/
https://notabug.org/MisterE123/wormball

### PR DESCRIPTION
**Pull request by SmallJoker**
Supersedes #10928: simpler variant, without the interpolator class.
Fixes #10908

The server must have authority about attachments (see https://github.com/minetest/minetest/pull/10928#issuecomment-778676120). This PR ignores any player movement packets as long they're attached, and the client will no longer send them either (superfluous).

## To do

This PR is Ready for Review.

## How to test

1. Create a server
2. Check whether you can see other players moving
3. Place cart onto rail, attach
4. [this script](https://github.com/minetest/minetest/issues/10908#issuecomment-774481432)

The entity must still move normally without any interpolation/position reset glitches.

### CODE REVIEW

File: src/network/serverpackethandler.cpp [hunk 1]
```diff
@@ -460,6 +460,10 @@ void Server::process_PlayerPos(RemotePlayer *player, PlayerSAO *playersao,
 	if (pkt->getRemainingBytes() < 12 + 12 + 4 + 4 + 4 + 1 + 1)
 		return;
 
+	// Player position is defined by parent
+	if (playersao->isAttached())
```
Comment (sfan5) [inline src/network/serverpackethandler.cpp:464]: It's not that simple unfortunately.
the pitch, yaw, wanted_range and pressed keys should still be updated even when attached

File: src/server/player_sao.cpp [hunk 2]
```diff
@@ -574,28 +574,9 @@ bool PlayerSAO::checkMovementCheat()
...
 
-		if (diff > maxdiff * maxdiff) {
-			setBasePosition(parent_pos);
-			actionstream << "Server: " << m_player->getName()
-					<< " moved away from parent; diff=" << sqrtf(diff) / BS
-					<< " resetting position." << std::endl;
-			return true;
-		}
-		// Player movement is locked to the entity. Skip further checks
+	if (getParent()) {
```
Comment (sfan5) [inline src/server/player_sao.cpp:578]: This should be merged with the previous condition so that `m_last_good_position` is updated too

**Review by sfan5 — CHANGES_REQUESTED** [review]

File: src/server/player_sao.cpp (hunk 2 above)
Comment (sfan5) [reply src/server/player_sao.cpp:578]: It might also be better to have `FATAL_ERROR_IF(getParent(), "...")` since checkMovementCheat shouldn't run anyway when attached.

Comment (SmallJoker) [reply src/server/player_sao.cpp]: It should also not be run in singleplayer and when anticheat is disabled. I think these checks should belong into `checkMovementCheat` for consistency in case the function is called elsewhere too (code duplication).

File: src/network/serverpackethandler.cpp (hunk 1 above)
Comment (SmallJoker) [reply src/network/serverpackethandler.cpp]: Yes of course! PlayerPos sends more than the player position, and I should really have known that.

Comment (sfan5) [reply src/network/serverpackethandler.cpp]: Fully removing the check is a bad idea too, since that reintroduces the exploit.
`process_PlayerPos` should ignore the player position but process the rest when attached.

File: src/network/serverpackethandler.cpp [hunk 3]
```diff
@@ -488,8 +488,12 @@ void Server::process_PlayerPos(RemotePlayer *player, PlayerSAO *playersao,
...
-	player->setSpeed(speed);
+	if (!playersao->isAttached()) {
+		// Only update player positions when moving freely
+		// to not interfere with attachment handling
+		playersao->setBasePosition(position);
+		player->setSpeed(speed);
+	}
 	playersao->setLookPitch(pitch);
 	playersao->setPlayerYaw(yaw);
 	playersao->setFov(fov);
```
Comment (sfan5) [inline src/network/serverpackethandler.cpp:499]: the `if (playersao->checkMovementCheat()) {` down further too

Comment (SmallJoker) [reply src/network/serverpackethandler.cpp:499]: I'd like to keep this as-is in case the movement check is later used in another location.
https://github.com/minetest/minetest/pull/10952#discussion_r575823239

IMO deciding whether a check should performed is the task of the anticheat function, not its caller. At this point it's mainly a question about coding practices. I can adjust that if you insist.

Comment (sfan5) [reply src/network/serverpackethandler.cpp:499]: No that's fine.

**Review by sfan5 — APPROVED** [review]
Tested, works.

**Comment by lhofhansl** [comment]
Applied and tested. Works as advertised.

**Comment by TheTermos** [comment]
Congratulation guys, we seem to have fixed the eternal problem of 2nd level attachment player detaching.

```
on_rightclick = function(self,clicker)
	local pos = self.object:get_pos()
	local at1 = minetest.add_entity(pos,self.name)
	at1:set_attach(self.object,nil,{x=0,y=10,z=0})
	clicker: set_attach(at1,nil,{x=0,y=10,z=0})
	self.object:set_velocity({z=30.0,y=0,x=0.0})
end,
```

No detaching whatsoever.
Movement becomes jerky if velocity exceeds 35, but that's already faster than the mapgen can handle.
