### PR TITLE
Fix plantlike wield texture overlay no_texture.png

### LINKED ISSUE #16827: Default plantlike wield image is now `no_texture.png`
### Luanti version

```true
5.15.0-dev
```

### Operating system and version

GNU/Linux

### CPU model

Intel(R) Core(TM) i5-2500S (4) @ 3.70 GHz

### GPU model

AMD Radeon HD 6730M/6770M/7690M XT

### Active renderer

4.6 / opengl / SDL 2.32.60 (COMPAT)

### Summary

If you wield a plantlike node with `tiles` set, but no inventory and wield image, your wieldhand now shows the "no texture" dummy texture (`no_texture.png`) instead of a rendering of the plantlike node.

In previous version 5.14, such nodes rendered the first plant `tiles` texture by default when you wield it, so this is a regression.

### Steps to reproduce

1. Launch DevTest
2. Grab every available plantlike node in your inventory and wield them (try `testnodes:plantlike` first)

### PR DESCRIPTION
**Pull request by cx384**
Fixes #16827

## To do

Ready for Review.

## How to test

Get some plantlike drawtype nodes from devtest and look at the wield image.

### CODE REVIEW

File: src/client/wieldmesh.cpp [hunk 1]
```diff
@@ -121,7 +121,7 @@ static scene::IMesh *createExtrusionMesh(int resolution_x, int resolution_y)
 }
 
 static video::ITexture *extractTexture(const TileDef &def, const TileLayer &layer,
-	ITextureSource *tsrc)
+		ITextureSource *tsrc, bool overlay = false)
```
Comment (sfan5) [inline src/client/wieldmesh.cpp]: i this is is more accurately named `bool fallback = true`

Comment (sfan5) [reply src/client/wieldmesh.cpp]: I meant inverting the logic too: `fallback` = return no_texture.png as fallback; `!fallback` = return nullptr

Comment (cx384) [reply src/client/wieldmesh.cpp]: Oh right, sorry, should be fixed now.

**Review by sfan5 — APPROVED** [review]
lgtm
