### PR TITLE
Fix server-side formspec state keeping issue

### LINKED ISSUE #13331: Calling minetest.close_formspec(name, "") doesn't erase server's formspec state
##### Minetest version

```
5.6.1, 5.7.0-dev-38e0052
```

##### OS / Hardware

Operating system: N/A
CPU: N/A

GPU model: N/A
OpenGL version: N/A

##### Summary

If you call `minetest.close_formspec(player_name, "")`, the player will still be able to submit fields in the formspec they had open. I believe this is because the below code doesn't check for empty formnames.

https://github.com/minetest/minetest/blob/b7359f5fa93f531986c86b1ced20bb4584593b0a/src/server.cpp#L1545

##### Steps to reproduce

1. Open a formspec
2. Call `minetest.close_formspec(name, "")`
3. Use a modified client or something to send fields to the formspec. It's possible to do this with an unmodified client if you get the timing right, however I tested this by modifying clientpackethandler.cpp so that close formspec packets get ignored
4. Notice how the server still recieves the fields

If you close the formspec with its formname instead of `""` in step 2, the server will reject the form submission with a "possible exploitation attempt" warning.

I used this code with my [snippets](https://content.minetest.net/packages/luk3yx/snippets/) mod and a modified client to test this issue:

```lua
if not tmp then
    tmp = true
    minetest.register_on_player_receive_fields(function(player, formname, fields)
        minetest.chat_send_player(player:get_player_name(), ('Got form submission on %q: %s'):format(formname, dump(fields)))
    end)
end


minetest.show_formspec("singleplayer", "test", "size[3,3]button[0,0;3,1;test;Test button]")
minetest.after(3, function()
    minetest.close_formspec("singleplayer", "")
    minetest.chat_send_all("Form closed, try pressing the button")
end)
```

I may open a PR to fix this later since the fix seems trivial.

### PR DESCRIPTION
**Pull request by luk3yx**
Add compact, short information about your PR for easier understanding:

- Goal of the PR
Fix #13331
- How does the PR work?
By removing the player's entry from `m_formspec_state_data` when `minetest.close_formspec(name, "")` is called
- Does it resolve any reported issue?
#13331
- Does this relate to a goal in [the roadmap](../doc/direction.md)?
No

## To do

This PR is a Ready for Review.

## How to test

See #13331

### CODE REVIEW

File: src/server.cpp [hunk 1]
```diff
@@ -1542,7 +1542,8 @@ void Server::SendShowFormspecMessage(session_t peer_id, const std::string &forms
 		//the client should close the formspec
 		//but make sure there wasn't another one open in meantime
 		const auto it = m_formspec_state_data.find(peer_id);
-		if (it != m_formspec_state_data.end() && it->second == formname) {
+		if (it != m_formspec_state_data.end() &&
+				(it->second == formname || formname.empty())) {
```
Comment (Desour) [inline src/server.cpp:1546]: Please add a comment explaining why "" is special.

Comment (luk3yx) [reply src/server.cpp:1548]: Done

**Review by sfan5 — APPROVED** [review]

**Review by Desour — APPROVED** [review]
