### PR TITLE
Sanitize server IP field

### LINKED ISSUE #9168: Serverlist Does Not Sanitize favoriteservers.txt
##### Minetest version

```
5.1.0 (Flatpak)
```

##### OS / Hardware

Operating system: Fedora 31
CPU: Intel i5

##### Summary

If you enter certain characters into the Address input and attempt to connect, Minetest will add that "server" to the `favoriteservers.txt` file, notably `[` and `,`.

##### Steps to reproduce

1. Open Minetest
2. Go To The "Join Game" Tab
3. Enter any combination containing `[` or `,` and see the results.

With `,`:
Screenshot from 2019-12-05 18-01-59

With `[`:
Screenshot from 2019-12-05 18-02-36

### PR DESCRIPTION
**Pull request by Zughy**
Closes #9168 

## To do

This PR is Ready for Review.

## How to test

Write things like `[`, `;` or `,` in the IP field, in the multiplayer tab, and it shouldn't mess up the server list

### CODE REVIEW

File: builtin/mainmenu/common.lua [hunk 1]
```diff
@@ -87,7 +87,7 @@ function render_serverlist_row(spec, is_favorite)
 	if spec.name then
 		text = text .. core.formspec_escape(spec.name:trim())
 	elseif spec.address then
-		text = text .. spec.address:trim()
+		text = text .. core.formspec_escape(spec.address:trim())
 		if spec.port then
 			text = text .. ":" .. spec.port
```
Comment (sfan5) [inline builtin/mainmenu/common.lua:92]: is port parsed as int or does the same problem apply here?

Comment (Zughy) [reply builtin/mainmenu/common.lua:92]: I tried putting things like ; and [ but it doesn't seem to work
