### PR TITLE
Corrections to loops and BFS cullers

### LINKED ISSUE #13345: Consistent, extreme dtime jitter at high view ranges (BFS occlusion culler)
##### Minetest version

```
5.7.0-dev-9af587c54
```

##### OS / Hardware

Operating system: Linux debian 6.1.0-6-amd64 (Debian Unstable)
CPU: AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx (8) @ 2.100GHz

GPU model: (integrated in CPU) AMD ATI Radeon Vega Series / Radeon Vega Mobile Series
OpenGL version: 4.6

##### Summary

Note: 5.6.1 works smoothly as expected.

##### Steps to reproduce

1. Open any game, world, or server.
2. Observe lag. This happens even if you teleport far into the sky where no nodes or entities are visible.

### PR DESCRIPTION
**Pull request by x2048**
This adds corrections to #13352. Fixes #13345 in the short term.

Things done:
* Reset usage timers and improve reporting of statistics in the loops culler
* Correctly touch map blocks when using bfs culler
* Align use of variables between the two algorithms.

## To do

This PR is Ready for Review.

## How to test

1. Clear your settings.
2. Set `client_unload_unused_data_timeout = 6`
3. Start a world and fly around
4. Mapblocks behind your back must not be unloaded by the client (they are within range).
5. There must not be any flickering of the wield mesh as you move or stand still (this happens if the air block your are in is unloaded and reloaded by the client).
6. Run `/set occlusion_culler loops`
7. In the profile screen check that the counters for 'Mapblocks loaded' and 'Meshes in range' are non-zero.

### CODE REVIEW

File: src/client/clientmap.cpp [hunk 1]
```diff
@@ -630,23 +652,27 @@ void ClientMap::touchMapBlocks()
 		*/
 
 		for (MapBlock *block : sectorblocks) {
-			/*
-				Compare block position to camera position, skip
-				if not seen on display
-			*/
+			MapBlockMesh *mesh = block->mesh;
 
-			if (!block->mesh) {
```
Comment (lhofhansl) [inline src/client/clientmap.cpp:638]: This, and following changes are unrelated to bringing loops back.
Did you do a brief perf test on this? Might be quite more expensive.

Also, even with 1x1x1 mesh_chunks there are blocks without a mesh, I am not sure we want to reset the usage counters for those. And I mean I am really not sure one way or the other.

**Comment by lhofhansl** [comment]
Tested. Works. And with a low client unload timeout it also avoids the flickering from unloaded/re-creating the meshes (with larger than 1x1x1 meshed). Perf looks good too.

So +1

File: src/client/clientmap.cpp (hunk 1 above)
Comment (x2048) [reply src/client/clientmap.cpp:638]: I've noticed that with small values for client_unload_unused_data_timeout the wield mesh flickers when flying about ground without this patch. This is because the air block the player is in gets unloaded and replaced with 'ignore' blocks which do not store light. Keeping air blocks loaded in the client prevents this unloading cycle and makes the picture stable even when client is configured to unload blocks aggressively.
