### PR TITLE
Fix 'alpha' property for liquid nodes

### LINKED ISSUE #5769: Water translucency not affected by low values of nodedef 'alpha'
MT master with water nodedef alpha 0, 1, 63, 127 ...

screenshot_master0

screenshot_master1

screenshot_master63

screenshot_master127

Translucency does not visibly change.
Fixing PR is #5494

### PR DESCRIPTION
**Pull request by juhdanad**
Since #4986 the `alpha` property of liquids did not work correctly. This commit restores the old behavior: `alpha` overrides texture translucency.

Related: #5461.

EDIT by paramat: Fixes #5769

### CODE REVIEW

File: src/nodedef.cpp [hunk 1]
```diff
@@ -752,15 +750,15 @@ void ContentFeatures::updateTextures(ITextureSource *tsrc, IShaderSource *shdsrc
 	}
 
 	if (is_liquid) {
+		// Vertex alpha is no longer supported, correct if necessary.
+		correctAlpha(tdef, 6);
+		correctAlpha(tdef_spec, CF_SPECIAL_COUNT);
```
Comment (numberZero) [inline src/nodedef.cpp]: Why doing that for liquids only? Are they the only nodes which support the `alpha` parameter?

Comment (paramat) [inline src/nodedef.cpp]: Yes.

**Comment by juhdanad** [comment]
Rebased!

**Comment by paramat** [comment]
I can confirm the bug https://github.com/minetest/minetest/issues/5461#issuecomment-290889024

**Comment by paramat** [comment]
Testing ...
First master with alpha 0, 1, 63, 127 ...

screenshot_master0

screenshot_master1

screenshot_master63

screenshot_master127

Translucency does not visibly change.

Now this PR with alpha 0, 1, 63, 127

screenshot_pr0

screenshot_pr1

screenshot_pr63

screenshot_pr127

Note that it works for alpha >= 1, alpha = 0 seems to revert to texture's own alpha, perhaps it should actually be completely transparent?

File: src/nodedef.cpp [hunk 2]
```diff
@@ -469,21 +469,17 @@ void ContentFeatures::serialize(std::ostream &os, u16 protocol_version) const
 	writeU8(os, legacy_wallmounted);
 }
 
-void ContentFeatures::correctAlpha()
+void ContentFeatures::correctAlpha(TileDef *tiles, int length)
 {
 	if (alpha == 0 || alpha == 255)
```
Comment (paramat) [inline src/nodedef.cpp]: So maybe
`if (alpha == 255)`?

**Comment by paramat** [comment]
As far as i understand it, code seems ok (if the alpha = 0 thing is fixed).

File: src/nodedef.cpp (hunk 2 above)
Comment (paramat) [inline src/nodedef.cpp]: Yes my suggestion above works.

**Comment by paramat** [comment]
+1 if `if (alpha == 255)` is used @juhdanad

**Comment by juhdanad** [comment]
I will try to rebase next day, I have been really busy lately.

**Comment by juhdanad** [comment]
Rebased!

The `alpha == 0` check is intentional: `use_texture_alpha` sets alpha to 0 (see [there](https://github.com/minetest/minetest/blob/master/src/script/common/c_content.cpp#L500)). Without that, `use_texture_alpha` liquids would be invisible.

**Comment by paramat** [comment]
Ok.
