### PR TITLE
Touchscreen: Camera movement improvements

### LINKED ISSUE #11003: Move view angle while breaking or punching nodes
##### Minetest version

```
5.4.0
```

##### OS / Hardware

Operating system: android 7 Nougat
CPU: Samsung Exynos

GPU model:
OpenGL version:

##### Summary

I can't change the direction I look at while punching. I have to pick either punching or changing my viewpoint. I wish to do both

##### Steps to reproduce

1) Open the app and click on the world
2) Punch nothing
3) Use another finger to change viewpoint

### PR DESCRIPTION
**Pull request by grorp**
Fixes #11003.

On touchscreens, you can currently only move your camera while digging if `touch_use_crosshair = true` is set. This is an arbitrary and unnecessary limitation. The Android version of Minecraft doesn't have this issue. An example where it is especially annoying: If you're charging a bow in MineClone 2, you can't aim if you don't enable `touch_use_crosshair`.

This PR removes this limitation.

This PR also adjusts `touchscreen_sensitivity` to the display density to avoid too fast camera movement on high-DPI displays. The effective sensitivity stays the same for `xhdpi` displays, which is the most common density according to https://developer.android.com/about/dashboards/.

Additionally, this PR removes the visible camera jump when you cross the touchscreen_threshold.

## To do

This PR is a Ready for Review.

Looking for feedback from touchscreen players.

## How to test

Try moving the camera while digging (or aiming a bow in MineClone 2) with `touch_use_crosshair = false`.

### CODE REVIEW

File: src/gui/touchscreengui.cpp [hunk 1]
```diff
@@ -793,6 +793,7 @@ void TouchScreenGUI::translateEvent(const SEvent &event)
 		}
 
 		m_pointer_pos[event.TouchInput.ID] = touch_pos;
+		m_pointer_downpos[event.TouchInput.ID] = touch_pos;
```
Comment (srifqi) [inline src/gui/touchscreengui.cpp:796]: Can these lines be swapped? `m_pointer_downpos` is declared first in the header file.

**Review by srifqi — APPROVED** [review]
This PR looks good to me.

**Comment by grorp** [comment]
Rebased after #14389.

@srifqi Have you tested this as well? Especially the last commit makes a quite significant difference and I'd like to know what you think about it.

**Review by srifqi — APPROVED** [review]
The current state of this PR looks good to me. I can not feel any difference while testing, though.

**Comment by grorp** [comment]
I assume your approval applies even though you didn't add the "One approval" label?

I'd like this PR to get more testing before it's merged, but no players have shown interest in testing it for 1+ month. Merging it seems to be the only way for it to get more testing. If you didn't notice a difference, the changes may have less impact than I expected anyway.
