### PR TITLE
[no squash] Some fixes

### LINKED ISSUE #16554: Default nametag size is too small (when using `nametag_scale_z`)
### Luanti version

```true
5.14
```

### Operating system and version

Pop!_OS 22.04 LTS

### CPU model

i7 7700

### GPU model

_No response_

### Active renderer

_No response_

### Summary

Logged in on AES, `nametag_fontsize` is untouched. Compare the lecterns with the users (the latter has no scaling). 1920x1080, no system rescaling

Image

I'd like to underline that up close is good

Image

### Steps to reproduce

~~Log in on AES~~ [not necessary](https://github.com/luanti-org/luanti/issues/16554#issuecomment-3384635082), just have a look at the comments

### LINKED ISSUE #16989: Function to know whether a file is cached
### Problem

Calling `dynamic_add_media({filepath=somefile, to_player = p_name}, ..)` on a player who's already got the file cached triggers a warning in chat:
```
WARNING[Server]: Server::sendRequestedMedia(): Client has requested "test-audio-1.ogg" before, not sending it again.
```

Use case: online game with different maps, each one with its own BGM. When you enter a map for the first time, the associated BGM is downloaded (instead of downloading everything when logging in from a new device)

### Solutions

A function to check whether a file has already been cached for the given client would be great

### Alternatives

---

### Additional context

_No response_

### LINKED ISSUE #17002: Early `core.get_translated_string` call breaks server translation
### Luanti version

```true
Luanti 5.14.0 (Linux)
Using LuaJIT 2.1.1753364724
Built by GCC 15.2
Running on Linux/6.18.5 x86_64
BUILD_TYPE=Release
RUN_IN_PLACE=0
USE_CURL=1
USE_GETTEXT=1
USE_SOUND=1
STATIC_SHAREDIR="/usr/share/luanti"
STATIC_LOCALEDIR="/usr/share/locale"
```

### Operating system and version

Arch linux 6.18.5 x86_64

### CPU model

_No response_

### GPU model

_No response_

### Active renderer

_No response_

### Summary

If you try to get a translation (`core.get_translated_string`) of a string during server startup, the string will not be translated, and subsequent attempts to translate it on the server side will be useless.

[According to the luatic, the following happens](https://discord.com/channels/369122544273588224/369123175583186964/1479580393710682163):

> `fillMediaCache()` is called after `m_modmgr->loadMods(*m_script);`, `Server::getTranslationLanguage` is cached. the cache is initialized when `m_media` is still empty if you call it at load time.

### Steps to reproduce

Need to create a lua mod:
`init.lua:`
```lua
core.get_translated_string('ru', '')

core.register_chatcommand('get', {
	func = function(name, param)
		local s = core.translate('wood', 'gi_log-title')

		core.log(s)
		core.log(core.get_translated_string('ru', s))

		print(s)
		print(core.get_translated_string('ru', s))

		return true, ''
	end
})
```
Create a locale folder and add the Russian locale (note that the English locale will not work in any case #6503)
`wood.ru.po`:
```
msgctxt "wood"
msgid "gi_log-title"
msgstr "Бревно ги"
```
Don't forget to switch to the Russian locale (or to another one if you change lang_code)

Launch the server and enter the command `/get`:
Image
(we see that the first line was translated by the client, the second remained unchanged)

Modify the init.lua file (comment out the translation method call):
```lua
-- core.get_translated_string('ru', '')

core.register_chatcommand('get', {
	func = function(name, param)
		local s = core.translate('wood', 'gi_log-title')

		core.log(s)
		core.log(core.get_translated_string('ru', s))

		print(s)
		print(core.get_translated_string('ru', s))

		return true, ''
	end
})
```
Launch the server and enter the command `/get`:
Image
(we see that both lines were translated correctly)

### LINKED ISSUE #17012: Broken items with `on_drop` and `core.register_allow_player_inventory_action` with no taking allowed
### Luanti version

```true
5.15.1, 5.16.0-dev
```

### Operating system and version

Pop!_OS 24.04 LTS

### CPU model

_No response_

### GPU model

_No response_

### Active renderer

_No response_

### Summary

If I have a function that overwrites an itemstack, the overwrite doesn't really work if it's launched from the `on_drop` function of the item, with `register_allow_player_inventory_action` not allowing taking. It doesn't matter if the function is immediately called or if it's inside an after.

The original item disappears and it's overwritten by a ghost item: the engine thinks it's been correctly overwritten (`get_wielded_item()` returns the overwritten item), but the slot is empty, the hand rendered and the item can't be used. If you log out and log in again, the slot is cleared.

Ghost item aside, **I expect functions having the last saying over inventory actions**. In my use case, I have a shooter minigame in which pressing Q reloads the held weapon. Bullets are tracked via item metadata, so reloading means giving a new itemstack with the full magazine after reloading has ended.

### Steps to reproduce

Add the following code:
```lua
local ammo = 3
local is_reloading = false

local function reload(user, itemstack)
    is_reloading = true
    core.chat_send_all("Reloading")
    
    core.after(1, function()
        core.chat_send_all("Reloaded")
        ammo = 3
        is_reloading = false
        itemstack:get_meta():set_string("inventory_image", "server_favorite.png")
        itemstack:get_meta():set_string("wield_image", "server_favorite.png")
    	user:get_inventory():set_stack("main", 1, itemstack)
    	
    	core.chat_send_all("Item in hand = " .. itemstack:get_name())
    end)
end

core.register_node("test:node", {
    description = "Test node",
    wield_image = "server_favorite.png",
    inventory_image = "server_favorite.png",
    groups = {cracky = 3},

    on_use = function(itemstack, user, pointed_thing)
    	if not is_reloading and ammo > 0 then
    	   ammo = ammo -1
    	   core.chat_send_all("Ammo = " .. ammo)
    	   
    	   if ammo == 0 then
    	       core.after(0, function()
    	           itemstack:get_meta():set_string("inventory_image", "server_favorite.png^[hsl:0:-100")
    	           itemstack:get_meta():set_string("wield_image", "server_favorite.png^[hsl:0:-100")
    	           user:get_inventory():set_stack("main", 1, itemstack)
    	           reload(user, itemstack)
    	       end)
    	   end
    	end
    end,
    
    on_drop = function(itemstack, user, pos)
        if not is_reloading then
            reload(user, itemstack)
        end
    end,
})

core.register_allow_player_inventory_action(function(player, action, inventory, inventory_info)
    if action ~= "take" then return end
    
    core.chat_send_all("Action = take")
    if inventory_info.stack and inventory_info.stack:get_name() == "test:node" then return 0 end
end)


core.register_chatcommand("hand", {
	func = function(name)
		local player = core.get_player_by_name(name)
		return true, "Currently in your hand: " .. player:get_wielded_item():get_name()
	end
})
```

1. `/giveme test:node` and put it in your first slot
2. Click with it a few times (check chat): reload function is called, it ends, profit
3. Now, instead of emptying the magazine, press Q to call the reload function
4. Item is gone, kind of
5. To be sure it's not completely gone, call `/hand` to know what you're currently holding

### PR DESCRIPTION
**Pull request by sfan5**
A bug fix PR. It fixes bugs.

1&2: fixes #17012
3: fixes #17002
4: fixes #16554
5: fixes #16989

## To do

This PR is Ready for Review.

## How to test

code:
```lua
core.register_node("test2:node", {
	description = "Test Node",
	wield_image = "server_favorite.png",
	inventory_image = "server_favorite.png",
	groups = {cracky = 3},
	on_drop = function(itemstack, user, pos)
		core.chat_send_all("dropped: " .. itemstack:to_string())
		itemstack:get_meta():set_string("inventory_image", 
			string.format("server_favorite.png^[colorize:#%06x", math.random(0, 0xffffff)))
		return itemstack
	end,
})
core.register_allow_player_inventory_action(function(player, action, inventory, inventory_info)
    if action ~= "take" then return end
    if inventory_info.stack and inventory_info.stack:get_name() == "test2:node" then return 0 end
end)
core.register_on_player_inventory_action(function(player, action, inventory, inventory_info)
	if action == "take" then core.chat_send_all("taken: " .. inventory_info.stack:to_string()) end
end)

core.register_chatcommand("asdf", {
	func = function(name, param)
		core.chat_send_player(name, "Loading")
		local p = {filepath = core.get_worldpath() .. "/5mb_big.obj", to_player = name}
		core.dynamic_add_media(p, function(name) core.chat_send_player(name, "Loaded 1") end)
		core.dynamic_add_media(p, function(name) core.chat_send_player(name, "Loaded 2") end)
		return true
	end
})
```

1. dropping the item should not show `dropped: `
2. get rid of `register_allow_player_inventory_action`. dropping the item should cause it to change color
3. see #17002
4. apply eyes to nametag
5. run `/asdf`, it should load twice and show no warning at the client *or* server (make sure file is not in cache already)

### CODE REVIEW

File: src/server.cpp [hunk 1]
```diff
@@ -2675,6 +2675,11 @@ bool Server::addMediaFile(const std::string &filename,
 	verbosestream << "Server: " << sha1_hex << " is " << filename
 			<< " (" << (filedata.size() >> 10) << "KiB)" << std::endl;
 
+	// Invalidate cached translations if we just added a translation file
+	if (Translations::isTranslationFile(filename)) {
+		server_translations.clear();
```
Comment (SmallJoker) [inline src/server.cpp:2681]: Could be done more precisely only on the language:
```C++
auto it = server_translations.find(Translations::getFileLanguage(filename));
if (it != server_translations.end())
	server_translations.erase(it);
```

However, I'd rather have the comment above say something like
```
// Invalidate cached translations if we just added a translation file
// If really needed, this could be optimized but performance is not critical in this case.
```

File: src/client/client.cpp [hunk 2]
```diff
@@ -752,23 +752,25 @@ void Client::step(float dtime)
...
 			}
-
-			if (done.size() == 255) { // maximum in one packet
-				sendHaveMedia(done);
-				done.clear();
+		}
+		while (!done.empty()) {
+			// this looks stupid, but is a simple and correct way to chunk them
+			std::vector<u32> part;
+			while (!done.empty() && part.size() < 255) {
```
Comment (SmallJoker) [inline src/client/client.cpp:768]: This changes FIFO to FILO. Late requests are processed first. This is however not an issue, right?

**Comment by j-r** [comment]
FWIW, the `on_drop` changes are LGTM, but I think it'd be better to just disallow changing the item and/or increasing the count, at least for now. That opens the door for changing the order as @SmallJoker suggested and perhaps do onPut handling for the new items, or something like that. The behavior implemented here isn't worse than before, but it still is not really logical to e.g. allowing to drop a partial stack and then morph it  into something totally different, and I think it'd be better if mods don't start to use that.

File: src/client/client.cpp (hunk 2 above)
Comment (sfan5) [reply src/client/client.cpp:768]: No order guarantees.

**Comment by NathanSalapat** [comment]
I think this broke dropping items. If you have a stack and try and drop a single node with Shift+Q it drops the entire stack, and when you pick it up it's only a single item. Dropping with Q drops the entire stack and when you pick it back up it's all the items it should be.

**Comment by SmallJoker** [comment]
Can confirm. Shift+Q removes the stack from the inventory and drops an itemstack of size 1. Regression.
