### PR TITLE
Fix Inventory::moveItemSomewhere()

### LINKED ISSUE #7761: Minetest crashes when shift clicking on an item in the 3x3 crafting space (Flatpak, Fedora 30)
##### Issue type
 - Bug report

 
##### Minetest version

```
0.4.17.1
```

##### OS / Hardware
Operating system: Fedora 28

##### Summary
When I shift click on any item that is in the 3x3 craft space of the inventory minetest crashes with this message:
```
/usr/include/c++/8/bits/stl_vector.h:932: std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::operator[](std::vector<_Tp, _Alloc>::size_type) [with _Tp = ItemStack; _Alloc = std::allocator<ItemStack>; std::vector<_Tp, _Alloc>::reference = ItemStack&; std::vector<_Tp, _Alloc>::size_type = long unsigned int]: Assertion '__builtin_expect(__n < this->size(), true)' failed.
Aborted (core dumped)
```

##### Steps to reproduce
Shift click on any item that is in the 3x3 craft space of the inventory.

### PR DESCRIPTION
**Pull request by sfan5**
fixes #7761
If the destination inventory had 20 slots, the code would check which of the 20 slots in the <b>source</b> inventory were empty. The thing it intended to do is already covered by `addItem`, so just use that.

## To do

This PR is Ready for Review.

### CODE REVIEW

File: src/inventory.cpp [hunk 1]
```diff
@@ -713,27 +713,13 @@ void InventoryList::moveItemSomewhere(u32 i, InventoryList *dest, u32 count)
...
-	u32 dest_size = dest->getSize();
-	// First try all the non-empty slots
-	for (u32 dest_i = 0; dest_i < dest_size; dest_i++) {
-		if (!m_items[dest_i].empty()) {
-			item1 = dest->addItem(dest_i, item1);
-			if (item1.empty()) return;
-		}
-	}
+	ItemStack leftover;
+	leftover = dest->addItem(item1);
```
Comment (SmallJoker) [inline src/inventory.cpp]: Could be simplified to `ItemStack leftover = dest->addItem(item1);`
