### PR TITLE
Use legacy image implementation when not using 9-slice image

### LINKED ISSUE #12581: Inventory slots in Repixture look different in 5.6.0-dev (with gui_scaling_filter = true)
##### Minetest version
```
2cf52642fa89a9497b0200f5a4637a25a82f9c3d
```

This is 5.6.0-dev.

##### Summary

The inventory slots of Repixture 3.3.0 look a bit different after the update to Minetest 5.6.0-dev.

https://www.satoshiupload.com/images/Gz2DFb16jW.png

The correct way for the slots to look is without that thin extra border. In the -dev version, a slight "border" suddenly appeared, which looks mildly irritating, and I want to get rid of it, and I don't know how. Either way, this seems like a regression.

This screenshot was taken in Minetest 5.5.0 and 5.6.0-dev, playing Repixture 3.3.0, respectively. The left one is the behavior I want, the right one shows the undesirable behavior. Both screenshots were taken at a window size of 2560×1389 (excluding window decorations).

##### Steps to reproduce

1. Open the inventory in each of the 2 Minetest versions
2. Compare

### PR DESCRIPTION
**Pull request by x2048**
Fixes #12581

## To do

This PR is Ready for Review.

## How to test

1. Set `gui_scaling_filter = true`
2. Start Repixture game
3. Open inventory
4. Notice that inventory slots do not have dark border (see #12581).

### CODE REVIEW

File: src/gui/guiFormSpecMenu.cpp [hunk 1]
```diff
@@ -825,12 +825,23 @@ void GUIFormSpecMenu::parseImage(parserData* data, const std::string &element)
...
 		parseMiddleRect(parts[3], &middle);
-
-	GUIAnimatedImage *e = new GUIAnimatedImage(Environment, data->current_parent,
-		spec.fid, rect);
-
-	e->setTexture(texture);
-	e->setMiddleRect(middle);
+	
+	gui::IGUIElement *e;
+	if (middle.getArea() > 0) {
```
Comment (sfan5) [inline src/gui/guiFormSpecMenu.cpp:830]: would be good to add a comment to indicate this is a bug workaround and not just "normally there"

**Comment by SmallJoker** [comment]
This could also be fixed the other way around: by specifying whether or not to scale&filter GUIAnimatedImage:
```diff
diff --git a/src/gui/guiAnimatedImage.cpp b/src/gui/guiAnimatedImage.cpp
index 890763e71..d68009085 100644
--- a/src/gui/guiAnimatedImage.cpp
+++ b/src/gui/guiAnimatedImage.cpp
@@ -36,8 +36,12 @@ void GUIAnimatedImage::draw()
 	if (m_middle.getArea() == 0) {
 		const video::SColor color(255, 255, 255, 255);
 		const video::SColor colors[] = {color, color, color, color};
-		draw2DImageFilterScaled(driver, m_texture, AbsoluteRect, rect, cliprect,
-			colors, true);
+		if (m_scale_image) {
+			driver->draw2DImage(m_texture, AbsoluteRect, rect, cliprect, colors, true);
+		} else {
+			draw2DImageFilterScaled(driver, m_texture, AbsoluteRect, rect, cliprect,
+				colors, true);
+		}
 	} else {
 		draw2DImage9Slice(driver, m_texture, AbsoluteRect, rect, m_middle, cliprect);
 	}
diff --git a/src/gui/guiAnimatedImage.h b/src/gui/guiAnimatedImage.h
index 885aedece..d66a4cca1 100644
--- a/src/gui/guiAnimatedImage.h
+++ b/src/gui/guiAnimatedImage.h
@@ -16,6 +16,8 @@ class GUIAnimatedImage : public gui::IGUIElement {
 	void setTexture(video::ITexture *texture) { m_texture = texture; };
 	video::ITexture *getTexture() const { return m_texture; };
 
+	void setScaleImage(bool do_scale) { m_scale_image = do_scale; }
+
 	void setMiddleRect(const core::rect<s32> &middle) { m_middle = middle; };
 	core::rect<s32> getMiddleRect() const { return m_middle; };
 
@@ -30,6 +32,7 @@ class GUIAnimatedImage : public gui::IGUIElement {
 
 private:
 	video::ITexture *m_texture = nullptr;
+	bool m_scale_image = false;
 
 	u64 m_global_time = 0;
 	s32 m_frame_idx = 0;
diff --git a/src/gui/guiFormSpecMenu.cpp b/src/gui/guiFormSpecMenu.cpp
index a635cda48..ca026aca5 100644
--- a/src/gui/guiFormSpecMenu.cpp
+++ b/src/gui/guiFormSpecMenu.cpp
@@ -831,6 +831,7 @@ void GUIFormSpecMenu::parseImage(parserData* data, const std::string &element)
 
 	e->setTexture(texture);
 	e->setMiddleRect(middle);
+	e->setScaleImage(middle.getArea() == 0);
 
 	auto style = getDefaultStyleForElement("image", spec.fname);
 	e->setNotClipped(style.getBool(StyleSpec::NOCLIP, m_formspec_version < 3));

```

File: src/gui/guiFormSpecMenu.cpp (hunk 1 above)
Comment (x2048) [reply src/gui/guiFormSpecMenu.cpp:834]: Added an explanation.

**Review by sfan5 — APPROVED** [review]
LGTM (not tested)
