### PR TITLE
Map download: Escape ':' to '_'

### LINKED ISSUE #9215: World saving database path must escape/replace IPv6 address colons on Windows
##### Minetest 5.1.0

```
2019-12-18 02:09:30: INFO[Main]: Connecting to server at [2001:db8::1]:30000
2019-12-18 02:09:30: INFO[Main]: Database_SQLite3: Failed to create directory "C:\Games\minetest\bin\..\worlds\server_[2001:db8::1]_30000"
```

##### OS / Hardware

Operating system: Windows (doesn't matter which version)

##### Summary

Due to limitations in Windows path supported chars, colon (`:`) is prohobited for usage, its used only in disk selection (ex. `C:\`).
Such symbols must be replaced.

##### Steps to reproduce

Connect to server directly via IPv6 address when `enable_local_map_saving` option is enabled on Windows.

### PR DESCRIPTION
**Pull request by Montandalar**
Add compact, short information about your PR for easier understanding:

Under windows, clients that direct connect to a server by its IPv6 address and have map saving enabling crash upon trying to create the save directory, which will contain ':' (a disallowed character on Windows).

This PR resolves #9215 

Starting from now, any new map saves on all platforms will replace ':' in the hostname with '_'. To preserve backwards compatibility with any IPv6 worlds made on systems that *do* support ':' in filenames, the presence of a directory with the un-escaped hostname is first checked before trying to escape.

This PR is Ready for Review.

## How to test
* Connect to a server by IPv6 e.g. LinuxWorks Next Generation 2a03:4000:35:2c0::1, in the follow cases:
* With a Windows system
* With a linux system before and after compiling this branch, to make sure the old save is loaded instead
* With a linux system after compiling this branch and without any map save for the server.

### CODE REVIEW

File: src/client/client.cpp [hunk 1]
```diff
@@ -782,11 +782,20 @@ void Client::initLocalMapSaving(const Address &address,
 		return;
 	}
 
-	const std::string world_path = porting::path_user
-		+ DIR_DELIM + "worlds"
-		+ DIR_DELIM + "server_"
+	std::string world_path;
+#define set_world_path(hostname) \
+	world_path = porting::path_user \
```
Comment (SmallJoker) [inline src/client/client.cpp]: FYI: This would be more like C++:
```C++
auto set_world_path = [&] (const std::string &hostname) {
	world_path = porting::path_user +
		DIR_DELIM + "worlds" +
		DIR_DELIM + "server_" +
		hostname + "_" + std::to_string(address.getPort());
};
```

Comment (Montandalar) [reply src/client/client.cpp]: Ah, I am new to C++ from C, thanks for that.

File: src/client/client.cpp [hunk 2]
```diff
@@ -782,11 +782,20 @@ void Client::initLocalMapSaving(const Address &address,
...
+		+ DIR_DELIM + "worlds" \
+		+ DIR_DELIM + "server_" \
 		+ hostname + "_" + std::to_string(address.getPort());
 
+	set_world_path(hostname);
+	if (!fs::IsDir(world_path)) {
+		std::string hostname_escaped = hostname;
+		str_replace(hostname_escaped, ':', '_');
```
Comment (sfan5) [inline src/client/client.cpp]: why not just unconditionally escape?
or put the code that escapes inside an `#ifdef _WIN32`?

Comment (SmallJoker) [reply src/client/client.cpp]: `:` cannot be used in general on FAT16, FAT32 and NTFS filesystems.

Comment (sfan5) [reply src/client/client.cpp]: That's mostly a Windows limitation, you can create such directories or files from Linux.

Comment (SmallJoker) [reply src/client/client.cpp]: Meanwhile on Ubuntu + USB flash drive:
```
$ sudo file -s /dev/sdf
/dev/sdf: DOS/MBR boot sector, code offset 0x58+2, OEM-ID "MSDOS5.0", <snip>, sectors 4142080 (volumes > 32 MB), FAT (32 bit), sectors/FAT 4038, reserved 0x1, <snip>, unlabeled
$ LANG=en touch "te:st.txt"
touch: setting times of 'te:st.txt': No such file or directory
```

Comment (rubenwardy) [reply src/client/client.cpp]: This should be replaced on all programs, using such characters causes portability problems

Comment (Montandalar) [reply src/client/client.cpp]: I tossed up whether to replace globally or only on Windows and I decided that other OS users will still have issues from (as mentioned): FAT filesystems, etc. The escape is left conditional only to support existing linux world downloads.
